openapi: 3.0.0
info:
  title: Giraffe Ground Station
  description: Giraffe Ground Station API
  version: 0.5.0

paths:
  /api/status:
    get:
      description: Used to test your connection with the GGS server and to get the current status of it's resources.
      responses:
        200:
          description: OK - Connection successful. The response body will always be the same and can be used to verify communication with the correct server.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ggs:
                    $ref: '#/components/schemas/EntityStatus'
                  gfs:
                    $ref: '#/components/schemas/EntityStatus'
                  influx_db:
                    $ref: '#/components/schemas/EntityStatus'
                  telemetry:
                    $ref: '#/components/schemas/EntityStatus'

  /api/static/{file}:
    get:
      description: Get a static file from the server. Used for documentation.
      parameters:
      - in: path
        name: file
        schema:
          type: string
        required: true
        description: The file to get
      responses:
        200:
          description: OK - The file was found and returned
          content:
            text/html:
              schema:
                type: string
                format: binary
                example: This is a documentation file.

  /api/{resource}/settings:
    parameters:
      - $ref: '#/components/parameters/Resource'
      - $ref: '#/components/parameters/Category'

    get:
      description: Get the current settings and metadata related to the settings
      parameters:
        - in: query
          name: include
          schema:
            type: string
            enum: [values, metadata, all]
            default: all
          description: The data to return in the response. 'values' returns the current values, 'metadata' returns metadata about the setting, 'all' returns both.
      responses:
        200:
          description: OK - The settings were found and returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSettingsResponse'
        400:
          description: Bad Request - Query parameters were invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          description: Internal server error - could be related to there being no connection to the flight computer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      description: Set new values for the settings
      parameters:
        - $ref: '#/components/parameters/Resource'
      requestBody:
        description: The new values for the settings in the resource/category that you want to set.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutSettingValues'
      responses:
        200:
          description: OK - The new settings have been set
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        202:
          description: Accepted - The new settings have been received and will be set. This will happen when the settings need to be set on the flight computer.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        400:
          description: Bad Request - The request was not formatted correctly
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: Setting category not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        503:
          description: Service Unavailable - The settings could not be set. This will happen if the flight software is not connected with the ground station.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      description: Delete the settings in the resource/category and reset them to their default values
      responses:
        200:
          description: OK - The settings have been reset
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        400:
          description: Bad Request - The request was not formatted correctly
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          $ref: '#/components/responses/NotFound'

  /api/{resource}/data:
    parameters:
      - $ref: '#/components/parameters/Resource'
      - $ref: '#/components/parameters/DataCategory'
    get:
      description: Used to get data from the ground station, including telemetry and fligth software data

components:
  responses:
    NotFound:
      description: The requested resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    BadRequest:
      description: The request was not formatted correctly
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  parameters:
    Resource:
      in: path
      name: resource
      schema:
        type: string
        enum: [ggs, gfs]
      description: Specify between the ground station and the flight computer
      required: true

    Category:
      in: query
      name: category
      schema:
        type: string
        enum: [gfs_connection, influx_db]
      description: >
          - `gfs_connection` - ggs - The connection settings for the flight computer

          - `influx_db` - ggs - The connection settings for the influx database

          - `ggs_telemetry` - ggs - The telemetry settings for the ground station
      required: true

    DataCategory:
      in: query
      name: category
      schema:
        type: string
        enum: [critical, position, status, errors, logs]
      description: >
          - `critical` - gfs - Critical data from the flight computer

          - `position` - gfs - Position data (GPS, IMU) from the flight computer

          - `status_system` - gfs

          - `status_general` - gfs

          - `status_modules` - gfs

          - `status_extensions` - gfs

          - `status_datastream` - gfs

          - `status_telemetry` - gfs

          - `status_datalog` - gfs

          - `errors` - gfs - Error data from the flight computer
      required: true

  schemas:
    EntityStatus:
      type: string
      enum: [connected, disconnected]

    GetSettingsResponse:
      type: object
      properties:
        metadata:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/SettingMetaData'
        values:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/SettingValue'
      example:
        metadata:
          gfs_server_address:
            type: string
            name: GFS Server Address
            description: The address of the GFS server
            default: localhost
          gfs_server_port:
            type: integer
            name: GFS Server Port
            description: The port of the GFS server
            default: 5000
            min: 0
            max: 65535
        values:
          gfs_server_address: localhost
          gfs_server_port: 5000



    SettingMetaData:
      type: object
      properties:
        "type":
          type: string
          enum: ["int", "float", "bool", "enum", "string"]
          description: The data type of the setting
          example: "string"
        name:
          type: string
          description: Human readable name of the setting
          example: "GFS Server Address"
        description:
          type: string
          description: Human readable name of the string
        default:
          oneOf:
          - type: string
          - type: integer
          - type: number
          description: The default value of this setting, in it's appropriate type.
        max:
          type: integer
          description: This will only be included with integer, float, and string type. This is either the maximum number of characters, or the maximum value.
        min:
          type: integer
          description: This will only be included with integer, float, and string type. This is either the minimum number of characters, or the minimum value.
        true_state:
          type: string
          description: This is a semantic item that is included with boolean type settings.
          example: "enabled"
        false_state:
          type: string
          description: This is a semantic item that is included with boolean type settings.
          example: "disconnected"
      required:
        - type
        - name
        - description
        - default

    SettingValue:
      properties:
        value:
          oneOf:
          - type: string
          - type: integer
          - type: number
          - type: boolean
          description: The current value of the setting, in it's appropriate type.
      example:
        value: "t"

    PutSettingValues:
      type: object
      additionalProperties:
        oneOf:
        - type: string
        - type: integer
        - type: number
        - type: boolean
      example:
        gfs_server_address: "192.168.0.2"
        gfs_server_port: "8123"

    SuccessResponse:
      type: object
      properties:
        message:
          type: string
          description: A human readable success message
          example: "Info message"

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: A human readable error message
          example: "Error message"