@startuml

title GDL Session Layer State Machine

left to right direction

state Connected

state Disconnected {
  state WaitForSyn
  state SynSent : Await SynAck response
  state SynAckSent : Await Ack response

  [*] --> WaitForSyn

  ' If we are the initiator
  WaitForSyn -[#red]-> SynSent : T/O
  SynSent -[#red]-> WaitForSyn : T/O
  SynSent -[#green]-> Connected : SYN-ACK received

  ' If we are the responder
  WaitForSyn -[#green]-> SynAckSent : SYN received
  SynAckSent -[#red]-> WaitForSyn : T/O
  SynAckSent -[#green]-> Connected : ACK received
}

Connected -[#red]-> Disconnected : T/O

@enduml