Giraffe: modules::DataModule Class Reference
modules::DataModule Class Reference
A major module of the Giraffe Flight System that handles data flow through the system.
#include <data_module.hpp>
Public Member Functions
DataModule (data::SharedData &shared_data, cfg::Configuration &configuration)
Constructor for the data module.
~DataModule () override=default
bool addCommand (const cmd::Command &command)
Public wrapper for adding a command to the command queue.
node::Status getStatus () const
Returns the status of the module.
void start ()
Starts a thread to run the module.
void stop ()
Stops the module by setting the stop flag to true and joining the runner thread.
Protected Member Functions
template<typename T >
void data (data::DataId identifier, T value, int precision=2)
Used internally in the module. This function adds a data to the data stream.
void debug (std::string info)
void error (DiagnosticId log_id, int info)
Same as the other error function, but takes an int instead of a string.
void error (DiagnosticId, std::string info="")
Used internally in the module. This function adds an error to the log stream. It is used to log errors that occur in the module.
void info (std::string info="")
Used internally in the module. This function adds a info message to the log stream.
void setStatus (const node::Status status)
void sleep ()
Sleeps the module for the sleep interval.
bool stopRequested () const
Returns true if the stop flag is set to true.
virtual void updateLocalConfig ()
Protected Attributes
cfg::Configuration & configuration_
modules::MetaData metadata_
data::SharedData & shared_data_
Private Member Functions
void calculateCalculatedData ()
Use existing data to calculate the data that can be calculated.
void loop () override
Loop override for the data module.
void parseCameraNewImageDataPacket (const data::DataPacket &packet)
Process a data packet with ID data::DataId::CAMERA_newImagePath.
void parseExtensionDataPacket (const data::DataPacket &packet)
Parses all data from extensions and updates the data frame.
void parseGeneralDataPacket (const data::DataPacket &packet)
void parseStatusDataPacket (const data::DataPacket &packet)
Parses the status of modules and updates the data block.
void processAllStreams ()
Processes all of the data streams and updates the data block that contains the stream stats.
void processCommand (const cmd::Command &)
Used to process and commands sent to the data module.
void processDataPacket (const data::DataPacket &packet)
void processGpsFramePacket (const data::GpsFramePacket &packet)
Process all packets from the GPSFrame stream.
void processImuFramePacket (const data::ImuFramePacket &packet)
Process all packets from the IMUFrame stream.
void processLogPacket (const data::LogPacket &packet)
Process all packets from the log stream.
template<typename T >
void processStream (data::Stream< T > &stream, data::blocks::StreamsStats::StreamStats &stats, std::function< void(const T &)> parse_function)
Used to process shared streams.
void runner ()
This is the main function for each module.
void shutdown () override
Shutdown override for the data module.
void startup () override
Startup override for the data module.
Private Attributes
bst::RollingAverage average_horizontal_speed_ {20}
Rolling average of the horizontal speed. Once every 15 seconds (20 in a 5 minute span)
bst::Timer average_speed_timer_ {15 * 1000}
bst::RollingAverage average_vertical_speed_ {20}
data::blocks::CalculatedData calculated_data_ {}
Buffer for the calculated data. Used by the calculateCalculatedData method.
cmd::CommandQueue command_queue_
The command queue for the module.
bool console_module_enabled_ = false
User to determine if shared 'log_container' needs to be updated so the console module can print the log.
bool data_file_enabled_ = false
True if data file logging is enabled.
cfg::gEnum::LogStrategy data_file_logging_strategy_
The current data file logging strategy.
data_middleware::DataLog data_log_
The data log object, used to log data and errors to files.
double distance_traveled_ = 0.0
The distance traveled in km.
cfg::gEnum::ErrorLogStrategy error_file_logging_strategy_
The current error file logging strategy.
data_middleware::FileSystemManager file_system_
Used to manage the file system/data files.
bst::Timer gps_distance_update_timer_ {}
This timer is used to determine when to update the gps path for the purpose of calculating distance traveled.
data_middleware::InfluxDb influxdb_
Used to access the influxdb database.
bool influxdb_enabled_ = false
True if influxdb logging is enabled.
int influxdb_write_rate_ms_ = 1000
bst::geo::Point last_gps_point_ {}
The last gps point. Used to calculate distance traveled.
bst::geo::Point launch_gps_point_ {}
The initial gps point. This is the "launch point".
bool launch_gps_point_set_ = false
True if the initial gps point has been set.
bool log_file_enabled_ = false
True if error file logging is enabled.
std::thread runner_thread_
The thread that runs runner().
std::atomic< node::Status > status_ = node::Status::UNKNOWN
The status of the module.
std::atomic< bool > stop_flag_ = true
The stop flag is used to stop the module.
Detailed Description
A major module of the Giraffe Flight System that handles data flow through the system.
Constructor & Destructor Documentation
DataModule()
modules::DataModule::DataModule (data::SharedData & shared_data, cfg::Configuration & configuration)
Constructor for the data module.
Parameters
shared_data - System wide shared data object.
configuration - System wide configuration object.
References modules::Module::configuration_, and modules::Module::error().
~DataModule()
modules::DataModule::~DataModule () override default
Member Function Documentation
startup()
void modules::DataModule::startup () override private virtual
Startup override for the data module.
Currently doesn't do anything unique.
Todo:
why the call to sleep()?
Reimplemented from modules::Module.
loop()
void modules::DataModule::loop () override private virtual
Loop override for the data module.
Calls all stream parsing, file/db logging functions.
Reimplemented from modules::Module.
shutdown()
void modules::DataModule::shutdown () override private virtual
Shutdown override for the data module.
As this is one of the last modules to shutdown, it will do a final call to parsing functions.
Reimplemented from modules::Module.
processCommand()
void modules::DataModule::processCommand (const cmd::Command & command) private virtual
Used to process and commands sent to the data module.
Todo:
This function is not implemented yet.
Todo:
Test this, this could end poorly
Reimplemented from modules::Module.
References cmd::Command::command_id, and cmd::Command::int_arg.
processStream()
template<typename T > void modules::DataModule::processStream (data::Stream< T > & stream, data::blocks::StreamsStats::StreamStats & stats, std::function< void(const T &)> parse_function) inline private
Used to process shared streams.
This function will process all packets in a stream and update the streams stats. If data packets are added to the stream while this function is running, they will be processed on the next call.
Template Parameters
T - The type of stream packet.
Parameters
stream - The stream to process.
stats - The stream stats to update
parse_function - The function to call on each packet.
References data::blocks::StreamsStats::StreamStats::current_packets, data::Stream< T >::getNumPackets(), data::Stream< T >::getPacket(), data::Stream< T >::getTotalPackets(), data::blocks::StreamsStats::StreamStats::processing_delay_ms, and data::blocks::StreamsStats::StreamStats::total_packets.
processAllStreams()
void modules::DataModule::processAllStreams () private
Processes all of the data streams and updates the data block that contains the stream stats.
References processDataPacket(), processGpsFramePacket(), processImuFramePacket(), and processLogPacket().
processLogPacket()
void modules::DataModule::processLogPacket (const data::LogPacket & packet) private
Process all packets from the log stream.
Todo:
debug/log packets should be processed here
References data::LogPacket::ERROR, data::LogPacket::level, and util::to_string().
Referenced by processAllStreams().
processGpsFramePacket()
void modules::DataModule::processGpsFramePacket (const data::GpsFramePacket & packet) private
Process all packets from the GPSFrame stream.
References data::blocks::LocationData::current_gps_fix, data::GpsFrame::fix, data::GpsFramePacket::frame, data::blocks::LocationData::have_gps_source, data::isGpsFrameValid(), data::blocks::LocationData::last_gps_frame, data::blocks::LocationData::last_valid_gps_fix, and data::blocks::LocationData::last_valid_gps_frame.
Referenced by processAllStreams().
processImuFramePacket()
void modules::DataModule::processImuFramePacket (const data::ImuFramePacket & packet) private
Process all packets from the IMUFrame stream.
References data::ImuFramePacket::frame, and data::isImuFrameValid().
Referenced by processAllStreams().
calculateCalculatedData()
void modules::DataModule::calculateCalculatedData () private
Use existing data to calculate the data that can be calculated.
Todo:
This function is not implemented yet.
The distance that must be traveled for the distance traveled to be updated.
Todo:
Report the launch position as a data point
Todo:
Report this error
Todo:
Report this error
Todo:
put this on a timer instead. Otherwise it will be reported as invalid if there is a single invalid gps frame. Reset the timer if there is a valid frame.
References calculatePressureAltitude(), data::FIX_2D, data::FIX_3D, and util::to_string().
start()
void modules::Module::start () inherited
Starts a thread to run the module.
This function will start a thread to run a module, but only if the module is not already running. If the module is already running, an error will be logged. It also resets the stop flag to false.
References modules::Module::runner(), node::RUNNING, and node::SLEEPING.
Referenced by DataModuleTests::cycleDataModule(), ExtensionModuleTests::cycleExtensionModule(), and FlightRunner::toggleModule().
stop()
void modules::Module::stop () inherited
Stops the module by setting the stop flag to true and joining the runner thread.
This function will stop the module by setting the stop flag to true and joining the runner thread. It also sets the status to STOPPED. If a module is in the sleep state, it will only stop after the next loop. This means that the sleep interval plus the time it takes to run the loop and shutdown will be the total time it takes to stop the module.
References node::STOPPED, and node::STOPPING.
Referenced by FlightRunner::~FlightRunner(), DataModuleTests::cycleDataModule(), ExtensionModuleTests::cycleExtensionModule(), and FlightRunner::toggleModule().
getStatus()
node::Status modules::Module::getStatus () const inherited
Returns the status of the module.
Returns
Returns the status of the module.
See also
node::Status
addCommand()
bool modules::Module::addCommand (const cmd::Command & command) inline inherited
Public wrapper for adding a command to the command queue.
See also
cmd::CommandQueue
References cmd::CommandQueue::addCommand(), and modules::Module::command_queue_.
Referenced by FlightRunner::routeCommand().
updateLocalConfig()
virtual void modules::Module::updateLocalConfig () inline protected virtual inherited
Reimplemented in modules::ExtensionModule.
References giraffe_assert.
setStatus()
void modules::Module::setStatus (const node::Status status) protected inherited
Todo:
Sets the status of the module and reports it to the data stream.
error() [1/2]
void modules::Module::error (DiagnosticId log_id, std::string info = "") protected inherited
Used internally in the module. This function adds an error to the log stream. It is used to log errors that occur in the module.
Uses the module meta data to add the correct node identification.
Parameters
log_id The log id of the error.
info Optional information to add to the log.
Referenced by DataModule(), modules::ExtensionModule::addExtension(), modules::ExtensionModule::addPreConfiguredExtension(), modules::ExtensionModule::processCommand(), and modules::ExtensionModule::startup().
error() [2/2]
void modules::Module::error (DiagnosticId log_id, int info) protected inherited
Same as the other error function, but takes an int instead of a string.
References util::to_string().
info()
void modules::Module::info (std::string info = "") protected inherited
Used internally in the module. This function adds a info message to the log stream.
Uses the module meta data to add the correct node identification.
Parameters
info info string to add to the log.
Referenced by modules::ExtensionModule::addExtension(), and modules::ExtensionModule::startup().
debug()
void modules::Module::debug (std::string info) protected inherited
data()
template<typename T > template void modules::Module::data< double > (data::DataId identifier, T value, int precision = 2) protected inherited
Used internally in the module. This function adds a data to the data stream.
Template Parameters
T a non-string type that can be converted to a string with std::to_string
Parameters
identifier The data identifier.
value The value of the data.
precision The precision (if the type is a float or double)
References util::to_string().
stopRequested()
bool modules::Module::stopRequested () const inline protected inherited
Returns true if the stop flag is set to true.
Used internally in a module to check if the module should stop in between large tasks.
Returns
true
false
References modules::Module::stop_flag_.
sleep()
void modules::Module::sleep () protected inherited
Sleeps the module for the sleep interval.
Default of 1 second, this is blocking.
runner()
void modules::Module::runner () private inherited
This is the main function for each module.
This function is what runs in the thread. It calls startup, then loops until the stop flag is set to true. It then calls shutdown.
It also handles the command queue.
References node::RUNNING, node::SLEEPING, node::STARTING, node::STOPPED, and node::STOPPING.
Referenced by modules::Module::start().
Member Data Documentation
calculated_data_
data::blocks::CalculatedData modules::DataModule::calculated_data_ {} private
Buffer for the calculated data. Used by the calculateCalculatedData method.
data_log_
data_middleware::DataLog modules::DataModule::data_log_ private
The data log object, used to log data and errors to files.
influxdb_
data_middleware::InfluxDb modules::DataModule::influxdb_ private
Used to access the influxdb database.
file_system_
data_middleware::FileSystemManager modules::DataModule::file_system_ private
Used to manage the file system/data files.
data_file_enabled_
bool modules::DataModule::data_file_enabled_ = false private
True if data file logging is enabled.
This is updated every loop based on the configuration.
log_file_enabled_
bool modules::DataModule::log_file_enabled_ = false private
True if error file logging is enabled.
This is updated every loop based on the configuration.
influxdb_enabled_
bool modules::DataModule::influxdb_enabled_ = false private
True if influxdb logging is enabled.
This is updated every loop based on the configuration.
influxdb_write_rate_ms_
int modules::DataModule::influxdb_write_rate_ms_ = 1000 private
console_module_enabled_
bool modules::DataModule::console_module_enabled_ = false private
User to determine if shared 'log_container' needs to be updated so the console module can print the log.
data_file_logging_strategy_
cfg::gEnum::LogStrategy modules::DataModule::data_file_logging_strategy_ private
Initial value:
=
      cfg::gEnum::LogStrategy::INTERVAL
The current data file logging strategy.
This is updated every loop based on the configuration.
error_file_logging_strategy_
cfg::gEnum::ErrorLogStrategy modules::DataModule::error_file_logging_strategy_ private
Initial value:
=
      cfg::gEnum::ErrorLogStrategy::ALL
The current error file logging strategy.
This is updated every loop based on the configuration.
gps_distance_update_timer_
bst::Timer modules::DataModule::gps_distance_update_timer_ {} private
This timer is used to determine when to update the gps path for the purpose of calculating distance traveled.
See also
calculateCalculatedData
last_gps_point_
bst::geo::Point modules::DataModule::last_gps_point_ {} private
The last gps point. Used to calculate distance traveled.
See also
calculateCalculatedData
launch_gps_point_
bst::geo::Point modules::DataModule::launch_gps_point_ {} private
The initial gps point. This is the "launch point".
launch_gps_point_set_
bool modules::DataModule::launch_gps_point_set_ = false private
True if the initial gps point has been set.
distance_traveled_
double modules::DataModule::distance_traveled_ = 0.0 private
The distance traveled in km.
average_horizontal_speed_
bst::RollingAverage modules::DataModule::average_horizontal_speed_ {20} private
Rolling average of the horizontal speed. Once every 15 seconds (20 in a 5 minute span)
average_vertical_speed_
bst::RollingAverage modules::DataModule::average_vertical_speed_ {20} private
average_speed_timer_
bst::Timer modules::DataModule::average_speed_timer_ {15 * 1000} private
metadata_
modules::MetaData modules::Module::metadata_ protected inherited
shared_data_
data::SharedData& modules::Module::shared_data_ protected inherited
Referenced by modules::ExtensionModule::loop().
configuration_
cfg::Configuration& modules::Module::configuration_ protected inherited
Referenced by DataModule(), modules::ExtensionModule::addPreConfiguredExtension(), modules::ExtensionModule::startup(), and modules::ExtensionModule::updateLocalConfig().
status_
std::atomic<node::Status> modules::Module::status_ = node::Status::UNKNOWN private inherited
The status of the module.
See also
node::Status
stop_flag_
std::atomic<bool> modules::Module::stop_flag_ = true private inherited
The stop flag is used to stop the module.
Set to true to stop the module upon a call to stop().
Referenced by modules::Module::stopRequested().
runner_thread_
std::thread modules::Module::runner_thread_ private inherited
The thread that runs runner().
command_queue_
cmd::CommandQueue modules::Module::command_queue_ private inherited
The command queue for the module.
See also
cmd::CommandQueue
Referenced by modules::Module::addCommand().