Giraffe: ax25::DataLinkStateMachine Class Reference
ax25::DataLinkStateMachine Class Reference
#include <data_link.hpp>
Public Member Functions
DataLinkStateMachine (StateMachineData &data)
~DataLinkStateMachine ()=default
DataLinkStates getCurrentState () const
void receive (Primitive primitive)
Protected Member Functions
void generateSignal (Primitive primitive)
void indicateError (StateMachineErrors error_code, bool active)
void isSignalPresent (Primitive primitive)
Protected Attributes
StateMachineData & data_
Private Member Functions
void set_state (DataLinkStates state)
void state_awaitingConnection ()
void state_awaitingConnectionV2_2 ()
void state_awaitingRelease ()
void state_connected ()
void state_disconnected ()
void state_timerRecovery ()
void subroutine_checkIFrameAcked ()
void subroutine_checkNeedForResponse ()
void subroutine_clearExceptionConditions ()
void subroutine_enquiryResponse ()
void subroutine_establishDataLink ()
void subroutine_establishExtendedDataLink ()
void subroutine_invokeRetransmission ()
void subroutine_NrErrorRecovery ()
void subroutine_selectT1Value ()
void subroutine_setVersion2_0 ()
void subroutine_setVersion2_2 ()
void subroutine_transmitEnquiry ()
void subroutine_uiCheck ()
Private Attributes
DataLinkStates state_ = DataLinkStates::DISCONNECTED
Constructor & Destructor Documentation
DataLinkStateMachine()
ax25::DataLinkStateMachine::DataLinkStateMachine (StateMachineData & data) inline
~DataLinkStateMachine()
ax25::DataLinkStateMachine::~DataLinkStateMachine () default
Member Function Documentation
getCurrentState()
DataLinkStates ax25::DataLinkStateMachine::getCurrentState () const inline
References state_.
receive()
void ax25::DataLinkStateMachine::receive (Primitive primitive)
set_state()
void ax25::DataLinkStateMachine::set_state (DataLinkStates state) inline private
References state_.
state_disconnected()
void ax25::DataLinkStateMachine::state_disconnected () private
References ax25::BaseAX25StateMachine::generateSignal(), and subroutine_uiCheck().
state_awaitingConnection()
void ax25::DataLinkStateMachine::state_awaitingConnection () private
References subroutine_uiCheck().
state_awaitingRelease()
void ax25::DataLinkStateMachine::state_awaitingRelease () private
References subroutine_uiCheck().
state_connected()
void ax25::DataLinkStateMachine::state_connected () private
state_timerRecovery()
void ax25::DataLinkStateMachine::state_timerRecovery () private
state_awaitingConnectionV2_2()
void ax25::DataLinkStateMachine::state_awaitingConnectionV2_2 () private
subroutine_NrErrorRecovery()
void ax25::DataLinkStateMachine::subroutine_NrErrorRecovery () private
subroutine_establishDataLink()
void ax25::DataLinkStateMachine::subroutine_establishDataLink () private
subroutine_clearExceptionConditions()
void ax25::DataLinkStateMachine::subroutine_clearExceptionConditions () private
subroutine_transmitEnquiry()
void ax25::DataLinkStateMachine::subroutine_transmitEnquiry () private
subroutine_enquiryResponse()
void ax25::DataLinkStateMachine::subroutine_enquiryResponse () private
subroutine_invokeRetransmission()
void ax25::DataLinkStateMachine::subroutine_invokeRetransmission () private
subroutine_checkIFrameAcked()
void ax25::DataLinkStateMachine::subroutine_checkIFrameAcked () private
subroutine_checkNeedForResponse()
void ax25::DataLinkStateMachine::subroutine_checkNeedForResponse () private
subroutine_selectT1Value()
void ax25::DataLinkStateMachine::subroutine_selectT1Value () private
subroutine_establishExtendedDataLink()
void ax25::DataLinkStateMachine::subroutine_establishExtendedDataLink () private
subroutine_setVersion2_0()
void ax25::DataLinkStateMachine::subroutine_setVersion2_0 () private
subroutine_setVersion2_2()
void ax25::DataLinkStateMachine::subroutine_setVersion2_2 () private
subroutine_uiCheck()
void ax25::DataLinkStateMachine::subroutine_uiCheck () private
Referenced by state_awaitingConnection(), state_awaitingRelease(), and state_disconnected().
generateSignal()
void ax25::BaseAX25StateMachine::generateSignal (Primitive primitive) protected inherited
Referenced by state_disconnected().
isSignalPresent()
void ax25::BaseAX25StateMachine::isSignalPresent (Primitive primitive) protected inherited
Referenced by ax25::SimplexPhysicalLayerStateMachine::state_ready().
indicateError()
void ax25::BaseAX25StateMachine::indicateError (StateMachineErrors error_code, bool active) protected inherited
Member Data Documentation
state_
DataLinkStates ax25::DataLinkStateMachine::state_ = DataLinkStates::DISCONNECTED private
Referenced by getCurrentState(), and set_state().
data_
StateMachineData& ax25::BaseAX25StateMachine::data_ protected inherited
Referenced by ax25::SimplexPhysicalLayerStateMachine::state_ready().