Giraffe: FlightPhaseManagerTest Class Reference
FlightPhaseManagerTest Class Reference
Classes
struct TestContainer
Protected Types
using Parameter = PredictionParameters::Parameter
Protected Member Functions
void bringToAscent ()
void bringToDescent ()
void bringToLaunch ()
void dumpDataStream ()
void setParamsAscent ()
void setParamsDescent ()
void setParamsInvalid ()
void setParamsLaunch ()
void setParamsRecovery ()
virtual void SetUp ()
virtual void TearDown ()
void tick (size_t ticks=1)
bool validateHasDataItem (data::DataId data_id)
bool validateHasError (DiagnosticId error_id)
bool validateNoData ()
bool validateNoError ()
Protected Attributes
FlightPhaseManager * manager_ = nullptr
TestContainer * test_ = nullptr
Static Protected Attributes
static constexpr size_t FILTER_RATE = 5
Class Documentation
FlightPhaseManagerTest::TestContainer
struct FlightPhaseManagerTest::TestContainer
Class Members
FakeSharedData shared_data
FlightPhaseManager flight_phase_manager
PredictionParameters detection_data
FlightData & flight_data
Block< CalculatedData > & calculated_data
Block< LocationData > & location_data
Block< ImuData > & imu_data
Member Typedef Documentation
Parameter
using FlightPhaseManagerTest::Parameter = PredictionParameters::Parameter protected
Member Function Documentation
SetUp()
virtual void FlightPhaseManagerTest::SetUp () inline protected virtual
References FlightPhaseManagerTest::TestContainer::flight_phase_manager, manager_, and test_.
TearDown()
virtual void FlightPhaseManagerTest::TearDown () inline protected virtual
References test_.
validateNoError()
bool FlightPhaseManagerTest::validateNoError () inline protected
References data::Stream< T >::getPacket(), FakeSharedData::hasLogItems(), data::Streams::log, FlightPhaseManagerTest::TestContainer::shared_data, data::SharedData::streams, test_, and util::to_string().
Referenced by bringToAscent(), bringToDescent(), and bringToLaunch().
validateHasError()
bool FlightPhaseManagerTest::validateHasError (DiagnosticId error_id) inline protected
References data::Stream< T >::getPacket(), FakeSharedData::hasLogItems(), data::LogPacket::id, data::Streams::log, FlightPhaseManagerTest::TestContainer::shared_data, data::SharedData::streams, test_, and util::to_string().
validateHasDataItem()
bool FlightPhaseManagerTest::validateHasDataItem (data::DataId data_id) inline protected
References data::Streams::data, data::Stream< T >::getPacket(), FakeSharedData::hasDataItems(), data::DataPacket::identifier, FlightPhaseManagerTest::TestContainer::shared_data, data::SharedData::streams, test_, and util::to_string().
validateNoData()
bool FlightPhaseManagerTest::validateNoData () inline protected
References data::Streams::data, data::Stream< T >::getPacket(), FakeSharedData::hasDataItems(), FlightPhaseManagerTest::TestContainer::shared_data, data::SharedData::streams, test_, and util::to_string().
dumpDataStream()
void FlightPhaseManagerTest::dumpDataStream () inline protected
References data::Streams::data, data::Stream< T >::getPacket(), FlightPhaseManagerTest::TestContainer::shared_data, data::SharedData::streams, test_, and util::to_string().
tick()
void FlightPhaseManagerTest::tick (size_t ticks = 1) inline protected
References manager_, and FlightPhaseManager::update().
Referenced by bringToAscent(), and bringToDescent().
setParamsInvalid()
void FlightPhaseManagerTest::setParamsInvalid () inline protected
References setCalculatedDataInvalid(), setLocationDataInvalid(), FlightPhaseManagerTest::TestContainer::shared_data, and test_.
setParamsLaunch()
void FlightPhaseManagerTest::setParamsLaunch () inline protected
References setCalculatedDataLaunch(), setLocationDataLaunch(), FlightPhaseManagerTest::TestContainer::shared_data, and test_.
setParamsAscent()
void FlightPhaseManagerTest::setParamsAscent () inline protected
References setCalculatedDataAscent(), setLocationDataAscent(), FlightPhaseManagerTest::TestContainer::shared_data, and test_.
Referenced by bringToAscent().
setParamsDescent()
void FlightPhaseManagerTest::setParamsDescent () inline protected
References setCalculatedDataDescent(), setLocationDataDescent(), FlightPhaseManagerTest::TestContainer::shared_data, and test_.
Referenced by bringToDescent().
setParamsRecovery()
void FlightPhaseManagerTest::setParamsRecovery () inline protected
References setCalculatedDataRecovery(), setLocationDataRecovery(), FlightPhaseManagerTest::TestContainer::shared_data, and test_.
bringToLaunch()
void FlightPhaseManagerTest::bringToLaunch () inline protected
References data::Streams::data, FlightPhaseManagerTest::TestContainer::flight_data, FlightPhaseManagerTest::TestContainer::flight_phase_manager, FlightPhaseManager::getCurrentFlightPhase(), data::FlightData::getFlightPhase(), LAUNCH, data::Streams::log, manager_, PRE_LAUNCH, FlightPhaseManager::requestLaunch(), data::Stream< T >::reset(), FlightPhaseManager::setPreLaunch(), FlightPhaseManagerTest::TestContainer::shared_data, data::SharedData::streams, test_, and validateNoError().
Referenced by bringToAscent().
bringToAscent()
void FlightPhaseManagerTest::bringToAscent () inline protected
References ASCENT, bringToLaunch(), data::Streams::data, FILTER_RATE, FlightPhaseManagerTest::TestContainer::flight_data, FlightPhaseManager::getCurrentFlightPhase(), data::FlightData::getFlightPhase(), data::Streams::log, manager_, data::Stream< T >::reset(), setParamsAscent(), FlightPhaseManagerTest::TestContainer::shared_data, data::SharedData::streams, test_, tick(), and validateNoError().
Referenced by bringToDescent().
bringToDescent()
void FlightPhaseManagerTest::bringToDescent () inline protected
References bringToAscent(), data::Streams::data, DESCENT, FILTER_RATE, FlightPhaseManagerTest::TestContainer::flight_data, FlightPhaseManager::getCurrentFlightPhase(), data::FlightData::getFlightPhase(), data::Streams::log, manager_, data::Stream< T >::reset(), setParamsDescent(), FlightPhaseManagerTest::TestContainer::shared_data, data::SharedData::streams, test_, tick(), and validateNoError().
Member Data Documentation
FILTER_RATE
constexpr size_t FlightPhaseManagerTest::FILTER_RATE = 5 static constexpr protected
Referenced by bringToAscent(), and bringToDescent().
test_
TestContainer* FlightPhaseManagerTest::test_ = nullptr protected
Referenced by bringToAscent(), bringToDescent(), bringToLaunch(), dumpDataStream(), setParamsAscent(), setParamsDescent(), setParamsInvalid(), setParamsLaunch(), setParamsRecovery(), SetUp(), TearDown(), validateHasDataItem(), validateHasError(), validateNoData(), and validateNoError().
manager_
FlightPhaseManager* FlightPhaseManagerTest::manager_ = nullptr protected
Referenced by bringToAscent(), bringToDescent(), bringToLaunch(), SetUp(), and tick().