Giraffe: data::ErrorReporter Class Reference
data::ErrorReporter Class Reference
A simple class to unique errors once.
#include <error_reporter.hpp>
Public Member Functions
ErrorReporter (SharedData &shared_data, node::Identification source, DiagnosticId error_id)
Constructor.
void clearError ()
void reportError (std::string extra_info="")
Private Attributes
const DiagnosticId error_id_
bool is_set_ = false
std::string previous_extra_info_ = ""
SharedData & shared_data_
const node::Identification source_id_
Detailed Description
A simple class to unique errors once.
Allows for an error to be reported once unless it is cleared.
Constructor & Destructor Documentation
ErrorReporter()
data::ErrorReporter::ErrorReporter (SharedData & shared_data, node::Identification source, DiagnosticId error_id) inline
Constructor.
Parameters
shared_data - Reference to shared data.
source - The source of the error.
error_id - The error id to report.
Member Function Documentation
reportError()
void data::ErrorReporter::reportError (std::string extra_info = "") inline
References data::LogStream::error(), data::Frames::error_frame, error_id_, data::SharedData::frames, is_set_, data::ErrorFrame::isActive(), data::Streams::log, previous_extra_info_, shared_data_, source_id_, and data::SharedData::streams.
Referenced by FlightPhaseManager::reportPhaseChangeInvalid().
clearError()
void data::ErrorReporter::clearError () inline
References is_set_.
Member Data Documentation
is_set_
bool data::ErrorReporter::is_set_ = false private
Referenced by clearError(), and reportError().
shared_data_
SharedData& data::ErrorReporter::shared_data_ private
Referenced by reportError().
source_id_
const node::Identification data::ErrorReporter::source_id_ private
Referenced by reportError().
error_id_
const DiagnosticId data::ErrorReporter::error_id_ private
Referenced by reportError().
previous_extra_info_
std::string data::ErrorReporter::previous_extra_info_ = "" private
Referenced by reportError().