Giraffe: giraffe::gdl::TransportLayer Class Reference
giraffe::gdl::TransportLayer Class Reference
The Transport Layer - Layer 3.
#include <transport_layer.hpp>
Public Types
enum class State { IDLE , EXCHANGE_SEND , EXCHANGE_WAITING_FOR_ACK , BROADCAST }
Public Member Functions
TransportLayer (Config &config, NetworkLayer &network_layer)
~TransportLayer ()
bool isConnected () const
bool isReadyToSend ()
Check if the transport layer is ready to send a message (true) or if it is busy with the previous message (false).
bool receive (Message &message)
bool send (Message &message)
Send a message to the remote node.
void update (Statistics &statistics)
Private Member Functions
void broadcastState ()
void controllerIdleState ()
void exchangeSendState ()
void exchangeWaitingForAckState ()
void idleState ()
void sendAck (uint32_t message_id)
void sendPing ()
void sendPingResponse ()
Private Attributes
Config & config_
bool connected_ = false
Packet current_tx_packet_ {}
bool downlink_connected_ = false
bst::Timer exchange_ack_timer_ {GDL_RDT_RETRY_INTERVAL_MS}
A timer used to retry sending an exchange message if we don't receive an ack.
bst::Timer exchange_ping_interval_timer_ {GDL_EXCHANGE_PING_INTERVAL_MS}
The interval to send pings at if we don't receive any messages. Used by the controller node only.
uint32_t last_acked_message_id_ = 0xffffffff
The last message id that was acked by the local node.
bst::Time last_message_received_ {}
bool message_received_ = false
NetworkLayer & network_layer_
bst::Timer new_tx_timer_ {GDL_NEW_TX_DELAY_MS}
The timer to create a delay before sending a new message.
uint32_t position_packets_received_ = 0
Message received_message_ {}
bst::Timer received_timer_ {GDL_EXCHANGE_CONNECTION_TIMEOUT_MS}
Reset whenever a message is received.
uint32_t sent_exchange_message_id_ = 0
State state_ = State::IDLE
uint32_t telemetry_packets_received_ = 0
uint32_t total_messages_dropped_ = 0
bool uplink_connected_ = false
bst::Timer uplink_timer_ {GDL_EXCHANGE_CONNECTION_TIMEOUT_MS}
Used by the remote node only to detect if we are getting responses to packets that we send.
Detailed Description
The Transport Layer - Layer 3.
The transport layer is responsible for sending messages from the application layer (DataLink) to the network layer (NetworkLayer) and receiving messages from the network layer and passing them to the application layer. The transport layer will look at the messages queues and will route the contents to the correct portion of the network layer.
Along with all of this, the transport layer is responsible for maintaining the connection between the local and remote nodes.
Member Enumeration Documentation
State
enum class giraffe::gdl::TransportLayer::State strong
Enumerator
IDLE
EXCHANGE_SEND
EXCHANGE_WAITING_FOR_ACK
BROADCAST
Constructor & Destructor Documentation
TransportLayer()
giraffe::gdl::TransportLayer::TransportLayer (Config & config, NetworkLayer & network_layer)
~TransportLayer()
giraffe::gdl::TransportLayer::~TransportLayer ()
Member Function Documentation
isReadyToSend()
bool giraffe::gdl::TransportLayer::isReadyToSend ()
Check if the transport layer is ready to send a message (true) or if it is busy with the previous message (false).
References IDLE, new_tx_timer_, and state_.
Referenced by giraffe::gdl::DataLink::gdlThread(), and send().
send()
bool giraffe::gdl::TransportLayer::send (Message & message)
Send a message to the remote node.
This will set the state of the transport layer to something other than IDLE. If the message type is 'EXCHANGE' and we are in proactive keep alive mode, we will only send the message if we are connected.
Parameters
message - The message to send.
Todo:
handle other messages and report an error
References giraffe::gdl::Packet::APRS_TELEMETRY, giraffe::gdl::Message::BROADCAST, giraffe::gdl::Packet::BROADCAST, BROADCAST, config_, current_tx_packet_, giraffe::gdl::Message::EXCHANGE, giraffe::gdl::Packet::EXCHANGE, EXCHANGE_SEND, giraffe::gdl::Config::getProactiveKeepAlive(), giraffe::gdl::Message::getType(), giraffe::gdl::Message::IMAGE, isConnected(), isReadyToSend(), giraffe::gdl::Message::LOCATION, giraffe::gdl::Packet::LOCATION, giraffe::gdl::Packet::setPacketType(), giraffe::gdl::Packet::SSTV, state_, and giraffe::gdl::Message::TELEMETRY.
Referenced by giraffe::gdl::DataLink::gdlThread().
receive()
bool giraffe::gdl::TransportLayer::receive (Message & message)
References message_received_, and received_message_.
Referenced by giraffe::gdl::DataLink::gdlThread().
isConnected()
bool giraffe::gdl::TransportLayer::isConnected () const inline
References connected_.
Referenced by send().
update()
void giraffe::gdl::TransportLayer::update (Statistics & statistics)
References BROADCAST, broadcastState(), giraffe::gdl::Statistics::downlink_connected, downlink_connected_, EXCHANGE_SEND, EXCHANGE_WAITING_FOR_ACK, exchangeSendState(), exchangeWaitingForAckState(), IDLE, idleState(), giraffe::gdl::Statistics::last_message_received, last_message_received_, network_layer_, giraffe::gdl::Statistics::position_packets_received, position_packets_received_, state_, giraffe::gdl::Statistics::telemetry_packets_received, telemetry_packets_received_, giraffe::gdl::Statistics::total_messages_dropped, total_messages_dropped_, giraffe::gdl::NetworkLayer::update(), giraffe::gdl::Statistics::uplink_connected, and uplink_connected_.
Referenced by giraffe::gdl::DataLink::gdlThread().
idleState()
void giraffe::gdl::TransportLayer::idleState () private
Todo:
remove this. We should never get here. We can log this.
Note
this may be worth expanding to a queue in the future
Todo:
handle connection timeout reset
Todo:
handle connection timeout reset
Todo:
log this
References giraffe::gdl::Packet::APRS_TELEMETRY, giraffe::gdl::Packet::BROADCAST, config_, connected_, controllerIdleState(), downlink_connected_, giraffe::gdl::Packet::EXCHANGE, exchange_ping_interval_timer_, giraffe::gdl::Message::getData(), giraffe::gdl::Message::getIdentifier(), giraffe::gdl::Packet::getPacketType(), giraffe::gdl::Config::getProactiveKeepAlive(), giraffe::gdl::Config::isController(), last_acked_message_id_, last_message_received_, giraffe::gdl::Message::LOCATION, giraffe::gdl::Packet::LOCATION, message_received_, network_layer_, giraffe::gdl::Packet::PING, giraffe::gdl::Packet::PING_RESPONSE, position_packets_received_, received_message_, received_timer_, giraffe::gdl::NetworkLayer::rxPacket(), sendAck(), sendPingResponse(), giraffe::gdl::Message::setExchangeMessage(), giraffe::gdl::Message::setType(), giraffe::gdl::Message::TELEMETRY, telemetry_packets_received_, uplink_connected_, and uplink_timer_.
Referenced by update().
controllerIdleState()
void giraffe::gdl::TransportLayer::controllerIdleState () private
References config_, exchange_ping_interval_timer_, giraffe::gdl::Config::getProactiveKeepAlive(), and sendPing().
Referenced by idleState().
exchangeSendState()
void giraffe::gdl::TransportLayer::exchangeSendState () private
Todo:
handle error
Todo:
handle error
References current_tx_packet_, exchange_ack_timer_, EXCHANGE_WAITING_FOR_ACK, giraffe::gdl::GDL_RDT_MAX_RETRIES, giraffe::gdl::Message::getIdentifier(), giraffe::gdl::Packet::getSendAttempts(), IDLE, giraffe::gdl::Packet::incrementSendAttempts(), network_layer_, sent_exchange_message_id_, state_, total_messages_dropped_, and giraffe::gdl::NetworkLayer::txPacket().
Referenced by update().
exchangeWaitingForAckState()
void giraffe::gdl::TransportLayer::exchangeWaitingForAckState () private
Todo:
remove this. We should never get here. We can log this.
Todo:
log this
References giraffe::gdl::Packet::ACK, exchange_ack_timer_, exchange_ping_interval_timer_, EXCHANGE_SEND, giraffe::gdl::Message::getIdentifier(), giraffe::gdl::Packet::getPacketType(), IDLE, message_received_, network_layer_, new_tx_timer_, received_timer_, giraffe::gdl::NetworkLayer::rxPacket(), sent_exchange_message_id_, state_, uplink_connected_, and uplink_timer_.
Referenced by update().
broadcastState()
void giraffe::gdl::TransportLayer::broadcastState () private
Todo:
handle error
References current_tx_packet_, IDLE, network_layer_, new_tx_timer_, state_, and giraffe::gdl::NetworkLayer::txPacket().
Referenced by update().
sendAck()
void giraffe::gdl::TransportLayer::sendAck (uint32_t message_id) private
Todo:
handle error
References giraffe::gdl::Packet::ACK, network_layer_, giraffe::gdl::Message::setIdentifier(), giraffe::gdl::Packet::setPacketType(), and giraffe::gdl::NetworkLayer::txPacket().
Referenced by idleState().
sendPing()
void giraffe::gdl::TransportLayer::sendPing () private
Todo:
handle error
References network_layer_, giraffe::gdl::Packet::PING, giraffe::gdl::Message::setIdentifier(), giraffe::gdl::Packet::setPacketType(), and giraffe::gdl::NetworkLayer::txPacket().
Referenced by controllerIdleState().
sendPingResponse()
void giraffe::gdl::TransportLayer::sendPingResponse () private
Todo:
handle error
References network_layer_, giraffe::gdl::Packet::PING_RESPONSE, giraffe::gdl::Message::setIdentifier(), giraffe::gdl::Packet::setPacketType(), and giraffe::gdl::NetworkLayer::txPacket().
Referenced by idleState().
Member Data Documentation
config_
Config& giraffe::gdl::TransportLayer::config_ private
Referenced by controllerIdleState(), idleState(), and send().
network_layer_
NetworkLayer& giraffe::gdl::TransportLayer::network_layer_ private
Referenced by broadcastState(), exchangeSendState(), exchangeWaitingForAckState(), idleState(), sendAck(), sendPing(), sendPingResponse(), and update().
connected_
bool giraffe::gdl::TransportLayer::connected_ = false private
Referenced by idleState(), and isConnected().
uplink_connected_
bool giraffe::gdl::TransportLayer::uplink_connected_ = false private
Referenced by exchangeWaitingForAckState(), idleState(), and update().
downlink_connected_
bool giraffe::gdl::TransportLayer::downlink_connected_ = false private
Referenced by idleState(), and update().
current_tx_packet_
Packet giraffe::gdl::TransportLayer::current_tx_packet_ {} private
Referenced by broadcastState(), exchangeSendState(), and send().
message_received_
bool giraffe::gdl::TransportLayer::message_received_ = false private
Referenced by exchangeWaitingForAckState(), idleState(), and receive().
received_message_
Message giraffe::gdl::TransportLayer::received_message_ {} private
Referenced by idleState(), and receive().
state_
State giraffe::gdl::TransportLayer::state_ = State::IDLE private
Referenced by broadcastState(), exchangeSendState(), exchangeWaitingForAckState(), isReadyToSend(), send(), and update().
new_tx_timer_
bst::Timer giraffe::gdl::TransportLayer::new_tx_timer_ {GDL_NEW_TX_DELAY_MS} private
The timer to create a delay before sending a new message.
Referenced by broadcastState(), exchangeWaitingForAckState(), and isReadyToSend().
received_timer_
bst::Timer giraffe::gdl::TransportLayer::received_timer_ {GDL_EXCHANGE_CONNECTION_TIMEOUT_MS} private
Reset whenever a message is received.
Used by the controller node and the remote node.
Referenced by exchangeWaitingForAckState(), and idleState().
uplink_timer_
bst::Timer giraffe::gdl::TransportLayer::uplink_timer_ {GDL_EXCHANGE_CONNECTION_TIMEOUT_MS} private
Used by the remote node only to detect if we are getting responses to packets that we send.
Referenced by exchangeWaitingForAckState(), and idleState().
exchange_ping_interval_timer_
bst::Timer giraffe::gdl::TransportLayer::exchange_ping_interval_timer_ {GDL_EXCHANGE_PING_INTERVAL_MS} private
The interval to send pings at if we don't receive any messages. Used by the controller node only.
See also
GDL_EXCHANGE_PING_INTERVAL_MS
Referenced by controllerIdleState(), exchangeWaitingForAckState(), and idleState().
exchange_ack_timer_
bst::Timer giraffe::gdl::TransportLayer::exchange_ack_timer_ {GDL_RDT_RETRY_INTERVAL_MS} private
A timer used to retry sending an exchange message if we don't receive an ack.
Referenced by exchangeSendState(), and exchangeWaitingForAckState().
last_acked_message_id_
uint32_t giraffe::gdl::TransportLayer::last_acked_message_id_ = 0xffffffff private
The last message id that was acked by the local node.
This is used to determine if the message should be pushed to the DataLink layer or not. If the message id of the next received message does not match this, it will be pushed up. If the message id of the received message matches this, it will not be pushed up but it will still be acked.
Referenced by idleState().
sent_exchange_message_id_
uint32_t giraffe::gdl::TransportLayer::sent_exchange_message_id_ = 0 private
Referenced by exchangeSendState(), and exchangeWaitingForAckState().
total_messages_dropped_
uint32_t giraffe::gdl::TransportLayer::total_messages_dropped_ = 0 private
Referenced by exchangeSendState(), and update().
last_message_received_
bst::Time giraffe::gdl::TransportLayer::last_message_received_ {} private
Referenced by idleState(), and update().
position_packets_received_
uint32_t giraffe::gdl::TransportLayer::position_packets_received_ = 0 private
Referenced by idleState(), and update().
telemetry_packets_received_
uint32_t giraffe::gdl::TransportLayer::telemetry_packets_received_ = 0 private
Referenced by idleState(), and update().