Giraffe: modules::SystemModule Class Reference
modules::SystemModule Class Reference
#include <system_module.hpp>
Public Member Functions
SystemModule (data::SharedData &, cfg::Configuration &)
~SystemModule () override
bool addCommand (const cmd::Command &command)
Public wrapper for adding a command to the command queue.
node::Status getStatus () const
Returns the status of the module.
void start ()
Starts a thread to run the module.
void stop ()
Stops the module by setting the stop flag to true and joining the runner thread.
Protected Member Functions
template<typename T >
void data (data::DataId identifier, T value, int precision=2)
Used internally in the module. This function adds a data to the data stream.
void debug (std::string info)
void error (DiagnosticId log_id, int info)
Same as the other error function, but takes an int instead of a string.
void error (DiagnosticId, std::string info="")
Used internally in the module. This function adds an error to the log stream. It is used to log errors that occur in the module.
void info (std::string info="")
Used internally in the module. This function adds a info message to the log stream.
void setStatus (const node::Status status)
void sleep ()
Sleeps the module for the sleep interval.
bool stopRequested () const
Returns true if the stop flag is set to true.
virtual void updateLocalConfig ()
Protected Attributes
cfg::Configuration & configuration_
modules::MetaData metadata_
data::SharedData & shared_data_
Private Member Functions
void loop () override
Continually called at a rate set by the sleep interval.
void processCommand (const cmd::Command &)
Called when a command is received.
void runner ()
This is the main function for each module.
void shutdown () override
Called only once at shutdown.
void startup () override
This function is called when the module is started.
void updateCpuAndMemoryInfo ()
void updateCpuTemp ()
void updateDiskInfo ()
void updateNetworkInfo ()
Private Attributes
cmd::CommandQueue command_queue_
The command queue for the module.
data::blocks::SystemInfo data_ = data::blocks::SystemInfo()
std::thread runner_thread_
The thread that runs runner().
std::atomic< node::Status > status_ = node::Status::UNKNOWN
The status of the module.
std::atomic< bool > stop_flag_ = true
The stop flag is used to stop the module.
Detailed Description
Todo:
this header needs some work
Constructor & Destructor Documentation
SystemModule()
modules::SystemModule::SystemModule (data::SharedData & shared_data, cfg::Configuration & config)
~SystemModule()
modules::SystemModule::~SystemModule () override
Member Function Documentation
startup()
void modules::SystemModule::startup () override private virtual
This function is called when the module is started.
This is overridden by the module implementation. Called only once at startup.
Reimplemented from modules::Module.
loop()
void modules::SystemModule::loop () override private virtual
Continually called at a rate set by the sleep interval.
Reimplemented from modules::Module.
shutdown()
void modules::SystemModule::shutdown () override private virtual
Called only once at shutdown.
Reimplemented from modules::Module.
processCommand()
void modules::SystemModule::processCommand (const cmd::Command & command) private virtual
Called when a command is received.
Parameters
command
Reimplemented from modules::Module.
updateCpuAndMemoryInfo()
void modules::SystemModule::updateCpuAndMemoryInfo () private
updateCpuTemp()
void modules::SystemModule::updateCpuTemp () private
updateDiskInfo()
void modules::SystemModule::updateDiskInfo () private
updateNetworkInfo()
void modules::SystemModule::updateNetworkInfo () private
start()
void modules::Module::start () inherited
Starts a thread to run the module.
This function will start a thread to run a module, but only if the module is not already running. If the module is already running, an error will be logged. It also resets the stop flag to false.
References modules::Module::runner(), node::RUNNING, and node::SLEEPING.
Referenced by FlightRunner::toggleModule().
stop()
void modules::Module::stop () inherited
Stops the module by setting the stop flag to true and joining the runner thread.
This function will stop the module by setting the stop flag to true and joining the runner thread. It also sets the status to STOPPED. If a module is in the sleep state, it will only stop after the next loop. This means that the sleep interval plus the time it takes to run the loop and shutdown will be the total time it takes to stop the module.
References node::STOPPED, and node::STOPPING.
Referenced by FlightRunner::~FlightRunner(), and FlightRunner::toggleModule().
getStatus()
node::Status modules::Module::getStatus () const inherited
Returns the status of the module.
Returns
Returns the status of the module.
See also
node::Status
addCommand()
bool modules::Module::addCommand (const cmd::Command & command) inline inherited
Public wrapper for adding a command to the command queue.
See also
cmd::CommandQueue
References cmd::CommandQueue::addCommand(), and modules::Module::command_queue_.
Referenced by FlightRunner::routeCommand().
updateLocalConfig()
virtual void modules::Module::updateLocalConfig () inline protected virtual inherited
Reimplemented in modules::ExtensionModule.
References giraffe_assert.
setStatus()
void modules::Module::setStatus (const node::Status status) protected inherited
Todo:
Sets the status of the module and reports it to the data stream.
error() [1/2]
void modules::Module::error (DiagnosticId log_id, std::string info = "") protected inherited
Used internally in the module. This function adds an error to the log stream. It is used to log errors that occur in the module.
Uses the module meta data to add the correct node identification.
Parameters
log_id The log id of the error.
info Optional information to add to the log.
Referenced by modules::DataModule::DataModule(), and modules::ExtensionModule::startup().
error() [2/2]
void modules::Module::error (DiagnosticId log_id, int info) protected inherited
Same as the other error function, but takes an int instead of a string.
References util::to_string().
info()
void modules::Module::info (std::string info = "") protected inherited
Used internally in the module. This function adds a info message to the log stream.
Uses the module meta data to add the correct node identification.
Parameters
info info string to add to the log.
Referenced by modules::ExtensionModule::startup().
debug()
void modules::Module::debug (std::string info) protected inherited
data()
template<typename T > template void modules::Module::data< double > (data::DataId identifier, T value, int precision = 2) protected inherited
Used internally in the module. This function adds a data to the data stream.
Template Parameters
T a non-string type that can be converted to a string with std::to_string
Parameters
identifier The data identifier.
value The value of the data.
precision The precision (if the type is a float or double)
References util::to_string().
stopRequested()
bool modules::Module::stopRequested () const inline protected inherited
Returns true if the stop flag is set to true.
Used internally in a module to check if the module should stop in between large tasks.
Returns
true
false
References modules::Module::stop_flag_.
sleep()
void modules::Module::sleep () protected inherited
Sleeps the module for the sleep interval.
Default of 1 second, this is blocking.
runner()
void modules::Module::runner () private inherited
This is the main function for each module.
This function is what runs in the thread. It calls startup, then loops until the stop flag is set to true. It then calls shutdown.
It also handles the command queue.
References node::RUNNING, node::SLEEPING, node::STARTING, node::STOPPED, and node::STOPPING.
Referenced by modules::Module::start().
Member Data Documentation
data_
data::blocks::SystemInfo modules::SystemModule::data_ = data::blocks::SystemInfo() private
metadata_
modules::MetaData modules::Module::metadata_ protected inherited
shared_data_
data::SharedData& modules::Module::shared_data_ protected inherited
Referenced by modules::ExtensionModule::loop().
configuration_
cfg::Configuration& modules::Module::configuration_ protected inherited
Referenced by modules::DataModule::DataModule(), modules::ExtensionModule::startup(), and modules::ExtensionModule::updateLocalConfig().
status_
std::atomic<node::Status> modules::Module::status_ = node::Status::UNKNOWN private inherited
The status of the module.
See also
node::Status
stop_flag_
std::atomic<bool> modules::Module::stop_flag_ = true private inherited
The stop flag is used to stop the module.
Set to true to stop the module upon a call to stop().
Referenced by modules::Module::stopRequested().
runner_thread_
std::thread modules::Module::runner_thread_ private inherited
The thread that runs runner().
command_queue_
cmd::CommandQueue modules::Module::command_queue_ private inherited
The command queue for the module.
See also
cmd::CommandQueue
Referenced by modules::Module::addCommand().