Giraffe: giraffe::gdl::Packet Class Reference
giraffe::gdl::Packet Class Reference
The packet class is used in the transport and network layers. It contains some extra information.
#include <gdl_packet.hpp>
Public Types
enum class PacketType : uint8_t {
UNKNOWN , BROADCAST , EXCHANGE , LOCATION ,
PING , PING_RESPONSE , ACK
}
enum class Type : uint8_t { BROADCAST , EXCHANGE , LOCATION }
Public Member Functions
Packet ()=default
Packet (const Message &message)
std::string getData () const
uint32_t getIdentifier () const
std::string getIdentifierString () const
json getJson () const
Location getLocation () const
PacketType getPacketType () const
uint32_t getSendAttempts () const
Type getType () const
void incrementSendAttempts ()
bool setBroadcastMessage (std::string broadcast_message, uint32_t identifier)
void setData (std::string data)
bool setExchangeMessage (std::string exchange_message, uint32_t identifier)
void setIdentifier (uint32_t identifier)
bool setIdentifierFromHex (const std::string &identifier)
void setLocation (Location location)
bool setLocationMessage (Location location, uint32_t identifier)
void setPacketType (PacketType packet_type)
void setType (Type type)
Private Attributes
std::string data_ {}
uint32_t identifier_ = 0
Location location_ {}
PacketType packet_type_ = PacketType::UNKNOWN
uint32_t send_attempts_ = 0
Type type_ {Type::BROADCAST}
Detailed Description
The packet class is used in the transport and network layers. It contains some extra information.
Member Enumeration Documentation
PacketType
enum giraffe::gdl::Packet::PacketType : uint8_t strong
Enumerator
UNKNOWN
BROADCAST
EXCHANGE
LOCATION
PING
PING_RESPONSE
ACK
Type
enum giraffe::gdl::Message::Type : uint8_t strong inherited
Enumerator
BROADCAST
EXCHANGE
LOCATION
Constructor & Destructor Documentation
Packet() [1/2]
giraffe::gdl::Packet::Packet () default
Packet() [2/2]
giraffe::gdl::Packet::Packet (const Message & message) inline
Member Function Documentation
setPacketType()
void giraffe::gdl::Packet::setPacketType (PacketType packet_type) inline
References packet_type_.
Referenced by giraffe::gdl::NetworkLayer::rxPacket(), giraffe::gdl::TransportLayer::send(), giraffe::gdl::TransportLayer::sendAck(), giraffe::gdl::TransportLayer::sendPing(), and giraffe::gdl::TransportLayer::sendPingResponse().
getPacketType()
PacketType giraffe::gdl::Packet::getPacketType () const inline
References packet_type_.
Referenced by giraffe::gdl::TransportLayer::exchangeWaitingForAckState(), giraffe::gdl::TransportLayer::idleState(), and giraffe::gdl::NetworkLayer::txPacket().
incrementSendAttempts()
void giraffe::gdl::Packet::incrementSendAttempts () inline
References send_attempts_.
Referenced by giraffe::gdl::TransportLayer::exchangeSendState().
getSendAttempts()
uint32_t giraffe::gdl::Packet::getSendAttempts () const inline
References send_attempts_.
Referenced by giraffe::gdl::TransportLayer::exchangeSendState().
setBroadcastMessage()
bool giraffe::gdl::Message::setBroadcastMessage (std::string broadcast_message, uint32_t identifier) inline inherited
References giraffe::gdl::Message::BROADCAST, giraffe::gdl::Message::data_, giraffe::gdl::GDL_MESSAGE_DATA_MAX_SIZE, giraffe::gdl::Message::identifier_, and giraffe::gdl::Message::type_.
Referenced by giraffe::gdl::GdlServer::handleSetNewBroadcast().
setExchangeMessage()
bool giraffe::gdl::Message::setExchangeMessage (std::string exchange_message, uint32_t identifier) inline inherited
References giraffe::gdl::Message::data_, giraffe::gdl::Message::EXCHANGE, giraffe::gdl::GDL_MESSAGE_DATA_MAX_SIZE, giraffe::gdl::Message::identifier_, and giraffe::gdl::Message::type_.
Referenced by giraffe::gdl::GdlServer::handleSetNewExchange(), giraffe::gdl::TransportLayer::idleState(), main(), and giraffe::gdl::DataLink::sendText().
setLocationMessage()
bool giraffe::gdl::Message::setLocationMessage (Location location, uint32_t identifier) inline inherited
Todo:
validate values
References giraffe::gdl::Message::data_, giraffe::gdl::Message::identifier_, giraffe::gdl::Message::LOCATION, giraffe::gdl::Message::location_, and giraffe::gdl::Message::type_.
getIdentifier()
uint32_t giraffe::gdl::Message::getIdentifier () const inline inherited
References giraffe::gdl::Message::identifier_.
Referenced by giraffe::gdl::TransportLayer::exchangeSendState(), giraffe::gdl::TransportLayer::exchangeWaitingForAckState(), and giraffe::gdl::TransportLayer::idleState().
setIdentifier()
void giraffe::gdl::Message::setIdentifier (uint32_t identifier) inline inherited
References giraffe::gdl::Message::identifier_.
Referenced by giraffe::gdl::TransportLayer::sendAck(), giraffe::gdl::TransportLayer::sendPing(), and giraffe::gdl::TransportLayer::sendPingResponse().
setIdentifierFromHex()
bool giraffe::gdl::Message::setIdentifierFromHex (const std::string & identifier) inline inherited
References giraffe::gdl::Message::identifier_.
Referenced by giraffe::gdl::NetworkLayer::rxPacket().
getIdentifierString()
std::string giraffe::gdl::Message::getIdentifierString () const inline inherited
References giraffe::gdl::Message::identifier_.
Referenced by giraffe::gdl::Message::getJson(), modules::TelemetryModule::processTelemetryMessageQueue(), and giraffe::gdl::NetworkLayer::txPacket().
getType()
Type giraffe::gdl::Message::getType () const inline inherited
References giraffe::gdl::Message::type_.
Referenced by giraffe::gdl::Message::getJson(), main(), modules::TelemetryModule::processTelemetryMessageQueue(), giraffe::gdl::TransportLayer::send(), and giraffe::gdl::DataLink::sendMessage().
setType()
void giraffe::gdl::Message::setType (Type type) inline inherited
References giraffe::gdl::Message::type_.
setData()
void giraffe::gdl::Message::setData (std::string data) inline inherited
References giraffe::gdl::Message::data_.
Referenced by giraffe::gdl::NetworkLayer::rxPacket().
getData()
std::string giraffe::gdl::Message::getData () const inline inherited
References giraffe::gdl::Message::data_.
Referenced by giraffe::gdl::Message::getJson(), giraffe::gdl::TransportLayer::idleState(), main(), modules::TelemetryModule::processTelemetryMessageQueue(), and giraffe::gdl::NetworkLayer::txPacket().
setLocation()
void giraffe::gdl::Message::setLocation (Location location) inline inherited
References giraffe::gdl::Message::location_.
Referenced by giraffe::gdl::NetworkLayer::rxPacket(), and modules::TelemetryModule::sendAprsPositionPacket().
getLocation()
Location giraffe::gdl::Message::getLocation () const inline inherited
References giraffe::gdl::Message::location_.
Referenced by giraffe::gdl::Message::getJson(), and giraffe::gdl::NetworkLayer::txAprsPositionPacket().
getJson()
json giraffe::gdl::Message::getJson () const inline inherited
References giraffe::gdl::Message::Location::altitude, giraffe::gdl::Message::BROADCAST, giraffe::gdl::Message::EXCHANGE, giraffe::gdl::Message::getData(), giraffe::gdl::Message::getIdentifierString(), giraffe::gdl::Message::getLocation(), giraffe::gdl::Message::getType(), giraffe::gdl::Message::Location::heading, giraffe::gdl::Message::Location::latitude, giraffe::gdl::Message::LOCATION, giraffe::gdl::Message::Location::longitude, giraffe::gdl::Message::Location::speed, and giraffe::gdl::Message::Location::time_code.
Referenced by giraffe::gdl::GdlServer::handleRequestReceivedMessages(), and giraffe::gdl::GdlServer::handleRequestSentMessages().
Member Data Documentation
packet_type_
PacketType giraffe::gdl::Packet::packet_type_ = PacketType::UNKNOWN private
Referenced by getPacketType(), and setPacketType().
send_attempts_
uint32_t giraffe::gdl::Packet::send_attempts_ = 0 private
Referenced by getSendAttempts(), and incrementSendAttempts().
identifier_
uint32_t giraffe::gdl::Message::identifier_ = 0 private inherited
Referenced by giraffe::gdl::Message::getIdentifier(), giraffe::gdl::Message::getIdentifierString(), giraffe::gdl::Message::setBroadcastMessage(), giraffe::gdl::Message::setExchangeMessage(), giraffe::gdl::Message::setIdentifier(), giraffe::gdl::Message::setIdentifierFromHex(), and giraffe::gdl::Message::setLocationMessage().
type_
Type giraffe::gdl::Message::type_ {Type::BROADCAST} private inherited
Referenced by giraffe::gdl::Message::getType(), giraffe::gdl::Message::setBroadcastMessage(), giraffe::gdl::Message::setExchangeMessage(), giraffe::gdl::Message::setLocationMessage(), and giraffe::gdl::Message::setType().
data_
std::string giraffe::gdl::Message::data_ {} private inherited
Referenced by giraffe::gdl::Message::getData(), giraffe::gdl::Message::setBroadcastMessage(), giraffe::gdl::Message::setData(), giraffe::gdl::Message::setExchangeMessage(), and giraffe::gdl::Message::setLocationMessage().
location_
Location giraffe::gdl::Message::location_ {} private inherited
Referenced by giraffe::gdl::Message::getLocation(), giraffe::gdl::Message::setLocation(), and giraffe::gdl::Message::setLocationMessage().