Giraffe: data::LogStream Class Reference
data::LogStream Class Reference
#include <streams.hpp>
Public Member Functions
void addPacket (LogPacket packet)
void debug (node::Identification source, std::string info="", DiagnosticId log_id=DiagnosticId::GENERIC_debug)
void error (node::Identification source, DiagnosticId error_id, std::string info="")
void errorBoosterSeatException (const node::Identification source, const DiagnosticId error_id, const bst::BoosterSeatException &exception)
void errorStdException (const node::Identification source, const DiagnosticId error_id, const std::exception &exception)
int getNumPackets ()
bool getPacket (LogPacket &packet)
int getTotalPackets ()
void info (node::Identification source, std::string info="", DiagnosticId log_id=DiagnosticId::GENERIC_info)
void reset ()
Private Attributes
int current_packets_
std::queue< LogPacket > packet_queue_
std::mutex stream_mutex_
std::atomic< int > total_packets_
Member Function Documentation
error()
void data::LogStream::error (node::Identification source, DiagnosticId error_id, std::string info = "") inline
References data::Stream< LogPacket >::addPacket(), data::LogPacket::ERROR, data::LogPacket::id, data::LogPacket::info, info(), data::LogPacket::level, data::BaseStreamPacket::resetTime(), and data::BaseStreamPacket::source.
Referenced by cfg::CfgSection::error(), giraffe::Logger::error(), RequestRouter::handleCommandRequest(), FlightRunner::processCommand(), FlightRunner::routeCommand(), FlightRunner::setLaunchPosition(), validation::setValidEnum(), and validation::setValidValue().
info()
void data::LogStream::info (node::Identification source, std::string info = "", DiagnosticId log_id = DiagnosticId::GENERIC_info) inline
References data::Stream< LogPacket >::addPacket(), data::LogPacket::id, data::LogPacket::INFO, data::LogPacket::info, data::LogPacket::level, data::BaseStreamPacket::resetTime(), and data::BaseStreamPacket::source.
Referenced by debug(), error(), and giraffe::Logger::info().
debug()
void data::LogStream::debug (node::Identification source, std::string info = "", DiagnosticId log_id = DiagnosticId::GENERIC_debug) inline
References data::Stream< LogPacket >::addPacket(), data::LogPacket::DEBUG, data::LogPacket::id, data::LogPacket::info, info(), data::LogPacket::level, data::BaseStreamPacket::resetTime(), and data::BaseStreamPacket::source.
Referenced by giraffe::Logger::debug().
errorBoosterSeatException()
void data::LogStream::errorBoosterSeatException (const node::Identification source, const DiagnosticId error_id, const bst::BoosterSeatException & exception) inline
References data::Stream< LogPacket >::addPacket(), data::LogPacket::ERROR, data::LogPacket::id, data::LogPacket::info, data::LogPacket::level, data::BaseStreamPacket::resetTime(), data::BaseStreamPacket::source, and util::to_string().
errorStdException()
void data::LogStream::errorStdException (const node::Identification source, const DiagnosticId error_id, const std::exception & exception) inline
References data::Stream< LogPacket >::addPacket(), data::LogPacket::ERROR, data::LogPacket::id, data::LogPacket::info, data::LogPacket::level, data::BaseStreamPacket::resetTime(), and data::BaseStreamPacket::source.
addPacket()
void data::Stream< LogPacket >::addPacket (LogPacket packet) inline inherited
getPacket()
bool data::Stream< LogPacket >::getPacket (LogPacket & packet) inline inherited
getNumPackets()
int data::Stream< LogPacket >::getNumPackets () inline inherited
getTotalPackets()
int data::Stream< LogPacket >::getTotalPackets () inline inherited
reset()
void data::Stream< LogPacket >::reset () inline inherited
Member Data Documentation
stream_mutex_
std::mutex data::Stream< LogPacket >::stream_mutex_ private inherited
packet_queue_
std::queue<LogPacket > data::Stream< LogPacket >::packet_queue_ private inherited
current_packets_
int data::Stream< LogPacket >::current_packets_ private inherited
total_packets_
std::atomic<int> data::Stream< LogPacket >::total_packets_ private inherited