Giraffe: cfg::Extensions Class Reference
cfg::Extensions Class Reference
The extensions section of the configuration.
#include <cfg_extensions.hpp>
Public Member Functions
Extensions (data::Streams &streams)
bool addExtension (const ExtensionMetadata &metadata)
Add an extension to the configuration.
std::vector< ExtensionMetadata > getExtensions () const
Returns a copy of the extension metadata configuration vector.
Json getJson () const
bool removeExtension (const std::string &name)
Remove an extension from the configuration by name.
void setFromJson (const Json &json_data)
void toggleExtension (const std::string &name, bool enabled)
Enable or disable an extension by name.
bool updateExtension (const std::string &name, const ExtensionMetadata &metadata)
Update an extension given its name and new metadata.
Protected Member Functions
void error (DiagnosticId diagnostic_id, const std::string &info="")
Logs a debug message.
Protected Attributes
std::mutex cfg_lock_ = std::mutex()
data::Streams & streams_
Private Member Functions
bool doesNameExist (const std::string &name) const
Checks if an extension with the given name exists.
Private Attributes
std::vector< ExtensionMetadata > extensions_ {}
Detailed Description
The extensions section of the configuration.
Constructor & Destructor Documentation
Extensions()
cfg::Extensions::Extensions (data::Streams & streams) inline
Member Function Documentation
setFromJson()
void cfg::Extensions::setFromJson (const Json & json_data)
References cfg::CfgSection::cfg_lock_, doesNameExist(), cfg::CfgSection::error(), extensions_, data::Streams::log, cfg::ExtensionMetadata::name, cfg::ExtensionMetadata::setFromJson(), cfg::CfgSection::streams_, and util::to_string().
getJson()
Json cfg::Extensions::getJson () const
References cfg::CfgSection::cfg_lock_, and extensions_.
addExtension()
bool cfg::Extensions::addExtension (const ExtensionMetadata & metadata)
Add an extension to the configuration.
Warning
This does not check for validity!
Parameters
metadata The metadata for the extension to add.
References cfg::CfgSection::cfg_lock_, doesNameExist(), cfg::CfgSection::error(), extensions_, and metadata.
removeExtension()
bool cfg::Extensions::removeExtension (const std::string & name)
Remove an extension from the configuration by name.
If the extension does not exist, nothing changes but an error is logged.
Parameters
name The name of the extension to remove.
References cfg::CfgSection::cfg_lock_, cfg::CfgSection::error(), and extensions_.
updateExtension()
bool cfg::Extensions::updateExtension (const std::string & name, const ExtensionMetadata & metadata)
Update an extension given its name and new metadata.
Parameters
name - The name of the extension to update
metadata - The new metadata for the extension (can have a different name)
Returns
true - If the extension existed and was updated
false - If the extension did not exist or could not be updated
References cfg::CfgSection::cfg_lock_, cfg::CfgSection::error(), extensions_, and metadata.
toggleExtension()
void cfg::Extensions::toggleExtension (const std::string & name, bool enabled)
Enable or disable an extension by name.
If an extension with the given name does not exist, nothing changes but an error is logged. If the extension is already in the state requested, nothing happens.
Parameters
name The name of the extension to toggle.
enabled Whether or not the extension should be enabled.
References cfg::CfgSection::cfg_lock_, cfg::CfgSection::error(), and extensions_.
getExtensions()
std::vector< ExtensionMetadata > cfg::Extensions::getExtensions () const
Returns a copy of the extension metadata configuration vector.
Returns
std::vector<ExtensionMetadata> All extension metadata loaded.
References cfg::CfgSection::cfg_lock_, and extensions_.
doesNameExist()
bool cfg::Extensions::doesNameExist (const std::string & name) const private
Checks if an extension with the given name exists.
Warning
This function does not lock the cfg_lock_ mutex.
Parameters
name The name of the extension to check for.
Returns
true If the extension exists.
false If the extension does not exist.
References extensions_.
Referenced by addExtension(), and setFromJson().
error()
void cfg::CfgSection::error (DiagnosticId diagnostic_id, const std::string & info = "") inline protected inherited
Logs a debug message.
Note
This currently isn't used as the rest is autogenerated, but it really should be.
Parameters
diagnostic_id The id of the log.
info The information to log.
References node::CONFIGURATION, data::LogStream::error(), data::Streams::log, and cfg::CfgSection::streams_.
Referenced by cfg::AdcMappings::addAdcConfig(), addExtension(), cfg::AdcMappings::removeAdcConfig(), removeExtension(), cfg::AdcMappings::setFromJson(), setFromJson(), toggleExtension(), cfg::AdcMappings::updateAdcConfig(), and updateExtension().
Member Data Documentation
extensions_
std::vector<ExtensionMetadata> cfg::Extensions::extensions_ {} private
Referenced by addExtension(), doesNameExist(), getExtensions(), getJson(), removeExtension(), setFromJson(), toggleExtension(), and updateExtension().
cfg_lock_
std::mutex cfg::CfgSection::cfg_lock_ = std::mutex() mutable protected inherited
Referenced by cfg::AdcMappings::addAdcConfig(), addExtension(), cfg::AdcMappings::getAdcConfigs(), getExtensions(), cfg::AdcMappings::getJson(), getJson(), cfg::AdcMappings::removeAdcConfig(), removeExtension(), cfg::AdcMappings::setFromJson(), setFromJson(), toggleExtension(), cfg::AdcMappings::updateAdcConfig(), and updateExtension().
streams_
data::Streams& cfg::CfgSection::streams_ protected inherited
Referenced by cfg::CfgSection::error(), cfg::AdcMappings::setFromJson(), and setFromJson().