Giraffe: PredictionParameters Class Reference
PredictionParameters Class Reference
A class that contains and updates the parameters used to detect the flight phase.
#include <prediction_parameters.hpp>
Classes
struct Parameter
A structure that represents the parameters that are used for flight phase detection.
Public Member Functions
PredictionParameters (const PredictionParameters &)=delete
Delete the copy constructor.
PredictionParameters (data::SharedData &shared_data)
Default constructor.
PredictionParameters (PredictionParameters &&)=delete
Delete the move constructor.
~PredictionParameters ()=default
Default destructor.
Parameter getParameter (Parameter::Id id) const
Get a parameter by its ID.
PredictionParameters & operator= (const PredictionParameters &)=delete
Delete the copy assignment operator.
void updateParameters ()
Updates all of the parameters.
Private Member Functions
double applyInvalidFilter (Parameter::Id id, double value)
Applies a filter to a parameter. Does not update the parameter. or care if it's valid.
void updateParameter (Parameter::Id id, double newValue, bool valid=true, bool digital=false, bool digitalValue=false)
Validates, filters, and updates a parameter's value.
bool validateParameter (Parameter::Id id, double value)
Validates a parameter.
Private Attributes
data::blocks::Block< data::blocks::CalculatedData > & calculated_data_
data::FlightData & flight_data_
data::blocks::Block< data::blocks::ImuData > & imu_data_
data::blocks::Block< data::blocks::LocationData > & location_data_
std::array< Parameter, static_cast< uint8_t >(Parameter::Id::NUM_PARAMETERS)> parameters_
An array that contains all of the parameters.
Detailed Description
A class that contains and updates the parameters used to detect the flight phase.
Constructor & Destructor Documentation
PredictionParameters() [1/3]
PredictionParameters::PredictionParameters (data::SharedData & shared_data)
Default constructor.
References giraffe_assert, and parameters_.
~PredictionParameters()
PredictionParameters::~PredictionParameters () default
Default destructor.
PredictionParameters() [2/3]
PredictionParameters::PredictionParameters (const PredictionParameters &) delete
Delete the copy constructor.
PredictionParameters() [3/3]
PredictionParameters::PredictionParameters (PredictionParameters &&) delete
Delete the move constructor.
Member Function Documentation
operator=()
PredictionParameters & PredictionParameters::operator= (const PredictionParameters &) delete
Delete the copy assignment operator.
getParameter()
Parameter PredictionParameters::getParameter (Parameter::Id id) const inline
Get a parameter by its ID.
Parameters
id The ID of the parameter to get.
References giraffe_assert, PredictionParameters::Parameter::NUM_PARAMETERS, and parameters_.
Referenced by FlightPhasePredictor::getPointsFromRule(), and DetectionDataTest::validateParametersInInitialState().
updateParameters()
void PredictionParameters::updateParameters () inline
Updates all of the parameters.
Todo:
The GPS data must be recent, the current fix should be updated by the data module so this check should be redundant. Get rid of it if it is.
References calculated_data_, PredictionParameters::Parameter::DISTANCE_FROM_GROUND, PredictionParameters::Parameter::DISTANCE_FROM_LAUNCH, PredictionParameters::Parameter::DISTANCE_TRAVELED, data::FIX_2D, data::FIX_3D, flight_data_, data::blocks::Block< T >::get(), data::FlightData::getMissionClockSeconds(), data::FlightData::getUptimeSeconds(), PredictionParameters::Parameter::GPS_ALTITUDE, PredictionParameters::Parameter::GPS_HORIZONTAL_SPEED, PredictionParameters::Parameter::GPS_HORIZONTAL_SPEED_1MIN, PredictionParameters::Parameter::GPS_VERTICAL_SPEED, PredictionParameters::Parameter::GPS_VERTICAL_SPEED_1MIN, data::blocks::LocationData::have_gps_source, location_data_, PredictionParameters::Parameter::MISSION_CLOCK, PredictionParameters::Parameter::PRESSURE_ALTITUDE, PredictionParameters::Parameter::PRESSURE_VERTICAL_SPEED, PredictionParameters::Parameter::PRESSURE_VERTICAL_SPEED_1MIN, PredictionParameters::Parameter::UP_TIME, and updateParameter().
Referenced by FlightPhasePredictor::update().
updateParameter()
void PredictionParameters::updateParameter (Parameter::Id id, double newValue, bool valid = true, bool digital = false, bool digitalValue = false) inline private
Validates, filters, and updates a parameter's value.
Parameters
id - The ID of the parameter to update.
newValue - The new value of the parameter.
valid - (default true) Set to false to mark the parameter as invalid before validation.
References applyInvalidFilter(), giraffe_assert, PredictionParameters::Parameter::NUM_PARAMETERS, parameters_, and validateParameter().
Referenced by updateParameters().
validateParameter()
bool PredictionParameters::validateParameter (Parameter::Id id, double value) inline private
Validates a parameter.
Parameters
id - The ID of the parameter to validate.
value - The value of the parameter to validate.
References giraffe_assert, PredictionParameters::Parameter::IN_RANGE, PredictionParameters::Parameter::NONE, and parameters_.
Referenced by updateParameter().
applyInvalidFilter()
double PredictionParameters::applyInvalidFilter (Parameter::Id id, double value) inline private
Applies a filter to a parameter. Does not update the parameter. or care if it's valid.
Parameters
id - The ID of the parameter to filter.
value - The value to filter.
Returns
The filtered value.
References PredictionParameters::Parameter::ALWAYS_UPDATE, PredictionParameters::Parameter::CLAMP_IN_RANGE, PredictionParameters::Parameter::DO_NOT_UPDATE, giraffe_assert, parameters_, and PredictionParameters::Parameter::ZERO_IF_INVALID.
Referenced by updateParameter().
Member Data Documentation
parameters_
std::array<Parameter, static_cast<uint8_t>(Parameter::Id::NUM_PARAMETERS)> PredictionParameters::parameters_ private
An array that contains all of the parameters.
Referenced by PredictionParameters(), applyInvalidFilter(), getParameter(), updateParameter(), and validateParameter().
flight_data_
data::FlightData& PredictionParameters::flight_data_ private
Referenced by updateParameters().
calculated_data_
data::blocks::Block<data::blocks::CalculatedData>& PredictionParameters::calculated_data_ private
Referenced by updateParameters().
location_data_
data::blocks::Block<data::blocks::LocationData>& PredictionParameters::location_data_ private
Referenced by updateParameters().
imu_data_
data::blocks::Block<data::blocks::ImuData>& PredictionParameters::imu_data_ private