Giraffe: cmd::CommandQueue Class Reference
cmd::CommandQueue Class Reference
Used within modules to queue commands to be processed.
#include <command.hpp>
Public Member Functions
CommandQueue (node::Identification this_destination)
bool addCommand (Command command)
Adds a command to the queue.
bool getCommand (Command &command)
Gets the next command in the queue.
Private Attributes
std::mutex lock_ = std::mutex()
Mutex lock for the queue as multiple threads may be accessing it.
std::queue< Command > queue_ = std::queue<Command>()
The queue of commands.
node::Identification this_destination_
The destination of this command queue. Used to filter commands.
Detailed Description
Used within modules to queue commands to be processed.
Constructor & Destructor Documentation
CommandQueue()
cmd::CommandQueue::CommandQueue (node::Identification this_destination) inline
Member Function Documentation
addCommand()
bool cmd::CommandQueue::addCommand (Command command) inline
Adds a command to the queue.
Parameters
command The command to add.
Returns
true if the command was added successfully (space in the queue). False otherwise.
References cmd::K_MAX_COMMAND_QUEUE_SIZE, lock_, and queue_.
Referenced by modules::Module::addCommand().
getCommand()
bool cmd::CommandQueue::getCommand (Command & command) inline
Gets the next command in the queue.
Parameters
command (out) The command to populate.
Returns
true if a command was retrieved. If the queue is empty, this will return false.
References lock_, and queue_.
Member Data Documentation
this_destination_
node::Identification cmd::CommandQueue::this_destination_ private
The destination of this command queue. Used to filter commands.
lock_
std::mutex cmd::CommandQueue::lock_ = std::mutex() private
Mutex lock for the queue as multiple threads may be accessing it.
Referenced by addCommand(), and getCommand().
queue_
std::queue<Command> cmd::CommandQueue::queue_ = std::queue<Command>() private
The queue of commands.
Referenced by addCommand(), and getCommand().