Giraffe: data::ErrorFrame Class Reference
data::ErrorFrame Class Reference
The error frame.
#include <error_frame.hpp>
Public Member Functions
ErrorFrame ()=default
~ErrorFrame ()=default
void addError (const data::LogPacket &packet)
Add an error (LogPacket) to the error frame.
void clearAllErrors ()
Clear all errors from the error frame.
void clearError (DiagnosticId id)
Clear an individual error from the frame by id.
std::vector< DiagnosticId > getActiveErrorIds () const
Get all active error ids that are currently in the frame.
bool getError (DiagnosticId id, ErrorFrameItem &item) const
Returns the error with the given id if it exists in the frame.
std::unordered_map< DiagnosticId, ErrorFrameItem > getFullFrame () const
Get the full error frame.
bool isActive (DiagnosticId id) const
Returns true if the error is active in the frame.
bool lastOccurrence (DiagnosticId id, bst::clck::TimePoint &time) const
Returns a time point of when the last time that a specified error was reported. If the error is not in the frame, false is returned, otherwise true.
int numActiveErrors () const
The number of active errors in the frame.
int numOccurrences (DiagnosticId id) const
Returns the number of occurrences of an error. If the error is not in the frame, 0 is returned.
int numTotalErrors () const
The total number of errors that have been added to the frame. This is not the number of active errors, but the total number of errors that have been added to the frame.
bst::clck::TimePoint timeOfLastErrorReported () const
Returns a time point representing when the last time was that an error was added to the frame.
Private Member Functions
void clear ()
Clears all contents of the frame.
bool get (const DiagnosticId key, ErrorFrameItem &data) const
Get an item from the frame.
std::unordered_map< DiagnosticId, ErrorFrameItem > getAll () const
bool in (const DiagnosticId &key) const
Returns true if an item is in the frame, false if it is not.
void insert (const DiagnosticId &key, const ErrorFrameItem &value)
Insert or replace an item.
bool remove (const DiagnosticId &key)
Removes an item from the frame.
int size () const
Returns the total items in the frame.
Private Attributes
std::mutex error_frame_mutex_ {}
Mutex for the error frame specifically.
std::unordered_map< DiagnosticId, ErrorFrameItem > frame_
std::mutex frame_lock_
bst::clck::TimePoint last_error_reported_ {}
The time of the last error reported.
int total_errors_ = 0
The total number of errors in the frame.
Detailed Description
The error frame.
Used to keep track of errors that have occurred in the system. Specifically, the number of occurrences of each error along with the first and last time the error was reported.
Constructor & Destructor Documentation
ErrorFrame()
data::ErrorFrame::ErrorFrame () default
~ErrorFrame()
data::ErrorFrame::~ErrorFrame () default
Member Function Documentation
addError()
void data::ErrorFrame::addError (const data::LogPacket & packet)
Add an error (LogPacket) to the error frame.
If the error already exists, it will be updated, otherwise it will be added to the frame.
Parameters
packet - The LogPacket to add.
References data::BaseStreamPacket::created_time, data::LogPacket::ERROR, error_frame_mutex_, data::Frame< DiagnosticId, ErrorFrameItem >::get(), data::Frame< ID, DATA >::get(), giraffe_assert, data::LogPacket::id, data::Frame< ID, DATA >::insert(), last_error_reported_, data::ErrorFrameItem::last_reported, data::LogPacket::level, and total_errors_.
Referenced by TEST().
clearError()
void data::ErrorFrame::clearError (DiagnosticId id)
Clear an individual error from the frame by id.
Parameters
id - The id of the error to clear.
References error_frame_mutex_, data::Frame< DiagnosticId, ErrorFrameItem >::get(), and data::Frame< ID, DATA >::remove().
clearAllErrors()
void data::ErrorFrame::clearAllErrors ()
Clear all errors from the error frame.
References data::Frame< ID, DATA >::clear(), error_frame_mutex_, and data::Frame< DiagnosticId, ErrorFrameItem >::get().
numTotalErrors()
int data::ErrorFrame::numTotalErrors () const
The total number of errors that have been added to the frame. This is not the number of active errors, but the total number of errors that have been added to the frame.
Returns
int - The total number of errors that have been added to the frame.
References error_frame_mutex_, data::Frame< DiagnosticId, ErrorFrameItem >::get(), and total_errors_.
Referenced by getErrorFrameData().
numActiveErrors()
int data::ErrorFrame::numActiveErrors () const
The number of active errors in the frame.
Returns
int - The number of active errors in the frame.
References error_frame_mutex_, data::Frame< DiagnosticId, ErrorFrameItem >::get(), and data::Frame< ID, DATA >::size().
Referenced by bit::test_case::runTestFCS_0001().
getError()
bool data::ErrorFrame::getError (DiagnosticId id, ErrorFrameItem & item) const
Returns the error with the given id if it exists in the frame.
If the error does not exist in the frame, the item will be left unmodified and false will be returned. Otherwise, the item will be populated with the error info and true will be returned.
Parameters
id - The id of the error to get.
item (out) - The item to populate with the error info.
Returns
true - The error was found in the frame.
false - The error was not found in the frame.
References error_frame_mutex_, data::Frame< DiagnosticId, ErrorFrameItem >::get(), and data::Frame< ID, DATA >::get().
getActiveErrorIds()
std::vector< DiagnosticId > data::ErrorFrame::getActiveErrorIds () const
Get all active error ids that are currently in the frame.
Returns
std::vector<DiagnosticId> - A vector of all active error ids.
References error_frame_mutex_, data::Frame< ID, DATA >::frame_, and data::Frame< DiagnosticId, ErrorFrameItem >::get().
Referenced by getErrorFrameData().
isActive()
bool data::ErrorFrame::isActive (DiagnosticId id) const
Returns true if the error is active in the frame.
Parameters
id - The id of the error to check.
Returns
true - The error is active in the frame.
false - The error is not active in the frame.
References error_frame_mutex_, data::Frame< DiagnosticId, ErrorFrameItem >::get(), and data::Frame< ID, DATA >::in().
Referenced by data::ErrorReporter::reportError().
numOccurrences()
int data::ErrorFrame::numOccurrences (DiagnosticId id) const
Returns the number of occurrences of an error. If the error is not in the frame, 0 is returned.
Parameters
id - The id of the error to check.
Returns
int - The number of occurrences of the error.
References error_frame_mutex_, data::Frame< DiagnosticId, ErrorFrameItem >::get(), data::Frame< ID, DATA >::get(), and data::ErrorFrameItem::occurrences.
timeOfLastErrorReported()
bst::clck::TimePoint data::ErrorFrame::timeOfLastErrorReported () const
Returns a time point representing when the last time was that an error was added to the frame.
Returns
bst::clck::TimePoint - The time the last error was added.
References error_frame_mutex_, data::Frame< DiagnosticId, ErrorFrameItem >::get(), and last_error_reported_.
lastOccurrence()
bool data::ErrorFrame::lastOccurrence (DiagnosticId id, bst::clck::TimePoint & time) const
Returns a time point of when the last time that a specified error was reported. If the error is not in the frame, false is returned, otherwise true.
Parameters
id - The id of the error to check.
time (out) - The time point of when the error was last reported.
Returns
true - The error was found in the frame.
false - The error was not found in the frame.
References error_frame_mutex_, data::Frame< DiagnosticId, ErrorFrameItem >::get(), data::Frame< ID, DATA >::get(), and data::ErrorFrameItem::last_reported.
getFullFrame()
std::unordered_map< DiagnosticId, ErrorFrameItem > data::ErrorFrame::getFullFrame () const
Get the full error frame.
Returns
std::unordered_map<DiagnosticId, ErrorFrameItem> - The error frame.
References error_frame_mutex_, data::Frame< ID, DATA >::frame_, and data::Frame< DiagnosticId, ErrorFrameItem >::get().
Referenced by data_middleware::DataFormatter::fullErrorFrame().
insert()
void data::Frame< DiagnosticId , ErrorFrameItem >::insert (const DiagnosticId & key, const ErrorFrameItem & value) inline inherited
Insert or replace an item.
in()
bool data::Frame< DiagnosticId , ErrorFrameItem >::in (const DiagnosticId & key) const inline inherited
Returns true if an item is in the frame, false if it is not.
Returns
true
false
get()
bool data::Frame< DiagnosticId , ErrorFrameItem >::get (const DiagnosticId key, ErrorFrameItem & data) const inline inherited
Get an item from the frame.
Parameters
key - The identifier of the item to get.
data - The data to be returned.
Returns
true - If the item was found.
false - If the item was not found.
clear()
void data::Frame< DiagnosticId , ErrorFrameItem >::clear () inline inherited
Clears all contents of the frame.
size()
int data::Frame< DiagnosticId , ErrorFrameItem >::size () const inline inherited
Returns the total items in the frame.
remove()
bool data::Frame< DiagnosticId , ErrorFrameItem >::remove (const DiagnosticId & key) inline inherited
Removes an item from the frame.
Parameters
key - The identifier of the item to remove.
Returns
true - If the item was removed.
false - If the item was not removed.
getAll()
std::unordered_map< DiagnosticId , ErrorFrameItem > data::Frame< DiagnosticId , ErrorFrameItem >::getAll () const inline inherited
Member Data Documentation
error_frame_mutex_
std::mutex data::ErrorFrame::error_frame_mutex_ {} mutable private
Mutex for the error frame specifically.
Referenced by addError(), clearAllErrors(), clearError(), getActiveErrorIds(), getError(), getFullFrame(), isActive(), lastOccurrence(), numActiveErrors(), numOccurrences(), numTotalErrors(), and timeOfLastErrorReported().
total_errors_
int data::ErrorFrame::total_errors_ = 0 private
The total number of errors in the frame.
Referenced by addError(), and numTotalErrors().
last_error_reported_
bst::clck::TimePoint data::ErrorFrame::last_error_reported_ {} private
The time of the last error reported.
Referenced by addError(), and timeOfLastErrorReported().
frame_
std::unordered_map<DiagnosticId , ErrorFrameItem > data::Frame< DiagnosticId , ErrorFrameItem >::frame_ protected inherited
frame_lock_
std::mutex data::Frame< DiagnosticId , ErrorFrameItem >::frame_lock_ mutable private inherited