Giraffe: giraffe::CommonLogger< LOG_SIZE > Class Template Reference
giraffe::CommonLogger< LOG_SIZE > Class Template Reference
#include <common_logger.hpp>
Public Member Functions
CommonLogger (LoggerLevel level=LoggerLevel::INFO, bool print_to_stdout=false)
~CommonLogger ()=default
void debug (const std::string &msg)
void error (const std::string &msg)
LoggerLevel getLevel () const
size_t getLogQueueSize () const
bool getPrintToStdout () const
void info (const std::string &msg)
bool popEntry (LoggerEntry &entry)
void setLevel (const LoggerLevel level)
void setPrintToStdout (const bool print_to_stdout)
void warn (const std::string &msg)
Private Member Functions
void log (const LoggerLevel level, const std::string &msg)
Private Attributes
LoggerLevel level_to_log_
std::queue< LoggerEntry > log_queue_ {}
bool print_to_stdout_
Constructor & Destructor Documentation
CommonLogger()
template<size_t LOG_SIZE> giraffe::CommonLogger< LOG_SIZE >::CommonLogger (LoggerLevel level = LoggerLevel::INFO, bool print_to_stdout = false) inline
~CommonLogger()
template<size_t LOG_SIZE> giraffe::CommonLogger< LOG_SIZE >::~CommonLogger () default
Member Function Documentation
debug()
template<size_t LOG_SIZE> void giraffe::CommonLogger< LOG_SIZE >::debug (const std::string & msg) inline
References giraffe::DEBUG, and giraffe::CommonLogger< LOG_SIZE >::log().
Referenced by giraffe::gdl::GdlServer::loadConfig(), giraffe::gdl::GdlServer::run(), and giraffe::gdl::GdlServer::saveConfig().
info()
template<size_t LOG_SIZE> void giraffe::CommonLogger< LOG_SIZE >::info (const std::string & msg) inline
References giraffe::INFO, and giraffe::CommonLogger< LOG_SIZE >::log().
Referenced by giraffe::gdl::GdlServer::handleSetConfig(), giraffe::gdl::GdlServer::handleSetNewBroadcast(), giraffe::gdl::GdlServer::handleSetNewExchange(), giraffe::gdl::GdlServer::loadConfig(), giraffe::gdl::GdlServer::run(), and giraffe::gdl::GdlServer::stop().
warn()
template<size_t LOG_SIZE> void giraffe::CommonLogger< LOG_SIZE >::warn (const std::string & msg) inline
References giraffe::CommonLogger< LOG_SIZE >::log(), and giraffe::WARN.
Referenced by giraffe::gdl::GdlServer::loadConfig(), giraffe::gdl::GdlServer::run(), giraffe::gdl::GdlServer::sendMessage(), and giraffe::gdl::GdlServer::setConfigFromJson().
error()
template<size_t LOG_SIZE> void giraffe::CommonLogger< LOG_SIZE >::error (const std::string & msg) inline
References giraffe::ERROR, and giraffe::CommonLogger< LOG_SIZE >::log().
Referenced by giraffe::gdl::GdlServer::handleSetNewExchange(), giraffe::gdl::GdlServer::loadConfig(), giraffe::gdl::GdlServer::run(), and giraffe::gdl::GdlServer::saveConfig().
setLevel()
template<size_t LOG_SIZE> void giraffe::CommonLogger< LOG_SIZE >::setLevel (const LoggerLevel level) inline
References giraffe::CommonLogger< LOG_SIZE >::level_to_log_.
Referenced by giraffe::gdl::GdlServer::setConfigFromJson().
getLevel()
template<size_t LOG_SIZE> LoggerLevel giraffe::CommonLogger< LOG_SIZE >::getLevel () const inline
References giraffe::CommonLogger< LOG_SIZE >::level_to_log_.
Referenced by giraffe::gdl::GdlServer::getConfigJson().
setPrintToStdout()
template<size_t LOG_SIZE> void giraffe::CommonLogger< LOG_SIZE >::setPrintToStdout (const bool print_to_stdout) inline
References giraffe::CommonLogger< LOG_SIZE >::print_to_stdout_.
Referenced by giraffe::gdl::GdlServer::setConfigFromJson().
getPrintToStdout()
template<size_t LOG_SIZE> bool giraffe::CommonLogger< LOG_SIZE >::getPrintToStdout () const inline
References giraffe::CommonLogger< LOG_SIZE >::print_to_stdout_.
Referenced by giraffe::gdl::GdlServer::getConfigJson().
popEntry()
template<size_t LOG_SIZE> bool giraffe::CommonLogger< LOG_SIZE >::popEntry (LoggerEntry & entry) inline
References giraffe::CommonLogger< LOG_SIZE >::log_queue_.
Referenced by giraffe::gdl::GdlServer::handleRequestLog().
getLogQueueSize()
template<size_t LOG_SIZE> size_t giraffe::CommonLogger< LOG_SIZE >::getLogQueueSize () const inline
References giraffe::CommonLogger< LOG_SIZE >::log_queue_.
Referenced by giraffe::gdl::GdlServer::handleRequestStatus().
log()
template<size_t LOG_SIZE> void giraffe::CommonLogger< LOG_SIZE >::log (const LoggerLevel level, const std::string & msg) inline private
References giraffe::CommonLogger< LOG_SIZE >::level_to_log_, giraffe::CommonLogger< LOG_SIZE >::log_queue_, and giraffe::CommonLogger< LOG_SIZE >::print_to_stdout_.
Referenced by giraffe::CommonLogger< LOG_SIZE >::debug(), giraffe::CommonLogger< LOG_SIZE >::error(), giraffe::CommonLogger< LOG_SIZE >::info(), and giraffe::CommonLogger< LOG_SIZE >::warn().
Member Data Documentation
level_to_log_
template<size_t LOG_SIZE> LoggerLevel giraffe::CommonLogger< LOG_SIZE >::level_to_log_ private
Referenced by giraffe::CommonLogger< LOG_SIZE >::getLevel(), giraffe::CommonLogger< LOG_SIZE >::log(), and giraffe::CommonLogger< LOG_SIZE >::setLevel().
print_to_stdout_
template<size_t LOG_SIZE> bool giraffe::CommonLogger< LOG_SIZE >::print_to_stdout_ private
Referenced by giraffe::CommonLogger< LOG_SIZE >::getPrintToStdout(), giraffe::CommonLogger< LOG_SIZE >::log(), and giraffe::CommonLogger< LOG_SIZE >::setPrintToStdout().
log_queue_
template<size_t LOG_SIZE> std::queue<LoggerEntry> giraffe::CommonLogger< LOG_SIZE >::log_queue_ {} private
Referenced by giraffe::CommonLogger< LOG_SIZE >::getLogQueueSize(), giraffe::CommonLogger< LOG_SIZE >::log(), and giraffe::CommonLogger< LOG_SIZE >::popEntry().