Giraffe: giraffe::gdl::AprsTelemetrySender Class Reference
giraffe::gdl::AprsTelemetrySender Class Reference
Manages sending APRS telemetry data via the Data Link.
#include <gdl_telemetry_sender.hpp>
Public Types
enum class Status : uint8_t {
UNKNOWN = 0 , DISABLED , WAITING_FOR_DATA , SEND_DATA_DELAY ,
SENDING_DATA , METADATA_WAIT_FOR_INITIAL_DATA , SENDING_METADATA
}
The status of the telemetry sender. Used for debugging/logging.
using TelemetryData = signal_easel::aprs::telemetry::TelemetryData
Public Member Functions
AprsTelemetrySender (Config &gdl_config)
Constructor for the telemetry sender.
~AprsTelemetrySender ()=default
Default destructor.
void addNewData (const TelemetryData &telemetry_data)
Add new telemetry data to the telemetry sender. If the telemetry sender is enabled, the send interval has elapsed, and we are waiting for data, the telemetry data will be sent on the next update.
uint32_t getNumDataPacketsAddedToQueue () const
Get the number of data packets that have been added to the queue.
Status getStatus () const
Get the status of the telemetry sender. This is used for monitoring, debugging, and logging, etc. Not use internally.
void sendTelemetryMetadata ()
Ask the telemetry sender to send the parameter name, unit/label, coefficient, and bit sense messages.
void update (IDataLink &gdl)
Periodic update function for the telemetry sender.
Static Public Member Functions
static constexpr std::string getStatusString (Status status)
Convert the status enum to a string for debugging/logging.
Private Types
enum class MetadataSendState {
NONE , WAIT_FOR_INITIAL_DATA , PARAMETER_NAMES , UNITS_LABELS ,
COEFFICIENTS , BIT_SENSE
}
State list for sending telemetry metadata.
Private Member Functions
uint16_t getNextSequenceNumber ()
Get the next sequence number for the telemetry data packet.
void sendMetadataStateMachine (IDataLink &gdl)
Handles sending telemetry metadata. Implemented with a simple state machine.
Private Attributes
Config & config_
General GDL configuration.
bst::Stopwatch data_send_interval_stopwatch_
Used to determine when to send telemetry data.
std::atomic< bool > initial_data_added_ = false
This flag indicates that a set of telemetry data was added to the sender. This must be true before telemetry metadata packets can be sent.
MetadataSendState metadata_send_state_ = MetadataSendState::NONE
The current state of the telemetry metadata sending state machine.
std::atomic< bool > new_data_available_ = false
A flag to indicate that new data is available to send. If there is no new data, there is no reason to send a telemetry data packet.
std::atomic< uint32_t > num_data_packets_added_to_queue_ = 0
The total number of data packets added to the queue. Reported in upper level GDL statistics.
uint16_t sequence_number_ = 0
The sequence number for the telemetry data packet. Incremented for each packet sent. Range is 0-999.
std::atomic< Status > status_ = Status::UNKNOWN
The status of the telemetry sender. Used for debugging/logging.
TelemetryData telemetry_data_ {}
The telemetry data to send.
std::mutex telemetry_data_lock_ {}
Mutex to protect the local telemetry data.
Detailed Description
Manages sending APRS telemetry data via the Data Link.
Warning
This class is contained within the Data Link. It's updated from an internal thread of the Data Link. Thought should be put into making sure that this class is thread safe.
Member Typedef Documentation
TelemetryData
using giraffe::gdl::AprsTelemetrySender::TelemetryData = signal_easel::aprs::telemetry::TelemetryData
Member Enumeration Documentation
Status
enum giraffe::gdl::AprsTelemetrySender::Status : uint8_t strong
The status of the telemetry sender. Used for debugging/logging.
Enumerator
UNKNOWN
DISABLED
WAITING_FOR_DATA
SEND_DATA_DELAY
SENDING_DATA
METADATA_WAIT_FOR_INITIAL_DATA
SENDING_METADATA
MetadataSendState
enum giraffe::gdl::AprsTelemetrySender::MetadataSendState strong private
State list for sending telemetry metadata.
Enumerator
NONE
WAIT_FOR_INITIAL_DATA
PARAMETER_NAMES
UNITS_LABELS
COEFFICIENTS
BIT_SENSE
Constructor & Destructor Documentation
AprsTelemetrySender()
giraffe::gdl::AprsTelemetrySender::AprsTelemetrySender (Config & gdl_config) inline
Constructor for the telemetry sender.
Parameters
gdl_config - The configuration for the GDL instance.
References data_send_interval_stopwatch_.
~AprsTelemetrySender()
giraffe::gdl::AprsTelemetrySender::~AprsTelemetrySender () default
Default destructor.
Member Function Documentation
getStatusString()
static constexpr std::string giraffe::gdl::AprsTelemetrySender::getStatusString (Status status) inline static constexpr
Convert the status enum to a string for debugging/logging.
Parameters
status - The status to convert.
Returns
The status as a string.
References DISABLED, METADATA_WAIT_FOR_INITIAL_DATA, SEND_DATA_DELAY, SENDING_DATA, SENDING_METADATA, UNKNOWN, and WAITING_FOR_DATA.
Referenced by giraffe::gdl::DataLink::getTelemetrySenderStatusString().
getStatus()
Status giraffe::gdl::AprsTelemetrySender::getStatus () const inline
Get the status of the telemetry sender. This is used for monitoring, debugging, and logging, etc. Not use internally.
Returns
The current status.
References status_.
Referenced by giraffe::gdl::DataLink::getTelemetrySenderStatus().
addNewData()
void giraffe::gdl::AprsTelemetrySender::addNewData (const TelemetryData & telemetry_data) inline
Add new telemetry data to the telemetry sender. If the telemetry sender is enabled, the send interval has elapsed, and we are waiting for data, the telemetry data will be sent on the next update.
Parameters
telemetry_data - The telemetry data to send.
References initial_data_added_, new_data_available_, telemetry_data_, and telemetry_data_lock_.
Referenced by giraffe::gdl::DataLink::updateTelemetryData().
sendTelemetryMetadata()
void giraffe::gdl::AprsTelemetrySender::sendTelemetryMetadata () inline
Ask the telemetry sender to send the parameter name, unit/label, coefficient, and bit sense messages.
Todo:
Another place where an error could be reported.
References config_, giraffe::gdl::Config::isAprsTelemetrySenderEnabled(), metadata_send_state_, NONE, and WAIT_FOR_INITIAL_DATA.
Referenced by giraffe::gdl::DataLink::sendTelemetryMetadataPackets().
update()
void giraffe::gdl::AprsTelemetrySender::update (IDataLink & gdl) inline
Periodic update function for the telemetry sender.
Todo:
Really need a way to report errors in GDL...
References config_, data_send_interval_stopwatch_, DISABLED, giraffe::gdl::Config::getAprsTelemetryDataIntervalMs(), getNextSequenceNumber(), giraffe::gdl::Config::isAprsTelemetrySenderEnabled(), metadata_send_state_, new_data_available_, NONE, num_data_packets_added_to_queue_, SEND_DATA_DELAY, SENDING_DATA, sendMetadataStateMachine(), giraffe::gdl::IDataLink::sendTelemetryData(), status_, telemetry_data_, telemetry_data_lock_, and WAITING_FOR_DATA.
Referenced by giraffe::gdl::DataLink::gdlThread().
getNumDataPacketsAddedToQueue()
uint32_t giraffe::gdl::AprsTelemetrySender::getNumDataPacketsAddedToQueue () const inline
Get the number of data packets that have been added to the queue.
Returns
The number of data packets added to the queue.
References num_data_packets_added_to_queue_.
Referenced by giraffe::gdl::DataLink::gdlThread().
getNextSequenceNumber()
uint16_t giraffe::gdl::AprsTelemetrySender::getNextSequenceNumber () inline private
Get the next sequence number for the telemetry data packet.
Returns
The next sequence number.
References sequence_number_.
Referenced by update().
sendMetadataStateMachine()
void giraffe::gdl::AprsTelemetrySender::sendMetadataStateMachine (IDataLink & gdl) inline private
Handles sending telemetry metadata. Implemented with a simple state machine.
References BIT_SENSE, COEFFICIENTS, initial_data_added_, metadata_send_state_, METADATA_WAIT_FOR_INITIAL_DATA, NONE, PARAMETER_NAMES, SENDING_METADATA, giraffe::gdl::IDataLink::sendTelemetryBitSense(), giraffe::gdl::IDataLink::sendTelemetryCoefficients(), giraffe::gdl::IDataLink::sendTelemetryParameterNames(), giraffe::gdl::IDataLink::sendTelemetryUnitsAndLabels(), status_, telemetry_data_, telemetry_data_lock_, UNITS_LABELS, and WAIT_FOR_INITIAL_DATA.
Referenced by update().
Member Data Documentation
metadata_send_state_
MetadataSendState giraffe::gdl::AprsTelemetrySender::metadata_send_state_ = MetadataSendState::NONE private
The current state of the telemetry metadata sending state machine.
Referenced by sendMetadataStateMachine(), sendTelemetryMetadata(), and update().
initial_data_added_
std::atomic<bool> giraffe::gdl::AprsTelemetrySender::initial_data_added_ = false private
This flag indicates that a set of telemetry data was added to the sender. This must be true before telemetry metadata packets can be sent.
Referenced by addNewData(), and sendMetadataStateMachine().
new_data_available_
std::atomic<bool> giraffe::gdl::AprsTelemetrySender::new_data_available_ = false private
A flag to indicate that new data is available to send. If there is no new data, there is no reason to send a telemetry data packet.
Referenced by addNewData(), and update().
telemetry_data_lock_
std::mutex giraffe::gdl::AprsTelemetrySender::telemetry_data_lock_ {} private
Mutex to protect the local telemetry data.
Referenced by addNewData(), sendMetadataStateMachine(), and update().
telemetry_data_
TelemetryData giraffe::gdl::AprsTelemetrySender::telemetry_data_ {} private
The telemetry data to send.
Referenced by addNewData(), sendMetadataStateMachine(), and update().
sequence_number_
uint16_t giraffe::gdl::AprsTelemetrySender::sequence_number_ = 0 private
The sequence number for the telemetry data packet. Incremented for each packet sent. Range is 0-999.
Referenced by getNextSequenceNumber().
data_send_interval_stopwatch_
bst::Stopwatch giraffe::gdl::AprsTelemetrySender::data_send_interval_stopwatch_ private
Used to determine when to send telemetry data.
A bst::Stopwatch was used instead of a bst::Timer because the configuration for the interval can be changed on the fly. The timer would need to expire before the new interval would take effect. If the timer was set to a very long interval this would be very annoying.
Referenced by AprsTelemetrySender(), and update().
config_
Config& giraffe::gdl::AprsTelemetrySender::config_ private
General GDL configuration.
Referenced by sendTelemetryMetadata(), and update().
status_
std::atomic<Status> giraffe::gdl::AprsTelemetrySender::status_ = Status::UNKNOWN private
The status of the telemetry sender. Used for debugging/logging.
Referenced by getStatus(), sendMetadataStateMachine(), and update().
num_data_packets_added_to_queue_
std::atomic<uint32_t> giraffe::gdl::AprsTelemetrySender::num_data_packets_added_to_queue_ = 0 private
The total number of data packets added to the queue. Reported in upper level GDL statistics.
Referenced by getNumDataPacketsAddedToQueue(), and update().