Giraffe: data::Misc Class Reference
data::Misc Class Reference
#include <shared_data.hpp>
Public Member Functions
FlightPhase getFlightPhase () const
Get the current flight phase.
int getUptimeSeconds () const
std::string getUptimeString () const
Get the uptime represented as a string in the format "HH:MM:SS".
Public Attributes
friend FlightRunner
This is here so that the flight runner alone can set the flight phase.
Private Attributes
std::atomic< FlightPhase > flight_phase = FlightPhase::UNKNOWN
The current flight phase.
const bst::clck::TimePoint start_time_ = bst::clck::now()
A time point representing the start time of the flight runner.
Member Function Documentation
getUptimeSeconds()
int data::Misc::getUptimeSeconds () const inline
References start_time_.
getUptimeString()
std::string data::Misc::getUptimeString () const inline
Get the uptime represented as a string in the format "HH:MM:SS".
Returns
std::string The uptime string.
References start_time_.
Referenced by data_middleware::DataFormatter::fullErrorFrame(), and data_middleware::DataFormatter::setupFrameStructure().
getFlightPhase()
FlightPhase data::Misc::getFlightPhase () const inline
Get the current flight phase.
Returns
FlightPhase The current flight phase.
References flight_phase.
Referenced by FlightRunner::detectFlightPhase().
Member Data Documentation
FlightRunner
friend data::Misc::FlightRunner
This is here so that the flight runner alone can set the flight phase.
start_time_
const bst::clck::TimePoint data::Misc::start_time_ = bst::clck::now() private
A time point representing the start time of the flight runner.
Referenced by getUptimeSeconds(), and getUptimeString().
flight_phase
std::atomic<FlightPhase> data::Misc::flight_phase = FlightPhase::UNKNOWN private
The current flight phase.
Referenced by getFlightPhase(), and FlightRunner::setFlightPhase().