Giraffe: FlightPhaseManager Class Reference
FlightPhaseManager Class Reference
This class manages everything related to flight phases and sequencing.
#include <flight_phase_manager.hpp>
Public Types
using Probability = FlightPhasePredictor::Probability
Public Member Functions
FlightPhaseManager (data::SharedData &shared_data, FlightPhase initial_phase=FlightPhase::UNKNOWN, size_t update_rate_ms=250, size_t filter_threshold=10)
Constructor.
~FlightPhaseManager ()=default
Destructor.
FlightPhase getCurrentFlightPhase () const
Get the current flight phase. This is the phase that the entire system will use.
bool requestLaunch ()
Request that the flight phase be changed to launch. Only valid if the current phase is pre-launch.
void setPreLaunch ()
Set the flight phase to pre-launch.
bool update ()
Update the flight phase manager.
Private Member Functions
bool flightPhaseUpdate (FlightPhase new_phase)
void forceRecovery (std::string reason)
void reportPhaseChangeInvalid (FlightPhase current_phase, FlightPhase new_phase, std::string extra_info)
void setFlightPhase (FlightPhase new_phase)
Private Attributes
FlightPhase flight_phase_ = FlightPhase::UNKNOWN
The current flight phase. Filtered and continually checked.
giraffe::Logger logger_
data::ErrorReporter phase_change_invalid_error_
bst::ConsecutiveValuesFilter< FlightPhase > phase_filter_
The filter for the flight phase. Filters out intermittent phase changes.
const size_t PHASE_FILTER_THRESHOLD_
The threshold for the phase filter.
FlightPhasePredictor phase_predictor_
The phase predictor. It generates the predicted phase along with a probability value for each phase.
bst::Timer phase_update_timer_ {static_cast<int>(UPDATE_RATE_)}
The timer for updating the phase.
bst::Timer phase_valid_watchdog_ {static_cast<int>(PHASE_VALID_TIMEOUT_MS)}
Probability prob_ {}
The probability of each phase.
data::SharedData & shared_data_
bool unknown_phase_error_reported_ = false
const size_t UPDATE_RATE_
The rate at which the predicted flight phase should be updated.
Static Private Attributes
constexpr static size_t PHASE_VALID_TIMEOUT_MS = 1000 * 60
Detailed Description
This class manages everything related to flight phases and sequencing.
Member Typedef Documentation
Probability
using FlightPhaseManager::Probability = FlightPhasePredictor::Probability
Constructor & Destructor Documentation
FlightPhaseManager()
FlightPhaseManager::FlightPhaseManager (data::SharedData & shared_data, FlightPhase initial_phase = FlightPhase::UNKNOWN, size_t update_rate_ms = 250, size_t filter_threshold = 10) inline
Constructor.
Parameters
shared_data - The shared data object.
initial_phase - The initial phase of the flight. Loaded from FlightRunnerData at startup. Defaults to UNKNOWN as a safety measure.
update_rate_ms - The rate at which the predicted flight phase should be updated. Calls to update() will need to be at or faster than this rate. The actual update rate is update_rate_ms * filter_threshold.
filter_threshold - The threshold for the phase filter.
References forceRecovery(), LAUNCH, and setFlightPhase().
~FlightPhaseManager()
FlightPhaseManager::~FlightPhaseManager () default
Destructor.
Member Function Documentation
update()
bool FlightPhaseManager::update () inline
Update the flight phase manager.
Returns
true if the phase changed, false otherwise.
References FlightPhasePredictor::Probability::ascent, FlightPhasePredictor::Probability::data_quality, FlightPhasePredictor::Probability::descent, data::SharedData::flight_data, flightPhaseUpdate(), FlightPhasePredictor::getPhaseProbability(), FlightPhasePredictor::getPredictedPhase(), FlightPhasePredictor::Probability::launch, phase_filter_, phase_predictor_, phase_update_timer_, FlightPhasePredictor::Probability::recovery, data::FlightData::setPhasePrediction(), shared_data_, and FlightPhasePredictor::update().
Referenced by FlightRunner::flightLogic(), and FlightPhaseManagerTest::tick().
getCurrentFlightPhase()
FlightPhase FlightPhaseManager::getCurrentFlightPhase () const inline
Get the current flight phase. This is the phase that the entire system will use.
Returns
The current flight phase.
References flight_phase_.
Referenced by FlightPhaseManagerTest::bringToAscent(), FlightPhaseManagerTest::bringToDescent(), FlightPhaseManagerTest::bringToLaunch(), and FlightRunner::processCommand().
requestLaunch()
bool FlightPhaseManager::requestLaunch () inline
Request that the flight phase be changed to launch. Only valid if the current phase is pre-launch.
References flight_phase_, LAUNCH, PRE_LAUNCH, and setFlightPhase().
Referenced by FlightPhaseManagerTest::bringToLaunch(), and FlightRunner::processCommand().
setPreLaunch()
void FlightPhaseManager::setPreLaunch () inline
Set the flight phase to pre-launch.
This could be a dangerous operation. It should only be called via a manual action.
References PRE_LAUNCH, and setFlightPhase().
Referenced by FlightPhaseManagerTest::bringToLaunch(), and FlightRunner::processCommand().
flightPhaseUpdate()
bool FlightPhaseManager::flightPhaseUpdate (FlightPhase new_phase) inline private
References ASCENT, DESCENT, giraffe::Logger::error(), flight_phase_, forceRecovery(), LAUNCH, logger_, NUM_PHASES, phase_valid_watchdog_, PRE_LAUNCH, RECOVERY, reportPhaseChangeInvalid(), setFlightPhase(), util::to_string(), UNKNOWN, and unknown_phase_error_reported_.
Referenced by update().
forceRecovery()
void FlightPhaseManager::forceRecovery (std::string reason) inline private
References giraffe::Logger::error(), logger_, RECOVERY, and setFlightPhase().
Referenced by FlightPhaseManager(), and flightPhaseUpdate().
setFlightPhase()
void FlightPhaseManager::setFlightPhase (FlightPhase new_phase) inline private
References data::CommandStream::addCommand(), data::DataStream::addData(), data::Streams::command, data::Streams::data, cmd::Command::destination, data::SharedData::flight_data, flight_phase_, node::FLIGHT_RUNNER, phase_filter_, data::FlightData::setFlightPhase(), shared_data_, data::SharedData::streams, and util::to_string().
Referenced by FlightPhaseManager(), flightPhaseUpdate(), forceRecovery(), requestLaunch(), and setPreLaunch().
reportPhaseChangeInvalid()
void FlightPhaseManager::reportPhaseChangeInvalid (FlightPhase current_phase, FlightPhase new_phase, std::string extra_info) inline private
References phase_change_invalid_error_, data::ErrorReporter::reportError(), and util::to_string().
Referenced by flightPhaseUpdate().
Member Data Documentation
flight_phase_
FlightPhase FlightPhaseManager::flight_phase_ = FlightPhase::UNKNOWN private
The current flight phase. Filtered and continually checked.
Referenced by flightPhaseUpdate(), getCurrentFlightPhase(), requestLaunch(), and setFlightPhase().
phase_predictor_
FlightPhasePredictor FlightPhaseManager::phase_predictor_ private
The phase predictor. It generates the predicted phase along with a probability value for each phase.
Referenced by update().
UPDATE_RATE_
const size_t FlightPhaseManager::UPDATE_RATE_ private
The rate at which the predicted flight phase should be updated.
PHASE_FILTER_THRESHOLD_
const size_t FlightPhaseManager::PHASE_FILTER_THRESHOLD_ private
The threshold for the phase filter.
phase_filter_
bst::ConsecutiveValuesFilter<FlightPhase> FlightPhaseManager::phase_filter_ private
Initial value:
{
      FlightPhase::UNKNOWN, PHASE_FILTER_THRESHOLD_}
The filter for the flight phase. Filters out intermittent phase changes.
Referenced by setFlightPhase(), and update().
prob_
Probability FlightPhaseManager::prob_ {} private
The probability of each phase.
phase_update_timer_
bst::Timer FlightPhaseManager::phase_update_timer_ {static_cast<int>(UPDATE_RATE_)} private
The timer for updating the phase.
Referenced by update().
PHASE_VALID_TIMEOUT_MS
constexpr static size_t FlightPhaseManager::PHASE_VALID_TIMEOUT_MS = 1000 * 60 static constexpr private
phase_valid_watchdog_
bst::Timer FlightPhaseManager::phase_valid_watchdog_ {static_cast<int>(PHASE_VALID_TIMEOUT_MS)} private
Referenced by flightPhaseUpdate().
shared_data_
data::SharedData& FlightPhaseManager::shared_data_ private
Referenced by setFlightPhase(), and update().
logger_
giraffe::Logger FlightPhaseManager::logger_ private
Initial value:
{shared_data_, node::Identification::FLIGHT_RUNNER,
                          "phase_mgr"}
Referenced by flightPhaseUpdate(), and forceRecovery().
unknown_phase_error_reported_
bool FlightPhaseManager::unknown_phase_error_reported_ = false private
Referenced by flightPhaseUpdate().
phase_change_invalid_error_
data::ErrorReporter FlightPhaseManager::phase_change_invalid_error_ private
Initial value:
{
      shared_data_, node::Identification::FLIGHT_RUNNER,
      DiagnosticId::FLIGHT_RUNNER_phaseChangeInvalid}
Referenced by reportPhaseChangeInvalid().