Giraffe: data::Stream< T > Class Template Reference
data::Stream< T > Class Template Reference
#include <streams.hpp>
Public Member Functions
Stream ()
void addPacket (T packet)
int getNumPackets ()
bool getPacket (T &packet)
int getTotalPackets ()
void reset ()
Private Attributes
int current_packets_ = 0
std::queue< T > packet_queue_
std::mutex stream_mutex_ = std::mutex()
std::atomic< int > total_packets_ = 0
Constructor & Destructor Documentation
Stream()
template<class T > data::Stream< T >::Stream () inline
Member Function Documentation
addPacket()
template<class T > void data::Stream< T >::addPacket (T packet) inline
References data::Stream< T >::current_packets_, data::Stream< T >::packet_queue_, data::Stream< T >::stream_mutex_, and data::Stream< T >::total_packets_.
Referenced by extension::Extension::data(), extension::Extension::dataWithSecondaryIdentifier(), extension::Extension::debug(), extension::Extension::error(), and extension::Extension::info().
getPacket()
template<class T > bool data::Stream< T >::getPacket (T & packet) inline
References data::Stream< T >::current_packets_, data::Stream< T >::packet_queue_, and data::Stream< T >::stream_mutex_.
Referenced by FlightPhaseManagerTest::dumpDataStream(), FakeSharedData::hasDataItem(), ConfigurationTest::printStreamErrors(), ExtensionTestFramework::printStreams(), modules::DataModule::processStream(), FlightPhaseManagerTest::validateHasDataItem(), FlightPhaseManagerTest::validateHasError(), FlightPhaseManagerTest::validateNoData(), and FlightPhaseManagerTest::validateNoError().
getNumPackets()
template<class T > int data::Stream< T >::getNumPackets () inline
References data::Stream< T >::current_packets_, and data::Stream< T >::stream_mutex_.
Referenced by FakeSharedData::hasDataItems(), FakeSharedData::hasLogItems(), ConfigurationTest::printStreamErrors(), and modules::DataModule::processStream().
getTotalPackets()
template<class T > int data::Stream< T >::getTotalPackets () inline
References data::Stream< T >::total_packets_.
Referenced by ExtensionTestFramework::getTotalDataPackets(), ExtensionTestFramework::getTotalGpsPackets(), ExtensionTestFramework::getTotalImuPackets(), ExtensionTestFramework::getTotalLogPackets(), and modules::DataModule::processStream().
reset()
template<class T > void data::Stream< T >::reset () inline
References data::Stream< T >::current_packets_, data::Stream< T >::packet_queue_, data::Stream< T >::stream_mutex_, and data::Stream< T >::total_packets_.
Referenced by FlightPhaseManagerTest::bringToAscent(), FlightPhaseManagerTest::bringToDescent(), and FlightPhaseManagerTest::bringToLaunch().
Member Data Documentation
stream_mutex_
template<class T > std::mutex data::Stream< T >::stream_mutex_ = std::mutex() private
Referenced by data::Stream< T >::addPacket(), data::Stream< T >::getNumPackets(), data::Stream< T >::getPacket(), and data::Stream< T >::reset().
packet_queue_
template<class T > std::queue<T> data::Stream< T >::packet_queue_ private
Referenced by data::Stream< T >::addPacket(), data::Stream< T >::getPacket(), and data::Stream< T >::reset().
current_packets_
template<class T > int data::Stream< T >::current_packets_ = 0 private
Referenced by data::Stream< T >::addPacket(), data::Stream< T >::getNumPackets(), data::Stream< T >::getPacket(), and data::Stream< T >::reset().
total_packets_
template<class T > std::atomic<int> data::Stream< T >::total_packets_ = 0 private
Referenced by data::Stream< T >::addPacket(), data::Stream< T >::getTotalPackets(), and data::Stream< T >::reset().