Giraffe: giraffe::Gpio Class Reference
giraffe::Gpio Class Reference
This class is used to interface extensions with the BCM Gpio pins.
#include <gpio.hpp>
Classes
struct Pin
A pin struct that contains the pin number, mode, and default.
Public Types
enum class PinMode { INPUT , OUTPUT , UNINITIALIZED }
The pin modes. Uninitialized is only used internally.
Public Member Functions
bool read (Pin pin)
Read the value of an input pin.
void releasePin (Pin pin)
Release a pin for use by another instance.
void setupPin (Pin pin)
A function to setup a pin for input or output.
void write (Pin pin, bool high)
Write a value to an output pin pin (HIGH or LOW)
Static Public Member Functions
static void deInitialize ()
Static function to close the BCM registers and reset the reserved pins.
static void initialize ()
Static initialization of the BCM registers.
static bool isInitialized ()
Check if the GPIO registers are mapped.
Private Member Functions
bool isOwner (const Pin &pin)
A function to check if the current instance owns a reserved pin.
bool isPinReserved (const Pin &pin)
A function to check if a pin has been reserved.
void reservePin (const Pin &pin)
A function to reserve a pin for use.
void setOwner (const Pin &pin)
A function to set the owner of a pin.
Private Attributes
uint32_t pins_owned_ = 0
Contains the pins owned by a particular instance of Gpio.
Static Private Attributes
static std::mutex gpio_lock_
The lock used to ensure that only one instance can reserve a pin or user it at a time.
static std::array< Pin, 28 > reserved_pins_ = {}
This array is used to keep track of which pins are reserved.
Detailed Description
This class is used to interface extensions with the BCM Gpio pins.
Currently this only supports the Raspberry Pi. It has not been thoroughly tested.
Todo:
Unit Tests
Bug:
If Gpio::Close() is called, instances of Gpio may have weird behavior.
Member Enumeration Documentation
PinMode
enum class giraffe::Gpio::PinMode strong
The pin modes. Uninitialized is only used internally.
Enumerator
INPUT
OUTPUT
UNINITIALIZED
Member Function Documentation
initialize()
void giraffe::Gpio::initialize () static
Static initialization of the BCM registers.
This function is called once, it maps the BCM registers to gpio_memory_map_. I decided to go with the simple approach of using /dev/gpiomem instead of the others as I currently don't need any features past basic digital IO.
Exceptions
GpioException
References gpio_lock_, GPIO_MEMORY_MAP_SIZE, and s_gpio_memory_map.
deInitialize()
void giraffe::Gpio::deInitialize () static
Static function to close the BCM registers and reset the reserved pins.
This deallocates the memory map and resets the reserved pins array.
Todo:
Set pins to their 'initial_state_' before closing.
References gpio_lock_, GPIO_MEMORY_MAP_SIZE, reserved_pins_, and s_gpio_memory_map.
isInitialized()
bool giraffe::Gpio::isInitialized () static
Check if the GPIO registers are mapped.
Returns
true - The registers are mapped.
false - The registers are not mapped.
References gpio_lock_, and verifyInitialized().
setupPin()
void giraffe::Gpio::setupPin (Pin pin)
A function to setup a pin for input or output.
Parameters
pin The pin to setup.
Exceptions
GpioException
References gpio_lock_, INPUT, isPinReserved(), giraffe::Gpio::Pin::mode, giraffe::Gpio::Pin::pin_number, readWithBarrier(), reservePin(), s_gpio_memory_map, setOwner(), UNINITIALIZED, verifyInitialized(), and writeWithBarrier().
Referenced by extension::RgbStatusLed::startup().
write()
void giraffe::Gpio::write (Pin pin, bool high)
Write a value to an output pin pin (HIGH or LOW)
The pin must be reserved and owned by the current instance before writing to it. The pin must also be set as an output pin.
Parameters
pin The pin to write to.
on The value to write to the pin, true for HIGH, false for LOW.
Exceptions
GpioException
Todo:
Verify that the pin is owned by the current instance.
Can a user change the mode of a pin after it has been reserved to write to it?
References calculateAddress(), gpio_lock_, isOwner(), giraffe::Gpio::Pin::mode, OUTPUT, giraffe::Gpio::Pin::pin_number, verifyInitialized(), and writeWithBarrier().
Referenced by extension::RgbStatusLed::loop(), and extension::RgbStatusLed::shutdown().
read()
bool giraffe::Gpio::read (Pin pin)
Read the value of an input pin.
The pin must be reserved and owned by the current instance before reading from it. The pin must also be set as an input pin.
Parameters
pin The pin to read from.
Returns
true The pin is HIGH.
false The pin is LOW.
Exceptions
GpioException
References calculateAddress(), gpio_lock_, INPUT, isOwner(), isPinReserved(), giraffe::Gpio::Pin::mode, giraffe::Gpio::Pin::pin_number, readWithBarrier(), and verifyInitialized().
releasePin()
void giraffe::Gpio::releasePin (Pin pin)
Release a pin for use by another instance.
Parameters
pin - The pin to release.
Exceptions
GpioException
References gpio_lock_, isOwner(), giraffe::Gpio::Pin::pin_number, pins_owned_, reserved_pins_, and verifyInitialized().
Referenced by extension::RgbStatusLed::shutdown().
isPinReserved()
bool giraffe::Gpio::isPinReserved (const Pin & pin) private
A function to check if a pin has been reserved.
This function is not thread safe, the caller must lock the mutex prior to calling this function.
Returns
true The pin has been initialized.
false The pin has not been initialized.
References giraffe::Gpio::Pin::pin_number, reserved_pins_, and UNINITIALIZED.
Referenced by read(), and setupPin().
reservePin()
void giraffe::Gpio::reservePin (const Pin & pin) private
A function to reserve a pin for use.
This function is not thread safe, the caller must lock the mutex. This should be called after the pin has been initialized. Parameter safety is not checked.
Parameters
pin The pin to reserve.
References giraffe::Gpio::Pin::pin_number, and reserved_pins_.
Referenced by setupPin().
isOwner()
bool giraffe::Gpio::isOwner (const Pin & pin) private
A function to check if the current instance owns a reserved pin.
This function accesses the pins_owned_ variable, which is not static.
Parameters
pin The pin to check.
Returns
true This instance owns the pin.
false This instance does not own the pin.
References giraffe::Gpio::Pin::pin_number, and pins_owned_.
Referenced by read(), releasePin(), and write().
setOwner()
void giraffe::Gpio::setOwner (const Pin & pin) private
A function to set the owner of a pin.
Accesses non-static variable pins_owned_. This should only be called if the pin is not reserved by another instance.
Parameters
pin The pin to become the owner of.
References giraffe::Gpio::Pin::pin_number, and pins_owned_.
Referenced by setupPin().
Member Data Documentation
gpio_lock_
std::mutex giraffe::Gpio::gpio_lock_ static private
The lock used to ensure that only one instance can reserve a pin or user it at a time.
This mutex is used to ensure that only one instance of Gpio can access the BCM registers at a time along with static members.
Todo:
ability to release a pin
Referenced by deInitialize(), initialize(), isInitialized(), read(), releasePin(), setupPin(), and write().
reserved_pins_
std::array< Gpio::Pin, 28 > giraffe::Gpio::reserved_pins_ = {} static private
This array is used to keep track of which pins are reserved.
Initialized in Gpio::Initialize(), all pins are initially set with mode PinMode::UNINITIALIZED and a pin number of -1.
See also
Gpio::reservePin()
Gpio::isPinReserved()
Gpio::deInitialize()
Referenced by deInitialize(), isPinReserved(), releasePin(), and reservePin().
pins_owned_
uint32_t giraffe::Gpio::pins_owned_ = 0 private
Contains the pins owned by a particular instance of Gpio.
This is a bitmask, where each bit corresponds to a pin.
See also
Gpio::setOwner()
Gpio::isOwner()
Referenced by isOwner(), releasePin(), and setOwner().