Giraffe: ax25::SimplexPhysicalLayerStateMachine Class Reference
ax25::SimplexPhysicalLayerStateMachine Class Reference
#include <simplex_physical_layer.hpp>
Public Types
enum class State {
READY = 0 , RECEIVING = 1 , TRANSMITTER_SUPPRESSION = 2 , TRANSMITTER_START = 3 ,
TRANSMITTING = 4 , DIGIPEATING = 5 , RECEIVER_START = 6
}
Public Member Functions
SimplexPhysicalLayerStateMachine (StateMachineData &data)
~SimplexPhysicalLayerStateMachine ()=default
State getCurrentState () const
void receive (Primitive primitive)
Protected Member Functions
void generateSignal (Primitive primitive)
void indicateError (StateMachineErrors error_code, bool active)
void isSignalPresent (Primitive primitive)
Protected Attributes
StateMachineData & data_
Private Member Functions
bool acquisitionOfSignal ()
void getFrameFromRadio ()
bool lossOfSignal ()
void sendFrameToRadio ()
void set_state (State state)
void state_digipeating ()
void state_ready ()
void state_receiverStart ()
void state_receiving ()
void state_transmitterStart ()
void state_transmitterSuppression ()
void state_transmitting ()
void subroutine_acquisition ()
void subroutine_startTransmitter ()
bool turnTransmitterOff ()
bool turnTransmitterOn ()
Private Attributes
State state_ = State::READY
Member Enumeration Documentation
State
enum ax25::SimplexPhysicalLayerStateMachine::State strong
Enumerator
READY
RECEIVING
TRANSMITTER_SUPPRESSION
TRANSMITTER_START
TRANSMITTING
DIGIPEATING
RECEIVER_START
Constructor & Destructor Documentation
SimplexPhysicalLayerStateMachine()
ax25::SimplexPhysicalLayerStateMachine::SimplexPhysicalLayerStateMachine (StateMachineData & data) inline
~SimplexPhysicalLayerStateMachine()
ax25::SimplexPhysicalLayerStateMachine::~SimplexPhysicalLayerStateMachine () default
Member Function Documentation
getCurrentState()
State ax25::SimplexPhysicalLayerStateMachine::getCurrentState () const inline
References state_.
receive()
void ax25::SimplexPhysicalLayerStateMachine::receive (Primitive primitive)
set_state()
void ax25::SimplexPhysicalLayerStateMachine::set_state (State state) inline private
References state_.
Referenced by state_ready().
state_ready()
void ax25::SimplexPhysicalLayerStateMachine::state_ready () private
References ax25::BaseAX25StateMachine::data_, ax25::BaseAX25StateMachine::isSignalPresent(), ax25::PH_EXPEDITED_DATA_request, ax25::PH_RELEASE_request, ax25::PH_SEIZE_request, set_state(), ax25::Timers::t102, and ax25::StateMachineData::timers.
state_receiving()
void ax25::SimplexPhysicalLayerStateMachine::state_receiving () private
state_transmitterSuppression()
void ax25::SimplexPhysicalLayerStateMachine::state_transmitterSuppression () private
state_transmitterStart()
void ax25::SimplexPhysicalLayerStateMachine::state_transmitterStart () private
state_transmitting()
void ax25::SimplexPhysicalLayerStateMachine::state_transmitting () private
state_digipeating()
void ax25::SimplexPhysicalLayerStateMachine::state_digipeating () private
state_receiverStart()
void ax25::SimplexPhysicalLayerStateMachine::state_receiverStart () private
subroutine_startTransmitter()
void ax25::SimplexPhysicalLayerStateMachine::subroutine_startTransmitter () private
subroutine_acquisition()
void ax25::SimplexPhysicalLayerStateMachine::subroutine_acquisition () private
turnTransmitterOn()
bool ax25::SimplexPhysicalLayerStateMachine::turnTransmitterOn () private
turnTransmitterOff()
bool ax25::SimplexPhysicalLayerStateMachine::turnTransmitterOff () private
sendFrameToRadio()
void ax25::SimplexPhysicalLayerStateMachine::sendFrameToRadio () private
acquisitionOfSignal()
bool ax25::SimplexPhysicalLayerStateMachine::acquisitionOfSignal () private
lossOfSignal()
bool ax25::SimplexPhysicalLayerStateMachine::lossOfSignal () private
getFrameFromRadio()
void ax25::SimplexPhysicalLayerStateMachine::getFrameFromRadio () private
generateSignal()
void ax25::BaseAX25StateMachine::generateSignal (Primitive primitive) protected inherited
Referenced by ax25::DataLinkStateMachine::state_disconnected().
isSignalPresent()
void ax25::BaseAX25StateMachine::isSignalPresent (Primitive primitive) protected inherited
Referenced by state_ready().
indicateError()
void ax25::BaseAX25StateMachine::indicateError (StateMachineErrors error_code, bool active) protected inherited
Member Data Documentation
state_
State ax25::SimplexPhysicalLayerStateMachine::state_ = State::READY private
Referenced by getCurrentState(), and set_state().
data_
StateMachineData& ax25::BaseAX25StateMachine::data_ protected inherited
Referenced by state_ready().