Giraffe: extension::Bme280 Class Reference
extension::Bme280 Class Reference
#include <bme280.hpp>
Classes
struct CompensationData
Public Member Functions
Bme280 (ExtensionResources &resources, cfg::ExtensionMetadata metadata)
DiagnosticId getFaultCode () const
Get the Fault Code when the status is ERROR.
node::Status getStatus () const
Get the Status of the extension.
bool isFaulted () const
Returns true if the extension is in a faulted state.
void loop () override
void reset ()
Only to be called when an extension is in the Error state. This joins the thread and fixes the status.
void start ()
Starts the extension.
void startup () override
void stop ()
Sends a stop signal to the extension.
Protected Member Functions
template<typename T >
void data (data::DataId identifier, T value, int precision=2)
void data (data::GpsFrame frame)
templates for Extension::data
void data (data::ImuFrame frame)
void dataWithSecondaryIdentifier (data::DataId identifier, uint32_t value, const std::string &secondary_identifier)
void debug (const std::string &message)
void error (DiagnosticId log_id, int info)
void error (DiagnosticId, const std::string &info="")
void extSleep (uint32_t milliseconds)
Sleep internally for a given number of milliseconds.
void info (std::string info)
void raiseFault (DiagnosticId ext_fault_code, std::string info="")
Used internally to raise a fault. This will stop an extension.
virtual void shutdown ()
bool stopRequested () const
Returns true if the extension has been requested to stop.
Protected Attributes
cfg::ExtensionMetadata metadata_
Private Member Functions
bool configureSensor ()
Configures the BME280. (Weather Monitoring config, Section 3.5.1)
bool handshake ()
Reads the 'ID' register on the BME280, which should return 0x60.
bool processEnvironmentalData ()
Processes the raw environmental data into known units using the compensation data.
bool readCompensationData ()
Reads and stores the compensation data from the BME280.
bool readEnvironmentalData ()
Reads the raw environmental data from the BME280.
void resetSensor ()
Send the reset command to the sensor.
void runner ()
void sleep ()
Private Attributes
CompensationData comp_data_ {}
bst::Timer compensation_timer_
A timer that is used to read the sensor's compensation data at a configured interval.
std::atomic< DiagnosticId > fault_code_ = DiagnosticId::EXT_FAULT_none
The fault code associated with the fault.
std::atomic< bool > fault_flag_ = false
This is raised with a call to raiseFault().
double humidity_ = 0.0
I2cInterface i2c_
ExtensionResources & interfaces_
double pressure_ = 0.0
uint32_t raw_humidity_ = 0
uint32_t raw_pressure_ = 0
uint32_t raw_temperature_ = 0
bst::Timer read_timer_
A timer used with loop() to verify that the sensor is functioning.
std::thread runner_thread_ = std::thread()
std::atomic< node::Status > status_ = node::Status::STOPPED
std::atomic< bool > stop_flag_ = true
double temperature_ = 0.0
Class Documentation
extension::Bme280::CompensationData
struct extension::Bme280::CompensationData
Class Members
uint16_t dig_T1
int16_t dig_T2
int16_t dig_T3
uint16_t dig_P1
int16_t dig_P2
int16_t dig_P3
int16_t dig_P4
int16_t dig_P5
int16_t dig_P6
int16_t dig_P7
int16_t dig_P8
int16_t dig_P9
uint8_t dig_H1
int16_t dig_H2
uint8_t dig_H3
int16_t dig_H4
int16_t dig_H5
int8_t dig_H6
Constructor & Destructor Documentation
Bme280()
extension::Bme280::Bme280 (ExtensionResources & resources, cfg::ExtensionMetadata metadata)
Member Function Documentation
startup()
void extension::Bme280::startup () override virtual
Reimplemented from extension::Extension.
References extension::CONFIGURE, configureSensor(), I2cInterface::connect(), extension::DONE, extension::Extension::extSleep(), extension::HANDSHAKE, handshake(), i2c_, extension::I2C_CONNECT, extension::Extension::raiseFault(), extension::READ_COMPENSATION_DATA, readCompensationData(), extension::Extension::stopRequested(), and I2cInterface::SUCCESS.
loop()
void extension::Bme280::loop () override virtual
Reimplemented from extension::Extension.
References compensation_timer_, extension::Extension::data(), extension::Extension::error(), humidity_, pressure_, processEnvironmentalData(), extension::Extension::raiseFault(), read_timer_, readCompensationData(), readEnvironmentalData(), and temperature_.
handshake()
bool extension::Bme280::handshake () private
Reads the 'ID' register on the BME280, which should return 0x60.
Returns
true - handshake successful
false - handshake failed
References i2c_, I2cInterface::readByteFromReg(), and I2cInterface::SUCCESS.
Referenced by startup().
configureSensor()
bool extension::Bme280::configureSensor () private
Configures the BME280. (Weather Monitoring config, Section 3.5.1)
Sensor Mode: Normal Oversampling: 1x on all IIR Filter: Off Standby Time: 125ms
Returns
true - configuration successful
false - configuration failed
References i2c_, I2cInterface::SUCCESS, and I2cInterface::writeByteToReg().
Referenced by startup().
readCompensationData()
bool extension::Bme280::readCompensationData () private
Reads and stores the compensation data from the BME280.
Returns
true - compensation data read successfully
false - failed to read compensation data
References comp_data_, extension::Bme280::CompensationData::dig_H1, extension::Bme280::CompensationData::dig_H2, extension::Bme280::CompensationData::dig_H3, extension::Bme280::CompensationData::dig_H4, extension::Bme280::CompensationData::dig_H5, extension::Bme280::CompensationData::dig_P1, extension::Bme280::CompensationData::dig_P2, extension::Bme280::CompensationData::dig_P3, extension::Bme280::CompensationData::dig_P4, extension::Bme280::CompensationData::dig_P5, extension::Bme280::CompensationData::dig_P6, extension::Bme280::CompensationData::dig_P7, extension::Bme280::CompensationData::dig_P8, extension::Bme280::CompensationData::dig_P9, extension::Bme280::CompensationData::dig_T1, extension::Bme280::CompensationData::dig_T2, extension::Bme280::CompensationData::dig_T3, i2c_, I2cInterface::readChunkFromReg(), and I2cInterface::SUCCESS.
Referenced by loop(), and startup().
readEnvironmentalData()
bool extension::Bme280::readEnvironmentalData () private
Reads the raw environmental data from the BME280.
The raw data (pressure, temperature, humidity) is stored in the follow registers:
Pressure: 0xF7, 0xF8, 0xF9 Temperature: 0xFA, 0xFB, 0xFC Humidity: 0xFD, 0xFE
You'll notice that all of these registers are sequential. This means that all of the data can be read in a single I2C transaction. (As recommended in section 4 of the datasheet)
Pressure: 0xF7 data[0] 7:0 MSB - 8 bits 0xF8 data[1] 7:0 LSB - 8 bits 0xF9 data[2] 7:4 XLSB - 4 bits [19:12] [11:4] [3:0]
Temperature: 0xFA data[3] 7:0 MSB - 8 bits 0xFB data[4] 7:0 LSB - 8 bits 0xFC data[5] 7:4 XLSB - 4 bits [19:12] [11:4] [3:0]
Humidity: 0xFD data[6] 7:0 MSB - 8 bits 0xFE data[7] 7:0 LSB - 8 bits [15:8] [7:0]
Returns
true - environmental data read successfully
false - failed to read environmental data
References extension::Extension::data(), i2c_, raw_humidity_, raw_pressure_, raw_temperature_, I2cInterface::readChunkFromReg(), and I2cInterface::SUCCESS.
Referenced by loop().
processEnvironmentalData()
bool extension::Bme280::processEnvironmentalData () private
Processes the raw environmental data into known units using the compensation data.
This is directly copied from the BME280 datasheet, but with different variable names.
References comp_data_, extension::Bme280::CompensationData::dig_H1, extension::Bme280::CompensationData::dig_H2, extension::Bme280::CompensationData::dig_H3, extension::Bme280::CompensationData::dig_H4, extension::Bme280::CompensationData::dig_H5, extension::Bme280::CompensationData::dig_H6, extension::Bme280::CompensationData::dig_P1, extension::Bme280::CompensationData::dig_P2, extension::Bme280::CompensationData::dig_P3, extension::Bme280::CompensationData::dig_P4, extension::Bme280::CompensationData::dig_P5, extension::Bme280::CompensationData::dig_P6, extension::Bme280::CompensationData::dig_P7, extension::Bme280::CompensationData::dig_P8, extension::Bme280::CompensationData::dig_P9, extension::Bme280::CompensationData::dig_T1, extension::Bme280::CompensationData::dig_T2, extension::Bme280::CompensationData::dig_T3, extension::Extension::error(), humidity_, pressure_, raw_humidity_, raw_pressure_, raw_temperature_, and temperature_.
Referenced by loop().
resetSensor()
void extension::Bme280::resetSensor () private
Send the reset command to the sensor.
References i2c_, and I2cInterface::writeByteToReg().
start()
void extension::Extension::start () inherited
Starts the extension.
References extension::Extension::error(), extension::Extension::fault_code_, extension::Extension::fault_flag_, node::K_ACTIVE_STATUSES, extension::Extension::runner(), extension::Extension::runner_thread_, extension::Extension::status_, and extension::Extension::stop_flag_.
Referenced by ExtensionTestFramework::runExtensionFor().
stop()
void extension::Extension::stop () inherited
Sends a stop signal to the extension.
The timeout for stopping an extension.
The interval of how often to check if the extension has stopped.
References extension::Extension::error(), node::K_INACTIVE_STATUSES, extension::Extension::runner_thread_, extension::Extension::status_, and extension::Extension::stop_flag_.
Referenced by extension::Extension::~Extension(), extension::Extension::reset(), and ExtensionTestFramework::runExtensionFor().
reset()
void extension::Extension::reset () inherited
Only to be called when an extension is in the Error state. This joins the thread and fixes the status.
References extension::Extension::status_, extension::Extension::stop(), and node::STOPPED.
getStatus()
node::Status extension::Extension::getStatus () const inline inherited
Get the Status of the extension.
Returns
node::Status The status of the extension.
References extension::Extension::status_.
getFaultCode()
DiagnosticId extension::Extension::getFaultCode () const inline inherited
Get the Fault Code when the status is ERROR.
Returns
DiagnosticId The fault code.
References extension::Extension::fault_code_.
isFaulted()
bool extension::Extension::isFaulted () const inline inherited
Returns true if the extension is in a faulted state.
Returns
true if the extension is in a faulted state, false otherwise.
References extension::Extension::fault_flag_.
Referenced by extension::AdcExtensionBase::startup(), and extension::ImuExtensionBase::startup().
shutdown()
virtual void extension::Extension::shutdown () inline protected virtual inherited
Reimplemented in extension::SamM8q, extension::RgbStatusLed, extension::PiCamera, extension::ImuExtensionBase, and extension::AdcExtensionBase.
Referenced by extension::Extension::runner().
data() [1/3]
template<typename T > void extension::Extension::data (data::DataId identifier, T value, int precision = 2) protected inherited
References data::Stream< T >::addPacket(), data::Streams::data, data::DataPacket::identifier, extension::Extension::interfaces_, kExtensionId, extension::Extension::metadata_, cfg::ExtensionMetadata::name, data::BaseStreamPacket::secondary_identifier, data::BaseStreamPacket::source, extension::ExtensionResources::streams, util::to_string(), and data::DataPacket::value.
Referenced by loop(), extension::Ds18b20::loop(), extension::ImuExtensionBase::loop(), extension::PiCamera::loop(), extension::SimTemperatureSensor::loop(), extension::SimPressureSensor::loop(), extension::SimHumiditySensor::loop(), extension::SimGpsSensor::loop(), extension::SimImuSensor::loop(), extension::SimCamera::loop(), readEnvironmentalData(), and extension::SamM8q::stateRead().
data() [2/3]
void extension::Extension::data (data::GpsFrame frame) protected inherited
templates for Extension::data
 */
template void Extension::data<int>(data::DataId, int, int);
template void Extension::data<float>(data::DataId, float, int);
template void Extension::data<double>(data::DataId, double, int);
template void Extension::data<uint32_t>(data::DataId, uint32_t, int);
template void Extension::data<std::string>(data::DataId, std::string, int);
/**
 *
References data::GpsFrameStream::addFrame(), node::EXTENSION, data::Streams::gps, extension::Extension::interfaces_, extension::Extension::metadata_, cfg::ExtensionMetadata::name, and extension::ExtensionResources::streams.
data() [3/3]
void extension::Extension::data (data::ImuFrame frame) protected inherited
References data::ImuFrameStream::addFrame(), node::EXTENSION, data::Streams::imu, extension::Extension::interfaces_, extension::Extension::metadata_, cfg::ExtensionMetadata::name, and extension::ExtensionResources::streams.
dataWithSecondaryIdentifier()
void extension::Extension::dataWithSecondaryIdentifier (data::DataId identifier, uint32_t value, const std::string & secondary_identifier) protected inherited
References data::Stream< T >::addPacket(), data::Streams::data, node::EXTENSION, data::DataPacket::identifier, extension::Extension::interfaces_, extension::Extension::metadata_, cfg::ExtensionMetadata::name, data::DataPacket::NUMERIC, data::DataPacket::numeric_value, data::BaseStreamPacket::secondary_identifier, data::BaseStreamPacket::source, extension::ExtensionResources::streams, and data::DataPacket::type.
Referenced by extension::AdcExtensionBase::reportAdcData().
error() [1/2]
void extension::Extension::error (DiagnosticId log_id, const std::string & info = "") protected inherited
References data::Stream< T >::addPacket(), data::LogPacket::ERROR, data::LogPacket::id, data::LogPacket::info, extension::Extension::interfaces_, kExtensionId, data::LogPacket::level, data::Streams::log, extension::Extension::metadata_, cfg::ExtensionMetadata::name, data::BaseStreamPacket::secondary_identifier, data::BaseStreamPacket::source, and extension::ExtensionResources::streams.
Referenced by extension::ImuExtensionBase::ImuExtensionBase(), extension::PiCamera::PiCamera(), extension::Mcp3021::adcStartup(), loop(), extension::Ds18b20::loop(), extension::PiCamera::loop(), processEnvironmentalData(), extension::Extension::raiseFault(), extension::Extension::start(), extension::SamM8q::stateConfigure(), extension::SamM8q::stateRead(), and extension::Extension::stop().
error() [2/2]
void extension::Extension::error (DiagnosticId log_id, int info) protected inherited
References data::Stream< T >::addPacket(), data::LogPacket::ERROR, data::LogPacket::id, extension::Extension::info(), data::LogPacket::info, extension::Extension::interfaces_, kExtensionId, data::LogPacket::level, data::Streams::log, extension::Extension::metadata_, cfg::ExtensionMetadata::name, data::BaseStreamPacket::secondary_identifier, data::BaseStreamPacket::source, extension::ExtensionResources::streams, and util::to_string().
info()
void extension::Extension::info (std::string info) protected inherited
References data::Stream< T >::addPacket(), data::LogPacket::id, data::LogPacket::INFO, data::LogPacket::info, extension::Extension::interfaces_, kExtensionId, data::LogPacket::level, data::Streams::log, extension::Extension::metadata_, cfg::ExtensionMetadata::name, data::BaseStreamPacket::secondary_identifier, data::BaseStreamPacket::source, and extension::ExtensionResources::streams.
Referenced by extension::Extension::debug(), and extension::Extension::error().
debug()
void extension::Extension::debug (const std::string & message) protected inherited
References data::Stream< T >::addPacket(), data::LogPacket::DEBUG, data::LogPacket::id, extension::Extension::info(), data::LogPacket::info, extension::Extension::interfaces_, kExtensionId, data::LogPacket::level, data::Streams::log, extension::Extension::metadata_, cfg::ExtensionMetadata::name, data::BaseStreamPacket::secondary_identifier, data::BaseStreamPacket::source, and extension::ExtensionResources::streams.
Referenced by extension::RgbStatusLed::RgbStatusLed(), extension::Mcp3021::adcStartup(), extension::Ds18b20::init(), extension::Ds18b20::loop(), extension::PiCamera::loop(), extension::Mcp3021::readAdc(), extension::Ds18b20::startup(), extension::SamM8q::startup(), extension::SamM8q::stateConfigure(), extension::SamM8q::stateRead(), extension::SamM8q::stateReset(), and extension::SamM8q::transitionState().
stopRequested()
bool extension::Extension::stopRequested () const protected inherited
Returns true if the extension has been requested to stop.
This should be used in the loop() function for extensions that take a long time to complete a single loop iteration. This is helpful for to stop extensions quickly upon request. Fast extensions do not need to use this.
Returns
true - The extension has been requested to stop.
false - The extension has not been requested to stop.
References extension::Extension::stop_flag_.
Referenced by extension::Extension::sleep(), startup(), extension::Ds18b20::startup(), and extension::SamM8q::startup().
raiseFault()
void extension::Extension::raiseFault (DiagnosticId ext_fault_code, std::string info = "") protected inherited
Used internally to raise a fault. This will stop an extension.
References extension::Extension::error(), extension::Extension::fault_code_, extension::Extension::fault_flag_, and extension::Extension::stop_flag_.
Referenced by extension::Bmi088::Bmi088(), extension::RgbStatusLed::RgbStatusLed(), extension::Mcp3021::adcStartup(), extension::Bmi088::imuStartup(), extension::AdcExtensionBase::loop(), loop(), extension::Ds18b20::loop(), extension::ImuExtensionBase::loop(), extension::PiCamera::loop(), extension::RgbStatusLed::shutdown(), startup(), extension::Ds18b20::startup(), extension::PiCamera::startup(), extension::RgbStatusLed::startup(), extension::SamM8q::startup(), and extension::SamM8q::stateReset().
extSleep()
void extension::Extension::extSleep (uint32_t milliseconds) protected inherited
Sleep internally for a given number of milliseconds.
This has a limit of 1 second.
Parameters
milliseconds - The number of milliseconds to sleep.
Referenced by extension::Bmi088::accHandshake(), extension::Bmi088::configureAccelerometer(), extension::Bmi088::gyroHandshake(), startup(), extension::Ds18b20::startup(), extension::SamM8q::startup(), and extension::SamM8q::stateRead().
sleep()
void extension::Extension::sleep () private inherited
References extension::Extension::metadata_, extension::Extension::stopRequested(), and cfg::ExtensionMetadata::update_interval.
Referenced by extension::Extension::runner().
runner()
void extension::Extension::runner () private inherited
References node::ERROR, extension::Extension::fault_flag_, extension::Extension::loop(), node::RUNNING, extension::Extension::shutdown(), extension::Extension::sleep(), node::STARTING, extension::Extension::startup(), extension::Extension::status_, extension::Extension::stop_flag_, node::STOPPED, and node::STOPPING.
Referenced by extension::Extension::start().
Member Data Documentation
i2c_
I2cInterface extension::Bme280::i2c_ private
Referenced by configureSensor(), handshake(), readCompensationData(), readEnvironmentalData(), resetSensor(), and startup().
compensation_timer_
bst::Timer extension::Bme280::compensation_timer_ private
A timer that is used to read the sensor's compensation data at a configured interval.
Referenced by loop().
read_timer_
bst::Timer extension::Bme280::read_timer_ private
A timer used with loop() to verify that the sensor is functioning.
Referenced by loop().
raw_temperature_
uint32_t extension::Bme280::raw_temperature_ = 0 private
Referenced by processEnvironmentalData(), and readEnvironmentalData().
raw_pressure_
uint32_t extension::Bme280::raw_pressure_ = 0 private
Referenced by processEnvironmentalData(), and readEnvironmentalData().
raw_humidity_
uint32_t extension::Bme280::raw_humidity_ = 0 private
Referenced by processEnvironmentalData(), and readEnvironmentalData().
temperature_
double extension::Bme280::temperature_ = 0.0 private
Referenced by loop(), and processEnvironmentalData().
pressure_
double extension::Bme280::pressure_ = 0.0 private
Referenced by loop(), and processEnvironmentalData().
humidity_
double extension::Bme280::humidity_ = 0.0 private
Referenced by loop(), and processEnvironmentalData().
comp_data_
CompensationData extension::Bme280::comp_data_ {} private
Referenced by processEnvironmentalData(), and readCompensationData().
metadata_
cfg::ExtensionMetadata extension::Extension::metadata_ protected inherited
Referenced by extension::Bmi088::Bmi088(), extension::Extension::data(), extension::Extension::dataWithSecondaryIdentifier(), extension::Extension::debug(), extension::Extension::error(), extension::Extension::info(), extension::Ds18b20::init(), and extension::Extension::sleep().
fault_flag_
std::atomic<bool> extension::Extension::fault_flag_ = false private inherited
This is raised with a call to raiseFault().
This is used to stop the extension. Cleared on a call to start().
Referenced by extension::Extension::isFaulted(), extension::Extension::raiseFault(), extension::Extension::runner(), and extension::Extension::start().
fault_code_
std::atomic<DiagnosticId> extension::Extension::fault_code_ = DiagnosticId::EXT_FAULT_none private inherited
The fault code associated with the fault.
This is set when raiseFault() is called. Cleared on a call to start().
Referenced by extension::Extension::getFaultCode(), extension::Extension::raiseFault(), and extension::Extension::start().
status_
std::atomic<node::Status> extension::Extension::status_ = node::Status::STOPPED private inherited
Referenced by extension::Extension::getStatus(), extension::Extension::reset(), extension::Extension::runner(), extension::Extension::start(), and extension::Extension::stop().
stop_flag_
std::atomic<bool> extension::Extension::stop_flag_ = true private inherited
Referenced by extension::Extension::raiseFault(), extension::Extension::runner(), extension::Extension::start(), extension::Extension::stop(), and extension::Extension::stopRequested().
runner_thread_
std::thread extension::Extension::runner_thread_ = std::thread() private inherited
Referenced by extension::Extension::start(), and extension::Extension::stop().
interfaces_
ExtensionResources& extension::Extension::interfaces_ private inherited
Referenced by extension::Extension::data(), extension::Extension::dataWithSecondaryIdentifier(), extension::Extension::debug(), extension::Extension::error(), and extension::Extension::info().