Giraffe: bit::TestCase Class Reference
bit::TestCase Class Reference
#include <built_in_test.hpp>
Public Member Functions
TestCase (TestGroupId group_id, TestId test_id, data::SharedData &shared_data)
~TestCase ()=default
TestStatus getStatus () const
TestId getTestID () const
std::string getTestIdString () const
void reset ()
void startTest ()
void stopTest ()
void update ()
Private Attributes
TestGroupId group_id_
data::SharedData & shared_data_
TestStatus status_ = TestStatus::NOTRUN
TestId test_id_
Constructor & Destructor Documentation
TestCase()
bit::TestCase::TestCase (TestGroupId group_id, TestId test_id, data::SharedData & shared_data) inline
~TestCase()
bit::TestCase::~TestCase () default
Member Function Documentation
getStatus()
TestStatus bit::TestCase::getStatus () const inline
References status_.
getTestID()
TestId bit::TestCase::getTestID () const inline
References test_id_.
getTestIdString()
std::string bit::TestCase::getTestIdString () const inline
References test_id_.
Referenced by update().
startTest()
void bit::TestCase::startTest () inline
References status_.
stopTest()
void bit::TestCase::stopTest () inline
References status_.
update()
void bit::TestCase::update () inline
References data::LogStream::error(), node::FLIGHT_RUNNER, getTestIdString(), group_id_, data::Streams::log, bit::test_case::runTestFCS_0001(), bit::test_case::runTestGPS_0400(), shared_data_, bit::TestResult::status, status_, data::SharedData::streams, bit::TestResult::test_id, and test_id_.
reset()
void bit::TestCase::reset () inline
References status_.
Member Data Documentation
group_id_
TestGroupId bit::TestCase::group_id_ private
Referenced by update().
test_id_
TestId bit::TestCase::test_id_ private
Referenced by getTestID(), getTestIdString(), and update().
status_
TestStatus bit::TestCase::status_ = TestStatus::NOTRUN private
Referenced by getStatus(), reset(), startTest(), stopTest(), and update().
shared_data_
data::SharedData& bit::TestCase::shared_data_ private
Referenced by update().