Giraffe: RequestRouter Class Reference
RequestRouter Class Reference
#include <request_handler.hpp>
Public Member Functions
RequestRouter (data::SharedData &shared_data, cfg::Configuration &config, data::blocks::ServerModuleStats &server_stats)
Construct a RequestRouter object.
~RequestRouter ()=default
double getBytesPerSecondDown () const
double getBytesPerSecondUp () const
void handleMessage (sock::TcpSocketServer &client, std::string &request)
This function is responsible for parsing a request and routing it to the right place.
void oneSecondTick ()
Private Member Functions
void handleDataRequest (sock::TcpSocketServer &client, protocol::Message &msg)
This function responds to data requests.
void handlePingRequest (sock::TcpSocketServer &client, protocol::Message &msg)
This function responds to a ping request.
void handleSettingRequest (sock::TcpSocketServer &client, protocol::Message &msg)
This function responds to a setting request.
void sendErrorPacket (sock::TcpSocketServer &client, const std::string &error="")
This function is the generic error response function.
void sendMessage (protocol::Message &response, sock::TcpSocketServer &client)
Private Attributes
BoosterSeat::RollingAverage bytes_per_second_down_ = {60}
BoosterSeat::RollingAverage bytes_per_second_up_ = {60}
cfg::Configuration & config_
data::SharedData & shared_data_
data::blocks::ServerModuleStats & stats_
Constructor & Destructor Documentation
RequestRouter()
RequestRouter::RequestRouter (data::SharedData & shared_data, cfg::Configuration & config, data::blocks::ServerModuleStats & server_stats)
Construct a RequestRouter object.
Parameters
shared_data - The shared data object.
config - The global configuration.
server_stats - The server stats data block.
~RequestRouter()
RequestRouter::~RequestRouter () default
Member Function Documentation
handleMessage()
void RequestRouter::handleMessage (sock::TcpSocketServer & client, std::string & request)
This function is responsible for parsing a request and routing it to the right place.
The function handles incoming requests from a TCP socket server by parsing them as JSON strings and checking their type and category before sending the appropriate response or an error packet if they are not implemented or malformed.
Parameters
client The client parameter is a reference to a sock::TcpSocketServer object, which represents the client that sent the request to the server.
request The request parameter is a reference to a std::string object that contains the json message received from the client.
References bytes_per_second_down_, protocol::Message::dst, protocol::GFS, handleDataRequest(), handlePingRequest(), handleSettingRequest(), data::blocks::ServerModuleStats::num_messages_received, protocol::parseMessage(), protocol::REQ, protocol::Message::rsc, sendErrorPacket(), stats_, and protocol::Message::typ.
oneSecondTick()
void RequestRouter::oneSecondTick () inline
References bytes_per_second_down_, and bytes_per_second_up_.
getBytesPerSecondDown()
double RequestRouter::getBytesPerSecondDown () const inline
References bytes_per_second_down_.
getBytesPerSecondUp()
double RequestRouter::getBytesPerSecondUp () const inline
References bytes_per_second_up_.
sendErrorPacket()
void RequestRouter::sendErrorPacket (sock::TcpSocketServer & client, const std::string & error = "") private
This function is the generic error response function.
Parameters
client The client is the client socket.
error A string containing the error message.
References protocol::createResponseMessage(), protocol::ERROR, protocol::GFS, data::blocks::ServerModuleStats::num_invalid_received, sendMessage(), stats_, and protocol::UNKNOWN.
Referenced by handleMessage().
handlePingRequest()
void RequestRouter::handlePingRequest (sock::TcpSocketServer & client, protocol::Message & msg) private
This function responds to a ping request.
Parameters
client
msg
References protocol::createResponseMessage(), protocol::GFS, protocol::GOOD, protocol::Message::id, sendMessage(), and protocol::Message::src.
Referenced by handleMessage().
handleSettingRequest()
auto RequestRouter::handleSettingRequest (sock::TcpSocketServer & client, protocol::Message & msg) private
This function responds to a setting request.
It will respond with the configuration portion requested if it exists. Otherwise it will respond with an error.
Parameters
client
msg
References protocol::createResponseMessage(), protocol::GFS, and protocol::GOOD.
Referenced by handleMessage().
handleDataRequest()
auto RequestRouter::handleDataRequest (sock::TcpSocketServer & client, protocol::Message & msg) private
This function responds to data requests.
Parameters
client
msg
References protocol::createResponseMessage(), protocol::GFS, protocol::GOOD, and data::toJson().
Referenced by handleMessage().
sendMessage()
void RequestRouter::sendMessage (protocol::Message & response, sock::TcpSocketServer & client) private
References bytes_per_second_up_, protocol::Message::getJsonString(), and sock::TcpSocketServer::send().
Referenced by handlePingRequest(), and sendErrorPacket().
Member Data Documentation
shared_data_
data::SharedData& RequestRouter::shared_data_ private
config_
cfg::Configuration& RequestRouter::config_ private
stats_
data::blocks::ServerModuleStats& RequestRouter::stats_ private
Referenced by handleMessage(), and sendErrorPacket().
bytes_per_second_down_
BoosterSeat::RollingAverage RequestRouter::bytes_per_second_down_ = {60} private
Referenced by getBytesPerSecondDown(), handleMessage(), and oneSecondTick().
bytes_per_second_up_
BoosterSeat::RollingAverage RequestRouter::bytes_per_second_up_ = {60} private
Referenced by getBytesPerSecondUp(), oneSecondTick(), and sendMessage().