Giraffe: giraffe::gdl::IDataLink Class Reference
giraffe::gdl::IDataLink Class Reference abstract
Interface for the Giraffe Data Link.
#include <i_giraffe_data_link.hpp>
Public Types
using TelemetryData = signal_easel::aprs::telemetry::TelemetryData
Public Member Functions
virtual ~IDataLink ()=default
virtual Config & getConfig ()=0
virtual Statistics getStatistics ()=0
virtual bool sendTelemetryBitSense (TelemetryData &telemetry_data)=0
virtual bool sendTelemetryCoefficients (TelemetryData &telemetry_data)=0
virtual bool sendTelemetryData (TelemetryData &telemetry_data, uint32_t message_id)=0
virtual bool sendTelemetryParameterNames (TelemetryData &telemetry_data)=0
virtual bool sendTelemetryUnitsAndLabels (TelemetryData &telemetry_data)=0
virtual void updateTelemetryData (const TelemetryData &telemetry_data)=0
Detailed Description
Interface for the Giraffe Data Link.
Member Typedef Documentation
TelemetryData
using giraffe::gdl::IDataLink::TelemetryData = signal_easel::aprs::telemetry::TelemetryData
Constructor & Destructor Documentation
~IDataLink()
virtual giraffe::gdl::IDataLink::~IDataLink () virtual default
Member Function Documentation
getStatistics()
virtual Statistics giraffe::gdl::IDataLink::getStatistics () pure virtual
Implemented in giraffe::gdl::DataLink, and MockIDataLink.
getConfig()
virtual Config & giraffe::gdl::IDataLink::getConfig () pure virtual
Implemented in giraffe::gdl::DataLink, and MockIDataLink.
Referenced by giraffe::AprsManager::initializeTelemetryData().
updateTelemetryData()
virtual void giraffe::gdl::IDataLink::updateTelemetryData (const TelemetryData & telemetry_data) pure virtual
Implemented in MockIDataLink, and giraffe::gdl::DataLink.
Referenced by giraffe::AprsManager::updateTelemetryData().
sendTelemetryData()
virtual bool giraffe::gdl::IDataLink::sendTelemetryData (TelemetryData & telemetry_data, uint32_t message_id) pure virtual
Implemented in giraffe::gdl::DataLink.
Referenced by giraffe::gdl::AprsTelemetrySender::update().
sendTelemetryCoefficients()
virtual bool giraffe::gdl::IDataLink::sendTelemetryCoefficients (TelemetryData & telemetry_data) pure virtual
Implemented in giraffe::gdl::DataLink.
Referenced by giraffe::gdl::AprsTelemetrySender::sendMetadataStateMachine(), and giraffe::AprsManager::sendOnAirDefinitionPackets().
sendTelemetryParameterNames()
virtual bool giraffe::gdl::IDataLink::sendTelemetryParameterNames (TelemetryData & telemetry_data) pure virtual
Implemented in giraffe::gdl::DataLink.
Referenced by giraffe::gdl::AprsTelemetrySender::sendMetadataStateMachine(), and giraffe::AprsManager::sendOnAirDefinitionPackets().
sendTelemetryUnitsAndLabels()
virtual bool giraffe::gdl::IDataLink::sendTelemetryUnitsAndLabels (TelemetryData & telemetry_data) pure virtual
Implemented in giraffe::gdl::DataLink.
Referenced by giraffe::gdl::AprsTelemetrySender::sendMetadataStateMachine(), and giraffe::AprsManager::sendOnAirDefinitionPackets().
sendTelemetryBitSense()
virtual bool giraffe::gdl::IDataLink::sendTelemetryBitSense (TelemetryData & telemetry_data) pure virtual
Implemented in giraffe::gdl::DataLink.
Referenced by giraffe::gdl::AprsTelemetrySender::sendMetadataStateMachine(), and giraffe::AprsManager::sendOnAirDefinitionPackets().