Giraffe: OneWireInterface Class Reference
OneWireInterface Class Reference
#include <one_wire_interface.hpp>
Public Member Functions
OneWireInterface ()=default
~OneWireInterface ()=default
bool deviceExists ()
bool readTemperatureFile (std::string &data)
bool readW1SlaveFile (std::string &data)
void setDeviceId (std::string device_id)
Private Attributes
std::string path_ {}
Constructor & Destructor Documentation
OneWireInterface()
OneWireInterface::OneWireInterface () default
~OneWireInterface()
OneWireInterface::~OneWireInterface () default
Member Function Documentation
setDeviceId()
void OneWireInterface::setDeviceId (std::string device_id)
References kOneWireLocation, and path_.
Referenced by extension::Ds18b20::init().
readW1SlaveFile()
bool OneWireInterface::readW1SlaveFile (std::string & data)
References path_.
readTemperatureFile()
bool OneWireInterface::readTemperatureFile (std::string & data)
References path_.
Referenced by extension::Ds18b20::readData().
deviceExists()
bool OneWireInterface::deviceExists ()
References path_.
Referenced by extension::Ds18b20::init().
Member Data Documentation
path_
std::string OneWireInterface::path_ {} private
Referenced by deviceExists(), readTemperatureFile(), readW1SlaveFile(), and setDeviceId().