Giraffe: data::FlightData Class Reference
data::FlightData Class Reference
#include <flight_data.hpp>
Public Member Functions
Json getBitTestData ()
FlightPhase getFlightPhase () const
Get the current flight phase.
bool getLaunchPosition (double &latitude, double &longitude, double &altitude)
bool getMissionClockSeconds (int32_t &seconds)
Get the mission clock time in seconds. May be negative or positive. A negative value is in the future.
FlightPhase getPredictedPhase () const
Get the predicted flight phase.
std::string getSystemTimeUtc () const
Get the system time in UTC.
int getUptimeSeconds () const
The number of seconds since the flight runner was started.
std::string getUptimeString () const
Get the uptime represented as a string in the format "HH:MM:SS".
void setBitTestData (Json &data)
void setLaunchPosition (double latitude, double longitude, double altitude)
Json toJson ()
Public Attributes
friend FlightPhaseManager
This is here so that the flight phase manager can set the flight phase.
Static Public Attributes
static constexpr bool K_IN_SIMULATOR = false
Private Member Functions
void setFlightPhase (FlightPhase new_phase)
void setPhasePrediction (FlightPhase predicted_phase, double launch, double ascent, double descent, double recovery, double data_quality)
Private Attributes
std::atomic< double > ascent_prediction_ = 0.0
Json bit_test_buffer_ {}
std::mutex bit_test_buffer_mutex_ {}
std::atomic< double > descent_prediction_ = 0.0
std::atomic< FlightPhase > flight_phase_ = FlightPhase::UNKNOWN
The current flight phase.
std::atomic< bool > have_launch_position_ = false
True if the launch position has been set.
std::atomic< double > launch_altitude_ = 0.0
The launch position.
std::atomic< double > launch_position_latitude_ = 0.0
std::atomic< double > launch_position_longitude_ = 0.0
std::atomic< double > launch_prediction_ = 0.0
std::atomic< FlightPhase > predicted_phase_ = FlightPhase::UNKNOWN
The predicted flight phase. Used by the flight phase manager to determine the current phase.
std::atomic< double > prediction_quality_ = 0.0
std::atomic< double > recovery_prediction_ = 0.0
const bst::clck::TimePoint start_time_ = bst::clck::now()
A time point representing the start time of the flight runner.
Member Function Documentation
getUptimeSeconds()
int data::FlightData::getUptimeSeconds () const inline
The number of seconds since the flight runner was started.
Returns
int The number of seconds. This value should always be positive.
References start_time_.
Referenced by PredictionParameters::updateParameters().
getUptimeString()
std::string data::FlightData::getUptimeString () const inline
Get the uptime represented as a string in the format "HH:MM:SS".
Returns
std::string The uptime string.
References start_time_.
Referenced by data_middleware::DataFormatter::fullErrorFrame(), data_middleware::DataFormatter::setupFrameStructure(), and toJson().
getSystemTimeUtc()
std::string data::FlightData::getSystemTimeUtc () const inline
Get the system time in UTC.
Returns
std::string hh:mm:ss
Referenced by toJson().
getFlightPhase()
FlightPhase data::FlightData::getFlightPhase () const inline
Get the current flight phase.
Returns
FlightPhase The current flight phase.
References flight_phase_.
Referenced by FlightPhaseManagerTest::bringToAscent(), FlightPhaseManagerTest::bringToDescent(), FlightPhaseManagerTest::bringToLaunch(), FlightRunner::fl_phaseChanged(), bit::BuiltInTest::updateBitTestData(), and giraffe::AprsManager::updateTelemetryData().
getPredictedPhase()
FlightPhase data::FlightData::getPredictedPhase () const inline
Get the predicted flight phase.
Returns
FlightPhase The predicted flight phase.
References predicted_phase_.
setLaunchPosition()
void data::FlightData::setLaunchPosition (double latitude, double longitude, double altitude) inline
References have_launch_position_, launch_altitude_, launch_position_latitude_, and launch_position_longitude_.
Referenced by FlightRunner::setLaunchPosition().
getLaunchPosition()
bool data::FlightData::getLaunchPosition (double & latitude, double & longitude, double & altitude) inline
References have_launch_position_, launch_altitude_, launch_position_latitude_, and launch_position_longitude_.
Referenced by data_middleware::CalculatedData::calculateDistanceData().
getMissionClockSeconds()
bool data::FlightData::getMissionClockSeconds (int32_t & seconds) inline
Get the mission clock time in seconds. May be negative or positive. A negative value is in the future.
Parameters
[out] seconds - The mission clock time in seconds.
Returns
bool - True if the mission clock is running, false when it's paused.
Todo:
Implement the mission clock from the JS side into the flight runner.
Referenced by PredictionParameters::updateParameters().
toJson()
Json data::FlightData::toJson () inline
References ascent_prediction_, descent_prediction_, flight_phase_, getSystemTimeUtc(), getUptimeString(), have_launch_position_, K_IN_SIMULATOR, launch_altitude_, launch_position_latitude_, launch_position_longitude_, launch_prediction_, recovery_prediction_, and util::to_string().
Referenced by RequestRouter::handleDataRequest().
getBitTestData()
Json data::FlightData::getBitTestData () inline
References bit_test_buffer_, and bit_test_buffer_mutex_.
Referenced by RequestRouter::handleDataRequest().
setBitTestData()
void data::FlightData::setBitTestData (Json & data) inline
References bit_test_buffer_, and bit_test_buffer_mutex_.
Referenced by bit::BuiltInTest::updateBitTestData().
setFlightPhase()
void data::FlightData::setFlightPhase (FlightPhase new_phase) inline private
References flight_phase_.
Referenced by FlightPhaseManager::setFlightPhase().
setPhasePrediction()
void data::FlightData::setPhasePrediction (FlightPhase predicted_phase, double launch, double ascent, double descent, double recovery, double data_quality) inline private
References ascent_prediction_, descent_prediction_, launch_prediction_, predicted_phase_, prediction_quality_, and recovery_prediction_.
Referenced by FlightPhaseManager::update().
Member Data Documentation
K_IN_SIMULATOR
constexpr bool data::FlightData::K_IN_SIMULATOR = false static constexpr
Referenced by toJson().
FlightPhaseManager
friend data::FlightData::FlightPhaseManager
This is here so that the flight phase manager can set the flight phase.
start_time_
const bst::clck::TimePoint data::FlightData::start_time_ = bst::clck::now() private
A time point representing the start time of the flight runner.
Referenced by getUptimeSeconds(), and getUptimeString().
flight_phase_
std::atomic<FlightPhase> data::FlightData::flight_phase_ = FlightPhase::UNKNOWN private
The current flight phase.
Referenced by getFlightPhase(), setFlightPhase(), and toJson().
predicted_phase_
std::atomic<FlightPhase> data::FlightData::predicted_phase_ = FlightPhase::UNKNOWN private
The predicted flight phase. Used by the flight phase manager to determine the current phase.
Referenced by getPredictedPhase(), and setPhasePrediction().
have_launch_position_
std::atomic<bool> data::FlightData::have_launch_position_ = false private
True if the launch position has been set.
Referenced by getLaunchPosition(), setLaunchPosition(), and toJson().
launch_altitude_
std::atomic<double> data::FlightData::launch_altitude_ = 0.0 private
The launch position.
Referenced by getLaunchPosition(), setLaunchPosition(), and toJson().
launch_position_latitude_
std::atomic<double> data::FlightData::launch_position_latitude_ = 0.0 private
Referenced by getLaunchPosition(), setLaunchPosition(), and toJson().
launch_position_longitude_
std::atomic<double> data::FlightData::launch_position_longitude_ = 0.0 private
Referenced by getLaunchPosition(), setLaunchPosition(), and toJson().
launch_prediction_
std::atomic<double> data::FlightData::launch_prediction_ = 0.0 private
Referenced by setPhasePrediction(), and toJson().
ascent_prediction_
std::atomic<double> data::FlightData::ascent_prediction_ = 0.0 private
Referenced by setPhasePrediction(), and toJson().
descent_prediction_
std::atomic<double> data::FlightData::descent_prediction_ = 0.0 private
Referenced by setPhasePrediction(), and toJson().
recovery_prediction_
std::atomic<double> data::FlightData::recovery_prediction_ = 0.0 private
Referenced by setPhasePrediction(), and toJson().
prediction_quality_
std::atomic<double> data::FlightData::prediction_quality_ = 0.0 private
Referenced by setPhasePrediction().
bit_test_buffer_mutex_
std::mutex data::FlightData::bit_test_buffer_mutex_ {} private
Referenced by getBitTestData(), and setBitTestData().
bit_test_buffer_
Json data::FlightData::bit_test_buffer_ {} private
Referenced by getBitTestData(), and setBitTestData().