Giraffe: cfg::CfgSection Class Reference
cfg::CfgSection Class Reference
This is the base class for all configuration sections.
#include <cfg_section.hpp>
Public Member Functions
CfgSection (data::Streams &streams)
Protected Member Functions
void error (DiagnosticId diagnostic_id, const std::string &info="")
Logs a debug message.
Protected Attributes
std::mutex cfg_lock_ = std::mutex()
data::Streams & streams_
Detailed Description
This is the base class for all configuration sections.
Note
This isn't an immediate thing, but this will be slow if the config is accessed often. However, it is thread safe. right now and most sections aren't accessed all that often.
Constructor & Destructor Documentation
CfgSection()
cfg::CfgSection::CfgSection (data::Streams & streams) inline
Member Function Documentation
error()
void cfg::CfgSection::error (DiagnosticId diagnostic_id, const std::string & info = "") inline protected
Logs a debug message.
Note
This currently isn't used as the rest is autogenerated, but it really should be.
Parameters
diagnostic_id The id of the log.
info The information to log.
References node::CONFIGURATION, data::LogStream::error(), data::Streams::log, and streams_.
Referenced by cfg::AdcMappings::addAdcConfig(), cfg::Extensions::addExtension(), cfg::AdcMappings::removeAdcConfig(), cfg::Extensions::removeExtension(), cfg::AdcMappings::setFromJson(), cfg::Extensions::setFromJson(), cfg::Extensions::toggleExtension(), cfg::AdcMappings::updateAdcConfig(), and cfg::Extensions::updateExtension().
Member Data Documentation
cfg_lock_
std::mutex cfg::CfgSection::cfg_lock_ = std::mutex() mutable protected
Referenced by cfg::AdcMappings::addAdcConfig(), cfg::Extensions::addExtension(), cfg::AdcMappings::getAdcConfigs(), cfg::Extensions::getExtensions(), cfg::AdcMappings::getJson(), cfg::Extensions::getJson(), cfg::AdcMappings::removeAdcConfig(), cfg::Extensions::removeExtension(), cfg::AdcMappings::setFromJson(), cfg::Extensions::setFromJson(), cfg::Extensions::toggleExtension(), cfg::AdcMappings::updateAdcConfig(), and cfg::Extensions::updateExtension().
streams_
data::Streams& cfg::CfgSection::streams_ protected
Referenced by error(), cfg::AdcMappings::setFromJson(), and cfg::Extensions::setFromJson().