Giraffe: data::blocks::Block< T > Class Template Reference
data::blocks::Block< T > Class Template Reference
Simple Struct Container with a mutex. The struct must have a valid default constructor.
#include <blocks.hpp>
Public Member Functions
T get ()
int getAgeMs ()
int getAgeSec ()
void set (T data)
Private Attributes
T data_ = T()
bst::clck::TimePoint last_updated_ = bst::clck::now()
std::mutex mutex_ = std::mutex()
Detailed Description
template<class T>
class data::blocks::Block< T >
Simple Struct Container with a mutex. The struct must have a valid default constructor.
Member Function Documentation
set()
template<class T > void data::blocks::Block< T >::set (T data) inline
References data::blocks::Block< T >::data_, data::blocks::Block< T >::get(), data::blocks::Block< T >::last_updated_, and data::blocks::Block< T >::mutex_.
get()
template<class T > T data::blocks::Block< T >::get () inline
References data::blocks::Block< T >::data_, data::blocks::Block< T >::get(), and data::blocks::Block< T >::mutex_.
Referenced by data::blocks::Block< T >::get(), data::blocks::Block< T >::getAgeMs(), data::blocks::Block< T >::getAgeSec(), data::blocks::Block< T >::set(), and PredictionParameters::updateParameters().
getAgeMs()
template<class T > int data::blocks::Block< T >::getAgeMs () inline
References data::blocks::Block< T >::get(), data::blocks::Block< T >::last_updated_, and data::blocks::Block< T >::mutex_.
getAgeSec()
template<class T > int data::blocks::Block< T >::getAgeSec () inline
References data::blocks::Block< T >::get(), data::blocks::Block< T >::last_updated_, and data::blocks::Block< T >::mutex_.
Member Data Documentation
mutex_
template<class T > std::mutex data::blocks::Block< T >::mutex_ = std::mutex() private
Referenced by data::blocks::Block< T >::get(), data::blocks::Block< T >::getAgeMs(), data::blocks::Block< T >::getAgeSec(), and data::blocks::Block< T >::set().
data_
template<class T > T data::blocks::Block< T >::data_ = T() private
Referenced by data::blocks::Block< T >::get(), and data::blocks::Block< T >::set().
last_updated_
template<class T > bst::clck::TimePoint data::blocks::Block< T >::last_updated_ = bst::clck::now() private
Referenced by data::blocks::Block< T >::getAgeMs(), data::blocks::Block< T >::getAgeSec(), and data::blocks::Block< T >::set().