Giraffe: giraffe::gdl::MessageQueue Class Reference
giraffe::gdl::MessageQueue Class Reference
A queue for messages.
#include <gdl_message.hpp>
Public Member Functions
MessageQueue ()=default
~MessageQueue ()=default
bool peek (Message &message)
Peek at the next message on the queue.
bool pop (Message &message)
Pop a message from the queue.
bool push (Message message)
Push a message onto the queue.
uint8_t size () const
Get the size of the queue.
Private Attributes
std::mutex mutex_ {}
std::queue< Message > queue_ {}
Detailed Description
A queue for messages.
Constructor & Destructor Documentation
MessageQueue()
giraffe::gdl::MessageQueue::MessageQueue () default
~MessageQueue()
giraffe::gdl::MessageQueue::~MessageQueue () default
Member Function Documentation
push()
bool giraffe::gdl::MessageQueue::push (Message message)
Push a message onto the queue.
This will lock the queue. If there is no space on the queue, the message will not be pushed and false will be returned.
Parameters
message - The message to push.
Returns
true - If the message was pushed.
false - If the message was not pushed.
References giraffe::gdl::GDL_MESSAGE_QUEUES_SIZE, mutex_, and queue_.
Referenced by giraffe::gdl::DataLink::broadcastText(), giraffe::gdl::DataLink::gdlThread(), giraffe::gdl::DataLink::sendMessage(), giraffe::gdl::DataLink::sendTelemetryBitSense(), giraffe::gdl::DataLink::sendTelemetryCoefficients(), giraffe::gdl::DataLink::sendTelemetryData(), giraffe::gdl::DataLink::sendTelemetryParameterNames(), giraffe::gdl::DataLink::sendTelemetryUnitsAndLabels(), and giraffe::gdl::DataLink::sendText().
peek()
bool giraffe::gdl::MessageQueue::peek (Message & message)
Peek at the next message on the queue.
This will lock the queue. If there is no message on the queue, false will be returned.
Parameters
message - The message that was peeked.
Returns
true - If a message was peeked.
false - If a message was not peeked.
References mutex_, and queue_.
Referenced by giraffe::gdl::DataLink::gdlThread().
pop()
bool giraffe::gdl::MessageQueue::pop (Message & message)
Pop a message from the queue.
This will lock the queue. If there is no message on the queue, false will be returned.
Parameters
message - The message that was popped.
Returns
true - If a message was popped.
false - If a message was not popped.
References mutex_, and queue_.
Referenced by giraffe::gdl::DataLink::gdlThread(), and giraffe::gdl::DataLink::receiveMessage().
size()
uint8_t giraffe::gdl::MessageQueue::size () const
Get the size of the queue.
Returns
int - The size of the queue.
References mutex_, and queue_.
Referenced by giraffe::gdl::DataLink::gdlThread(), and giraffe::gdl::DataLink::messageAvailable().
Member Data Documentation
mutex_
std::mutex giraffe::gdl::MessageQueue::mutex_ {} mutable private
Referenced by peek(), pop(), push(), and size().
queue_
std::queue<Message> giraffe::gdl::MessageQueue::queue_ {} private
Referenced by peek(), pop(), push(), and size().