Giraffe: extension::SimHumiditySensor Class Reference
extension::SimHumiditySensor Class Reference
#include <simulated_extensions.hpp>
Public Member Functions
SimHumiditySensor (ExtensionResources &resources, cfg::ExtensionMetadata metadata)
DiagnosticId getFaultCode () const
Get the Fault Code when the status is ERROR.
node::Status getStatus () const
Get the Status of the extension.
bool isFaulted () const
Returns true if the extension is in a faulted state.
void loop () override
void reset ()
Only to be called when an extension is in the Error state. This joins the thread and fixes the status.
void start ()
Starts the extension.
void stop ()
Sends a stop signal to the extension.
Protected Member Functions
template<typename T >
void data (data::DataId identifier, T value, int precision=2)
void data (data::GpsFrame frame)
templates for Extension::data
void data (data::ImuFrame frame)
void debug (std::string message)
For when debugging is enabled, simple debug messages can be sent to the log.
void error (DiagnosticId log_id, int info)
void error (DiagnosticId, const std::string &info="")
void extSleep (uint32_t milliseconds)
Sleep internally for a given number of milliseconds.
void info (std::string info)
void raiseFault (DiagnosticId ext_fault_code, std::string info="")
Used internally to raise a fault. This will stop an extension.
virtual void shutdown ()
virtual void startup ()
bool stopRequested () const
Returns true if the extension has been requested to stop.
Protected Attributes
cfg::ExtensionMetadata metadata_
Private Member Functions
void runner ()
void sleep ()
Private Attributes
std::atomic< DiagnosticId > fault_code_ = DiagnosticId::EXT_FAULT_none
The fault code associated with the fault.
std::atomic< bool > fault_flag_ = false
This is raised with a call to raiseFault().
bool increasing_ = false
ExtensionResources & interfaces_
double rh_ = 100.0
std::thread runner_thread_ = std::thread()
std::atomic< node::Status > status_ = node::Status::STOPPED
std::atomic< bool > stop_flag_ = true
Constructor & Destructor Documentation
SimHumiditySensor()
extension::SimHumiditySensor::SimHumiditySensor (ExtensionResources & resources, cfg::ExtensionMetadata metadata) inline
Member Function Documentation
loop()
void extension::SimHumiditySensor::loop () inline override virtual
Reimplemented from extension::Extension.
References extension::Extension::data(), increasing_, and rh_.
start()
void extension::Extension::start () inherited
Starts the extension.
References extension::Extension::error(), extension::Extension::fault_code_, extension::Extension::fault_flag_, node::K_ACTIVE_STATUSES, extension::Extension::runner(), extension::Extension::runner_thread_, extension::Extension::status_, and extension::Extension::stop_flag_.
stop()
void extension::Extension::stop () inherited
Sends a stop signal to the extension.
The timeout for stopping an extension.
The interval of how often to check if the extension has stopped.
References extension::Extension::error(), node::K_INACTIVE_STATUSES, extension::Extension::runner_thread_, extension::Extension::status_, and extension::Extension::stop_flag_.
Referenced by extension::Extension::~Extension(), and extension::Extension::reset().
reset()
void extension::Extension::reset () inherited
Only to be called when an extension is in the Error state. This joins the thread and fixes the status.
References extension::Extension::status_, extension::Extension::stop(), and node::STOPPED.
getStatus()
node::Status extension::Extension::getStatus () const inline inherited
Get the Status of the extension.
Returns
node::Status The status of the extension.
References extension::Extension::status_.
getFaultCode()
DiagnosticId extension::Extension::getFaultCode () const inline inherited
Get the Fault Code when the status is ERROR.
Returns
DiagnosticId The fault code.
References extension::Extension::fault_code_.
isFaulted()
bool extension::Extension::isFaulted () const inline inherited
Returns true if the extension is in a faulted state.
Returns
true if the extension is in a faulted state, false otherwise.
References extension::Extension::fault_flag_.
Referenced by extension::AdcExtensionBase< AdcResolution >::startup().
startup()
virtual void extension::Extension::startup () inline protected virtual inherited
Reimplemented in extension::SamM8qExtension, extension::Ds18b20Extension, extension::Bme280Extension, extension::AdcExtensionBase< AdcResolution >, and extension::AdcExtensionBase< 10 >.
Referenced by extension::Extension::runner().
shutdown()
virtual void extension::Extension::shutdown () inline protected virtual inherited
Reimplemented in extension::SamM8qExtension, extension::AdcExtensionBase< AdcResolution >, and extension::AdcExtensionBase< 10 >.
Referenced by extension::Extension::runner().
data() [1/3]
template<typename T > void extension::Extension::data (data::DataId identifier, T value, int precision = 2) protected inherited
References data::Stream< T >::addPacket(), data::Streams::data, data::DataPacket::identifier, extension::Extension::interfaces_, kExtensionId, extension::Extension::metadata_, cfg::ExtensionMetadata::name, data::BaseStreamPacket::secondary_identifier, data::BaseStreamPacket::source, extension::ExtensionResources::streams, util::to_string(), and data::DataPacket::value.
Referenced by extension::AdcExtensionBase< AdcResolution >::loop(), extension::Bme280Extension::loop(), extension::Ds18b20Extension::loop(), extension::SimTemperatureSensor::loop(), extension::SimPressureSensor::loop(), loop(), extension::SimGpsSensor::loop(), extension::SimImuSensor::loop(), extension::AdcExtensionBase< AdcResolution >::percentage(), extension::Bme280Extension::readEnvironmentalData(), extension::SamM8qExtension::stateRead(), extension::AdcExtensionBase< AdcResolution >::voltageDivider(), and extension::AdcExtensionBase< AdcResolution >::voltageReference().
data() [2/3]
void extension::Extension::data (data::GpsFrame frame) protected inherited
templates for Extension::data
 */
template void Extension::data<int>(data::DataId, int, int);
template void Extension::data<float>(data::DataId, float, int);
template void Extension::data<double>(data::DataId, double, int);
template void Extension::data<uint32_t>(data::DataId, uint32_t, int);
template void Extension::data<std::string>(data::DataId, std::string, int);
/**
 *
References data::GpsFrameStream::addFrame(), node::EXTENSION, data::Streams::gps, extension::Extension::interfaces_, extension::Extension::metadata_, cfg::ExtensionMetadata::name, and extension::ExtensionResources::streams.
data() [3/3]
void extension::Extension::data (data::ImuFrame frame) protected inherited
References data::ImuFrameStream::addFrame(), node::EXTENSION, data::Streams::imu, extension::Extension::interfaces_, extension::Extension::metadata_, cfg::ExtensionMetadata::name, and extension::ExtensionResources::streams.
error() [1/2]
void extension::Extension::error (DiagnosticId log_id, const std::string & info = "") protected inherited
References data::Stream< T >::addPacket(), data::LogPacket::id, data::LogPacket::info, extension::Extension::interfaces_, kExtensionId, data::Streams::log, extension::Extension::metadata_, cfg::ExtensionMetadata::name, data::BaseStreamPacket::secondary_identifier, data::BaseStreamPacket::source, and extension::ExtensionResources::streams.
Referenced by extension::AdcExtensionBase< AdcResolution >::AdcExtensionBase(), extension::Mcp3021Extension::adcStartup(), extension::Bme280Extension::loop(), extension::Ds18b20Extension::loop(), extension::Bme280Extension::processEnvironmentalData(), extension::Extension::raiseFault(), extension::Extension::start(), extension::SamM8qExtension::stateConfigure(), extension::SamM8qExtension::stateRead(), and extension::Extension::stop().
error() [2/2]
void extension::Extension::error (DiagnosticId log_id, int info) protected inherited
References data::Stream< T >::addPacket(), data::LogPacket::id, extension::Extension::info(), data::LogPacket::info, extension::Extension::interfaces_, kExtensionId, data::Streams::log, extension::Extension::metadata_, cfg::ExtensionMetadata::name, data::BaseStreamPacket::secondary_identifier, data::BaseStreamPacket::source, extension::ExtensionResources::streams, and util::to_string().
info()
void extension::Extension::info (std::string info) protected inherited
References data::Stream< T >::addPacket(), data::LogPacket::id, data::LogPacket::info, extension::Extension::interfaces_, kExtensionId, data::Streams::log, extension::Extension::metadata_, cfg::ExtensionMetadata::name, data::BaseStreamPacket::secondary_identifier, data::BaseStreamPacket::source, and extension::ExtensionResources::streams.
Referenced by extension::Extension::error().
stopRequested()
bool extension::Extension::stopRequested () const protected inherited
Returns true if the extension has been requested to stop.
This should be used in the loop() function for extensions that take a long time to complete a single loop iteration. This is helpful for to stop extensions quickly upon request. Fast extensions do not need to use this.
Returns
true - The extension has been requested to stop.
false - The extension has not been requested to stop.
References extension::Extension::stop_flag_.
Referenced by extension::Extension::sleep(), extension::Bme280Extension::startup(), extension::Ds18b20Extension::startup(), and extension::SamM8qExtension::startup().
raiseFault()
void extension::Extension::raiseFault (DiagnosticId ext_fault_code, std::string info = "") protected inherited
Used internally to raise a fault. This will stop an extension.
References extension::Extension::error(), extension::Extension::fault_code_, extension::Extension::fault_flag_, and extension::Extension::stop_flag_.
Referenced by extension::Mcp3021Extension::adcStartup(), extension::AdcExtensionBase< AdcResolution >::loop(), extension::Bme280Extension::loop(), extension::Ds18b20Extension::loop(), extension::Bme280Extension::startup(), extension::Ds18b20Extension::startup(), extension::SamM8qExtension::startup(), and extension::SamM8qExtension::stateReset().
debug()
void extension::Extension::debug (std::string message) protected inherited
For when debugging is enabled, simple debug messages can be sent to the log.
Parameters
message
extSleep()
void extension::Extension::extSleep (uint32_t milliseconds) protected inherited
Sleep internally for a given number of milliseconds.
This has a limit of 1 second.
Parameters
milliseconds - The number of milliseconds to sleep.
Referenced by extension::Bme280Extension::startup(), extension::Ds18b20Extension::startup(), extension::SamM8qExtension::startup(), and extension::SamM8qExtension::stateRead().
sleep()
void extension::Extension::sleep () private inherited
References extension::Extension::metadata_, extension::Extension::stopRequested(), and cfg::ExtensionMetadata::update_interval.
Referenced by extension::Extension::runner().
runner()
void extension::Extension::runner () private inherited
References node::ERROR, extension::Extension::fault_flag_, extension::Extension::loop(), node::RUNNING, extension::Extension::shutdown(), extension::Extension::sleep(), node::STARTING, extension::Extension::startup(), extension::Extension::status_, extension::Extension::stop_flag_, node::STOPPED, and node::STOPPING.
Referenced by extension::Extension::start().
Member Data Documentation
rh_
double extension::SimHumiditySensor::rh_ = 100.0 private
Referenced by loop().
increasing_
bool extension::SimHumiditySensor::increasing_ = false private
Referenced by loop().
metadata_
cfg::ExtensionMetadata extension::Extension::metadata_ protected inherited
Referenced by extension::Extension::data(), extension::Extension::error(), extension::Extension::info(), extension::Ds18b20Extension::init(), and extension::Extension::sleep().
fault_flag_
std::atomic<bool> extension::Extension::fault_flag_ = false private inherited
This is raised with a call to raiseFault().
This is used to stop the extension. Cleared on a call to start().
Referenced by extension::Extension::isFaulted(), extension::Extension::raiseFault(), extension::Extension::runner(), and extension::Extension::start().
fault_code_
std::atomic<DiagnosticId> extension::Extension::fault_code_ = DiagnosticId::EXT_FAULT_none private inherited
The fault code associated with the fault.
This is set when raiseFault() is called. Cleared on a call to start().
Referenced by extension::Extension::getFaultCode(), extension::Extension::raiseFault(), and extension::Extension::start().
status_
std::atomic<node::Status> extension::Extension::status_ = node::Status::STOPPED private inherited
Referenced by extension::Extension::getStatus(), extension::Extension::reset(), extension::Extension::runner(), extension::Extension::start(), and extension::Extension::stop().
stop_flag_
std::atomic<bool> extension::Extension::stop_flag_ = true private inherited
Referenced by extension::Extension::raiseFault(), extension::Extension::runner(), extension::Extension::start(), extension::Extension::stop(), and extension::Extension::stopRequested().
runner_thread_
std::thread extension::Extension::runner_thread_ = std::thread() private inherited
Referenced by extension::Extension::start(), and extension::Extension::stop().
interfaces_
ExtensionResources& extension::Extension::interfaces_ private inherited
Referenced by extension::Extension::data(), extension::Extension::error(), and extension::Extension::info().