Giraffe: gdl::GiraffeDataLink Class Reference
gdl::GiraffeDataLink Class Reference
The Giraffe Data Link core class/interface - Layer 4 (Application)
#include <giraffe_data_link.hpp>
Classes
struct MessageQueues
Public Types
enum class ConnectionStatus { DISCONNECTED , CONNECTED }
enum class Status {
ERROR , STOPPED , STARTING , RUNNING ,
STOPPING
}
The status of the GDL instance.
Public Member Functions
GiraffeDataLink (GdlConfig config, SessionLayer &session_layer)
Create a new Giraffe Data Link instance.
~GiraffeDataLink ()
Deconstruct the GDL instance, this will stop the GDL instance if it is running.
int getBroadcastQueueSize () const
ConnectionStatus getConnectionStatus () const
Get the connection status of the GDL instance.
int getExchangeQueueSize () const
bool getReceivedMessage (Message &message)
Get a message from the receive queue.
int getReceiveQueueSize () const
GiraffeDataLink::Status getStatus () const
Get the status of the GDL instance.
bool sendBroadcastMessage (Message message)
Add a message to the broadcast queue.
bool sendExchangeMessage (Message message)
Add a message to the exchange queue.
void start ()
Start the GDL instance.
void stop ()
Stop the GDL instance.
Private Member Functions
void gdlThread ()
The main thread function for GDL.
Private Attributes
const GdlConfig config_
The configuration for the GDL instance.
std::atomic< ConnectionStatus > connection_status_
The status of the connection.
std::thread gdl_thread_ {}
The thread that runs GDL.
MessageQueues queues_
The queues for the GDL instance.
SessionLayer & session_layer_
The session layer for the GDL instance.
std::atomic< Status > status_ {Status::STOPPED}
The status of the GDL instance.
Detailed Description
The Giraffe Data Link core class/interface - Layer 4 (Application)
Member Enumeration Documentation
Status
enum gdl::GiraffeDataLink::Status strong
The status of the GDL instance.
Enumerator
ERROR
STOPPED
STARTING
RUNNING
STOPPING
ConnectionStatus
enum gdl::GiraffeDataLink::ConnectionStatus strong
Enumerator
DISCONNECTED
CONNECTED
Constructor & Destructor Documentation
GiraffeDataLink()
gdl::GiraffeDataLink::GiraffeDataLink (GdlConfig config, SessionLayer & session_layer)
Create a new Giraffe Data Link instance.
Parameters
config - The configuration for the GDL instance
session_layer - The session layer for the GDL instance
~GiraffeDataLink()
gdl::GiraffeDataLink::~GiraffeDataLink ()
Deconstruct the GDL instance, this will stop the GDL instance if it is running.
References RUNNING, status_, and stop().
Member Function Documentation
start()
void gdl::GiraffeDataLink::start ()
Start the GDL instance.
If it's already running, this will do nothing.
References gdl_thread_, gdlThread(), STARTING, status_, and STOPPED.
stop()
void gdl::GiraffeDataLink::stop ()
Stop the GDL instance.
If it's already stopped, this will do nothing.
References gdl_thread_, RUNNING, status_, and STOPPING.
Referenced by ~GiraffeDataLink().
getStatus()
GiraffeDataLink::Status gdl::GiraffeDataLink::getStatus () const
Get the status of the GDL instance.
Returns
GiraffeDataLink::Status - The status of the GDL instance.
References status_.
getConnectionStatus()
GiraffeDataLink::ConnectionStatus gdl::GiraffeDataLink::getConnectionStatus () const
Get the connection status of the GDL instance.
Returns
GiraffeDataLink::ConnectionStatus - The connection status
References connection_status_.
sendExchangeMessage()
bool gdl::GiraffeDataLink::sendExchangeMessage (Message message)
Add a message to the exchange queue.
Requires a connection.
Parameters
message - The message to add to the queue.
Returns
true - If the message was added to the queue.
false - If the message was not added to the queue.
References gdl::GiraffeDataLink::MessageQueues::exchange, gdl::MessageQueue::push(), queues_, RUNNING, and status_.
sendBroadcastMessage()
bool gdl::GiraffeDataLink::sendBroadcastMessage (Message message)
Add a message to the broadcast queue.
Does not require a connection.
Parameters
message - The message to add to the queue.
Returns
true - If the message was added to the queue.
false - If the message was not added to the queue.
References gdl::GiraffeDataLink::MessageQueues::broadcast, gdl::MessageQueue::push(), queues_, RUNNING, and status_.
getReceivedMessage()
bool gdl::GiraffeDataLink::getReceivedMessage (Message & message)
Get a message from the receive queue.
Parameters
message (out) - The message to get from the queue.
Returns
true - If a message was available.
false - If a message was not available.
References gdl::MessageQueue::pop(), queues_, and gdl::GiraffeDataLink::MessageQueues::received.
getExchangeQueueSize()
int gdl::GiraffeDataLink::getExchangeQueueSize () const
References gdl::GiraffeDataLink::MessageQueues::exchange, queues_, and gdl::MessageQueue::size().
getBroadcastQueueSize()
int gdl::GiraffeDataLink::getBroadcastQueueSize () const
References gdl::GiraffeDataLink::MessageQueues::broadcast, queues_, and gdl::MessageQueue::size().
getReceiveQueueSize()
int gdl::GiraffeDataLink::getReceiveQueueSize () const
References queues_, gdl::GiraffeDataLink::MessageQueues::received, and gdl::MessageQueue::size().
gdlThread()
void gdl::GiraffeDataLink::gdlThread () private
The main thread function for GDL.
References RUNNING, and status_.
Referenced by start().
Member Data Documentation
config_
const GdlConfig gdl::GiraffeDataLink::config_ private
The configuration for the GDL instance.
queues_
MessageQueues gdl::GiraffeDataLink::queues_ private
The queues for the GDL instance.
Referenced by getBroadcastQueueSize(), getExchangeQueueSize(), getReceivedMessage(), getReceiveQueueSize(), sendBroadcastMessage(), and sendExchangeMessage().
session_layer_
SessionLayer& gdl::GiraffeDataLink::session_layer_ private
The session layer for the GDL instance.
gdl_thread_
std::thread gdl::GiraffeDataLink::gdl_thread_ {} private
The thread that runs GDL.
Referenced by start(), and stop().
status_
std::atomic<Status> gdl::GiraffeDataLink::status_ {Status::STOPPED} private
The status of the GDL instance.
Referenced by ~GiraffeDataLink(), gdlThread(), getStatus(), sendBroadcastMessage(), sendExchangeMessage(), start(), and stop().
connection_status_
std::atomic<ConnectionStatus> gdl::GiraffeDataLink::connection_status_ private
Initial value:
{
      ConnectionStatus::DISCONNECTED}
The status of the connection.
Referenced by getConnectionStatus().