Giraffe: data::Frame< ID, DATA > Class Template Reference
data::Frame< ID, DATA > Class Template Reference
A generic frame (map) for storing data.
#include <frame.hpp>
Public Member Functions
Frame ()=default
~Frame ()=default
void clear ()
Clears all contents of the frame.
bool get (const ID key, DATA &data) const
Get an item from the frame.
std::unordered_map< ID, DATA > getAll () const
bool in (const ID &key) const
Returns true if an item is in the frame, false if it is not.
void insert (const ID &key, const DATA &value)
Insert or replace an item.
bool remove (const ID &key)
Removes an item from the frame.
int size () const
Returns the total items in the frame.
Protected Attributes
std::unordered_map< ID, DATA > frame_ = std::unordered_map<ID, DATA>()
Private Attributes
std::mutex frame_lock_ = std::mutex()
Detailed Description
template<class ID, class DATA>
class data::Frame< ID, DATA >
A generic frame (map) for storing data.
This class is thread safe.
Template Parameters
ID - The identifier type.
DATA - The data type.
Constructor & Destructor Documentation
Frame()
template<class ID , class DATA > data::Frame< ID, DATA >::Frame () default
~Frame()
template<class ID , class DATA > data::Frame< ID, DATA >::~Frame () default
Member Function Documentation
insert()
template<class ID , class DATA > void data::Frame< ID, DATA >::insert (const ID & key, const DATA & value) inline
Insert or replace an item.
References data::Frame< ID, DATA >::frame_, data::Frame< ID, DATA >::frame_lock_, and data::Frame< ID, DATA >::get().
Referenced by data::ErrorFrame::addError(), data_middleware::AdcInterpolation::insertVoltageDividerValue(), and data_middleware::AdcInterpolation::processDataPacket().
in()
template<class ID , class DATA > bool data::Frame< ID, DATA >::in (const ID & key) const inline
Returns true if an item is in the frame, false if it is not.
Returns
true
false
References data::Frame< ID, DATA >::frame_, data::Frame< ID, DATA >::frame_lock_, and data::Frame< ID, DATA >::get().
Referenced by data::ErrorFrame::isActive().
get()
template<class ID , class DATA > bool data::Frame< ID, DATA >::get (const ID key, DATA & data) const inline
Get an item from the frame.
Parameters
key - The identifier of the item to get.
data - The data to be returned.
Returns
true - If the item was found.
false - If the item was not found.
References data::Frame< ID, DATA >::frame_, data::Frame< ID, DATA >::frame_lock_, and data::Frame< ID, DATA >::get().
Referenced by data::ErrorFrame::addError(), data::Frame< ID, DATA >::clear(), data::Frame< ID, DATA >::get(), data::Frame< ID, DATA >::getAll(), data::ErrorFrame::getError(), data::Frame< ID, DATA >::in(), data::Frame< ID, DATA >::insert(), data::ErrorFrame::lastOccurrence(), data::ErrorFrame::numOccurrences(), data::Frame< ID, DATA >::remove(), and data::Frame< ID, DATA >::size().
clear()
template<class ID , class DATA > void data::Frame< ID, DATA >::clear () inline
Clears all contents of the frame.
References data::Frame< ID, DATA >::frame_, data::Frame< ID, DATA >::frame_lock_, and data::Frame< ID, DATA >::get().
Referenced by data::ErrorFrame::clearAllErrors().
size()
template<class ID , class DATA > int data::Frame< ID, DATA >::size () const inline
Returns the total items in the frame.
References data::Frame< ID, DATA >::frame_, data::Frame< ID, DATA >::frame_lock_, and data::Frame< ID, DATA >::get().
Referenced by data::ErrorFrame::numActiveErrors().
remove()
template<class ID , class DATA > bool data::Frame< ID, DATA >::remove (const ID & key) inline
Removes an item from the frame.
Parameters
key - The identifier of the item to remove.
Returns
true - If the item was removed.
false - If the item was not removed.
References data::Frame< ID, DATA >::frame_, data::Frame< ID, DATA >::frame_lock_, and data::Frame< ID, DATA >::get().
Referenced by data::ErrorFrame::clearError().
getAll()
template<class ID , class DATA > std::unordered_map< ID, DATA > data::Frame< ID, DATA >::getAll () const inline
References data::Frame< ID, DATA >::frame_, data::Frame< ID, DATA >::frame_lock_, and data::Frame< ID, DATA >::get().
Referenced by data::toJson(), and data::toJson().
Member Data Documentation
frame_
template<class ID , class DATA > std::unordered_map<ID, DATA> data::Frame< ID, DATA >::frame_ = std::unordered_map<ID, DATA>() protected
Referenced by data::Frame< ID, DATA >::clear(), data::Frame< ID, DATA >::get(), data::ErrorFrame::getActiveErrorIds(), data::Frame< ID, DATA >::getAll(), data::ErrorFrame::getFullFrame(), data::Frame< ID, DATA >::in(), data::Frame< ID, DATA >::insert(), data::Frame< ID, DATA >::remove(), and data::Frame< ID, DATA >::size().
frame_lock_
template<class ID , class DATA > std::mutex data::Frame< ID, DATA >::frame_lock_ = std::mutex() mutable private
Referenced by data::Frame< ID, DATA >::clear(), data::Frame< ID, DATA >::get(), data::Frame< ID, DATA >::getAll(), data::Frame< ID, DATA >::in(), data::Frame< ID, DATA >::insert(), data::Frame< ID, DATA >::remove(), and data::Frame< ID, DATA >::size().