Giraffe: gfs_sim::GfsSimulator Class Reference
gfs_sim::GfsSimulator Class Reference
#include <gfs_simulator.hpp>
Public Member Functions
GfsSimulator ()=default
~GfsSimulator ()
double getAltitudeM () const
double getBatteryVoltage () const
double getHeadingDeg () const
double getHorzVelocityMps () const
double getHumidityPercent () const
double getLatitudeDeg () const
double getLongitudeDeg () const
double getPressureMbar () const
double getTemperatureC () const
double getVertAccelMps2 () const
double getVertVelocityMps () const
bool isRunning () const
void launch ()
void start ()
void stop ()
Private Member Functions
void printData ()
void run ()
void stateAscent ()
void stateDescent ()
void stateLanded ()
void stateLanding ()
void stateMachine ()
void statePop ()
void statePreLaunch ()
Private Attributes
double elapsed_seconds_ {0.0}
SimElectrical electrical_ {sim_data_}
SimEnvironmental environment_ {sim_data_}
bst::Stopwatch flight_stopwatch_ {}
BalloonPhysics physics_ {state_, environment_, sim_data_}
bst::Timer print_timer_ {K_PRINT_INTERVAL_MS}
SimData sim_data_ {}
std::thread sim_thread_ {}
SimState state_ {SimState::PRE_LAUNCH}
bst::Timer state_machine_timer_ {K_UPDATE_INTERVAL_MS}
std::atomic< bool > stop_flag_ {false}
Constructor & Destructor Documentation
GfsSimulator()
gfs_sim::GfsSimulator::GfsSimulator () default
~GfsSimulator()
gfs_sim::GfsSimulator::~GfsSimulator () inline
References stop().
Member Function Documentation
start()
void gfs_sim::GfsSimulator::start ()
References run(), sim_thread_, and stop_flag_.
Referenced by main().
stop()
void gfs_sim::GfsSimulator::stop ()
References sim_thread_, and stop_flag_.
Referenced by ~GfsSimulator().
isRunning()
bool gfs_sim::GfsSimulator::isRunning () const
References sim_thread_, and stop_flag_.
launch()
void gfs_sim::GfsSimulator::launch () inline
References gfs_sim::BalloonPhysics::launch(), gfs_sim::log(), and physics_.
getTemperatureC()
double gfs_sim::GfsSimulator::getTemperatureC () const inline
References sim_data_, and gfs_sim::SimData::temperature_c.
getPressureMbar()
double gfs_sim::GfsSimulator::getPressureMbar () const inline
References gfs_sim::SimData::pressure_mbar, and sim_data_.
getHumidityPercent()
double gfs_sim::GfsSimulator::getHumidityPercent () const inline
References gfs_sim::SimData::humidity_percent, and sim_data_.
getAltitudeM()
double gfs_sim::GfsSimulator::getAltitudeM () const inline
References gfs_sim::SimData::altitude_m, and sim_data_.
getVertVelocityMps()
double gfs_sim::GfsSimulator::getVertVelocityMps () const inline
References sim_data_, and gfs_sim::SimData::vert_velocity_mps.
getVertAccelMps2()
double gfs_sim::GfsSimulator::getVertAccelMps2 () const inline
References sim_data_, and gfs_sim::SimData::vert_accel_mps2.
getHorzVelocityMps()
double gfs_sim::GfsSimulator::getHorzVelocityMps () const inline
References gfs_sim::SimData::horz_velocity_mps, and sim_data_.
getHeadingDeg()
double gfs_sim::GfsSimulator::getHeadingDeg () const inline
References gfs_sim::SimData::heading_deg, and sim_data_.
getLatitudeDeg()
double gfs_sim::GfsSimulator::getLatitudeDeg () const inline
References gfs_sim::SimData::latitude_deg, and sim_data_.
getLongitudeDeg()
double gfs_sim::GfsSimulator::getLongitudeDeg () const inline
References gfs_sim::SimData::longitude_deg, and sim_data_.
getBatteryVoltage()
double gfs_sim::GfsSimulator::getBatteryVoltage () const inline
References gfs_sim::SimData::battery_voltage, and sim_data_.
run()
void gfs_sim::GfsSimulator::run () private
References elapsed_seconds_, electrical_, flight_stopwatch_, gfs_sim::K_DELTA_TIME_S, gfs_sim::K_PRINT_SIM_DATA, gfs_sim::K_SLEEP_INTERVAL_MS, physics_, print_timer_, printData(), state_machine_timer_, stateMachine(), stop_flag_, gfs_sim::SimElectrical::update(), and gfs_sim::BalloonPhysics::update().
Referenced by start().
stateMachine()
void gfs_sim::GfsSimulator::stateMachine () private
References gfs_sim::ASCENT, gfs_sim::DESCENT, gfs_sim::LANDED, gfs_sim::LANDING, gfs_sim::POP, gfs_sim::PRE_LAUNCH, state_, stateAscent(), stateDescent(), stateLanded(), stateLanding(), statePop(), and statePreLaunch().
Referenced by run().
statePreLaunch()
void gfs_sim::GfsSimulator::statePreLaunch () private
Referenced by stateMachine().
stateAscent()
void gfs_sim::GfsSimulator::stateAscent () private
Referenced by stateMachine().
statePop()
void gfs_sim::GfsSimulator::statePop () private
Referenced by stateMachine().
stateDescent()
void gfs_sim::GfsSimulator::stateDescent () private
Referenced by stateMachine().
stateLanding()
void gfs_sim::GfsSimulator::stateLanding () private
Referenced by stateMachine().
stateLanded()
void gfs_sim::GfsSimulator::stateLanded () private
Referenced by stateMachine().
printData()
void gfs_sim::GfsSimulator::printData () private
References gfs_sim::ASCENT, gfs_sim::DESCENT, elapsed_seconds_, environment_, gfs_sim::BalloonPhysics::getAltitude(), gfs_sim::BalloonPhysics::getDirectionOfTravel(), gfs_sim::BalloonPhysics::getHorizontalSpeed(), gfs_sim::SimEnvironmental::getPressureMillibars(), gfs_sim::SimEnvironmental::getRelativeHumidityPercent(), gfs_sim::SimEnvironmental::getTemperatureCelsius(), gfs_sim::BalloonPhysics::getTotalDistance(), gfs_sim::BalloonPhysics::getVerticalSpeed(), gfs_sim::SimEnvironmental::getWindDirectionDegrees(), gfs_sim::SimEnvironmental::getWindSpeedMPS(), gfs_sim::LANDED, gfs_sim::LANDING, physics_, gfs_sim::POP, gfs_sim::PRE_LAUNCH, and state_.
Referenced by run().
Member Data Documentation
state_
SimState gfs_sim::GfsSimulator::state_ {SimState::PRE_LAUNCH} private
Referenced by printData(), and stateMachine().
state_machine_timer_
bst::Timer gfs_sim::GfsSimulator::state_machine_timer_ {K_UPDATE_INTERVAL_MS} private
Referenced by run().
print_timer_
bst::Timer gfs_sim::GfsSimulator::print_timer_ {K_PRINT_INTERVAL_MS} private
Referenced by run().
flight_stopwatch_
bst::Stopwatch gfs_sim::GfsSimulator::flight_stopwatch_ {} private
Referenced by run().
elapsed_seconds_
double gfs_sim::GfsSimulator::elapsed_seconds_ {0.0} private
Referenced by printData(), and run().
sim_data_
SimData gfs_sim::GfsSimulator::sim_data_ {} private
Referenced by getAltitudeM(), getBatteryVoltage(), getHeadingDeg(), getHorzVelocityMps(), getHumidityPercent(), getLatitudeDeg(), getLongitudeDeg(), getPressureMbar(), getTemperatureC(), getVertAccelMps2(), and getVertVelocityMps().
environment_
SimEnvironmental gfs_sim::GfsSimulator::environment_ {sim_data_} private
Referenced by printData().
physics_
BalloonPhysics gfs_sim::GfsSimulator::physics_ {state_, environment_, sim_data_} private
Referenced by launch(), printData(), and run().
electrical_
SimElectrical gfs_sim::GfsSimulator::electrical_ {sim_data_} private
Referenced by run().
stop_flag_
std::atomic<bool> gfs_sim::GfsSimulator::stop_flag_ {false} private
Referenced by isRunning(), run(), start(), and stop().
sim_thread_
std::thread gfs_sim::GfsSimulator::sim_thread_ {} private
Referenced by isRunning(), start(), and stop().