Giraffe: extension::I2cExtensionAdapter Class Reference
extension::I2cExtensionAdapter Class Reference abstract
Adapter for I2C Extensions.
#include <i2c_extension_adapter.hpp>
Protected Member Functions
I2cExtensionAdapter (ExtensionResources &resources, cfg::ExtensionMetadata &metadata, uint8_t i2c_address, uint32_t i2c_handshake_timeout_ms=kDefaultI2cHandshakeTimeoutMs, uint32_t i2c_handshake_retry_delay_ms=kDefaultI2cHandshakeRetryDelayMs)
virtual ~I2cExtensionAdapter ()=default
bool connectToI2cBus (DiagnosticId &error)
virtual bool i2cHandshake ()=0
Protected Attributes
I2cInterface i2c_
Private Attributes
bst::Timer handshake_timer_
uint32_t retry_delay_ms_
Detailed Description
Adapter for I2C Extensions.
Warning
This is currently not implemented!
Constructor & Destructor Documentation
I2cExtensionAdapter()
extension::I2cExtensionAdapter::I2cExtensionAdapter (ExtensionResources & resources, cfg::ExtensionMetadata & metadata, uint8_t i2c_address, uint32_t i2c_handshake_timeout_ms = kDefaultI2cHandshakeTimeoutMs, uint32_t i2c_handshake_retry_delay_ms = kDefaultI2cHandshakeRetryDelayMs) inline protected
References metadata.
~I2cExtensionAdapter()
virtual extension::I2cExtensionAdapter::~I2cExtensionAdapter () protected virtual default
Member Function Documentation
i2cHandshake()
virtual bool extension::I2cExtensionAdapter::i2cHandshake () protected pure virtual
Implemented in extension::Mcp3021.
Referenced by connectToI2cBus().
connectToI2cBus()
bool extension::I2cExtensionAdapter::connectToI2cBus (DiagnosticId & error) inline protected
References I2cInterface::ADDRESS_SET_ERROR, I2cInterface::BUS_OPEN_ERROR, I2cInterface::connect(), handshake_timer_, i2c_, i2cHandshake(), retry_delay_ms_, and I2cInterface::SUCCESS.
Referenced by extension::Mcp3021::adcStartup().
Member Data Documentation
i2c_
I2cInterface extension::I2cExtensionAdapter::i2c_ protected
Referenced by connectToI2cBus(), and extension::Mcp3021::readAdc().
handshake_timer_
bst::Timer extension::I2cExtensionAdapter::handshake_timer_ private
Referenced by connectToI2cBus().
retry_delay_ms_
uint32_t extension::I2cExtensionAdapter::retry_delay_ms_ private
Referenced by connectToI2cBus().