Giraffe: gdl::MessageQueue Class Reference
gdl::MessageQueue Class Reference
A queue for messages.
#include <gdl_message_queue.hpp>
Public Member Functions
MessageQueue (const uint8_t max_queue_size)
Construct a new Message Queue.
~MessageQueue ()=default
Destroy the Message Queue object.
bool pop (Message &message)
Pop a message from the queue.
bool push (Message message)
Push a message onto the queue.
uint8_t size () const
Get the size of the queue.
Private Attributes
const uint8_t max_size_
std::mutex mutex_ {}
std::queue< Message > queue_ {}
Detailed Description
A queue for messages.
Constructor & Destructor Documentation
MessageQueue()
gdl::MessageQueue::MessageQueue (const uint8_t max_queue_size) inline
Construct a new Message Queue.
Parameters
max_queue_size - The maximum size of the queue.
~MessageQueue()
gdl::MessageQueue::~MessageQueue () default
Destroy the Message Queue object.
Member Function Documentation
push()
bool gdl::MessageQueue::push (Message message)
Push a message onto the queue.
This will lock the queue. If there is no space on the queue, the message will not be pushed and false will be returned.
Parameters
message - The message to push.
Returns
true - If the message was pushed.
false - If the message was not pushed.
References max_size_, mutex_, and queue_.
Referenced by gdl::GiraffeDataLink::sendBroadcastMessage(), and gdl::GiraffeDataLink::sendExchangeMessage().
pop()
bool gdl::MessageQueue::pop (Message & message)
Pop a message from the queue.
This will lock the queue. If there is no message on the queue, false will be returned.
Parameters
message - The message that was popped.
Returns
true - If a message was popped.
false - If a message was not popped.
References mutex_, and queue_.
Referenced by gdl::GiraffeDataLink::getReceivedMessage().
size()
uint8_t gdl::MessageQueue::size () const
Get the size of the queue.
Returns
int - The size of the queue.
References mutex_, and queue_.
Referenced by gdl::GiraffeDataLink::getBroadcastQueueSize(), gdl::GiraffeDataLink::getExchangeQueueSize(), and gdl::GiraffeDataLink::getReceiveQueueSize().
Member Data Documentation
max_size_
const uint8_t gdl::MessageQueue::max_size_ private
Referenced by push().
mutex_
std::mutex gdl::MessageQueue::mutex_ {} mutable private
Referenced by pop(), push(), and size().
queue_
std::queue<Message> gdl::MessageQueue::queue_ {} private
Referenced by pop(), push(), and size().