Giraffe: data_middleware::DataFormatter Class Reference
data_middleware::DataFormatter Class Reference
#include <data_formatting.hpp>
Public Member Functions
DataFormatter (cfg::Configuration &config, data::SharedData &shared_data)
~DataFormatter ()=default
std::string dataPacketToJsonString (const data::DataPacket &packet) const
std::string fullErrorFrame ()
std::string fullFrame ()
std::string logPacketToJsonString (const data::LogPacket &packet) const
std::string partialFrame (std::vector< DataFrameComponent > components)
Private Member Functions
void addComponent (DataFrameComponent component, json &frame)
json fullFrameLogPacketToJson (const data::ErrorFrameItem &item) const
std::string generateTimestamp (const bst::clck::TimePoint time_point=bst::clck::now()) const
Generates a timestamp based off of the current configuration.
void setupFrameStructure (json &frame, const std::string &body_field)
Used to set up the frame json structure.
Private Attributes
cfg::Configuration & config_
data::SharedData & shared_data_
Constructor & Destructor Documentation
DataFormatter()
data_middleware::DataFormatter::DataFormatter (cfg::Configuration & config, data::SharedData & shared_data) inline
~DataFormatter()
data_middleware::DataFormatter::~DataFormatter () default
Member Function Documentation
fullFrame()
std::string DataFormatter::fullFrame ()
References addComponent(), data_middleware::CALCULATED_DATA, data_middleware::ENVIRONMENTAL_DATA, data_middleware::MODULES_STATUSES, data_middleware::SERVER_STATS, setupFrameStructure(), data_middleware::STREAM_STATS, data_middleware::SYSTEM_INFO, and data_middleware::TELEMETRY_DATA.
partialFrame()
std::string DataFormatter::partialFrame (std::vector< DataFrameComponent > components)
References addComponent(), and setupFrameStructure().
dataPacketToJsonString()
std::string DataFormatter::dataPacketToJsonString (const data::DataPacket & packet) const
References data::BaseStreamPacket::created_time, node::EXTENSION, generateTimestamp(), data::DataPacket::identifier, node::K_IDENTIFICATION_TO_STRING_MAP, data::BaseStreamPacket::secondary_identifier, data::BaseStreamPacket::source, and data::DataPacket::value.
fullErrorFrame()
std::string DataFormatter::fullErrorFrame ()
References data::Frames::error_frame, data::SharedData::flight_data, data::SharedData::frames, fullFrameLogPacketToJson(), generateTimestamp(), data::ErrorFrame::getFullFrame(), data::FlightData::getUptimeString(), and shared_data_.
logPacketToJsonString()
std::string DataFormatter::logPacketToJsonString (const data::LogPacket & packet) const
References data::BaseStreamPacket::created_time, node::EXTENSION, generateTimestamp(), data::LogPacket::id, data::LogPacket::info, node::K_IDENTIFICATION_TO_STRING_MAP, data::LogPacket::level, data::BaseStreamPacket::secondary_identifier, data::BaseStreamPacket::source, and util::to_string().
setupFrameStructure()
void DataFormatter::setupFrameStructure (json & frame, const std::string & body_field) private
Used to set up the frame json structure.
Parameters
frame - The json object to set up.
body_field - The name of the field that will contain the body.
References data::SharedData::flight_data, generateTimestamp(), data::FlightData::getUptimeString(), and shared_data_.
Referenced by fullFrame(), and partialFrame().
addComponent()
void DataFormatter::addComponent (DataFrameComponent component, json & frame) private
References data::SharedData::blocks, data_middleware::CALCULATED_DATA, data::SharedBlocks::calculated_data, data::Frames::env_hum, data::Frames::env_pres, data::Frames::env_temp, data_middleware::ENVIRONMENTAL_DATA, data::SharedData::frames, data_middleware::MODULES_STATUSES, data::SharedBlocks::modules_statuses, data::SharedBlocks::server_module_stats, data_middleware::SERVER_STATS, shared_data_, data_middleware::STREAM_STATS, data::SharedBlocks::stream_stats, data_middleware::SYSTEM_INFO, data::SharedBlocks::system_info, data_middleware::TELEMETRY_DATA, data::SharedBlocks::telemetry_module_stats, and data::toJson().
Referenced by fullFrame(), and partialFrame().
generateTimestamp()
std::string DataFormatter::generateTimestamp (const bst::clck::TimePoint time_point = bst::clck::now()) const private
Generates a timestamp based off of the current configuration.
Uses either UTC or local time, either generates HH:MM:SS or DD/MM/YYYY_HH:MM:SS. 24 hour time is used.
Parameters
time_point - The time point to generate the timestamp from (defaults to now)
Returns
std::string - The generated timestamp
References config_.
Referenced by dataPacketToJsonString(), fullErrorFrame(), logPacketToJsonString(), and setupFrameStructure().
fullFrameLogPacketToJson()
Json DataFormatter::fullFrameLogPacketToJson (const data::ErrorFrameItem & item) const private
References data::ErrorFrameItem::first_reported, data::LogPacket::id, data::ErrorFrameItem::last_reported, data::ErrorFrameItem::occurrences, and data::ErrorFrameItem::packet.
Referenced by fullErrorFrame().
Member Data Documentation
config_
cfg::Configuration& data_middleware::DataFormatter::config_ private
Referenced by generateTimestamp().
shared_data_
data::SharedData& data_middleware::DataFormatter::shared_data_ private
Referenced by addComponent(), fullErrorFrame(), and setupFrameStructure().