Giraffe: giraffe::gdl::SoftwarePhysicalLayer Class Reference
giraffe::gdl::SoftwarePhysicalLayer Class Reference
#include <software_physical_layer.hpp>
Public Types
enum class Mode { NONE , DATA , APRS , SSTV }
enum class State {
ERROR , DISABLED , STARTING , IDLE ,
TRANSMITTING , RECEIVING , BUSY
}
Public Member Functions
SoftwarePhysicalLayer (const Config &config)
~SoftwarePhysicalLayer () override=default
bool changeMode (Mode mode) override
Attempts to change the mode of the physical layer.
void disable () override
Attempts to disable the physical layer.
void enable () override
Attempts to enable the physical layer.
Mode getMode () const
Get the current mode of the physical layer.
double getRssi () const override
Gets the current RSSI of the physical layer.
PhysicalLayer::State getState () const
Gets the current state of the physical layer.
bool startTransmit () override
Starts transmitting data if possible.
bool stopTransmit () override
Stops transmitting data if currently transmitting.
void update () override
Updates the physical layer.
Protected Member Functions
void setMode (Mode mode)
void setState (State state)
Protected Attributes
const Config & config_
Private Attributes
Mode mode_ = Mode::NONE
State state_ = State::DISABLED
Member Enumeration Documentation
State
enum giraffe::gdl::PhysicalLayer::State strong inherited
Enumerator
ERROR
The physical layer is in an error state. A call to enable() is allowed to attempt to recover from this state.
DISABLED
The physical layer is currently disabled.
STARTING
The physical layer is currently starting up.
IDLE
The physical layer is currently idle and ready to be used.
TRANSMITTING
The physical layer is currently transmitting data.
RECEIVING
The physical layer is currently receiving data.
BUSY
The physical layer is busy and cannot be used. This should be temporary.
Mode
enum giraffe::gdl::PhysicalLayer::Mode strong inherited
Enumerator
NONE
DATA
APRS
SSTV
Constructor & Destructor Documentation
SoftwarePhysicalLayer()
giraffe::gdl::SoftwarePhysicalLayer::SoftwarePhysicalLayer (const Config & config) inline
~SoftwarePhysicalLayer()
giraffe::gdl::SoftwarePhysicalLayer::~SoftwarePhysicalLayer () override default
Member Function Documentation
enable()
void giraffe::gdl::SoftwarePhysicalLayer::enable () inline override virtual
Attempts to enable the physical layer.
Implements giraffe::gdl::PhysicalLayer.
References giraffe::gdl::PhysicalLayer::IDLE, and giraffe::gdl::PhysicalLayer::setState().
disable()
void giraffe::gdl::SoftwarePhysicalLayer::disable () inline override virtual
Attempts to disable the physical layer.
Implements giraffe::gdl::PhysicalLayer.
References giraffe::gdl::PhysicalLayer::DISABLED, and giraffe::gdl::PhysicalLayer::setState().
update()
void giraffe::gdl::SoftwarePhysicalLayer::update () inline override virtual
Updates the physical layer.
Implements giraffe::gdl::PhysicalLayer.
startTransmit()
bool giraffe::gdl::SoftwarePhysicalLayer::startTransmit () inline override virtual
Starts transmitting data if possible.
Returns
true if transmission was started, false otherwise
Todo:
add a timeout parameter
Implements giraffe::gdl::PhysicalLayer.
References giraffe::gdl::PhysicalLayer::setState(), and giraffe::gdl::PhysicalLayer::TRANSMITTING.
stopTransmit()
bool giraffe::gdl::SoftwarePhysicalLayer::stopTransmit () inline override virtual
Stops transmitting data if currently transmitting.
Returns
true if a transmission was in progress and was stopped, false otherwise
Implements giraffe::gdl::PhysicalLayer.
References giraffe::gdl::PhysicalLayer::IDLE, and giraffe::gdl::PhysicalLayer::setState().
getRssi()
double giraffe::gdl::SoftwarePhysicalLayer::getRssi () const inline override virtual
Gets the current RSSI of the physical layer.
Implements giraffe::gdl::PhysicalLayer.
changeMode()
bool giraffe::gdl::SoftwarePhysicalLayer::changeMode (Mode mode) inline override virtual
Attempts to change the mode of the physical layer.
Parameters
mode - The new mode to change to.
Returns
true if the mode was changed, false otherwise
Implements giraffe::gdl::PhysicalLayer.
References giraffe::gdl::PhysicalLayer::setMode().
getState()
PhysicalLayer::State giraffe::gdl::PhysicalLayer::getState () const inline inherited
Gets the current state of the physical layer.
Returns
The current state of the physical layer
References giraffe::gdl::PhysicalLayer::state_.
getMode()
Mode giraffe::gdl::PhysicalLayer::getMode () const inline inherited
Get the current mode of the physical layer.
Returns
The current mode of the physical layer
References giraffe::gdl::PhysicalLayer::mode_.
setState()
void giraffe::gdl::PhysicalLayer::setState (State state) inline protected inherited
References giraffe::gdl::PhysicalLayer::state_.
Referenced by disable(), giraffe::radio::Radio::disable(), enable(), giraffe::radio::Radio::enable(), giraffe::radio::SoftwareRadio::enable(), startTransmit(), giraffe::radio::Radio::startTransmit(), stopTransmit(), and giraffe::radio::Radio::stopTransmit().
setMode()
void giraffe::gdl::PhysicalLayer::setMode (Mode mode) inline protected inherited
References giraffe::gdl::PhysicalLayer::mode_.
Referenced by changeMode(), giraffe::radio::Radio::changeMode(), and giraffe::radio::SoftwareRadio::changeMode().
Member Data Documentation
config_
const Config& giraffe::gdl::PhysicalLayer::config_ protected inherited
state_
State giraffe::gdl::PhysicalLayer::state_ = State::DISABLED private inherited
Referenced by giraffe::gdl::PhysicalLayer::getState(), and giraffe::gdl::PhysicalLayer::setState().
mode_
Mode giraffe::gdl::PhysicalLayer::mode_ = Mode::NONE private inherited
Referenced by giraffe::gdl::PhysicalLayer::getMode(), and giraffe::gdl::PhysicalLayer::setMode().