Giraffe: FlightPhasePredictorTest Class Reference
FlightPhasePredictorTest Class Reference
Classes
struct TestContainer
Protected Types
using Parameter = PredictionParameters::Parameter
Protected Member Functions
virtual void SetUp ()
virtual void TearDown ()
void tick ()
Protected Attributes
FlightPhasePredictor * predictor_ = nullptr
FlightPhasePredictor::Probability prob_ {}
TestContainer * test_ = nullptr
Static Protected Attributes
static constexpr double DETECTED_PHASE_PROBABILITY_THRESHOLD = 50.0
When all parameters are valid and indicate a specific phase, the probability of that phase should be above this value.
static constexpr double OTHER_PHASES_PROBABILITY_THRESHOLD = 20.0
When testing, the probability of the other phases should be the current phase probability minus this value. This is a nice value to shoot for. The higher this value, the better.
static constexpr double PROBABILITY_MAX = 100.0
Class Documentation
FlightPhasePredictorTest::TestContainer
struct FlightPhasePredictorTest::TestContainer
Class Members
SharedData shared_data
FlightPhasePredictor flight_phase_predictor
Block< CalculatedData > & calculated_data
Block< LocationData > & location_data
Block< ImuData > & imu_data
Member Typedef Documentation
Parameter
using FlightPhasePredictorTest::Parameter = PredictionParameters::Parameter protected
Member Function Documentation
SetUp()
virtual void FlightPhasePredictorTest::SetUp () inline protected virtual
References FlightPhasePredictorTest::TestContainer::flight_phase_predictor, FlightPhasePredictor::getPhaseProbability(), predictor_, prob_, and test_.
TearDown()
virtual void FlightPhasePredictorTest::TearDown () inline protected virtual
References test_.
tick()
void FlightPhasePredictorTest::tick () inline protected
References FlightPhasePredictor::getPhaseProbability(), predictor_, prob_, and FlightPhasePredictor::update().
Member Data Documentation
OTHER_PHASES_PROBABILITY_THRESHOLD
constexpr double FlightPhasePredictorTest::OTHER_PHASES_PROBABILITY_THRESHOLD = 20.0 static constexpr protected
When testing, the probability of the other phases should be the current phase probability minus this value. This is a nice value to shoot for. The higher this value, the better.
DETECTED_PHASE_PROBABILITY_THRESHOLD
constexpr double FlightPhasePredictorTest::DETECTED_PHASE_PROBABILITY_THRESHOLD = 50.0 static constexpr protected
When all parameters are valid and indicate a specific phase, the probability of that phase should be above this value.
PROBABILITY_MAX
constexpr double FlightPhasePredictorTest::PROBABILITY_MAX = 100.0 static constexpr protected
test_
TestContainer* FlightPhasePredictorTest::test_ = nullptr protected
Referenced by SetUp(), and TearDown().
predictor_
FlightPhasePredictor* FlightPhasePredictorTest::predictor_ = nullptr protected
Referenced by SetUp(), and tick().
prob_
FlightPhasePredictor::Probability FlightPhasePredictorTest::prob_ {} protected
Referenced by SetUp(), and tick().