Giraffe: giraffe::Logger Class Reference
giraffe::Logger Class Reference
#include <logger.hpp>
Public Member Functions
Logger (data::LogStream &log_stream, node::Identification source, std::string secondary_source="")
void debug (std::string message)
void error (DiagnosticId error_id, std::string info="")
void info (std::string message)
Private Attributes
data::LogStream & log_stream_
std::string secondary_source_
node::Identification source_
Constructor & Destructor Documentation
Logger()
giraffe::Logger::Logger (data::LogStream & log_stream, node::Identification source, std::string secondary_source = "") inline
Member Function Documentation
info()
void giraffe::Logger::info (std::string message) inline
References data::LogStream::info(), log_stream_, secondary_source_, and source_.
Referenced by error().
debug()
void giraffe::Logger::debug (std::string message) inline
References data::LogStream::debug(), log_stream_, secondary_source_, and source_.
Referenced by data_middleware::CalculatedData::calculateDistanceData(), and RequestRouter::handleMessage().
error()
void giraffe::Logger::error (DiagnosticId error_id, std::string info = "") inline
References data::LogStream::error(), info(), log_stream_, secondary_source_, and source_.
Referenced by data_middleware::AdcInterpolation::getAdcConfig().
Member Data Documentation
log_stream_
data::LogStream& giraffe::Logger::log_stream_ private
Referenced by debug(), error(), and info().
source_
node::Identification giraffe::Logger::source_ private
Referenced by debug(), error(), and info().
secondary_source_
std::string giraffe::Logger::secondary_source_ private
Referenced by debug(), error(), and info().