Giraffe: gdl::TransportLayer Class Reference
gdl::TransportLayer Class Reference
#include <gdl_transport_layer.hpp>
Public Types
enum class State { IDLE , SENDING , WAITING_FOR_ACK }
Public Member Functions
TransportLayer (NetworkLayer &network_layer, GdlConfig config)
~TransportLayer ()=default
bool isReady ()
bool receive (Message &message)
bool send (Message &message)
void update (MessageQueue &received_messages)
void updateStatus (gdl::GdlStatus &status)
Private Member Functions
bool isTimerExpired ()
bool receivedAck ()
void sendAck (std::string id)
bool sendPacket ()
void startTimer ()
Private Attributes
GdlConfig config_
Message current_message_ {}
std::string last_acked_id_ {}
NetworkLayer & network_layer_
State state_ = State::IDLE
bst::Timer timer_
Member Enumeration Documentation
State
enum gdl::TransportLayer::State strong
Enumerator
IDLE
SENDING
WAITING_FOR_ACK
Constructor & Destructor Documentation
TransportLayer()
gdl::TransportLayer::TransportLayer (NetworkLayer & network_layer, GdlConfig config) inline
~TransportLayer()
gdl::TransportLayer::~TransportLayer () default
Member Function Documentation
isReady()
bool gdl::TransportLayer::isReady () inline
References IDLE, and state_.
Referenced by gdl::GiraffeDataLink::gdlThread().
send()
bool gdl::TransportLayer::send (Message & message) inline
References current_message_, IDLE, SENDING, and state_.
Referenced by gdl::GiraffeDataLink::gdlThread().
receive()
bool gdl::TransportLayer::receive (Message & message) inline
References network_layer_, and gdl::NetworkLayer::rxMessage().
update()
void gdl::TransportLayer::update (MessageQueue & received_messages) inline
References config_, current_message_, IDLE, isTimerExpired(), last_acked_id_, gdl::GdlConfig::max_retries, network_layer_, gdl::MessageQueue::push(), receivedAck(), gdl::Message::retries, gdl::NetworkLayer::rxMessage(), sendAck(), SENDING, sendPacket(), startTimer(), state_, gdl::NetworkLayer::update(), and WAITING_FOR_ACK.
Referenced by gdl::GiraffeDataLink::gdlThread().
updateStatus()
void gdl::TransportLayer::updateStatus (gdl::GdlStatus & status) inline
References network_layer_, and gdl::NetworkLayer::updateStatus().
Referenced by gdl::GiraffeDataLink::gdlThread().
sendPacket()
bool gdl::TransportLayer::sendPacket () inline private
References current_message_, network_layer_, and gdl::NetworkLayer::txMessage().
Referenced by update().
sendAck()
void gdl::TransportLayer::sendAck (std::string id) inline private
References gdl::Message::data, gdl::Message::EXCHANGE, network_layer_, and gdl::NetworkLayer::txMessage().
Referenced by update().
startTimer()
void gdl::TransportLayer::startTimer () inline private
References timer_.
Referenced by update().
isTimerExpired()
bool gdl::TransportLayer::isTimerExpired () inline private
References timer_.
Referenced by update().
receivedAck()
bool gdl::TransportLayer::receivedAck () inline private
References network_layer_, and gdl::NetworkLayer::rxMessage().
Referenced by update().
Member Data Documentation
network_layer_
NetworkLayer& gdl::TransportLayer::network_layer_ private
Referenced by receive(), receivedAck(), sendAck(), sendPacket(), update(), and updateStatus().
config_
GdlConfig gdl::TransportLayer::config_ private
Referenced by update().
timer_
bst::Timer gdl::TransportLayer::timer_ private
Referenced by isTimerExpired(), and startTimer().
current_message_
Message gdl::TransportLayer::current_message_ {} private
Referenced by send(), sendPacket(), and update().
state_
State gdl::TransportLayer::state_ = State::IDLE private
Referenced by isReady(), send(), and update().
last_acked_id_
std::string gdl::TransportLayer::last_acked_id_ {} private
Referenced by update().