Giraffe: console_pages::Pages Class Reference
console_pages::Pages Class Reference
#include <console_pages.hpp>
Public Member Functions
Pages (cfg::Configuration &config, data::SharedData &shared_data)
~Pages ()=default
Menu getCurrentMenu ()
const std::array< std::string, K_MAX_NUM_PAGE_LINES > & getCurrentPage ()
int getMaxNumPageLines () const
int getNumLinesOnPage () const
void navigateMenu (PageOption key)
Private Member Functions
void data ()
void extensionData ()
void extensions ()
void gfsStatus ()
void location ()
void log ()
void server ()
void setNumLinesOnPage (const int num_lines)
void system ()
Private Attributes
cfg::Configuration & config_
std::array< std::string, K_MAX_NUM_PAGE_LINES > content_ = {}
Menu current_menu_
int current_num_lines_ = 0
PageOption current_page_ = K_INITIAL_PAGE
data::SharedData & shared_data_
Constructor & Destructor Documentation
Pages()
console_pages::Pages::Pages (cfg::Configuration & config, data::SharedData & shared_data) inline
~Pages()
console_pages::Pages::~Pages () default
Member Function Documentation
getCurrentPage()
const std::array< std::string, console_pages::K_MAX_NUM_PAGE_LINES > & console_pages::Pages::getCurrentPage ()
References content_, current_page_, console_pages::DATA, data(), console_pages::EXTENSION_DATA, extensionData(), console_pages::EXTENSIONS, extensions(), console_pages::GFS_STATUS, gfsStatus(), console_pages::LOCATION, location(), console_pages::LOG, log(), console_pages::SERVER, server(), console_pages::SYSTEM, and system().
getNumLinesOnPage()
int console_pages::Pages::getNumLinesOnPage () const inline
References current_num_lines_.
getCurrentMenu()
console_pages::Menu console_pages::Pages::getCurrentMenu ()
navigateMenu()
void console_pages::Pages::navigateMenu (const console_pages::PageOption key)
getMaxNumPageLines()
int console_pages::Pages::getMaxNumPageLines () const inline
References console_pages::K_MAX_NUM_PAGE_LINES.
gfsStatus()
void console_pages::Pages::gfsStatus () private
References data::blocks::ModulesStatuses::console, data::blocks::SystemInfo::cpu_load_avg_1, data::blocks::SystemInfo::cpu_load_avg_15, data::blocks::SystemInfo::cpu_load_avg_5, data::blocks::ModulesStatuses::data, data::blocks::ModulesStatuses::extension, f2s(), console_pages::K_DATA_WINDOW_WIDTH, node::K_STATUS_TO_STRING_MAP, LandR(), data::blocks::ModulesStatuses::server, data::blocks::ModulesStatuses::system, and util::to_string().
Referenced by getCurrentPage().
data()
void console_pages::Pages::data () private
References b2str(), data::blocks::StreamsStats::data, data::blocks::DataLogStats::data_archive_dir, data::blocks::DataLogStats::data_archive_dir_size, data::blocks::DataLogStats::data_dir, data::blocks::DataLogStats::data_file, data::blocks::DataLogStats::data_file_path, data::blocks::DataLogStats::data_file_size, data::blocks::StreamsStats::gps, data::blocks::StreamsStats::imu, LandR(), data::blocks::StreamsStats::log, data::blocks::DataLogStats::log_archive_dir, data::blocks::DataLogStats::log_archive_dir_size, data::blocks::DataLogStats::log_dir, data::blocks::DataLogStats::log_file, data::blocks::DataLogStats::log_file_path, data::blocks::DataLogStats::log_file_size, and util::to_string().
Referenced by getCurrentPage().
log()
void console_pages::Pages::log () private
Referenced by getCurrentPage().
server()
void console_pages::Pages::server () private
References b2str(), f2s(), and util::to_string().
Referenced by getCurrentPage().
extensions()
void console_pages::Pages::extensions () private
References util::to_string().
Referenced by getCurrentPage().
system()
void console_pages::Pages::system () private
References f2s().
Referenced by getCurrentPage().
location()
void console_pages::Pages::location () private
References f2s(), data::K_GPS_FIX_TO_STRING_MAP, and util::to_string().
Referenced by getCurrentPage().
extensionData()
void console_pages::Pages::extensionData () private
References util::to_string().
Referenced by getCurrentPage().
setNumLinesOnPage()
void console_pages::Pages::setNumLinesOnPage (const int num_lines) private
References console_pages::K_MAX_NUM_PAGE_LINES.
Member Data Documentation
config_
cfg::Configuration& console_pages::Pages::config_ private
shared_data_
data::SharedData& console_pages::Pages::shared_data_ private
current_page_
PageOption console_pages::Pages::current_page_ = K_INITIAL_PAGE private
Referenced by getCurrentPage().
current_num_lines_
int console_pages::Pages::current_num_lines_ = 0 private
Referenced by getNumLinesOnPage().
content_
std::array<std::string, K_MAX_NUM_PAGE_LINES> console_pages::Pages::content_ = {} private
Referenced by getCurrentPage().
current_menu_
Menu console_pages::Pages::current_menu_ private
Initial value:
= {
      {"GFS Status", PageOption::GFS_STATUS},
      {"Data", PageOption::DATA},
      {"Log", PageOption::LOG},
      {"Server", PageOption::SERVER},
      {"Extensions", PageOption::EXTENSIONS},
      {"Extension Data", PageOption::EXTENSION_DATA},
      {"System", PageOption::SYSTEM},
      {"Location", PageOption::LOCATION},
  }