Giraffe: cfg::AdcMappings Class Reference
cfg::AdcMappings Class Reference
#include <cfg_adcmappings.hpp>
Public Member Functions
AdcMappings (data::Streams &streams)
bool addAdcConfig (const AdcConfig &adc_config)
std::vector< AdcConfig > getAdcConfigs () const
Json getJson () const
bool removeAdcConfig (const std::string &label)
void setFromJson (const Json &json_data)
bool updateAdcConfig (const std::string &label, const AdcConfig &adc_config)
Protected Member Functions
void error (DiagnosticId diagnostic_id, const std::string &info="")
Logs a debug message.
Protected Attributes
std::mutex cfg_lock_ = std::mutex()
data::Streams & streams_
Private Member Functions
bool doesLabelExist (const std::string &label) const
Private Attributes
std::vector< AdcConfig > adc_configs_ {}
Constructor & Destructor Documentation
AdcMappings()
cfg::AdcMappings::AdcMappings (data::Streams & streams) inline
Member Function Documentation
setFromJson()
void cfg::AdcMappings::setFromJson (const Json & json_data)
References adc_configs_, cfg::CfgSection::cfg_lock_, doesLabelExist(), cfg::CfgSection::error(), cfg::AdcConfig::fromJson(), cfg::AdcConfig::label, data::Streams::log, cfg::CfgSection::streams_, and util::to_string().
getJson()
Json cfg::AdcMappings::getJson () const
References adc_configs_, and cfg::CfgSection::cfg_lock_.
addAdcConfig()
bool cfg::AdcMappings::addAdcConfig (const AdcConfig & adc_config)
References adc_configs_, cfg::CfgSection::cfg_lock_, doesLabelExist(), cfg::CfgSection::error(), and cfg::AdcConfig::label.
removeAdcConfig()
bool cfg::AdcMappings::removeAdcConfig (const std::string & label)
References adc_configs_, cfg::CfgSection::cfg_lock_, and cfg::CfgSection::error().
updateAdcConfig()
bool cfg::AdcMappings::updateAdcConfig (const std::string & label, const AdcConfig & adc_config)
References adc_configs_, cfg::CfgSection::cfg_lock_, and cfg::CfgSection::error().
getAdcConfigs()
std::vector< AdcConfig > cfg::AdcMappings::getAdcConfigs () const
References adc_configs_, and cfg::CfgSection::cfg_lock_.
doesLabelExist()
bool cfg::AdcMappings::doesLabelExist (const std::string & label) const private
References adc_configs_.
Referenced by addAdcConfig(), and setFromJson().
error()
void cfg::CfgSection::error (DiagnosticId diagnostic_id, const std::string & info = "") inline protected inherited
Logs a debug message.
Note
This currently isn't used as the rest is autogenerated, but it really should be.
Parameters
diagnostic_id The id of the log.
info The information to log.
References node::CONFIGURATION, data::LogStream::error(), data::Streams::log, and cfg::CfgSection::streams_.
Referenced by addAdcConfig(), cfg::Extensions::addExtension(), removeAdcConfig(), cfg::Extensions::removeExtension(), setFromJson(), cfg::Extensions::setFromJson(), cfg::Extensions::toggleExtension(), updateAdcConfig(), and cfg::Extensions::updateExtension().
Member Data Documentation
adc_configs_
std::vector<AdcConfig> cfg::AdcMappings::adc_configs_ {} private
Referenced by addAdcConfig(), doesLabelExist(), getAdcConfigs(), getJson(), removeAdcConfig(), setFromJson(), and updateAdcConfig().
cfg_lock_
std::mutex cfg::CfgSection::cfg_lock_ = std::mutex() mutable protected inherited
Referenced by addAdcConfig(), cfg::Extensions::addExtension(), getAdcConfigs(), cfg::Extensions::getExtensions(), getJson(), cfg::Extensions::getJson(), removeAdcConfig(), cfg::Extensions::removeExtension(), setFromJson(), cfg::Extensions::setFromJson(), cfg::Extensions::toggleExtension(), updateAdcConfig(), and cfg::Extensions::updateExtension().
streams_
data::Streams& cfg::CfgSection::streams_ protected inherited
Referenced by cfg::CfgSection::error(), setFromJson(), and cfg::Extensions::setFromJson().