Giraffe: bit::BuiltInTest Class Reference
bit::BuiltInTest Class Reference
#include <built_in_test.hpp>
Public Member Functions
BuiltInTest (data::SharedData &shared_data)
~BuiltInTest ()
void getBitTestData (Json &out_data) override
void reset ()
Reset the BIT system to it's initial state.
void start ()
void stop ()
Private Member Functions
void bitTestRunner ()
void updateBitTestData ()
Private Attributes
TestGroup adc_test_group_
Test cases for the ADC group.
TestGroup batt_test_group_
Test cases for the BATT group.
TestGroup cam_test_group_
Test cases for the CAM group.
TestGroup dlnk_test_group_
Test cases for the DLNK group.
TestGroup env_test_group_
Test cases for the ENV group.
TestGroup extn_test_group_
Test cases for the EXTN group.
TestGroup fcs_test_group_
Test cases for the FCS group.
bit::TestStatus general_bit_status_ {bit::TestStatus::NOTRUN}
TestGroup gps_test_group_
Test cases for the GPS group.
TestGroup imu_test_group_
Test cases for the IMU group.
giraffe::Logger logger_
std::atomic< bool > running_ {false}
data::SharedData & shared_data_
TestGroup sys_test_group_
Test cases for the SYS group.
Json test_data_buffer_ {}
std::mutex test_data_mutex_ {}
std::map< TestGroupId, TestGroup & > test_groups_map_
This map contains the collection of test groups.
std::thread thread_ {}
Constructor & Destructor Documentation
BuiltInTest()
bit::BuiltInTest::BuiltInTest (data::SharedData & shared_data) inline
References updateBitTestData().
~BuiltInTest()
bit::BuiltInTest::~BuiltInTest () inline
References running_, stop(), test_groups_map_, and thread_.
Member Function Documentation
start()
void bit::BuiltInTest::start () inline
References bitTestRunner(), giraffe::Logger::error(), logger_, running_, and thread_.
Referenced by FlightRunner::processCommand().
stop()
void bit::BuiltInTest::stop () inline
References giraffe::Logger::error(), logger_, running_, and thread_.
Referenced by ~BuiltInTest(), and FlightRunner::processCommand().
reset()
void bit::BuiltInTest::reset () inline
Reset the BIT system to it's initial state.
Warning
Risk of race conditions here. It's just BIT, so low risk.
References giraffe::Logger::error(), general_bit_status_, logger_, running_, test_groups_map_, thread_, and updateBitTestData().
Referenced by FlightRunner::processCommand().
getBitTestData()
void bit::BuiltInTest::getBitTestData (Json & out_data) inline override virtual
Implements bit::IBuiltInTest.
References test_data_buffer_, test_data_mutex_, and updateBitTestData().
updateBitTestData()
void bit::BuiltInTest::updateBitTestData () inline private
References data::SharedData::flight_data, general_bit_status_, data::FlightData::getFlightPhase(), PRE_LAUNCH, running_, data::FlightData::setBitTestData(), shared_data_, test_data_buffer_, test_data_mutex_, and test_groups_map_.
Referenced by BuiltInTest(), bitTestRunner(), getBitTestData(), and reset().
bitTestRunner()
void bit::BuiltInTest::bitTestRunner () inline private
References general_bit_status_, running_, test_groups_map_, and updateBitTestData().
Referenced by start().
Member Data Documentation
test_data_mutex_
std::mutex bit::BuiltInTest::test_data_mutex_ {} private
Referenced by getBitTestData(), and updateBitTestData().
test_data_buffer_
Json bit::BuiltInTest::test_data_buffer_ {} private
Referenced by getBitTestData(), and updateBitTestData().
shared_data_
data::SharedData& bit::BuiltInTest::shared_data_ private
Referenced by updateBitTestData().
logger_
giraffe::Logger bit::BuiltInTest::logger_ private
Referenced by reset(), start(), and stop().
general_bit_status_
bit::TestStatus bit::BuiltInTest::general_bit_status_ {bit::TestStatus::NOTRUN} private
Referenced by bitTestRunner(), reset(), and updateBitTestData().
thread_
std::thread bit::BuiltInTest::thread_ {} private
Referenced by ~BuiltInTest(), reset(), start(), and stop().
running_
std::atomic<bool> bit::BuiltInTest::running_ {false} private
Referenced by ~BuiltInTest(), bitTestRunner(), reset(), start(), stop(), and updateBitTestData().
fcs_test_group_
TestGroup bit::BuiltInTest::fcs_test_group_ private
Initial value:
{
    TestGroupId::FCS, shared_data_,
    {{TestGroupId::FCS, TestId::FCS_ErrorTest, shared_data_},
    {TestGroupId::FCS, TestId::FCS_FlightPhasePredictorTest, shared_data_},
    {TestGroupId::FCS, TestId::FCS_LaunchPositionTest, shared_data_},
    {TestGroupId::FCS, TestId::FCS_DataModuleProcessingTest, shared_data_},
    },
  }
Test cases for the FCS group.
sys_test_group_
TestGroup bit::BuiltInTest::sys_test_group_ private
Initial value:
{
    TestGroupId::SYS, shared_data_,
    {{TestGroupId::SYS, TestId::SYS_ErrorTest, shared_data_},
    },
  }
Test cases for the SYS group.
dlnk_test_group_
TestGroup bit::BuiltInTest::dlnk_test_group_ private
Initial value:
{
    TestGroupId::DLNK, shared_data_,
    {{TestGroupId::DLNK, TestId::DLNK_ConfigLocationDataTest, shared_data_},
    },
  }
Test cases for the DLNK group.
gps_test_group_
TestGroup bit::BuiltInTest::gps_test_group_ private
Initial value:
{
    TestGroupId::GPS, shared_data_,
    {{TestGroupId::GPS, TestId::GPS_InstalledTest, shared_data_},
    },
  }
Test cases for the GPS group.
batt_test_group_
TestGroup bit::BuiltInTest::batt_test_group_ private
Initial value:
{
    TestGroupId::BATT, shared_data_,
    {{TestGroupId::BATT, TestId::BATT_AdcTest, shared_data_},
    },
  }
Test cases for the BATT group.
extn_test_group_
TestGroup bit::BuiltInTest::extn_test_group_ private
Initial value:
{
    TestGroupId::EXTN, shared_data_,
    {{TestGroupId::EXTN, TestId::EXTN_ExtensionsRunningTest, shared_data_},
    },
  }
Test cases for the EXTN group.
env_test_group_
TestGroup bit::BuiltInTest::env_test_group_ private
Initial value:
{
    TestGroupId::ENV, shared_data_,
    {{TestGroupId::ENV, TestId::ENV_TemperatureTest, shared_data_},
    },
  }
Test cases for the ENV group.
cam_test_group_
TestGroup bit::BuiltInTest::cam_test_group_ private
Initial value:
{
    TestGroupId::CAM, shared_data_,
    {{TestGroupId::CAM, TestId::CAM_InstalledTest, shared_data_},
    },
  }
Test cases for the CAM group.
imu_test_group_
TestGroup bit::BuiltInTest::imu_test_group_ private
Initial value:
{
    TestGroupId::IMU, shared_data_,
    {{TestGroupId::IMU, TestId::IMU_InstalledTest, shared_data_},
    },
  }
Test cases for the IMU group.
adc_test_group_
TestGroup bit::BuiltInTest::adc_test_group_ private
Initial value:
{
    TestGroupId::ADC, shared_data_,
    {{TestGroupId::ADC, TestId::ADC_InstalledTest, shared_data_},
    },
  }
Test cases for the ADC group.
test_groups_map_
std::map<TestGroupId, TestGroup &> bit::BuiltInTest::test_groups_map_ private
Initial value:
{
    {TestGroupId::FCS, fcs_test_group_},
    {TestGroupId::SYS, sys_test_group_},
    {TestGroupId::DLNK, dlnk_test_group_},
    {TestGroupId::GPS, gps_test_group_},
    {TestGroupId::BATT, batt_test_group_},
    {TestGroupId::EXTN, extn_test_group_},
    {TestGroupId::ENV, env_test_group_},
    {TestGroupId::CAM, cam_test_group_},
    {TestGroupId::IMU, imu_test_group_},
    {TestGroupId::ADC, adc_test_group_},
  }
This map contains the collection of test groups.
Referenced by ~BuiltInTest(), bitTestRunner(), reset(), and updateBitTestData().