Giraffe: bit::TestGroup Class Reference
bit::TestGroup Class Reference
#include <built_in_test.hpp>
Public Member Functions
TestGroup (bit::TestGroupId group_id, data::SharedData &shared_data, std::vector< TestCase > test_cases)
~TestGroup ()=default
Json getGroupResults ()
TestStatus getGroupStatus () const
void reset ()
void start ()
void stop ()
Private Member Functions
void groupRunner ()
void setGroupStatus (TestStatus status)
Private Attributes
bit::TestGroupId group_id_
std::atomic< TestStatus > group_status_ {TestStatus::NOTRUN}
giraffe::Logger logger_
std::atomic< bool > running_ {false}
data::SharedData & shared_data_
std::vector< TestCase > test_cases_
std::mutex test_results_mutex_ {}
std::thread thread_ {}
Constructor & Destructor Documentation
TestGroup()
bit::TestGroup::TestGroup (bit::TestGroupId group_id, data::SharedData & shared_data, std::vector< TestCase > test_cases) inline
~TestGroup()
bit::TestGroup::~TestGroup () default
Member Function Documentation
start()
void bit::TestGroup::start () inline
References giraffe::Logger::error(), groupRunner(), logger_, running_, setGroupStatus(), and thread_.
stop()
void bit::TestGroup::stop () inline
References running_, setGroupStatus(), and thread_.
Referenced by reset().
reset()
void bit::TestGroup::reset () inline
References setGroupStatus(), stop(), and test_cases_.
getGroupStatus()
TestStatus bit::TestGroup::getGroupStatus () const inline
References group_status_.
getGroupResults()
Json bit::TestGroup::getGroupResults () inline
References group_status_, test_cases_, and test_results_mutex_.
groupRunner()
void bit::TestGroup::groupRunner () inline private
References running_, setGroupStatus(), and test_cases_.
Referenced by start().
setGroupStatus()
void bit::TestGroup::setGroupStatus (TestStatus status) inline private
References group_status_.
Referenced by groupRunner(), reset(), start(), and stop().
Member Data Documentation
group_id_
bit::TestGroupId bit::TestGroup::group_id_ private
shared_data_
data::SharedData& bit::TestGroup::shared_data_ private
logger_
giraffe::Logger bit::TestGroup::logger_ private
Referenced by start().
test_cases_
std::vector<TestCase> bit::TestGroup::test_cases_ private
Referenced by getGroupResults(), groupRunner(), and reset().
thread_
std::thread bit::TestGroup::thread_ {} private
Referenced by start(), and stop().
running_
std::atomic<bool> bit::TestGroup::running_ {false} private
Referenced by groupRunner(), start(), and stop().
group_status_
std::atomic<TestStatus> bit::TestGroup::group_status_ {TestStatus::NOTRUN} private
Referenced by getGroupResults(), getGroupStatus(), and setGroupStatus().
test_results_mutex_
std::mutex bit::TestGroup::test_results_mutex_ {} private
Referenced by getGroupResults().