Giraffe: data_middleware::DataLog Class Reference
data_middleware::DataLog Class Reference
Used to write data and log information to files. Used by the data module.
#include <data_log.hpp>
Public Member Functions
DataLog (data::SharedData &shared_data, cfg::Configuration &config)
~DataLog ()=default
void logDataFrame (cfg::gEnum::LogStrategy strategy)
Used for periodic logging of all data.
void logDataPacket (const data::DataPacket &packet)
Used to add a single data packet to the file log.
void logErrorFrame ()
void logLogPacket (const data::LogPacket &packet)
Used to log a single log packet to the file log.
Private Member Functions
void appendToDataFile (const std::string &content)
Used to append data to the data file.
void appendToFile (const std::string &path, const std::string &data, const DiagnosticId error_id)
Attempts to append data to a file. Only checks the file validity.
void appendToLogFile (const std::string &content)
Used to append data to the log file.
bool archiveFile (const std::string &file_path, const std::string &archive_dir_path, const DiagnosticId error_id)
Moves a file to the archive directory according to the archive method.
void archiveOtherFilesInDir (const std::string &dir_path, const std::string &archive_dir_path, DiagnosticId error_id)
Called only startup. If there are any files in the data or log directories that have been left behind, they will be archived. Not recursive.
void createDataArchiveDir ()
Used to create the data archive directory with createDirectory().
void createDataDir ()
Used to create the data directory with createDirectory().
void createDirectory (const std::string &path, const DiagnosticId booster_seat_log_id, const DiagnosticId std_except_log_id, bool &validity_flag)
Attempt to create a directory, log any errors, and set the validity flag in fs_status_.
void createFile (const std::string &new_file_path, const DiagnosticId booster_seat_log_id, const DiagnosticId std_except_log_id, bool &validity_flag)
Attempt to create a file, log any errors, and set the validity flag in fs_status_.
void createLogArchiveDir ()
Used to create the log archive directory with createDirectory().
void createLogDir ()
Used to create the log directory with createDirectory().
void createNewDataFile ()
Generates a new file path and attempts to create a new data file.
void createNewLogFile ()
Generates a new file path and attempts to create a new log file.
void rotateFiles ()
This method checks the size of the data and log files and archives them if they have exceeded the maximum size.
void trimArchive ()
This method will use the configured archive settings to trim the oldest files in the archive directory if the archive size limit is exceeded.
void updateDirSize (const std::string &dir_path, const DiagnosticId error_id, data::blocks::DataLogStats::FileSizeType &dir_size)
Attempts to read the size of a directory.
void updateFileList ()
This method will update the file list in the relevant data block.
void updateFileSize (const std::string &file_path, const DiagnosticId error_id, data::blocks::DataLogStats::FileSizeType &file_size)
Attempts to read the size of a file.
void updateFileSystem ()
Handles the file system management.
void validateDirExists (const std::string &path, const DiagnosticId does_not_exist_log_id, const DiagnosticId booster_seat_log_id, const DiagnosticId std_except_log_id, bool &validity_flag)
Validates the existence of a directory.
void validateFileExists (const std::string &path, const DiagnosticId does_not_exist_log_id, const DiagnosticId booster_seat_log_id, const DiagnosticId std_except_log_id, bool &validity_flag)
Validates the existence of a file.
void validateFileSystem ()
Checks for the existence of the data log directories and files.
Private Attributes
cfg::Configuration & config_
The configuration.
BoosterSeat::Stopwatch data_frame_stopwatch_ = BoosterSeat::Stopwatch()
Used to time how often the full data frame is logged if the appropriate log strategy is selected.
BoosterSeat::Stopwatch error_frame_stopwatch_ = BoosterSeat::Stopwatch()
Used to time how often the error data frame is logged if the appropriate error log strategy is selected.
DataFormatter formatter_
Used to format the data before it is written to the files. (turns things into json strings.)
data::blocks::DataLogStats fs_status_ = {}
The file system status data block. Used to keep track of the file system locally to reduce the number of times the data block is set.
data::SharedData & shared_data_
The shared data.
BoosterSeat::Stopwatch validation_stopwatch_ = BoosterSeat::Stopwatch()
Used within 'updateFileSystem'. Keeps track of the last time the file system was checked.
Detailed Description
Used to write data and log information to files. Used by the data module.
Constructor & Destructor Documentation
DataLog()
data_middleware::DataLog::DataLog (data::SharedData & shared_data, cfg::Configuration & config)
References archiveOtherFilesInDir(), data::SharedData::blocks, createDataArchiveDir(), createDataDir(), createLogArchiveDir(), createLogDir(), createNewDataFile(), createNewLogFile(), data::blocks::DataLogStats::data_dir, data_frame_stopwatch_, data::SharedBlocks::data_log_stats, error_frame_stopwatch_, fs_status_, kDataArchiveDirPath, kDataDirPath, kLogArchiveDirPath, kLogDirPath, data::blocks::DataLogStats::log_dir, shared_data_, updateFileList(), and validation_stopwatch_.
~DataLog()
data_middleware::DataLog::~DataLog () default
Member Function Documentation
logDataPacket()
void data_middleware::DataLog::logDataPacket (const data::DataPacket & packet)
Used to add a single data packet to the file log.
Parameters
packet
See also
data::DataPacket
References data::DataPacket::STATUS, and data::DataPacket::type.
logDataFrame()
void data_middleware::DataLog::logDataFrame (cfg::gEnum::LogStrategy strategy)
Used for periodic logging of all data.
The strategy was recently read from the configuration prior to this method being called (from the data module). No need to read it again.
Parameters
strategy - The strategy to use for logging.
Todo:
Implement this. Requires configuration list loading.
References kNodeId.
logErrorFrame()
void data_middleware::DataLog::logErrorFrame ()
logLogPacket()
void data_middleware::DataLog::logLogPacket (const data::LogPacket & packet)
Used to log a single log packet to the file log.
Parameters
packet
See also
data::LogPacket
References data::LogPacket::level.
appendToDataFile()
void data_middleware::DataLog::appendToDataFile (const std::string & content) private
Used to append data to the data file.
Parameters
content - The content to append.
appendToLogFile()
void data_middleware::DataLog::appendToLogFile (const std::string & content) private
Used to append data to the log file.
Parameters
content - The content to append.
updateFileSystem()
void data_middleware::DataLog::updateFileSystem () private
Handles the file system management.
Checks the following:
Creates a new log file if necessary.
If it's the first start.
If the current log file is too large.
Checks the log file(s) for validity and size.
Checks the archive directories for size. It then updates the data block with relevant information.
See also
kMaxDirCreationAttempts
Todo:
Error Log
validateFileSystem()
void data_middleware::DataLog::validateFileSystem () private
Checks for the existence of the data log directories and files.
Checks if the directories exist.
If they do not it will attempt to create them a set number of times.
References kDataArchiveDirPath, kDataDirPath, kLogArchiveDirPath, and kLogDirPath.
Member Data Documentation
shared_data_
data::SharedData& data_middleware::DataLog::shared_data_ private
The shared data.
Referenced by DataLog().
config_
cfg::Configuration& data_middleware::DataLog::config_ private
The configuration.
fs_status_
data::blocks::DataLogStats data_middleware::DataLog::fs_status_ = {} private
The file system status data block. Used to keep track of the file system locally to reduce the number of times the data block is set.
Referenced by DataLog().
validation_stopwatch_
BoosterSeat::Stopwatch data_middleware::DataLog::validation_stopwatch_ = BoosterSeat::Stopwatch() private
Used within 'updateFileSystem'. Keeps track of the last time the file system was checked.
Referenced by DataLog().
data_frame_stopwatch_
BoosterSeat::Stopwatch data_middleware::DataLog::data_frame_stopwatch_ = BoosterSeat::Stopwatch() private
Used to time how often the full data frame is logged if the appropriate log strategy is selected.
Referenced by DataLog().
error_frame_stopwatch_
BoosterSeat::Stopwatch data_middleware::DataLog::error_frame_stopwatch_ = BoosterSeat::Stopwatch() private
Used to time how often the error data frame is logged if the appropriate error log strategy is selected.
Referenced by DataLog().
formatter_
DataFormatter data_middleware::DataLog::formatter_ private
Used to format the data before it is written to the files. (turns things into json strings.)