Giraffe: giraffe::StatusLedChannel Class Reference
giraffe::StatusLedChannel Class Reference
#include <status_led.hpp>
Public Types
enum class Channel { RED , GREEN , BLUE }
Public Member Functions
StatusLedChannel (StatusLedState &status_led_state, Channel channel)
void blink ()
StatusLedState::State getState () const
void off ()
void on ()
Private Member Functions
void set ()
Private Attributes
Channel channel_
StatusLedState::State state_ = StatusLedState::State::OFF
StatusLedState & status_led_state_
Member Enumeration Documentation
Channel
enum giraffe::StatusLedChannel::Channel strong
Enumerator
RED
GREEN
BLUE
Constructor & Destructor Documentation
StatusLedChannel()
giraffe::StatusLedChannel::StatusLedChannel (StatusLedState & status_led_state, Channel channel) inline
Member Function Documentation
blink()
void giraffe::StatusLedChannel::blink () inline
References giraffe::StatusLedState::BLINK, set(), and state_.
on()
void giraffe::StatusLedChannel::on () inline
References giraffe::StatusLedState::ON, set(), and state_.
off()
void giraffe::StatusLedChannel::off () inline
References giraffe::StatusLedState::OFF, set(), and state_.
getState()
StatusLedState::State giraffe::StatusLedChannel::getState () const inline
References state_.
set()
void giraffe::StatusLedChannel::set () inline private
References BLUE, channel_, GREEN, RED, giraffe::StatusLedState::setBlue(), giraffe::StatusLedState::setGreen(), giraffe::StatusLedState::setRed(), state_, and status_led_state_.
Referenced by blink(), off(), and on().
Member Data Documentation
status_led_state_
StatusLedState& giraffe::StatusLedChannel::status_led_state_ private
Referenced by set().
channel_
Channel giraffe::StatusLedChannel::channel_ private
Referenced by set().
state_
StatusLedState::State giraffe::StatusLedChannel::state_ = StatusLedState::State::OFF private
Referenced by blink(), getState(), off(), on(), and set().