Giraffe: giraffe::radio::SoftwareRadio Class Reference
giraffe::radio::SoftwareRadio Class Reference
#include <software_radio.hpp>
Public Types
enum class Mode { NONE , DATA , APRS , SSTV }
using State = giraffe::gdl::PhysicalLayer::State
Public Member Functions
SoftwareRadio (giraffe::gdl::Config &config)
~SoftwareRadio () override=default
bool changeMode (Mode mode) override
Attempts to change the mode of the physical layer.
void disable () override
Attempts to disable the physical layer.
void enable () override
Attempts to enable the physical layer.
Mode getMode () const
Get the current mode of the physical layer.
double getRssi () const override
Gets the current RSSI of the physical layer.
PhysicalLayer::State getState () const
Gets the current state of the physical layer.
bool startTransmit () override
Starts transmitting data if possible.
bool stopTransmit () override
Stops transmitting data if currently transmitting.
void update () override
Updates the physical layer.
Protected Member Functions
void setMode (Mode mode)
void setState (State state)
Protected Attributes
const Config & config_
Private Attributes
Mode mode_ = Mode::NONE
State state_ = State::DISABLED
Member Typedef Documentation
State
using giraffe::radio::Radio::State = giraffe::gdl::PhysicalLayer::State inherited
Member Enumeration Documentation
Mode
enum class giraffe::gdl::PhysicalLayer::Mode strong inherited
Enumerator
NONE
DATA
APRS
SSTV
Constructor & Destructor Documentation
SoftwareRadio()
giraffe::radio::SoftwareRadio::SoftwareRadio (giraffe::gdl::Config & config) inline
~SoftwareRadio()
giraffe::radio::SoftwareRadio::~SoftwareRadio () override default
Member Function Documentation
enable()
void giraffe::radio::SoftwareRadio::enable () inline override virtual
Attempts to enable the physical layer.
Reimplemented from giraffe::radio::Radio.
References giraffe::gdl::PhysicalLayer::setState().
disable()
void giraffe::radio::SoftwareRadio::disable () inline override virtual
Attempts to disable the physical layer.
Reimplemented from giraffe::radio::Radio.
update()
void giraffe::radio::SoftwareRadio::update () inline override virtual
Updates the physical layer.
Reimplemented from giraffe::radio::Radio.
startTransmit()
bool giraffe::radio::SoftwareRadio::startTransmit () inline override virtual
Starts transmitting data if possible.
Returns
true if transmission was started, false otherwise
Todo:
add a timeout parameter
Reimplemented from giraffe::radio::Radio.
stopTransmit()
bool giraffe::radio::SoftwareRadio::stopTransmit () inline override virtual
Stops transmitting data if currently transmitting.
Returns
true if a transmission was in progress and was stopped, false otherwise
Reimplemented from giraffe::radio::Radio.
changeMode()
bool giraffe::radio::SoftwareRadio::changeMode (Mode mode) inline override virtual
Attempts to change the mode of the physical layer.
Parameters
mode - The new mode to change to.
Returns
true if the mode was changed, false otherwise
Reimplemented from giraffe::radio::Radio.
References giraffe::gdl::PhysicalLayer::setMode().
getRssi()
double giraffe::radio::Radio::getRssi () const inline override virtual inherited
Gets the current RSSI of the physical layer.
Implements giraffe::gdl::PhysicalLayer.
getState()
PhysicalLayer::State giraffe::gdl::PhysicalLayer::getState () const inline inherited
Gets the current state of the physical layer.
Returns
The current state of the physical layer
References giraffe::gdl::PhysicalLayer::state_.
getMode()
Mode giraffe::gdl::PhysicalLayer::getMode () const inline inherited
Get the current mode of the physical layer.
Returns
The current mode of the physical layer
References giraffe::gdl::PhysicalLayer::mode_.
setState()
void giraffe::gdl::PhysicalLayer::setState (State state) inline protected inherited
References giraffe::gdl::PhysicalLayer::state_.
Referenced by giraffe::gdl::SoftwarePhysicalLayer::disable(), giraffe::radio::Radio::disable(), giraffe::gdl::SoftwarePhysicalLayer::enable(), giraffe::radio::Radio::enable(), enable(), giraffe::gdl::SoftwarePhysicalLayer::startTransmit(), giraffe::radio::Radio::startTransmit(), giraffe::gdl::SoftwarePhysicalLayer::stopTransmit(), and giraffe::radio::Radio::stopTransmit().
setMode()
void giraffe::gdl::PhysicalLayer::setMode (Mode mode) inline protected inherited
References giraffe::gdl::PhysicalLayer::mode_.
Referenced by giraffe::gdl::SoftwarePhysicalLayer::changeMode(), giraffe::radio::Radio::changeMode(), and changeMode().
Member Data Documentation
config_
const Config& giraffe::gdl::PhysicalLayer::config_ protected inherited
state_
State giraffe::gdl::PhysicalLayer::state_ = State::DISABLED private inherited
Referenced by giraffe::gdl::PhysicalLayer::getState(), and giraffe::gdl::PhysicalLayer::setState().
mode_
Mode giraffe::gdl::PhysicalLayer::mode_ = Mode::NONE private inherited
Referenced by giraffe::gdl::PhysicalLayer::getMode(), and giraffe::gdl::PhysicalLayer::setMode().