Giraffe: I2cInterface Class Reference
I2cInterface Class Reference
A wrapper around I2C communication that restricts a single thread from accessing the bus at a time.
#include <i2c_interface.hpp>
Public Types
enum class Result : int {
SUCCESS = 0 , BUS_OPEN_ERROR = 1 , ADDRESS_SET_ERROR = 2 , FD_NOT_OPEN = 3 ,
DISCONNECT_CLOSE_ERROR = 4 , WRITE_ERROR = 5 , WRITE_ERROR_NUM_BYTES = 6 , DATA_SIZE_ERROR = 6 ,
READ_ERROR = 7 , READ_ERROR_WRITE_REG = 8 , READ_ERROR_NUM_BYTES
}
Return codes for I2cInterface methods.
Public Member Functions
I2cInterface (cfg::gEnum::I2CBus bus, uint8_t address, std::mutex &bus_lock)
Construct a new I2cInterface instance.
~I2cInterface ()
Destroy the I2cInterface instance. Disconnects from the bus if it's open.
Result connect ()
Connect to the bus. If it's already connected, disconnect and reconnect.
Result disconnect ()
Disconnect from the bus. Reports an error if the bus is not connected.
uint8_t getAddress () const
Get the address of the device on the bus.
Result readByte (uint8_t &data_byte)
Read a single byte from the device without specifying a register.
Result readByteFromReg (uint8_t &data_byte, uint8_t register_address)
Read a single byte from the device at the specified register.
Result readChunk (std::vector< uint8_t > &data, size_t num_bytes)
Read a chunk of data from the device without specifying a register.
Result readChunkFromReg (std::vector< uint8_t > &data, uint8_t register_address, size_t num_bytes)
Read a chunk of data from the device at the specified register.
void reset ()
Disconnect from the bus if it's connected, otherwise do nothing.
Result writeByte (uint8_t data_byte)
Write a single byte to the device without specifying a register.
Result writeByteToReg (uint8_t data_byte, uint8_t register_address)
Write a single byte to the device at the specified register.
Result writeChunk (std::vector< uint8_t > &data)
Write a chunk of data to the device at the specified register.
Private Member Functions
bool isConnected () const
Checks the file descriptor to see if it's connected to the bus.
Private Attributes
const uint8_t address_
The address of the device on the bus to connect to.
const cfg::gEnum::I2CBus bus_
The bus to connect to. This will be translated to a file name.
std::mutex & bus_lock_
A common mutex to lock the bus with.
std::string file_name_ {}
The file name of the bus to connect to.
int i2c_fd_ = -1
The file descriptor of the bus.
Detailed Description
A wrapper around I2C communication that restricts a single thread from accessing the bus at a time.
Member Enumeration Documentation
Result
enum I2cInterface::Result : int strong
Return codes for I2cInterface methods.
Enumerator
SUCCESS
Generic success code.
BUS_OPEN_ERROR
Could not open the bus (e.g. the file descriptor is -1)
ADDRESS_SET_ERROR
Failed to set the address of the device on the bus.
FD_NOT_OPEN
The file descriptor is not open. This is likely because the bus has not been connected to.
DISCONNECT_CLOSE_ERROR
WRITE_ERROR
WRITE_ERROR_NUM_BYTES
If the number of bytes to be written is not equal to the number of bytes that were actually written, this error is returned.
DATA_SIZE_ERROR
Passing an empty vector as a C array is undefined behavior.
READ_ERROR
READ_ERROR_WRITE_REG
READ_ERROR_NUM_BYTES
Constructor & Destructor Documentation
I2cInterface()
I2cInterface::I2cInterface (cfg::gEnum::I2CBus bus, uint8_t address, std::mutex & bus_lock)
Construct a new I2cInterface instance.
Parameters
bus - The bus to connect to.
address - The address of the device on the bus.
bus_lock - A common mutex to lock the bus with.
References file_name_, and giraffe_assert.
~I2cInterface()
I2cInterface::~I2cInterface ()
Destroy the I2cInterface instance. Disconnects from the bus if it's open.
References disconnect().
Member Function Documentation
connect()
I2cInterface::Result I2cInterface::connect ()
Connect to the bus. If it's already connected, disconnect and reconnect.
Returns
Result - 'SUCCESS' if successful, otherwise an error code.
References address_, ADDRESS_SET_ERROR, bus_lock_, BUS_OPEN_ERROR, file_name_, i2c_fd_, and SUCCESS.
Referenced by extension::I2cExtensionAdapter::connectToI2cBus(), extension::Bme280::startup(), and extension::SamM8q::startup().
disconnect()
I2cInterface::Result I2cInterface::disconnect ()
Disconnect from the bus. Reports an error if the bus is not connected.
Returns
Result - 'SUCCESS' if successful, otherwise an error code.
References bus_lock_, DISCONNECT_CLOSE_ERROR, FD_NOT_OPEN, i2c_fd_, isConnected(), and SUCCESS.
Referenced by ~I2cInterface().
reset()
void I2cInterface::reset ()
Disconnect from the bus if it's connected, otherwise do nothing.
Will not report any error. This is really just a safe way to reset the connection.
References bus_lock_, i2c_fd_, and isConnected().
getAddress()
uint8_t I2cInterface::getAddress () const
Get the address of the device on the bus.
Returns
uint8_t - The address of the device on the bus.
References address_.
Referenced by ubx::setProtocolDDC().
writeByte()
I2cInterface::Result I2cInterface::writeByte (uint8_t data_byte)
Write a single byte to the device without specifying a register.
Parameters
data_byte - The byte to write.
Returns
Result - 'SUCCESS' if successful, otherwise an error code.
References bus_lock_, FD_NOT_OPEN, i2c_fd_, isConnected(), SUCCESS, and WRITE_ERROR.
writeByteToReg()
I2cInterface::Result I2cInterface::writeByteToReg (uint8_t data_byte, uint8_t register_address)
Write a single byte to the device at the specified register.
This will first write the register address, then the data byte.
Parameters
data_byte - The byte to write.
register_address - The register address to write to.
Returns
Result - 'SUCCESS' if successful, otherwise an error code.
References bus_lock_, FD_NOT_OPEN, i2c_fd_, isConnected(), SUCCESS, and WRITE_ERROR.
Referenced by extension::Bme280::configureSensor(), and extension::Bme280::resetSensor().
writeChunk()
I2cInterface::Result I2cInterface::writeChunk (std::vector< uint8_t > & data)
Write a chunk of data to the device at the specified register.
Parameters
data - The data to write.
Returns
Result - 'SUCCESS' if successful, otherwise an error code.
References bus_lock_, DATA_SIZE_ERROR, FD_NOT_OPEN, i2c_fd_, isConnected(), SUCCESS, and WRITE_ERROR.
Referenced by ubx::writeUBX().
readByte()
I2cInterface::Result I2cInterface::readByte (uint8_t & data_byte)
Read a single byte from the device without specifying a register.
Parameters
data_byte (out) - The byte read from the device.
Returns
Result - 'SUCCESS' if successful, otherwise an error code.
References bus_lock_, FD_NOT_OPEN, i2c_fd_, isConnected(), READ_ERROR, and SUCCESS.
readByteFromReg()
I2cInterface::Result I2cInterface::readByteFromReg (uint8_t & data_byte, uint8_t register_address)
Read a single byte from the device at the specified register.
Parameters
data_byte (out) - The byte read from the device.
register_address - The register address to read from.
Returns
Result - 'SUCCESS' if successful, otherwise an error code.
References bus_lock_, FD_NOT_OPEN, i2c_fd_, isConnected(), READ_ERROR, and SUCCESS.
Referenced by ubx::getStreamSize(), extension::Bme280::handshake(), extension::SamM8q::handshake(), and ubx::readNextUBX().
readChunkFromReg()
I2cInterface::Result I2cInterface::readChunkFromReg (std::vector< uint8_t > & data, uint8_t register_address, size_t num_bytes)
Read a chunk of data from the device at the specified register.
The 'data' vector will be cleared and resized to 'num_bytes'.
Parameters
data (out) - The data read from the device.
register_address - The register address to read from.
num_bytes - The number of bytes to read.
Returns
Result - 'SUCCESS' if successful, otherwise an error code.
References bus_lock_, FD_NOT_OPEN, i2c_fd_, isConnected(), READ_ERROR, READ_ERROR_NUM_BYTES, READ_ERROR_WRITE_REG, and SUCCESS.
Referenced by ubx::flushStream(), ubx::pollMessage(), extension::Bme280::readCompensationData(), extension::Bme280::readEnvironmentalData(), and ubx::readNextUBX().
readChunk()
I2cInterface::Result I2cInterface::readChunk (std::vector< uint8_t > & data, size_t num_bytes)
Read a chunk of data from the device without specifying a register.
The 'data' vector will be cleared and resized to 'num_bytes'.
Parameters
data (out) - The data read from the device.
num_bytes - The number of bytes to read.
Returns
Result - 'SUCCESS' if successful, otherwise an error code.
References bus_lock_, FD_NOT_OPEN, i2c_fd_, isConnected(), READ_ERROR, READ_ERROR_NUM_BYTES, and SUCCESS.
Referenced by extension::Mcp3021::readAdc().
isConnected()
bool I2cInterface::isConnected () const private
Checks the file descriptor to see if it's connected to the bus.
Returns
true - The file descriptor is open.
false - The file descriptor is not open.
References i2c_fd_.
Referenced by disconnect(), readByte(), readByteFromReg(), readChunk(), readChunkFromReg(), reset(), writeByte(), writeByteToReg(), and writeChunk().
Member Data Documentation
bus_
const cfg::gEnum::I2CBus I2cInterface::bus_ private
The bus to connect to. This will be translated to a file name.
address_
const uint8_t I2cInterface::address_ private
The address of the device on the bus to connect to.
Referenced by connect(), and getAddress().
bus_lock_
std::mutex& I2cInterface::bus_lock_ private
A common mutex to lock the bus with.
Referenced by connect(), disconnect(), readByte(), readByteFromReg(), readChunk(), readChunkFromReg(), reset(), writeByte(), writeByteToReg(), and writeChunk().
file_name_
std::string I2cInterface::file_name_ {} private
The file name of the bus to connect to.
Referenced by I2cInterface(), and connect().
i2c_fd_
int I2cInterface::i2c_fd_ = -1 private
The file descriptor of the bus.
Referenced by connect(), disconnect(), isConnected(), readByte(), readByteFromReg(), readChunk(), readChunkFromReg(), reset(), writeByte(), writeByteToReg(), and writeChunk().