Giraffe: GdlTerminal Class Reference
GdlTerminal Class Reference
The Giraffe Data Link Terminal.
Public Member Functions
GdlTerminal ()
~GdlTerminal ()=default
void routeRequest (const std::string &rsc)
int run ()
Private Member Functions
json aprsPositionalPacketToJson (signal_easel::aprs::PositionPacket &packet)
Private Attributes
signal_easel::aprs::Packet base_aprs_packet_ {}
sock::TcpSocketServer client_socket_ {}
gdl::GiraffeDataLink gdl_ {gdl_config_, transport_layer_}
gdl::GdlConfig gdl_config_ {}
gdl::AprsNetworkLayer network_layer_ {physical_layer_, base_aprs_packet_}
gdl::PhysicalLayer physical_layer_ {}
sock::TcpSocketServer server_socket_ {}
bool stop_flag_ {false}
gdl::TransportLayer transport_layer_ {network_layer_, gdl_config_}
Detailed Description
The Giraffe Data Link Terminal.
This contains a simple terminal for interacting with the GDL (or at least it did). However, not it is primarily interfaced with the GGS via a TCP socket.
Constructor & Destructor Documentation
GdlTerminal()
GdlTerminal::GdlTerminal () inline
~GdlTerminal()
GdlTerminal::~GdlTerminal () default
Member Function Documentation
run()
int GdlTerminal::run () inline
References sock::TcpSocketServer::accept(), client_socket_, gdl_, sock::TcpSocketServer::init(), protocol::parseMessage(), sock::TcpSocketServer::receive(), protocol::REQ, routeRequest(), protocol::Message::rsc, server_socket_, gdl::GiraffeDataLink::start(), gdl::GiraffeDataLink::stop(), stop_flag_, and protocol::Message::typ.
Referenced by main().
routeRequest()
void GdlTerminal::routeRequest (const std::string & rsc) inline
References aprsPositionalPacketToJson(), client_socket_, protocol::createResponseMessage(), protocol::ERROR, protocol::GDL, gdl_, GDL_CONNECTION_STATE_MAP, GDL_STATUS_MAP, gdl::GiraffeDataLink::getAprsGpsRxQueueSize(), gdl::GiraffeDataLink::getAprsGpsTxQueueSize(), gdl::GiraffeDataLink::getDownlinkStatus(), gdl::GiraffeDataLink::getGdlStatus(), protocol::Message::getJsonString(), gdl::GiraffeDataLink::getReceivedAprsGpsPacket(), gdl::GiraffeDataLink::getStatus(), gdl::GiraffeDataLink::getUplinkStatus(), protocol::GGS, protocol::GOOD, and sock::TcpSocketServer::send().
Referenced by run().
aprsPositionalPacketToJson()
json GdlTerminal::aprsPositionalPacketToJson (signal_easel::aprs::PositionPacket & packet) inline private
Referenced by routeRequest().
Member Data Documentation
stop_flag_
bool GdlTerminal::stop_flag_ {false} private
Referenced by run().
base_aprs_packet_
signal_easel::aprs::Packet GdlTerminal::base_aprs_packet_ {} private
gdl_config_
gdl::GdlConfig GdlTerminal::gdl_config_ {} private
server_socket_
sock::TcpSocketServer GdlTerminal::server_socket_ {} private
Referenced by run().
client_socket_
sock::TcpSocketServer GdlTerminal::client_socket_ {} private
Referenced by routeRequest(), and run().
physical_layer_
gdl::PhysicalLayer GdlTerminal::physical_layer_ {} private
network_layer_
gdl::AprsNetworkLayer GdlTerminal::network_layer_ {physical_layer_, base_aprs_packet_} private
transport_layer_
gdl::TransportLayer GdlTerminal::transport_layer_ {network_layer_, gdl_config_} private
gdl_
gdl::GiraffeDataLink GdlTerminal::gdl_ {gdl_config_, transport_layer_} private
Referenced by routeRequest(), and run().