Giraffe: giraffe::gdl::Message Class Reference
giraffe::gdl::Message Class Reference
A message that can be sent via GDL.
#include <gdl_message.hpp>
Classes
struct AprsTelemetry
struct Image
struct Location
Public Types
enum class Type : uint8_t {
BROADCAST , EXCHANGE , LOCATION , IMAGE ,
TELEMETRY
}
The type of message.
Public Member Functions
Message ()=default
std::string getData () const
uint32_t getIdentifier () const
std::string getIdentifierString () const
Image getImage () const
json getJson () const
Location getLocation () const
AprsTelemetry getTelemetry () const
uint32_t getTimestamp () const
Get the timestamp of the message in Unix time (seconds since epoch).
Type getType () const
bool setBroadcastMessage (std::string broadcast_message, uint32_t identifier)
void setData (std::string data)
bool setExchangeMessage (std::string exchange_message, uint32_t identifier)
void setIdentifier (uint32_t identifier)
bool setIdentifierFromHex (const std::string &identifier)
void setImageMessage (Image image_info, uint32_t identifier)
void setLocation (Location location)
bool setLocationMessage (Location location, uint32_t identifier)
void setTelemetry (AprsTelemetry telemetry)
void setTelemetryMessage (AprsTelemetry telemetry, uint32_t identifier)
void setType (Type type)
void updateTimestamp ()
Set the timestamp of the message to the current time.
bool verifyType ()
Private Attributes
std::variant< std::string, Location, Image, AprsTelemetry > contents_
uint32_t identifier_ = 0
uint32_t timestamp_ {0}
The timestamp of when the message was received or sent.
Type type_ {Type::BROADCAST}
Detailed Description
A message that can be sent via GDL.
Class Documentation
giraffe::gdl::Message::AprsTelemetry
struct giraffe::gdl::Message::AprsTelemetry
Class Members
typedef Type TelemType
typedef TelemetryData TelemetryData
Class Members
TelemType telemetry_type
TelemetryData telemetry_data
giraffe::gdl::Message::Image
struct giraffe::gdl::Message::Image
Class Members
string path
giraffe::gdl::Message::Location
struct giraffe::gdl::Message::Location
Class Members
double latitude
double longitude
uint32_t altitude
double speed
int heading
string time_code
Member Enumeration Documentation
Type
enum giraffe::gdl::Message::Type : uint8_t strong
The type of message.
Enumerator
BROADCAST
EXCHANGE
LOCATION
IMAGE
TELEMETRY
Constructor & Destructor Documentation
Message()
giraffe::gdl::Message::Message () default
Member Function Documentation
setBroadcastMessage()
bool giraffe::gdl::Message::setBroadcastMessage (std::string broadcast_message, uint32_t identifier) inline
References BROADCAST, contents_, giraffe::gdl::GDL_MESSAGE_DATA_MAX_SIZE, identifier_, and type_.
Referenced by giraffe::gdl::DataLink::broadcastText(), giraffe::gdl::GdlServer::handleSetNewBroadcast(), main(), and TEST().
setExchangeMessage()
bool giraffe::gdl::Message::setExchangeMessage (std::string exchange_message, uint32_t identifier) inline
References contents_, EXCHANGE, giraffe::gdl::GDL_MESSAGE_DATA_MAX_SIZE, identifier_, and type_.
Referenced by giraffe::gdl::GdlServer::handleSetNewExchange(), giraffe::gdl::TransportLayer::idleState(), main(), giraffe::gdl::DataLink::sendText(), and TEST().
setLocationMessage()
bool giraffe::gdl::Message::setLocationMessage (Location location, uint32_t identifier) inline
References contents_, identifier_, LOCATION, and type_.
Referenced by TEST().
setImageMessage()
void giraffe::gdl::Message::setImageMessage (Image image_info, uint32_t identifier) inline
References contents_, identifier_, IMAGE, and type_.
Referenced by modules::TelemetryModule::sendSstvImage(), and TEST().
setTelemetryMessage()
void giraffe::gdl::Message::setTelemetryMessage (AprsTelemetry telemetry, uint32_t identifier) inline
References contents_, identifier_, TELEMETRY, and type_.
Referenced by giraffe::gdl::DataLink::sendTelemetryBitSense(), giraffe::gdl::DataLink::sendTelemetryCoefficients(), giraffe::gdl::DataLink::sendTelemetryData(), giraffe::gdl::DataLink::sendTelemetryParameterNames(), and giraffe::gdl::DataLink::sendTelemetryUnitsAndLabels().
getIdentifier()
uint32_t giraffe::gdl::Message::getIdentifier () const inline
References identifier_.
Referenced by giraffe::gdl::TransportLayer::exchangeSendState(), giraffe::gdl::TransportLayer::exchangeWaitingForAckState(), giraffe::gdl::TransportLayer::idleState(), and TEST().
setIdentifier()
void giraffe::gdl::Message::setIdentifier (uint32_t identifier) inline
References identifier_.
Referenced by giraffe::gdl::TransportLayer::sendAck(), giraffe::gdl::TransportLayer::sendPing(), and giraffe::gdl::TransportLayer::sendPingResponse().
setIdentifierFromHex()
bool giraffe::gdl::Message::setIdentifierFromHex (const std::string & identifier) inline
References identifier_.
Referenced by giraffe::gdl::NetworkLayer::rxPacket().
getIdentifierString()
std::string giraffe::gdl::Message::getIdentifierString () const inline
References identifier_.
Referenced by getJson(), modules::TelemetryModule::processTelemetryMessageQueue(), and giraffe::gdl::NetworkLayer::txPacket().
getType()
Type giraffe::gdl::Message::getType () const inline
References type_.
Referenced by getJson(), main(), modules::TelemetryModule::processTelemetryMessageQueue(), giraffe::gdl::TransportLayer::send(), giraffe::gdl::DataLink::sendMessage(), TEST(), and verifyType().
setType()
void giraffe::gdl::Message::setType (Type type) inline
References type_.
Referenced by giraffe::gdl::TransportLayer::idleState(), and TEST().
setData()
void giraffe::gdl::Message::setData (std::string data) inline
References contents_.
Referenced by giraffe::gdl::NetworkLayer::rxPacket().
getData()
std::string giraffe::gdl::Message::getData () const inline
References contents_.
Referenced by getJson(), giraffe::gdl::TransportLayer::idleState(), main(), modules::TelemetryModule::processTelemetryMessageQueue(), TEST(), and giraffe::gdl::NetworkLayer::txPacket().
setLocation()
void giraffe::gdl::Message::setLocation (Location location) inline
References contents_.
Referenced by giraffe::gdl::NetworkLayer::rxPacket(), and modules::TelemetryModule::sendAprsPositionPacket().
setTelemetry()
void giraffe::gdl::Message::setTelemetry (AprsTelemetry telemetry) inline
References contents_.
Referenced by giraffe::gdl::NetworkLayer::rxPacket().
getLocation()
Location giraffe::gdl::Message::getLocation () const inline
References contents_.
Referenced by getJson(), TEST(), and giraffe::gdl::NetworkLayer::txAprsPositionPacket().
getImage()
Image giraffe::gdl::Message::getImage () const inline
References contents_.
Referenced by getJson(), TEST(), and giraffe::gdl::NetworkLayer::txSstvImage().
getTelemetry()
AprsTelemetry giraffe::gdl::Message::getTelemetry () const inline
References contents_.
Referenced by getJson(), and giraffe::gdl::NetworkLayer::txAprsTelemetryPacket().
getJson()
json giraffe::gdl::Message::getJson () const inline
References giraffe::gdl::Message::Location::altitude, BROADCAST, EXCHANGE, getData(), getIdentifierString(), getImage(), getLocation(), getTelemetry(), getTimestamp(), getType(), giraffe::gdl::Message::Location::heading, IMAGE, giraffe::gdl::Message::Location::latitude, LOCATION, giraffe::gdl::Message::Location::longitude, giraffe::gdl::Message::Image::path, giraffe::gdl::Message::Location::speed, TELEMETRY, and giraffe::gdl::Message::Location::time_code.
Referenced by giraffe::gdl::GdlServer::handleRequestReceivedMessages(), and giraffe::gdl::GdlServer::handleRequestSentMessages().
verifyType()
bool giraffe::gdl::Message::verifyType () inline
References BROADCAST, contents_, EXCHANGE, getType(), giraffe_assert, IMAGE, LOCATION, and TELEMETRY.
Referenced by TEST().
updateTimestamp()
void giraffe::gdl::Message::updateTimestamp () inline
Set the timestamp of the message to the current time.
Unix time - seconds since epoch
References getUnixTime(), and timestamp_.
Referenced by giraffe::gdl::NetworkLayer::rxPacket().
getTimestamp()
uint32_t giraffe::gdl::Message::getTimestamp () const inline
Get the timestamp of the message in Unix time (seconds since epoch).
References timestamp_.
Referenced by getJson().
Member Data Documentation
identifier_
uint32_t giraffe::gdl::Message::identifier_ = 0 private
Referenced by getIdentifier(), getIdentifierString(), setBroadcastMessage(), setExchangeMessage(), setIdentifier(), setIdentifierFromHex(), setImageMessage(), setLocationMessage(), and setTelemetryMessage().
type_
Type giraffe::gdl::Message::type_ {Type::BROADCAST} private
Referenced by getType(), setBroadcastMessage(), setExchangeMessage(), setImageMessage(), setLocationMessage(), setTelemetryMessage(), and setType().
contents_
std::variant<std::string, Location, Image, AprsTelemetry> giraffe::gdl::Message::contents_ private
Referenced by getData(), getImage(), getLocation(), getTelemetry(), setBroadcastMessage(), setData(), setExchangeMessage(), setImageMessage(), setLocation(), setLocationMessage(), setTelemetry(), setTelemetryMessage(), and verifyType().
timestamp_
uint32_t giraffe::gdl::Message::timestamp_ {0} private
The timestamp of when the message was received or sent.
Unix time - seconds since epoch
Referenced by getTimestamp(), and updateTimestamp().