Giraffe: giraffe::FlightRunnerData Class Reference
giraffe::FlightRunnerData Class Reference
Data that is persisted across system restarts. Used by the flight runner to track the state of the system.
#include <flight_runner_data.hpp>
Public Types
enum class ShutdownReason { CRASH_OR_UNKNOWN , CTRL_C , TELEMETRY_SDN_COMMAND }
The reason the system was shutdown. Stored in the data file.
Public Member Functions
FlightRunnerData ()
The default constructor will attempt to load the data from the saved file.
~FlightRunnerData ()
Destructor will attempt to save to the data file.
void clearLaunchPosition ()
Clears the launch position/set it to invalid.
void fullReset ()
Fully resets the flight runner data as if the system has never started before.
FlightPhase getFlightPhase () const
void getLaunchPosition (bool &valid, double &latitude, double &longitude, double &altitude)
Get the Launch Position object.
uint32_t getNumStartups () const
bool getSecondsSincePreviousShutdown (int64_t &num_seconds)
bool getSecondsSincePreviousStartup (int64_t &num_seconds)
bool getSecondsSinceStartup (int64_t &num_seconds)
void incrementNumStartups ()
void setFlightPhase (FlightPhase flight_phase)
void setLaunchPosition (bool valid, double latitude, double longitude, double altitude)
Set the launch position. Called on the transition from pre-launch to launch.
void setShutdownReason (ShutdownReason shutdown_reason)
Private Member Functions
void saveData (bool shutdown_save=false)
Attempts to save the data to a file.
Private Attributes
std::string data_file_path_ = ""
The path to the data file. Set in the constructor.
FlightPhase flight_phase_ = FlightPhase::UNKNOWN
double launch_position_altitude_ = 0.0
double launch_position_latitude_ = 0.0
double launch_position_longitude_ = 0.0
bool launch_position_valid_ = false
The launch position. Set to invalid by default.
bool load_status_ = false
Set to true when the data has been loaded from a file.
uint32_t num_startups_ = 0
The number of times the system has been started.
bst::Time previous_shutdown_time_ = {}
Used to store the time the system was previously shut down. Updated at shutdown.
bool previous_shutdown_time_valid_ = false
bst::Time previous_startup_time_ = {}
The previous time the system was started. Updated at startup.
bool previous_startup_time_valid_ = false
bool save_status_ = false
Set to true when the data has been saved to a file.
ShutdownReason shutdown_reason_ = ShutdownReason::CRASH_OR_UNKNOWN
bst::Time startup_time_ = {}
The time the system was started. Immediately set once after startup. Not updated after a full reset.
Detailed Description
Data that is persisted across system restarts. Used by the flight runner to track the state of the system.
Member Enumeration Documentation
ShutdownReason
enum giraffe::FlightRunnerData::ShutdownReason strong
The reason the system was shutdown. Stored in the data file.
Enumerator
CRASH_OR_UNKNOWN
The system stopped accidentally, not on purpose. Most likely a software crash.
CTRL_C
User requested a shutdown by pressing CTRL+C.
TELEMETRY_SDN_COMMAND
User requested a shutdown via the telemetry sdn command.
Constructor & Destructor Documentation
FlightRunnerData()
giraffe::FlightRunnerData::FlightRunnerData ()
The default constructor will attempt to load the data from the saved file.
~FlightRunnerData()
giraffe::FlightRunnerData::~FlightRunnerData ()
Destructor will attempt to save to the data file.
Member Function Documentation
fullReset()
void giraffe::FlightRunnerData::fullReset ()
Fully resets the flight runner data as if the system has never started before.
incrementNumStartups()
void giraffe::FlightRunnerData::incrementNumStartups ()
getNumStartups()
uint32_t giraffe::FlightRunnerData::getNumStartups () const
setShutdownReason()
void giraffe::FlightRunnerData::setShutdownReason (ShutdownReason shutdown_reason)
getSecondsSinceStartup()
bool giraffe::FlightRunnerData::getSecondsSinceStartup (int64_t & num_seconds)
getSecondsSincePreviousStartup()
bool giraffe::FlightRunnerData::getSecondsSincePreviousStartup (int64_t & num_seconds)
getSecondsSincePreviousShutdown()
bool giraffe::FlightRunnerData::getSecondsSincePreviousShutdown (int64_t & num_seconds)
setFlightPhase()
void giraffe::FlightRunnerData::setFlightPhase (FlightPhase flight_phase)
Referenced by FlightRunner::setFlightPhase().
getFlightPhase()
FlightPhase giraffe::FlightRunnerData::getFlightPhase () const
Referenced by FlightRunner::detectFlightPhase().
clearLaunchPosition()
void giraffe::FlightRunnerData::clearLaunchPosition ()
Clears the launch position/set it to invalid.
Referenced by FlightRunner::setLaunchPosition().
setLaunchPosition()
void giraffe::FlightRunnerData::setLaunchPosition (bool valid, double latitude, double longitude, double altitude)
Set the launch position. Called on the transition from pre-launch to launch.
Parameters
valid - True if the position is valid.
latitude - The latitude of the launch position.
longitude - The longitude of the launch position.
altitude - The altitude of the launch position.
Referenced by FlightRunner::setLaunchPosition().
getLaunchPosition()
void giraffe::FlightRunnerData::getLaunchPosition (bool & valid, double & latitude, double & longitude, double & altitude)
Get the Launch Position object.
Parameters
[out] valid - True if the position is valid.
[out] latitude - The latitude of the launch position.
[out] longitude - The longitude of the launch position.
[out] altitude - The altitude of the launch position.
saveData()
void giraffe::FlightRunnerData::saveData (bool shutdown_save = false) private
Attempts to save the data to a file.
Member Data Documentation
load_status_
bool giraffe::FlightRunnerData::load_status_ = false private
Set to true when the data has been loaded from a file.
save_status_
bool giraffe::FlightRunnerData::save_status_ = false private
Set to true when the data has been saved to a file.
startup_time_
bst::Time giraffe::FlightRunnerData::startup_time_ = {} private
The time the system was started. Immediately set once after startup. Not updated after a full reset.
Todo:
this is a duplicate of the time in shared_date_.flight_data
previous_startup_time_
bst::Time giraffe::FlightRunnerData::previous_startup_time_ = {} private
The previous time the system was started. Updated at startup.
previous_startup_time_valid_
bool giraffe::FlightRunnerData::previous_startup_time_valid_ = false private
previous_shutdown_time_
bst::Time giraffe::FlightRunnerData::previous_shutdown_time_ = {} private
Used to store the time the system was previously shut down. Updated at shutdown.
previous_shutdown_time_valid_
bool giraffe::FlightRunnerData::previous_shutdown_time_valid_ = false private
shutdown_reason_
ShutdownReason giraffe::FlightRunnerData::shutdown_reason_ = ShutdownReason::CRASH_OR_UNKNOWN private
num_startups_
uint32_t giraffe::FlightRunnerData::num_startups_ = 0 private
The number of times the system has been started.
flight_phase_
FlightPhase giraffe::FlightRunnerData::flight_phase_ = FlightPhase::UNKNOWN private
This is only set in detectFlightPhase.
See also
detectFlightPhase
launch_position_valid_
bool giraffe::FlightRunnerData::launch_position_valid_ = false private
The launch position. Set to invalid by default.
launch_position_latitude_
double giraffe::FlightRunnerData::launch_position_latitude_ = 0.0 private
launch_position_longitude_
double giraffe::FlightRunnerData::launch_position_longitude_ = 0.0 private
launch_position_altitude_
double giraffe::FlightRunnerData::launch_position_altitude_ = 0.0 private
data_file_path_
std::string giraffe::FlightRunnerData::data_file_path_ = "" private
The path to the data file. Set in the constructor.