Giraffe: giraffe::radio::Radio Class Reference
giraffe::radio::Radio Class Reference
#include <radio.hpp>
Public Types
enum class Mode { NONE , DATA , APRS , SSTV }
using State = giraffe::gdl::PhysicalLayer::State
Public Member Functions
Radio (giraffe::gdl::Config &config)
virtual ~Radio ()=default
bool changeMode (Mode mode) override
Attempts to change the mode of the physical layer.
void disable () override
Attempts to disable the physical layer.
void enable () override
Attempts to enable the physical layer.
Mode getMode () const
Get the current mode of the physical layer.
double getRssi () const override
Gets the current RSSI of the physical layer.
PhysicalLayer::State getState () const
Gets the current state of the physical layer.
bool startTransmit () override
Starts transmitting data if possible.
bool stopTransmit () override
Stops transmitting data if currently transmitting.
void update () override
Updates the physical layer.
Protected Member Functions
void setMode (Mode mode)
void setState (State state)
Protected Attributes
const Config & config_
Private Attributes
Mode mode_ = Mode::NONE
State state_ = State::DISABLED
Member Typedef Documentation
State
using giraffe::radio::Radio::State = giraffe::gdl::PhysicalLayer::State
Member Enumeration Documentation
Mode
enum giraffe::gdl::PhysicalLayer::Mode strong inherited
Enumerator
NONE
DATA
APRS
SSTV
Constructor & Destructor Documentation
Radio()
giraffe::radio::Radio::Radio (giraffe::gdl::Config & config) inline
~Radio()
virtual giraffe::radio::Radio::~Radio () virtual default
Member Function Documentation
enable()
void giraffe::radio::Radio::enable () inline override virtual
Attempts to enable the physical layer.
Implements giraffe::gdl::PhysicalLayer.
Reimplemented in giraffe::radio::SoftwareRadio, and giraffe::radio::Sa868.
References giraffe::gdl::PhysicalLayer::IDLE, and giraffe::gdl::PhysicalLayer::setState().
disable()
void giraffe::radio::Radio::disable () inline override virtual
Attempts to disable the physical layer.
Implements giraffe::gdl::PhysicalLayer.
Reimplemented in giraffe::radio::SoftwareRadio, and giraffe::radio::Sa868.
References giraffe::gdl::PhysicalLayer::DISABLED, and giraffe::gdl::PhysicalLayer::setState().
update()
void giraffe::radio::Radio::update () inline override virtual
Updates the physical layer.
Implements giraffe::gdl::PhysicalLayer.
Reimplemented in giraffe::radio::SoftwareRadio, and giraffe::radio::Sa868.
startTransmit()
bool giraffe::radio::Radio::startTransmit () inline override virtual
Starts transmitting data if possible.
Returns
true if transmission was started, false otherwise
Todo:
add a timeout parameter
Implements giraffe::gdl::PhysicalLayer.
Reimplemented in giraffe::radio::SoftwareRadio.
References giraffe::gdl::PhysicalLayer::setState(), and giraffe::gdl::PhysicalLayer::TRANSMITTING.
stopTransmit()
bool giraffe::radio::Radio::stopTransmit () inline override virtual
Stops transmitting data if currently transmitting.
Returns
true if a transmission was in progress and was stopped, false otherwise
Implements giraffe::gdl::PhysicalLayer.
Reimplemented in giraffe::radio::SoftwareRadio.
References giraffe::gdl::PhysicalLayer::IDLE, and giraffe::gdl::PhysicalLayer::setState().
getRssi()
double giraffe::radio::Radio::getRssi () const inline override virtual
Gets the current RSSI of the physical layer.
Implements giraffe::gdl::PhysicalLayer.
changeMode()
bool giraffe::radio::Radio::changeMode (Mode mode) inline override virtual
Attempts to change the mode of the physical layer.
Parameters
mode - The new mode to change to.
Returns
true if the mode was changed, false otherwise
Implements giraffe::gdl::PhysicalLayer.
Reimplemented in giraffe::radio::SoftwareRadio.
References giraffe::gdl::PhysicalLayer::setMode().
getState()
PhysicalLayer::State giraffe::gdl::PhysicalLayer::getState () const inline inherited
Gets the current state of the physical layer.
Returns
The current state of the physical layer
References giraffe::gdl::PhysicalLayer::state_.
getMode()
Mode giraffe::gdl::PhysicalLayer::getMode () const inline inherited
Get the current mode of the physical layer.
Returns
The current mode of the physical layer
References giraffe::gdl::PhysicalLayer::mode_.
setState()
void giraffe::gdl::PhysicalLayer::setState (State state) inline protected inherited
References giraffe::gdl::PhysicalLayer::state_.
Referenced by giraffe::gdl::SoftwarePhysicalLayer::disable(), disable(), giraffe::gdl::SoftwarePhysicalLayer::enable(), enable(), giraffe::radio::SoftwareRadio::enable(), giraffe::gdl::SoftwarePhysicalLayer::startTransmit(), startTransmit(), giraffe::gdl::SoftwarePhysicalLayer::stopTransmit(), and stopTransmit().
setMode()
void giraffe::gdl::PhysicalLayer::setMode (Mode mode) inline protected inherited
References giraffe::gdl::PhysicalLayer::mode_.
Referenced by giraffe::gdl::SoftwarePhysicalLayer::changeMode(), changeMode(), and giraffe::radio::SoftwareRadio::changeMode().
Member Data Documentation
config_
const Config& giraffe::gdl::PhysicalLayer::config_ protected inherited
state_
State giraffe::gdl::PhysicalLayer::state_ = State::DISABLED private inherited
Referenced by giraffe::gdl::PhysicalLayer::getState(), and giraffe::gdl::PhysicalLayer::setState().
mode_
Mode giraffe::gdl::PhysicalLayer::mode_ = Mode::NONE private inherited
Referenced by giraffe::gdl::PhysicalLayer::getMode(), and giraffe::gdl::PhysicalLayer::setMode().