Giraffe: MockIDataLink Class Reference
MockIDataLink Class Reference final abstract
Public Types
using TelemetryData = signal_easel::aprs::telemetry::TelemetryData
Public Member Functions
gdl::Config & getConfig () override
gdl::Statistics getStatistics () override
gdl::IDataLink::TelemetryData & getTelemetryData ()
MOCK_METHOD (bool, sendTelemetryBitSense,(gdl::IDataLink::TelemetryData &data),(override))
MOCK_METHOD (bool, sendTelemetryCoefficients,(gdl::IDataLink::TelemetryData &data),(override))
MOCK_METHOD (bool, sendTelemetryData,(gdl::IDataLink::TelemetryData &data, uint32_t message_id),(override))
MOCK_METHOD (bool, sendTelemetryParameterNames,(gdl::IDataLink::TelemetryData &data),(override))
MOCK_METHOD (bool, sendTelemetryUnitsAndLabels,(gdl::IDataLink::TelemetryData &data),(override))
virtual bool sendTelemetryBitSense (TelemetryData &telemetry_data)=0
virtual bool sendTelemetryCoefficients (TelemetryData &telemetry_data)=0
virtual bool sendTelemetryData (TelemetryData &telemetry_data, uint32_t message_id)=0
virtual bool sendTelemetryParameterNames (TelemetryData &telemetry_data)=0
virtual bool sendTelemetryUnitsAndLabels (TelemetryData &telemetry_data)=0
void updateTelemetryData (const gdl::IDataLink::TelemetryData &data) override
Private Attributes
gdl::Config config_ {false}
gdl::Statistics stats_ {}
gdl::IDataLink::TelemetryData telemetry_data_ {}
Member Typedef Documentation
TelemetryData
using giraffe::gdl::IDataLink::TelemetryData = signal_easel::aprs::telemetry::TelemetryData inherited
Member Function Documentation
getStatistics()
gdl::Statistics MockIDataLink::getStatistics () inline override virtual
Implements giraffe::gdl::IDataLink.
References stats_.
getConfig()
gdl::Config & MockIDataLink::getConfig () inline override virtual
Implements giraffe::gdl::IDataLink.
References config_.
Referenced by AprsTelemetryDataManagerTest::SetUp().
updateTelemetryData()
void MockIDataLink::updateTelemetryData (const gdl::IDataLink::TelemetryData & data) inline override virtual
Implements giraffe::gdl::IDataLink.
References telemetry_data_.
MOCK_METHOD() [1/5]
MockIDataLink::MOCK_METHOD (bool , sendTelemetryData , (gdl::IDataLink::TelemetryData &data, uint32_t message_id) , (override))
MOCK_METHOD() [2/5]
MockIDataLink::MOCK_METHOD (bool , sendTelemetryCoefficients , (gdl::IDataLink::TelemetryData &data) , (override))
MOCK_METHOD() [3/5]
MockIDataLink::MOCK_METHOD (bool , sendTelemetryParameterNames , (gdl::IDataLink::TelemetryData &data) , (override))
MOCK_METHOD() [4/5]
MockIDataLink::MOCK_METHOD (bool , sendTelemetryUnitsAndLabels , (gdl::IDataLink::TelemetryData &data) , (override))
MOCK_METHOD() [5/5]
MockIDataLink::MOCK_METHOD (bool , sendTelemetryBitSense , (gdl::IDataLink::TelemetryData &data) , (override))
getTelemetryData()
gdl::IDataLink::TelemetryData & MockIDataLink::getTelemetryData () inline
References telemetry_data_.
sendTelemetryData()
virtual bool giraffe::gdl::IDataLink::sendTelemetryData (TelemetryData & telemetry_data, uint32_t message_id) pure virtual inherited
Implemented in giraffe::gdl::DataLink.
Referenced by giraffe::gdl::AprsTelemetrySender::update().
sendTelemetryCoefficients()
virtual bool giraffe::gdl::IDataLink::sendTelemetryCoefficients (TelemetryData & telemetry_data) pure virtual inherited
Implemented in giraffe::gdl::DataLink.
Referenced by giraffe::gdl::AprsTelemetrySender::sendMetadataStateMachine(), and giraffe::AprsManager::sendOnAirDefinitionPackets().
sendTelemetryParameterNames()
virtual bool giraffe::gdl::IDataLink::sendTelemetryParameterNames (TelemetryData & telemetry_data) pure virtual inherited
Implemented in giraffe::gdl::DataLink.
Referenced by giraffe::gdl::AprsTelemetrySender::sendMetadataStateMachine(), and giraffe::AprsManager::sendOnAirDefinitionPackets().
sendTelemetryUnitsAndLabels()
virtual bool giraffe::gdl::IDataLink::sendTelemetryUnitsAndLabels (TelemetryData & telemetry_data) pure virtual inherited
Implemented in giraffe::gdl::DataLink.
Referenced by giraffe::gdl::AprsTelemetrySender::sendMetadataStateMachine(), and giraffe::AprsManager::sendOnAirDefinitionPackets().
sendTelemetryBitSense()
virtual bool giraffe::gdl::IDataLink::sendTelemetryBitSense (TelemetryData & telemetry_data) pure virtual inherited
Implemented in giraffe::gdl::DataLink.
Referenced by giraffe::gdl::AprsTelemetrySender::sendMetadataStateMachine(), and giraffe::AprsManager::sendOnAirDefinitionPackets().
Member Data Documentation
stats_
gdl::Statistics MockIDataLink::stats_ {} private
Referenced by getStatistics().
config_
gdl::Config MockIDataLink::config_ {false} private
Referenced by getConfig().
telemetry_data_
gdl::IDataLink::TelemetryData MockIDataLink::telemetry_data_ {} private
Referenced by getTelemetryData(), and updateTelemetryData().