Giraffe: modules::TelemetryModule Class Reference
modules::TelemetryModule Class Reference
#include <telemetry_module.hpp>
Public Member Functions
TelemetryModule (data::SharedData &shared_data, cfg::Configuration &config)
~TelemetryModule () override=default
bool addCommand (const cmd::Command &command)
Public wrapper for adding a command to the command queue.
node::Status getStatus () const
Returns the status of the module.
void start ()
Starts a thread to run the module.
void stop ()
Stops the module by setting the stop flag to true and joining the runner thread.
Protected Member Functions
template<typename T >
void data (data::DataId identifier, T value, int precision=2)
Used internally in the module. This function adds a data to the data stream.
void debug (std::string info)
Used internally for debug messages.
void error (DiagnosticId log_id, int info)
Same as the other error function, but takes an int instead of a string.
void error (DiagnosticId, std::string info="")
Used internally in the module. This function adds an error to the log stream. It is used to log errors that occur in the module.
void info (std::string info="")
Used internally in the module. This function adds a info message to the log stream.
void setStatus (const node::Status status)
void sleep ()
Sleeps the module for the sleep interval.
bool stopRequested () const
Returns true if the stop flag is set to true.
virtual void updateLocalConfig ()
Protected Attributes
cfg::Configuration & configuration_
modules::MetaData metadata_
data::SharedData & shared_data_
Private Member Functions
uint32_t getNextMessageId ()
void loop () override
Continually called at a rate set by the sleep interval.
void processCommand (const cmd::Command &command)
Process commands that are received from the flight runner.
void processTelemetryMessageQueue ()
Called if there is a message in the receive queue. Pops one message and processes it.
void reportDescent ()
Called when the flight computer detects that it is descending. If the data link is connected, it will send a message to the ground station.
void runner ()
This is the main function for each module.
void sendAprsPositionPacket (bool force_send=false)
This function will only send a packet if it is time to send one. If not, it will just return immediately.
void sendSstvImage ()
Send an SSTV image.
void shutdown () override
Called only once at shutdown.
void startup () override
This function is called when the module is started.
Private Attributes
bst::Timer aprs_manager_data_update_timer_ {}
The update rate of the APRS Manager.
bst::Timer aprs_position_packet_timer_ {}
giraffe::AprsManager aprs_telemetry_manager_
The APRS Telemetry Data Manager for managing APRS telemetry packets and all of the data that goes into them.
cmd::CommandQueue command_queue_
The command queue for the module.
giraffe::gdl::DataLink gdl_ {gdl_config_}
The Data Link used for telemetry.
giraffe::gdl::Config gdl_config_ {false}
The configuration for the data link.
std::string last_received_message_ = ""
uint32_t message_id_ = 0
std::shared_ptr< giraffe::gdl::PhysicalLayer > physical_layer_ = nullptr
A software radio for the data link that can be used in place of a physical radio. It is mostly just stubbed out.
std::thread runner_thread_
The thread that runs runner().
std::atomic< node::Status > status_ = node::Status::UNKNOWN
The status of the module.
std::atomic< bool > stop_flag_ = true
The stop flag is used to stop the module.
int total_messages_received_ = 0
int total_messages_sent_ = 0
Constructor & Destructor Documentation
TelemetryModule()
modules::TelemetryModule::TelemetryModule (data::SharedData & shared_data, cfg::Configuration & config) inline
~TelemetryModule()
modules::TelemetryModule::~TelemetryModule () override default
Member Function Documentation
startup()
void modules::TelemetryModule::startup () override private virtual
This function is called when the module is started.
This is overridden by the module implementation. Called only once at startup.
Reimplemented from modules::Module.
References aprs_position_packet_timer_, modules::Module::configuration_, giraffe::gdl::DataLink::enable(), modules::Module::error(), gdl_, gdl_config_, physical_layer_, giraffe::gdl::Config::setCallSign(), giraffe::gdl::DataLink::setPhysicalLayer(), giraffe::gdl::Config::setRemoteCallSign(), giraffe::gdl::Config::setRemoteSSID(), and giraffe::gdl::Config::setSSID().
loop()
void modules::TelemetryModule::loop () override private virtual
Continually called at a rate set by the sleep interval.
Reimplemented from modules::Module.
References data::blocks::TelemetryModuleStats::exchange_queue_size.
shutdown()
void modules::TelemetryModule::shutdown () override private virtual
Called only once at shutdown.
Reimplemented from modules::Module.
processTelemetryMessageQueue()
void modules::TelemetryModule::processTelemetryMessageQueue () private
Called if there is a message in the receive queue. Pops one message and processes it.
Todo:
log an error and respond to the telemetry packet
References giraffe::gdl::Message::getData(), giraffe::gdl::Message::getIdentifierString(), giraffe::gdl::Message::getType(), giraffe::gdl::Message::LOCATION, cmd::parseCommandString(), and node::TELEMETRY_MODULE.
sendAprsPositionPacket()
void modules::TelemetryModule::sendAprsPositionPacket (bool force_send = false) private
This function will only send a packet if it is time to send one. If not, it will just return immediately.
Parameters
force_send - If true, the packet will be sent regardless of the timer or data validity. This is used for an external trigger/user command.
Todo:
log an error
Todo:
Maybe use the last valid GPS frame instead, but first there needs to be a time stamp as to when this one was generated. I have a fear of DST and time zones causing issues here.
Todo:
log an error
Todo:
log an error
Todo:
log a warning but maybe still send the packet?
Todo:
Fix this time code!
Warning
Time code in not implemented for APRS position packets.
Todo:
put force_send_error in the APRS comment field
References data::ERROR, data::FIX_2D, data::NO_FIX, giraffe::gdl::Message::setLocation(), and giraffe::gdl::Message::Location::time_code.
sendSstvImage()
void modules::TelemetryModule::sendSstvImage () private
Send an SSTV image.
Only functions if SSTV is configured. Requires a camera to be connected.
References giraffe::gdl::Message::Image::path, and giraffe::gdl::Message::setImageMessage().
reportDescent()
void modules::TelemetryModule::reportDescent () private
Called when the flight computer detects that it is descending. If the data link is connected, it will send a message to the ground station.
Todo:
Capture the return values of sendText and broadcastText and set a error if they fail.
Todo:
report an error
processCommand()
void modules::TelemetryModule::processCommand (const cmd::Command & command) private virtual
Process commands that are received from the flight runner.
Parameters
command - The command to process.
Reimplemented from modules::Module.
References cmd::Command::command_id.
getNextMessageId()
uint32_t modules::TelemetryModule::getNextMessageId () inline private
References message_id_.
start()
void modules::Module::start () inherited
Starts a thread to run the module.
This function will start a thread to run a module, but only if the module is not already running. If the module is already running, an error will be logged. It also resets the stop flag to false.
References modules::Module::runner(), node::RUNNING, and node::SLEEPING.
Referenced by DataModuleTests::cycleDataModule(), ExtensionModuleTests::cycleExtensionModule(), modules::ConsoleModule::startup(), and FlightRunner::toggleModule().
stop()
void modules::Module::stop () inherited
Stops the module by setting the stop flag to true and joining the runner thread.
This function will stop the module by setting the stop flag to true and joining the runner thread. It also sets the status to STOPPED. If a module is in the sleep state, it will only stop after the next loop. This means that the sleep interval plus the time it takes to run the loop and shutdown will be the total time it takes to stop the module.
References node::STOPPED, and node::STOPPING.
Referenced by FlightRunner::~FlightRunner(), DataModuleTests::cycleDataModule(), ExtensionModuleTests::cycleExtensionModule(), and FlightRunner::toggleModule().
getStatus()
node::Status modules::Module::getStatus () const inherited
Returns the status of the module.
Returns
Returns the status of the module.
See also
node::Status
addCommand()
bool modules::Module::addCommand (const cmd::Command & command) inline inherited
Public wrapper for adding a command to the command queue.
See also
cmd::CommandQueue
References cmd::CommandQueue::addCommand(), and modules::Module::command_queue_.
Referenced by FlightRunner::routeCommand().
updateLocalConfig()
virtual void modules::Module::updateLocalConfig () inline protected virtual inherited
Reimplemented in modules::ExtensionModule.
References giraffe_assert.
setStatus()
void modules::Module::setStatus (const node::Status status) protected inherited
Todo:
Sets the status of the module and reports it to the data stream.
error() [1/2]
void modules::Module::error (DiagnosticId log_id, std::string info = "") protected inherited
Used internally in the module. This function adds an error to the log stream. It is used to log errors that occur in the module.
Uses the module meta data to add the correct node identification.
Parameters
log_id The log id of the error.
info Optional information to add to the log.
Referenced by modules::DataModule::DataModule(), modules::ExtensionModule::addExtension(), modules::ExtensionModule::addPreConfiguredExtension(), modules::ExtensionModule::processCommand(), modules::ExtensionModule::startup(), and startup().
error() [2/2]
void modules::Module::error (DiagnosticId log_id, int info) protected inherited
Same as the other error function, but takes an int instead of a string.
info()
void modules::Module::info (std::string info = "") protected inherited
Used internally in the module. This function adds a info message to the log stream.
Uses the module meta data to add the correct node identification.
Parameters
info info string to add to the log.
Referenced by modules::ExtensionModule::addExtension(), modules::ExtensionModule::processCommand(), modules::ExtensionModule::restartState(), and modules::ExtensionModule::startup().
debug()
void modules::Module::debug (std::string info) protected inherited
Used internally for debug messages.
Parameters
info The debug message.
data()
template<typename T > template void modules::Module::data< double > (data::DataId identifier, T value, int precision = 2) protected inherited
Used internally in the module. This function adds a data to the data stream.
Template Parameters
T a non-string type that can be converted to a string with std::to_string
Parameters
identifier The data identifier.
value The value of the data.
precision The precision (if the type is a float or double)
stopRequested()
bool modules::Module::stopRequested () const inline protected inherited
Returns true if the stop flag is set to true.
Used internally in a module to check if the module should stop in between large tasks.
Returns
true
false
References modules::Module::stop_flag_.
sleep()
void modules::Module::sleep () protected inherited
Sleeps the module for the sleep interval.
Default of 1 second, this is blocking.
runner()
void modules::Module::runner () private inherited
This is the main function for each module.
This function is what runs in the thread. It calls startup, then loops until the stop flag is set to true. It then calls shutdown.
It also handles the command queue.
References node::RUNNING, node::SLEEPING, node::STARTING, node::STOPPED, and node::STOPPING.
Referenced by modules::Module::start().
Member Data Documentation
total_messages_sent_
int modules::TelemetryModule::total_messages_sent_ = 0 private
total_messages_received_
int modules::TelemetryModule::total_messages_received_ = 0 private
last_received_message_
std::string modules::TelemetryModule::last_received_message_ = "" private
aprs_position_packet_timer_
bst::Timer modules::TelemetryModule::aprs_position_packet_timer_ {} private
Referenced by startup().
message_id_
uint32_t modules::TelemetryModule::message_id_ = 0 private
Referenced by getNextMessageId().
gdl_config_
giraffe::gdl::Config modules::TelemetryModule::gdl_config_ {false} private
The configuration for the data link.
Referenced by startup().
physical_layer_
std::shared_ptr<giraffe::gdl::PhysicalLayer> modules::TelemetryModule::physical_layer_ = nullptr private
A software radio for the data link that can be used in place of a physical radio. It is mostly just stubbed out.
An optional SA868 radio that can be used in place of the software radio. This will be populated if it's selected in the configuration.
Referenced by startup().
gdl_
giraffe::gdl::DataLink modules::TelemetryModule::gdl_ {gdl_config_} private
The Data Link used for telemetry.
Referenced by startup().
aprs_manager_data_update_timer_
bst::Timer modules::TelemetryModule::aprs_manager_data_update_timer_ {} private
The update rate of the APRS Manager.
aprs_telemetry_manager_
giraffe::AprsManager modules::TelemetryModule::aprs_telemetry_manager_ private
Initial value:
{
      shared_data_, configuration_, gdl_, aprs_manager_data_update_timer_}
The APRS Telemetry Data Manager for managing APRS telemetry packets and all of the data that goes into them.
metadata_
modules::MetaData modules::Module::metadata_ protected inherited
shared_data_
data::SharedData& modules::Module::shared_data_ protected inherited
Referenced by modules::ExtensionModule::loop(), and modules::ExtensionModule::startup().
configuration_
cfg::Configuration& modules::Module::configuration_ protected inherited
Referenced by modules::DataModule::DataModule(), modules::ExtensionModule::addPreConfiguredExtension(), modules::ExtensionModule::startup(), startup(), and modules::ExtensionModule::updateLocalConfig().
status_
std::atomic<node::Status> modules::Module::status_ = node::Status::UNKNOWN private inherited
The status of the module.
See also
node::Status
stop_flag_
std::atomic<bool> modules::Module::stop_flag_ = true private inherited
The stop flag is used to stop the module.
Set to true to stop the module upon a call to stop().
Referenced by modules::Module::stopRequested().
runner_thread_
std::thread modules::Module::runner_thread_ private inherited
The thread that runs runner().
command_queue_
cmd::CommandQueue modules::Module::command_queue_ private inherited
The command queue for the module.
See also
cmd::CommandQueue
Referenced by modules::Module::addCommand().