Giraffe: modules::ExtensionModule Class Reference
modules::ExtensionModule Class Reference
#include <extension_module.hpp>
Classes
struct ExtContainer
The container that holds the information about an extension and the extension itself.
Public Member Functions
ExtensionModule (data::SharedData &, cfg::Configuration &)
~ExtensionModule () override=default
bool addCommand (const cmd::Command &command)
Public wrapper for adding a command to the command queue.
node::Status getStatus () const
Returns the status of the module.
void start ()
Starts a thread to run the module.
void stop ()
Stops the module by setting the stop flag to true and joining the runner thread.
Protected Member Functions
template<typename T >
void data (data::DataId identifier, T value, int precision=2)
Used internally in the module. This function adds a data to the data stream.
void debug (std::string info)
Used internally for debug messages.
void error (DiagnosticId log_id, int info)
Same as the other error function, but takes an int instead of a string.
void error (DiagnosticId, std::string info="")
Used internally in the module. This function adds an error to the log stream. It is used to log errors that occur in the module.
void info (std::string info="")
Used internally in the module. This function adds a info message to the log stream.
void setStatus (const node::Status status)
void sleep ()
Sleeps the module for the sleep interval.
bool stopRequested () const
Returns true if the stop flag is set to true.
Protected Attributes
cfg::Configuration & configuration_
modules::MetaData metadata_
data::SharedData & shared_data_
Private Types
enum class ExtAction {
UNKNOWN , DISABLE , START , RUN ,
STOP , RESTART , ERROR_START , ERROR_STOP ,
ERROR_RESTART , ERROR_DISABLE
}
The action determines the targeted state of the extension.
Private Member Functions
void addExtension (const cfg::ExtensionMetadata &extension_metadata)
void addPreConfiguredExtension (const std::string &ext_option)
std::optional< ExtContainer > createExtension (const cfg::ExtensionMetadata &)
void disableState (ExtContainer &)
void errorDisableState (ExtContainer &)
void errorRestartState (ExtContainer &)
void errorStartState (ExtContainer &)
void loop () override
Continually called at a rate set by the sleep interval.
void processCommand (const cmd::Command &) override
Called when a command is received.
void restartState (ExtContainer &)
void runner ()
This is the main function for each module.
void runState (ExtContainer &)
void shutdown () override
Called only once at shutdown.
void startState (ExtContainer &)
void startup () override
This function is called when the module is started.
void stateMachine (ExtContainer &)
void stopState (ExtContainer &)
void unknownState (ExtContainer &)
void updateLocalConfig () override
Private Attributes
cmd::CommandQueue command_queue_
The command queue for the module.
std::vector< cfg::ExtensionMetadata > extension_metadata_ {}
extension::ExtensionResources extension_resources_
std::vector< ExtContainer > extensions_ {}
int max_restart_attempts_ = 0
int max_startup_attempts_ = 0
int restart_delay_ = 0
std::thread runner_thread_
The thread that runs runner().
int startup_timeout_ = 0
data::blocks::ExtensionModuleStats stats_ {}
std::atomic< node::Status > status_ = node::Status::UNKNOWN
The status of the module.
int status_polling_interval_ = 0
bst::Timer status_polling_timer_ {}
std::atomic< bool > stop_flag_ = true
The stop flag is used to stop the module.
Member Enumeration Documentation
ExtAction
enum modules::ExtensionModule::ExtAction strong private
The action determines the targeted state of the extension.
This is how the extension module keeps track of what it is trying to do with an extension.
See also
extension_module_actions.puml
Enumerator
UNKNOWN
DISABLE
START
RUN
STOP
RESTART
ERROR_START
ERROR_STOP
ERROR_RESTART
ERROR_DISABLE
Constructor & Destructor Documentation
ExtensionModule()
modules::ExtensionModule::ExtensionModule (data::SharedData & shared_data, cfg::Configuration & config)
~ExtensionModule()
modules::ExtensionModule::~ExtensionModule () override default
Member Function Documentation
startup()
void modules::ExtensionModule::startup () override private virtual
This function is called when the module is started.
This is overridden by the module implementation. Called only once at startup.
Reimplemented from modules::Module.
References addExtension(), giraffe::StatusLedState::BLINK, modules::Module::configuration_, createExtension(), modules::Module::error(), extensions_, modules::Module::info(), extension::K_SIMULATED_EXTENSIONS_VEC, giraffe::StatusLedState::setBlue(), modules::Module::shared_data_, data::SharedData::status_led, and updateLocalConfig().
loop()
void modules::ExtensionModule::loop () override private virtual
Continually called at a rate set by the sleep interval.
Reimplemented from modules::Module.
References data::SharedData::blocks, extension_metadata_, data::SharedBlocks::extension_module_stats, extensions_, node::K_ACTIVE_STATUSES, data::blocks::ExtensionModuleStats::num_active, data::blocks::ExtensionModuleStats::num_configured, data::blocks::ExtensionModuleStats::num_inactive, giraffe::StatusLedState::OFF, giraffe::StatusLedState::setBlue(), modules::Module::shared_data_, stateMachine(), stats_, data::SharedData::status_led, and status_polling_timer_.
shutdown()
void modules::ExtensionModule::shutdown () override private virtual
Called only once at shutdown.
Reimplemented from modules::Module.
References extensions_, and node::K_ACTIVE_STATUSES.
processCommand()
void modules::ExtensionModule::processCommand (const cmd::Command & command) override private virtual
Called when a command is received.
Parameters
command
Reimplemented from modules::Module.
References addPreConfiguredExtension(), cmd::Command::command_id, modules::Module::error(), and cmd::Command::str_arg.
updateLocalConfig()
void modules::ExtensionModule::updateLocalConfig () override private virtual
Todo:
Implement the loading/updating of extensions
Reimplemented from modules::Module.
References modules::Module::configuration_, extension_metadata_, max_restart_attempts_, max_startup_attempts_, restart_delay_, startup_timeout_, status_polling_interval_, and status_polling_timer_.
Referenced by addPreConfiguredExtension(), and startup().
addExtension()
void modules::ExtensionModule::addExtension (const cfg::ExtensionMetadata & extension_metadata) private
References createExtension(), modules::Module::error(), extensions_, modules::Module::info(), and cfg::ExtensionMetadata::name.
Referenced by addPreConfiguredExtension(), and startup().
createExtension()
std::optional< ExtensionModule::ExtContainer > modules::ExtensionModule::createExtension (const cfg::ExtensionMetadata & meta) private
References BME280, extension_resources_, giraffe_assert, restart_delay_, startup_timeout_, and cfg::ExtensionMetadata::type.
Referenced by addExtension(), and startup().
addPreConfiguredExtension()
void modules::ExtensionModule::addPreConfiguredExtension (const std::string & ext_option) private
References addExtension(), BME280, modules::Module::configuration_, modules::Module::error(), extension_metadata_, and updateLocalConfig().
Referenced by processCommand().
stateMachine()
void modules::ExtensionModule::stateMachine (ExtContainer & ext) private
References modules::ExtensionModule::ExtContainer::action, DISABLE, disableState(), ERROR_RESTART, ERROR_START, ERROR_STOP, errorRestartState(), errorStartState(), giraffe_assert, RESTART, restartState(), RUN, runState(), START, startState(), STOP, stopState(), UNKNOWN, and unknownState().
Referenced by loop().
unknownState()
void modules::ExtensionModule::unknownState (ExtContainer & ext) private
References modules::ExtensionModule::ExtContainer::action, DISABLE, cfg::ExtensionMetadata::enabled, modules::ExtensionModule::ExtContainer::metadata, START, modules::ExtensionModule::ExtContainer::startup_shutdown_timer, and startup_timeout_.
Referenced by stateMachine().
disableState()
void modules::ExtensionModule::disableState (ExtContainer & ext) private
Referenced by stateMachine().
startState()
void modules::ExtensionModule::startState (ExtContainer & ext) private
References modules::ExtensionModule::ExtContainer::action, node::ERROR, ERROR_RESTART, ERROR_START, modules::ExtensionModule::ExtContainer::extension, giraffe_assert, RUN, node::RUNNING, node::STARTING, modules::ExtensionModule::ExtContainer::startup_shutdown_timer, and node::STOPPED.
Referenced by stateMachine().
runState()
void modules::ExtensionModule::runState (ExtContainer & ext) private
Todo:
watchdog timer?
References modules::ExtensionModule::ExtContainer::action, node::ERROR, ERROR_RESTART, modules::ExtensionModule::ExtContainer::extension, giraffe_assert, and node::RUNNING.
Referenced by stateMachine().
stopState()
void modules::ExtensionModule::stopState (ExtContainer & ext) private
Todo:
handle the fault code?
References node::ERROR, modules::ExtensionModule::ExtContainer::extension, giraffe_assert, node::RUNNING, modules::ExtensionModule::ExtContainer::startup_shutdown_timer, node::STOPPED, and node::STOPPING.
Referenced by stateMachine().
restartState()
void modules::ExtensionModule::restartState (ExtContainer & ext) private
References giraffe_assert.
Referenced by stateMachine().
errorStartState()
void modules::ExtensionModule::errorStartState (ExtContainer & ext) private
Todo:
handle the fault code
Todo:
add delay
References modules::ExtensionModule::ExtContainer::action, node::ERROR, ERROR_DISABLE, modules::ExtensionModule::ExtContainer::extension, max_startup_attempts_, START, and modules::ExtensionModule::ExtContainer::startup_attempts.
Referenced by stateMachine().
errorRestartState()
void modules::ExtensionModule::errorRestartState (ExtContainer & ext) private
Referenced by stateMachine().
errorDisableState()
void modules::ExtensionModule::errorDisableState (ExtContainer & ext) private
start()
void modules::Module::start () inherited
Starts a thread to run the module.
This function will start a thread to run a module, but only if the module is not already running. If the module is already running, an error will be logged. It also resets the stop flag to false.
References modules::Module::runner(), node::RUNNING, and node::SLEEPING.
Referenced by DataModuleTests::cycleDataModule(), ExtensionModuleTests::cycleExtensionModule(), and FlightRunner::toggleModule().
stop()
void modules::Module::stop () inherited
Stops the module by setting the stop flag to true and joining the runner thread.
This function will stop the module by setting the stop flag to true and joining the runner thread. It also sets the status to STOPPED. If a module is in the sleep state, it will only stop after the next loop. This means that the sleep interval plus the time it takes to run the loop and shutdown will be the total time it takes to stop the module.
References node::STOPPED, and node::STOPPING.
Referenced by FlightRunner::~FlightRunner(), DataModuleTests::cycleDataModule(), ExtensionModuleTests::cycleExtensionModule(), and FlightRunner::toggleModule().
getStatus()
node::Status modules::Module::getStatus () const inherited
Returns the status of the module.
Returns
Returns the status of the module.
See also
node::Status
addCommand()
bool modules::Module::addCommand (const cmd::Command & command) inline inherited
Public wrapper for adding a command to the command queue.
See also
cmd::CommandQueue
References cmd::CommandQueue::addCommand(), and modules::Module::command_queue_.
Referenced by FlightRunner::routeCommand().
setStatus()
void modules::Module::setStatus (const node::Status status) protected inherited
Todo:
Sets the status of the module and reports it to the data stream.
error() [1/2]
void modules::Module::error (DiagnosticId log_id, std::string info = "") protected inherited
Used internally in the module. This function adds an error to the log stream. It is used to log errors that occur in the module.
Uses the module meta data to add the correct node identification.
Parameters
log_id The log id of the error.
info Optional information to add to the log.
Referenced by modules::DataModule::DataModule(), addExtension(), addPreConfiguredExtension(), processCommand(), and startup().
error() [2/2]
void modules::Module::error (DiagnosticId log_id, int info) protected inherited
Same as the other error function, but takes an int instead of a string.
References util::to_string().
info()
void modules::Module::info (std::string info = "") protected inherited
Used internally in the module. This function adds a info message to the log stream.
Uses the module meta data to add the correct node identification.
Parameters
info info string to add to the log.
Referenced by addExtension(), and startup().
debug()
void modules::Module::debug (std::string info) protected inherited
Used internally for debug messages.
Parameters
info The debug message.
data()
template<typename T > template void modules::Module::data< double > (data::DataId identifier, T value, int precision = 2) protected inherited
Used internally in the module. This function adds a data to the data stream.
Template Parameters
T a non-string type that can be converted to a string with std::to_string
Parameters
identifier The data identifier.
value The value of the data.
precision The precision (if the type is a float or double)
References util::to_string().
stopRequested()
bool modules::Module::stopRequested () const inline protected inherited
Returns true if the stop flag is set to true.
Used internally in a module to check if the module should stop in between large tasks.
Returns
true
false
References modules::Module::stop_flag_.
sleep()
void modules::Module::sleep () protected inherited
Sleeps the module for the sleep interval.
Default of 1 second, this is blocking.
runner()
void modules::Module::runner () private inherited
This is the main function for each module.
This function is what runs in the thread. It calls startup, then loops until the stop flag is set to true. It then calls shutdown.
It also handles the command queue.
References node::RUNNING, node::SLEEPING, node::STARTING, node::STOPPED, and node::STOPPING.
Referenced by modules::Module::start().
Member Data Documentation
extension_resources_
extension::ExtensionResources modules::ExtensionModule::extension_resources_ private
Referenced by createExtension().
extensions_
std::vector<ExtContainer> modules::ExtensionModule::extensions_ {} private
Referenced by addExtension(), loop(), shutdown(), and startup().
extension_metadata_
std::vector<cfg::ExtensionMetadata> modules::ExtensionModule::extension_metadata_ {} private
Referenced by addPreConfiguredExtension(), loop(), and updateLocalConfig().
status_polling_timer_
bst::Timer modules::ExtensionModule::status_polling_timer_ {} private
Referenced by loop(), and updateLocalConfig().
stats_
data::blocks::ExtensionModuleStats modules::ExtensionModule::stats_ {} private
Referenced by loop().
status_polling_interval_
int modules::ExtensionModule::status_polling_interval_ = 0 private
Referenced by updateLocalConfig().
max_restart_attempts_
int modules::ExtensionModule::max_restart_attempts_ = 0 private
Referenced by updateLocalConfig().
restart_delay_
int modules::ExtensionModule::restart_delay_ = 0 private
Referenced by createExtension(), and updateLocalConfig().
startup_timeout_
int modules::ExtensionModule::startup_timeout_ = 0 private
Referenced by createExtension(), unknownState(), and updateLocalConfig().
max_startup_attempts_
int modules::ExtensionModule::max_startup_attempts_ = 0 private
Referenced by errorStartState(), and updateLocalConfig().
metadata_
modules::MetaData modules::Module::metadata_ protected inherited
shared_data_
data::SharedData& modules::Module::shared_data_ protected inherited
Referenced by loop(), and startup().
configuration_
cfg::Configuration& modules::Module::configuration_ protected inherited
Referenced by modules::DataModule::DataModule(), addPreConfiguredExtension(), startup(), and updateLocalConfig().
status_
std::atomic<node::Status> modules::Module::status_ = node::Status::UNKNOWN private inherited
The status of the module.
See also
node::Status
stop_flag_
std::atomic<bool> modules::Module::stop_flag_ = true private inherited
The stop flag is used to stop the module.
Set to true to stop the module upon a call to stop().
Referenced by modules::Module::stopRequested().
runner_thread_
std::thread modules::Module::runner_thread_ private inherited
The thread that runs runner().
command_queue_
cmd::CommandQueue modules::Module::command_queue_ private inherited
The command queue for the module.
See also
cmd::CommandQueue
Referenced by modules::Module::addCommand().