Giraffe: giraffe::gdl::GdlServer Class Reference
giraffe::gdl::GdlServer Class Reference
The Giraffe Data Link Terminal.
#include <gdl_server.hpp>
Public Member Functions
GdlServer ()=default
~GdlServer ()=default
int run ()
void stop ()
Private Member Functions
json getConfigJson ()
uint32_t getNewBroadcastId ()
std::string getNextResponseId ()
void handleRequestConfig ()
void handleRequestLog ()
void handleRequestReceivedMessages ()
void handleRequestSentMessages ()
void handleRequestStatus ()
void handleSetConfig (const json &request_data)
void handleSetDisableReceiver ()
void handleSetEnableReceiver ()
void handleSetNewBroadcast (const json &request_data)
void handleSetNewExchange (const json &request_data)
void handleSetResetConfig ()
void handleSetRestart ()
int loadConfig ()
void routeRequest (const std::string &rsc)
void routeSet (const protocol::Message &received_msg)
bool saveConfig ()
Attempts to save the current configuration to the config file.
bool sendMessage (const gdl::Message &msg)
void sendResponseData (const json &data, const std::string &resource)
void sendResponseError (const std::string &error)
void sendResponseSuccess ()
bool setConfigFromJson (const json &config)
Set the configuration from a JSON object. Will use default values for any missing fields.
Private Attributes
sock::TcpSocketServer client_socket_ {}
bool data_link_enabled_ {true}
DataLink gdl_ {gdl_config_, physical_layer_}
Config gdl_config_ = Config(true)
uint32_t last_broadcast_id_ {1}
CommonLogger< 100 > log_ {LoggerLevel::INFO, true}
std::shared_ptr< SoftwarePhysicalLayer > physical_layer_
uint32_t protocol_id_ {1}
bool response_sent_ {false}
Used to check if a response has been sent to the client.
bool send_result_ {false}
Set in sendResponseData() and sendResponseError() to indicate that the client is not connected.
std::queue< gdl::Message > sent_messages_ {}
int server_port_ {9557}
sock::TcpSocketServer server_socket_ {}
bool stop_flag_ {false}
Static Private Attributes
static const size_t MAX_SENT_MESSAGES {50}
Detailed Description
The Giraffe Data Link Terminal.
This contains a simple terminal for interacting with the GDL (or at least it did). However, not it is primarily interfaced with the GGS via a TCP socket.
Constructor & Destructor Documentation
GdlServer()
giraffe::gdl::GdlServer::GdlServer () default
~GdlServer()
giraffe::gdl::GdlServer::~GdlServer () default
Member Function Documentation
run()
int giraffe::gdl::GdlServer::run ()
Todo:
There might be a better way to do this.
References sock::TcpSocketServer::accept(), client_socket_, data_link_enabled_, giraffe::CommonLogger< LOG_SIZE >::debug(), giraffe::gdl::DataLink::disable(), giraffe::gdl::DataLink::enable(), giraffe::CommonLogger< LOG_SIZE >::error(), gdl_, sock::TcpSocketServer::getClientAddress(), giraffe::CommonLogger< LOG_SIZE >::info(), sock::TcpSocketServer::init(), giraffe::gdl::DataLink::isEnabled(), loadConfig(), log_, protocol::parseMessage(), sock::TcpSocketServer::receive(), protocol::REQ, response_sent_, routeRequest(), routeSet(), protocol::Message::rsc, send_result_, server_port_, server_socket_, protocol::SET, stop_flag_, util::to_string(), protocol::Message::typ, and giraffe::CommonLogger< LOG_SIZE >::warn().
Referenced by main().
stop()
void giraffe::gdl::GdlServer::stop () inline
References client_socket_, sock::TcpSocketServer::close(), giraffe::CommonLogger< LOG_SIZE >::info(), log_, server_socket_, and stop_flag_.
Referenced by signalHandler().
loadConfig()
int giraffe::gdl::GdlServer::loadConfig () private
References config, giraffe::file_paths::createGiraffeDirIfNotExists(), giraffe::CommonLogger< LOG_SIZE >::debug(), giraffe::CommonLogger< LOG_SIZE >::error(), giraffe::file_paths::getGdlServerConfigFilePath(), giraffe::CommonLogger< LOG_SIZE >::info(), log_, saveConfig(), setConfigFromJson(), and giraffe::CommonLogger< LOG_SIZE >::warn().
Referenced by run().
saveConfig()
bool giraffe::gdl::GdlServer::saveConfig () private
Attempts to save the current configuration to the config file.
Only need to check the return value for reporting reasons. (request)
Returns
true - The configuration was saved successfully.
false - The configuration was not saved successfully. Error in log.
References config, giraffe::CommonLogger< LOG_SIZE >::debug(), giraffe::CommonLogger< LOG_SIZE >::error(), getConfigJson(), giraffe::file_paths::getGdlServerConfigFilePath(), and log_.
Referenced by handleSetConfig(), and loadConfig().
getConfigJson()
json giraffe::gdl::GdlServer::getConfigJson () private
References config, gdl_config_, giraffe::gdl::Config::getCallSign(), giraffe::CommonLogger< LOG_SIZE >::getLevel(), giraffe::CommonLogger< LOG_SIZE >::getPrintToStdout(), giraffe::gdl::Config::getProactiveKeepAlive(), giraffe::gdl::Config::getRemoteCallSign(), giraffe::gdl::Config::getRemoteSSID(), giraffe::gdl::Config::getSSID(), log_, server_port_, and giraffe::to_string().
Referenced by handleRequestConfig(), and saveConfig().
setConfigFromJson()
bool giraffe::gdl::GdlServer::setConfigFromJson (const json & config) private
Set the configuration from a JSON object. Will use default values for any missing fields.
Parameters
config - The JSON object to use for configuration.
Returns
true - The JSON was fully parsed and valid. Configuration was set.
false - The JSON was invalid. Configuration may be partially set.
References config, giraffe::DEBUG, giraffe::ERROR, gdl_config_, giraffe::INFO, log_, server_port_, giraffe::gdl::Config::setCallSign(), giraffe::CommonLogger< LOG_SIZE >::setLevel(), giraffe::CommonLogger< LOG_SIZE >::setPrintToStdout(), giraffe::gdl::Config::setProactiveKeepAlive(), giraffe::gdl::Config::setRemoteCallSign(), giraffe::gdl::Config::setRemoteSSID(), giraffe::gdl::Config::setSSID(), giraffe::WARN, and giraffe::CommonLogger< LOG_SIZE >::warn().
Referenced by handleSetConfig(), and loadConfig().
sendResponseData()
void giraffe::gdl::GdlServer::sendResponseData (const json & data, const std::string & resource) private
References client_socket_, protocol::createResponseMessage(), protocol::GDL, protocol::Message::getJsonString(), getNextResponseId(), protocol::GGS, protocol::GOOD, response_sent_, sock::TcpSocketServer::send(), and send_result_.
Referenced by handleRequestConfig(), handleRequestLog(), handleRequestReceivedMessages(), handleRequestSentMessages(), and handleRequestStatus().
sendResponseError()
void giraffe::gdl::GdlServer::sendResponseError (const std::string & error) private
References client_socket_, protocol::createResponseMessage(), protocol::ERROR, protocol::GDL, protocol::Message::getJsonString(), getNextResponseId(), protocol::GGS, response_sent_, sock::TcpSocketServer::send(), and send_result_.
Referenced by handleSetConfig(), handleSetDisableReceiver(), handleSetEnableReceiver(), handleSetNewBroadcast(), handleSetNewExchange(), handleSetResetConfig(), handleSetRestart(), routeRequest(), and routeSet().
sendResponseSuccess()
void giraffe::gdl::GdlServer::sendResponseSuccess () private
References client_socket_, protocol::createResponseMessage(), protocol::GDL, protocol::Message::getJsonString(), getNextResponseId(), protocol::GGS, protocol::GOOD, response_sent_, sock::TcpSocketServer::send(), and send_result_.
Referenced by handleSetConfig(), handleSetNewBroadcast(), and handleSetNewExchange().
routeRequest()
void giraffe::gdl::GdlServer::routeRequest (const std::string & rsc) private
References handleRequestConfig(), handleRequestLog(), handleRequestReceivedMessages(), handleRequestSentMessages(), handleRequestStatus(), and sendResponseError().
Referenced by run().
handleRequestConfig()
void giraffe::gdl::GdlServer::handleRequestConfig () private
References getConfigJson(), and sendResponseData().
Referenced by routeRequest().
handleRequestStatus()
void giraffe::gdl::GdlServer::handleRequestStatus () private
References giraffe::gdl::Statistics::broadcast_queue_size, giraffe::gdl::DataLink::DISABLED, giraffe::gdl::Statistics::downlink_connected, giraffe::gdl::Statistics::exchange_queue_size, gdl_, giraffe::CommonLogger< LOG_SIZE >::getLogQueueSize(), giraffe::gdl::DataLink::getStatistics(), giraffe::gdl::DataLink::getStatus(), giraffe::gdl::Statistics::last_message_received, log_, giraffe::gdl::Statistics::network_layer_latency_ms, giraffe::gdl::Statistics::position_packets_received, giraffe::gdl::Statistics::received_queue_size, sendResponseData(), sent_messages_, giraffe::gdl::Statistics::signal_to_noise_ratio, giraffe::gdl::Statistics::telemetry_packets_received, giraffe::gdl::Statistics::total_messages_dropped, giraffe::gdl::Statistics::total_packets_received, giraffe::gdl::Statistics::total_packets_sent, giraffe::gdl::Statistics::uplink_connected, and giraffe::gdl::Statistics::volume.
Referenced by routeRequest().
handleRequestReceivedMessages()
void giraffe::gdl::GdlServer::handleRequestReceivedMessages () private
References gdl_, giraffe::gdl::Message::getJson(), giraffe::gdl::DataLink::messageAvailable(), giraffe::gdl::DataLink::receiveMessage(), and sendResponseData().
Referenced by routeRequest().
handleRequestSentMessages()
void giraffe::gdl::GdlServer::handleRequestSentMessages () private
References giraffe::gdl::Message::getJson(), sendResponseData(), and sent_messages_.
Referenced by routeRequest().
handleRequestLog()
void giraffe::gdl::GdlServer::handleRequestLog () private
References giraffe::LoggerEntry::getLevelString(), log_, giraffe::LoggerEntry::msg, giraffe::CommonLogger< LOG_SIZE >::popEntry(), sendResponseData(), and giraffe::LoggerEntry::time.
Referenced by routeRequest().
routeSet()
void giraffe::gdl::GdlServer::routeSet (const protocol::Message & received_msg) private
References protocol::Message::dat, handleSetConfig(), handleSetDisableReceiver(), handleSetEnableReceiver(), handleSetNewBroadcast(), handleSetNewExchange(), handleSetResetConfig(), handleSetRestart(), protocol::Message::rsc, and sendResponseError().
Referenced by run().
handleSetNewBroadcast()
void giraffe::gdl::GdlServer::handleSetNewBroadcast (const json & request_data) private
References getNewBroadcastId(), giraffe::CommonLogger< LOG_SIZE >::info(), log_, sendMessage(), sendResponseError(), sendResponseSuccess(), and giraffe::gdl::Message::setBroadcastMessage().
Referenced by routeSet().
handleSetNewExchange()
void giraffe::gdl::GdlServer::handleSetNewExchange (const json & request_data) private
References giraffe::CommonLogger< LOG_SIZE >::error(), getNewBroadcastId(), giraffe::CommonLogger< LOG_SIZE >::info(), log_, sendMessage(), sendResponseError(), sendResponseSuccess(), and giraffe::gdl::Message::setExchangeMessage().
Referenced by routeSet().
handleSetDisableReceiver()
void giraffe::gdl::GdlServer::handleSetDisableReceiver () private
References sendResponseError().
Referenced by routeSet().
handleSetEnableReceiver()
void giraffe::gdl::GdlServer::handleSetEnableReceiver () private
References sendResponseError().
Referenced by routeSet().
handleSetResetConfig()
void giraffe::gdl::GdlServer::handleSetResetConfig () private
References sendResponseError().
Referenced by routeSet().
handleSetRestart()
void giraffe::gdl::GdlServer::handleSetRestart () private
References sendResponseError().
Referenced by routeSet().
handleSetConfig()
void giraffe::gdl::GdlServer::handleSetConfig (const json & request_data) private
References giraffe::CommonLogger< LOG_SIZE >::info(), log_, saveConfig(), sendResponseError(), sendResponseSuccess(), and setConfigFromJson().
Referenced by routeSet().
getNewBroadcastId()
uint32_t giraffe::gdl::GdlServer::getNewBroadcastId () inline private
References last_broadcast_id_.
Referenced by handleSetNewBroadcast(), and handleSetNewExchange().
sendMessage()
bool giraffe::gdl::GdlServer::sendMessage (const gdl::Message & msg) inline private
References gdl_, log_, MAX_SENT_MESSAGES, giraffe::gdl::DataLink::sendMessage(), sent_messages_, and giraffe::CommonLogger< LOG_SIZE >::warn().
Referenced by handleSetNewBroadcast(), and handleSetNewExchange().
getNextResponseId()
std::string giraffe::gdl::GdlServer::getNextResponseId () inline private
References protocol_id_, and util::to_string().
Referenced by sendResponseData(), sendResponseError(), and sendResponseSuccess().
Member Data Documentation
stop_flag_
bool giraffe::gdl::GdlServer::stop_flag_ {false} private
Referenced by run(), and stop().
server_port_
int giraffe::gdl::GdlServer::server_port_ {9557} private
Referenced by getConfigJson(), run(), and setConfigFromJson().
data_link_enabled_
bool giraffe::gdl::GdlServer::data_link_enabled_ {true} private
Referenced by run().
server_socket_
sock::TcpSocketServer giraffe::gdl::GdlServer::server_socket_ {} private
Referenced by run(), and stop().
client_socket_
sock::TcpSocketServer giraffe::gdl::GdlServer::client_socket_ {} private
Referenced by run(), sendResponseData(), sendResponseError(), sendResponseSuccess(), and stop().
send_result_
bool giraffe::gdl::GdlServer::send_result_ {false} private
Set in sendResponseData() and sendResponseError() to indicate that the client is not connected.
Referenced by run(), sendResponseData(), sendResponseError(), and sendResponseSuccess().
response_sent_
bool giraffe::gdl::GdlServer::response_sent_ {false} private
Used to check if a response has been sent to the client.
Referenced by run(), sendResponseData(), sendResponseError(), and sendResponseSuccess().
gdl_config_
Config giraffe::gdl::GdlServer::gdl_config_ = Config(true) private
Referenced by getConfigJson(), and setConfigFromJson().
physical_layer_
std::shared_ptr<SoftwarePhysicalLayer> giraffe::gdl::GdlServer::physical_layer_ private
Initial value:
=
      std::make_shared<SoftwarePhysicalLayer>(gdl_config_)
gdl_
DataLink giraffe::gdl::GdlServer::gdl_ {gdl_config_, physical_layer_} private
Referenced by handleRequestReceivedMessages(), handleRequestStatus(), run(), and sendMessage().
last_broadcast_id_
uint32_t giraffe::gdl::GdlServer::last_broadcast_id_ {1} private
Referenced by getNewBroadcastId().
protocol_id_
uint32_t giraffe::gdl::GdlServer::protocol_id_ {1} private
Referenced by getNextResponseId().
log_
CommonLogger<100> giraffe::gdl::GdlServer::log_ {LoggerLevel::INFO, true} private
Referenced by getConfigJson(), handleRequestLog(), handleRequestStatus(), handleSetConfig(), handleSetNewBroadcast(), handleSetNewExchange(), loadConfig(), run(), saveConfig(), sendMessage(), setConfigFromJson(), and stop().
MAX_SENT_MESSAGES
const size_t giraffe::gdl::GdlServer::MAX_SENT_MESSAGES {50} static private
Referenced by sendMessage().
sent_messages_
std::queue<gdl::Message> giraffe::gdl::GdlServer::sent_messages_ {} private
Referenced by handleRequestSentMessages(), handleRequestStatus(), and sendMessage().