Giraffe: FlightPhasePredictor Class Reference
FlightPhasePredictor Class Reference
Uses data provided by PredictionParameters to predict the current flight phase.
#include <flight_phase_predictor.hpp>
Classes
struct Probability
A stucture that contains the probabilities of being in each phase. The probabilities range from 0 to 100.
Public Types
using Parameter = PredictionParameters::Parameter
Public Member Functions
FlightPhasePredictor (const FlightPhasePredictor &)=delete
Delete the copy constructor.
FlightPhasePredictor (data::SharedData &shared_data)
FlightPhasePredictor (FlightPhasePredictor &&)=delete
Delete the move constructor.
~FlightPhasePredictor ()=default
Probability getPhaseProbability () const
Get the phase probabilities structure.
FlightPhase getPredictedPhase () const
Get the predicted flight phase.
FlightPhasePredictor & operator= (const FlightPhasePredictor &)=delete
Delete the copy assignment operator.
bool update ()
Update the flight phase predictor.
Static Public Attributes
static constexpr double MINIMUM_PROBABILITY_QUALITY = 50.0
Private Member Functions
double getPointsFromRule (const Rule &parameter_rule)
Get the probability points from a rule.
double getPointsFromRuleSet (const PhaseRuleSet &phase_rule_set)
Get the probability points from a rule set.
bool predictFlightPhase ()
Using the probabilities, determine the current flight phase.
void processAllRules ()
Process all rule sets of every phase and calculate the probabilities.
Private Attributes
PredictionParameters detection_data_
double num_invalid_parameters_ {0}
The number of valid parameters.
double num_total_parameters_ {0}
The number of parameters that exist.
Probability phase_probability_ {}
The last calculated probabilities of being in each phase.
FlightPhase predicted_phase_ {FlightPhase::UNKNOWN}
The last detected flight phase.
Detailed Description
Uses data provided by PredictionParameters to predict the current flight phase.
Class Documentation
FlightPhasePredictor::Probability
struct FlightPhasePredictor::Probability
A stucture that contains the probabilities of being in each phase. The probabilities range from 0 to 100.
Class Members
double launch The probability of being in the launch phase. 0 to 100.
double ascent The probability of being in the ascent phase. 0 to 100.
double descent The probability of being in the descent phase. 0 to 100.
double recovery The probability of being in the recovery phase. 0 to 100.
double data_quality
Member Typedef Documentation
Parameter
using FlightPhasePredictor::Parameter = PredictionParameters::Parameter
Constructor & Destructor Documentation
FlightPhasePredictor() [1/3]
FlightPhasePredictor::FlightPhasePredictor (data::SharedData & shared_data) inline
~FlightPhasePredictor()
FlightPhasePredictor::~FlightPhasePredictor () default
FlightPhasePredictor() [2/3]
FlightPhasePredictor::FlightPhasePredictor (const FlightPhasePredictor &) delete
Delete the copy constructor.
FlightPhasePredictor() [3/3]
FlightPhasePredictor::FlightPhasePredictor (FlightPhasePredictor &&) delete
Delete the move constructor.
Member Function Documentation
operator=()
FlightPhasePredictor& FlightPhasePredictor::operator= (const FlightPhasePredictor &) delete
Delete the copy assignment operator.
update()
bool FlightPhasePredictor::update ()
Update the flight phase predictor.
Returns
true if the flight phase has changed, false if it has stayed the same.
References detection_data_, predictFlightPhase(), processAllRules(), and PredictionParameters::updateParameters().
Referenced by FlightPhasePredictorTest::tick(), and FlightPhaseManager::update().
getPhaseProbability()
Probability FlightPhasePredictor::getPhaseProbability () const inline
Get the phase probabilities structure.
References phase_probability_.
Referenced by FlightPhasePredictorTest::SetUp(), FlightPhasePredictorTest::tick(), and FlightPhaseManager::update().
getPredictedPhase()
FlightPhase FlightPhasePredictor::getPredictedPhase () const inline
Get the predicted flight phase.
References predicted_phase_.
Referenced by FlightPhaseManager::update().
getPointsFromRule()
double FlightPhasePredictor::getPointsFromRule (const Rule & parameter_rule) private
Get the probability points from a rule.
References detection_data_, Rule::filter, PredictionParameters::getParameter(), Rule::id, PredictionParameters::Parameter::is_valid, num_invalid_parameters_, num_total_parameters_, Rule::points, and PredictionParameters::Parameter::value.
Referenced by getPointsFromRuleSet().
getPointsFromRuleSet()
double FlightPhasePredictor::getPointsFromRuleSet (const PhaseRuleSet & phase_rule_set) private
Get the probability points from a rule set.
Parameters
phase_rule_set - The rule set to get the points from.
Returns
The points from the rule set.
References getPointsFromRule().
Referenced by processAllRules().
processAllRules()
void FlightPhasePredictor::processAllRules () private
Process all rule sets of every phase and calculate the probabilities.
References ASCENT, DESCENT, getPhaseRuleSetMap(), getPointsFromRuleSet(), giraffe_assert, LAUNCH, num_invalid_parameters_, num_total_parameters_, phase_probability_, and RECOVERY.
Referenced by update().
predictFlightPhase()
bool FlightPhasePredictor::predictFlightPhase () private
Using the probabilities, determine the current flight phase.
Returns
true if the phase was changed, false if it stayed the same.
References ASCENT, FlightPhasePredictor::Probability::data_quality, DESCENT, LAUNCH, MINIMUM_PROBABILITY_QUALITY, phase_probability_, predicted_phase_, RECOVERY, and UNKNOWN.
Referenced by update().
Member Data Documentation
MINIMUM_PROBABILITY_QUALITY
constexpr double FlightPhasePredictor::MINIMUM_PROBABILITY_QUALITY = 50.0 static constexpr
Referenced by predictFlightPhase().
predicted_phase_
FlightPhase FlightPhasePredictor::predicted_phase_ {FlightPhase::UNKNOWN} private
The last detected flight phase.
Referenced by getPredictedPhase(), and predictFlightPhase().
phase_probability_
Probability FlightPhasePredictor::phase_probability_ {} private
The last calculated probabilities of being in each phase.
Referenced by getPhaseProbability(), predictFlightPhase(), and processAllRules().
num_total_parameters_
double FlightPhasePredictor::num_total_parameters_ {0} private
The number of parameters that exist.
Referenced by getPointsFromRule(), and processAllRules().
num_invalid_parameters_
double FlightPhasePredictor::num_invalid_parameters_ {0} private
The number of valid parameters.
Referenced by getPointsFromRule(), and processAllRules().
detection_data_
PredictionParameters FlightPhasePredictor::detection_data_ private
Referenced by getPointsFromRule(), and update().