Giraffe: ExtensionTestFramework Class Reference
ExtensionTestFramework Class Reference
#include <extension_test_framework.hpp>
Public Member Functions
int getTotalDataPackets ()
int getTotalGpsPackets ()
int getTotalImuPackets ()
int getTotalLogPackets ()
void printStreams ()
void runExtensionFor (extension::Extension &ext, int ms)
void sleep (int ms)
Public Attributes
cfg::ExtensionMetadata meta {}
extension::ExtensionResources resources
giraffe::StatusLedState status_led {}
data::Streams streams {}
Member Function Documentation
printStreams()
void ExtensionTestFramework::printStreams ()
References data::Streams::data, data::Stream< T >::getPacket(), data::Streams::gps, data::Streams::imu, data::Streams::log, streams, and util::to_string().
getTotalDataPackets()
int ExtensionTestFramework::getTotalDataPackets ()
References data::Streams::data, data::Stream< T >::getTotalPackets(), and streams.
getTotalLogPackets()
int ExtensionTestFramework::getTotalLogPackets ()
References data::Stream< T >::getTotalPackets(), data::Streams::log, and streams.
getTotalGpsPackets()
int ExtensionTestFramework::getTotalGpsPackets ()
References data::Stream< T >::getTotalPackets(), data::Streams::gps, and streams.
getTotalImuPackets()
int ExtensionTestFramework::getTotalImuPackets ()
References data::Stream< T >::getTotalPackets(), data::Streams::imu, and streams.
sleep()
void ExtensionTestFramework::sleep (int ms)
Referenced by runExtensionFor().
runExtensionFor()
void ExtensionTestFramework::runExtensionFor (extension::Extension & ext, int ms)
References sleep().
Member Data Documentation
streams
data::Streams ExtensionTestFramework::streams {}
Referenced by getTotalDataPackets(), getTotalGpsPackets(), getTotalImuPackets(), getTotalLogPackets(), and printStreams().
status_led
giraffe::StatusLedState ExtensionTestFramework::status_led {}
resources
extension::ExtensionResources ExtensionTestFramework::resources
Initial value:
{streams, cfg::gEnum::I2CBus::I2C_1,
                                          status_led}
meta
cfg::ExtensionMetadata ExtensionTestFramework::meta {}
Referenced by TEST().