Giraffe: gfs_sim::SimEnvironmental Class Reference
gfs_sim::SimEnvironmental Class Reference
#include <sim_environmental.hpp>
Public Member Functions
SimEnvironmental (SimData &data)
double getPressureMillibars () const
double getRelativeHumidityPercent () const
double getTemperatureCelsius () const
double getWindDirectionDegrees () const
double getWindSpeedMPS () const
void setAltitudeMeters (double altitude_meters)
Private Attributes
double altitude_meters_ = 0.0
SimData & data_
EnvData env_data_ {}
Constructor & Destructor Documentation
SimEnvironmental()
gfs_sim::SimEnvironmental::SimEnvironmental (SimData & data) inline
Member Function Documentation
setAltitudeMeters()
void gfs_sim::SimEnvironmental::setAltitudeMeters (double altitude_meters)
References altitude_meters_, data_, env_data_, gfs_sim::SimData::humidity_percent, gfs_sim::K_ENVIRONMENTAL_DATA, gfs_sim::SimData::pressure_mbar, gfs_sim::EnvData::pressure_millibars, gfs_sim::EnvData::relative_humidity_percent, gfs_sim::SimData::temperature_c, gfs_sim::EnvData::temperature_celsius, gfs_sim::EnvData::wind_direction_degrees, and gfs_sim::EnvData::wind_speed_mps.
Referenced by gfs_sim::BalloonPhysics::update().
getTemperatureCelsius()
double gfs_sim::SimEnvironmental::getTemperatureCelsius () const
References env_data_, and gfs_sim::EnvData::temperature_celsius.
Referenced by gfs_sim::GfsSimulator::printData().
getWindSpeedMPS()
double gfs_sim::SimEnvironmental::getWindSpeedMPS () const
References env_data_, and gfs_sim::EnvData::wind_speed_mps.
Referenced by gfs_sim::GfsSimulator::printData(), and gfs_sim::BalloonPhysics::updateHorizontal().
getWindDirectionDegrees()
double gfs_sim::SimEnvironmental::getWindDirectionDegrees () const
References env_data_, and gfs_sim::EnvData::wind_direction_degrees.
Referenced by gfs_sim::GfsSimulator::printData(), and gfs_sim::BalloonPhysics::updateHorizontal().
getPressureMillibars()
double gfs_sim::SimEnvironmental::getPressureMillibars () const
References env_data_, and gfs_sim::EnvData::pressure_millibars.
Referenced by gfs_sim::GfsSimulator::printData().
getRelativeHumidityPercent()
double gfs_sim::SimEnvironmental::getRelativeHumidityPercent () const
References env_data_, and gfs_sim::EnvData::relative_humidity_percent.
Referenced by gfs_sim::GfsSimulator::printData().
Member Data Documentation
altitude_meters_
double gfs_sim::SimEnvironmental::altitude_meters_ = 0.0 private
Referenced by setAltitudeMeters().
env_data_
EnvData gfs_sim::SimEnvironmental::env_data_ {} private
Referenced by getPressureMillibars(), getRelativeHumidityPercent(), getTemperatureCelsius(), getWindDirectionDegrees(), getWindSpeedMPS(), and setAltitudeMeters().
data_
SimData& gfs_sim::SimEnvironmental::data_ private
Referenced by setAltitudeMeters().