Giraffe: giraffe::gdl::DataLink Class Reference
giraffe::gdl::DataLink Class Reference
#include <giraffe_data_link.hpp>
Public Types
enum class Connection { DISABLED , DISCONNECTED , CONNECTED }
Status of a connection.
enum class Status {
ERROR , DISABLED , STARTING , RUNNING ,
STOPPING
}
Data Link Status.
using TelemetryData = signal_easel::aprs::telemetry::TelemetryData
Public Member Functions
DataLink (Config &config, std::shared_ptr< PhysicalLayer > p_physical_layer=nullptr)
Constructor for the Giraffe Data Link.
~DataLink ()
Destructor for the Giraffe Data Link. Stops the background thread if it is running.
bool broadcastText (const std::string &text, uint32_t message_id)
Broadcast a text message over the Data Link.
bool disable ()
Disable the Data Link. Stops the background thread.
bool enable ()
Enable the Data Link. Starts the background thread.
Config & getConfig () override
Statistics getStatistics () override
Get statistics about the Data Link.
DataLink::Status getStatus () const
Get the status of the Data Link.
AprsTelemetrySender::Status getTelemetrySenderStatus () const
std::string getTelemetrySenderStatusString () const
bool isEnabled () const
Check if the Data Link is enabled.
bool messageAvailable () const
Check if a messages have been received and are available.
bool receiveMessage (Message &message)
Receive a message from the Data Link if one is available.
bool sendMessage (const Message &message)
Send a message over the Data Link.
bool sendTelemetryBitSense (TelemetryData &telemetry_data) override
Send an APRS telemetry bit sense message over the Data Link. (Broadcast message)
bool sendTelemetryCoefficients (TelemetryData &telemetry_data) override
Send an APRS telemetry coefficient message over the Data Link. (Broadcast message)
bool sendTelemetryData (TelemetryData &telemetry_data, uint32_t message_id) override
Send telemetry data over the Data Link. (Broadcast message)
void sendTelemetryMetadataPackets ()
bool sendTelemetryParameterNames (TelemetryData &telemetry_data) override
Send an APRS telemetry parameter names message over the Data Link. (Broadcast message)
bool sendTelemetryUnitsAndLabels (TelemetryData &telemetry_data) override
Send an APRS telemetry units and labels message over the Data Link. (Broadcast message)
bool sendText (const std::string &text, uint32_t message_id)
Send a text message over the Data Link. (Exchange message)
bool setPhysicalLayer (std::shared_ptr< PhysicalLayer > p_physical_layer)
Add a physical layer to the Data Link.
void updateTelemetryData (const TelemetryData &telemetry_data) override
Update the telemetry data for the data link telemetry sender.
Private Member Functions
void gdlThread ()
The function that runs in the background thread.
bool isRunning ()
void setStatus (Status status)
Private Attributes
Config & config_
Thread safe GDL configuration.
std::thread gdl_thread_ {}
The background thread for the GDL.
std::atomic< bool > gdl_thread_stop_flag_ {true}
Flag to stop the background thread.
MessageQueue in_queue_ {}
Received messages queue.
NetworkLayer network_layer_ {config_, p_physical_layer_}
The network layer for the GDL.
MessageQueue out_broadcast_queue_ {}
Outgoing broadcast message queue.
MessageQueue out_exchange_queue_ {}
Outgoing exchange message queue.
std::shared_ptr< PhysicalLayer > p_physical_layer_
The physical layer for the GDL.
Statistics statistics_ {}
The statistics for the GDL.
std::mutex statistics_lock_ {}
Lock for the statistics.
std::atomic< Status > status_ {Status::DISABLED}
The status of the GDL.
AprsTelemetrySender telemetry_sender_ {config_}
TransportLayer transport_layer_ {config_, network_layer_}
The transport layer for the GDL.
Member Typedef Documentation
TelemetryData
using giraffe::gdl::IDataLink::TelemetryData = signal_easel::aprs::telemetry::TelemetryData inherited
Member Enumeration Documentation
Connection
enum class giraffe::gdl::DataLink::Connection strong
Status of a connection.
Enumerator
DISABLED
DISCONNECTED
CONNECTED
Status
enum class giraffe::gdl::DataLink::Status strong
Data Link Status.
Enumerator
ERROR
DISABLED
STARTING
RUNNING
STOPPING
Constructor & Destructor Documentation
DataLink()
giraffe::gdl::DataLink::DataLink (Config & config, std::shared_ptr< PhysicalLayer > p_physical_layer = nullptr)
Constructor for the Giraffe Data Link.
Parameters
config - The configuration for the GDL instance.
p_physical_layer - The (optional) physical layer for the GDL. If not set, the physical layer needs to be set before the GDL can be enabled.
References DISABLED, and status_.
~DataLink()
giraffe::gdl::DataLink::~DataLink ()
Destructor for the Giraffe Data Link. Stops the background thread if it is running.
References disable(), DISABLED, and status_.
Member Function Documentation
setPhysicalLayer()
bool giraffe::gdl::DataLink::setPhysicalLayer (std::shared_ptr< PhysicalLayer > p_physical_layer)
Add a physical layer to the Data Link.
Parameters
p_physical_layer - A shared pointer to the physical layer.
Returns
True if the physical layer was set, false otherwise. Will return false if the Data Link already has a physical layer set.
References isRunning(), and p_physical_layer_.
Referenced by modules::TelemetryModule::startup(), and TEST().
enable()
bool giraffe::gdl::DataLink::enable ()
Enable the Data Link. Starts the background thread.
Returns
True if the Data Link was enabled or is already enabled, false if the Data Link could not be enabled.
References gdl_thread_, gdl_thread_stop_flag_, gdlThread(), isRunning(), p_physical_layer_, setStatus(), and STARTING.
Referenced by main(), giraffe::gdl::GdlServer::run(), modules::TelemetryModule::startup(), TEST(), TEST(), TEST(), and TEST().
disable()
bool giraffe::gdl::DataLink::disable ()
Disable the Data Link. Stops the background thread.
Returns
True if the Data Link was disabled or is already disabled, false if the Data Link could not be disabled.
References gdl_thread_, gdl_thread_stop_flag_, isEnabled(), isRunning(), setStatus(), and STOPPING.
Referenced by ~DataLink(), giraffe::gdl::GdlServer::run(), and TEST().
isEnabled()
bool giraffe::gdl::DataLink::isEnabled () const inline
Check if the Data Link is enabled.
References gdl_thread_stop_flag_.
Referenced by disable(), giraffe::gdl::GdlServer::run(), TEST(), and TEST().
getStatus()
DataLink::Status giraffe::gdl::DataLink::getStatus () const
Get the status of the Data Link.
Returns
The status of the Data Link.
References status_.
Referenced by giraffe::gdl::GdlServer::handleRequestStatus(), TEST(), and TEST().
sendMessage()
bool giraffe::gdl::DataLink::sendMessage (const Message & message)
Send a message over the Data Link.
Parameters
message - The message to send.
Returns
true if the message was added to the out queue, false otherwise.
References giraffe::gdl::Message::EXCHANGE, giraffe::gdl::Message::getType(), isRunning(), out_broadcast_queue_, out_exchange_queue_, and giraffe::gdl::MessageQueue::push().
Referenced by giraffe::gdl::GdlServer::sendMessage(), TEST(), and TEST().
sendText()
bool giraffe::gdl::DataLink::sendText (const std::string & text, uint32_t message_id)
Send a text message over the Data Link. (Exchange message)
Parameters
text - The text to send.
message_id A unique identifier for the message.
Returns
true if the message was added to the out queue, false otherwise.
References isRunning(), out_exchange_queue_, giraffe::gdl::MessageQueue::push(), and giraffe::gdl::Message::setExchangeMessage().
sendTelemetryData()
bool giraffe::gdl::DataLink::sendTelemetryData (TelemetryData & telemetry_data, uint32_t message_id) override virtual
Send telemetry data over the Data Link. (Broadcast message)
This overrides the functionality of the APRS telemetry sender. This will immediately add the telemetry packet to the broadcast queue. This method is actually used by the telemetry sender to send telemetry.
Parameters
telemetry_data - The telemetry data to send.
Returns
true if the message was added to the out queue, false otherwise.
Implements giraffe::gdl::IDataLink.
References isRunning(), out_exchange_queue_, giraffe::gdl::MessageQueue::push(), giraffe::gdl::Message::setTelemetryMessage(), and giraffe::gdl::Message::AprsTelemetry::telemetry_type.
sendTelemetryCoefficients()
bool giraffe::gdl::DataLink::sendTelemetryCoefficients (TelemetryData & telemetry_data) override virtual
Send an APRS telemetry coefficient message over the Data Link. (Broadcast message)
This overrides the functionality of the APRS telemetry sender. This will immediately add the telemetry packet to the broadcast queue. This method is actually used by the telemetry sender to send telemetry.
Parameters
telemetry_data - The telemetry data to send.
Returns
true if the message was added to the out queue, false
Implements giraffe::gdl::IDataLink.
References isRunning(), out_exchange_queue_, giraffe::gdl::MessageQueue::push(), giraffe::gdl::Message::setTelemetryMessage(), and giraffe::gdl::Message::AprsTelemetry::telemetry_type.
sendTelemetryParameterNames()
bool giraffe::gdl::DataLink::sendTelemetryParameterNames (TelemetryData & telemetry_data) override virtual
Send an APRS telemetry parameter names message over the Data Link. (Broadcast message)
This overrides the functionality of the APRS telemetry sender. This will immediately add the telemetry packet to the broadcast queue. This method is actually used by the telemetry sender to send telemetry.
Parameters
telemetry_data - The telemetry data to send.
Returns
true if the message was added to the out queue, false
Implements giraffe::gdl::IDataLink.
References isRunning(), out_exchange_queue_, giraffe::gdl::MessageQueue::push(), giraffe::gdl::Message::setTelemetryMessage(), and giraffe::gdl::Message::AprsTelemetry::telemetry_type.
sendTelemetryUnitsAndLabels()
bool giraffe::gdl::DataLink::sendTelemetryUnitsAndLabels (TelemetryData & telemetry_data) override virtual
Send an APRS telemetry units and labels message over the Data Link. (Broadcast message)
This overrides the functionality of the APRS telemetry sender. This will immediately add the telemetry packet to the broadcast queue. This method is actually used by the telemetry sender to send telemetry.
Parameters
telemetry_data - The telemetry data to send.
Returns
true if the message was added to the out queue, false
Implements giraffe::gdl::IDataLink.
References isRunning(), out_exchange_queue_, giraffe::gdl::MessageQueue::push(), giraffe::gdl::Message::setTelemetryMessage(), and giraffe::gdl::Message::AprsTelemetry::telemetry_type.
sendTelemetryBitSense()
bool giraffe::gdl::DataLink::sendTelemetryBitSense (TelemetryData & telemetry_data) override virtual
Send an APRS telemetry bit sense message over the Data Link. (Broadcast message)
This overrides the functionality of the APRS telemetry sender. This will immediately add the telemetry packet to the broadcast queue. This method is actually used by the telemetry sender to send telemetry.
Parameters
telemetry_data - The telemetry data to send.
Returns
true if the message was added to the out queue, false
Implements giraffe::gdl::IDataLink.
References isRunning(), out_exchange_queue_, giraffe::gdl::MessageQueue::push(), giraffe::gdl::Message::setTelemetryMessage(), and giraffe::gdl::Message::AprsTelemetry::telemetry_type.
broadcastText()
bool giraffe::gdl::DataLink::broadcastText (const std::string & text, uint32_t message_id)
Broadcast a text message over the Data Link.
Parameters
text - The text to send.
message_id A unique identifier for the message.
Returns
true if the message was added to the out queue, false otherwise.
References isRunning(), out_exchange_queue_, giraffe::gdl::MessageQueue::push(), and giraffe::gdl::Message::setBroadcastMessage().
receiveMessage()
bool giraffe::gdl::DataLink::receiveMessage (Message & message)
Receive a message from the Data Link if one is available.
Parameters
message[out] - The received message.
Returns
true if there was a message to receive and message was set, false otherwise.
References in_queue_, isRunning(), and giraffe::gdl::MessageQueue::pop().
Referenced by giraffe::gdl::GdlServer::handleRequestReceivedMessages().
messageAvailable()
bool giraffe::gdl::DataLink::messageAvailable () const inline
Check if a messages have been received and are available.
Returns
true if messages are available, false otherwise.
References in_queue_, and giraffe::gdl::MessageQueue::size().
Referenced by giraffe::gdl::GdlServer::handleRequestReceivedMessages().
getStatistics()
Statistics giraffe::gdl::DataLink::getStatistics () inline override virtual
Get statistics about the Data Link.
Returns
GDL statistics.
Implements giraffe::gdl::IDataLink.
References statistics_, and statistics_lock_.
Referenced by giraffe::gdl::GdlServer::handleRequestStatus().
updateTelemetryData()
void giraffe::gdl::DataLink::updateTelemetryData (const TelemetryData & telemetry_data) inline override virtual
Update the telemetry data for the data link telemetry sender.
This does not send the telemetry data, it just updates the telemetry sender so that it can send it when it is ready.
Parameters
telemetry_data - The telemetry data to add.
Implements giraffe::gdl::IDataLink.
References giraffe::gdl::AprsTelemetrySender::addNewData(), config_, giraffe_assert, giraffe::gdl::Config::isController(), and telemetry_sender_.
getTelemetrySenderStatus()
AprsTelemetrySender::Status giraffe::gdl::DataLink::getTelemetrySenderStatus () const inline
References giraffe::gdl::AprsTelemetrySender::getStatus(), and telemetry_sender_.
Referenced by getTelemetrySenderStatusString().
getTelemetrySenderStatusString()
std::string giraffe::gdl::DataLink::getTelemetrySenderStatusString () const inline
References giraffe::gdl::AprsTelemetrySender::getStatusString(), and getTelemetrySenderStatus().
sendTelemetryMetadataPackets()
void giraffe::gdl::DataLink::sendTelemetryMetadataPackets () inline
References giraffe::gdl::AprsTelemetrySender::sendTelemetryMetadata(), and telemetry_sender_.
getConfig()
Config & giraffe::gdl::DataLink::getConfig () inline override virtual
Implements giraffe::gdl::IDataLink.
References config_.
isRunning()
bool giraffe::gdl::DataLink::isRunning () inline private
References gdl_thread_.
Referenced by broadcastText(), disable(), enable(), receiveMessage(), sendMessage(), sendTelemetryBitSense(), sendTelemetryCoefficients(), sendTelemetryData(), sendTelemetryParameterNames(), sendTelemetryUnitsAndLabels(), sendText(), and setPhysicalLayer().
setStatus()
void giraffe::gdl::DataLink::setStatus (Status status) inline private
References status_.
Referenced by disable(), enable(), and gdlThread().
gdlThread()
void giraffe::gdl::DataLink::gdlThread () private
The function that runs in the background thread.
Todo:
handle error (should never happen)
Todo:
handle error (should never happen)
Todo:
handle error (no space in queue)
References giraffe::gdl::Statistics::aprs_telemetry_data_packets_added, giraffe::gdl::Statistics::broadcast_queue_size, DISABLED, giraffe::gdl::Statistics::exchange_queue_size, giraffe::gdl::GDL_THREAD_SLEEP_INTERVAL_MS, gdl_thread_stop_flag_, giraffe::gdl::AprsTelemetrySender::getNumDataPacketsAddedToQueue(), giraffe_assert, in_queue_, giraffe::gdl::TransportLayer::isReadyToSend(), out_broadcast_queue_, out_exchange_queue_, giraffe::gdl::MessageQueue::peek(), giraffe::gdl::MessageQueue::pop(), giraffe::gdl::MessageQueue::push(), giraffe::gdl::TransportLayer::receive(), giraffe::gdl::Statistics::received_queue_size, RUNNING, giraffe::gdl::TransportLayer::send(), setStatus(), giraffe::gdl::MessageQueue::size(), statistics_, statistics_lock_, telemetry_sender_, transport_layer_, giraffe::gdl::AprsTelemetrySender::update(), and giraffe::gdl::TransportLayer::update().
Referenced by enable().
Member Data Documentation
config_
Config& giraffe::gdl::DataLink::config_ private
Thread safe GDL configuration.
Referenced by getConfig(), and updateTelemetryData().
telemetry_sender_
AprsTelemetrySender giraffe::gdl::DataLink::telemetry_sender_ {config_} private
Referenced by gdlThread(), getTelemetrySenderStatus(), sendTelemetryMetadataPackets(), and updateTelemetryData().
out_broadcast_queue_
MessageQueue giraffe::gdl::DataLink::out_broadcast_queue_ {} private
Outgoing broadcast message queue.
Referenced by gdlThread(), and sendMessage().
out_exchange_queue_
MessageQueue giraffe::gdl::DataLink::out_exchange_queue_ {} private
Outgoing exchange message queue.
Referenced by broadcastText(), gdlThread(), sendMessage(), sendTelemetryBitSense(), sendTelemetryCoefficients(), sendTelemetryData(), sendTelemetryParameterNames(), sendTelemetryUnitsAndLabels(), and sendText().
in_queue_
MessageQueue giraffe::gdl::DataLink::in_queue_ {} private
Received messages queue.
Referenced by gdlThread(), messageAvailable(), and receiveMessage().
gdl_thread_
std::thread giraffe::gdl::DataLink::gdl_thread_ {} private
The background thread for the GDL.
Referenced by disable(), enable(), and isRunning().
gdl_thread_stop_flag_
std::atomic<bool> giraffe::gdl::DataLink::gdl_thread_stop_flag_ {true} private
Flag to stop the background thread.
Referenced by disable(), enable(), gdlThread(), and isEnabled().
status_
std::atomic<Status> giraffe::gdl::DataLink::status_ {Status::DISABLED} private
The status of the GDL.
Referenced by DataLink(), ~DataLink(), getStatus(), and setStatus().
statistics_lock_
std::mutex giraffe::gdl::DataLink::statistics_lock_ {} private
Lock for the statistics.
Referenced by gdlThread(), and getStatistics().
statistics_
Statistics giraffe::gdl::DataLink::statistics_ {} private
The statistics for the GDL.
Referenced by gdlThread(), and getStatistics().
p_physical_layer_
std::shared_ptr<PhysicalLayer> giraffe::gdl::DataLink::p_physical_layer_ private
The physical layer for the GDL.
This is a shared pointer. PhysicalLayer is a base class that can be extended to create a custom physical layer.
Referenced by enable(), and setPhysicalLayer().
network_layer_
NetworkLayer giraffe::gdl::DataLink::network_layer_ {config_, p_physical_layer_} private
The network layer for the GDL.
transport_layer_
TransportLayer giraffe::gdl::DataLink::transport_layer_ {config_, network_layer_} private
The transport layer for the GDL.
Referenced by gdlThread().