Giraffe: giraffe::gdl::NetworkLayer Class Reference
giraffe::gdl::NetworkLayer Class Reference
#include <gdl_layers.hpp>
Public Member Functions
NetworkLayer (Config &config, PhysicalLayer &physical_layer)
~NetworkLayer ()
bool rxPacket (Packet &packet)
bool txPacket (Packet &packet)
void update (Statistics &stats)
Private Member Functions
bool txAprsPositionPacket (const Packet &packet)
Private Attributes
Config & config_
signal_easel::aprs::Modulator modulator_ {}
PhysicalLayer & physical_layer_
signal_easel::aprs::Receiver receiver_ {}
uint32_t total_packets_received_ = 0
uint32_t total_packets_sent_ = 0
Constructor & Destructor Documentation
NetworkLayer()
giraffe::gdl::NetworkLayer::NetworkLayer (Config & config, PhysicalLayer & physical_layer)
References giraffe::gdl::PhysicalLayer::enable(), and physical_layer_.
~NetworkLayer()
giraffe::gdl::NetworkLayer::~NetworkLayer ()
Member Function Documentation
txPacket()
bool giraffe::gdl::NetworkLayer::txPacket (Packet & packet)
References giraffe::gdl::Packet::ACK, giraffe::gdl::Packet::BROADCAST, config_, giraffe::gdl::Packet::EXCHANGE, giraffe::gdl::EXP_PREFIX_ACK, giraffe::gdl::EXP_PREFIX_BROADCAST, giraffe::gdl::EXP_PREFIX_EXCHANGE, giraffe::gdl::EXP_PREFIX_PING, giraffe::gdl::EXP_PREFIX_PING_RESPONSE, giraffe::gdl::Config::getCallSign(), giraffe::gdl::Message::getData(), giraffe::gdl::Message::getIdentifierString(), giraffe::gdl::Packet::getPacketType(), giraffe::gdl::Config::getRemoteCallSign(), giraffe::gdl::Config::getRemoteSSID(), giraffe::gdl::Config::getSSID(), giraffe::gdl::Packet::LOCATION, modulator_, giraffe::gdl::Packet::PING, giraffe::gdl::Packet::PING_RESPONSE, total_packets_sent_, and txAprsPositionPacket().
Referenced by giraffe::gdl::TransportLayer::broadcastState(), giraffe::gdl::TransportLayer::exchangeSendState(), giraffe::gdl::TransportLayer::sendAck(), giraffe::gdl::TransportLayer::sendPing(), and giraffe::gdl::TransportLayer::sendPingResponse().
rxPacket()
bool giraffe::gdl::NetworkLayer::rxPacket (Packet & packet)
References giraffe::gdl::Packet::ACK, giraffe::gdl::Packet::BROADCAST, config_, giraffe::gdl::Packet::EXCHANGE, giraffe::gdl::EXP_PREFIX_ACK, giraffe::gdl::EXP_PREFIX_BROADCAST, giraffe::gdl::EXP_PREFIX_EXCHANGE, giraffe::gdl::EXP_PREFIX_PING, giraffe::gdl::EXP_PREFIX_PING_RESPONSE, giraffe::gdl::Config::getCallSign(), giraffe::gdl::Config::getSSID(), giraffe::gdl::Message::Location::latitude, giraffe::gdl::Packet::LOCATION, giraffe::gdl::Packet::PING, giraffe::gdl::Packet::PING_RESPONSE, receiver_, giraffe::gdl::Message::setData(), giraffe::gdl::Message::setIdentifierFromHex(), giraffe::gdl::Message::setLocation(), giraffe::gdl::Packet::setPacketType(), and total_packets_received_.
Referenced by giraffe::gdl::TransportLayer::exchangeWaitingForAckState(), and giraffe::gdl::TransportLayer::idleState().
update()
void giraffe::gdl::NetworkLayer::update (Statistics & stats)
References giraffe::gdl::Statistics::network_layer_latency_ms, physical_layer_, receiver_, giraffe::gdl::Statistics::signal_to_noise_ratio, giraffe::gdl::Statistics::total_packets_received, total_packets_received_, giraffe::gdl::Statistics::total_packets_sent, total_packets_sent_, giraffe::gdl::PhysicalLayer::update(), and giraffe::gdl::Statistics::volume.
Referenced by giraffe::gdl::TransportLayer::update().
txAprsPositionPacket()
bool giraffe::gdl::NetworkLayer::txAprsPositionPacket (const Packet & packet) private
Todo:
report back up
References config_, giraffe::gdl::Config::getCallSign(), giraffe::gdl::Message::getLocation(), giraffe::gdl::Config::getRemoteCallSign(), giraffe::gdl::Config::getRemoteSSID(), giraffe::gdl::Config::getSSID(), giraffe::gdl::Message::Location::latitude, and modulator_.
Referenced by txPacket().
Member Data Documentation
total_packets_sent_
uint32_t giraffe::gdl::NetworkLayer::total_packets_sent_ = 0 private
Referenced by txPacket(), and update().
total_packets_received_
uint32_t giraffe::gdl::NetworkLayer::total_packets_received_ = 0 private
Referenced by rxPacket(), and update().
config_
Config& giraffe::gdl::NetworkLayer::config_ private
Referenced by rxPacket(), txAprsPositionPacket(), and txPacket().
physical_layer_
PhysicalLayer& giraffe::gdl::NetworkLayer::physical_layer_ private
Referenced by NetworkLayer(), and update().
modulator_
signal_easel::aprs::Modulator giraffe::gdl::NetworkLayer::modulator_ {} private
Referenced by txAprsPositionPacket(), and txPacket().
receiver_
signal_easel::aprs::Receiver giraffe::gdl::NetworkLayer::receiver_ {} private
Referenced by rxPacket(), and update().