Giraffe: GfsMetaData Class Reference
GfsMetaData Class Reference
Protected Member Functions
virtual void SetUp ()
virtual void TearDown ()
void validateBoolTypeSetting (std::string setting_name)
void validateCategory (std::string category_name)
void validateEnumTypeSetting (std::string setting_name)
void validateFloatTypeSetting (std::string setting_name)
void validateIntTypeSetting (std::string setting_name)
void validateSettingMetadata (std::string setting_name)
void validateStringTypeSetting (std::string setting_name)
Protected Attributes
json category = {}
json cfg = {}
const std::string file_path_ = "gfs_configuration_metadata.json"
json setting = {}
std::vector< std::string > valid_settings_ = {}
Member Function Documentation
SetUp()
virtual void GfsMetaData::SetUp () inline protected virtual
References file_path_.
TearDown()
virtual void GfsMetaData::TearDown () inline protected virtual
validateCategory()
void GfsMetaData::validateCategory (std::string category_name) inline protected
References category.
validateSettingMetadata()
void GfsMetaData::validateSettingMetadata (std::string setting_name) inline protected
References category, setting, setting_description_min_length, setting_name_max_length, setting_name_min_length, validateBoolTypeSetting(), validateEnumTypeSetting(), validateFloatTypeSetting(), validateIntTypeSetting(), and validateStringTypeSetting().
validateStringTypeSetting()
void GfsMetaData::validateStringTypeSetting (std::string setting_name) inline protected
References setting.
Referenced by validateSettingMetadata().
validateIntTypeSetting()
void GfsMetaData::validateIntTypeSetting (std::string setting_name) inline protected
References setting.
Referenced by validateSettingMetadata().
validateFloatTypeSetting()
void GfsMetaData::validateFloatTypeSetting (std::string setting_name) inline protected
References setting.
Referenced by validateSettingMetadata().
validateBoolTypeSetting()
void GfsMetaData::validateBoolTypeSetting (std::string setting_name) inline protected
References setting.
Referenced by validateSettingMetadata().
validateEnumTypeSetting()
void GfsMetaData::validateEnumTypeSetting (std::string setting_name) inline protected
References setting.
Referenced by validateSettingMetadata().
Member Data Documentation
cfg
json GfsMetaData::cfg = {} protected
category
json GfsMetaData::category = {} protected
Referenced by validateCategory(), and validateSettingMetadata().
setting
json GfsMetaData::setting = {} protected
Referenced by validateBoolTypeSetting(), validateEnumTypeSetting(), validateFloatTypeSetting(), validateIntTypeSetting(), validateSettingMetadata(), and validateStringTypeSetting().
file_path_
const std::string GfsMetaData::file_path_ = "gfs_configuration_metadata.json" protected
Referenced by SetUp().
valid_settings_
std::vector<std::string> GfsMetaData::valid_settings_ = {} protected