Giraffe: extension::ImuExtensionBase Class Reference
extension::ImuExtensionBase Class Reference
#include <imu_extension_base.hpp>
Public Member Functions
ImuExtensionBase (ExtensionResources &resources, cfg::ExtensionMetadata metadata)
DiagnosticId getFaultCode () const
Get the Fault Code when the status is ERROR.
node::Status getStatus () const
Get the Status of the extension.
bool isFaulted () const
Returns true if the extension is in a faulted state.
void reset ()
Only to be called when an extension is in the Error state. This joins the thread and fixes the status.
void start ()
Starts the extension.
void stop ()
Sends a stop signal to the extension.
Protected Member Functions
template<typename T >
void data (data::DataId identifier, T value, int precision=2)
void data (data::GpsFrame frame)
templates for Extension::data
void data (data::ImuFrame frame)
void dataWithSecondaryIdentifier (data::DataId identifier, uint32_t value, const std::string &secondary_identifier)
void debug (const std::string &message)
void error (DiagnosticId log_id, int info)
void error (DiagnosticId, const std::string &info="")
void extSleep (uint32_t milliseconds)
Sleep internally for a given number of milliseconds.
virtual void imuShutdown ()
virtual void imuStartup ()
void info (std::string info)
void raiseFault (DiagnosticId ext_fault_code, std::string info="")
Used internally to raise a fault. This will stop an extension.
virtual bool readImu ()
void reportAccelData (const double x, const double y, const double z)
void reportGyroData (const double x, const double y, const double z)
bool stopRequested () const
Returns true if the extension has been requested to stop.
Protected Attributes
cfg::ExtensionMetadata metadata_
Private Member Functions
void loop () override
void runner ()
void shutdown () override
void sleep ()
void startup () override
Private Attributes
bst::RollingAverage accel_x_ {10}
bst::RollingAverage accel_y_ {10}
bst::RollingAverage accel_z_ {10}
uint32_t data_report_counter_ {0}
uint32_t data_report_interval_
std::atomic< DiagnosticId > fault_code_ = DiagnosticId::EXT_FAULT_none
The fault code associated with the fault.
std::atomic< bool > fault_flag_ = false
This is raised with a call to raiseFault().
bst::RollingAverage gyro_x_ {10}
bst::RollingAverage gyro_y_ {10}
bst::RollingAverage gyro_z_ {10}
bst::Timer imu_watchdog_
ExtensionResources & interfaces_
std::thread runner_thread_ = std::thread()
std::atomic< node::Status > status_ = node::Status::STOPPED
std::atomic< bool > stop_flag_ = true
Constructor & Destructor Documentation
ImuExtensionBase()
extension::ImuExtensionBase::ImuExtensionBase (ExtensionResources & resources, cfg::ExtensionMetadata metadata) inline
References accel_x_, accel_y_, accel_z_, data_report_interval_, extension::Extension::error(), extension::K_DEFAULT_REPORT_INTERVAL, and metadata.
Member Function Documentation
imuStartup()
virtual void extension::ImuExtensionBase::imuStartup () inline protected virtual
Reimplemented in extension::Bmi088.
Referenced by startup().
readImu()
virtual bool extension::ImuExtensionBase::readImu () inline protected virtual
Reimplemented in extension::Bmi088.
References giraffe_assert.
Referenced by loop().
imuShutdown()
virtual void extension::ImuExtensionBase::imuShutdown () inline protected virtual
reportAccelData()
void extension::ImuExtensionBase::reportAccelData (const double x, const double y, const double z) inline protected
References accel_x_, accel_y_, and accel_z_.
Referenced by extension::Bmi088::readAccelData().
reportGyroData()
void extension::ImuExtensionBase::reportGyroData (const double x, const double y, const double z) inline protected
References gyro_x_, gyro_y_, and gyro_z_.
Referenced by extension::Bmi088::readGyroData().
startup()
void extension::ImuExtensionBase::startup () inline override private virtual
Reimplemented from extension::Extension.
References imu_watchdog_, imuStartup(), and extension::Extension::isFaulted().
loop()
void extension::ImuExtensionBase::loop () inline override private virtual
Reimplemented from extension::Extension.
References accel_x_, accel_y_, accel_z_, extension::Extension::data(), data_report_counter_, data_report_interval_, gyro_x_, gyro_y_, gyro_z_, imu_watchdog_, extension::Extension::raiseFault(), readImu(), data::ImuFrame::x_acceleration, data::ImuFrame::x_angular_velocity, data::ImuFrame::y_acceleration, data::ImuFrame::y_angular_velocity, data::ImuFrame::z_acceleration, and data::ImuFrame::z_angular_velocity.
shutdown()
void extension::ImuExtensionBase::shutdown () inline override private virtual
Reimplemented from extension::Extension.
start()
void extension::Extension::start () inherited
Starts the extension.
References extension::Extension::error(), extension::Extension::fault_code_, extension::Extension::fault_flag_, node::K_ACTIVE_STATUSES, extension::Extension::runner(), extension::Extension::runner_thread_, extension::Extension::status_, and extension::Extension::stop_flag_.
Referenced by ExtensionTestFramework::runExtensionFor().
stop()
void extension::Extension::stop () inherited
Sends a stop signal to the extension.
The timeout for stopping an extension.
The interval of how often to check if the extension has stopped.
References extension::Extension::error(), node::K_INACTIVE_STATUSES, extension::Extension::runner_thread_, extension::Extension::status_, and extension::Extension::stop_flag_.
Referenced by extension::Extension::~Extension(), extension::Extension::reset(), and ExtensionTestFramework::runExtensionFor().
reset()
void extension::Extension::reset () inherited
Only to be called when an extension is in the Error state. This joins the thread and fixes the status.
References extension::Extension::status_, extension::Extension::stop(), and node::STOPPED.
getStatus()
node::Status extension::Extension::getStatus () const inline inherited
Get the Status of the extension.
Returns
node::Status The status of the extension.
References extension::Extension::status_.
getFaultCode()
DiagnosticId extension::Extension::getFaultCode () const inline inherited
Get the Fault Code when the status is ERROR.
Returns
DiagnosticId The fault code.
References extension::Extension::fault_code_.
isFaulted()
bool extension::Extension::isFaulted () const inline inherited
Returns true if the extension is in a faulted state.
Returns
true if the extension is in a faulted state, false otherwise.
References extension::Extension::fault_flag_.
Referenced by extension::AdcExtensionBase::startup(), and startup().
data() [1/3]
template<typename T > void extension::Extension::data (data::DataId identifier, T value, int precision = 2) protected inherited
References data::Stream< T >::addPacket(), data::Streams::data, data::DataPacket::identifier, extension::Extension::interfaces_, kExtensionId, extension::Extension::metadata_, cfg::ExtensionMetadata::name, data::BaseStreamPacket::secondary_identifier, data::BaseStreamPacket::source, extension::ExtensionResources::streams, util::to_string(), and data::DataPacket::value.
Referenced by extension::Bme280::loop(), extension::Ds18b20::loop(), loop(), extension::PiCamera::loop(), extension::SimTemperatureSensor::loop(), extension::SimPressureSensor::loop(), extension::SimHumiditySensor::loop(), extension::SimGpsSensor::loop(), extension::SimImuSensor::loop(), extension::Bme280::readEnvironmentalData(), and extension::SamM8q::stateRead().
data() [2/3]
void extension::Extension::data (data::GpsFrame frame) protected inherited
templates for Extension::data
 */
template void Extension::data<int>(data::DataId, int, int);
template void Extension::data<float>(data::DataId, float, int);
template void Extension::data<double>(data::DataId, double, int);
template void Extension::data<uint32_t>(data::DataId, uint32_t, int);
template void Extension::data<std::string>(data::DataId, std::string, int);
/**
 *
References data::GpsFrameStream::addFrame(), node::EXTENSION, data::Streams::gps, extension::Extension::interfaces_, extension::Extension::metadata_, cfg::ExtensionMetadata::name, and extension::ExtensionResources::streams.
data() [3/3]
void extension::Extension::data (data::ImuFrame frame) protected inherited
References data::ImuFrameStream::addFrame(), node::EXTENSION, data::Streams::imu, extension::Extension::interfaces_, extension::Extension::metadata_, cfg::ExtensionMetadata::name, and extension::ExtensionResources::streams.
dataWithSecondaryIdentifier()
void extension::Extension::dataWithSecondaryIdentifier (data::DataId identifier, uint32_t value, const std::string & secondary_identifier) protected inherited
References data::Stream< T >::addPacket(), data::Streams::data, node::EXTENSION, data::DataPacket::identifier, extension::Extension::interfaces_, extension::Extension::metadata_, cfg::ExtensionMetadata::name, data::DataPacket::NUMERIC, data::DataPacket::numeric_value, data::BaseStreamPacket::secondary_identifier, data::BaseStreamPacket::source, extension::ExtensionResources::streams, and data::DataPacket::type.
Referenced by extension::AdcExtensionBase::reportAdcData().
error() [1/2]
void extension::Extension::error (DiagnosticId log_id, const std::string & info = "") protected inherited
References data::Stream< T >::addPacket(), data::LogPacket::ERROR, data::LogPacket::id, data::LogPacket::info, extension::Extension::interfaces_, kExtensionId, data::LogPacket::level, data::Streams::log, extension::Extension::metadata_, cfg::ExtensionMetadata::name, data::BaseStreamPacket::secondary_identifier, data::BaseStreamPacket::source, and extension::ExtensionResources::streams.
Referenced by ImuExtensionBase(), extension::PiCamera::PiCamera(), extension::Mcp3021::adcStartup(), extension::Bme280::loop(), extension::Ds18b20::loop(), extension::PiCamera::loop(), extension::Bme280::processEnvironmentalData(), extension::Extension::raiseFault(), extension::Extension::start(), extension::SamM8q::stateConfigure(), extension::SamM8q::stateRead(), and extension::Extension::stop().
error() [2/2]
void extension::Extension::error (DiagnosticId log_id, int info) protected inherited
References data::Stream< T >::addPacket(), data::LogPacket::ERROR, data::LogPacket::id, extension::Extension::info(), data::LogPacket::info, extension::Extension::interfaces_, kExtensionId, data::LogPacket::level, data::Streams::log, extension::Extension::metadata_, cfg::ExtensionMetadata::name, data::BaseStreamPacket::secondary_identifier, data::BaseStreamPacket::source, extension::ExtensionResources::streams, and util::to_string().
info()
void extension::Extension::info (std::string info) protected inherited
References data::Stream< T >::addPacket(), data::LogPacket::id, data::LogPacket::INFO, data::LogPacket::info, extension::Extension::interfaces_, kExtensionId, data::LogPacket::level, data::Streams::log, extension::Extension::metadata_, cfg::ExtensionMetadata::name, data::BaseStreamPacket::secondary_identifier, data::BaseStreamPacket::source, and extension::ExtensionResources::streams.
Referenced by extension::Extension::debug(), and extension::Extension::error().
debug()
void extension::Extension::debug (const std::string & message) protected inherited
References data::Stream< T >::addPacket(), data::LogPacket::DEBUG, data::LogPacket::id, extension::Extension::info(), data::LogPacket::info, extension::Extension::interfaces_, kExtensionId, data::LogPacket::level, data::Streams::log, extension::Extension::metadata_, cfg::ExtensionMetadata::name, data::BaseStreamPacket::secondary_identifier, data::BaseStreamPacket::source, and extension::ExtensionResources::streams.
Referenced by extension::RgbStatusLed::RgbStatusLed(), extension::Mcp3021::adcStartup(), extension::Ds18b20::init(), extension::Ds18b20::loop(), extension::PiCamera::loop(), extension::Mcp3021::readAdc(), extension::Ds18b20::startup(), extension::SamM8q::startup(), extension::SamM8q::stateConfigure(), extension::SamM8q::stateRead(), extension::SamM8q::stateReset(), and extension::SamM8q::transitionState().
stopRequested()
bool extension::Extension::stopRequested () const protected inherited
Returns true if the extension has been requested to stop.
This should be used in the loop() function for extensions that take a long time to complete a single loop iteration. This is helpful for to stop extensions quickly upon request. Fast extensions do not need to use this.
Returns
true - The extension has been requested to stop.
false - The extension has not been requested to stop.
References extension::Extension::stop_flag_.
Referenced by extension::Extension::sleep(), extension::Bme280::startup(), extension::Ds18b20::startup(), and extension::SamM8q::startup().
raiseFault()
void extension::Extension::raiseFault (DiagnosticId ext_fault_code, std::string info = "") protected inherited
Used internally to raise a fault. This will stop an extension.
References extension::Extension::error(), extension::Extension::fault_code_, extension::Extension::fault_flag_, and extension::Extension::stop_flag_.
Referenced by extension::Bmi088::Bmi088(), extension::RgbStatusLed::RgbStatusLed(), extension::Mcp3021::adcStartup(), extension::Bmi088::imuStartup(), extension::AdcExtensionBase::loop(), extension::Bme280::loop(), extension::Ds18b20::loop(), loop(), extension::PiCamera::loop(), extension::RgbStatusLed::shutdown(), extension::Bme280::startup(), extension::Ds18b20::startup(), extension::PiCamera::startup(), extension::RgbStatusLed::startup(), extension::SamM8q::startup(), and extension::SamM8q::stateReset().
extSleep()
void extension::Extension::extSleep (uint32_t milliseconds) protected inherited
Sleep internally for a given number of milliseconds.
This has a limit of 1 second.
Parameters
milliseconds - The number of milliseconds to sleep.
Referenced by extension::Bmi088::accHandshake(), extension::Bmi088::configureAccelerometer(), extension::Bmi088::gyroHandshake(), extension::Bme280::startup(), extension::Ds18b20::startup(), extension::SamM8q::startup(), and extension::SamM8q::stateRead().
sleep()
void extension::Extension::sleep () private inherited
References extension::Extension::metadata_, extension::Extension::stopRequested(), and cfg::ExtensionMetadata::update_interval.
Referenced by extension::Extension::runner().
runner()
void extension::Extension::runner () private inherited
References node::ERROR, extension::Extension::fault_flag_, extension::Extension::loop(), node::RUNNING, extension::Extension::shutdown(), extension::Extension::sleep(), node::STARTING, extension::Extension::startup(), extension::Extension::status_, extension::Extension::stop_flag_, node::STOPPED, and node::STOPPING.
Referenced by extension::Extension::start().
Member Data Documentation
imu_watchdog_
bst::Timer extension::ImuExtensionBase::imu_watchdog_ private
Referenced by loop(), and startup().
data_report_interval_
uint32_t extension::ImuExtensionBase::data_report_interval_ private
Referenced by ImuExtensionBase(), and loop().
data_report_counter_
uint32_t extension::ImuExtensionBase::data_report_counter_ {0} private
Referenced by loop().
accel_x_
bst::RollingAverage extension::ImuExtensionBase::accel_x_ {10} private
Referenced by ImuExtensionBase(), loop(), and reportAccelData().
accel_y_
bst::RollingAverage extension::ImuExtensionBase::accel_y_ {10} private
Referenced by ImuExtensionBase(), loop(), and reportAccelData().
accel_z_
bst::RollingAverage extension::ImuExtensionBase::accel_z_ {10} private
Referenced by ImuExtensionBase(), loop(), and reportAccelData().
gyro_x_
bst::RollingAverage extension::ImuExtensionBase::gyro_x_ {10} private
Referenced by loop(), and reportGyroData().
gyro_y_
bst::RollingAverage extension::ImuExtensionBase::gyro_y_ {10} private
Referenced by loop(), and reportGyroData().
gyro_z_
bst::RollingAverage extension::ImuExtensionBase::gyro_z_ {10} private
Referenced by loop(), and reportGyroData().
metadata_
cfg::ExtensionMetadata extension::Extension::metadata_ protected inherited
Referenced by extension::Bmi088::Bmi088(), extension::Extension::data(), extension::Extension::dataWithSecondaryIdentifier(), extension::Extension::debug(), extension::Extension::error(), extension::Extension::info(), extension::Ds18b20::init(), and extension::Extension::sleep().
fault_flag_
std::atomic<bool> extension::Extension::fault_flag_ = false private inherited
This is raised with a call to raiseFault().
This is used to stop the extension. Cleared on a call to start().
Referenced by extension::Extension::isFaulted(), extension::Extension::raiseFault(), extension::Extension::runner(), and extension::Extension::start().
fault_code_
std::atomic<DiagnosticId> extension::Extension::fault_code_ = DiagnosticId::EXT_FAULT_none private inherited
The fault code associated with the fault.
This is set when raiseFault() is called. Cleared on a call to start().
Referenced by extension::Extension::getFaultCode(), extension::Extension::raiseFault(), and extension::Extension::start().
status_
std::atomic<node::Status> extension::Extension::status_ = node::Status::STOPPED private inherited
Referenced by extension::Extension::getStatus(), extension::Extension::reset(), extension::Extension::runner(), extension::Extension::start(), and extension::Extension::stop().
stop_flag_
std::atomic<bool> extension::Extension::stop_flag_ = true private inherited
Referenced by extension::Extension::raiseFault(), extension::Extension::runner(), extension::Extension::start(), extension::Extension::stop(), and extension::Extension::stopRequested().
runner_thread_
std::thread extension::Extension::runner_thread_ = std::thread() private inherited
Referenced by extension::Extension::start(), and extension::Extension::stop().
interfaces_
ExtensionResources& extension::Extension::interfaces_ private inherited
Referenced by extension::Extension::data(), extension::Extension::dataWithSecondaryIdentifier(), extension::Extension::debug(), extension::Extension::error(), and extension::Extension::info().