Giraffe: gdl::NetworkLayer Class Reference
gdl::NetworkLayer Class Reference abstract
#include <gdl_network_layer.hpp>
Public Member Functions
NetworkLayer (PhysicalLayer &physical_layer)
virtual ~NetworkLayer ()
virtual bool rxMessage (Message &message)=0
virtual bool txMessage (Message &message)=0
void update ()
virtual void updateNetworkLayer ()=0
virtual void updateStatus (GdlStatus &status)=0
Protected Attributes
PhysicalLayer & physical_layer_
Constructor & Destructor Documentation
NetworkLayer()
gdl::NetworkLayer::NetworkLayer (PhysicalLayer & physical_layer) inline
References gdl::PhysicalLayer::enable(), and physical_layer_.
~NetworkLayer()
virtual gdl::NetworkLayer::~NetworkLayer () inline virtual
Member Function Documentation
txMessage()
virtual bool gdl::NetworkLayer::txMessage (Message & message) pure virtual
Implemented in gdl::AprsNetworkLayer.
Referenced by gdl::TransportLayer::sendAck(), and gdl::TransportLayer::sendPacket().
rxMessage()
virtual bool gdl::NetworkLayer::rxMessage (Message & message) pure virtual
Implemented in gdl::AprsNetworkLayer.
Referenced by gdl::TransportLayer::receive(), gdl::TransportLayer::receivedAck(), and gdl::TransportLayer::update().
updateNetworkLayer()
virtual void gdl::NetworkLayer::updateNetworkLayer () pure virtual
Implemented in gdl::AprsNetworkLayer.
Referenced by update().
updateStatus()
virtual void gdl::NetworkLayer::updateStatus (GdlStatus & status) pure virtual
Implemented in gdl::AprsNetworkLayer.
Referenced by gdl::TransportLayer::updateStatus().
update()
void gdl::NetworkLayer::update () inline
References physical_layer_, gdl::PhysicalLayer::update(), and updateNetworkLayer().
Referenced by gdl::TransportLayer::update().
Member Data Documentation
physical_layer_
PhysicalLayer& gdl::NetworkLayer::physical_layer_ protected
Referenced by NetworkLayer(), and update().