Giraffe: giraffe::SpiInterface Class Reference
giraffe::SpiInterface Class Reference
#include <spi_interface.hpp>
Classes
struct Config
Public Member Functions
SpiInterface (Config config)
Constructor for the SPI interface class.
~SpiInterface ()
Destructor for the SPI interface class. Closes the file descriptors if they are open.
void closeDevice ()
Closes the SPI device. No action is taken if the device is already closed.
bool isOpen () const
Returns true if the SPI device is open, false otherwise.
bool openDevice (std::string device_path)
Attempts to open the SPI device. Returns true if successful, false otherwise.
bool transfer (uint8_t *tx_buffer, uint8_t *rx_buffer, size_t transfer_size)
SPI transfer function. Returns true if the transfer was successful, false otherwise.
Private Attributes
Config config_ {}
int spi_fd_ = -1
Class Documentation
giraffe::SpiInterface::Config
struct giraffe::SpiInterface::Config
Class Members
uint8_t bits_per_word
uint32_t speed_hz
uint16_t delay_usecs
Constructor & Destructor Documentation
SpiInterface()
giraffe::SpiInterface::SpiInterface (Config config) inline
Constructor for the SPI interface class.
~SpiInterface()
giraffe::SpiInterface::~SpiInterface () inline
Destructor for the SPI interface class. Closes the file descriptors if they are open.
References closeDevice().
Member Function Documentation
openDevice()
bool giraffe::SpiInterface::openDevice (std::string device_path)
Attempts to open the SPI device. Returns true if successful, false otherwise.
Note
This function will call giraffe_assert if the device is already open.
Parameters
device_path - The path to the SPI device. Example: "/dev/spidev0.1"
Returns
true If the device was opened successfully.
false If the device was not opened successfully.
References giraffe_assert, and spi_fd_.
Referenced by extension::Bmi088::startup().
closeDevice()
void giraffe::SpiInterface::closeDevice ()
Closes the SPI device. No action is taken if the device is already closed.
References spi_fd_.
Referenced by extension::Bmi088::~Bmi088(), and ~SpiInterface().
isOpen()
bool giraffe::SpiInterface::isOpen () const inline
Returns true if the SPI device is open, false otherwise.
Returns
true The SPI device is open.
false The SPI device is closed.
References spi_fd_.
transfer()
bool giraffe::SpiInterface::transfer (uint8_t * tx_buffer, uint8_t * rx_buffer, size_t transfer_size)
SPI transfer function. Returns true if the transfer was successful, false otherwise.
Parameters
tx_buffer The buffer to transmit (must be at least transfer_size)
rx_buffer The buffer to receive (must be at least transfer_size)
transfer_size The number of bytes to transfer
Returns
true The transfer was successful
false The transfer was not successful
References giraffe::SpiInterface::Config::bits_per_word, config_, giraffe::SpiInterface::Config::delay_usecs, giraffe_assert, giraffe::SpiInterface::Config::speed_hz, and spi_fd_.
Referenced by extension::Bmi088::accelerometerHandshake(), extension::Bmi088::configureAccelerometer(), extension::Bmi088::configureGyro(), extension::Bmi088::gyroHandshake(), extension::Bmi088::readAccelData(), and extension::Bmi088::readGyroData().
Member Data Documentation
spi_fd_
int giraffe::SpiInterface::spi_fd_ = -1 private
Referenced by closeDevice(), isOpen(), openDevice(), and transfer().
config_
Config giraffe::SpiInterface::config_ {} private
Referenced by transfer().