Giraffe: giraffe::gdl::Config Class Reference
giraffe::gdl::Config Class Reference
Data Link Configuration.
#include <gdl_config_and_stats.hpp>
Public Member Functions
Config (bool is_controller=true)
Constructor for GDL Configuration.
~Config ()=default
uint32_t getAprsTelemetryDataIntervalMs () const
std::string getCallSign ()
bool getProactiveKeepAlive () const
std::string getRemoteCallSign ()
uint8_t getRemoteSSID () const
uint8_t getSSID () const
bool isAprsTelemetrySenderEnabled () const
bool isController () const
void setAprsTelemetryDataIntervalMs (uint32_t interval_ms)
void setAprsTelemetrySenderEnabled (bool enabled)
void setCallSign (const std::string &call_sign)
void setProactiveKeepAlive (bool proactive_keep_alive)
void setRemoteCallSign (const std::string &remote_call_sign)
void setRemoteSSID (uint8_t remote_ssid)
void setSSID (uint8_t ssid)
Private Attributes
std::atomic< uint32_t > aprs_telemetry_data_interval_ms_ {5 * 60 * 1000}
The interval at which to send telemetry data packets. Default is 5 minutes.
std::atomic< bool > aprs_telemetry_sender_enabled_ {false}
Set to true to enable the APRS telemetry sender.
std::string call_sign_ = "NOCALL"
std::mutex call_sign_lock_ {}
bool is_controller_ = true
std::atomic< bool > proactive_keep_alive_ {false}
std::string remote_call_sign_ = "NOCALL"
std::atomic< uint8_t > remote_ssid_ = 0
std::atomic< uint8_t > ssid_ = 0
Detailed Description
Data Link Configuration.
Constructor & Destructor Documentation
Config()
giraffe::gdl::Config::Config (bool is_controller = true) inline
Constructor for GDL Configuration.
Parameters
is_controller - Is this GDL instance the controller or the remote?
~Config()
giraffe::gdl::Config::~Config () default
Member Function Documentation
setCallSign()
void giraffe::gdl::Config::setCallSign (const std::string & call_sign) inline
References call_sign_, and call_sign_lock_.
Referenced by giraffe::gdl::GdlServer::setConfigFromJson(), and modules::TelemetryModule::startup().
getCallSign()
std::string giraffe::gdl::Config::getCallSign () inline
References call_sign_, and call_sign_lock_.
Referenced by giraffe::gdl::GdlServer::getConfigJson(), giraffe::gdl::NetworkLayer::rxPacket(), giraffe::gdl::NetworkLayer::txAprsPositionPacket(), giraffe::gdl::NetworkLayer::txAprsTelemetryPacket(), giraffe::gdl::NetworkLayer::txPacket(), and giraffe::gdl::NetworkLayer::txSstvImage().
setSSID()
void giraffe::gdl::Config::setSSID (uint8_t ssid) inline
References ssid_.
Referenced by giraffe::gdl::GdlServer::setConfigFromJson(), and modules::TelemetryModule::startup().
getSSID()
uint8_t giraffe::gdl::Config::getSSID () const inline
References ssid_.
Referenced by giraffe::gdl::GdlServer::getConfigJson(), giraffe::gdl::NetworkLayer::rxPacket(), giraffe::gdl::NetworkLayer::txAprsPositionPacket(), giraffe::gdl::NetworkLayer::txAprsTelemetryPacket(), and giraffe::gdl::NetworkLayer::txPacket().
setRemoteCallSign()
void giraffe::gdl::Config::setRemoteCallSign (const std::string & remote_call_sign) inline
References call_sign_lock_, and remote_call_sign_.
Referenced by giraffe::gdl::GdlServer::setConfigFromJson(), and modules::TelemetryModule::startup().
getRemoteCallSign()
std::string giraffe::gdl::Config::getRemoteCallSign () inline
References call_sign_lock_, and remote_call_sign_.
Referenced by giraffe::gdl::GdlServer::getConfigJson(), giraffe::gdl::NetworkLayer::txAprsPositionPacket(), giraffe::gdl::NetworkLayer::txAprsTelemetryPacket(), and giraffe::gdl::NetworkLayer::txPacket().
setRemoteSSID()
void giraffe::gdl::Config::setRemoteSSID (uint8_t remote_ssid) inline
References remote_ssid_.
Referenced by giraffe::gdl::GdlServer::setConfigFromJson(), and modules::TelemetryModule::startup().
setAprsTelemetrySenderEnabled()
void giraffe::gdl::Config::setAprsTelemetrySenderEnabled (bool enabled) inline
References aprs_telemetry_sender_enabled_.
Referenced by giraffe::AprsManager::initializeTelemetryData(), and main().
setAprsTelemetryDataIntervalMs()
void giraffe::gdl::Config::setAprsTelemetryDataIntervalMs (uint32_t interval_ms) inline
References aprs_telemetry_data_interval_ms_.
Referenced by giraffe::AprsManager::initializeTelemetryData().
getRemoteSSID()
uint8_t giraffe::gdl::Config::getRemoteSSID () const inline
References remote_ssid_.
Referenced by giraffe::gdl::GdlServer::getConfigJson(), giraffe::gdl::NetworkLayer::txAprsPositionPacket(), giraffe::gdl::NetworkLayer::txAprsTelemetryPacket(), and giraffe::gdl::NetworkLayer::txPacket().
isController()
bool giraffe::gdl::Config::isController () const inline
References is_controller_.
Referenced by giraffe::gdl::TransportLayer::idleState(), and giraffe::gdl::DataLink::updateTelemetryData().
setProactiveKeepAlive()
void giraffe::gdl::Config::setProactiveKeepAlive (bool proactive_keep_alive) inline
References proactive_keep_alive_.
Referenced by giraffe::gdl::GdlServer::setConfigFromJson().
getProactiveKeepAlive()
bool giraffe::gdl::Config::getProactiveKeepAlive () const inline
References proactive_keep_alive_.
Referenced by giraffe::gdl::TransportLayer::controllerIdleState(), giraffe::gdl::GdlServer::getConfigJson(), giraffe::gdl::TransportLayer::idleState(), and giraffe::gdl::TransportLayer::send().
isAprsTelemetrySenderEnabled()
bool giraffe::gdl::Config::isAprsTelemetrySenderEnabled () const inline
References aprs_telemetry_sender_enabled_.
Referenced by giraffe::gdl::AprsTelemetrySender::sendTelemetryMetadata(), AprsTelemetryDataManagerTest::SetUp(), and giraffe::gdl::AprsTelemetrySender::update().
getAprsTelemetryDataIntervalMs()
uint32_t giraffe::gdl::Config::getAprsTelemetryDataIntervalMs () const inline
References aprs_telemetry_data_interval_ms_.
Referenced by AprsTelemetryDataManagerTest::SetUp(), and giraffe::gdl::AprsTelemetrySender::update().
Member Data Documentation
is_controller_
bool giraffe::gdl::Config::is_controller_ = true private
Referenced by isController().
call_sign_lock_
std::mutex giraffe::gdl::Config::call_sign_lock_ {} private
Referenced by getCallSign(), getRemoteCallSign(), setCallSign(), and setRemoteCallSign().
call_sign_
std::string giraffe::gdl::Config::call_sign_ = "NOCALL" private
Referenced by getCallSign(), and setCallSign().
ssid_
std::atomic<uint8_t> giraffe::gdl::Config::ssid_ = 0 private
Referenced by getSSID(), and setSSID().
remote_call_sign_
std::string giraffe::gdl::Config::remote_call_sign_ = "NOCALL" private
Referenced by getRemoteCallSign(), and setRemoteCallSign().
remote_ssid_
std::atomic<uint8_t> giraffe::gdl::Config::remote_ssid_ = 0 private
Referenced by getRemoteSSID(), and setRemoteSSID().
proactive_keep_alive_
std::atomic<bool> giraffe::gdl::Config::proactive_keep_alive_ {false} private
Referenced by getProactiveKeepAlive(), and setProactiveKeepAlive().
aprs_telemetry_sender_enabled_
std::atomic<bool> giraffe::gdl::Config::aprs_telemetry_sender_enabled_ {false} private
Set to true to enable the APRS telemetry sender.
Referenced by isAprsTelemetrySenderEnabled(), and setAprsTelemetrySenderEnabled().
aprs_telemetry_data_interval_ms_
std::atomic<uint32_t> giraffe::gdl::Config::aprs_telemetry_data_interval_ms_ {5 * 60 * 1000} private
The interval at which to send telemetry data packets. Default is 5 minutes.
Referenced by getAprsTelemetryDataIntervalMs(), and setAprsTelemetryDataIntervalMs().