Giraffe: giraffe::StatusLedState Class Reference
giraffe::StatusLedState Class Reference
#include <status_led.hpp>
Public Types
enum class State { OFF , ON , BLINK }
Public Member Functions
StatusLedState ()=default
~StatusLedState ()=default
State getBlueState () const
State getGreenState () const
State getRedState () const
void setBlue (State state)
void setGreen (State state)
void setRed (State state)
Private Attributes
std::atomic< State > b_state_ = State::OFF
std::atomic< State > g_state_ = State::OFF
std::atomic< State > r_state_ = State::OFF
Member Enumeration Documentation
State
enum giraffe::StatusLedState::State strong
Enumerator
OFF
ON
BLINK
Constructor & Destructor Documentation
StatusLedState()
giraffe::StatusLedState::StatusLedState () default
~StatusLedState()
giraffe::StatusLedState::~StatusLedState () default
Member Function Documentation
setRed()
void giraffe::StatusLedState::setRed (State state) inline
References r_state_.
setGreen()
void giraffe::StatusLedState::setGreen (State state) inline
References g_state_.
setBlue()
void giraffe::StatusLedState::setBlue (State state) inline
References b_state_.
getRedState()
State giraffe::StatusLedState::getRedState () const inline
References r_state_.
Referenced by extension::RgbStatusLed::loop().
getGreenState()
State giraffe::StatusLedState::getGreenState () const inline
References g_state_.
Referenced by extension::RgbStatusLed::loop().
getBlueState()
State giraffe::StatusLedState::getBlueState () const inline
References b_state_.
Referenced by extension::RgbStatusLed::loop().
Member Data Documentation
r_state_
std::atomic<State> giraffe::StatusLedState::r_state_ = State::OFF private
Referenced by getRedState(), and setRed().
g_state_
std::atomic<State> giraffe::StatusLedState::g_state_ = State::OFF private
Referenced by getGreenState(), and setGreen().
b_state_
std::atomic<State> giraffe::StatusLedState::b_state_ = State::OFF private
Referenced by getBlueState(), and setBlue().