Giraffe: giraffe::AprsManager Class Reference
giraffe::AprsManager Class Reference
Manages GDL APRS Position and Telemetry Data.
#include <aprs_manager.hpp>
Public Member Functions
AprsManager (data::SharedData &shared_data, cfg::Configuration &config, gdl::IDataLink &data_link, bst::ITimer &data_update_timer_)
Constructor.
void loadConfiguration ()
Force a configuration reload.
bool sendOnAirDefinitionPackets ()
Sends the on-air definition packets.
void update ()
This method handles everything that needs to be done. It must be called at least at the rate of the configured send rate.
Static Public Attributes
static constexpr int DATA_UPDATE_RATE_MS = 1000
Private Member Functions
void initializePositionPacketData ()
Initializes the APRS Position Packet data from the configuration.
void initializeTelemetryData ()
Initializes the APRS Telemetry data from the configuration.
void updatePositionPacketData ()
void updateTelemetryData ()
Private Attributes
cfg::Configuration & config_
gdl::IDataLink & data_link_
bst::ITimer & data_update_timer_
Timer used for updating the local state of the telemetry data.
Logger logger_
bool position_packet_initialized_ = false
Set to true after a successful call to initializePositionPacketData.
data::SharedData & shared_data_
gdl::IDataLink::TelemetryData telemetry_data_ {}
bool telemetry_data_initialized_ = false
Set to true after a successful call to initializeTelemetryData.
Detailed Description
Manages GDL APRS Position and Telemetry Data.
This class is responsible structuring the telemetry data packets and updating the GDL's telemetry sender with the data. This class is now also responsible for sending APRS Position packets.
Todo:
Consider renaming to "AprsDataManager"
Constructor & Destructor Documentation
AprsManager()
giraffe::AprsManager::AprsManager (data::SharedData & shared_data, cfg::Configuration & config, gdl::IDataLink & data_link, bst::ITimer & data_update_timer)
Constructor.
Parameters
shared_data - Shared data object - needed for getting data and logging.
config - GFS Configuration.
data_link - The Data Link.
Todo:
This probably needs to be brought into the configuration so it's user accessible.
References DATA_UPDATE_RATE_MS, data_update_timer_, and loadConfiguration().
Member Function Documentation
loadConfiguration()
void giraffe::AprsManager::loadConfiguration ()
Force a configuration reload.
References initializePositionPacketData(), and initializeTelemetryData().
Referenced by AprsManager(), and AprsTelemetryDataManagerTest::SetUp().
update()
void giraffe::AprsManager::update ()
This method handles everything that needs to be done. It must be called at least at the rate of the configured send rate.
References config_, data_update_timer_, updatePositionPacketData(), and updateTelemetryData().
Referenced by AprsTelemetryDataManagerTest::causeDataUpdate().
sendOnAirDefinitionPackets()
bool giraffe::AprsManager::sendOnAirDefinitionPackets ()
Sends the on-air definition packets.
This will add the PARM, UNIT, EQNS, and BITS packets to the data link broadcast queue. The purpose of this method is to allow an external process (Data Link Commands) to request these instead of sending them automatically.
Returns
true if the packets were successfully added to the broadcast queue, false otherwise.
References data_link_, giraffe::gdl::IDataLink::sendTelemetryBitSense(), giraffe::gdl::IDataLink::sendTelemetryCoefficients(), giraffe::gdl::IDataLink::sendTelemetryParameterNames(), giraffe::gdl::IDataLink::sendTelemetryUnitsAndLabels(), telemetry_data_, and telemetry_data_initialized_.
initializePositionPacketData()
void giraffe::AprsManager::initializePositionPacketData () private
Initializes the APRS Position Packet data from the configuration.
References position_packet_initialized_.
Referenced by loadConfiguration().
initializeTelemetryData()
void giraffe::AprsManager::initializeTelemetryData () private
Initializes the APRS Telemetry data from the configuration.
References config_, data_link_, giraffe::Logger::error(), giraffe::gdl::IDataLink::getConfig(), logger_, giraffe::gdl::Config::setAprsTelemetryDataIntervalMs(), giraffe::gdl::Config::setAprsTelemetrySenderEnabled(), telemetry_data_, and telemetry_data_initialized_.
Referenced by loadConfiguration().
updatePositionPacketData()
void giraffe::AprsManager::updatePositionPacketData () private
Todo:
Implement
Referenced by update().
updateTelemetryData()
void giraffe::AprsManager::updateTelemetryData () private
Todo:
Implement
Todo:
Implement
References ASCENT, data::SharedData::blocks, data::SharedBlocks::calculated_data, data_link_, DESCENT, data::SharedData::flight_data, data::FlightData::getFlightPhase(), LAUNCH, PRE_LAUNCH, RECOVERY, shared_data_, telemetry_data_, UNKNOWN, and giraffe::gdl::IDataLink::updateTelemetryData().
Referenced by update().
Member Data Documentation
DATA_UPDATE_RATE_MS
constexpr int giraffe::AprsManager::DATA_UPDATE_RATE_MS = 1000 static constexpr
Referenced by AprsManager().
position_packet_initialized_
bool giraffe::AprsManager::position_packet_initialized_ = false private
Set to true after a successful call to initializePositionPacketData.
Referenced by initializePositionPacketData().
telemetry_data_initialized_
bool giraffe::AprsManager::telemetry_data_initialized_ = false private
Set to true after a successful call to initializeTelemetryData.
Referenced by initializeTelemetryData(), and sendOnAirDefinitionPackets().
telemetry_data_
gdl::IDataLink::TelemetryData giraffe::AprsManager::telemetry_data_ {} private
Referenced by initializeTelemetryData(), sendOnAirDefinitionPackets(), and updateTelemetryData().
shared_data_
data::SharedData& giraffe::AprsManager::shared_data_ private
Referenced by updateTelemetryData().
config_
cfg::Configuration& giraffe::AprsManager::config_ private
Referenced by initializeTelemetryData(), and update().
data_link_
gdl::IDataLink& giraffe::AprsManager::data_link_ private
Referenced by initializeTelemetryData(), sendOnAirDefinitionPackets(), and updateTelemetryData().
data_update_timer_
bst::ITimer& giraffe::AprsManager::data_update_timer_ private
Timer used for updating the local state of the telemetry data.
This is not used for sending the data. That is handled by GDLs telemetry sender.
Referenced by AprsManager(), and update().
logger_
Logger giraffe::AprsManager::logger_ private
Initial value:
{shared_data_, node::Identification::TELEMETRY_MODULE,
                 "AprsTDM"}
Referenced by initializeTelemetryData().