Giraffe: extension::Extension Class Reference
extension::Extension Class Reference
#include <extension_base.hpp>
Public Member Functions
Extension (const Extension &)=delete
Extension (ExtensionResources &resources, cfg::ExtensionMetadata metadata)
virtual ~Extension ()
This will attempt to stop the extension if it is running, but with a configured timeout.
DiagnosticId getFaultCode () const
Get the Fault Code when the status is ERROR.
node::Status getStatus () const
Get the Status of the extension.
bool isFaulted () const
Returns true if the extension is in a faulted state.
Extension & operator= (const Extension &)=delete
void reset ()
Only to be called when an extension is in the Error state. This joins the thread and fixes the status.
void start ()
Starts the extension.
void stop ()
Sends a stop signal to the extension.
Protected Member Functions
template<typename T >
void data (data::DataId identifier, T value, int precision=2)
void data (data::GpsFrame frame)
templates for Extension::data
void data (data::ImuFrame frame)
void dataWithSecondaryIdentifier (data::DataId identifier, uint32_t value, const std::string &secondary_identifier)
void debug (const std::string &message)
void error (DiagnosticId log_id, int info)
void error (DiagnosticId, const std::string &info="")
void extSleep (uint32_t milliseconds)
Sleep internally for a given number of milliseconds.
void info (std::string info)
virtual void loop ()
void raiseFault (DiagnosticId ext_fault_code, std::string info="")
Used internally to raise a fault. This will stop an extension.
virtual void shutdown ()
virtual void startup ()
bool stopRequested () const
Returns true if the extension has been requested to stop.
Protected Attributes
cfg::ExtensionMetadata metadata_
Private Member Functions
void runner ()
void sleep ()
Private Attributes
std::atomic< DiagnosticId > fault_code_ = DiagnosticId::EXT_FAULT_none
The fault code associated with the fault.
std::atomic< bool > fault_flag_ = false
This is raised with a call to raiseFault().
ExtensionResources & interfaces_
std::thread runner_thread_ = std::thread()
std::atomic< node::Status > status_ = node::Status::STOPPED
std::atomic< bool > stop_flag_ = true
Detailed Description
Many of the things in here are nearly identical to modules. However, there are few subtle differences.
Modules are unique, you will only every have one "server" module. Extensions are not. You may have multiple BMP280 sensors, for example. As extensions are identified by name, the handling of the data packets is a bit different. Along with that, extensions do not have direct access to 'shared_data' as modules do. Instead, they all have access to the data/log stream, but only through the data(), error(), and info() functions.
Extensions do not need to be written in a thread safe manner as they are run in their own thread and their only interface is through methods that are thread safe.
Constructor & Destructor Documentation
Extension() [1/2]
extension::Extension::Extension (ExtensionResources & resources, cfg::ExtensionMetadata metadata)
Extension() [2/2]
extension::Extension::Extension (const Extension &) delete
~Extension()
extension::Extension::~Extension () virtual
This will attempt to stop the extension if it is running, but with a configured timeout.
See also
kExtensionDestroyTimeoutMs
This really shouldn't be used, but it is here to silence a warning and it's there if needed.
References stop().
Member Function Documentation
operator=()
Extension & extension::Extension::operator= (const Extension &) delete
start()
void extension::Extension::start ()
Starts the extension.
References error(), fault_code_, fault_flag_, node::K_ACTIVE_STATUSES, runner(), runner_thread_, status_, and stop_flag_.
Referenced by ExtensionTestFramework::runExtensionFor().
stop()
void extension::Extension::stop ()
Sends a stop signal to the extension.
The timeout for stopping an extension.
The interval of how often to check if the extension has stopped.
References error(), node::K_INACTIVE_STATUSES, runner_thread_, status_, and stop_flag_.
Referenced by ~Extension(), reset(), and ExtensionTestFramework::runExtensionFor().
reset()
void extension::Extension::reset ()
Only to be called when an extension is in the Error state. This joins the thread and fixes the status.
References status_, stop(), and node::STOPPED.
Referenced by extension::Ds18b20::startup().
getStatus()
node::Status extension::Extension::getStatus () const inline
Get the Status of the extension.
Returns
node::Status The status of the extension.
References status_.
getFaultCode()
DiagnosticId extension::Extension::getFaultCode () const inline
Get the Fault Code when the status is ERROR.
Returns
DiagnosticId The fault code.
References fault_code_.
isFaulted()
bool extension::Extension::isFaulted () const inline
Returns true if the extension is in a faulted state.
Returns
true if the extension is in a faulted state, false otherwise.
References fault_flag_.
Referenced by extension::AdcExtensionBase::startup(), and extension::ImuExtensionBase::startup().
startup()
virtual void extension::Extension::startup () inline protected virtual
Reimplemented in extension::AdcExtensionBase, extension::Bme280, extension::Ds18b20, extension::ImuExtensionBase, extension::PiCamera, extension::RgbStatusLed, extension::SamM8q, and extension::SimTest.
Referenced by runner().
loop()
virtual void extension::Extension::loop () inline protected virtual
Reimplemented in extension::AdcExtensionBase, extension::Bme280, extension::Ds18b20, extension::ImuExtensionBase, extension::PiCamera, extension::RgbStatusLed, extension::SamM8q, extension::UnitTestExtension, extension::SimTest, extension::SimTemperatureSensor, extension::SimPressureSensor, extension::SimHumiditySensor, extension::SimGpsSensor, extension::SimImuSensor, extension::SimAdcSensor, and extension::SimCamera.
Referenced by runner().
shutdown()
virtual void extension::Extension::shutdown () inline protected virtual
Reimplemented in extension::AdcExtensionBase, extension::ImuExtensionBase, extension::PiCamera, extension::RgbStatusLed, extension::SamM8q, and extension::SimTest.
Referenced by runner().
data() [1/3]
template<typename T > void extension::Extension::data (data::DataId identifier, T value, int precision = 2) protected
References data::Stream< T >::addPacket(), data::Streams::data, data::DataPacket::identifier, interfaces_, kExtensionId, metadata_, cfg::ExtensionMetadata::name, data::BaseStreamPacket::secondary_identifier, data::BaseStreamPacket::source, extension::ExtensionResources::streams, and data::DataPacket::value.
data() [2/3]
void extension::Extension::data (data::GpsFrame frame) protected
templates for Extension::data
 */
template void Extension::data<int>(data::DataId, int, int);
template void Extension::data<float>(data::DataId, float, int);
template void Extension::data<double>(data::DataId, double, int);
template void Extension::data<uint32_t>(data::DataId, uint32_t, int);
template void Extension::data<std::string>(data::DataId, std::string, int);
/**
 *
References data::GpsFrameStream::addFrame(), node::EXTENSION, data::Streams::gps, interfaces_, metadata_, cfg::ExtensionMetadata::name, and extension::ExtensionResources::streams.
data() [3/3]
void extension::Extension::data (data::ImuFrame frame) protected
References data::ImuFrameStream::addFrame(), node::EXTENSION, data::Streams::imu, interfaces_, metadata_, cfg::ExtensionMetadata::name, and extension::ExtensionResources::streams.
dataWithSecondaryIdentifier()
void extension::Extension::dataWithSecondaryIdentifier (data::DataId identifier, uint32_t value, const std::string & secondary_identifier) protected
References data::Stream< T >::addPacket(), data::Streams::data, node::EXTENSION, data::DataPacket::identifier, interfaces_, metadata_, cfg::ExtensionMetadata::name, data::DataPacket::NUMERIC, data::DataPacket::numeric_value, data::BaseStreamPacket::secondary_identifier, data::BaseStreamPacket::source, extension::ExtensionResources::streams, and data::DataPacket::type.
Referenced by extension::SimAdcSensor::loop(), and extension::AdcExtensionBase::reportAdcData().
error() [1/2]
void extension::Extension::error (DiagnosticId log_id, const std::string & info = "") protected
References data::Stream< T >::addPacket(), data::LogPacket::ERROR, data::LogPacket::id, data::LogPacket::info, interfaces_, kExtensionId, data::LogPacket::level, data::Streams::log, metadata_, cfg::ExtensionMetadata::name, data::BaseStreamPacket::secondary_identifier, data::BaseStreamPacket::source, and extension::ExtensionResources::streams.
Referenced by extension::ImuExtensionBase::ImuExtensionBase(), extension::PiCamera::PiCamera(), extension::Mcp3021::adcStartup(), extension::SimCamera::copySampleImage(), extension::Bme280::loop(), extension::Ds18b20::loop(), extension::PiCamera::loop(), extension::Bme280::processEnvironmentalData(), raiseFault(), start(), extension::SamM8q::stateConfigure(), extension::SamM8q::stateRead(), and stop().
error() [2/2]
void extension::Extension::error (DiagnosticId log_id, int info) protected
References data::Stream< T >::addPacket(), data::LogPacket::ERROR, data::LogPacket::id, info(), data::LogPacket::info, interfaces_, kExtensionId, data::LogPacket::level, data::Streams::log, metadata_, cfg::ExtensionMetadata::name, data::BaseStreamPacket::secondary_identifier, data::BaseStreamPacket::source, and extension::ExtensionResources::streams.
info()
void extension::Extension::info (std::string info) protected
References data::Stream< T >::addPacket(), data::LogPacket::id, info(), data::LogPacket::INFO, data::LogPacket::info, interfaces_, kExtensionId, data::LogPacket::level, data::Streams::log, metadata_, cfg::ExtensionMetadata::name, data::BaseStreamPacket::secondary_identifier, data::BaseStreamPacket::source, and extension::ExtensionResources::streams.
Referenced by debug(), error(), and info().
debug()
void extension::Extension::debug (const std::string & message) protected
References data::Stream< T >::addPacket(), data::LogPacket::DEBUG, data::LogPacket::id, info(), data::LogPacket::info, interfaces_, kExtensionId, data::LogPacket::level, data::Streams::log, metadata_, cfg::ExtensionMetadata::name, data::BaseStreamPacket::secondary_identifier, data::BaseStreamPacket::source, and extension::ExtensionResources::streams.
Referenced by extension::RgbStatusLed::RgbStatusLed(), extension::Mcp3021::adcStartup(), extension::Ds18b20::init(), extension::Ds18b20::loop(), extension::PiCamera::loop(), extension::Mcp3021::readAdc(), extension::Ds18b20::startup(), extension::SamM8q::startup(), extension::SamM8q::stateConfigure(), extension::SamM8q::stateRead(), extension::SamM8q::stateReset(), and extension::SamM8q::transitionState().
stopRequested()
bool extension::Extension::stopRequested () const protected
Returns true if the extension has been requested to stop.
This should be used in the loop() function for extensions that take a long time to complete a single loop iteration. This is helpful for to stop extensions quickly upon request. Fast extensions do not need to use this.
Returns
true - The extension has been requested to stop.
false - The extension has not been requested to stop.
References stop_flag_.
Referenced by sleep(), extension::Bme280::startup(), extension::Ds18b20::startup(), and extension::SamM8q::startup().
raiseFault()
void extension::Extension::raiseFault (DiagnosticId ext_fault_code, std::string info = "") protected
Used internally to raise a fault. This will stop an extension.
References error(), fault_code_, fault_flag_, and stop_flag_.
Referenced by extension::Bmi088::Bmi088(), extension::RgbStatusLed::RgbStatusLed(), extension::Mcp3021::adcStartup(), extension::Bmi088::imuStartup(), extension::AdcExtensionBase::loop(), extension::Bme280::loop(), extension::Ds18b20::loop(), extension::ImuExtensionBase::loop(), extension::PiCamera::loop(), extension::RgbStatusLed::shutdown(), extension::Bme280::startup(), extension::Ds18b20::startup(), extension::PiCamera::startup(), extension::RgbStatusLed::startup(), extension::SamM8q::startup(), and extension::SamM8q::stateReset().
extSleep()
void extension::Extension::extSleep (uint32_t milliseconds) protected
Sleep internally for a given number of milliseconds.
This has a limit of 1 second.
Parameters
milliseconds - The number of milliseconds to sleep.
Referenced by extension::Bmi088::accHandshake(), extension::Bmi088::configureAccelerometer(), extension::Bmi088::gyroHandshake(), extension::Bme280::startup(), extension::Ds18b20::startup(), extension::SamM8q::startup(), and extension::SamM8q::stateRead().
sleep()
void extension::Extension::sleep () private
References metadata_, stopRequested(), and cfg::ExtensionMetadata::update_interval.
Referenced by runner().
runner()
void extension::Extension::runner () private
References node::ERROR, fault_flag_, loop(), node::RUNNING, shutdown(), sleep(), node::STARTING, startup(), status_, stop_flag_, node::STOPPED, and node::STOPPING.
Referenced by start().
Member Data Documentation
metadata_
cfg::ExtensionMetadata extension::Extension::metadata_ protected
Referenced by extension::Bmi088::Bmi088(), data(), data(), data(), dataWithSecondaryIdentifier(), debug(), error(), error(), info(), extension::Ds18b20::init(), and sleep().
fault_flag_
std::atomic<bool> extension::Extension::fault_flag_ = false private
This is raised with a call to raiseFault().
This is used to stop the extension. Cleared on a call to start().
Referenced by isFaulted(), raiseFault(), runner(), and start().
fault_code_
std::atomic<DiagnosticId> extension::Extension::fault_code_ = DiagnosticId::EXT_FAULT_none private
The fault code associated with the fault.
This is set when raiseFault() is called. Cleared on a call to start().
Referenced by getFaultCode(), raiseFault(), and start().
status_
std::atomic<node::Status> extension::Extension::status_ = node::Status::STOPPED private
Referenced by getStatus(), reset(), runner(), start(), and stop().
stop_flag_
std::atomic<bool> extension::Extension::stop_flag_ = true private
Referenced by raiseFault(), runner(), start(), stop(), and stopRequested().
runner_thread_
std::thread extension::Extension::runner_thread_ = std::thread() private
Referenced by start(), and stop().
interfaces_
ExtensionResources& extension::Extension::interfaces_ private
Referenced by data(), data(), data(), dataWithSecondaryIdentifier(), debug(), error(), error(), and info().