Giraffe: data_middleware::AdcInterpolation Class Reference
data_middleware::AdcInterpolation Class Reference
Data Module utility class for processing ADC data.
#include <adc_interpolation.hpp>
Public Member Functions
AdcInterpolation (data::SharedData &shared_data, cfg::Configuration &configuration)
~AdcInterpolation ()=default
void processDataPacket (const data::DataPacket &data_packet)
Takes in a data packet containing raw ADC data and processes it according to the ADC configuration.
Private Member Functions
const cfg::AdcConfig & getAdcConfig (const std::string &key)
Returns the ADC channel configuration for the given key. If one does not exist, an error is logged and a basic configuration is added to the map and returned.
void insertPercentageValue (const cfg::AdcConfig &adc_cfg, uint32_t value)
Takes in the raw ADC value and the ADC Value Configuration and inserts a calculated percentage value into the adc data frame.
void insertVoltageDividerValue (const cfg::AdcConfig &adc_cfg, uint32_t value)
Takes in the raw ADC value and the ADC Value Configuration and inserts a calculated voltage divider value into the adc data frame.
Private Attributes
std::unordered_map< std::string, cfg::AdcConfig > adc_map_
Maps extension_name:adc_channel to the ADC configuration.
cfg::Configuration & configuration_
giraffe::Logger logger_
data::SharedData & shared_data_
Detailed Description
Data Module utility class for processing ADC data.
Constructor & Destructor Documentation
AdcInterpolation()
data_middleware::AdcInterpolation::AdcInterpolation (data::SharedData & shared_data, cfg::Configuration & configuration)
References adc_map_, configuration_, giraffe::Logger::info(), logger_, and util::to_string().
~AdcInterpolation()
data_middleware::AdcInterpolation::~AdcInterpolation () default
Member Function Documentation
processDataPacket()
void data_middleware::AdcInterpolation::processDataPacket (const data::DataPacket & data_packet)
Takes in a data packet containing raw ADC data and processes it according to the ADC configuration.
Parameters
data_packet - The data packet containing the ADC data.
References data::Frames::adc, data::SharedData::frames, getAdcConfig(), giraffe_assert, data::DataPacket::identifier, data::Frame< ID, DATA >::insert(), insertPercentageValue(), insertVoltageDividerValue(), data::DataPacket::numeric_value, data::BaseStreamPacket::secondary_identifier, and shared_data_.
insertPercentageValue()
void data_middleware::AdcInterpolation::insertPercentageValue (const cfg::AdcConfig & adc_cfg, uint32_t value) private
Takes in the raw ADC value and the ADC Value Configuration and inserts a calculated percentage value into the adc data frame.
Parameters
adc_cfg - The ADC configuration.
value - The raw ADC value.
References cfg::AdcConfig::label, cfg::AdcConfig::percentage_clamp, cfg::AdcConfig::percentage_max, and cfg::AdcConfig::percentage_min.
Referenced by processDataPacket().
insertVoltageDividerValue()
void data_middleware::AdcInterpolation::insertVoltageDividerValue (const cfg::AdcConfig & adc_cfg, uint32_t value) private
Takes in the raw ADC value and the ADC Value Configuration and inserts a calculated voltage divider value into the adc data frame.
Parameters
adc_cfg - The ADC configuration.
value - The raw ADC value.
References data::Frames::adc, data::DataStream::addNumericData(), data::Streams::data, node::DATA_MODULE, data::SharedData::frames, data::Frame< ID, DATA >::insert(), cfg::AdcConfig::label, cfg::AdcConfig::resistor_1_value, cfg::AdcConfig::resistor_2_value, cfg::AdcConfig::resolution, shared_data_, data::SharedData::streams, and cfg::AdcConfig::voltage_reference.
Referenced by processDataPacket().
getAdcConfig()
const cfg::AdcConfig & data_middleware::AdcInterpolation::getAdcConfig (const std::string & key) private
Returns the ADC channel configuration for the given key. If one does not exist, an error is logged and a basic configuration is added to the map and returned.
Parameters
key - The key to look up the ADC configuration. extension_name:channel_number
Returns
const cfg::AdcConfig& - The ADC configuration.
Referenced by processDataPacket().
Member Data Documentation
adc_map_
std::unordered_map<std::string, cfg::AdcConfig> data_middleware::AdcInterpolation::adc_map_ private
Maps extension_name:adc_channel to the ADC configuration.
Referenced by AdcInterpolation().
shared_data_
data::SharedData& data_middleware::AdcInterpolation::shared_data_ private
Referenced by insertVoltageDividerValue(), and processDataPacket().
configuration_
cfg::Configuration& data_middleware::AdcInterpolation::configuration_ private
Referenced by AdcInterpolation().
logger_
giraffe::Logger data_middleware::AdcInterpolation::logger_ private
Referenced by AdcInterpolation().