Giraffe: gfs_sim::BalloonPhysics Class Reference
gfs_sim::BalloonPhysics Class Reference
#include <sim_physics.hpp>
Public Member Functions
BalloonPhysics (SimState &state, SimEnvironmental &env, SimData &data)
double getAltitude () const
double getDirectionOfTravel () const
double getHorizontalSpeed () const
double getTotalDistance () const
double getVerticalAcceleration () const
double getVerticalSpeed () const
void launch ()
void update (double delta_time_s)
Private Member Functions
void setDirectionOfTravel (double direction_of_travel)
void setHorizontalSpeed (double horizontal_speed)
void setVerticalAcceleration (double vertical_acceleration)
void stateAscent ()
void stateDescent ()
void stateLanded ()
void stateLanding ()
void stateMachine ()
void statePop ()
void statePreLaunch ()
void stopTravel ()
void updateCoordinates (double distance_m, double heading)
void updateHorizontal (double delta_time_s)
void verticalAccelerationVariation (double variance)
Private Attributes
double altitude_ {K_START_ALTITUDE_METERS}
SimData & data_
double direction_of_travel_ {0.0}
double distance_since_last_coordinate_ {0.0}
SimEnvironmental & env_
double horizontal_speed_ {K_START_HORIZONTAL_SPEED_MPS}
double latitude_ {K_START_LATITUDE}
bool launch_signal_ {false}
double longitude_ {K_START_LONGITUDE}
SimState & state_
double total_distance_ {0.0}
double vertical_acceleration_ {K_START_VERTICAL_ACCELERATION_MPS2}
double vertical_speed_ {K_START_VERTICAL_SPEED_MPS}
Constructor & Destructor Documentation
BalloonPhysics()
gfs_sim::BalloonPhysics::BalloonPhysics (SimState & state, SimEnvironmental & env, SimData & data) inline
Member Function Documentation
update()
void gfs_sim::BalloonPhysics::update (double delta_time_s)
References altitude_, gfs_sim::SimData::altitude_m, gfs_sim::ASCENT, data_, gfs_sim::DESCENT, direction_of_travel_, env_, gfs_sim::SimData::heading_deg, horizontal_speed_, gfs_sim::SimData::horz_velocity_mps, gfs_sim::LANDING, latitude_, gfs_sim::SimData::latitude_deg, longitude_, gfs_sim::SimData::longitude_deg, gfs_sim::POP, gfs_sim::SimEnvironmental::setAltitudeMeters(), state_, stateMachine(), updateHorizontal(), gfs_sim::SimData::vert_accel_mps2, gfs_sim::SimData::vert_velocity_mps, vertical_acceleration_, and vertical_speed_.
Referenced by gfs_sim::GfsSimulator::run().
launch()
void gfs_sim::BalloonPhysics::launch () inline
References launch_signal_.
Referenced by gfs_sim::GfsSimulator::launch().
getAltitude()
double gfs_sim::BalloonPhysics::getAltitude () const inline
References altitude_.
Referenced by gfs_sim::GfsSimulator::printData(), stateAscent(), stateDescent(), and stateLanding().
getVerticalSpeed()
double gfs_sim::BalloonPhysics::getVerticalSpeed () const inline
References vertical_speed_.
Referenced by gfs_sim::GfsSimulator::printData(), stateAscent(), stateDescent(), and statePop().
getVerticalAcceleration()
double gfs_sim::BalloonPhysics::getVerticalAcceleration () const inline
References vertical_acceleration_.
getHorizontalSpeed()
double gfs_sim::BalloonPhysics::getHorizontalSpeed () const inline
References horizontal_speed_.
Referenced by gfs_sim::GfsSimulator::printData().
getDirectionOfTravel()
double gfs_sim::BalloonPhysics::getDirectionOfTravel () const inline
References direction_of_travel_.
Referenced by gfs_sim::GfsSimulator::printData(), and updateHorizontal().
getTotalDistance()
double gfs_sim::BalloonPhysics::getTotalDistance () const inline
References total_distance_.
Referenced by gfs_sim::GfsSimulator::printData().
setVerticalAcceleration()
void gfs_sim::BalloonPhysics::setVerticalAcceleration (double vertical_acceleration) inline private
References vertical_acceleration_.
Referenced by stateAscent(), stateDescent(), and statePreLaunch().
setHorizontalSpeed()
void gfs_sim::BalloonPhysics::setHorizontalSpeed (double horizontal_speed) inline private
References horizontal_speed_.
Referenced by statePreLaunch(), and updateHorizontal().
setDirectionOfTravel()
void gfs_sim::BalloonPhysics::setDirectionOfTravel (double direction_of_travel) inline private
References direction_of_travel_.
Referenced by updateHorizontal().
verticalAccelerationVariation()
void gfs_sim::BalloonPhysics::verticalAccelerationVariation (double variance) inline private
References vertical_acceleration_.
Referenced by stateAscent(), and statePop().
updateHorizontal()
void gfs_sim::BalloonPhysics::updateHorizontal (double delta_time_s) private
References distance_since_last_coordinate_, env_, getDirectionOfTravel(), gfs_sim::SimEnvironmental::getWindDirectionDegrees(), gfs_sim::SimEnvironmental::getWindSpeedMPS(), horizontal_speed_, setDirectionOfTravel(), setHorizontalSpeed(), total_distance_, and updateCoordinates().
Referenced by update().
updateCoordinates()
void gfs_sim::BalloonPhysics::updateCoordinates (double distance_m, double heading) private
References latitude_, and longitude_.
Referenced by updateHorizontal().
stopTravel()
void gfs_sim::BalloonPhysics::stopTravel () inline private
References horizontal_speed_, vertical_acceleration_, and vertical_speed_.
Referenced by stateLanding().
statePreLaunch()
void gfs_sim::BalloonPhysics::statePreLaunch () private
References gfs_sim::ASCENT, launch_signal_, setHorizontalSpeed(), setVerticalAcceleration(), and state_.
Referenced by stateMachine().
stateAscent()
void gfs_sim::BalloonPhysics::stateAscent () private
References getAltitude(), getVerticalSpeed(), gfs_sim::K_ASCENT_ACCELERATION_MPS2, gfs_sim::K_ASCENT_ACCELERATION_VARIANCE, gfs_sim::K_ASCENT_RATE_METERS_PER_SECOND_MAX, gfs_sim::K_ASCENT_RATE_METERS_PER_SECOND_MIN, gfs_sim::K_POP_ACCELERATION_MPS2, gfs_sim::K_POP_ALTITUDE_METERS, gfs_sim::POP, setVerticalAcceleration(), state_, and verticalAccelerationVariation().
Referenced by stateMachine().
statePop()
void gfs_sim::BalloonPhysics::statePop () private
References gfs_sim::DESCENT, getVerticalSpeed(), gfs_sim::K_POP_ACCELERATION_VARIANCE, gfs_sim::K_POP_DESCENT_RATE_METERS_PER_SECOND_TARGET, state_, and verticalAccelerationVariation().
Referenced by stateMachine().
stateDescent()
void gfs_sim::BalloonPhysics::stateDescent () private
References getAltitude(), getVerticalSpeed(), gfs_sim::K_DESCENT_DECELERATION_MPS2, gfs_sim::K_DESCENT_RATE_METERS_PER_SECOND_MAX, gfs_sim::K_DESCENT_RATE_METERS_PER_SECOND_MIN, gfs_sim::K_DESCENT_TRANSITION_ALTITUDE_METERS, gfs_sim::K_LANDING_ALTITUDE_METERS, gfs_sim::K_POP_ALTITUDE_METERS, gfs_sim::LANDING, setVerticalAcceleration(), and state_.
Referenced by stateMachine().
stateLanding()
void gfs_sim::BalloonPhysics::stateLanding () private
References getAltitude(), gfs_sim::K_LANDING_ALTITUDE_METERS, gfs_sim::LANDED, state_, and stopTravel().
Referenced by stateMachine().
stateLanded()
void gfs_sim::BalloonPhysics::stateLanded () private
Referenced by stateMachine().
stateMachine()
void gfs_sim::BalloonPhysics::stateMachine () private
References gfs_sim::ASCENT, gfs_sim::DESCENT, gfs_sim::LANDED, gfs_sim::LANDING, gfs_sim::POP, gfs_sim::PRE_LAUNCH, state_, stateAscent(), stateDescent(), stateLanded(), stateLanding(), statePop(), and statePreLaunch().
Referenced by update().
Member Data Documentation
launch_signal_
bool gfs_sim::BalloonPhysics::launch_signal_ {false} private
Referenced by launch(), and statePreLaunch().
altitude_
double gfs_sim::BalloonPhysics::altitude_ {K_START_ALTITUDE_METERS} private
Referenced by getAltitude(), and update().
vertical_speed_
double gfs_sim::BalloonPhysics::vertical_speed_ {K_START_VERTICAL_SPEED_MPS} private
Referenced by getVerticalSpeed(), stopTravel(), and update().
vertical_acceleration_
double gfs_sim::BalloonPhysics::vertical_acceleration_ {K_START_VERTICAL_ACCELERATION_MPS2} private
Referenced by getVerticalAcceleration(), setVerticalAcceleration(), stopTravel(), update(), and verticalAccelerationVariation().
direction_of_travel_
double gfs_sim::BalloonPhysics::direction_of_travel_ {0.0} private
Referenced by getDirectionOfTravel(), setDirectionOfTravel(), and update().
horizontal_speed_
double gfs_sim::BalloonPhysics::horizontal_speed_ {K_START_HORIZONTAL_SPEED_MPS} private
Referenced by getHorizontalSpeed(), setHorizontalSpeed(), stopTravel(), update(), and updateHorizontal().
total_distance_
double gfs_sim::BalloonPhysics::total_distance_ {0.0} private
Referenced by getTotalDistance(), and updateHorizontal().
distance_since_last_coordinate_
double gfs_sim::BalloonPhysics::distance_since_last_coordinate_ {0.0} private
Referenced by updateHorizontal().
latitude_
double gfs_sim::BalloonPhysics::latitude_ {K_START_LATITUDE} private
Referenced by update(), and updateCoordinates().
longitude_
double gfs_sim::BalloonPhysics::longitude_ {K_START_LONGITUDE} private
Referenced by update(), and updateCoordinates().
state_
SimState& gfs_sim::BalloonPhysics::state_ private
Referenced by stateAscent(), stateDescent(), stateLanding(), stateMachine(), statePop(), statePreLaunch(), and update().
env_
SimEnvironmental& gfs_sim::BalloonPhysics::env_ private
Referenced by update(), and updateHorizontal().
data_
SimData& gfs_sim::BalloonPhysics::data_ private
Referenced by update().