Giraffe: data::DataStream Class Reference
data::DataStream Class Reference
#include <streams.hpp>
Public Member Functions
void addData (node::Identification source, data::DataId data_id, std::string value)
void addPacket (DataPacket packet)
int getNumPackets ()
bool getPacket (DataPacket &packet)
int getTotalPackets ()
void reportStatus (node::Identification status_to_update, node::Status status, data::DataId extra_identifier=data::DataId::MODULE_statusUpdate)
void reset ()
Private Attributes
int current_packets_
std::queue< DataPacket > packet_queue_
std::mutex stream_mutex_
std::atomic< int > total_packets_
Member Function Documentation
addData()
void data::DataStream::addData (node::Identification source, data::DataId data_id, std::string value) inline
References data::Stream< DataPacket >::addPacket(), data::DataPacket::GENERIC, data::DataPacket::identifier, data::BaseStreamPacket::resetTime(), data::BaseStreamPacket::source, data::DataPacket::type, and data::DataPacket::value.
Referenced by FlightRunner::setFlightPhase().
reportStatus()
void data::DataStream::reportStatus (node::Identification status_to_update, node::Status status, data::DataId extra_identifier = data::DataId::MODULE_statusUpdate) inline
References data::Stream< DataPacket >::addPacket(), data::DataPacket::identifier, data::DataPacket::node_status, data::BaseStreamPacket::resetTime(), data::BaseStreamPacket::source, data::DataPacket::STATUS, and data::DataPacket::type.
addPacket()
void data::Stream< DataPacket >::addPacket (DataPacket packet) inline inherited
getPacket()
bool data::Stream< DataPacket >::getPacket (DataPacket & packet) inline inherited
getNumPackets()
int data::Stream< DataPacket >::getNumPackets () inline inherited
getTotalPackets()
int data::Stream< DataPacket >::getTotalPackets () inline inherited
reset()
void data::Stream< DataPacket >::reset () inline inherited
Member Data Documentation
stream_mutex_
std::mutex data::Stream< DataPacket >::stream_mutex_ private inherited
packet_queue_
std::queue<DataPacket > data::Stream< DataPacket >::packet_queue_ private inherited
current_packets_
int data::Stream< DataPacket >::current_packets_ private inherited
total_packets_
std::atomic<int> data::Stream< DataPacket >::total_packets_ private inherited