Giraffe: extension::Bmi088 Class Reference
extension::Bmi088 Class Reference
The BMI088 extension.
#include <bmi088.hpp>
Public Member Functions
Bmi088 (ExtensionResources &resources, cfg::ExtensionMetadata metadata)
~Bmi088 ()
DiagnosticId getFaultCode () const
Get the Fault Code when the status is ERROR.
node::Status getStatus () const
Get the Status of the extension.
bool isFaulted () const
Returns true if the extension is in a faulted state.
void loop () override
void reset ()
Only to be called when an extension is in the Error state. This joins the thread and fixes the status.
void start ()
Starts the extension.
void startup () override
void stop ()
Sends a stop signal to the extension.
Protected Member Functions
template<typename T >
void data (data::DataId identifier, T value, int precision=2)
void data (data::GpsFrame frame)
templates for Extension::data
void data (data::ImuFrame frame)
void date (data::DataId identifier, std::string string_data)
void debug (std::string message)
void error (DiagnosticId log_id, int info)
void error (DiagnosticId, const std::string &info="")
void extSleep (uint32_t milliseconds)
Sleep internally for a given number of milliseconds.
void info (std::string info)
void raiseFault (DiagnosticId ext_fault_code, std::string info="")
Used internally to raise a fault. This will stop an extension.
virtual void shutdown ()
bool stopRequested () const
Returns true if the extension has been requested to stop.
Protected Attributes
cfg::ExtensionMetadata metadata_
Private Member Functions
bool accelerometerHandshake ()
bool configureAccelerometer ()
bool configureGyro ()
bool gyroHandshake ()
bool readAccelData ()
bool readGyroData ()
void runner ()
void sleep ()
Private Attributes
std::string accel_address_ {}
std::atomic< DiagnosticId > fault_code_ = DiagnosticId::EXT_FAULT_none
The fault code associated with the fault.
std::atomic< bool > fault_flag_ = false
This is raised with a call to raiseFault().
std::string gyro_address_ {}
data::ImuFrame imu_data_ {}
ExtensionResources & interfaces_
bst::Timer read_timeout_
std::thread runner_thread_ = std::thread()
giraffe::SpiInterface spi_accel_
giraffe::SpiInterface spi_gyro_
std::atomic< node::Status > status_ = node::Status::STOPPED
std::atomic< bool > stop_flag_ = true
Detailed Description
The BMI088 extension.
This extension reads data from the Bosch BMI088 IMU. This extension uses the SPI interface to communicate with the IMU. The extension metadata must include the SPI device path for both the accelerometer and the gyroscope, separated by a comma. "<accelerometer>/<gyro>" For example: extra_args: "/dev/spidev0.0,/dev/spidev0.1"
Todo:
Accelerometer data.
Constructor & Destructor Documentation
Bmi088()
extension::Bmi088::Bmi088 (ExtensionResources & resources, cfg::ExtensionMetadata metadata)
References accel_address_, cfg::ExtensionMetadata::extra_args, gyro_address_, extension::Extension::metadata_, and extension::Extension::raiseFault().
~Bmi088()
extension::Bmi088::~Bmi088 ()
References giraffe::SpiInterface::closeDevice(), spi_accel_, and spi_gyro_.
Member Function Documentation
startup()
void extension::Bmi088::startup () override virtual
Reimplemented from extension::Extension.
References accel_address_, accelerometerHandshake(), configureAccelerometer(), configureGyro(), gyro_address_, gyroHandshake(), giraffe::SpiInterface::openDevice(), extension::Extension::raiseFault(), read_timeout_, spi_accel_, and spi_gyro_.
loop()
void extension::Bmi088::loop () override virtual
Reimplemented from extension::Extension.
References extension::Extension::data(), imu_data_, extension::Extension::raiseFault(), read_timeout_, readAccelData(), and readGyroData().
accelerometerHandshake()
bool extension::Bmi088::accelerometerHandshake () private
References BMI088_ACCEL_CHIP_ID_ADDR, BMI088_ACCEL_EXP_CHIP_ID, BMI088_READ_FLAG, extension::Extension::extSleep(), HANDSHAKE_ATTEMPTS, HANDSHAKE_RETRY_DELAY_MS, spi_accel_, and giraffe::SpiInterface::transfer().
Referenced by startup().
gyroHandshake()
bool extension::Bmi088::gyroHandshake () private
References BMI088_GYRO_CHIP_ID_ADDR, BMI088_GYRO_EXP_CHIP_ID, BMI088_READ_FLAG, extension::Extension::extSleep(), HANDSHAKE_ATTEMPTS, HANDSHAKE_RETRY_DELAY_MS, spi_gyro_, and giraffe::SpiInterface::transfer().
Referenced by startup().
configureAccelerometer()
bool extension::Bmi088::configureAccelerometer () private
References BMI088_ACC_PWR_CONF_ADDR, BMI088_ACC_PWR_CONF_VAL, BMI088_ACC_PWR_CTRL_ADDR, BMI088_ACC_PWR_CTRL_VAL, BMI088_WRITE_FLAG, spi_accel_, and giraffe::SpiInterface::transfer().
Referenced by startup().
configureGyro()
bool extension::Bmi088::configureGyro () private
References BMI088_GYRO_BW_ADDR, BMI088_GYRO_BW_VAL, BMI088_GYRO_RANGE_ADDR, BMI088_GYRO_RANGE_VAL, BMI088_WRITE_FLAG, spi_gyro_, and giraffe::SpiInterface::transfer().
Referenced by startup().
readGyroData()
bool extension::Bmi088::readGyroData () private
References BMI088_GYRO_RANGE, BMI088_READ_FLAG, BMI088_READ_GYRO_DATA_ADDR, imu_data_, spi_gyro_, giraffe::SpiInterface::transfer(), data::ImuFrame::x_angular_velocity, data::ImuFrame::y_angular_velocity, and data::ImuFrame::z_angular_velocity.
Referenced by loop().
readAccelData()
bool extension::Bmi088::readAccelData () private
References BMI088_READ_ACCEL_DATA_ADDR, BMI088_READ_FLAG, imu_data_, spi_gyro_, giraffe::SpiInterface::transfer(), data::ImuFrame::x_acceleration, data::ImuFrame::y_acceleration, and data::ImuFrame::z_acceleration.
Referenced by loop().
start()
void extension::Extension::start () inherited
Starts the extension.
References extension::Extension::error(), extension::Extension::fault_code_, extension::Extension::fault_flag_, node::K_ACTIVE_STATUSES, extension::Extension::runner(), extension::Extension::runner_thread_, extension::Extension::status_, and extension::Extension::stop_flag_.
stop()
void extension::Extension::stop () inherited
Sends a stop signal to the extension.
The timeout for stopping an extension.
The interval of how often to check if the extension has stopped.
References extension::Extension::error(), node::K_INACTIVE_STATUSES, extension::Extension::runner_thread_, extension::Extension::status_, and extension::Extension::stop_flag_.
Referenced by extension::Extension::~Extension(), and extension::Extension::reset().
reset()
void extension::Extension::reset () inherited
Only to be called when an extension is in the Error state. This joins the thread and fixes the status.
References extension::Extension::status_, extension::Extension::stop(), and node::STOPPED.
getStatus()
node::Status extension::Extension::getStatus () const inline inherited
Get the Status of the extension.
Returns
node::Status The status of the extension.
References extension::Extension::status_.
getFaultCode()
DiagnosticId extension::Extension::getFaultCode () const inline inherited
Get the Fault Code when the status is ERROR.
Returns
DiagnosticId The fault code.
References extension::Extension::fault_code_.
isFaulted()
bool extension::Extension::isFaulted () const inline inherited
Returns true if the extension is in a faulted state.
Returns
true if the extension is in a faulted state, false otherwise.
References extension::Extension::fault_flag_.
Referenced by extension::AdcExtensionBase< AdcResolution >::startup().
shutdown()
virtual void extension::Extension::shutdown () inline protected virtual inherited
Reimplemented in extension::SamM8q, extension::RgbStatusLed, extension::PiCamera, extension::AdcExtensionBase< AdcResolution >, and extension::AdcExtensionBase< 10 >.
Referenced by extension::Extension::runner().
data() [1/3]
template<typename T > void extension::Extension::data (data::DataId identifier, T value, int precision = 2) protected inherited
References data::Stream< T >::addPacket(), data::Streams::data, data::DataPacket::identifier, extension::Extension::interfaces_, kExtensionId, extension::Extension::metadata_, cfg::ExtensionMetadata::name, data::BaseStreamPacket::secondary_identifier, data::BaseStreamPacket::source, extension::ExtensionResources::streams, util::to_string(), and data::DataPacket::value.
Referenced by extension::AdcExtensionBase< AdcResolution >::loop(), extension::Bme280::loop(), loop(), extension::Ds18b20::loop(), extension::PiCamera::loop(), extension::AdcExtensionBase< AdcResolution >::percentage(), extension::Bme280::readEnvironmentalData(), extension::SamM8q::stateRead(), extension::AdcExtensionBase< AdcResolution >::voltageDivider(), and extension::AdcExtensionBase< AdcResolution >::voltageReference().
data() [2/3]
void extension::Extension::data (data::GpsFrame frame) protected inherited
templates for Extension::data
 */
template void Extension::data<int>(data::DataId, int, int);
template void Extension::data<float>(data::DataId, float, int);
template void Extension::data<double>(data::DataId, double, int);
template void Extension::data<uint32_t>(data::DataId, uint32_t, int);
template void Extension::data<std::string>(data::DataId, std::string, int);
/**
 *
References data::GpsFrameStream::addFrame(), node::EXTENSION, data::Streams::gps, extension::Extension::interfaces_, extension::Extension::metadata_, cfg::ExtensionMetadata::name, and extension::ExtensionResources::streams.
data() [3/3]
void extension::Extension::data (data::ImuFrame frame) protected inherited
References data::ImuFrameStream::addFrame(), node::EXTENSION, data::Streams::imu, extension::Extension::interfaces_, extension::Extension::metadata_, cfg::ExtensionMetadata::name, and extension::ExtensionResources::streams.
date()
void extension::Extension::date (data::DataId identifier, std::string string_data) protected inherited
error() [1/2]
void extension::Extension::error (DiagnosticId log_id, const std::string & info = "") protected inherited
References data::Stream< T >::addPacket(), data::LogPacket::ERROR, data::LogPacket::id, data::LogPacket::info, extension::Extension::interfaces_, kExtensionId, data::LogPacket::level, data::Streams::log, extension::Extension::metadata_, cfg::ExtensionMetadata::name, data::BaseStreamPacket::secondary_identifier, data::BaseStreamPacket::source, and extension::ExtensionResources::streams.
Referenced by extension::AdcExtensionBase< AdcResolution >::AdcExtensionBase(), extension::PiCamera::PiCamera(), extension::Mcp3021::adcStartup(), extension::Bme280::loop(), extension::Ds18b20::loop(), extension::PiCamera::loop(), extension::Bme280::processEnvironmentalData(), extension::Extension::raiseFault(), extension::Extension::start(), extension::SamM8q::stateConfigure(), extension::SamM8q::stateRead(), and extension::Extension::stop().
error() [2/2]
void extension::Extension::error (DiagnosticId log_id, int info) protected inherited
References data::Stream< T >::addPacket(), data::LogPacket::ERROR, data::LogPacket::id, extension::Extension::info(), data::LogPacket::info, extension::Extension::interfaces_, kExtensionId, data::LogPacket::level, data::Streams::log, extension::Extension::metadata_, cfg::ExtensionMetadata::name, data::BaseStreamPacket::secondary_identifier, data::BaseStreamPacket::source, extension::ExtensionResources::streams, and util::to_string().
info()
void extension::Extension::info (std::string info) protected inherited
References data::Stream< T >::addPacket(), data::LogPacket::id, data::LogPacket::INFO, data::LogPacket::info, extension::Extension::interfaces_, kExtensionId, data::LogPacket::level, data::Streams::log, extension::Extension::metadata_, cfg::ExtensionMetadata::name, data::BaseStreamPacket::secondary_identifier, data::BaseStreamPacket::source, and extension::ExtensionResources::streams.
Referenced by extension::Extension::debug(), and extension::Extension::error().
debug()
void extension::Extension::debug (std::string message) protected inherited
References data::Stream< T >::addPacket(), data::LogPacket::DEBUG, data::LogPacket::id, extension::Extension::info(), data::LogPacket::info, extension::Extension::interfaces_, kExtensionId, data::LogPacket::level, data::Streams::log, extension::Extension::metadata_, cfg::ExtensionMetadata::name, data::BaseStreamPacket::secondary_identifier, data::BaseStreamPacket::source, and extension::ExtensionResources::streams.
Referenced by extension::RgbStatusLed::RgbStatusLed(), extension::PiCamera::loop(), and extension::SamM8q::stateRead().
stopRequested()
bool extension::Extension::stopRequested () const protected inherited
Returns true if the extension has been requested to stop.
This should be used in the loop() function for extensions that take a long time to complete a single loop iteration. This is helpful for to stop extensions quickly upon request. Fast extensions do not need to use this.
Returns
true - The extension has been requested to stop.
false - The extension has not been requested to stop.
References extension::Extension::stop_flag_.
Referenced by extension::Extension::sleep(), extension::Bme280::startup(), extension::Ds18b20::startup(), and extension::SamM8q::startup().
raiseFault()
void extension::Extension::raiseFault (DiagnosticId ext_fault_code, std::string info = "") protected inherited
Used internally to raise a fault. This will stop an extension.
References extension::Extension::error(), extension::Extension::fault_code_, extension::Extension::fault_flag_, and extension::Extension::stop_flag_.
Referenced by Bmi088(), extension::RgbStatusLed::RgbStatusLed(), extension::Mcp3021::adcStartup(), extension::AdcExtensionBase< AdcResolution >::loop(), extension::Bme280::loop(), loop(), extension::Ds18b20::loop(), extension::PiCamera::loop(), extension::RgbStatusLed::shutdown(), extension::Bme280::startup(), startup(), extension::Ds18b20::startup(), extension::PiCamera::startup(), extension::RgbStatusLed::startup(), extension::SamM8q::startup(), and extension::SamM8q::stateReset().
extSleep()
void extension::Extension::extSleep (uint32_t milliseconds) protected inherited
Sleep internally for a given number of milliseconds.
This has a limit of 1 second.
Parameters
milliseconds - The number of milliseconds to sleep.
Referenced by accelerometerHandshake(), gyroHandshake(), extension::Bme280::startup(), extension::Ds18b20::startup(), extension::SamM8q::startup(), and extension::SamM8q::stateRead().
sleep()
void extension::Extension::sleep () private inherited
References extension::Extension::metadata_, extension::Extension::stopRequested(), and cfg::ExtensionMetadata::update_interval.
Referenced by extension::Extension::runner().
runner()
void extension::Extension::runner () private inherited
References node::ERROR, extension::Extension::fault_flag_, extension::Extension::loop(), node::RUNNING, extension::Extension::shutdown(), extension::Extension::sleep(), node::STARTING, extension::Extension::startup(), extension::Extension::status_, extension::Extension::stop_flag_, node::STOPPED, and node::STOPPING.
Referenced by extension::Extension::start().
Member Data Documentation
accel_address_
std::string extension::Bmi088::accel_address_ {} private
Referenced by Bmi088(), and startup().
gyro_address_
std::string extension::Bmi088::gyro_address_ {} private
Referenced by Bmi088(), and startup().
spi_accel_
giraffe::SpiInterface extension::Bmi088::spi_accel_ private
Referenced by ~Bmi088(), accelerometerHandshake(), configureAccelerometer(), and startup().
spi_gyro_
giraffe::SpiInterface extension::Bmi088::spi_gyro_ private
Referenced by ~Bmi088(), configureGyro(), gyroHandshake(), readAccelData(), readGyroData(), and startup().
read_timeout_
bst::Timer extension::Bmi088::read_timeout_ private
Referenced by loop(), and startup().
imu_data_
data::ImuFrame extension::Bmi088::imu_data_ {} private
Referenced by loop(), readAccelData(), and readGyroData().
metadata_
cfg::ExtensionMetadata extension::Extension::metadata_ protected inherited
Referenced by Bmi088(), extension::Extension::data(), extension::Extension::debug(), extension::Extension::error(), extension::Extension::info(), extension::Ds18b20::init(), and extension::Extension::sleep().
fault_flag_
std::atomic<bool> extension::Extension::fault_flag_ = false private inherited
This is raised with a call to raiseFault().
This is used to stop the extension. Cleared on a call to start().
Referenced by extension::Extension::isFaulted(), extension::Extension::raiseFault(), extension::Extension::runner(), and extension::Extension::start().
fault_code_
std::atomic<DiagnosticId> extension::Extension::fault_code_ = DiagnosticId::EXT_FAULT_none private inherited
The fault code associated with the fault.
This is set when raiseFault() is called. Cleared on a call to start().
Referenced by extension::Extension::getFaultCode(), extension::Extension::raiseFault(), and extension::Extension::start().
status_
std::atomic<node::Status> extension::Extension::status_ = node::Status::STOPPED private inherited
Referenced by extension::Extension::getStatus(), extension::Extension::reset(), extension::Extension::runner(), extension::Extension::start(), and extension::Extension::stop().
stop_flag_
std::atomic<bool> extension::Extension::stop_flag_ = true private inherited
Referenced by extension::Extension::raiseFault(), extension::Extension::runner(), extension::Extension::start(), extension::Extension::stop(), and extension::Extension::stopRequested().
runner_thread_
std::thread extension::Extension::runner_thread_ = std::thread() private inherited
Referenced by extension::Extension::start(), and extension::Extension::stop().
interfaces_
ExtensionResources& extension::Extension::interfaces_ private inherited
Referenced by extension::Extension::data(), extension::Extension::debug(), extension::Extension::error(), and extension::Extension::info().