Giraffe: GiraffeException Class Reference
GiraffeException Class Reference
#include <giraffe_exception.hpp>
Public Member Functions
GiraffeException (const DiagnosticId diagnostic_id, const std::string &info="")
DiagnosticId id () const throw ()
std::string info () const throw ()
const char * what () const override throw ()
Private Attributes
DiagnosticId diagnostic_id_
std::string info_
Constructor & Destructor Documentation
GiraffeException()
GiraffeException::GiraffeException (const DiagnosticId diagnostic_id, const std::string & info = "")
Member Function Documentation
id()
DiagnosticId GiraffeException::id () const throw ()
References diagnostic_id_.
Referenced by extension::PiCamera::PiCamera().
info()
std::string GiraffeException::info () const throw ()
References info_.
what()
const char * GiraffeException::what () const throw () override
References diagnostic_id_, hexString(), and info_.
Referenced by extension::RgbStatusLed::shutdown(), and extension::RgbStatusLed::startup().
Member Data Documentation
diagnostic_id_
DiagnosticId GiraffeException::diagnostic_id_ private
Referenced by id(), and what().
info_
std::string GiraffeException::info_ private
Referenced by info(), and what().