Giraffe: command_processor.cpp File Reference
command_processor.cpp File Reference
Used for parsing and processing commands.
#include "command.hpp"
#include <array>
#include <iostream>
#include <regex>
#include <unordered_map>
Functions
bool hexStringToUInt32 (const std::string &hex_string, uint32_t &hex_string_value)
Returns the value of a hex string as a uint32_t.
bool parseConfigurationCommand (const std::string &command_id_str, const std::string &arg, cmd::Command &command)
bool parseConsoleModuleCommand (const std::string &command_id_str, const std::string &arg, cmd::Command &command)
bool parseDataModuleCommand (const std::string &command_id_str, const std::string &arg, cmd::Command &command)
bool parseExtensionCommand (const std::string &command_id_str, const std::string &arg, cmd::Command &command)
bool parseExtensionModuleCommand (const std::string &command_id_str, const std::string &arg, cmd::Command &command)
bool parseFlightRunnerCommand (const std::string &command_id_str, const std::string &arg, cmd::Command &command)
bool parseServerModuleCommand (const std::string &command_id_str, const std::string &arg, cmd::Command &command)
bool parseSystemModuleCommand (const std::string &command_id_str, const std::string &arg, cmd::Command &command)
bool parseTelemetryModuleCommand (const std::string &command_id_str, const std::string &arg, cmd::Command &command)
Variables
static const std::unordered_map< std::string, node::Identification > K_DESTINATION_MAP
static const std::array< std::string, 6 > K_MODULE_IDENTIFIERS
Detailed Description
Used for parsing and processing commands.
=*========GIRAFFE========*= A Unified Flight Command and Control System https://github.com/joshua-jerred/Giraffe https://giraffe.joshuajer.red/ =*=======================*=
=*=======================*=
Author
Joshua Jerred (https://joshuajer.red)
Date
2023-11-03
Copyright
2023 (license to be defined)
Function Documentation
hexStringToUInt32()
bool hexStringToUInt32 (const std::string & hex_string, uint32_t & hex_string_value)
Returns the value of a hex string as a uint32_t.
Parameters
hex_string The hex string to convert.
hex_string_value (out) The value of the hex string.
Returns
true If the hex string was converted successfully.
false If the hex string was not converted successfully.
Referenced by parseDataModuleCommand().
parseFlightRunnerCommand()
bool parseFlightRunnerCommand (const std::string & command_id_str, const std::string & arg, cmd::Command & command)
Todo:
need to implement some kind of rolling authentication system for some of these commands.
References cmd::Command::command_id, cmd::Command::int_arg, K_MODULE_IDENTIFIERS, and cmd::Command::str_arg.
Referenced by cmd::parseCommandString().
parseConfigurationCommand()
bool parseConfigurationCommand (const std::string & command_id_str, const std::string & arg, cmd::Command & command)
Referenced by cmd::parseCommandString().
parseDataModuleCommand()
bool parseDataModuleCommand (const std::string & command_id_str, const std::string & arg, cmd::Command & command)
References cmd::Command::command_id, hexStringToUInt32(), and cmd::Command::int_arg.
Referenced by cmd::parseCommandString().
parseServerModuleCommand()
bool parseServerModuleCommand (const std::string & command_id_str, const std::string & arg, cmd::Command & command)
Referenced by cmd::parseCommandString().
parseConsoleModuleCommand()
bool parseConsoleModuleCommand (const std::string & command_id_str, const std::string & arg, cmd::Command & command)
Referenced by cmd::parseCommandString().
parseSystemModuleCommand()
bool parseSystemModuleCommand (const std::string & command_id_str, const std::string & arg, cmd::Command & command)
Referenced by cmd::parseCommandString().
parseExtensionModuleCommand()
bool parseExtensionModuleCommand (const std::string & command_id_str, const std::string & arg, cmd::Command & command)
References cmd::Command::command_id.
Referenced by cmd::parseCommandString().
parseExtensionCommand()
bool parseExtensionCommand (const std::string & command_id_str, const std::string & arg, cmd::Command & command)
Referenced by cmd::parseCommandString().
parseTelemetryModuleCommand()
bool parseTelemetryModuleCommand (const std::string & command_id_str, const std::string & arg, cmd::Command & command)
References cmd::Command::command_id.
Referenced by cmd::parseCommandString().
Variable Documentation
K_DESTINATION_MAP
const std::unordered_map<std::string, node::Identification> K_DESTINATION_MAP static
Initial value:
= {{"flr", node::Identification::FLIGHT_RUNNER},
                         {"cfg", node::Identification::CONFIGURATION},
                         {"dat", node::Identification::DATA_MODULE},
                         {"csl", node::Identification::CONSOLE_MODULE},
                         {"srv", node::Identification::SERVER_MODULE},
                         {"sys", node::Identification::SYSTEM_MODULE},
                         {"etm", node::Identification::EXTENSION_MODULE},
                         {"ext", node::Identification::EXTENSION},
                         {"tlm", node::Identification::TELEMETRY_MODULE}}
Referenced by cmd::parseCommandString().
K_MODULE_IDENTIFIERS
const std::array<std::string, 6> K_MODULE_IDENTIFIERS static
Initial value:
= {
    "dat", "csl", "srv", "sys", "etm", "tlm"}
Referenced by parseFlightRunnerCommand().