services:
  structurizr:
    image: structurizr/lite
    ports:
      - '8080:8080'
    volumes:
      - "./docs/structurizr:/usr/local/structurizr:Z"

  build_giraffe:
    image: pi_zero_gcc:latest
    volumes:
      - .:/project
    command: "bash ./project/docker_build.sh giraffe_flight_system"