Giraffe: console_module.cpp File Reference
console_module.cpp File Reference
#include <functional>
#include "console_module.hpp"
Variables
constexpr int kConsoleUpdateRate = 50
static modules::MetaData metadata ("console_module", node::Identification::CONSOLE_MODULE, kConsoleUpdateRate)
Variable Documentation
kConsoleUpdateRate
constexpr int kConsoleUpdateRate = 50 inline constexpr
The update interval is manually set to 50ms in this module. This is for keyboard input processing. In the configuration there is still a sleep interval that is used for actually updating the data.
metadata
modules::MetaData metadata("console_module", node::Identification::CONSOLE_MODULE, kConsoleUpdateRate) ("console_module" , node::Identification::CONSOLE_MODULE , kConsoleUpdateRate) static
Referenced by extension::AdcExtensionBase< AdcResolution >::AdcExtensionBase(), extension::I2cExtensionAdapter::I2cExtensionAdapter(), and cfg::Extensions::addExtension().