Giraffe: console_pages.cpp File Reference
console_pages.cpp File Reference
#include "console_pages.hpp"
#include <BoosterSeat/numbers.hpp>
#include <BoosterSeat/string_formatting.hpp>
#include <BoosterSeat/time.hpp>
#include <functional>
Functions
std::string b2str (bool val)
std::string f2s (double val)
std::string LandR (const std::string &l, const std::string &r)
Helper function to format two strings to be left and right aligned within the console window.
std::string title_and_data (std::string title, std::string data)
Variables
auto rnd = BoosterSeat::doubleToPrecisionTwo
Function Documentation
b2str()
std::string b2str (bool val) inline
Referenced by console_pages::Pages::data(), console_pages::Pages::server(), and console_pages::Pages::telemetry().
title_and_data()
std::string title_and_data (std::string title, std::string data) inline
f2s()
std::string f2s (double val)
Referenced by console_pages::Pages::gfsStatus(), console_pages::Pages::location(), console_pages::Pages::server(), console_pages::Pages::system(), console_pages::Pages::telemetry(), and util::to_string().
LandR()
std::string LandR (const std::string & l, const std::string & r)
Helper function to format two strings to be left and right aligned within the console window.
Parameters
l - left string
r - right string
Returns
std::string - formatted string
References console_pages::K_DATA_WINDOW_WIDTH.
Referenced by console_pages::Pages::data(), and console_pages::Pages::gfsStatus().
Variable Documentation
rnd
auto rnd = BoosterSeat::doubleToPrecisionTwo inline