Giraffe: test.cpp File Reference
flight_system/old/test-08/test.cpp File Reference
Tests for the UBX Utility.
#include <mutex>
#include "gtest/gtest.h"
#include "ubx.h"
Classes
class UBXTest
Macros
#define BUS_NUMBER 1
#define DEVICE_ADDRESS 0x42
#define VISUALIZATION true
Functions
std::ostream & operator<< (std::ostream &o, const ubx::UBXMessage &ubx)
TEST_F (UBXTest, UBXDetectWriteError)
TEST_F (UBXTest, UBXFullConfigTest)
TEST_F (UBXTest, UBXGenerateAndDetectNAK)
TEST_F (UBXTest, UBXMessageTest)
TEST_F (UBXTest, UBXNoACK)
TEST_F (UBXTest, UBXSetDDCandAckTest)
Detailed Description
Tests for the UBX Utility.
Author
Joshua Jerred (https://joshuajer.red/)
Date
2022-12-26
Copyright
Copyright (c) 2022
Version
0.1.0
Macro Definition Documentation
BUS_NUMBER
#define BUS_NUMBER 1
DEVICE_ADDRESS
#define DEVICE_ADDRESS 0x42
VISUALIZATION
#define VISUALIZATION true
Function Documentation
operator<<()
std::ostream& operator<< (std::ostream & o, const ubx::UBXMessage & ubx)
TEST_F() [1/6]
TEST_F (UBXTest , UBXMessageTest)
References ubx::UBXMessage::ck_a, ubx::UBXMessage::ck_b, ubx::UBXMessage::length, ubx::UBXMessage::mClass, and ubx::UBXMessage::mID.
TEST_F() [2/6]
TEST_F (UBXTest , UBXSetDDCandAckTest)
References ubx::ACK, BUS_NUMBER, DEVICE_ADDRESS, ubx::getStreamSize(), ubx::NACK, ubx::NONE, ubx::setProtocolDDC(), and ubx::WRITE_ERROR.
TEST_F() [3/6]
TEST_F (UBXTest , UBXGenerateAndDetectNAK)
References ubx::ACK, BUS_NUMBER, ubx::checkForAck(), DEVICE_ADDRESS, ubx::NACK, ubx::NONE, and ubx::writeUBX().
TEST_F() [4/6]
TEST_F (UBXTest , UBXDetectWriteError)
References ubx::setProtocolDDC(), and ubx::WRITE_ERROR.
TEST_F() [5/6]
TEST_F (UBXTest , UBXNoACK)
References ubx::ACK, BUS_NUMBER, ubx::checkForAck(), DEVICE_ADDRESS, ubx::NACK, and ubx::NONE.
TEST_F() [6/6]
TEST_F (UBXTest , UBXFullConfigTest)
References ubx::ACK, ubx::AIRBORNE_1G, BUS_NUMBER, DEVICE_ADDRESS, ubx::kNavPvt, ubx::sendResetCommand(), ubx::setDynamicModel(), ubx::setMeasurementRate(), ubx::setMessageRate(), and ubx::setProtocolDDC().