Giraffe: test.cpp File Reference
flight_system/old/test-09/test.cpp File Reference
u-blox UBX Manual Test
#include <chrono>
#include <iostream>
#include <mutex>
#include <string>
#include <thread>
#include <unistd.h>
#include <unordered_map>
#include "ubx.h"
Macros
#define BUS_NUMBER 1
#define DEVICE_ADDRESS 0x42
Functions
int main ()
Detailed Description
u-blox UBX Manual Test
Author
Joshua Jerred (https://joshuajer.red/)
Date
2022-12-26
Copyright
Copyright (c) 2022
Version
0.1.0
Macro Definition Documentation
BUS_NUMBER
#define BUS_NUMBER 1
DEVICE_ADDRESS
#define DEVICE_ADDRESS 0x42
Function Documentation
main()
int main ()
Todo:
this needs a timeout
References ubx::ACK, ubx::AIRBORNE_1G, BUS_NUMBER, DEVICE_ADDRESS, ubx::flushStream(), ubx::getStreamSize(), ubx::kNavPvt, ubx::parsePVT(), ubx::pollMessage(), ubx::sendResetCommand(), ubx::setDynamicModel(), ubx::setMeasurementRate(), and ubx::setProtocolDDC().