Giraffe: gdl_terminal.cpp File Reference
gdl_terminal.cpp File Reference
GDL Terminal.
#include <chrono>
#include <iostream>
#include <sys/types.h>
#include <thread>
#include "gdl_message.hpp"
#include "giraffe_data_link.hpp"
#include "software_physical_layer.hpp"
Functions
int main (int argc, char **argv)
void userInput (std::atomic< bool > &running, std::mutex &input_mutex, std::string &input)
Detailed Description
GDL Terminal.
=*========GIRAFFE========*= A Unified Flight Command and Control System https://github.com/joshua-jerred/Giraffe https://giraffe.joshuajer.red/ =*=======================*=
=*=======================*=
Author
Joshua Jerred (https://joshuajer.red)
Date
2024-01-18
Copyright
2024 (license to be defined)
Function Documentation
userInput()
void userInput (std::atomic< bool > & running, std::mutex & input_mutex, std::string & input)
Referenced by main().
main()
int main (int argc, char ** argv)
References giraffe::gdl::Message::BROADCAST, config, giraffe::gdl::Message::EXCHANGE, giraffe::gdl::Message::getData(), giraffe::gdl::Message::getType(), giraffe::gdl::Message::setBroadcastMessage(), giraffe::gdl::Message::setExchangeMessage(), giraffe::gdl::Message::TELEMETRY, and userInput().