Giraffe: gpio.cpp File Reference
gpio.cpp File Reference
GPIO interface source file.
#include <fcntl.h>
#include <sys/mman.h>
#include <unistd.h>
#include "giraffe_exception.hpp"
#include "gpio.hpp"
Namespaces
giraffe
Functions
volatile uint32_t * calculateAddress (uint8_t offset, uint8_t pin)
uint32_t readWithBarrier (volatile uint32_t *address)
Reads a value from a memory address with a memory barrier. [https://www.airspayce.com/mikem/bcm2835/index.html].
bool verifyInitialized ()
A function to check if the BCM GPIO registers have been mapped.
void writeWithBarrier (volatile uint32_t *address, uint32_t value)
Writes a value to a memory address with a memory barrier. [https://www.airspayce.com/mikem/bcm2835/index.html].
Variables
static const uint32_t GPIO_MEMORY_MAP_SIZE = 0x1000
Size of the memory map, one page.
constexpr uint8_t giraffe::MAX_PIN_NUMBER = 27
static volatile uint32_t * s_gpio_memory_map = (uint32_t *)MAP_FAILED
The Gpio memory map is used store the mapping to the BCM registers.
Detailed Description
GPIO interface source file.
=*========GIRAFFE========*= A Unified Flight Command and Control System https://github.com/joshua-jerred/Giraffe https://giraffe.joshuajer.red/ =*=======================*=
=*=======================*=
Author
Joshua Jerred (https://joshuajer.red)
Date
2024-01-24
Copyright
2024 (license to be defined)
Function Documentation
verifyInitialized()
bool verifyInitialized ()
A function to check if the BCM GPIO registers have been mapped.
This function is not thread safe, the caller must lock the mutex prior to calling this function.
Returns
true Mapped, GPIO is ready to use.
false Not mapped.
References s_gpio_memory_map.
Referenced by giraffe::Gpio::isInitialized(), giraffe::Gpio::read(), giraffe::Gpio::setupPin(), and giraffe::Gpio::write().
writeWithBarrier()
void writeWithBarrier (volatile uint32_t * address, uint32_t value)
Writes a value to a memory address with a memory barrier. [https://www.airspayce.com/mikem/bcm2835/index.html].
Parameters
address The address to write to.
value The value to write.
Referenced by giraffe::Gpio::setupPin(), and giraffe::Gpio::write().
readWithBarrier()
uint32_t readWithBarrier (volatile uint32_t * address)
Reads a value from a memory address with a memory barrier. [https://www.airspayce.com/mikem/bcm2835/index.html].
Parameters
address The address to read from.
Returns
uint32_t The value read from the address.
Referenced by giraffe::Gpio::read(), and giraffe::Gpio::setupPin().
calculateAddress()
volatile uint32_t* calculateAddress (uint8_t offset, uint8_t pin)
References s_gpio_memory_map.
Referenced by giraffe::Gpio::read(), and giraffe::Gpio::write().
Variable Documentation
s_gpio_memory_map
volatile uint32_t* s_gpio_memory_map = (uint32_t *)MAP_FAILED static
The Gpio memory map is used store the mapping to the BCM registers.
[https://datasheets.raspberrypi.com/bcm2835/bcm2835-peripherals.pdf] [https://www.airspayce.com/mikem/bcm2835/index.html] [https://github.com/youngkin/gpio/blob/main/ledblink/bcmfuncs.c]
Initialized in Gpio::Initialize().
Referenced by calculateAddress(), giraffe::Gpio::deInitialize(), giraffe::Gpio::initialize(), giraffe::Gpio::setupPin(), and verifyInitialized().
GPIO_MEMORY_MAP_SIZE
const uint32_t GPIO_MEMORY_MAP_SIZE = 0x1000 static
Size of the memory map, one page.
Todo:
I need to find a source for this.
Referenced by giraffe::Gpio::deInitialize(), and giraffe::Gpio::initialize().