Giraffe: Flight Runner Console Helpers
Flight Runner Console Helpers
These are helper functions to print out startup and shutdown messages.
Functions
void _disabled (const std::string &module_name)
void _done ()
void _start (const std::string &module_name)
void _stop (const std::string &module_name)
Detailed Description
These are helper functions to print out startup and shutdown messages.
Function Documentation
_start()
void _start (const std::string & module_name) inline
_done()
void _done () inline
Referenced by FlightRunner::~FlightRunner().
_disabled()
void _disabled (const std::string & module_name) inline
Referenced by FlightRunner::~FlightRunner().
_stop()
void _stop (const std::string & module_name) inline
Referenced by FlightRunner::~FlightRunner().