Giraffe: SAM-M8Q State Machine
SAM-M8Q State Machine
The SAM-M8Q state machine.
Enumerations
enum class extension::SamM8q::ReadState { extension::SamM8q::READ_PACKET , extension::SamM8q::WAIT }
enum class extension::SamM8q::ResetState { extension::SamM8q::SEND_RESET , extension::SamM8q::WAIT , extension::SamM8q::HANDSHAKE }
enum class extension::SamM8q::State { extension::SamM8q::CONFIGURE , extension::SamM8q::RESET , extension::SamM8q::READ }
Functions
void extension::SamM8q::stateConfigure ()
void extension::SamM8q::stateRead ()
void extension::SamM8q::stateReset ()
void extension::SamM8q::transitionState (State new_state)
Variables
ReadState extension::SamM8q::read_state_ = ReadState::WAIT
ResetState extension::SamM8q::reset_state_ = ResetState::SEND_RESET
State extension::SamM8q::state_ = State::CONFIGURE
Detailed Description
The SAM-M8Q state machine.
See also
sam_m8q_gps_state_machine.puml
Enumeration Type Documentation
State
enum extension::SamM8q::State strong private
Enumerator
CONFIGURE
RESET
READ
ResetState
enum extension::SamM8q::ResetState strong private
Enumerator
SEND_RESET
WAIT
HANDSHAKE
ReadState
enum extension::SamM8q::ReadState strong private
Enumerator
READ_PACKET
WAIT
Function Documentation
transitionState()
void extension::SamM8q::transitionState (State new_state) private
References extension::SamM8q::CONFIGURE, extension::Extension::debug(), extension::SamM8q::READ, extension::SamM8q::read_state_, extension::SamM8q::read_watchdog_timer_, extension::SamM8q::RESET, extension::SamM8q::reset_state_, extension::SamM8q::SEND_RESET, extension::SamM8q::state_, and extension::SamM8q::WAIT.
Referenced by extension::SamM8q::stateConfigure(), extension::SamM8q::stateRead(), and extension::SamM8q::stateReset().
stateConfigure()
void extension::SamM8q::stateConfigure () private
Allow each command to be sent up to 3 times before giving up.
Todo:
Read the configuration data and verify
References ubx::ACK, ubx::AIRBORNE_1G, extension::Extension::debug(), extension::Extension::error(), extension::SamM8q::i2c_, extension::SamM8q::READ, extension::SamM8q::RESET, ubx::setDynamicModel(), ubx::setMeasurementRate(), ubx::setProtocolDDC(), and extension::SamM8q::transitionState().
Referenced by extension::SamM8q::loop().
stateReset()
void extension::SamM8q::stateReset () private
References extension::SamM8q::CONFIGURE, extension::Extension::debug(), extension::SamM8q::HANDSHAKE, extension::SamM8q::handshake(), extension::SamM8q::i2c_, extension::Extension::raiseFault(), extension::SamM8q::reset_attempts_, extension::SamM8q::reset_state_, extension::SamM8q::reset_wait_timer_, extension::SamM8q::SEND_RESET, ubx::sendResetCommand(), extension::SamM8q::transitionState(), and extension::SamM8q::WAIT.
Referenced by extension::SamM8q::loop().
stateRead()
void extension::SamM8q::stateRead () private
Todo:
document the +1 hour, why is this done?
References ubx::NavData::altitude, data::GpsFrame::altitude, extension::Extension::data(), ubx::NavData::day, extension::Extension::debug(), extension::Extension::error(), data::ERROR, extension::Extension::extSleep(), data::GpsFrame::fix, ubx::FIX_2D, data::FIX_2D, ubx::FIX_3D, data::FIX_3D, ubx::NavData::fix_type, ubx::flushStream(), data::GpsFrame::gps_utc_time, ubx::NavData::ground_speed, ubx::NavData::heading_accuracy, data::GpsFrame::heading_accuracy, ubx::NavData::heading_of_motion, data::GpsFrame::heading_of_motion, data::GpsFrame::horizontal_speed, ubx::NavData::horz_accuracy, data::GpsFrame::horz_accuracy, ubx::NavData::hour, extension::SamM8q::i2c_, data::GpsFrame::is_valid, ubx::kNavClassId, ubx::kNavPvt, ubx::NavData::latitude, data::GpsFrame::latitude, ubx::NavData::longitude, data::GpsFrame::longitude, ubx::NavData::minute, ubx::NavData::month, ubx::NO_FIX, data::NO_FIX, ubx::NavData::num_satellites, data::GpsFrame::num_satellites, ubx::parsePVT(), ubx::pollMessage(), extension::SamM8q::read_watchdog_timer_, extension::SamM8q::RESET, ubx::NavData::second, ubx::NavData::speed_accuracy, data::GpsFrame::speed_accuracy, extension::SamM8q::transitionState(), ubx::NavData::valid, ubx::NavData::vert_accuracy, data::GpsFrame::vert_accuracy, and ubx::NavData::year.
Referenced by extension::SamM8q::loop().
Variable Documentation
state_
State extension::SamM8q::state_ = State::CONFIGURE private
Referenced by extension::SamM8q::loop(), and extension::SamM8q::transitionState().
reset_state_
ResetState extension::SamM8q::reset_state_ = ResetState::SEND_RESET private
Referenced by extension::SamM8q::stateReset(), and extension::SamM8q::transitionState().
read_state_
ReadState extension::SamM8q::read_state_ = ReadState::WAIT private
Referenced by extension::SamM8q::transitionState().