Giraffe: .Filesystem
.Filesystem
Used to generate the file structure and manage the log files.
Functions
void data_middleware::DataLog::appendToFile (const std::string &path, const std::string &data, const DiagnosticId error_id)
Attempts to append data to a file. Only checks the file validity.
bool data_middleware::DataLog::archiveFile (const std::string &file_path, const std::string &archive_dir_path, const DiagnosticId error_id)
Moves a file to the archive directory according to the archive method.
void data_middleware::DataLog::archiveOtherFilesInDir (const std::string &dir_path, const std::string &archive_dir_path, DiagnosticId error_id)
Called only startup. If there are any files in the data or log directories that have been left behind, they will be archived. Not recursive.
void data_middleware::DataLog::createDataArchiveDir ()
Used to create the data archive directory with createDirectory().
void data_middleware::DataLog::createDataDir ()
Used to create the data directory with createDirectory().
void data_middleware::DataLog::createDirectory (const std::string &path, const DiagnosticId booster_seat_log_id, const DiagnosticId std_except_log_id, bool &validity_flag)
Attempt to create a directory, log any errors, and set the validity flag in fs_status_.
void data_middleware::DataLog::createFile (const std::string &new_file_path, const DiagnosticId booster_seat_log_id, const DiagnosticId std_except_log_id, bool &validity_flag)
Attempt to create a file, log any errors, and set the validity flag in fs_status_.
void data_middleware::DataLog::createLogArchiveDir ()
Used to create the log archive directory with createDirectory().
void data_middleware::DataLog::createLogDir ()
Used to create the log directory with createDirectory().
void data_middleware::DataLog::createNewDataFile ()
Generates a new file path and attempts to create a new data file.
void data_middleware::DataLog::createNewLogFile ()
Generates a new file path and attempts to create a new log file.
void data_middleware::DataLog::rotateFiles ()
This method checks the size of the data and log files and archives them if they have exceeded the maximum size.
void data_middleware::DataLog::trimArchive ()
This method will use the configured archive settings to trim the oldest files in the archive directory if the archive size limit is exceeded.
void data_middleware::DataLog::updateDirSize (const std::string &dir_path, const DiagnosticId error_id, data::blocks::DataLogStats::FileSizeType &dir_size)
Attempts to read the size of a directory.
void data_middleware::DataLog::updateFileList ()
This method will update the file list in the relevant data block.
void data_middleware::DataLog::updateFileSize (const std::string &file_path, const DiagnosticId error_id, data::blocks::DataLogStats::FileSizeType &file_size)
Attempts to read the size of a file.
void data_middleware::DataLog::validateDirExists (const std::string &path, const DiagnosticId does_not_exist_log_id, const DiagnosticId booster_seat_log_id, const DiagnosticId std_except_log_id, bool &validity_flag)
Validates the existence of a directory.
void data_middleware::DataLog::validateFileExists (const std::string &path, const DiagnosticId does_not_exist_log_id, const DiagnosticId booster_seat_log_id, const DiagnosticId std_except_log_id, bool &validity_flag)
Validates the existence of a file.
Detailed Description
Used to generate the file structure and manage the log files.
These methods all use BoosterSeat::filesystem to create the necessary directories and files for the data log. Any errors or exceptions should be caught and logged explicitly with unique error codes for each.
DataDir: ./data DataArchiveDir: ./data/archive DataFile: ./data/data_YYYY-MM-DD_HHMMSS.json
LogDir: ./log LogArchiveDir: ./log/archive LogFile: ./log/log_YYYY-MM-DD_HHMMSS.json
Function Documentation
createDirectory()
void data_middleware::DataLog::createDirectory (const std::string & path, const DiagnosticId booster_seat_log_id, const DiagnosticId std_except_log_id, bool & validity_flag) private
Attempt to create a directory, log any errors, and set the validity flag in fs_status_.
Parameters
path - The path to the directory.
booster_seat_log_id - The log id for BoosterSeat::BoosterSeatException.
std_except_log_id - The log id for std::exception.
validity_flag - The flag of fs_status_ to set if the directory is valid.
See also
DataLog::FsStatus
References kNodeId.
createFile()
void data_middleware::DataLog::createFile (const std::string & new_file_path, const DiagnosticId booster_seat_log_id, const DiagnosticId std_except_log_id, bool & validity_flag) private
Attempt to create a file, log any errors, and set the validity flag in fs_status_.
Parameters
new_file_path - The path to the directory.
booster_seat_log_id - The log id for BoosterSeat::BoosterSeatException.
std_except_log_id - The log id for std::exception.
validity_flag - The flag of fs_status_ to set if the directory is valid.
See also
DataLog::FsStatus
References kNodeId.
createDataDir()
void data_middleware::DataLog::createDataDir () private
Used to create the data directory with createDirectory().
References kDataDirPath, kMaxDirCreateAttempts, and kNodeId.
Referenced by data_middleware::DataLog::DataLog().
createLogDir()
void data_middleware::DataLog::createLogDir () private
Used to create the log directory with createDirectory().
References kLogDirPath, kMaxDirCreateAttempts, and kNodeId.
Referenced by data_middleware::DataLog::DataLog().
createDataArchiveDir()
void data_middleware::DataLog::createDataArchiveDir () private
Used to create the data archive directory with createDirectory().
References kDataArchiveDirPath, kMaxDirCreateAttempts, and kNodeId.
Referenced by data_middleware::DataLog::DataLog().
createLogArchiveDir()
void data_middleware::DataLog::createLogArchiveDir () private
Used to create the log archive directory with createDirectory().
References kLogArchiveDirPath, kMaxDirCreateAttempts, and kNodeId.
Referenced by data_middleware::DataLog::DataLog().
createNewDataFile()
void data_middleware::DataLog::createNewDataFile () private
Generates a new file path and attempts to create a new data file.
References generateFilePath(), kDataDirPath, and kDataFilePrefix.
Referenced by data_middleware::DataLog::DataLog().
createNewLogFile()
void data_middleware::DataLog::createNewLogFile () private
Generates a new file path and attempts to create a new log file.
References generateFilePath(), kLogDirPath, and kLogFilePrefix.
Referenced by data_middleware::DataLog::DataLog().
validateDirExists()
void data_middleware::DataLog::validateDirExists (const std::string & path, const DiagnosticId does_not_exist_log_id, const DiagnosticId booster_seat_log_id, const DiagnosticId std_except_log_id, bool & validity_flag) private
Validates the existence of a directory.
Parameters
path - The path to the directory.
does_not_exist_log_id - The error id to report if the directory does not exist.
booster_seat_log_id - The error id to report if BoosterSeat::BoosterSeatException is thrown.
std_except_log_id - The error id to report if std::exception is thrown.
validity_flag (out) - The 'valid' flag to set if the directory is valid.
References kNodeId.
validateFileExists()
void data_middleware::DataLog::validateFileExists (const std::string & path, const DiagnosticId does_not_exist_log_id, const DiagnosticId booster_seat_log_id, const DiagnosticId std_except_log_id, bool & validity_flag) private
Validates the existence of a file.
Parameters
path - The path to the file.
does_not_exist_log_id - The error id to report if the file does not exist.
booster_seat_log_id - The error id to report if BoosterSeat::BoosterSeatException is thrown.
std_except_log_id - The error id to report if std::exception is thrown.
validity_flag (out) - The 'valid' flag to set if the file is valid.
References kNodeId.
appendToFile()
void data_middleware::DataLog::appendToFile (const std::string & path, const std::string & data, const DiagnosticId error_id) private
Attempts to append data to a file. Only checks the file validity.
Parameters
path - The path to the file.
data - The string to append.
error_id - The error id to log if an error occurs.
References kNodeId.
updateFileSize()
void data_middleware::DataLog::updateFileSize (const std::string & file_path, const DiagnosticId error_id, data::blocks::DataLogStats::FileSizeType & file_size) private
Attempts to read the size of a file.
Parameters
file_path - The path to the file.
error_id - The error id to log if an error occurs.
file_size (out) - The variable to store the file size in.
References kDataSizeUnit, and kNodeId.
updateDirSize()
void data_middleware::DataLog::updateDirSize (const std::string & dir_path, const DiagnosticId error_id, data::blocks::DataLogStats::FileSizeType & dir_size) private
Attempts to read the size of a directory.
Parameters
dir_path - The path to the directory.
error_id - The error id to log if an error occurs.
dir_size - The variable to store the directory size in.
References kDataSizeUnit, and kNodeId.
archiveFile()
bool data_middleware::DataLog::archiveFile (const std::string & file_path, const std::string & archive_dir_path, const DiagnosticId error_id) private
Moves a file to the archive directory according to the archive method.
Parameters
file_path - The path to the file to archive.
archive_dir_path - The path to the archive directory.
error_id - The error id to log if an error occurs.
Returns
true if the file was archived successfully, false otherwise.
Todo:
Archive Methods
References kNodeId.
archiveOtherFilesInDir()
void data_middleware::DataLog::archiveOtherFilesInDir (const std::string & dir_path, const std::string & archive_dir_path, DiagnosticId error_id) private
Called only startup. If there are any files in the data or log directories that have been left behind, they will be archived. Not recursive.
Parameters
dir_path - The path to the directory to check for stray files.
archive_dir_path - The path to the archive directory.
error_id - The error id to log if an error occurs.
References kNodeId.
Referenced by data_middleware::DataLog::DataLog().
rotateFiles()
void data_middleware::DataLog::rotateFiles () private
This method checks the size of the data and log files and archives them if they have exceeded the maximum size.
This method first checks the size of the two files, if they are both under the maximum size, nothing happens. If a file is over the maximum configured size, it will attempt to archive the file and then create a new one.
References kDataArchiveDirPath, kLogArchiveDirPath, and kNodeId.
trimArchive()
void data_middleware::DataLog::trimArchive () private
This method will use the configured archive settings to trim the oldest files in the archive directory if the archive size limit is exceeded.
References kDataArchiveDirPath, and kNodeId.
updateFileList()
void data_middleware::DataLog::updateFileList () private
This method will update the file list in the relevant data block.
References getFileNamesInDir(), kDataArchiveDirPath, kLogArchiveDirPath, and kNodeId.
Referenced by data_middleware::DataLog::DataLog().