Giraffe: Server Module
Server Module
Classes
class modules::ServerModule
The server module. Provides a network interface for interacting with the flight system.
class RequestRouter
Used to handle client requests from the server module.
class sock::TcpSocketServer
The TCP socket server class.
Detailed Description
Class Documentation
modules::ServerModule
class modules::ServerModule
The server module. Provides a network interface for interacting with the flight system.
Public Member Functions
ServerModule (data::SharedData &, cfg::Configuration &)
~ServerModule () override=default
bool addCommand (const cmd::Command &command)
Public wrapper for adding a command to the command queue.
node::Status getStatus () const
Returns the status of the module.
void start ()
Starts a thread to run the module.
void stop ()
Stops the module by setting the stop flag to true and joining the runner thread.
Protected Member Functions
template<typename T >
void data (data::DataId identifier, T value, int precision=2)
Used internally in the module. This function adds a data to the data stream.
void debug (std::string info)
Used internally for debug messages.
void error (DiagnosticId log_id, int info)
Same as the other error function, but takes an int instead of a string.
void error (DiagnosticId, std::string info="")
Used internally in the module. This function adds an error to the log stream. It is used to log errors that occur in the module.
void info (std::string info="")
Used internally in the module. This function adds a info message to the log stream.
void setStatus (const node::Status status)
void sleep ()
Sleeps the module for the sleep interval.
bool stopRequested () const
Returns true if the stop flag is set to true.
virtual void updateLocalConfig ()
Protected Attributes
cfg::Configuration & configuration_
modules::MetaData metadata_
data::SharedData & shared_data_
Private Member Functions
void loop () override
Loop module function for the server module.
void processCommand (const cmd::Command &command)
Process a command that was received from the flight runner.
void runner ()
This is the main function for each module.
void shutdown () override
Shutdown the server module.
void startup () override
Startup the server module.
Private Attributes
cmd::CommandQueue command_queue_
The command queue for the module.
bst::Timer connected_timeout_ = {2000}
Used to update the 'connected' status of the server.
RequestRouter request_router_
Used to handle the requests from the client.
bst::Timer rolling_average_timer_ = {1000}
Timer for the rolling average. Used to call 'server_socket_.oneSecondTick()' every second.
std::thread runner_thread_
The thread that runs runner().
sock::TcpSocketServer server_socket_ = {}
The TCP socket used to communicate with the client.
data::blocks::ServerModuleStats stats_ = {}
Local copy of the server module stats. This is used to update the stats every loop.
std::atomic< node::Status > status_ = node::Status::UNKNOWN
The status of the module.
std::atomic< bool > stop_flag_ = true
The stop flag is used to stop the module.
Constructor & Destructor Documentation
ServerModule()
modules::ServerModule::ServerModule (data::SharedData & shared_data, cfg::Configuration & config)
~ServerModule()
modules::ServerModule::~ServerModule () override default
Member Function Documentation
startup()
void modules::ServerModule::startup () override private virtual
Startup the server module.
Reads the socket port from the configuration and initializes the socket with it. Override of Module::startup()
Reimplemented from modules::Module.
References util::to_string().
loop()
void modules::ServerModule::loop () override private virtual
Loop module function for the server module.
Connects to clients and handles the requests. Override of Module::loop()
Reimplemented from modules::Module.
References sock::TcpSocketServer::close(), and sock::TcpSocketServer::receive().
shutdown()
void modules::ServerModule::shutdown () override private virtual
Shutdown the server module.
Closes the socket. Override of Module::shutdown()
Reimplemented from modules::Module.
processCommand()
void modules::ServerModule::processCommand (const cmd::Command & command) private virtual
Process a command that was received from the flight runner.
Parameters
command The command to process.
Reimplemented from modules::Module.
start()
void modules::Module::start () inherited
Starts a thread to run the module.
This function will start a thread to run a module, but only if the module is not already running. If the module is already running, an error will be logged. It also resets the stop flag to false.
References modules::Module::runner(), node::RUNNING, and node::SLEEPING.
Referenced by DataModuleTests::cycleDataModule(), ExtensionModuleTests::cycleExtensionModule(), and FlightRunner::toggleModule().
stop()
void modules::Module::stop () inherited
Stops the module by setting the stop flag to true and joining the runner thread.
This function will stop the module by setting the stop flag to true and joining the runner thread. It also sets the status to STOPPED. If a module is in the sleep state, it will only stop after the next loop. This means that the sleep interval plus the time it takes to run the loop and shutdown will be the total time it takes to stop the module.
References node::STOPPED, and node::STOPPING.
Referenced by FlightRunner::~FlightRunner(), DataModuleTests::cycleDataModule(), ExtensionModuleTests::cycleExtensionModule(), and FlightRunner::toggleModule().
getStatus()
node::Status modules::Module::getStatus () const inherited
Returns the status of the module.
Returns
Returns the status of the module.
See also
node::Status
addCommand()
bool modules::Module::addCommand (const cmd::Command & command) inline inherited
Public wrapper for adding a command to the command queue.
See also
cmd::CommandQueue
References cmd::CommandQueue::addCommand(), and modules::Module::command_queue_.
Referenced by FlightRunner::routeCommand().
updateLocalConfig()
virtual void modules::Module::updateLocalConfig () inline protected virtual inherited
Reimplemented in modules::ExtensionModule.
References giraffe_assert.
setStatus()
void modules::Module::setStatus (const node::Status status) protected inherited
Todo:
Sets the status of the module and reports it to the data stream.
error() [1/2]
void modules::Module::error (DiagnosticId log_id, std::string info = "") protected inherited
Used internally in the module. This function adds an error to the log stream. It is used to log errors that occur in the module.
Uses the module meta data to add the correct node identification.
Parameters
log_id The log id of the error.
info Optional information to add to the log.
Referenced by modules::DataModule::DataModule(), modules::ExtensionModule::addExtension(), modules::ExtensionModule::addPreConfiguredExtension(), modules::ExtensionModule::processCommand(), and modules::ExtensionModule::startup().
error() [2/2]
void modules::Module::error (DiagnosticId log_id, int info) protected inherited
Same as the other error function, but takes an int instead of a string.
References util::to_string().
info()
void modules::Module::info (std::string info = "") protected inherited
Used internally in the module. This function adds a info message to the log stream.
Uses the module meta data to add the correct node identification.
Parameters
info info string to add to the log.
Referenced by modules::ExtensionModule::addExtension(), and modules::ExtensionModule::startup().
debug()
void modules::Module::debug (std::string info) protected inherited
Used internally for debug messages.
Parameters
info The debug message.
data()
template<typename T > template void modules::Module::data< double > (data::DataId identifier, T value, int precision = 2) protected inherited
Used internally in the module. This function adds a data to the data stream.
Template Parameters
T a non-string type that can be converted to a string with std::to_string
Parameters
identifier The data identifier.
value The value of the data.
precision The precision (if the type is a float or double)
References util::to_string().
stopRequested()
bool modules::Module::stopRequested () const inline protected inherited
Returns true if the stop flag is set to true.
Used internally in a module to check if the module should stop in between large tasks.
Returns
true
false
References modules::Module::stop_flag_.
sleep()
void modules::Module::sleep () protected inherited
Sleeps the module for the sleep interval.
Default of 1 second, this is blocking.
runner()
void modules::Module::runner () private inherited
This is the main function for each module.
This function is what runs in the thread. It calls startup, then loops until the stop flag is set to true. It then calls shutdown.
It also handles the command queue.
References node::RUNNING, node::SLEEPING, node::STARTING, node::STOPPED, and node::STOPPING.
Referenced by modules::Module::start().
Member Data Documentation
request_router_
RequestRouter modules::ServerModule::request_router_ private
Used to handle the requests from the client.
server_socket_
sock::TcpSocketServer modules::ServerModule::server_socket_ = {} private
The TCP socket used to communicate with the client.
stats_
data::blocks::ServerModuleStats modules::ServerModule::stats_ = {} private
Local copy of the server module stats. This is used to update the stats every loop.
rolling_average_timer_
bst::Timer modules::ServerModule::rolling_average_timer_ = {1000} private
Timer for the rolling average. Used to call 'server_socket_.oneSecondTick()' every second.
connected_timeout_
bst::Timer modules::ServerModule::connected_timeout_ = {2000} private
Used to update the 'connected' status of the server.
metadata_
modules::MetaData modules::Module::metadata_ protected inherited
shared_data_
data::SharedData& modules::Module::shared_data_ protected inherited
Referenced by modules::ExtensionModule::loop(), and modules::ExtensionModule::startup().
configuration_
cfg::Configuration& modules::Module::configuration_ protected inherited
Referenced by modules::DataModule::DataModule(), modules::ExtensionModule::addPreConfiguredExtension(), modules::ExtensionModule::startup(), and modules::ExtensionModule::updateLocalConfig().
status_
std::atomic<node::Status> modules::Module::status_ = node::Status::UNKNOWN private inherited
The status of the module.
See also
node::Status
stop_flag_
std::atomic<bool> modules::Module::stop_flag_ = true private inherited
The stop flag is used to stop the module.
Set to true to stop the module upon a call to stop().
Referenced by modules::Module::stopRequested().
runner_thread_
std::thread modules::Module::runner_thread_ private inherited
The thread that runs runner().
command_queue_
cmd::CommandQueue modules::Module::command_queue_ private inherited
The command queue for the module.
See also
cmd::CommandQueue
Referenced by modules::Module::addCommand().
RequestRouter
class RequestRouter
Used to handle client requests from the server module.
Public Member Functions
RequestRouter (data::SharedData &shared_data, cfg::Configuration &config, data::blocks::ServerModuleStats &server_stats)
Construct a RequestRouter object.
~RequestRouter ()=default
double getBytesPerSecondDown () const
Get the average bytes per second down.
double getBytesPerSecondUp () const
Get the average bytes per second up.
void handleMessage (sock::TcpSocketServer &client, std::string &request)
This function is responsible for parsing a request and routing it to the right place.
void oneSecondTick ()
Used to update the rolling average of bytes per second.
Private Member Functions
void handleAdcMappingSettingUpdate (sock::TcpSocketServer &client, protocol::Message &msg)
A special handler for updating ADC mapping settings.
void handleCommandRequest (sock::TcpSocketServer &client, protocol::Message &msg)
This function parses a command request, sends it to the command queue and sends a simple response back. It does not wait for the command to be executed.
void handleDataRequest (sock::TcpSocketServer &client, protocol::Message &msg)
This function responds to data requests.
void handleExtensionSettingUpdate (sock::TcpSocketServer &client, protocol::Message &msg)
A special handler for updating extension settings.
void handleImageRequest (sock::TcpSocketServer &client, const std::string &msg_rsc)
Response to an image request. Sends the image data to the client.
void handlePingRequest (sock::TcpSocketServer &client, protocol::Message &msg)
This function responds to a ping request.
void handleSettingRequest (sock::TcpSocketServer &client, protocol::Message &msg)
This function responds to a setting request.
void handleSettingSet (sock::TcpSocketServer &client, protocol::Message &msg)
This function handles a setting SET request. It will attempt to set the configuration with the value provided.
void sendErrorPacket (sock::TcpSocketServer &client, const std::string &error="")
This function is the generic error response function.
void sendMessage (protocol::Message &response, sock::TcpSocketServer &client)
Send a message to the client.
void sendSuccessResponse (sock::TcpSocketServer &client)
Send a basic success response.
Private Attributes
double bps_down_in_a_second_ = 0
double bps_up_in_a_second_ = 0
bst::RollingAverage< double > bytes_per_second_down_ = {60}
bst::RollingAverage< double > bytes_per_second_up_ = {60}
cfg::Configuration & config_
giraffe::Logger logger_
data::SharedData & shared_data_
data::blocks::ServerModuleStats & stats_
Constructor & Destructor Documentation
RequestRouter()
RequestRouter::RequestRouter (data::SharedData & shared_data, cfg::Configuration & config, data::blocks::ServerModuleStats & server_stats)
Construct a RequestRouter object.
Parameters
shared_data - The shared data object.
config - The global configuration.
server_stats - The server stats data block.
~RequestRouter()
RequestRouter::~RequestRouter () default
Member Function Documentation
handleMessage()
void RequestRouter::handleMessage (sock::TcpSocketServer & client, std::string & request)
This function is responsible for parsing a request and routing it to the right place.
The function handles incoming requests from a TCP socket server by parsing them as JSON strings and checking their type and category before sending the appropriate response or an error packet if they are not implemented or malformed.
Parameters
client The client parameter is a reference to a sock::TcpSocketServer object, which represents the client that sent the request to the server.
request The request parameter is a reference to a std::string object that contains the json message received from the client.
References bps_down_in_a_second_, giraffe::Logger::debug(), protocol::Message::dst, protocol::GFS, handleCommandRequest(), handleDataRequest(), handleImageRequest(), handlePingRequest(), handleSettingRequest(), handleSettingSet(), logger_, data::blocks::ServerModuleStats::num_messages_received, protocol::parseMessage(), protocol::REQ, protocol::Message::rsc, sendErrorPacket(), protocol::SET, stats_, and protocol::Message::typ.
oneSecondTick()
void RequestRouter::oneSecondTick () inline
Used to update the rolling average of bytes per second.
Todo:
remove
References bps_down_in_a_second_, bps_up_in_a_second_, bytes_per_second_down_, and bytes_per_second_up_.
getBytesPerSecondDown()
double RequestRouter::getBytesPerSecondDown () const inline
Get the average bytes per second down.
Returns
double - The average bytes per second down.
References bytes_per_second_down_.
getBytesPerSecondUp()
double RequestRouter::getBytesPerSecondUp () const inline
Get the average bytes per second up.
Returns
double - The average bytes per second up.
References bytes_per_second_up_.
sendErrorPacket()
void RequestRouter::sendErrorPacket (sock::TcpSocketServer & client, const std::string & error = "") private
This function is the generic error response function.
Parameters
client The client is the client socket.
error A string containing the error message.
References protocol::createResponseMessage(), protocol::ERROR, protocol::GFS, protocol::GGS, data::blocks::ServerModuleStats::num_invalid_received, sendMessage(), and stats_.
Referenced by handleAdcMappingSettingUpdate(), handleCommandRequest(), handleDataRequest(), handleExtensionSettingUpdate(), handleMessage(), handleSettingRequest(), and handleSettingSet().
handlePingRequest()
void RequestRouter::handlePingRequest (sock::TcpSocketServer & client, protocol::Message & msg) private
This function responds to a ping request.
Parameters
client
msg
References protocol::createResponseMessage(), protocol::GFS, protocol::GOOD, protocol::Message::id, sendMessage(), and protocol::Message::src.
Referenced by handleMessage().
handleSettingRequest()
void RequestRouter::handleSettingRequest (sock::TcpSocketServer & client, protocol::Message & msg) private
This function responds to a setting request.
It will respond with the configuration portion requested if it exists. Otherwise it will respond with an error.
Parameters
client - The client socket.
msg - The received message.
References config_, protocol::createResponseMessage(), protocol::GFS, protocol::GOOD, protocol::Message::id, protocol::Message::rsc, sendErrorPacket(), sendMessage(), and protocol::Message::src.
Referenced by handleMessage().
handleSettingSet()
void RequestRouter::handleSettingSet (sock::TcpSocketServer & client, protocol::Message & msg) private
This function handles a setting SET request. It will attempt to set the configuration with the value provided.
Parameters
client - The client socket.
msg - The received message.
References config_, protocol::createResponseMessage(), protocol::Message::getBodyJson(), protocol::GFS, protocol::GOOD, handleAdcMappingSettingUpdate(), handleExtensionSettingUpdate(), protocol::Message::id, protocol::Message::rsc, sendErrorPacket(), sendMessage(), and protocol::Message::src.
Referenced by handleMessage().
handleExtensionSettingUpdate()
void RequestRouter::handleExtensionSettingUpdate (sock::TcpSocketServer & client, protocol::Message & msg) private
A special handler for updating extension settings.
Parameters
client - The client socket.
msg - The received message.
References config_, protocol::Message::getBodyJson(), data::Streams::log, sendErrorPacket(), sendSuccessResponse(), cfg::ExtensionMetadata::setFromJson(), shared_data_, and data::SharedData::streams.
Referenced by handleSettingSet().
handleAdcMappingSettingUpdate()
void RequestRouter::handleAdcMappingSettingUpdate (sock::TcpSocketServer & client, protocol::Message & msg) private
A special handler for updating ADC mapping settings.
Parameters
client - The client socket.
msg - The received message.
References config_, cfg::AdcConfig::fromJson(), protocol::Message::getBodyJson(), data::Streams::log, sendErrorPacket(), sendSuccessResponse(), shared_data_, and data::SharedData::streams.
Referenced by handleSettingSet().
handleDataRequest()
void RequestRouter::handleDataRequest (sock::TcpSocketServer & client, protocol::Message & msg) private
This function responds to data requests.
Parameters
client
msg
References data::SharedData::blocks, data::SharedBlocks::calculated_data, protocol::createResponseMessage(), data::SharedBlocks::data_log_stats, data::Frames::env_hum, data::Frames::env_pres, data::Frames::env_temp, data::Frames::error_frame, data::SharedBlocks::extension_module_stats, data::SharedBlocks::file_system_data, data::SharedData::flight_data, data::SharedData::frames, getErrorFrameData(), protocol::GFS, protocol::GOOD, protocol::Message::id, data::SharedBlocks::location_data, data::SharedBlocks::modules_statuses, protocol::Message::rsc, sendErrorPacket(), sendMessage(), data::SharedBlocks::server_module_stats, shared_data_, protocol::Message::src, data::SharedBlocks::stream_stats, data::SharedBlocks::system_info, data::SharedBlocks::telemetry_module_stats, data::FlightData::toJson(), and data::toJson().
Referenced by handleMessage().
handleCommandRequest()
void RequestRouter::handleCommandRequest (sock::TcpSocketServer & client, protocol::Message & msg) private
This function parses a command request, sends it to the command queue and sends a simple response back. It does not wait for the command to be executed.
Parameters
client - The client socket.
msg - The message to parse.
References data::CommandStream::addCommand(), data::Streams::command, data::LogStream::error(), data::Streams::log, cmd::parseCommandString(), protocol::Message::rsc, sendErrorPacket(), node::SERVER_MODULE, shared_data_, and data::SharedData::streams.
Referenced by handleMessage().
handleImageRequest()
void RequestRouter::handleImageRequest (sock::TcpSocketServer & client, const std::string & msg_rsc) private
Response to an image request. Sends the image data to the client.
Parameters
client - The client socket.
msg_rsc - The message resource. (Contains img/<image_name>)
References giraffe::file_paths::getGfsImageDirPath(), sock::TcpSocketServer::send(), and sock::TcpSocketServer::sendRawData().
Referenced by handleMessage().
sendMessage()
void RequestRouter::sendMessage (protocol::Message & response, sock::TcpSocketServer & client) private
Send a message to the client.
Parameters
response - The message to send.
client - The client socket.
References bps_down_in_a_second_, protocol::Message::getJsonString(), and sock::TcpSocketServer::send().
Referenced by handleDataRequest(), handlePingRequest(), handleSettingRequest(), handleSettingSet(), sendErrorPacket(), and sendSuccessResponse().
sendSuccessResponse()
void RequestRouter::sendSuccessResponse (sock::TcpSocketServer & client) private
Send a basic success response.
Parameters
client - The client socket.
References protocol::createResponseMessage(), protocol::GFS, protocol::GGS, protocol::GOOD, and sendMessage().
Referenced by handleAdcMappingSettingUpdate(), and handleExtensionSettingUpdate().
Member Data Documentation
shared_data_
data::SharedData& RequestRouter::shared_data_ private
Referenced by handleAdcMappingSettingUpdate(), handleCommandRequest(), handleDataRequest(), and handleExtensionSettingUpdate().
config_
cfg::Configuration& RequestRouter::config_ private
Referenced by handleAdcMappingSettingUpdate(), handleExtensionSettingUpdate(), handleSettingRequest(), and handleSettingSet().
stats_
data::blocks::ServerModuleStats& RequestRouter::stats_ private
Referenced by handleMessage(), and sendErrorPacket().
logger_
giraffe::Logger RequestRouter::logger_ private
Referenced by handleMessage().
bps_down_in_a_second_
double RequestRouter::bps_down_in_a_second_ = 0 private
Referenced by handleMessage(), oneSecondTick(), and sendMessage().
bps_up_in_a_second_
double RequestRouter::bps_up_in_a_second_ = 0 private
Referenced by oneSecondTick().
bytes_per_second_down_
bst::RollingAverage<double> RequestRouter::bytes_per_second_down_ = {60} private
Referenced by getBytesPerSecondDown(), and oneSecondTick().
bytes_per_second_up_
bst::RollingAverage<double> RequestRouter::bytes_per_second_up_ = {60} private
Referenced by getBytesPerSecondUp(), and oneSecondTick().
sock::TcpSocketServer
class sock::TcpSocketServer
The TCP socket server class.
Public Member Functions
TcpSocketServer ()
~TcpSocketServer ()
bool accept (sock::TcpSocketServer &sock)
bool bind (const int port)
bool close ()
bool create ()
std::string getClientAddress () const
bool init (int port_number)
bool isValid () const
bool listen () const
bool receive (std::string &data) const
bool send (const std::string &data) const
bool sendRawData (const uint8_t *data, size_t size)
Private Attributes
sockaddr_in addr_ = {}
int sock_ = -1
Constructor & Destructor Documentation
TcpSocketServer()
sock::TcpSocketServer::TcpSocketServer ()
Todo:
remove this
References addr_.
~TcpSocketServer()
sock::TcpSocketServer::~TcpSocketServer ()
Member Function Documentation
init()
bool sock::TcpSocketServer::init (int port_number)
Referenced by giraffe::gdl::GdlServer::run().
create()
bool sock::TcpSocketServer::create ()
bind()
bool sock::TcpSocketServer::bind (const int port)
listen()
bool sock::TcpSocketServer::listen () const
References sock::K_MAX_CONNECTIONS.
accept()
bool sock::TcpSocketServer::accept (sock::TcpSocketServer & sock)
References sock_.
Referenced by giraffe::gdl::GdlServer::run().
close()
bool sock::TcpSocketServer::close ()
Referenced by modules::ServerModule::loop(), and giraffe::gdl::GdlServer::stop().
send()
bool sock::TcpSocketServer::send (const std::string & data) const
Referenced by RequestRouter::handleImageRequest(), RequestRouter::sendMessage(), giraffe::gdl::GdlServer::sendResponseData(), giraffe::gdl::GdlServer::sendResponseError(), and giraffe::gdl::GdlServer::sendResponseSuccess().
sendRawData()
bool sock::TcpSocketServer::sendRawData (const uint8_t * data, size_t size)
Referenced by RequestRouter::handleImageRequest().
receive()
bool sock::TcpSocketServer::receive (std::string & data) const
References sock::K_MAX_RECEIVE.
Referenced by modules::ServerModule::loop(), and giraffe::gdl::GdlServer::run().
isValid()
bool sock::TcpSocketServer::isValid () const
getClientAddress()
std::string sock::TcpSocketServer::getClientAddress () const
Referenced by giraffe::gdl::GdlServer::run().
Member Data Documentation
sock_
int sock::TcpSocketServer::sock_ = -1 private
Referenced by accept().
addr_
sockaddr_in sock::TcpSocketServer::addr_ = {} private
Referenced by TcpSocketServer().