Giraffe: bit::test_case Namespace Reference
bit::test_case Namespace Reference
Functions
TestResult runTestFCS_0001 (data::SharedData &shared_data)
Checks if the error frame has any active errors.
TestResult runTestGPS_0400 (data::SharedData &shared_data)
Checks if GPS hardware is configured and running.
Function Documentation
runTestFCS_0001()
TestResult bit::test_case::runTestFCS_0001 (data::SharedData & shared_data)
Checks if the error frame has any active errors.
Parameters
shared_data - The shared data object.
Returns
TestResult - The result of the test.
References data::Frames::error_frame, data::SharedData::frames, data::ErrorFrame::numActiveErrors(), bit::TestResult::test_id, and util::to_string().
Referenced by TEST(), and bit::TestCase::update().
runTestGPS_0400()
TestResult bit::test_case::runTestGPS_0400 (data::SharedData & shared_data)
Checks if GPS hardware is configured and running.
Parameters
shared_data - The shared data object.
Returns
TestResult - The result of the test.
References data::SharedData::blocks, data::SharedBlocks::location_data, and bit::TestResult::test_id.
Referenced by bit::TestCase::update().