Giraffe: giraffe Namespace Reference
giraffe Namespace Reference
Namespaces
namespace file_paths
namespace gdl
namespace radio
Classes
class AprsManager
Manages GDL APRS Position and Telemetry Data.
class CommonLogger
class DummyLogger
struct FCInfo
class FlightRunnerData
Data that is persisted across system restarts. Used by the flight runner to track the state of the system.
class Gpio
This class is used to interface extensions with the BCM Gpio pins.
class ILogger
class Logger
struct LoggerEntry
class OptionalLogger
Optional logger class.
struct SoftwareVersion
Giraffe Software Version Structure.
class SpiInterface
class StatusLedChannel
class StatusLedState
Enumerations
enum class AppIdentifier : uint8_t {
DAEMON = 0 , COMMAND_LINE , FLIGHT_SYSTEM , DATA_LINK_SERVER ,
_COUNT , UNKNOWN
}
The applications of the Giraffe system.
enum class LoggerLevel : uint8_t { DEBUG = 0 , INFO = 1 , WARN = 2 , ERROR = 3 }
Functions
FCInfo getFlightComputerInfo ()
NLOHMANN_JSON_SERIALIZE_ENUM (FlightRunnerData::ShutdownReason, { {FlightRunnerData::ShutdownReason::CRASH_OR_UNKNOWN, "crash_or_unknown"}, {FlightRunnerData::ShutdownReason::CTRL_C, "ctrl_c"}, {FlightRunnerData::ShutdownReason::TELEMETRY_SDN_COMMAND, "telemetry_sdn_command"}, }) NLOHMANN_JSON_SERIALIZE_ENUM(FlightPhase
std::string to_string (const LoggerLevel level)
Variables
constexpr uint32_t kNumStartupsDefault = 0
constexpr uint8_t MAX_PIN_NUMBER = 27
Enumeration Type Documentation
LoggerLevel
enum class giraffe::LoggerLevel : uint8_t strong
Enumerator
DEBUG
INFO
WARN
ERROR
AppIdentifier
enum class giraffe::AppIdentifier : uint8_t strong
The applications of the Giraffe system.
This should not be assumed to always be in the same order, or be complete.
Enumerator
DAEMON
giraffe_daemon
COMMAND_LINE
gcli - giraffe_command_line
FLIGHT_SYSTEM
gfs - giraffe_flight_system
DATA_LINK_SERVER
gdl_server - giraffe_data_link_server
_COUNT
Number of Giraffe applications, must be last.
UNKNOWN
unknown application, must be last.
Function Documentation
NLOHMANN_JSON_SERIALIZE_ENUM()
giraffe::NLOHMANN_JSON_SERIALIZE_ENUM (FlightRunnerData::ShutdownReason , { {FlightRunnerData::ShutdownReason::CRASH_OR_UNKNOWN, "crash_or_unknown"}, {FlightRunnerData::ShutdownReason::CTRL_C, "ctrl_c"}, {FlightRunnerData::ShutdownReason::TELEMETRY_SDN_COMMAND, "telemetry_sdn_command"}, })
References giraffe::FlightRunnerData::CRASH_OR_UNKNOWN, giraffe::FlightRunnerData::CTRL_C, and giraffe::FlightRunnerData::TELEMETRY_SDN_COMMAND.
getFlightComputerInfo()
FCInfo giraffe::getFlightComputerInfo ()
Todo:
Add support for PI 3, 4, etc.
References giraffe::FCInfo::architecture, giraffe::FCInfo::ARM, giraffe::FCInfo::OTHER, giraffe::FCInfo::PI_ZERO, giraffe::FCInfo::PI_ZERO_2, giraffe::FCInfo::type, giraffe::FCInfo::UNKNOWN, giraffe::FCInfo::X86, and giraffe::FCInfo::X86_64.
Referenced by extension::PiCamera::startup(), and TEST().
to_string()
std::string giraffe::to_string (const LoggerLevel level)
References DEBUG, ERROR, INFO, and WARN.
Referenced by giraffe::gdl::GdlServer::getConfigJson(), and giraffe::LoggerEntry::getLevelString().
Variable Documentation
kNumStartupsDefault
constexpr uint32_t giraffe::kNumStartupsDefault = 0 inline constexpr
MAX_PIN_NUMBER
constexpr uint8_t giraffe::MAX_PIN_NUMBER = 27 inline constexpr
Referenced by giraffe::Gpio::Pin::Pin().