Giraffe: data Namespace Reference
data Namespace Reference
Namespaces
blocks
Classes
struct BaseStreamPacket
struct CommandPacket
The packet for the command stream.
class CommandStream
The stream of new commands.
struct DataPacket
class DataStream
class ErrorFrame
The error frame.
struct ErrorFrameItem
A struct to store information about an error in the error frame.
class Frame
A generic frame (map) for storing data.
struct Frames
struct GpsFrame
A frame of GPS data straight from a GPS extension.
struct GpsFramePacket
class GpsFrameStream
struct ImuFrame
A frame of IMU data, straight from an IMU extension.
struct ImuFramePacket
class ImuFrameStream
struct LogPacket
class LogStream
class Misc
struct SharedBlocks
struct SharedData
Data that is shared across all modules and extensions.
class Stream
struct Streams
Enumerations
enum class GpsFix : uint8_t { ERROR = 0 , NO_FIX = 1 , FIX_2D = 2 , FIX_3D = 3 }
Functions
bool isGpsFrameValid (const data::GpsFrame &frame)
Checks if a GPS frame contains valid location data.
bool isImuFrameValid (const data::ImuFrame &frame)
Checks if an IMU frame contains valid data.
void to_json (json &j, const data::GpsFrame &frame)
Json toJson (data::Frame< std::string, data::DataPacket > &frame)
Variables
static const std::map< GpsFix, std::string > K_GPS_FIX_TO_STRING_MAP
auto rnd = bst::doubleToPrecisionTwo
Class Documentation
data::ErrorFrameItem
struct data::ErrorFrameItem
A struct to store information about an error in the error frame.
Class Members
TimePoint last_reported
TimePoint first_reported
int occurrences
LogPacket packet
data::Frames
struct data::Frames
Class Members
ErrorFrame error_frame Data frame containing all active error messages.
Frame< string, DataPacket > env_temp Temperature data from environmental extensions.
Frame< string, DataPacket > env_pres Pressure data from environmental extensions.
Frame< string, DataPacket > env_hum Humidity data from environmental extensions.
data::GpsFrame
struct data::GpsFrame
A frame of GPS data straight from a GPS extension.
Class Members
TimePoint gps_utc_time The UTC time of the GPS fix from the actual GPS clock.
bool is_valid This is generated by the extension, the data may still not be reliable.
GpsFix fix The GPS fix type.
uint8_t num_satellites The number of satellites used to calculate the fix.
double latitude The latitude in decimal degrees.
double longitude The longitude in decimal degrees.
double horz_accuracy The horizontal accuracy in meters.
double altitude The altitude in meters.
double vert_accuracy The vertical accuracy in meters.
double vertical_speed The vertical speed in meters/second.
double horizontal_speed The horizontal speed in meters/second.
double speed_accuracy The horizontal speed accuracy in meters/second.
double heading_of_motion The heading of motion in degrees. (not magnetic)
double heading_accuracy The heading of motion accuracy in degrees.
data::ImuFrame
struct data::ImuFrame
A frame of IMU data, straight from an IMU extension.
Class Members
TimePoint time The time of the IMU frame, generated by the system.
bool is_valid The extension will set this to true if it thinks the data is valid.
double x_acceleration
double y_acceleration
double z_acceleration
double x_angular_velocity
double y_angular_velocity
double z_angular_velocity
data::SharedBlocks
struct data::SharedBlocks
Class Members
Block< StreamsStats > stream_stats
Block< ModulesStatuses > modules_statuses
Block< ServerModuleStats > server_module_stats
Block< DataLogStats > data_log_stats
Block< SystemInfo > system_info
Block< ExtensionModuleStats > extension_module_stats
Block< LocationData > location_data
Block< ImuData > imu_data
Block< CameraImages > camera
Block< TelemetryModuleStats > telemetry_module_stats
Block< CalculatedData > calculated_data
data::SharedData
struct data::SharedData
Data that is shared across all modules and extensions.
Class Members
Streams streams
Frames frames
SharedBlocks blocks
Misc misc
LogContainer log_container
StatusLedState status_led
data::Streams
struct data::Streams
Class Members
DataStream data
LogStream log
GpsFrameStream gps
ImuFrameStream imu
CommandStream command The command stream. Parsed by the flight runner, not the data module.
Enumeration Type Documentation
GpsFix
enum data::GpsFix : uint8_t strong
Enumerator
ERROR
NO_FIX
FIX_2D
FIX_3D
Function Documentation
to_json()
void data::to_json (json & j, const data::GpsFrame & frame)
References data::GpsFrame::altitude, data::GpsFrame::fix, data::GpsFrame::gps_utc_time, data::GpsFrame::heading_accuracy, data::GpsFrame::heading_of_motion, data::GpsFrame::horizontal_speed, data::GpsFrame::horz_accuracy, data::GpsFrame::is_valid, K_GPS_FIX_TO_STRING_MAP, data::GpsFrame::latitude, data::GpsFrame::longitude, data::GpsFrame::num_satellites, data::GpsFrame::speed_accuracy, data::GpsFrame::vert_accuracy, and data::GpsFrame::vertical_speed.
isGpsFrameValid()
bool data::isGpsFrameValid (const data::GpsFrame & frame)
Checks if a GPS frame contains valid location data.
Simply checks if the data fields are within logical bounds. Does not have any knowledge of the previous location, so it cannot check for a sudden jump in position. This also checks for a time skew of less than 1 day in the hopes that the system data is correct.
Parameters
frame - The frame to check.
Returns
true - If the frame is valid.
false - If the frame is invalid.
References data::GpsFrame::altitude, ERROR, data::GpsFrame::fix, FIX_2D, FIX_3D, data::GpsFrame::gps_utc_time, data::GpsFrame::heading_of_motion, data::GpsFrame::horz_accuracy, data::GpsFrame::is_valid, data::GpsFrame::latitude, data::GpsFrame::longitude, NO_FIX, and data::GpsFrame::num_satellites.
Referenced by modules::DataModule::processGpsFramePacket(), and TEST().
isImuFrameValid()
bool data::isImuFrameValid (const data::ImuFrame & frame)
Checks if an IMU frame contains valid data.
Checks if the data fields are within logical bounds. Currently these bounds are based off of the BMI088 IMU.
Parameters
frame - The frame to check.
Returns
true - If the frame is valid.
false - If the frame is invalid.
References data::ImuFrame::is_valid, data::ImuFrame::time, data::ImuFrame::x_acceleration, data::ImuFrame::x_angular_velocity, data::ImuFrame::y_acceleration, data::ImuFrame::y_angular_velocity, data::ImuFrame::z_acceleration, and data::ImuFrame::z_angular_velocity.
Referenced by modules::DataModule::processImuFramePacket(), and TEST().
toJson()
Json data::toJson (data::Frame< std::string, data::DataPacket > & frame)
References data::Frame< ID, DATA >::getAll().
Referenced by data_middleware::DataFormatter::addComponent(), and RequestRouter::handleDataRequest().
Variable Documentation
K_GPS_FIX_TO_STRING_MAP
const std::map<GpsFix, std::string> data::K_GPS_FIX_TO_STRING_MAP static
Initial value:
= {
    {GpsFix::ERROR, "error_fix"},
    {GpsFix::NO_FIX, "no_fix"},
    {GpsFix::FIX_2D, "2d_fix"},
    {GpsFix::FIX_3D, "3d_fix"}}
Referenced by console_pages::Pages::location(), to_json(), data::blocks::to_json(), and util::to_string().
rnd
auto data::rnd = bst::doubleToPrecisionTwo inline
Referenced by data::blocks::ServerModuleStats::toJson(), data::blocks::DataLogStats::toJson(), data::blocks::SystemInfo::toJson(), and data::blocks::TelemetryModuleStats::toJson().