Giraffe: protocol Namespace Reference
protocol Namespace Reference
Classes
struct Message
Message struct, for the Giraffe Protocol Message.
Typedefs
typedef std::string MessageId
MessageId type, for the id of a message.
typedef std::string Resource
Enumerations
enum class Endpoint {
UNKNOWN , GFS , GGS , GDL ,
GWC
}
Endpoint enum, for the source and destination of a message.
enum class MessageType { UNKNOWN , REQ , SET , RSP }
Type enum, for the type of message.
enum class ResponseCode { UNKNOWN , GOOD , ERROR }
Functions
void createRequestMessage (Message &message, protocol::Endpoint src, protocol::Endpoint dst, Resource rsc)
Create a Request Message.
void createResponseMessage (Message &message, protocol::Endpoint src, protocol::Endpoint dst, MessageId id, protocol::ResponseCode rsp, Json dat, std::string rsc="")
Create a Response Message.
void createSetMessage (Message &message, protocol::Endpoint src, protocol::Endpoint dst, Resource rsc, Json dat)
Create a Set Message.
bool parseMessage (const std::string &json_string, Message &message)
Parse a JSON string into a Message.
Typedef Documentation
MessageId
typedef std::string protocol::MessageId
MessageId type, for the id of a message.
Resource
typedef std::string protocol::Resource
Enumeration Type Documentation
Endpoint
enum protocol::Endpoint strong
Endpoint enum, for the source and destination of a message.
Enumerator
UNKNOWN
GFS
GGS
GDL
GWC
MessageType
enum protocol::MessageType strong
Type enum, for the type of message.
Enumerator
UNKNOWN
REQ
SET
RSP
ResponseCode
enum protocol::ResponseCode strong
Enumerator
UNKNOWN
GOOD
ERROR
Function Documentation
parseMessage()
bool protocol::parseMessage (const std::string & json_string, protocol::Message & message)
Parse a JSON string into a Message.
Parameters
json_string - The JSON string to parse.
message - The message object to parse into.
Returns
true - If the message was parsed successfully.
false - If the message was not parsed successfully.
References protocol::Message::cde, protocol::Message::dat, protocol::Message::dst, protocol::Message::id, REQ, protocol::Message::rsc, RSP, SET, protocol::Message::src, stringToEndpointMap, stringToResponseCodeMap, stringToTypeMap, protocol::Message::typ, and UNKNOWN.
Referenced by RequestRouter::handleMessage(), and giraffe::gdl::GdlServer::run().
createRequestMessage()
void protocol::createRequestMessage (protocol::Message & message, protocol::Endpoint src, protocol::Endpoint dst, protocol::Resource rsc)
Create a Request Message.
Parameters
message (out) - The message structure to populate.
src - The source of the message.
dst - The destination of the message.
rsc - The resource to request.
Returns
true - If the message is valid.
false - If the message is not valid.
References protocol::Message::dst, protocol::Message::id, REQ, protocol::Message::rsc, protocol::Message::src, and protocol::Message::typ.
createSetMessage()
void protocol::createSetMessage (protocol::Message & message, protocol::Endpoint src, protocol::Endpoint dst, protocol::Resource rsc, Json dat)
Create a Set Message.
Parameters
message (out) - The message structure to populate.
src - The source of the message.
dst - The destination of the message.
rsc - The resource to set.
dat - The data to set the resource to.
Returns
true - If the message is valid.
false - If the message is not valid.
References protocol::Message::dat, protocol::Message::dst, protocol::Message::id, protocol::Message::rsc, SET, protocol::Message::src, and protocol::Message::typ.
createResponseMessage()
void protocol::createResponseMessage (protocol::Message & message, protocol::Endpoint src, protocol::Endpoint dst, protocol::MessageId id, protocol::ResponseCode rsp, Json dat, std::string rsc = "")
Create a Response Message.
Parameters
message (out) - The message structure to populate.
src - The source of the message.
dst - The destination of the message.
id - The id of the message to respond to.
dat - The data to respond with.
rsp - The response code.
rsc - (optional due to backwards compatibility) The resource that the response is for.
Returns
true - If the message is valid.
false - If the message is not valid.
References protocol::Message::cde, protocol::Message::dat, protocol::Message::dst, protocol::Message::id, protocol::Message::rsc, RSP, protocol::Message::src, and protocol::Message::typ.
Referenced by RequestRouter::handleDataRequest(), RequestRouter::handlePingRequest(), RequestRouter::handleSettingRequest(), RequestRouter::handleSettingSet(), RequestRouter::sendErrorPacket(), giraffe::gdl::GdlServer::sendResponseData(), giraffe::gdl::GdlServer::sendResponseError(), giraffe::gdl::GdlServer::sendResponseSuccess(), and RequestRouter::sendSuccessResponse().