Giraffe: extension Namespace Reference
extension Namespace Reference
Classes
struct AdcConfig
ADC Configuration - generated by parsing a config string.
class AdcExtensionBase
class Bme280
class Bmi088
The BMI088 extension.
class Ds18b20
class Extension
struct ExtensionResources
This contains objects that are shared between all extensions.
class I2cExtensionAdapter
Adapter for I2C Extensions.
class Mcp3021
class RgbStatusLed
A simple extension to control an RGB status LED.
class SamM8q
class SimGpsSensor
class SimHumiditySensor
class SimImuSensor
class SimPressureSensor
class SimTemperatureSensor
Enumerations
enum class AdcType { RAW_COUNT , PERCENTAGE , VOLTAGE_DIVIDER , VOLTAGE_REFERENCE }
ADC Types, a way to specify how to interpret the ADC values.
enum class StartupState {
I2C_CONNECT , HANDSHAKE , CONFIGURE , READ_COMPENSATION_DATA ,
DONE , I2C_CONNECT , HANDSHAKE , DONE
}
enum class StartupState {
I2C_CONNECT , HANDSHAKE , CONFIGURE , READ_COMPENSATION_DATA ,
DONE , I2C_CONNECT , HANDSHAKE , DONE
}
Functions
std::string getKeyValue (const std::string &config_string, const std::string &key)
bool parseAdcConfig (std::string config_string, AdcConfig &out_config)
Parse an ADC config string into an AdcConfig struct.
bool parsePercentAdc (std::string config_string, AdcConfig &out_config)
bool parseVoltageDividerAdc (std::string config_string, AdcConfig &out_config)
bool parseVoltageReferenceAdc (std::string config_string, AdcConfig &out_config)
bool validateSerialNumber (const std::string &serial_number)
Variables
constexpr int K_READ_TIMEOUT = 5000
The read timeout in milliseconds. The update interval is added to this.
constexpr uint8_t kBme280I2cAddress = 0x76
constexpr int kCompensationDataReadRate = 5000
constexpr uint32_t kDefaultI2cHandshakeRetryDelayMs = 100
constexpr uint32_t kDefaultI2cHandshakeTimeoutMs = 1000
constexpr int kInitTimeout = 2000
The init timeout in milliseconds.
constexpr uint32_t kWatchdogMultiplier = 4
The ADC timeout multiplier based on the update interval.
Class Documentation
extension::AdcConfig
struct extension::AdcConfig
ADC Configuration - generated by parsing a config string.
Class Members
AdcType type How to interpret the ADC values.
uint32_t resolution The resolution of the ADC in bits.
uint32_t voltage_reference The voltage reference of the ADC in millivolts.
uint32_t resistor_1 The resistance of the first resistor in the voltage divider in ohms.
uint32_t resistor_2 The resistance of the second resistor in the voltage divider in ohms.
uint32_t max The maximum value to use when calculating the percentage.
uint32_t min The minimum value to use when calculating the percentage.
bool clamp Whether or not to clamp the percentage to 0-100.
Enumeration Type Documentation
AdcType
enum extension::AdcType strong
ADC Types, a way to specify how to interpret the ADC values.
See also
adc_config.md
Enumerator
RAW_COUNT
PERCENTAGE
VOLTAGE_DIVIDER
VOLTAGE_REFERENCE
StartupState [1/2]
enum extension::StartupState strong
Enumerator
I2C_CONNECT
HANDSHAKE
CONFIGURE
READ_COMPENSATION_DATA
DONE
I2C_CONNECT
HANDSHAKE
DONE
StartupState [2/2]
enum extension::StartupState strong
Enumerator
I2C_CONNECT
HANDSHAKE
CONFIGURE
READ_COMPENSATION_DATA
DONE
I2C_CONNECT
HANDSHAKE
DONE
Function Documentation
getKeyValue()
std::string extension::getKeyValue (const std::string & config_string, const std::string & key) inline
Referenced by parseAdcConfig(), parsePercentAdc(), parseVoltageDividerAdc(), and parseVoltageReferenceAdc().
parsePercentAdc()
bool extension::parsePercentAdc (std::string config_string, AdcConfig & out_config) inline
References extension::AdcConfig::clamp, getKeyValue(), extension::AdcConfig::max, extension::AdcConfig::min, RAW_COUNT, extension::AdcConfig::resolution, and extension::AdcConfig::type.
Referenced by parseAdcConfig().
parseVoltageDividerAdc()
bool extension::parseVoltageDividerAdc (std::string config_string, AdcConfig & out_config) inline
References getKeyValue(), RAW_COUNT, extension::AdcConfig::resistor_1, extension::AdcConfig::resistor_2, extension::AdcConfig::type, and extension::AdcConfig::voltage_reference.
Referenced by parseAdcConfig().
parseVoltageReferenceAdc()
bool extension::parseVoltageReferenceAdc (std::string config_string, AdcConfig & out_config) inline
References getKeyValue(), RAW_COUNT, extension::AdcConfig::type, VOLTAGE_REFERENCE, and extension::AdcConfig::voltage_reference.
Referenced by parseAdcConfig().
parseAdcConfig()
bool extension::parseAdcConfig (std::string config_string, AdcConfig & out_config)
Parse an ADC config string into an AdcConfig struct.
If a configuration is invalid for a given type, it will revert to 'RAW_COUNT'.
See also
adc_config.md
Parameters
config_string - The config string to parse.
out_config - The config struct to populate.
Returns
true - If the config string was parsed successfully.
false - If the string was invalid.
References getKeyValue(), parsePercentAdc(), parseVoltageDividerAdc(), parseVoltageReferenceAdc(), PERCENTAGE, RAW_COUNT, extension::AdcConfig::resolution, extension::AdcConfig::type, VOLTAGE_DIVIDER, and VOLTAGE_REFERENCE.
Referenced by extension::AdcExtensionBase< AdcResolution >::AdcExtensionBase().
validateSerialNumber()
bool extension::validateSerialNumber (const std::string & serial_number) inline
Referenced by extension::Ds18b20::init().
Variable Documentation
kWatchdogMultiplier
constexpr uint32_t extension::kWatchdogMultiplier = 4 inline constexpr
The ADC timeout multiplier based on the update interval.
kBme280I2cAddress
constexpr uint8_t extension::kBme280I2cAddress = 0x76 inline constexpr
kCompensationDataReadRate
constexpr int extension::kCompensationDataReadRate = 5000 inline constexpr
K_READ_TIMEOUT
constexpr int extension::K_READ_TIMEOUT = 5000 inline constexpr
The read timeout in milliseconds. The update interval is added to this.
This thing is slow through the 1w file interface
kInitTimeout
constexpr int extension::kInitTimeout = 2000 inline constexpr
The init timeout in milliseconds.
kDefaultI2cHandshakeTimeoutMs
constexpr uint32_t extension::kDefaultI2cHandshakeTimeoutMs = 1000 inline constexpr
kDefaultI2cHandshakeRetryDelayMs
constexpr uint32_t extension::kDefaultI2cHandshakeRetryDelayMs = 100 inline constexpr