Giraffe: util Namespace Reference
util Namespace Reference
Generic to_string functions for a variety of types.
Functions
Json to_json (data::GpsFrame gps_frame)
std::string to_string (const data::DataId id) noexcept
std::string to_string (const data::DataPacket &packet) noexcept
std::string to_string (const data::GpsFix fix_type) noexcept
std::string to_string (const data::GpsFrame &frame) noexcept
std::string to_string (const data::GpsFramePacket &packet) noexcept
std::string to_string (const data::ImuFrame &frame) noexcept
std::string to_string (const data::ImuFramePacket &packet) noexcept
std::string to_string (const data::LogPacket &packet) noexcept
std::string to_string (const data::LogPacket::Level level) noexcept
std::string to_string (const DiagnosticId diagnostic_id) noexcept
std::string to_string (const node::Identification id) noexcept
std::string to_string (data::DataPacket::Type type) noexcept
Detailed Description
Generic to_string functions for a variety of types.
The only requirement is that they must be exception safe. So if they use a map, first map sure the key exists.
Function Documentation
to_json()
Json util::to_json (data::GpsFrame gps_frame)
References data::GpsFrame::altitude, data::GpsFrame::fix, data::GpsFrame::gps_utc_time, data::GpsFrame::heading_accuracy, data::GpsFrame::heading_of_motion, data::GpsFrame::horizontal_speed, data::GpsFrame::horz_accuracy, data::GpsFrame::is_valid, data::GpsFrame::latitude, data::GpsFrame::longitude, data::GpsFrame::num_satellites, data::GpsFrame::speed_accuracy, to_string(), data::GpsFrame::vert_accuracy, and data::GpsFrame::vertical_speed.
Referenced by data_middleware::InfluxDb::writeFrames().
to_string() [1/12]
std::string util::to_string (const node::Identification id) noexcept
References node::K_IDENTIFICATION_TO_STRING_MAP.
Referenced by giraffe::Gpio::Pin::Pin(), modules::DataModule::calculateCalculatedData(), console_pages::Pages::data(), extension::Extension::data(), modules::Module::data(), extension::Extension::error(), modules::Module::error(), data::LogStream::errorBoosterSeatException(), console_pages::Pages::extensionData(), console_pages::Pages::extensions(), giraffe::gdl::GdlServer::getNextResponseId(), data_middleware::InfluxLine::getString(), getUnixTime(), console_pages::Pages::gfsStatus(), console_pages::Pages::location(), data_middleware::InfluxDb::logDataPacket(), data_middleware::InfluxDb::logLogPacket(), data_middleware::DataFormatter::logPacketToJsonString(), modules::TelemetryModule::processCommand(), modules::DataModule::processLogPacket(), giraffe::Gpio::read(), giraffe::gdl::GdlServer::run(), console_pages::Pages::server(), cfg::Extensions::setFromJson(), giraffe::Gpio::setupPin(), modules::ServerModule::startup(), console_pages::Pages::telemetry(), to_json(), to_string(), and giraffe::Gpio::write().
to_string() [2/12]
std::string util::to_string (const data::LogPacket::Level level) noexcept
References data::LogPacket::DEBUG, data::LogPacket::ERROR, data::LogPacket::INFO, and data::LogPacket::WARN.
to_string() [3/12]
std::string util::to_string (const data::LogPacket & packet) noexcept
References to_string().
to_string() [4/12]
std::string util::to_string (const data::DataId id) noexcept
to_string() [5/12]
std::string util::to_string (const data::DataPacket & packet) noexcept
References to_string().
to_string() [6/12]
std::string util::to_string (const data::GpsFix fix_type) noexcept
References data::K_GPS_FIX_TO_STRING_MAP.
to_string() [7/12]
std::string util::to_string (const data::GpsFrame & frame) noexcept
References f2s(), and to_string().
to_string() [8/12]
std::string util::to_string (const data::GpsFramePacket & packet) noexcept
References to_string().
to_string() [9/12]
std::string util::to_string (const DiagnosticId diagnostic_id) noexcept
to_string() [10/12]
std::string util::to_string (data::DataPacket::Type type) noexcept
References data::DataPacket::GENERIC, and data::DataPacket::STATUS.
to_string() [11/12]
std::string util::to_string (const data::ImuFrame & frame) noexcept
References to_string().
to_string() [12/12]
std::string util::to_string (const data::ImuFramePacket & packet) noexcept
References to_string().
Referenced by to_string().