Giraffe: giraffe::file_paths Namespace Reference
giraffe::file_paths Namespace Reference
Functions
bool createGiraffeDirIfNotExists ()
Creates the Giraffe directory if it does not exist. Throws a GiraffeException if it cannot be created.
std::string generateFileNameWithTimestamp (const std::string &extension)
Generates a file name with the current time as a prefix.
std::string getGdlServerConfigFilePath ()
Returns the path to the Giraffe config file.
std::string getGfsConfigFilePath ()
Returns the path to the Flight Software config file.
std::string getGfsDataArchiveDirPath ()
Returns the path to the gfs data archive directory. Creates the directory if it does not exist.
std::string getGfsDataDirPath ()
Returns the path to the gfs data directory. Creates the directory if it does not exist.
std::string getGfsFlightRunnerDataFilePath ()
Get the Gfs Flight Runner Data File Path object.
std::string getGfsImageDirPath ()
Returns the path to the gfs image directory. Creates the directory if it does not exist.
std::string getGfsLogArchiveDirPath ()
Returns the path to the gfs log archive directory. Creates the directory if it does not exist.
std::string getGfsLogDirPath ()
Returns the path to the gfs log directory. Creates the directory if it does not exist.
std::string getGiraffeDirectoryPath ()
Get the Giraffe Directory Path.
Variables
const std::string GIRAFFE_DIRECTORY = ".giraffe"
Function Documentation
getGiraffeDirectoryPath()
std::string giraffe::file_paths::getGiraffeDirectoryPath ()
Get the Giraffe Directory Path.
Requires the HOME environment variable to be set. Will throw a GiraffeException if it is not set.
Returns
std::string The path to the Giraffe directory.
References GIRAFFE_DIRECTORY.
Referenced by data_middleware::FileSystemManager::FileSystemManager(), createGiraffeDirIfNotExists(), getGdlServerConfigFilePath(), getGfsConfigFilePath(), getGfsDataDirPath(), getGfsFlightRunnerDataFilePath(), getGfsImageDirPath(), and getGfsLogDirPath().
createGiraffeDirIfNotExists()
bool giraffe::file_paths::createGiraffeDirIfNotExists ()
Creates the Giraffe directory if it does not exist. Throws a GiraffeException if it cannot be created.
Returns
true - The directory did not exist and was created.
false - The directory already exists.
References getGiraffeDirectoryPath().
Referenced by getGfsDataArchiveDirPath(), getGfsDataDirPath(), getGfsImageDirPath(), getGfsLogArchiveDirPath(), getGfsLogDirPath(), and giraffe::gdl::GdlServer::loadConfig().
getGdlServerConfigFilePath()
std::string giraffe::file_paths::getGdlServerConfigFilePath ()
Returns the path to the Giraffe config file.
Returns
std::string - $HOME/.giraffe/gdl_server.json
References getGiraffeDirectoryPath().
Referenced by giraffe::gdl::GdlServer::loadConfig(), and giraffe::gdl::GdlServer::saveConfig().
getGfsConfigFilePath()
std::string giraffe::file_paths::getGfsConfigFilePath ()
Returns the path to the Flight Software config file.
Returns
std::string - $HOME/.giraffe/gfs_config.json
References getGiraffeDirectoryPath().
Referenced by FlightRunner::flightLoop(), and FlightRunner::start().
getGfsFlightRunnerDataFilePath()
std::string giraffe::file_paths::getGfsFlightRunnerDataFilePath ()
Get the Gfs Flight Runner Data File Path object.
Returns
std::string - $HOME/.giraffe/flight_runner_data.json
References getGiraffeDirectoryPath().
getGfsImageDirPath()
std::string giraffe::file_paths::getGfsImageDirPath ()
Returns the path to the gfs image directory. Creates the directory if it does not exist.
Returns
std::string - $HOME/.giraffe/gfs_images
References createGiraffeDirIfNotExists(), and getGiraffeDirectoryPath().
Referenced by data_middleware::FileSystemManager::FileSystemManager(), extension::PiCamera::PiCamera(), extension::SimCamera::SimCamera(), and RequestRouter::handleImageRequest().
getGfsDataDirPath()
std::string giraffe::file_paths::getGfsDataDirPath ()
Returns the path to the gfs data directory. Creates the directory if it does not exist.
Returns
std::string - $HOME/.giraffe/gfs_data
References createGiraffeDirIfNotExists(), and getGiraffeDirectoryPath().
Referenced by data_middleware::DataLog::createDataDir(), and getGfsDataArchiveDirPath().
getGfsDataArchiveDirPath()
std::string giraffe::file_paths::getGfsDataArchiveDirPath ()
Returns the path to the gfs data archive directory. Creates the directory if it does not exist.
Returns
std::string - $HOME/.giraffe/gfs_data/archive
References createGiraffeDirIfNotExists(), and getGfsDataDirPath().
Referenced by data_middleware::DataLog::createDataArchiveDir().
getGfsLogDirPath()
std::string giraffe::file_paths::getGfsLogDirPath ()
Returns the path to the gfs log directory. Creates the directory if it does not exist.
Returns
std::string - $HOME/.giraffe/gfs_log
References createGiraffeDirIfNotExists(), and getGiraffeDirectoryPath().
Referenced by data_middleware::DataLog::createLogDir(), and getGfsLogArchiveDirPath().
getGfsLogArchiveDirPath()
std::string giraffe::file_paths::getGfsLogArchiveDirPath ()
Returns the path to the gfs log archive directory. Creates the directory if it does not exist.
Returns
std::string - $HOME/.giraffe/gfs_log/archive
References createGiraffeDirIfNotExists(), and getGfsLogDirPath().
Referenced by data_middleware::DataLog::createLogArchiveDir().
generateFileNameWithTimestamp()
std::string giraffe::file_paths::generateFileNameWithTimestamp (const std::string & extension)
Generates a file name with the current time as a prefix.
Parameters
extension - The file extension to use
Returns
<utc data time>.<extension>
Warning
This function will not generate unique file names if called multiple times within the same second.
Variable Documentation
GIRAFFE_DIRECTORY
const std::string giraffe::file_paths::GIRAFFE_DIRECTORY = ".giraffe"
Referenced by getGiraffeDirectoryPath().