Giraffe: ubx Namespace Reference
ubx Namespace Reference
Classes
struct NavData
struct UBXMessage
Typedefs
typedef struct ubx::UBXMessage UBXMessage
Enumerations
enum class ACK {
ACK , NACK , NONE , WRITE_ERROR ,
READ_ERROR
}
enum class DYNAMIC_MODEL {
PORTABLE = 0x00 , STATIONARY = 0x02 , PEDESTRIAN = 0x03 , AUTOMOTIVE = 0x04 ,
SEA = 0x05 , AIRBORNE_1G = 0x06 , AIRBORNE_2G = 0x07 , AIRBORNE_4G = 0x08 ,
ERROR = 0xFF
}
enum class FixType {
NO_FIX = 0x00 , DEAD_RECK = 0x01 , FIX_2D = 0x02 , FIX_3D = 0x03 ,
COMBINED = 0x04 , TIME_ONLY = 0x05 , ERROR = 0xFF
}
Functions
ACK checkForAck (I2cInterface &i2c, const uint8_t msg_class, const uint8_t msg_id)
bool flushStream (I2cInterface &i2c)
int getStreamSize (I2cInterface &i2c)
std::ostream & operator<< (std::ostream &o, const NavData &nv)
std::ostream & operator<< (std::ostream &o, const UBXMessage &ubx)
bool parsePVT (const UBXMessage &message, NavData &data)
bool pollMessage (I2cInterface &i2c, UBXMessage &message, const uint8_t msg_class, const uint8_t msg_id, const int expected_size, const unsigned int timeout_ms)
Poll a message and read it from the GPS.
bool readNextUBX (I2cInterface &i2c, UBXMessage &message)
bool readSpecificMessage (I2cInterface &i2c, UBXMessage &message)
bool sendResetCommand (I2cInterface &i2c)
Send a UBX-CFG-RST command to the receiver (Hardware Reset)
ACK setDynamicModel (I2cInterface &i2c, const DYNAMIC_MODEL model)
ACK setMeasurementRate (I2cInterface &i2c, const uint16_t rate_ms)
ACK setMessageRate (I2cInterface &i2c, uint8_t msg_class, uint8_t msg_id, uint8_t rate)
CFG-MSG (0x06 0x01) Configure Message Rate.
ACK setProtocolDDC (I2cInterface &i2c, const bool extended_timeout)
Configure the I2C port to use UBX protocol for input and output.
bool writeUBX (I2cInterface &i2c, const UBXMessage &message)
bool writeUBX (I2cInterface &i2c, UBXMessage &message)
Variables
constexpr uint8_t kAckClassId = 0x05
constexpr uint8_t kCfgClassId = 0x06
constexpr uint8_t kInfClassId = 0x04
constexpr uint8_t kMgaClassId = 0x13
constexpr uint8_t kMonClassId = 0x0A
constexpr uint8_t kNavClassId = 0x01
constexpr uint8_t kNavPvt = 0x07
const std::unordered_map< uint8_t, std::string > UbxClassToString
const std::unordered_map< uint8_t, std::string > UbxIdToString
Class Documentation
ubx::NavData
struct ubx::NavData
Class Members
bool valid
int year
Todo:
currently, this really doesn't do anything
int month
int day
int hour
int minute
int second
FixType fix_type
int num_satellites
double latitude
double longitude
double horz_accuracy
double altitude
double vert_accuracy
double ground_speed
double speed_accuracy
double heading_of_motion
double heading_accuracy
Typedef Documentation
UBXMessage
typedef struct ubx::UBXMessage ubx::UBXMessage
Enumeration Type Documentation
ACK
enum ubx::ACK strong
Enumerator
ACK
NACK
NONE
WRITE_ERROR
READ_ERROR
DYNAMIC_MODEL
enum ubx::DYNAMIC_MODEL strong
Enumerator
PORTABLE
STATIONARY
PEDESTRIAN
AUTOMOTIVE
SEA
AIRBORNE_1G
AIRBORNE_2G
AIRBORNE_4G
ERROR
FixType
enum ubx::FixType strong
Enumerator
NO_FIX
DEAD_RECK
FIX_2D
FIX_3D
COMBINED
TIME_ONLY
ERROR
Function Documentation
getStreamSize()
int ubx::getStreamSize (I2cInterface & i2c)
In bytes, prevents over reading when there is an error with message size
References I2cInterface::readByteFromReg(), and I2cInterface::SUCCESS.
Referenced by checkForAck(), flushStream(), main(), pollMessage(), readNextUBX(), and TEST_F().
flushStream()
bool ubx::flushStream (I2cInterface & i2c)
References getStreamSize(), kStreamRegister, and I2cInterface::readChunkFromReg().
Referenced by main(), pollMessage(), and extension::SamM8q::stateRead().
readNextUBX()
bool ubx::readNextUBX (I2cInterface & i2c, UBXMessage & message)
First finds sync characters, then reads the rest of the message once it becomes available.
References ubx::UBXMessage::ck_a, ubx::UBXMessage::ck_b, getStreamSize(), kMaxPayloadSize, kStreamRegister, kSyncChar1, kSyncChar2, ubx::UBXMessage::length, ubx::UBXMessage::mClass, ubx::UBXMessage::mID, ubx::UBXMessage::payload, I2cInterface::readByteFromReg(), I2cInterface::readChunkFromReg(), I2cInterface::SUCCESS, UbxClassToString, UbxIdToString, and ubx::UBXMessage::verifyChecksum().
Referenced by checkForAck(), and readSpecificMessage().
readSpecificMessage()
bool ubx::readSpecificMessage (I2cInterface & i2c, UBXMessage & message)
References ubx::UBXMessage::length, ubx::UBXMessage::mClass, ubx::UBXMessage::mID, and readNextUBX().
writeUBX() [1/2]
bool ubx::writeUBX (I2cInterface & i2c, UBXMessage & message)
References ubx::UBXMessage::ck_a, ubx::UBXMessage::ck_b, ubx::UBXMessage::length, ubx::UBXMessage::mClass, ubx::UBXMessage::mID, ubx::UBXMessage::payload, I2cInterface::SUCCESS, ubx::UBXMessage::sync1, ubx::UBXMessage::sync2, and I2cInterface::writeChunk().
Referenced by pollMessage(), sendResetCommand(), setDynamicModel(), setMeasurementRate(), setMessageRate(), setProtocolDDC(), and TEST_F().
checkForAck()
ACK ubx::checkForAck (I2cInterface & i2c, const uint8_t msg_class, const uint8_t msg_id)
References ACK, getStreamSize(), kMaxMessageRetryAttempts, kMessageRetryDelayTime, ubx::UBXMessage::mClass, ubx::UBXMessage::mID, NACK, NONE, ubx::UBXMessage::payload, and readNextUBX().
Referenced by setDynamicModel(), setMeasurementRate(), setMessageRate(), setProtocolDDC(), and TEST_F().
sendResetCommand()
bool ubx::sendResetCommand (I2cInterface & i2c)
Send a UBX-CFG-RST command to the receiver (Hardware Reset)
References writeUBX().
Referenced by main(), extension::SamM8q::stateReset(), and TEST_F().
setProtocolDDC()
ACK ubx::setProtocolDDC (I2cInterface & i2c, const bool extended_timeout)
Configure the I2C port to use UBX protocol for input and output.
UBX-CFG-PRT (0x06 0x00) Configure I/O Port (Specifically I2C) Length: 20 bytes
[portID U1][reserved1 U1][txReady X2][mode X4][reserved2 U1[4]] [inProtoMask X2][outProtoMask X2][flags X2]<reserved3 U1[2]]
Does not configure TXReady
See also
32.10.25.5 of u-blox 8 / u-blox M8 Receiver Description
References checkForAck(), I2cInterface::getAddress(), WRITE_ERROR, and writeUBX().
Referenced by main(), extension::SamM8q::stateConfigure(), and TEST_F().
setMessageRate()
ACK ubx::setMessageRate (I2cInterface & i2c, uint8_t msg_class, uint8_t msg_id, uint8_t rate)
CFG-MSG (0x06 0x01) Configure Message Rate.
"Send rate is relative to the event a message is registered on. For example, if the rate of a navigation message is set to 2, the message is sent every second navigation solution."
See also
32.10.18.3
References checkForAck(), WRITE_ERROR, and writeUBX().
Referenced by TEST_F().
setMeasurementRate()
ACK ubx::setMeasurementRate (I2cInterface & i2c, const uint16_t rate_ms)
References checkForAck(), WRITE_ERROR, and writeUBX().
Referenced by main(), extension::SamM8q::stateConfigure(), and TEST_F().
setDynamicModel()
ACK ubx::setDynamicModel (I2cInterface & i2c, const DYNAMIC_MODEL model)
References checkForAck(), WRITE_ERROR, and writeUBX().
Referenced by main(), extension::SamM8q::stateConfigure(), and TEST_F().
pollMessage()
bool ubx::pollMessage (I2cInterface & i2c, UBXMessage & message, const uint8_t msg_class, const uint8_t msg_id, const int expected_size, const unsigned int timeout_ms)
Poll a message and read it from the GPS.
Messages can be polled by sending the header with a zero length payload.
Warning
I'm suspicious of this after looking back over 6 months later. Then again, I'm suspicious of this entire file.
Not exactly sure if this was the intended purpose, but previously there was undocumented pointer math. This is something to look back at if it's broken.
References ubx::UBXMessage::ck_a, ubx::UBXMessage::ck_b, flushStream(), getStreamSize(), kStreamRegister, ubx::UBXMessage::length, ubx::UBXMessage::mClass, ubx::UBXMessage::mID, ubx::UBXMessage::payload, I2cInterface::readChunkFromReg(), I2cInterface::SUCCESS, ubx::UBXMessage::sync1, ubx::UBXMessage::sync2, ubx::UBXMessage::verifyChecksum(), wait(), and writeUBX().
Referenced by main(), and extension::SamM8q::stateRead().
parsePVT()
bool ubx::parsePVT (const UBXMessage & message, NavData & data)
References COMBINED, DEAD_RECK, ERROR, FIX_2D, FIX_3D, ubx::UBXMessage::length, ubx::UBXMessage::mClass, ubx::UBXMessage::mID, NO_FIX, parseI4(), parseU2(), parseU4(), ubx::UBXMessage::payload, and TIME_ONLY.
Referenced by main(), and extension::SamM8q::stateRead().
operator<<() [1/2]
std::ostream & ubx::operator<< (std::ostream & o, const UBXMessage & ubx)
References UbxClassToString, and UbxIdToString.
operator<<() [2/2]
std::ostream & ubx::operator<< (std::ostream & o, const NavData & nv)
References ubx::NavData::altitude, COMBINED, ubx::NavData::day, DEAD_RECK, FIX_2D, FIX_3D, ubx::NavData::fix_type, ubx::NavData::ground_speed, ubx::NavData::heading_accuracy, ubx::NavData::heading_of_motion, ubx::NavData::horz_accuracy, ubx::NavData::hour, ubx::NavData::latitude, ubx::NavData::longitude, ubx::NavData::minute, ubx::NavData::month, NO_FIX, ubx::NavData::second, ubx::NavData::speed_accuracy, TIME_ONLY, ubx::NavData::valid, ubx::NavData::vert_accuracy, and ubx::NavData::year.
writeUBX() [2/2]
bool ubx::writeUBX (I2cInterface & i2c, const UBXMessage & message)
Variable Documentation
kNavClassId
constexpr uint8_t ubx::kNavClassId = 0x01 inline constexpr
Referenced by extension::SamM8q::stateRead().
kInfClassId
constexpr uint8_t ubx::kInfClassId = 0x04 inline constexpr
kAckClassId
constexpr uint8_t ubx::kAckClassId = 0x05 inline constexpr
kCfgClassId
constexpr uint8_t ubx::kCfgClassId = 0x06 inline constexpr
kMonClassId
constexpr uint8_t ubx::kMonClassId = 0x0A inline constexpr
kMgaClassId
constexpr uint8_t ubx::kMgaClassId = 0x13 inline constexpr
kNavPvt
constexpr uint8_t ubx::kNavPvt = 0x07 inline constexpr
Referenced by main(), extension::SamM8q::stateRead(), and TEST_F().
UbxClassToString
const std::unordered_map<uint8_t, std::string> ubx::UbxClassToString
Initial value:
= {
    {kNavClassId, "NAV"}, {kInfClassId, "INF"}, {kAckClassId, "ACK"},
    {kCfgClassId, "CFG"}, {kMonClassId, "MON"}, {kMgaClassId, "MGA"}}
Referenced by operator<<(), and readNextUBX().
UbxIdToString
const std::unordered_map<uint8_t, std::string> ubx::UbxIdToString
Referenced by operator<<(), and readNextUBX().