Giraffe: shared_data_helpers.hpp File Reference
shared_data_helpers.hpp File Reference
#include "shared_data.hpp"
#include "to_string.hpp"
Classes
class FakeSharedData
Functions
void setCalculatedDataAscent (data::SharedData &shared)
void setCalculatedDataDescent (data::SharedData &shared)
void setCalculatedDataInvalid (data::SharedData &shared)
void setCalculatedDataLaunch (data::SharedData &shared)
void setCalculatedDataRecovery (data::SharedData &shared)
void setCalculatedDataValid (data::SharedData &shared)
void setLocationDataAscent (data::SharedData &shared)
void setLocationDataDescent (data::SharedData &shared)
void setLocationDataInvalid (data::SharedData &shared)
void setLocationDataLaunch (data::SharedData &shared)
void setLocationDataRecovery (data::SharedData &shared)
void setLocationDataValid (data::SharedData &shared)
Function Documentation
setLocationDataValid()
void setLocationDataValid (data::SharedData & shared) inline
References data::SharedData::blocks, data::FIX_3D, data::GpsFrame::gps_utc_time, data::blocks::LocationData::have_gps_source, and data::SharedBlocks::location_data.
Referenced by TEST_F().
setLocationDataInvalid()
void setLocationDataInvalid (data::SharedData & shared) inline
References data::SharedData::blocks, data::GpsFrame::gps_utc_time, data::blocks::LocationData::have_gps_source, data::SharedBlocks::location_data, and data::NO_FIX.
Referenced by FlightPhaseManagerTest::setParamsInvalid(), and TEST_F().
setLocationDataLaunch()
void setLocationDataLaunch (data::SharedData & shared) inline
References data::SharedData::blocks, data::FIX_3D, data::GpsFrame::gps_utc_time, data::blocks::LocationData::have_gps_source, and data::SharedBlocks::location_data.
Referenced by FlightPhaseManagerTest::setParamsLaunch(), and TEST_F().
setLocationDataAscent()
void setLocationDataAscent (data::SharedData & shared) inline
References data::SharedData::blocks, data::FIX_3D, data::GpsFrame::gps_utc_time, data::blocks::LocationData::have_gps_source, and data::SharedBlocks::location_data.
Referenced by FlightPhaseManagerTest::setParamsAscent(), and TEST_F().
setLocationDataDescent()
void setLocationDataDescent (data::SharedData & shared) inline
References data::SharedData::blocks, data::FIX_3D, data::GpsFrame::gps_utc_time, data::blocks::LocationData::have_gps_source, and data::SharedBlocks::location_data.
Referenced by FlightPhaseManagerTest::setParamsDescent(), and TEST_F().
setLocationDataRecovery()
void setLocationDataRecovery (data::SharedData & shared) inline
References data::SharedData::blocks, data::FIX_3D, data::GpsFrame::gps_utc_time, data::blocks::LocationData::have_gps_source, and data::SharedBlocks::location_data.
Referenced by FlightPhaseManagerTest::setParamsRecovery(), and TEST_F().
setCalculatedDataValid()
void setCalculatedDataValid (data::SharedData & shared) inline
References data::SharedData::blocks, data::SharedBlocks::calculated_data, and data::blocks::CalculatedData::pressure_altitude_m.
Referenced by TEST_F().
setCalculatedDataInvalid()
void setCalculatedDataInvalid (data::SharedData & shared) inline
References data::SharedData::blocks, data::SharedBlocks::calculated_data, and data::blocks::CalculatedData::pressure_altitude_m.
Referenced by FlightPhaseManagerTest::setParamsInvalid(), and TEST_F().
setCalculatedDataLaunch()
void setCalculatedDataLaunch (data::SharedData & shared) inline
References data::SharedData::blocks, data::SharedBlocks::calculated_data, and data::blocks::CalculatedData::pressure_altitude_m.
Referenced by FlightPhaseManagerTest::setParamsLaunch(), and TEST_F().
setCalculatedDataAscent()
void setCalculatedDataAscent (data::SharedData & shared) inline
References data::SharedData::blocks, data::SharedBlocks::calculated_data, and data::blocks::CalculatedData::pressure_altitude_m.
Referenced by FlightPhaseManagerTest::setParamsAscent(), and TEST_F().
setCalculatedDataDescent()
void setCalculatedDataDescent (data::SharedData & shared) inline
References data::SharedData::blocks, data::SharedBlocks::calculated_data, and data::blocks::CalculatedData::pressure_altitude_m.
Referenced by FlightPhaseManagerTest::setParamsDescent(), and TEST_F().
setCalculatedDataRecovery()
void setCalculatedDataRecovery (data::SharedData & shared) inline
References data::SharedData::blocks, data::SharedBlocks::calculated_data, and data::blocks::CalculatedData::pressure_altitude_m.
Referenced by FlightPhaseManagerTest::setParamsRecovery(), and TEST_F().