Giraffe: main.cpp File Reference
src/data_link/server/main.cpp File Reference
Giraffe Data Link Server Main File.
#include <csignal>
#include "gdl_server.hpp"
Functions
int main ()
auto signalHandler (int signal_number) -> void
Variables
giraffe::gdl::GdlServer server {}
Detailed Description
Giraffe Data Link Server Main File.
=*========GIRAFFE========*= A Unified Flight Command and Control System https://github.com/joshua-jerred/Giraffe https://giraffe.joshuajer.red/ =*=======================*=
=*=======================*=
Author
Joshua Jerred (https://joshuajer.red)
Date
2024-01-13
Copyright
2024 (license to be defined)
Function Documentation
signalHandler()
auto signalHandler (int signal_number) -> void
References server, and giraffe::gdl::GdlServer::stop().
Referenced by main().
main()
int main ()
References giraffe::gdl::GdlServer::run(), server, and signalHandler().
Variable Documentation
server
giraffe::gdl::GdlServer server {}
Referenced by main(), and signalHandler().