Giraffe: data::Misc Struct Reference
data::Misc Struct Reference
#include <shared_data.hpp>
Public Member Functions
double getUptimeHours () const
std::string getUptimeString () const
Public Attributes
const BoosterSeat::clck::TimePoint start_time = BoosterSeat::clck::now()
const bst::Time startup_time = bst::Time(true)
The time the flight computer started up.
Member Function Documentation
getUptimeHours()
double data::Misc::getUptimeHours () const inline
References start_time.
getUptimeString()
std::string data::Misc::getUptimeString () const inline
References start_time.
Referenced by data_middleware::DataFormatter::fullErrorFrame(), and data_middleware::DataFormatter::setupFrameStructure().
Member Data Documentation
start_time
const BoosterSeat::clck::TimePoint data::Misc::start_time = BoosterSeat::clck::now()
Todo:
remove this
Warning
DEPRECATED
Referenced by getUptimeHours(), and getUptimeString().
startup_time
const bst::Time data::Misc::startup_time = bst::Time(true)
The time the flight computer started up.