Giraffe: data::SharedData Struct Reference
data::SharedData Struct Reference
Data that is shared across all modules and extensions.
#include <shared_data.hpp>
Public Attributes
SharedBlocks blocks {}
data::FlightData flight_data = FlightData()
Frames frames = Frames()
LogContainer log_container {}
giraffe::StatusLedState status_led {}
Streams streams = Streams()
Detailed Description
Data that is shared across all modules and extensions.
Member Data Documentation
flight_data
data::FlightData data::SharedData::flight_data = FlightData()
Referenced by data_middleware::CalculatedData::calculateDistanceData(), FlightRunner::fl_phaseChanged(), data_middleware::DataFormatter::fullErrorFrame(), RequestRouter::handleDataRequest(), FlightPhaseManager::setFlightPhase(), FlightRunner::setLaunchPosition(), data_middleware::DataFormatter::setupFrameStructure(), FlightPhaseManager::update(), bit::BuiltInTest::updateBitTestData(), and giraffe::AprsManager::updateTelemetryData().
streams
Streams data::SharedData::streams = Streams()
Referenced by FlightPhaseManagerTest::bringToAscent(), FlightPhaseManagerTest::bringToDescent(), FlightPhaseManagerTest::bringToLaunch(), FlightPhaseManagerTest::dumpDataStream(), FakeSharedData::dumpLog(), FlightRunner::fl_reportDescent(), RequestRouter::handleAdcMappingSettingUpdate(), RequestRouter::handleBitTestSet(), RequestRouter::handleCommandRequest(), RequestRouter::handleExtensionSettingUpdate(), FakeSharedData::hasDataItem(), FakeSharedData::hasDataItems(), FakeSharedData::hasLogItem(), FakeSharedData::hasLogItems(), data_middleware::AdcInterpolation::insertVoltageDividerValue(), ConfigurationTest::printStreamErrors(), FlightRunner::processCommand(), data::ErrorReporter::reportError(), FlightRunner::routeCommand(), FlightPhaseManager::setFlightPhase(), FlightRunner::setLaunchPosition(), ConfigurationTest::SetUp(), DataModuleTests::SetUp(), bit::TestCase::update(), FlightPhaseManagerTest::validateHasDataItem(), FlightPhaseManagerTest::validateHasError(), FlightPhaseManagerTest::validateNoData(), and FlightPhaseManagerTest::validateNoError().
frames
Frames data::SharedData::frames = Frames()
Referenced by data_middleware::DataFormatter::addComponent(), data_middleware::DataFormatter::fullErrorFrame(), RequestRouter::handleDataRequest(), data_middleware::AdcInterpolation::insertVoltageDividerValue(), data_middleware::AdcInterpolation::processDataPacket(), data::ErrorReporter::reportError(), bit::test_case::runTestFCS_0001(), and TEST().
blocks
SharedBlocks data::SharedData::blocks {}
Referenced by data_middleware::DataLog::DataLog(), data_middleware::DataFormatter::addComponent(), RequestRouter::handleDataRequest(), modules::ExtensionModule::loop(), bit::test_case::runTestGPS_0400(), setCalculatedDataAscent(), setCalculatedDataDescent(), setCalculatedDataInvalid(), setCalculatedDataLaunch(), setCalculatedDataRecovery(), setCalculatedDataValid(), FlightRunner::setLaunchPosition(), setLocationDataAscent(), setLocationDataDescent(), setLocationDataInvalid(), setLocationDataLaunch(), setLocationDataRecovery(), setLocationDataValid(), data_middleware::FileSystemManager::update(), data_middleware::CalculatedData::updateCalculatedData(), giraffe::AprsManager::updateTelemetryData(), and data_middleware::InfluxDb::writeFrames().
log_container
LogContainer data::SharedData::log_container {}
status_led
giraffe::StatusLedState data::SharedData::status_led {}
Referenced by FlightRunner::fl_phaseChanged(), modules::ExtensionModule::loop(), and modules::ExtensionModule::startup().