Giraffe: data::blocks::StreamsStats Struct Reference
data::blocks::StreamsStats Struct Reference
Struct containing statistics about the data and log streams.
#include <blocks.hpp>
Classes
struct StreamStats
Public Member Functions
Json toJson ()
Public Attributes
StreamStats command = StreamStats()
StreamStats data = StreamStats()
StreamStats gps = StreamStats()
StreamStats imu = StreamStats()
StreamStats log = StreamStats()
Detailed Description
Struct containing statistics about the data and log streams.
Class Documentation
data::blocks::StreamsStats::StreamStats
struct data::blocks::StreamsStats::StreamStats
Class Members
int current_packets
int total_packets
int processing_delay_ms
Member Function Documentation
toJson()
Json data::blocks::StreamsStats::toJson () inline
References data::blocks::StreamsStats::StreamStats::current_packets, gps, imu, log, data::blocks::StreamsStats::StreamStats::processing_delay_ms, and data::blocks::StreamsStats::StreamStats::total_packets.
Member Data Documentation
data
StreamStats data::blocks::StreamsStats::data = StreamStats()
Referenced by console_pages::Pages::data().
log
StreamStats data::blocks::StreamsStats::log = StreamStats()
Referenced by console_pages::Pages::data(), and toJson().
gps
StreamStats data::blocks::StreamsStats::gps = StreamStats()
Referenced by console_pages::Pages::data(), and toJson().
imu
StreamStats data::blocks::StreamsStats::imu = StreamStats()
Referenced by console_pages::Pages::data(), and toJson().
command
StreamStats data::blocks::StreamsStats::command = StreamStats()