Giraffe: test_gdl_message.cpp File Reference
test_gdl_message.cpp File Reference
#include "gtest/gtest.h"
#include "gdl_message.hpp"
Functions
TEST (GdlMessage, BroadcastMessage)
TEST (GdlMessage, ExchangeMessage)
TEST (GdlMessage, ImageMessage)
TEST (GdlMessage, LocationMessage)
TEST (GdlMessage, VerifyType)
Function Documentation
TEST() [1/5]
TEST (GdlMessage , BroadcastMessage)
References giraffe::gdl::Message::BROADCAST, giraffe::gdl::Message::getData(), giraffe::gdl::Message::getIdentifier(), giraffe::gdl::Message::getType(), giraffe::gdl::Message::setBroadcastMessage(), and giraffe::gdl::Message::verifyType().
TEST() [2/5]
TEST (GdlMessage , ExchangeMessage)
References giraffe::gdl::Message::EXCHANGE, giraffe::gdl::Message::getData(), giraffe::gdl::Message::getIdentifier(), giraffe::gdl::Message::getType(), giraffe::gdl::Message::setExchangeMessage(), and giraffe::gdl::Message::verifyType().
TEST() [3/5]
TEST (GdlMessage , LocationMessage)
References giraffe::gdl::Message::getIdentifier(), giraffe::gdl::Message::getLocation(), giraffe::gdl::Message::getType(), giraffe::gdl::Message::Location::latitude, giraffe::gdl::Message::LOCATION, giraffe::gdl::Message::setLocationMessage(), and giraffe::gdl::Message::verifyType().
TEST() [4/5]
TEST (GdlMessage , ImageMessage)
References giraffe::gdl::Message::getIdentifier(), giraffe::gdl::Message::getImage(), giraffe::gdl::Message::getType(), giraffe::gdl::Message::IMAGE, giraffe::gdl::Message::Image::path, giraffe::gdl::Message::setImageMessage(), and giraffe::gdl::Message::verifyType().
TEST() [5/5]
TEST (GdlMessage , VerifyType)
References giraffe::gdl::Message::BROADCAST, giraffe::gdl::Message::EXCHANGE, giraffe::gdl::Message::getData(), giraffe::gdl::Message::getIdentifier(), giraffe::gdl::Message::getType(), giraffe::gdl::Message::LOCATION, giraffe::gdl::Message::setExchangeMessage(), giraffe::gdl::Message::setType(), and giraffe::gdl::Message::verifyType().