Giraffe: test_gdl_with_audio.cpp File Reference
test_gdl_with_audio.cpp File Reference
#include "gtest/gtest.h"
#include <BoosterSeat/filesystem.hpp>
#include <BoosterSeat/sleep.hpp>
#include <giraffe_data_link.hpp>
#include <software_physical_layer.hpp>
Functions
TEST (gdl_with_audio, broadcast_image)
TEST (gdl_with_audio, broadcast_text)
Function Documentation
TEST() [1/2]
TEST (gdl_with_audio , broadcast_text)
References config, giraffe::gdl::createSwPhysicalLayer(), giraffe::gdl::DataLink::enable(), giraffe::gdl::DataLink::sendMessage(), and giraffe::gdl::Message::setBroadcastMessage().
TEST() [2/2]
TEST (gdl_with_audio , broadcast_image)
References config, giraffe::gdl::createSwPhysicalLayer(), giraffe::gdl::DataLink::enable(), giraffe::gdl::Message::Image::path, giraffe::gdl::DataLink::sendMessage(), and giraffe::gdl::Message::setImageMessage().