Giraffe: test_software_version.cpp File Reference
test_software_version.cpp File Reference
#include "software_version.hpp"
#include "unit_test.hpp"
Functions
TEST (common_SoftwareVersion, getNumbersAsString)
TEST (common_SoftwareVersion, setAndGetSemanticString)
Function Documentation
TEST() [1/2]
TEST (common_SoftwareVersion , setAndGetSemanticString)
References giraffe::SoftwareVersion::ALPHA, giraffe::SoftwareVersion::BETA, giraffe::SoftwareVersion::clean, giraffe::SoftwareVersion::getNumbersAsString(), giraffe::SoftwareVersion::getSemanticVersionString(), giraffe::SoftwareVersion::major, giraffe::SoftwareVersion::minor, giraffe::SoftwareVersion::patch, giraffe::SoftwareVersion::RELEASE, giraffe::SoftwareVersion::RELEASE_CANDIDATE, giraffe::SoftwareVersion::setVersionFromString(), giraffe::SoftwareVersion::stage, and giraffe::SoftwareVersion::UNKNOWN.
TEST() [2/2]
TEST (common_SoftwareVersion , getNumbersAsString)
References giraffe::SoftwareVersion::getNumbersAsString(), giraffe::SoftwareVersion::major, giraffe::SoftwareVersion::minor, and giraffe::SoftwareVersion::patch.