Giraffe: test_adc_config.cpp File Reference
test_adc_config.cpp File Reference
Simple test of the ADC extra args config parser.
#include <array>
#include "unit_test.hpp"
#include "adc_configuration.hpp"
Functions
TEST (AdcConfig, EmptyStringFailure)
TEST (AdcConfig, InvalidTypes)
TEST (AdcConfig, ValidMinimum)
TEST (AdcConfig, ValidPercent)
TEST (AdcTest, InvalidConfigs)
TEST (AdcTest, percentageResolution)
TEST (AdcTest, VoltageDividerValid)
TEST (AdcTest, VoltageReference)
Detailed Description
Simple test of the ADC extra args config parser.
=*========GIRAFFE========*= A Unified Flight Command and Control System https://github.com/joshua-jerred/Giraffe https://giraffe.joshuajer.red/ =*=======================*=
=*=======================*=
Author
Joshua Jerred (https://joshuajer.red)
Date
2023-07-05
Copyright
2023 (license to be defined)
Function Documentation
TEST() [1/8]
TEST (AdcConfig , EmptyStringFailure)
References extension::parseAdcConfig(), extension::RAW_COUNT, and extension::AdcConfig::type.
TEST() [2/8]
TEST (AdcConfig , InvalidTypes)
References extension::parseAdcConfig(), extension::RAW_COUNT, and extension::AdcConfig::type.
TEST() [3/8]
TEST (AdcConfig , ValidMinimum)
References extension::parseAdcConfig(), extension::PERCENTAGE, extension::RAW_COUNT, and extension::AdcConfig::type.
TEST() [4/8]
TEST (AdcConfig , ValidPercent)
References extension::AdcConfig::clamp, extension::AdcConfig::max, extension::AdcConfig::min, extension::parseAdcConfig(), extension::PERCENTAGE, and extension::AdcConfig::type.
TEST() [5/8]
TEST (AdcTest , percentageResolution)
References extension::AdcConfig::max, extension::AdcConfig::min, extension::parseAdcConfig(), extension::PERCENTAGE, extension::AdcConfig::resolution, and extension::AdcConfig::type.
TEST() [6/8]
TEST (AdcTest , VoltageDividerValid)
References extension::parseAdcConfig(), extension::AdcConfig::resistor_1, extension::AdcConfig::resistor_2, extension::AdcConfig::type, extension::VOLTAGE_DIVIDER, and extension::AdcConfig::voltage_reference.
TEST() [7/8]
TEST (AdcTest , InvalidConfigs)
References extension::parseAdcConfig(), extension::RAW_COUNT, and extension::AdcConfig::type.
TEST() [8/8]
TEST (AdcTest , VoltageReference)
References extension::parseAdcConfig(), extension::AdcConfig::type, extension::VOLTAGE_REFERENCE, and extension::AdcConfig::voltage_reference.