Giraffe: test_command_processor.cpp File Reference
test_command_processor.cpp File Reference
Test of the command processor.
#include "unit_test.hpp"
#include "command.hpp"
Functions
TEST (commands_DataModule, clearAllErrors)
TEST (commands_DataModule, clearSpecificError)
TEST (commands_FlightRunner, shutdownFlightSystem)
Detailed Description
Test of the command processor.
=*========GIRAFFE========*= A Unified Flight Command and Control System https://github.com/joshua-jerred/Giraffe https://giraffe.joshuajer.red/ =*=======================*=
=*=======================*=
Author
Joshua Jerred (https://joshuajer.red)
Date
2023-11-03
Copyright
2023 (license to be defined)
Function Documentation
TEST() [1/3]
TEST (commands_DataModule , clearAllErrors)
References node::DATA_MODULE, and cmd::parseCommandString().
TEST() [2/3]
TEST (commands_DataModule , clearSpecificError)
References node::DATA_MODULE, and cmd::parseCommandString().
TEST() [3/3]
TEST (commands_FlightRunner , shutdownFlightSystem)
References node::FLIGHT_RUNNER, and cmd::parseCommandString().