Giraffe: test_application_layer.cpp File Reference
test_application_layer.cpp File Reference
#include "gtest/gtest.h"
#include <BoosterSeat/sleep.hpp>
#include <giraffe_data_link.hpp>
#include <giraffe_diagnostics.hpp>
#include <software_physical_layer.hpp>
Macros
#define GDL_APPLICATION_LAYER_SIMULATOR
Functions
TEST (ApplicationLayer, ConstructWithPhysicalLayer)
TEST (ApplicationLayer, EnableRequiresRadio)
Variables
gdl::Config config
Macro Definition Documentation
GDL_APPLICATION_LAYER_SIMULATOR
#define GDL_APPLICATION_LAYER_SIMULATOR
Function Documentation
TEST() [1/2]
TEST (ApplicationLayer , EnableRequiresRadio)
References config, giraffe::gdl::DataLink::disable(), giraffe::gdl::DataLink::enable(), giraffe::gdl::DataLink::getStatus(), giraffe::gdl::DataLink::isEnabled(), and giraffe::gdl::DataLink::setPhysicalLayer().
TEST() [2/2]
TEST (ApplicationLayer , ConstructWithPhysicalLayer)
References config, giraffe::gdl::DataLink::enable(), giraffe::gdl::DataLink::getStatus(), and giraffe::gdl::DataLink::isEnabled().
Variable Documentation
config
gdl::Config config
Referenced by giraffe::gdl::createSwPhysicalLayer(), giraffe::gdl::GdlServer::getConfigJson(), giraffe::gdl::GdlServer::loadConfig(), main(), giraffe::gdl::GdlServer::saveConfig(), giraffe::gdl::GdlServer::setConfigFromJson(), TEST(), TEST(), TEST(), TEST(), and TEST().