Giraffe: test_flight_phase_predictor.cpp File Reference
test_flight_phase_predictor.cpp File Reference
#include "flight_phase_predictor.hpp"
#include "prediction_parameters.hpp"
#include "shared_data_helpers.hpp"
#include "unit_test.hpp"
Classes
class FlightPhasePredictorTest
struct FlightPhasePredictorTest::TestContainer
Functions
TEST_F (FlightPhasePredictorTest, ascentParameters)
TEST_F (FlightPhasePredictorTest, descentParameters)
TEST_F (FlightPhasePredictorTest, enableGpsAndCalculatedData)
TEST_F (FlightPhasePredictorTest, initialState)
TEST_F (FlightPhasePredictorTest, launchParameters)
TEST_F (FlightPhasePredictorTest, recoveryParameters)
TEST_F (FlightPhasePredictorTest, setsToUnknownWhenDataQualityIsLow)
Class Documentation
FlightPhasePredictorTest::TestContainer
struct FlightPhasePredictorTest::TestContainer
Class Members
SharedData shared_data {}
FlightPhasePredictor flight_phase_predictor {shared_data}
Block< CalculatedData > & calculated_data
Block< LocationData > & location_data
Block< ImuData > & imu_data
Function Documentation
TEST_F() [1/7]
TEST_F (FlightPhasePredictorTest , initialState)
References UNKNOWN.
TEST_F() [2/7]
TEST_F (FlightPhasePredictorTest , enableGpsAndCalculatedData)
References data::FIX_3D, data::GpsFrame::gps_utc_time, data::blocks::LocationData::have_gps_source, LAUNCH, data::blocks::CalculatedData::pressure_altitude_m, and UNKNOWN.
TEST_F() [3/7]
TEST_F (FlightPhasePredictorTest , setsToUnknownWhenDataQualityIsLow)
References LAUNCH, setCalculatedDataInvalid(), setCalculatedDataValid(), setLocationDataInvalid(), setLocationDataValid(), and UNKNOWN.
TEST_F() [4/7]
TEST_F (FlightPhasePredictorTest , launchParameters)
References LAUNCH, setCalculatedDataLaunch(), and setLocationDataLaunch().
TEST_F() [5/7]
TEST_F (FlightPhasePredictorTest , ascentParameters)
References ASCENT, setCalculatedDataAscent(), and setLocationDataAscent().
TEST_F() [6/7]
TEST_F (FlightPhasePredictorTest , descentParameters)
References DESCENT, setCalculatedDataDescent(), and setLocationDataDescent().
TEST_F() [7/7]
TEST_F (FlightPhasePredictorTest , recoveryParameters)
References RECOVERY, setCalculatedDataRecovery(), and setLocationDataRecovery().