Giraffe: test_message_queue.cpp File Reference
test_message_queue.cpp File Reference
#include "gtest/gtest.h"
#include "gdl_constants.hpp"
#include "gdl_message.hpp"
Functions
TEST (GdlMessageQueueTest, Pop)
TEST (GdlMessageQueueTest, PopEmpty)
TEST (GdlMessageQueueTest, Push)
TEST (GdlMessageQueueTest, PushFull)
Function Documentation
TEST() [1/4]
TEST (GdlMessageQueueTest , Push)
References giraffe::gdl::Message::setBroadcastMessage().
TEST() [2/4]
TEST (GdlMessageQueueTest , PushFull)
References giraffe::gdl::GDL_MESSAGE_QUEUES_SIZE, and giraffe::gdl::Message::setBroadcastMessage().
TEST() [3/4]
TEST (GdlMessageQueueTest , Pop)
References giraffe::gdl::GDL_MESSAGE_QUEUES_SIZE, giraffe::gdl::Message::getData(), giraffe::gdl::Message::getIdentifier(), and giraffe::gdl::Message::setBroadcastMessage().
TEST() [4/4]
TEST (GdlMessageQueueTest , PopEmpty)