Giraffe: test_positional.cpp File Reference
test_positional.cpp File Reference
Test of imu and gps data handling.
#include <BoosterSeat/clock.hpp>
#include <chrono>
#include "positional.hpp"
#include "unit_test.hpp"
Functions
TEST (isGpsFrameValidTest, altitudeValidity)
Verify validity of altitude (meters), must be within [-450, 40000].
TEST (isGpsFrameValidTest, emptyFrameInvalid)
Verify that an empty frame is invalid.
TEST (isGpsFrameValidTest, fixValidity)
A non-2d or non-3d fix should be invalid. A 2d fix is currently considered valid.
TEST (isGpsFrameValidTest, headingOfMotionValidity)
Verify validity of heading of motion (0-360 degrees)
TEST (isGpsFrameValidTest, horzAccuracyValidity)
Verify validity of horizontal accuracy (meters), must be within [0, 1000].
TEST (isGpsFrameValidTest, invalidTime)
Test to make sure that time is checked. Clock skew is ok, but it should not be too far off (1 day limit for now?)
TEST (isGpsFrameValidTest, latitudeValidity)
Verify validity of latitude.
TEST (isGpsFrameValidTest, longitudeValidity)
Verify validity of longitude.
TEST (isGpsFrameValidTest, numSatsValidity)
Verify that a fix and number of satellites are checked.
TEST (isGpsFrameValidTest, validFrame)
A frame with all zeros, and a good fix should be valid.
TEST (isImuFrameValid, accelerationValidity)
Verify validity of acceleration (m/s^2)
TEST (isImuFrameValid, angularVelocityValidity)
Verify validity of angular velocity (rad/s)
TEST (isImuFrameValid, emptyIsInvalid)
Verify validity of heading of motion (0-360 degrees)
TEST (isImuFrameValid, timeValidity)
Time delta out of range.
TEST (isImuFrameValid, validSetIsValid)
All zeros is valid, if is_valid is set to true.
Detailed Description
Test of imu and gps data handling.
=*========GIRAFFE========*= A Unified Flight Command and Control System https://github.com/joshua-jerred/Giraffe https://giraffe.joshuajer.red/ =*=======================*=
=*=======================*=
Author
Joshua Jerred (https://joshuajer.red)
Date
2023-06-29
Copyright
2023 (license to be defined)
Function Documentation
TEST() [1/15]
TEST (isGpsFrameValidTest , emptyFrameInvalid)
Verify that an empty frame is invalid.
References data::isGpsFrameValid().
TEST() [2/15]
TEST (isGpsFrameValidTest , validFrame)
A frame with all zeros, and a good fix should be valid.
References data::FIX_3D, and data::isGpsFrameValid().
TEST() [3/15]
TEST (isGpsFrameValidTest , invalidTime)
Test to make sure that time is checked. Clock skew is ok, but it should not be too far off (1 day limit for now?)
References data::FIX_3D, and data::isGpsFrameValid().
TEST() [4/15]
TEST (isGpsFrameValidTest , fixValidity)
A non-2d or non-3d fix should be invalid. A 2d fix is currently considered valid.
References data::ERROR, data::FIX_2D, data::FIX_3D, data::isGpsFrameValid(), and data::NO_FIX.
TEST() [5/15]
TEST (isGpsFrameValidTest , numSatsValidity)
Verify that a fix and number of satellites are checked.
References data::ERROR, data::FIX_2D, data::FIX_3D, and data::isGpsFrameValid().
TEST() [6/15]
TEST (isGpsFrameValidTest , latitudeValidity)
Verify validity of latitude.
References data::FIX_3D, and data::isGpsFrameValid().
TEST() [7/15]
TEST (isGpsFrameValidTest , longitudeValidity)
Verify validity of longitude.
References data::FIX_3D, and data::isGpsFrameValid().
TEST() [8/15]
TEST (isGpsFrameValidTest , horzAccuracyValidity)
Verify validity of horizontal accuracy (meters), must be within [0, 1000].
References data::FIX_3D, and data::isGpsFrameValid().
TEST() [9/15]
TEST (isGpsFrameValidTest , altitudeValidity)
Verify validity of altitude (meters), must be within [-450, 40000].
References data::FIX_3D, and data::isGpsFrameValid().
TEST() [10/15]
TEST (isGpsFrameValidTest , headingOfMotionValidity)
Verify validity of heading of motion (0-360 degrees)
References data::FIX_3D, and data::isGpsFrameValid().
TEST() [11/15]
TEST (isImuFrameValid , emptyIsInvalid)
Verify validity of heading of motion (0-360 degrees)
Warning
Not verifying validity of speeds, speed accuracy, or heading accuracy.
References data::isImuFrameValid().
TEST() [12/15]
TEST (isImuFrameValid , validSetIsValid)
All zeros is valid, if is_valid is set to true.
References data::ImuFrame::is_valid, and data::isImuFrameValid().
TEST() [13/15]
TEST (isImuFrameValid , timeValidity)
Time delta out of range.
References data::ImuFrame::is_valid, and data::isImuFrameValid().
TEST() [14/15]
TEST (isImuFrameValid , accelerationValidity)
Verify validity of acceleration (m/s^2)
References data::ImuFrame::is_valid, and data::isImuFrameValid().
TEST() [15/15]
TEST (isImuFrameValid , angularVelocityValidity)
Verify validity of angular velocity (rad/s)
References data::ImuFrame::is_valid, and data::isImuFrameValid().