Giraffe: ubx_protocol.cpp File Reference
ubx_protocol.cpp File Reference
The UBX Protocol implementation.
#include <BoosterSeat/timer.hpp>
#include <chrono>
#include <cstring>
#include <iostream>
#include <thread>
#include <unistd.h>
#include <unordered_map>
#include "ubx_ids.hpp"
#include "ubx_protocol.hpp"
Namespaces
ubx
Macros
#define UBX_ACK_NACK 0x00
Functions
ACK ubx::checkForAck (I2cInterface &i2c, const uint8_t msg_class, const uint8_t msg_id)
bool ubx::flushStream (I2cInterface &i2c)
int ubx::getStreamSize (I2cInterface &i2c)
std::ostream & ubx::operator<< (std::ostream &o, const NavData &nv)
std::ostream & ubx::operator<< (std::ostream &o, const UBXMessage &ubx)
int16_t parseI2 (const uint8_t msb, const uint8_t lsb)
int32_t parseI4 (const uint8_t msb, const uint8_t mid_msb, const uint8_t mid_lsb, const uint8_t lsb)
bool ubx::parsePVT (const UBXMessage &message, NavData &data)
uint16_t parseU2 (uint8_t msb, uint8_t lsb)
uint32_t parseU4 (const uint8_t msb, const uint8_t mid_msb, const uint8_t mid_lsb, const uint8_t lsb)
bool ubx::pollMessage (I2cInterface &i2c, UBXMessage &message, const uint8_t msg_class, const uint8_t msg_id, const int expected_size, const unsigned int timeout_ms)
Poll a message and read it from the GPS.
bool ubx::readNextUBX (I2cInterface &i2c, UBXMessage &message)
bool ubx::readSpecificMessage (I2cInterface &i2c, UBXMessage &message)
bool ubx::sendResetCommand (I2cInterface &i2c)
Send a UBX-CFG-RST command to the receiver (Hardware Reset)
ACK ubx::setDynamicModel (I2cInterface &i2c, const DYNAMIC_MODEL model)
ACK ubx::setMeasurementRate (I2cInterface &i2c, const uint16_t rate_ms)
ACK ubx::setMessageRate (I2cInterface &i2c, uint8_t msg_class, uint8_t msg_id, uint8_t rate)
CFG-MSG (0x06 0x01) Configure Message Rate.
ACK ubx::setProtocolDDC (I2cInterface &i2c, const bool extended_timeout)
Configure the I2C port to use UBX protocol for input and output.
void wait (int ms)
bool ubx::writeUBX (I2cInterface &i2c, UBXMessage &message)
Variables
constexpr uint32_t kMaxMessageRetryAttempts
constexpr uint32_t kMaxPayloadSize = 256
The maximum size of a UBX message payload in bytes.
constexpr uint32_t kMessageRetryDelayTime = 200
constexpr uint32_t kReadNextMessageTimeout = 500
constexpr uint8_t kStreamRegister = 0xFF
constexpr uint8_t kSyncChar1 = 0xB5
constexpr uint8_t kSyncChar2 = 0x62
Detailed Description
The UBX Protocol implementation.
=*========GIRAFFE========*= A Unified Flight Command and Control System https://github.com/joshua-jerred/Giraffe https://giraffe.joshuajer.red/ =*=======================*=
=*=======================*=
Author
Joshua Jerred (https://joshuajer.red)
Date
2023-10-13
Copyright
2023 (license to be defined)
Macro Definition Documentation
UBX_ACK_NACK
#define UBX_ACK_NACK 0x00
Function Documentation
wait()
void wait (int ms) inline
Referenced by ubx::pollMessage().
parseU2()
uint16_t parseU2 (uint8_t msb, uint8_t lsb) inline
Referenced by ubx::parsePVT().
parseU4()
uint32_t parseU4 (const uint8_t msb, const uint8_t mid_msb, const uint8_t mid_lsb, const uint8_t lsb) inline
Referenced by ubx::parsePVT().
parseI2()
int16_t parseI2 (const uint8_t msb, const uint8_t lsb) inline
parseI4()
int32_t parseI4 (const uint8_t msb, const uint8_t mid_msb, const uint8_t mid_lsb, const uint8_t lsb) inline
Referenced by ubx::parsePVT().
Variable Documentation
kStreamRegister
constexpr uint8_t kStreamRegister = 0xFF inline constexpr
Referenced by ubx::flushStream(), ubx::pollMessage(), and ubx::readNextUBX().
kSyncChar1
constexpr uint8_t kSyncChar1 = 0xB5 inline constexpr
Referenced by ubx::readNextUBX().
kSyncChar2
constexpr uint8_t kSyncChar2 = 0x62 inline constexpr
Referenced by ubx::readNextUBX().
kMessageRetryDelayTime
constexpr uint32_t kMessageRetryDelayTime = 200 inline constexpr
Referenced by ubx::checkForAck().
kMaxMessageRetryAttempts
constexpr uint32_t kMaxMessageRetryAttempts inline constexpr
Initial value:
=
    5
Referenced by ubx::checkForAck().
kMaxPayloadSize
constexpr uint32_t kMaxPayloadSize = 256 inline constexpr
The maximum size of a UBX message payload in bytes.
Referenced by ubx::readNextUBX().
kReadNextMessageTimeout
constexpr uint32_t kReadNextMessageTimeout = 500 inline constexpr