/// =*========GIRAFFE========*=
/// A Unified Flight Command and Control System
/// https://github.com/joshua-jerred/Giraffe
/// https://giraffe.joshuajer.red/
/// =*=======================*=
///
/// @file   test_cases_fcs.hpp
///
/// =*=======================*=
/// @author     Joshua Jerred (https://joshuajer.red)
/// @date       2024-12-03
/// @copyright  2024 (license to be defined)

#pragma once

#include "bit_types.hpp"
#include "shared_data.hpp"

namespace bit {

/// @brief This structure contains the data generated by each test case.
struct TestResult {
  TestId test_id;
  TestGroupId group_id;
  TestStatus status;
  std::string failure_reason;
};

namespace test_case {

/// @brief Checks if the error frame has any active errors.
/// @param shared_data - The shared data object.
/// @return TestResult - The result of the test.
TestResult runTestFCS_0001(data::SharedData &shared_data);

static inline TestResult runTestFCS_0002(data::SharedData &shared_data) {
  TestResult result{.test_id = TestId::FCS_FlightPhasePredictorTest,
                    .group_id = TestGroupId::FCS,
                    .status = TestStatus::SKIPPED,
                    .failure_reason = ""};
  (void)shared_data;
  /// @todo Make sure the flight phase predictor is working correctly

  return result;
};

/// @brief Checks if the launch position is set correctly.
/// @param shared_data - The shared data object.
/// @return TestResult - The result of the test.
static inline TestResult runTestFCS_0003(data::SharedData &shared_data) {
  TestResult result{.test_id = TestId::FCS_LaunchPositionTest,
                    .group_id = TestGroupId::FCS,
                    .status = TestStatus::SKIPPED,
                    .failure_reason = ""};
  double latitude = 0.0;
  double longitude = 0.0;
  double altitude = 0.0;

  if (!shared_data.flight_data.getLaunchPosition(latitude, longitude,
                                                 altitude)) {
    result.status = TestStatus::FAILED;
    result.failure_reason = "Launch position is not set.";
    return result;
  }

  result.status = TestStatus::PASSED;

  return result;
};

/// @brief Checks if the data module is processing data correctly/at a
/// reasonable rate.
/// @param shared_data - The shared data object.
/// @return TestResult - The result of the test.
TestResult runTestFCS_0004(data::SharedData &shared_data);

static inline TestResult runTestSYS_0100(data::SharedData &shared_data) {
  TestResult result{.test_id = TestId::SYS_DriveSpaceTest,
                    .group_id = TestGroupId::SYS,
                    .status = TestStatus::SKIPPED,
                    .failure_reason = ""};
  // @todo Implement the drive space test
  (void)shared_data;

  return result;
};

/// @brief Checks if the location data is configured correctly.
/// @param shared_data - The shared data object.
/// @return TestResult - The result of the test.
static inline TestResult runTestDLNK_0200(data::SharedData &shared_data) {
  TestResult result{.test_id = TestId::DLNK_ConfigLocationDataTest,
                    .group_id = TestGroupId::DLNK,
                    .status = TestStatus::SKIPPED,
                    .failure_reason = ""};
  // @todo Implement the location data test
  (void)shared_data;

  return result;
};

/// @brief Checks if GPS hardware is configured and running.
/// @param shared_data - The shared data object.
/// @return TestResult - The result of the test.
TestResult runTestGPS_0400(data::SharedData &shared_data);

static inline TestResult runTestBATT_0500(data::SharedData &shared_data) {
  TestResult result{.test_id = TestId::BATT_AdcTest,
                    .group_id = TestGroupId::BATT,
                    .status = TestStatus::SKIPPED,
                    .failure_reason = ""};
  // @todo Implement the ADC test for the battery
  (void)shared_data;

  return result;
};

static inline TestResult runTestEXTN_0600(data::SharedData &shared_data) {
  TestResult result{.test_id = TestId::EXTN_ExtensionsRunningTest,
                    .group_id = TestGroupId::EXTN,
                    .status = TestStatus::SKIPPED,
                    .failure_reason = ""};
  // @todo Implement the extensions running test
  (void)shared_data;

  return result;
};

static inline TestResult runTestENV_0700(data::SharedData &shared_data) {
  TestResult result{.test_id = TestId::ENV_TemperatureTest,
                    .group_id = TestGroupId::ENV,
                    .status = TestStatus::SKIPPED,
                    .failure_reason = ""};
  // @todo Implement the temperature test
  (void)shared_data;

  return result;
};

static inline TestResult runTestCAM_0800(data::SharedData &shared_data) {
  TestResult result{.test_id = TestId::CAM_InstalledTest,
                    .group_id = TestGroupId::CAM,
                    .status = TestStatus::SKIPPED,
                    .failure_reason = ""};
  // @todo Implement the camera installed test
  (void)shared_data;

  return result;
};

static inline TestResult runTestIMU_0900(data::SharedData &shared_data) {
  TestResult result{.test_id = TestId::IMU_InstalledTest,
                    .group_id = TestGroupId::IMU,
                    .status = TestStatus::SKIPPED,
                    .failure_reason = ""};
  // @todo Implement the IMU installed test
  (void)shared_data;

  return result;
};

static inline TestResult runTestADC_0A00(data::SharedData &shared_data) {
  TestResult result{.test_id = TestId::ADC_InstalledTest,
                    .group_id = TestGroupId::ADC,
                    .status = TestStatus::SKIPPED,
                    .failure_reason = ""};
  // @todo Implement the ADC installed test
  (void)shared_data;

  return result;
};

} // namespace test_case

} // namespace bit