Giraffe: TestExtension Class Reference
TestExtension Class Reference
#include <test-ext.h>
Public Member Functions
TestExtension (DataStream *pDS, ExtensionMetadata config_data)
~TestExtension ()
int getCritical ()
int getID ()
ExtensionMetadata::Interface getInterface ()
std::string getName ()
ExtensionStatus getStatus ()
std::string getType ()
void restart ()
int runner ()
void spawnRunner ()
void start ()
void stop ()
Protected Member Functions
void setStatus (ExtensionStatus status)
Protected Attributes
std::atomic< int > flag_
DataStream * mDataStream
std::thread runner_thread_
Private Member Functions
void setCategory (ExtensionMetadata::Category category)
void setCritical (int critical)
void setID (int num)
void setInterface (ExtensionMetadata::Interface interface)
void setName (std::string name)
void setType (std::string type)
void setUpdateInterval (int interval)
Private Attributes
int critical_
int id_
ExtensionMetadata::Interface interface_
std::string name_
ExtensionStatus status_
std::string type_
Constructor & Destructor Documentation
TestExtension()
TestExtension::TestExtension (DataStream * pDS, ExtensionMetadata config_data)
~TestExtension()
TestExtension::~TestExtension ()
Member Function Documentation
runner()
int TestExtension::runner () virtual
Reimplemented from Extension.
References DataStream::addData(), and Extension::mDataStream.
Referenced by spawnRunner().
spawnRunner()
void TestExtension::spawnRunner () virtual
Reimplemented from Extension.
References runner(), and Extension::runner_thread_.
start()
void Extension::start () inherited
References Extension::getStatus(), kStarting, kStopped, Extension::setStatus(), and Extension::spawnRunner().
stop()
void Extension::stop () inherited
restart()
void Extension::restart () inherited
getID()
int Extension::getID () inherited
References Extension::id_.
getName()
std::string Extension::getName () inherited
References Extension::name_.
getType()
std::string Extension::getType () inherited
References Extension::type_.
getInterface()
ExtensionMetadata::Interface Extension::getInterface () inherited
References Extension::interface_.
getCritical()
int Extension::getCritical () inherited
References Extension::critical_.
getStatus()
ExtensionStatus Extension::getStatus () inherited
References Extension::status_.
Referenced by Extension::start().
setStatus()
void Extension::setStatus (ExtensionStatus status) protected inherited
References Extension::status_.
Referenced by Extension::Extension(), Extension::setID(), Extension::setName(), and Extension::start().
setID()
void Extension::setID (int num) private inherited
References DataStream::addError(), Extension::id_, kError, Extension::mDataStream, Extension::name_, and Extension::setStatus().
Referenced by Extension::Extension().
setName()
void Extension::setName (std::string name) private inherited
References DataStream::addError(), kError, Extension::mDataStream, Extension::name_, and Extension::setStatus().
Referenced by Extension::Extension().
setType()
void Extension::setType (std::string type) private inherited
References Extension::type_.
Referenced by Extension::Extension().
setCategory()
void Extension::setCategory (ExtensionMetadata::Category category) private inherited
setInterface()
void Extension::setInterface (ExtensionMetadata::Interface interface) private inherited
References Extension::interface_.
Referenced by Extension::Extension().
setUpdateInterval()
void Extension::setUpdateInterval (int interval) private inherited
setCritical()
void Extension::setCritical (int critical) private inherited
References Extension::critical_.
Referenced by Extension::Extension().
Member Data Documentation
runner_thread_
std::thread Extension::runner_thread_ protected inherited
Referenced by spawnRunner().
flag_
std::atomic<int> Extension::flag_ protected inherited
Referenced by Extension::Extension().
mDataStream
DataStream* Extension::mDataStream protected inherited
Referenced by Extension::Extension(), runner(), Extension::setID(), and Extension::setName().
id_
int Extension::id_ private inherited
Referenced by Extension::getID(), and Extension::setID().
name_
std::string Extension::name_ private inherited
Referenced by Extension::getName(), Extension::setID(), Extension::setName(), and Extension::spawnRunner().
type_
std::string Extension::type_ private inherited
Referenced by Extension::getType(), and Extension::setType().
interface_
ExtensionMetadata::Interface Extension::interface_ private inherited
Referenced by Extension::getInterface(), and Extension::setInterface().
critical_
int Extension::critical_ private inherited
Referenced by Extension::getCritical(), and Extension::setCritical().
status_
ExtensionStatus Extension::status_ private inherited
Referenced by Extension::getStatus(), and Extension::setStatus().