Giraffe: Extension Class Reference
Extension Class Reference
#include <extension.h>
Public Member Functions
Extension (DataStream *pDS, ExtensionMetadata configData)
virtual ~Extension ()
int getCritical ()
int getID ()
ExtensionMetadata::Interface getInterface ()
std::string getName ()
ExtensionStatus getStatus ()
std::string getType ()
void restart ()
void start ()
void stop ()
Protected Member Functions
virtual int runner ()
void setStatus (ExtensionStatus status)
virtual void spawnRunner ()
Protected Attributes
std::atomic< int > flag_
DataStream * mDataStream
std::thread runner_thread_
Private Member Functions
void setCategory (ExtensionMetadata::Category category)
void setCritical (int critical)
void setID (int num)
void setInterface (ExtensionMetadata::Interface interface)
void setName (std::string name)
void setType (std::string type)
void setUpdateInterval (int interval)
Private Attributes
int critical_
int id_
ExtensionMetadata::Interface interface_
std::string name_
ExtensionStatus status_
std::string type_
Constructor & Destructor Documentation
Extension()
Extension::Extension (DataStream * pDS, ExtensionMetadata configData)
References ExtensionMetadata::critical, ExtensionMetadata::extension_type, flag_, ExtensionMetadata::id, ExtensionMetadata::interface, kStopped, mDataStream, ExtensionMetadata::name, setCritical(), setID(), setInterface(), setName(), setStatus(), and setType().
~Extension()
Extension::~Extension () virtual
Member Function Documentation
start()
void Extension::start ()
References getStatus(), kStarting, kStopped, setStatus(), and spawnRunner().
stop()
void Extension::stop ()
restart()
void Extension::restart ()
getID()
int Extension::getID ()
References id_.
getName()
std::string Extension::getName ()
References name_.
getType()
std::string Extension::getType ()
References type_.
getInterface()
ExtensionMetadata::Interface Extension::getInterface ()
References interface_.
getCritical()
int Extension::getCritical ()
References critical_.
getStatus()
ExtensionStatus Extension::getStatus ()
References status_.
Referenced by start().
runner()
int Extension::runner () protected virtual
Reimplemented in TestExtension.
spawnRunner()
void Extension::spawnRunner () protected virtual
Reimplemented in TestExtension.
References name_.
Referenced by start().
setStatus()
void Extension::setStatus (ExtensionStatus status) protected
References status_.
Referenced by Extension(), setID(), setName(), and start().
setID()
void Extension::setID (int num) private
References DataStream::addError(), id_, kError, mDataStream, name_, and setStatus().
Referenced by Extension().
setName()
void Extension::setName (std::string name) private
References DataStream::addError(), kError, mDataStream, name_, and setStatus().
Referenced by Extension().
setType()
void Extension::setType (std::string type) private
References type_.
Referenced by Extension().
setCategory()
void Extension::setCategory (ExtensionMetadata::Category category) private
setInterface()
void Extension::setInterface (ExtensionMetadata::Interface interface) private
References interface_.
Referenced by Extension().
setUpdateInterval()
void Extension::setUpdateInterval (int interval) private
setCritical()
void Extension::setCritical (int critical) private
References critical_.
Referenced by Extension().
Member Data Documentation
runner_thread_
std::thread Extension::runner_thread_ protected
Referenced by TestExtension::spawnRunner().
flag_
std::atomic<int> Extension::flag_ protected
Referenced by Extension().
mDataStream
DataStream* Extension::mDataStream protected
Referenced by Extension(), TestExtension::runner(), setID(), and setName().
id_
int Extension::id_ private
Referenced by getID(), and setID().
name_
std::string Extension::name_ private
Referenced by getName(), setID(), setName(), and spawnRunner().
type_
std::string Extension::type_ private
Referenced by getType(), and setType().
interface_
ExtensionMetadata::Interface Extension::interface_ private
Referenced by getInterface(), and setInterface().
critical_
int Extension::critical_ private
Referenced by getCritical(), and setCritical().
status_
ExtensionStatus Extension::status_ private
Referenced by getStatus(), and setStatus().