Giraffe: Flight-computer-modules
Flight-computer-modules
The DataService class is responsible for sensor data flow. It collects all of the data into "frames". A frame is a snapshot of the most recent data that has been pulled from the sensors. The DataService is also responsible for the data log and error log files.
Classes
class DataModule
Detailed Description
The DataService class is responsible for sensor data flow. It collects all of the data into "frames". A frame is a snapshot of the most recent data that has been pulled from the sensors. The DataService is also responsible for the data log and error log files.
Class Documentation
DataModule
class DataModule
Public Member Functions
DataModule (ConfigData config_data)
Construct a new Data Service object. Initializes the DataStream.
~DataModule ()
Stops the DataService and deconstruct the DataService object. Attempts safe shutdown of all services.
data_snapshot getDataSnapshot ()
Get a Data Snapshot.
DataStream * getDataStream ()
Get a pointer to the DataStream object.
void log ()
This function will log the data snapshot to the data log file.
virtual void start ()
virtual ModuleStatus status ()
virtual void stop ()
Protected Attributes
ModuleStatus module_status_
Private Member Functions
void parseDataStream ()
This function will get the current number of data packets before reading them all from the dataStream. This means that if another thread manages to add a packet to the dataStream while it's being parsed, it will not be read until the next time this function is called.
void parseErrorStream ()
Private Attributes
data_snapshot mDataSnapshot
DataStream * mpDataStream
Constructor & Destructor Documentation
DataModule()
DataModule::DataModule (ConfigData config_data)
Construct a new Data Service object. Initializes the DataStream.
References ConfigData::data_types, mDataSnapshot, mpDataStream, ConfigData::DataTypes::ExtensionDataType::name, and ConfigData::DataTypes::types.
~DataModule()
DataModule::~DataModule ()
Stops the DataService and deconstruct the DataService object. Attempts safe shutdown of all services.
References mpDataStream.
Member Function Documentation
getDataStream()
DataStream * DataModule::getDataStream ()
Get a pointer to the DataStream object.
Returns
DataStream*
References mpDataStream.
Referenced by FlightRunner::start().
getDataSnapshot()
data_snapshot DataModule::getDataSnapshot ()
Get a Data Snapshot.
References mDataSnapshot.
log()
void DataModule::log ()
This function will log the data snapshot to the data log file.
Todo:
Implement this function.
References parseDataStream().
Referenced by FlightRunner::flightLoop().
parseDataStream()
void DataModule::parseDataStream () private
This function will get the current number of data packets before reading them all from the dataStream. This means that if another thread manages to add a packet to the dataStream while it's being parsed, it will not be read until the next time this function is called.
References data_stream_packet::data_name, data_stream_packet::data_source, data_stream_packet::data_value, DataStream::getNextDataPacket(), DataStream::getNumDataPackets(), and mpDataStream.
Referenced by log().
parseErrorStream()
void DataModule::parseErrorStream () private
References error_stream_packet::error_info, error_stream_packet::error_name, error_stream_packet::error_source, DataStream::getNextErrorPacket(), DataStream::getNumErrorPackets(), and mpDataStream.
status()
virtual ModuleStatus Module::status () inline virtual inherited
References Module::module_status_.
start()
virtual void Module::start () inline virtual inherited
Reimplemented in ExtensionsModule, and ConsoleModule.
References Module::module_status_.
stop()
virtual void Module::stop () inline virtual inherited
Reimplemented in ExtensionsModule, and ConsoleModule.
References Module::module_status_.
Member Data Documentation
mpDataStream
DataStream* DataModule::mpDataStream private
Referenced by DataModule(), ~DataModule(), getDataStream(), parseDataStream(), and parseErrorStream().
mDataSnapshot
data_snapshot DataModule::mDataSnapshot private
Referenced by DataModule(), and getDataSnapshot().
module_status_
ModuleStatus Module::module_status_ protected inherited
Referenced by Module::start(), Module::status(), and Module::stop().