Giraffe: Parse_config
Parse_config
The following are the functions used to parse out the data from each section of the configuration file. Each function will.
Functions
void ConfigModule::parseDataTypes ()
Prases Data Types.
void ConfigModule::parseExtensions ()
Prases Extensions.
void ConfigModule::parseFlightLoops ()
Flight Loops.
void ConfigModule::parseGeneral ()
Prases General.
void ConfigModule::parseServer ()
Prases Server.
void ConfigModule::parseTelemetry ()
Prases Telemetry.
Detailed Description
The following are the functions used to parse out the data from each section of the configuration file. Each function will.
Function Documentation
parseGeneral()
void ConfigModule::parseGeneral () private
Prases General.
References ConfigModule::config_data_, ConfigModule::errors_, ConfigData::general, ConfigModule::json_buffer_, ConfigData::General::main_board, ConfigData::General::project_name, PROJECT_NAME_MAX_LENGTH, PROJECT_NAME_MIN_LENGTH, and ConfigData::General::starting_loop.
Referenced by ConfigModule::parseAll().
parseExtensions()
void ConfigModule::parseExtensions () private
Prases Extensions.
References ExtensionMetadata::address, ExtensionMetadata::category, ConfigModule::config_data_, ExtensionMetadata::critical, ConfigModule::errors_, EXTENSION_INTERVAL_MAX, EXTENSION_INTERVAL_MIN, EXTENSION_NAME_MAX_LENGTH, EXTENSION_NAME_MIN_LENGTH, ExtensionMetadata::extension_type, ConfigData::extensions, ConfigData::Extensions::extensions_list, ExtensionMetadata::id, ExtensionMetadata::interface, ConfigModule::json_buffer_, ExtensionMetadata::kError, ExtensionMetadata::kI2C, ExtensionMetadata::kOneWire, ExtensionMetadata::kRadio, ExtensionMetadata::name, and ExtensionMetadata::update_interval.
Referenced by ConfigModule::parseAll().
parseServer()
void ConfigModule::parseServer () private
Prases Server.
References ConfigModule::config_data_, ConfigModule::json_buffer_, ConfigData::server, and ConfigData::Server::web_server_enabled.
Referenced by ConfigModule::parseAll().
parseTelemetry()
void ConfigModule::parseTelemetry () private
Prases Telemetry.
Todo:
Needs to be completed.
References ConfigData::Telemetry::callsign, ConfigModule::config_data_, ConfigModule::errors_, ConfigModule::json_buffer_, ConfigData::telemetry, and ConfigData::Telemetry::telemetry_enabled.
Referenced by ConfigModule::parseAll().
parseDataTypes()
void ConfigModule::parseDataTypes () private
Prases Data Types.
References ConfigModule::config_data_, ConfigData::data_types, ConfigModule::errors_, ConfigModule::json_buffer_, ConfigData::DataTypes::ExtensionDataType::name, ConfigData::DataTypes::types, and ConfigData::DataTypes::ExtensionDataType::unit.
Referenced by ConfigModule::parseAll().
parseFlightLoops()
void ConfigModule::parseFlightLoops () private
Flight Loops.
References ConfigModule::config_data_, FlightLoop::Intervals::data_log, ConfigData::flight_loops, FlightLoop::intervals, ConfigModule::json_buffer_, FlightLoop::Intervals::server_update, ConfigData::Loops::testing, and FlightLoop::type.
Referenced by ConfigModule::parseAll().