@startuml
!include data-stream.puml
title Data Module

node DataModuleThread {
    object DataFrame
    object ErrorFrame

    getNextDataPacket --> DataFrame
    getNextErrorPacket --> ErrorFrame

    struct ModuleStatus {

    }

    struct ExtensionStatus {

    }

    struct CriticalData {
        + timestamp
        + battery_voltage
        + cpu_load_average_1_and_5
        + mem_usage
        + cpu_usage
        + confidence
        + lat
        + lon
        + heading
        + alt
        + h_speed
        + v_speed
    }


}

@enduml