@startuml

title Extension Module Actions

' This diagram shows how the extension
' module will handle extension 'actions'

state unknown
unknown: The default initial state of each extension

state start
start: Attempting to start the extension

state run
run: Keep the extension running

state stop
stop: Attempting to stop the extension

state restart
restart: Attempting to restart the extension

state error_restart
error_restart: Attempting to restart the extension

state error_disable
error_disable: Attempting to disable the extension

state disable
disable: Disable the extension (non error)

[*] --> unknown
unknown --> start : metadata.enabled = true
unknown --> disable : metadata.enabled = false

disable --> start : command requested

start --> run : extension started
start --> error_disable : reached max restarts

run --> stop : on shutdown
run --> stop : command requested
run --> disable : command 
run --> error_restart : restart on extension error
run --> restart : command requested (config change)

restart --> start : extension shutdown

error_restart --> run : extension restarted successfully
error_restart --> error_disable : reached max restarts

error_disable --> disable : command requested

@enduml