Giraffe: WavGen Class Reference
WavGen Class Reference
#include <wavgen.h>
Public Member Functions
WavGen (std::string filename)
~WavGen ()
void addSample (double sample)
void addSineWave (int freq, float amp, float duration)
bool done ()
Private Member Functions
void writeBytes (int data, int size)
Private Attributes
const int bits_per_sample_ = 16
int data_end_ = 0
int data_start_ = 0
bool file_open_ = false
const int max_amplitude_ = pow(2, bits_per_sample_ - 1) - 1
const int sample_rate_ = 44100
std::ofstream wav_file_ = std::ofstream()
float wave_angle_ = 0.0f
Constructor & Destructor Documentation
WavGen()
WavGen::WavGen (std::string filename)
References bits_per_sample_, data_start_, file_open_, sample_rate_, wav_file_, and writeBytes().
~WavGen()
WavGen::~WavGen ()
References done().
Member Function Documentation
addSineWave()
void WavGen::addSineWave (int freq, float amp, float duration)
References M_PI, max_amplitude_, sample_rate_, SINE_FILTER_SAMPLES, wave_angle_, and writeBytes().
Referenced by MWAVData::encode(), and modulators::Morse().
addSample()
void WavGen::addSample (double sample)
References max_amplitude_, and writeBytes().
Referenced by addSymbol(), and AFSK::encodeBitStream().
done()
bool WavGen::done ()
References data_end_, data_start_, file_open_, wav_file_, and writeBytes().
Referenced by ~WavGen().
writeBytes()
void WavGen::writeBytes (int data, int size) private
References file_open_, and wav_file_.
Referenced by WavGen(), addSample(), addSineWave(), and done().
Member Data Documentation
file_open_
bool WavGen::file_open_ = false private
Referenced by WavGen(), done(), and writeBytes().
sample_rate_
const int WavGen::sample_rate_ = 44100 private
Referenced by WavGen(), and addSineWave().
bits_per_sample_
const int WavGen::bits_per_sample_ = 16 private
Referenced by WavGen().
max_amplitude_
const int WavGen::max_amplitude_ = pow(2, bits_per_sample_ - 1) - 1 private
Referenced by addSample(), and addSineWave().
wave_angle_
float WavGen::wave_angle_ = 0.0f private
Referenced by addSineWave().
data_start_
int WavGen::data_start_ = 0 private
Referenced by WavGen(), and done().
data_end_
int WavGen::data_end_ = 0 private
Referenced by done().
wav_file_
std::ofstream WavGen::wav_file_ = std::ofstream() private
Referenced by WavGen(), done(), and writeBytes().