Giraffe: AFSK Class Reference
AFSK Class Reference
#include <afsk.h>
Public Types
enum class MODE { AX25 = 0 , MINIMODEM = 1 }
Public Member Functions
AFSK (WavGen &wavgen)
~AFSK ()
bool encodeAscii (const std::string &message)
bool encodeRawData (unsigned char *data, int length)
Private Member Functions
void addSymbol (bool change)
void encodeBitStream ()
void NRZI ()
Private Attributes
double amplitude_ = 1
const int baud_rate_ = 1200
BitStream bit_stream_ = BitStream()
const int bits_per_sample_ = 16
const int freq_center_ = 1700
const int freq_dev_ = 500
bool last_bit_ = false
const int max_amplitude_ = pow(2, bits_per_sample_ - 1) - 1
MODE mode_ = MODE::MINIMODEM
const int sample_rate_ = 44100
WavGen & wavgen_
Member Enumeration Documentation
MODE
enum AFSK::MODE strong
Enumerator
AX25
MINIMODEM
Constructor & Destructor Documentation
AFSK()
AFSK::AFSK (WavGen & wavgen)
~AFSK()
AFSK::~AFSK ()
Member Function Documentation
encodeRawData()
bool AFSK::encodeRawData (unsigned char * data, int length)
References BitStream::addBits(), bit_stream_, encodeBitStream(), and BitStream::pushBufferToBitStream().
Referenced by encodeAscii().
encodeAscii()
bool AFSK::encodeAscii (const std::string & message)
References encodeRawData().
Referenced by modulators::AfskAscii().
encodeBitStream()
void AFSK::encodeBitStream () private
NRZI encoding
0 is encoded as a change in tone, while 1 is encoded as no change It's not encoded into 0 and 1, it's bipolar, so -1 and 1.
References WavGen::addSample(), amplitude_, AX25, baud_rate_, bit_stream_, freq_center_, freq_dev_, BitStream::getBitStreamLength(), M_PI, MINIMODEM, mode_, BitStream::popNextBit(), sample_rate_, and wavgen_.
Referenced by encodeRawData().
addSymbol()
void AFSK::addSymbol (bool change) private
NRZI()
void AFSK::NRZI () private
Member Data Documentation
mode_
MODE AFSK::mode_ = MODE::MINIMODEM private
Referenced by encodeBitStream().
wavgen_
WavGen& AFSK::wavgen_ private
Referenced by encodeBitStream().
bit_stream_
BitStream AFSK::bit_stream_ = BitStream() private
Referenced by encodeBitStream(), and encodeRawData().
baud_rate_
const int AFSK::baud_rate_ = 1200 private
Referenced by encodeBitStream().
freq_center_
const int AFSK::freq_center_ = 1700 private
Referenced by encodeBitStream().
freq_dev_
const int AFSK::freq_dev_ = 500 private
Referenced by encodeBitStream().
last_bit_
bool AFSK::last_bit_ = false private
sample_rate_
const int AFSK::sample_rate_ = 44100 private
Referenced by encodeBitStream().
bits_per_sample_
const int AFSK::bits_per_sample_ = 16 private
max_amplitude_
const int AFSK::max_amplitude_ = pow(2, bits_per_sample_ - 1) - 1 private
amplitude_
double AFSK::amplitude_ = 1 private
Referenced by encodeBitStream().