Giraffe: BMP180 Class Reference
BMP180 Class Reference
#include <bmp180.h>
Public Member Functions
BMP180 (DataStream *p_data_stream, ExtensionMetadata extension_metadata)
~BMP180 ()
ExtensionMetadata::Category getCategory ()
int getCritical ()
std::vector< std::string > getExtraArgs ()
int getID ()
ExtensionMetadata::Interface getInterface ()
std::string getName ()
ExtensionStatus getStatus ()
std::string getType ()
int getUpdateInterval ()
void restart ()
Not implemented.
int runner ()
This must be overridden by each extension.
void start ()
Starts the extension thread if it is stopped, changes status.
void stop ()
Signals the thread to stop.
Protected Member Functions
void error (std::string error_code)
void error (std::string error_code, std::string info)
void sendData (std::string unit, float value)
Override for floats. See sendData(std::string, std::string).
void sendData (std::string unit, int value)
Override for integers. See sendData(std::string, std::string).
void sendData (std::string unit, std::string value)
Sends data to the data stream.
void setStatus (ExtensionStatus status)
Sets the status. Thread safe.
Protected Attributes
std::atomic< int > stop_flag_
Private Member Functions
int calculatePressure ()
int calculateTemperature ()
int handshake ()
int readCalibrationData ()
int readRawPressure ()
int readRawTemperature ()
short readShort (int registerAddress)
unsigned short readShortUnsigned (int registerAddress)
void setCategory (ExtensionMetadata::Category category)
Sets the category of the extension, does not do any error checking.
void setCritical (int critical)
Sets the critical flag of the extension 1=yes, 0=no.
void setExtraArgs (std::vector< std::string > extra_args)
void setID (int num)
Sets the ID of the extension, reports errors to the data stream.
void setInterface (ExtensionMetadata::Interface interface)
Sets the interface of the extension that will be used for device communication.
void setName (std::string name)
Sets the name of the extension, reports errors to the data stream.
void setType (std::string type)
Sets the type of the extension.
void setUpdateInterval (int interval)
Sets the update interval of the extension.
virtual void spawnRunner ()
This function will attempt to spawn the runner thread of the parent class.
Private Attributes
volatile short AC1_
volatile short AC2_
volatile short AC3_
volatile unsigned short AC4_
volatile unsigned short AC5_
volatile unsigned short AC6_
volatile short B1_
volatile short B2_
int B3_
unsigned int B4_
int B5_
int B6_
int B7_
uint8_t bus_number_
ExtensionMetadata::Category category_
int critical_
uint8_t device_address_
I2C i2c_bus_
int id_
ExtensionMetadata::Interface interface_
volatile short MB_
volatile short MC_
volatile short MD_
std::string name_
int P_
DataStream * p_data_stream_
float pressure_altitude_feet_
float pressure_altitude_meters_
float pressure_HPA_
float pressure_INHG_
std::vector< unsigned short > raw_calibration_data_
int raw_pressure_data_
int raw_temperature_data_
std::thread runner_thread_
std::atomic< ExtensionStatus > status_
int T_
float temp_C_
float temp_F_
std::string type_
int UP_
int update_interval_
int UT_
int X1_
int X2_
int X3_
Constructor & Destructor Documentation
BMP180()
BMP180::BMP180 (DataStream * p_data_stream, ExtensionMetadata extension_metadata)
References bus_number_, device_address_, ExtensionMetadata::extra_args, ExtensionMetadata::ExtraArgs::I2C_bus, i2c_bus_, and ExtensionMetadata::ExtraArgs::I2C_device_address.
~BMP180()
BMP180::~BMP180 ()
Member Function Documentation
runner()
int BMP180::runner () virtual
This must be overridden by each extension.
Todo:
Implement this.
This function is called by by spawnRunner() to start the thread. The runner belongs to each extension so the base class runner should never be called. The runner function override should contain an endless loop that generates data for the data stream. It should only continue the loop at a rate that is equal to 'update_interval_'. The runner must also check to see if the status is 'stopping', if it is it must shutdown and return 0. If this function is not overridden, it will add an error to the data stream and return -1.
Returns
int -1, an error value. 0 is for a clean stop.
Reimplemented from Extension.
References bus_number_, calculatePressure(), calculateTemperature(), I2C::connect(), device_address_, Extension::error(), ERROR, Extension::getUpdateInterval(), handshake(), i2c_bus_, pressure_altitude_feet_, pressure_altitude_meters_, pressure_HPA_, pressure_INHG_, readRawPressure(), readRawTemperature(), RUNNING, Extension::sendData(), Extension::setStatus(), Extension::stop_flag_, STOPPED, temp_C_, and temp_F_.
readCalibrationData()
int BMP180::readCalibrationData () private
References AC1_, AC2_, AC3_, AC4_, AC5_, AC6_, B1_, B2_, ExtensionException::description(), Extension::error(), ERROR, MB_, MC_, MD_, raw_calibration_data_, readShort(), readShortUnsigned(), REG_CAL_AC1, REG_CAL_AC2, REG_CAL_AC3, REG_CAL_AC4, REG_CAL_AC5, REG_CAL_AC6, REG_CAL_B1, REG_CAL_B2, REG_CAL_MB, REG_CAL_MC, REG_CAL_MD, and Extension::setStatus().
readRawTemperature()
int BMP180::readRawTemperature () private
References CMD_READTEMP, Extension::error(), ERROR, i2c_bus_, raw_temperature_data_, I2C::readByteFromReg(), REG_CTRL, REG_DATA, Extension::setStatus(), UT_, and I2C::writeByteToReg().
Referenced by runner().
readRawPressure()
int BMP180::readRawPressure () private
References CMD_READPRES, Extension::error(), ERROR, i2c_bus_, I2C::readByteFromReg(), REG_CTRL, REG_DATA, SAMPLING_ACCURACY, Extension::setStatus(), UP_, and I2C::writeByteToReg().
Referenced by runner().
calculateTemperature()
int BMP180::calculateTemperature () private
References AC5_, AC6_, B5_, Extension::error(), ERROR, MC_, MD_, Extension::setStatus(), T_, temp_C_, temp_F_, UT_, X1_, and X2_.
Referenced by runner().
calculatePressure()
int BMP180::calculatePressure () private
References AC2_, AC3_, AC4_, B1_, B2_, B3_, B4_, B5_, B6_, B7_, Extension::error(), ERROR, P_, pressure_altitude_feet_, pressure_altitude_meters_, pressure_HPA_, pressure_INHG_, SAMPLING_ACCURACY, Extension::setStatus(), temp_C_, UP_, X1_, X2_, and X3_.
Referenced by runner().
readShortUnsigned()
unsigned short BMP180::readShortUnsigned (int registerAddress) private
References i2c_bus_, and I2C::readByteFromReg().
Referenced by handshake(), readCalibrationData(), and readShort().
readShort()
short BMP180::readShort (int registerAddress) private
References readShortUnsigned().
Referenced by readCalibrationData().
handshake()
int BMP180::handshake () private
References Extension::error(), ERROR, readShortUnsigned(), REG_ID, and Extension::setStatus().
Referenced by runner().
start()
void Extension::start () inherited
Starts the extension thread if it is stopped, changes status.
This function attempts to start the extension thread with spawnRunner(). This will change the status to 'STARTING'. The thread is responsible for the later change to 'RUNNING' or 'ERROR'.
Parameters
None
Returns
void
References Extension::getStatus(), Extension::setStatus(), Extension::spawnRunner(), STARTING, and STOPPED.
stop()
void Extension::stop () inherited
Signals the thread to stop.
Sets the status to 'STOPPING' which signals the thread to stop. The thread is responsible for the later change to 'STOPPED' or 'ERROR'. This function does not wait for the thread to stop, it only changes the status. This functionality needs to be implemented in each extension's runner() method.
Todo:
Implement thread joining.
Parameters
None
Returns
void
References ERROR, Extension::getStatus(), Extension::runner_thread_, RUNNING, Extension::setStatus(), Extension::stop_flag_, and STOPPING.
restart()
void Extension::restart () inherited
Not implemented.
Restarts the extension thread and sets the status based on the result.
Todo:
Implement this.
getStatus()
ExtensionStatus Extension::getStatus () inherited
Returns
ExtensionStatus The status of the extension. Status is an atomic, so it is thread safe.
References Extension::status_.
Referenced by Extension::start(), and Extension::stop().
getID()
int Extension::getID () inherited
Returns
int The id of the extension.
References Extension::id_.
Referenced by Extension::error().
getName()
std::string Extension::getName () inherited
Returns
std::string The name of the extension.
References Extension::name_.
Referenced by Extension::sendData(), and Extension::setStatus().
getType()
std::string Extension::getType () inherited
Returns
std::string The type of the extension.
References Extension::type_.
getCategory()
ExtensionMetadata::Category Extension::getCategory () inherited
Returns
ExtensionMetadata::Category The category of the extension.
References Extension::category_.
getInterface()
ExtensionMetadata::Interface Extension::getInterface () inherited
Returns
ExtensionMetadata::Interface The interface of the extension.
References Extension::interface_.
getUpdateInterval()
int Extension::getUpdateInterval () inherited
Returns
int The update interval in milliseconds of the extension.
References Extension::update_interval_.
Referenced by runner(), DS18B20::runner(), TestExtension::runner(), BMP180_SIM::runner(), SAMM8Q_SIM::runner(), DS18B20_SIM::runner(), DRA818V_SIM::runner(), and Extension::sendData().
getCritical()
int Extension::getCritical () inherited
Returns
int Whether or not the extension is flight critical 0=no, 1=yes.
References Extension::critical_.
getExtraArgs()
std::vector<std::string> Extension::getExtraArgs () inherited
setStatus()
void Extension::setStatus (ExtensionStatus status) protected inherited
Sets the status. Thread safe.
Sets the status, no error checking is done. The status member is protected as a std::atomic<> so it is thread safe. This is called within the base class and parent class.
Parameters
status
References Extension::getName(), Extension::p_data_stream_, Extension::status_, and DataStream::updateExtensionStatus().
Referenced by Extension::Extension(), calculatePressure(), calculateTemperature(), handshake(), readCalibrationData(), readRawPressure(), readRawTemperature(), runner(), DS18B20::runner(), Extension::runner(), TestExtension::runner(), BMP180_SIM::runner(), SAMM8Q_SIM::runner(), DS18B20_SIM::runner(), DRA818V_SIM::runner(), Extension::setID(), Extension::setName(), Extension::start(), and Extension::stop().
sendData() [1/3]
void Extension::sendData (std::string unit, std::string value) protected inherited
Sends data to the data stream.
This function is used to send data from the extension to the data stream. It is a wrapper for the DataStream::addData() function. It fills in the extension name and the valid time in seconds which is defined as 'getUpdateInterval() / 1000'.
Bug:
This function does not take into account the time it may take an extension to collect it's data. Also send data could possibly be put into a template.
Parameters
std::string unit - The unit of the data. Example "TF" for temperature in fahrenheit. This is defined in the configuration.
std::string value
int value
float value
Returns
void
References DataStream::addData(), Extension::getName(), Extension::getUpdateInterval(), and Extension::p_data_stream_.
Referenced by runner(), DS18B20::runner(), TestExtension::runner(), BMP180_SIM::runner(), SAMM8Q_SIM::runner(), and DS18B20_SIM::runner().
sendData() [2/3]
void Extension::sendData (std::string unit, int value) protected inherited
Override for integers. See sendData(std::string, std::string).
Todo:
Limit number size?
References DataStream::addData(), Extension::getName(), Extension::getUpdateInterval(), and Extension::p_data_stream_.
sendData() [3/3]
void Extension::sendData (std::string unit, float value) protected inherited
Override for floats. See sendData(std::string, std::string).
Todo:
Limit to float precision?
References DataStream::addData(), Extension::getName(), Extension::getUpdateInterval(), and Extension::p_data_stream_.
error() [1/2]
void Extension::error (std::string error_code, std::string info) protected inherited
References DataStream::addError(), EXTENSION_PREFIX, Extension::getID(), Extension::p_data_stream_, and Extension::update_interval_.
Referenced by calculatePressure(), calculateTemperature(), handshake(), DS18B20::processData(), readCalibrationData(), DS18B20::readData(), readRawPressure(), readRawTemperature(), and runner().
error() [2/2]
void Extension::error (std::string error_code) protected inherited
References DataStream::addError(), EXTENSION_PREFIX, Extension::getID(), Extension::p_data_stream_, and Extension::update_interval_.
setID()
void Extension::setID (int num) private inherited
Sets the ID of the extension, reports errors to the data stream.
This does not check for duplicates.
Parameters
num The id
Returns
void
References DataStream::addError(), ERROR, EXTENSION_ID_MAX, EXTENSION_ID_MIN, Extension::id_, Extension::name_, Extension::p_data_stream_, and Extension::setStatus().
Referenced by Extension::Extension().
setName()
void Extension::setName (std::string name) private inherited
Sets the name of the extension, reports errors to the data stream.
Uses the extension max length and min length macros to validate the name. If the name is invalid, the status is set to ERROR, name is set to "NAME_ERROR" and the error is reported to the data stream. This error should be caught by the configuration module before it gets here.
Todo:
Add a check for valid characters (Is there a standard yet?).
Parameters
name The name of the extension.
Returns
void
References DataStream::addError(), ERROR, EXTENSION_NAME_MAX_LENGTH, EXTENSION_NAME_MIN_LENGTH, Extension::name_, Extension::p_data_stream_, and Extension::setStatus().
Referenced by Extension::Extension().
setType()
void Extension::setType (std::string type) private inherited
Sets the type of the extension.
Does not do any error checking.
Todo:
Add length and character checking.
Parameters
type
Returns
void
References Extension::type_.
Referenced by Extension::Extension().
setCategory()
void Extension::setCategory (ExtensionMetadata::Category category) private inherited
Sets the category of the extension, does not do any error checking.
Parameters
category
Returns
void
References Extension::category_.
Referenced by Extension::Extension().
setInterface()
void Extension::setInterface (ExtensionMetadata::Interface interface) private inherited
Sets the interface of the extension that will be used for device communication.
Parameters
interface
Returns
void
Todo:
Add extra args handling here if for interface. Ex: i2c bus and address.
References Extension::interface_.
Referenced by Extension::Extension().
setUpdateInterval()
void Extension::setUpdateInterval (int interval_ms) private inherited
Sets the update interval of the extension.
Currently does not do any error checking.
Todo:
Add range checking.
Parameters
interval The update interval in milliseconds, 0 means the thread will return after a single run.
References Extension::update_interval_.
Referenced by Extension::Extension().
setCritical()
void Extension::setCritical (int critical) private inherited
Sets the critical flag of the extension 1=yes, 0=no.
If the extension is flight critical and the status is 'ERROR' then the system should attempt to recover. This is/will be implemented in the health_check() function.
See also
health_check()
Parameters
critical 1=yes, 0=no.
References DataStream::addError(), Extension::critical_, Extension::name_, and Extension::p_data_stream_.
Referenced by Extension::Extension().
setExtraArgs()
void Extension::setExtraArgs (std::vector< std::string > extra_args) private inherited
spawnRunner()
void Extension::spawnRunner () private virtual inherited
This function will attempt to spawn the runner thread of the parent class.
Todo:
Implement this.
References Extension::runner(), and Extension::runner_thread_.
Referenced by Extension::start().
Member Data Documentation
bus_number_
uint8_t BMP180::bus_number_ private
Referenced by BMP180(), and runner().
device_address_
uint8_t BMP180::device_address_ private
Referenced by BMP180(), and runner().
i2c_bus_
I2C BMP180::i2c_bus_ private
Referenced by BMP180(), readRawPressure(), readRawTemperature(), readShortUnsigned(), and runner().
temp_F_
float BMP180::temp_F_ private
Referenced by calculateTemperature(), and runner().
temp_C_
float BMP180::temp_C_ private
Referenced by calculatePressure(), calculateTemperature(), and runner().
pressure_HPA_
float BMP180::pressure_HPA_ private
Referenced by calculatePressure(), and runner().
pressure_INHG_
float BMP180::pressure_INHG_ private
Referenced by calculatePressure(), and runner().
pressure_altitude_meters_
float BMP180::pressure_altitude_meters_ private
Referenced by calculatePressure(), and runner().
pressure_altitude_feet_
float BMP180::pressure_altitude_feet_ private
Referenced by calculatePressure(), and runner().
raw_calibration_data_
std::vector<unsigned short> BMP180::raw_calibration_data_ private
Referenced by readCalibrationData().
raw_temperature_data_
int BMP180::raw_temperature_data_ private
Referenced by readRawTemperature().
raw_pressure_data_
int BMP180::raw_pressure_data_ private
AC1_
volatile short BMP180::AC1_ private
Referenced by readCalibrationData().
AC2_
volatile short BMP180::AC2_ private
Referenced by calculatePressure(), and readCalibrationData().
AC3_
volatile short BMP180::AC3_ private
Referenced by calculatePressure(), and readCalibrationData().
AC4_
volatile unsigned short BMP180::AC4_ private
Referenced by calculatePressure(), and readCalibrationData().
AC5_
volatile unsigned short BMP180::AC5_ private
Referenced by calculateTemperature(), and readCalibrationData().
AC6_
volatile unsigned short BMP180::AC6_ private
Referenced by calculateTemperature(), and readCalibrationData().
B1_
volatile short BMP180::B1_ private
Referenced by calculatePressure(), and readCalibrationData().
B2_
volatile short BMP180::B2_ private
Referenced by calculatePressure(), and readCalibrationData().
MB_
volatile short BMP180::MB_ private
Referenced by readCalibrationData().
MC_
volatile short BMP180::MC_ private
Referenced by calculateTemperature(), and readCalibrationData().
MD_
volatile short BMP180::MD_ private
Referenced by calculateTemperature(), and readCalibrationData().
UT_
int BMP180::UT_ private
Referenced by calculateTemperature(), and readRawTemperature().
UP_
int BMP180::UP_ private
Referenced by calculatePressure(), and readRawPressure().
X1_
int BMP180::X1_ private
Referenced by calculatePressure(), and calculateTemperature().
X2_
int BMP180::X2_ private
Referenced by calculatePressure(), and calculateTemperature().
X3_
int BMP180::X3_ private
Referenced by calculatePressure().
B3_
int BMP180::B3_ private
Referenced by calculatePressure().
B4_
unsigned int BMP180::B4_ private
Referenced by calculatePressure().
B5_
int BMP180::B5_ private
Referenced by calculatePressure(), and calculateTemperature().
B6_
int BMP180::B6_ private
Referenced by calculatePressure().
B7_
int BMP180::B7_ private
Referenced by calculatePressure().
T_
int BMP180::T_ private
Referenced by calculateTemperature().
P_
int BMP180::P_ private
Referenced by calculatePressure().
stop_flag_
std::atomic<int> Extension::stop_flag_ protected inherited
Referenced by runner(), DS18B20::runner(), TestExtension::runner(), BMP180_SIM::runner(), SAMM8Q_SIM::runner(), DS18B20_SIM::runner(), DRA818V_SIM::runner(), and Extension::stop().
p_data_stream_
DataStream* Extension::p_data_stream_ private inherited
Referenced by Extension::Extension(), Extension::error(), Extension::runner(), Extension::sendData(), Extension::setCritical(), Extension::setID(), Extension::setName(), and Extension::setStatus().
runner_thread_
std::thread Extension::runner_thread_ private inherited
Referenced by Extension::spawnRunner(), and Extension::stop().
status_
std::atomic<ExtensionStatus> Extension::status_ private inherited
Referenced by Extension::getStatus(), and Extension::setStatus().
id_
int Extension::id_ private inherited
Referenced by Extension::getID(), and Extension::setID().
name_
std::string Extension::name_ private inherited
Referenced by Extension::getName(), Extension::runner(), Extension::setCritical(), Extension::setID(), and Extension::setName().
type_
std::string Extension::type_ private inherited
Referenced by Extension::getType(), and Extension::setType().
category_
ExtensionMetadata::Category Extension::category_ private inherited
Referenced by Extension::getCategory(), and Extension::setCategory().
interface_
ExtensionMetadata::Interface Extension::interface_ private inherited
Referenced by Extension::getInterface(), and Extension::setInterface().
update_interval_
int Extension::update_interval_ private inherited
Referenced by Extension::error(), Extension::getUpdateInterval(), and Extension::setUpdateInterval().
critical_
int Extension::critical_ private inherited
Referenced by Extension::getCritical(), and Extension::setCritical().