Giraffe: DataStream Class Reference
DataStream Class Reference
This class is passed to many extensions/modules. It is used to communicate data and errors to the data module from any location or even from other threads. There are locks when writing or reading from the streams that will allow for data safety when threads access the stream. This class is ultimately the communication bridge between sections of the flight computer.
#include <data-stream.h>
Classes
struct TXLogInfo
Public Member Functions
DataStream ()
Construct a new DataStream object.
~DataStream ()
Destroys the DataStream object. Waits for other threads to finish first. Other threads that access the data should be stopped before this is called.
void addData (std::string data_source, std::string data_name, std::string data_value, int seconds_until_expiry)
Add data to the data stream. This function is thread safe.
void addError (std::string error_source, std::string error_code, std::string error_info, int seconds_until_expiry=0)
Add an error to the error stream. This function is thread safe.
void addToCommandQueue (std::string command)
void addToTxQueue (Transmission tx)
std::string getData (std::string data_source, std::string data_name)
DataFrame getDataFrameCopy ()
Makes a copy of the DataFrame and returns it. This is generally called by a thread in a different module. This is thread safe.
ErrorFrame getErrorFrameCopy ()
std::unordered_map< std::string, ExtensionStatus > getExtensionStatuses ()
FlightProcedure getFlightProcedureCopy ()
std::mutex & getI2CBusLock ()
bool getNextCommand (GFSCommand &command)
DataStreamPacket getNextDataPacket ()
Returns the next data packet. Thread safe.
ErrorStreamPacket getNextErrorPacket ()
Returns the next error. Thread safe.
Transmission getNextTX ()
int getNumDataPackets ()
int getNumErrorPackets ()
int getTotalDataPackets ()
int getTotalErrorPackets ()
int getTotalTx ()
const std::deque< Transmission > & getTXLog ()
const TXLogInfo getTXLogInfo ()
const std::queue< Transmission > & getTXQueue ()
int getTXQueueSize ()
void lockTXLog ()
void lockTXQueue ()
bool requestTXFromLog (int tx_id, Transmission &tx)
void unlockTXLog ()
void unlockTXQueue ()
void updateDataFrame (DataFrame data_frame)
This is called externally by the data module. It is used to update the data frame that can be accessed by everyone. Thread safe.
void updateErrorFrame (ErrorFrame error_frame)
void updateExtensionStatus (std::string extension_name, ExtensionStatus status)
void updateFlightProcedure (FlightProcedure flight_procedure)
void updateModuleStatus (std::string module_name, ModuleStatus status)
Private Member Functions
void error (std::string code)
void error (std::string code, std::string info)
Private Attributes
std::queue< GFSCommand > command_queue_ = std::queue<GFSCommand>()
std::mutex command_queue_lock_ = std::mutex()
DataFrame data_frame_ = DataFrame()
std::mutex data_frame_lock_ = std::mutex()
std::queue< DataStreamPacket > data_stream_ = std::queue<DataStreamPacket>()
std::mutex data_stream_lock_ = std::mutex()
ErrorFrame error_frame_ = ErrorFrame()
std::mutex error_frame_lock_ = std::mutex()
std::queue< ErrorStreamPacket > error_stream_ = std::queue<ErrorStreamPacket>()
std::mutex error_stream_lock_ = std::mutex()
std::unordered_map< std::string, ExtensionStatus > extension_status_
std::mutex extension_status_lock_ = std::mutex()
int first_tx_in_log_ = 0
FlightProcedure flight_procedure_ = FlightProcedure()
std::mutex flight_procedure_lock_ = std::mutex()
std::mutex i2c_bus_lock_ = std::mutex()
const int kTXLogSize_ = 10
int last_tx_in_log_ = 0
std::unordered_map< std::string, ModuleStatus > module_status_
std::mutex module_status_lock_ = std::mutex()
int num_data_packets_ = 0
int num_error_packets_ = 0
int total_data_packets_ = 0
int total_error_packets_ = 0
std::deque< Transmission > tx_log_ {}
std::mutex tx_log_lock_ = std::mutex()
std::queue< Transmission > tx_queue_ = std::queue<Transmission>()
std::mutex tx_queue_lock_ = std::mutex()
Detailed Description
This class is passed to many extensions/modules. It is used to communicate data and errors to the data module from any location or even from other threads. There are locks when writing or reading from the streams that will allow for data safety when threads access the stream. This class is ultimately the communication bridge between sections of the flight computer.
Class Documentation
DataStream::TXLogInfo
struct DataStream::TXLogInfo
Class Members
int tx_log_size
int max_size
int first_tx_in_log
int last_tx_in_log
Constructor & Destructor Documentation
DataStream()
DataStream::DataStream ()
Construct a new DataStream object.
Parameters
None
References data_stream_lock_, error_stream_lock_, num_data_packets_, num_error_packets_, total_data_packets_, and total_error_packets_.
~DataStream()
DataStream::~DataStream ()
Destroys the DataStream object. Waits for other threads to finish first. Other threads that access the data should be stopped before this is called.
References data_frame_lock_, data_stream_lock_, error_frame_lock_, and error_stream_lock_.
Member Function Documentation
addToCommandQueue()
void DataStream::addToCommandQueue (std::string command)
References GFSCommand::arg, GFSCommand::category, command_queue_, command_queue_lock_, error(), GFSCommand::EXT, GFSCommand::FLR, GFSCommand::id, GFSCommand::MDL, and GFSCommand::TLM.
Referenced by modules::ServerModule::runner().
getNextCommand()
bool DataStream::getNextCommand (GFSCommand & command)
References command_queue_, and command_queue_lock_.
Referenced by FlightRunner::flightLoop().
addData()
void DataStream::addData (std::string data_source, std::string data_name, std::string data_value, int seconds_until_expiry)
Add data to the data stream. This function is thread safe.
Parameters
data_source - The source of the data, ie "BMP180"
data_name - The name of the data, ie "TEMP_F"
data_value - The value of the data, ie "72.5"
seconds_until_expiry - The number of seconds until the data should be considered expired. If this is 0, the data will never expire.
References data_stream_, data_stream_lock_, num_data_packets_, and total_data_packets_.
Referenced by modules::Module::data(), modules::TelemetryModule::playWav(), modules::TelemetryModule::runner(), modules::ServerModule::runner(), and modules::TelemetryModule::start().
addError()
void DataStream::addError (std::string error_source, std::string error_code, std::string error_info, int seconds_until_expiry = 0)
Add an error to the error stream. This function is thread safe.
Parameters
error_source The file or function that the error occurred in.
error_code The error code or name.
error_info Human readable information about the error.
seconds_until_expiry The number of seconds until the error should be considered expired. If this is 0, the error will never expire.
Returns
void
References error_stream_, error_stream_lock_, num_error_packets_, and total_error_packets_.
Referenced by modules::TelemetryModule::addToTXQueue(), addToTxQueue(), error(), modules::Module::error(), modules::ConfigModule::error(), modules::ServerModule::runner(), modules::ServerModule::sendDynamicData(), and modules::ServerModule::sendTelemetryData().
updateDataFrame()
void DataStream::updateDataFrame (DataFrame data_frame)
This is called externally by the data module. It is used to update the data frame that can be accessed by everyone. Thread safe.
Parameters
data_frame
Returns
void
References data_frame_, and data_frame_lock_.
Referenced by modules::DataModule::parseDataStream().
updateErrorFrame()
void DataStream::updateErrorFrame (ErrorFrame error_frame)
References error_frame_, and error_frame_lock_.
Referenced by modules::DataModule::parseErrorStream().
updateFlightProcedure()
void DataStream::updateFlightProcedure (FlightProcedure flight_procedure)
References flight_procedure_, and flight_procedure_lock_.
Referenced by FlightRunner::switchLoops().
getNextDataPacket()
DataStreamPacket DataStream::getNextDataPacket ()
Returns the next data packet. Thread safe.
Parameters
None
Returns
DataStreamPacket The next data packet, or an empty one if there are no more data packets.
References data_stream_, data_stream_lock_, and num_data_packets_.
Referenced by modules::DataModule::parseDataStream().
getNextErrorPacket()
ErrorStreamPacket DataStream::getNextErrorPacket ()
Returns the next error. Thread safe.
Parameters
None
Returns
ErrorStreamPacket An error stream packet with an error. If there are no more errors it will return an empty packet.
References error_stream_, error_stream_lock_, and num_error_packets_.
Referenced by modules::DataModule::parseErrorStream().
getData()
std::string DataStream::getData (std::string data_source, std::string data_name)
References data_frame_, and data_frame_lock_.
getDataFrameCopy()
DataFrame DataStream::getDataFrameCopy ()
Makes a copy of the DataFrame and returns it. This is generally called by a thread in a different module. This is thread safe.
Parameters
None
Returns
DataFrame
References data_frame_, and data_frame_lock_.
Referenced by modules::DataModule::log(), modules::ConsoleModule::printData(), modules::TelemetryModule::sendAPRS(), modules::TelemetryModule::sendDataPacket(), and modules::ServerModule::sendDynamicData().
getErrorFrameCopy()
ErrorFrame DataStream::getErrorFrameCopy ()
References error_frame_, and error_frame_lock_.
Referenced by modules::ConsoleModule::printData(), and modules::ServerModule::sendDynamicData().
getFlightProcedureCopy()
FlightProcedure DataStream::getFlightProcedureCopy ()
References flight_procedure_, and flight_procedure_lock_.
Referenced by modules::ConsoleModule::printData().
getNumDataPackets()
int DataStream::getNumDataPackets ()
Returns
int The number of data packets in the data stream.
References num_data_packets_.
Referenced by modules::DataModule::parseDataStream(), and modules::ConsoleModule::printData().
getNumErrorPackets()
int DataStream::getNumErrorPackets ()
Returns
int The number of error packets in the error stream.
References num_error_packets_.
Referenced by modules::DataModule::parseErrorStream(), and modules::ConsoleModule::printData().
getTotalDataPackets()
int DataStream::getTotalDataPackets ()
Returns
int The total number of data packets that have been added to the data stream since the data stream was created.
References total_data_packets_.
Referenced by modules::ConsoleModule::printData().
getTotalErrorPackets()
int DataStream::getTotalErrorPackets ()
Returns
int The total number of error packets that have been added to the error stream since the error stream was created.
References total_error_packets_.
Referenced by modules::ConsoleModule::printData().
lockTXQueue()
void DataStream::lockTXQueue ()
References tx_queue_lock_.
Referenced by modules::ServerModule::sendDynamicData().
getTXQueue()
const std::queue< Transmission > & DataStream::getTXQueue ()
References tx_queue_.
Referenced by modules::ServerModule::sendDynamicData().
unlockTXQueue()
void DataStream::unlockTXQueue ()
References tx_queue_lock_.
Referenced by modules::ServerModule::sendDynamicData().
addToTxQueue()
void DataStream::addToTxQueue (Transmission tx)
References addError(), first_tx_in_log_, kTXLogSize_, last_tx_in_log_, tx_log_, tx_log_lock_, Transmission::tx_num, tx_queue_, and tx_queue_lock_.
Referenced by modules::TelemetryModule::addToTXQueue().
getNextTX()
Transmission DataStream::getNextTX ()
References tx_queue_, and tx_queue_lock_.
Referenced by modules::TelemetryModule::runner().
getTXQueueSize()
int DataStream::getTXQueueSize ()
References tx_queue_, and tx_queue_lock_.
Referenced by modules::TelemetryModule::runner().
getTotalTx()
int DataStream::getTotalTx ()
lockTXLog()
void DataStream::lockTXLog ()
References tx_log_lock_.
Referenced by modules::ServerModule::sendTelemetryData().
getTXLog()
const std::deque< Transmission > & DataStream::getTXLog ()
References tx_log_.
Referenced by modules::ServerModule::sendTelemetryData().
unlockTXLog()
void DataStream::unlockTXLog ()
References tx_log_lock_.
Referenced by modules::ServerModule::sendTelemetryData().
getTXLogInfo()
const DataStream::TXLogInfo DataStream::getTXLogInfo ()
References DataStream::TXLogInfo::first_tx_in_log, first_tx_in_log_, kTXLogSize_, DataStream::TXLogInfo::last_tx_in_log, last_tx_in_log_, DataStream::TXLogInfo::max_size, tx_log_, tx_log_lock_, and DataStream::TXLogInfo::tx_log_size.
Referenced by modules::TelemetryModule::runner(), and modules::ServerModule::sendTelemetryData().
requestTXFromLog()
bool DataStream::requestTXFromLog (int tx_id, Transmission & tx)
References first_tx_in_log_, last_tx_in_log_, tx_log_, and tx_log_lock_.
Referenced by modules::TelemetryModule::doCommand().
updateExtensionStatus()
void DataStream::updateExtensionStatus (std::string extension_name, ExtensionStatus status)
References extension_status_, and extension_status_lock_.
updateModuleStatus()
void DataStream::updateModuleStatus (std::string module_name, ModuleStatus status)
References module_status_, and module_status_lock_.
getExtensionStatuses()
std::unordered_map< std::string, ExtensionStatus > DataStream::getExtensionStatuses ()
References extension_status_, and extension_status_lock_.
Referenced by modules::ServerModule::sendDynamicData().
getI2CBusLock()
std::mutex & DataStream::getI2CBusLock ()
References i2c_bus_lock_.
error() [1/2]
void DataStream::error (std::string code) private
References addError().
Referenced by addToCommandQueue().
error() [2/2]
void DataStream::error (std::string code, std::string info) private
References addError().
Member Data Documentation
num_data_packets_
int DataStream::num_data_packets_ = 0 private
Referenced by DataStream(), addData(), getNextDataPacket(), and getNumDataPackets().
total_data_packets_
int DataStream::total_data_packets_ = 0 private
Referenced by DataStream(), addData(), and getTotalDataPackets().
num_error_packets_
int DataStream::num_error_packets_ = 0 private
Referenced by DataStream(), addError(), getNextErrorPacket(), and getNumErrorPackets().
total_error_packets_
int DataStream::total_error_packets_ = 0 private
Referenced by DataStream(), addError(), and getTotalErrorPackets().
command_queue_lock_
std::mutex DataStream::command_queue_lock_ = std::mutex() private
Referenced by addToCommandQueue(), and getNextCommand().
command_queue_
std::queue<GFSCommand> DataStream::command_queue_ = std::queue<GFSCommand>() private
Referenced by addToCommandQueue(), and getNextCommand().
data_stream_lock_
std::mutex DataStream::data_stream_lock_ = std::mutex() private
Referenced by DataStream(), ~DataStream(), addData(), and getNextDataPacket().
data_stream_
std::queue<DataStreamPacket> DataStream::data_stream_ = std::queue<DataStreamPacket>() private
Referenced by addData(), and getNextDataPacket().
error_stream_lock_
std::mutex DataStream::error_stream_lock_ = std::mutex() private
Referenced by DataStream(), ~DataStream(), addError(), and getNextErrorPacket().
error_stream_
std::queue<ErrorStreamPacket> DataStream::error_stream_ = std::queue<ErrorStreamPacket>() private
Referenced by addError(), and getNextErrorPacket().
data_frame_lock_
std::mutex DataStream::data_frame_lock_ = std::mutex() private
Referenced by ~DataStream(), getData(), getDataFrameCopy(), and updateDataFrame().
data_frame_
DataFrame DataStream::data_frame_ = DataFrame() private
Referenced by getData(), getDataFrameCopy(), and updateDataFrame().
error_frame_lock_
std::mutex DataStream::error_frame_lock_ = std::mutex() private
Referenced by ~DataStream(), getErrorFrameCopy(), and updateErrorFrame().
error_frame_
ErrorFrame DataStream::error_frame_ = ErrorFrame() private
Referenced by getErrorFrameCopy(), and updateErrorFrame().
flight_procedure_lock_
std::mutex DataStream::flight_procedure_lock_ = std::mutex() private
Referenced by getFlightProcedureCopy(), and updateFlightProcedure().
flight_procedure_
FlightProcedure DataStream::flight_procedure_ = FlightProcedure() private
Referenced by getFlightProcedureCopy(), and updateFlightProcedure().
tx_queue_lock_
std::mutex DataStream::tx_queue_lock_ = std::mutex() private
Referenced by addToTxQueue(), getNextTX(), getTXQueueSize(), lockTXQueue(), and unlockTXQueue().
tx_queue_
std::queue<Transmission> DataStream::tx_queue_ = std::queue<Transmission>() private
Referenced by addToTxQueue(), getNextTX(), getTXQueue(), and getTXQueueSize().
extension_status_lock_
std::mutex DataStream::extension_status_lock_ = std::mutex() private
Referenced by getExtensionStatuses(), and updateExtensionStatus().
extension_status_
std::unordered_map<std::string, ExtensionStatus> DataStream::extension_status_ private
Initial value:
=
        std::unordered_map<std::string, ExtensionStatus>()
Referenced by getExtensionStatuses(), and updateExtensionStatus().
module_status_lock_
std::mutex DataStream::module_status_lock_ = std::mutex() private
Referenced by updateModuleStatus().
module_status_
std::unordered_map<std::string, ModuleStatus> DataStream::module_status_ private
Initial value:
=
        std::unordered_map<std::string, ModuleStatus>()
Referenced by updateModuleStatus().
i2c_bus_lock_
std::mutex DataStream::i2c_bus_lock_ = std::mutex() private
Referenced by getI2CBusLock().
tx_log_lock_
std::mutex DataStream::tx_log_lock_ = std::mutex() private
Referenced by addToTxQueue(), getTXLogInfo(), lockTXLog(), requestTXFromLog(), and unlockTXLog().
kTXLogSize_
const int DataStream::kTXLogSize_ = 10 private
Referenced by addToTxQueue(), and getTXLogInfo().
tx_log_
std::deque<Transmission> DataStream::tx_log_ {} private
Todo:
make this user configurable
Referenced by addToTxQueue(), getTXLog(), getTXLogInfo(), and requestTXFromLog().
first_tx_in_log_
int DataStream::first_tx_in_log_ = 0 private
Referenced by addToTxQueue(), getTXLogInfo(), and requestTXFromLog().
last_tx_in_log_
int DataStream::last_tx_in_log_ = 0 private
Referenced by addToTxQueue(), getTXLogInfo(), and requestTXFromLog().