Giraffe: SAMM8Q_SIM Class Reference
SAMM8Q_SIM Class Reference
The SAMM8Q_SIM is a simulated SAM-M8Q extension.
#include <simulated-extensions.h>
Public Member Functions
SAMM8Q_SIM (DataStream *p_data_stream, ExtensionMetadata extension_metadata)
~SAMM8Q_SIM ()
ExtensionMetadata::Category getCategory ()
int getCritical ()
std::vector< std::string > getExtraArgs ()
int getID ()
ExtensionMetadata::Interface getInterface ()
std::string getName ()
ExtensionStatus getStatus ()
std::string getType ()
int getUpdateInterval ()
void restart ()
Not implemented.
int runner ()
This must be overridden by each extension.
void start ()
Starts the extension thread if it is stopped, changes status.
void stop ()
Signals the thread to stop.
Protected Member Functions
void sendData (std::string unit, float value)
Override for floats. See sendData(std::string, std::string).
void sendData (std::string unit, int value)
Override for integers. See sendData(std::string, std::string).
void sendData (std::string unit, std::string value)
Sends data to the data stream.
void setStatus (ExtensionStatus status)
Sets the status. Thread safe.
Protected Attributes
std::atomic< int > stop_flag_
Private Member Functions
void setCategory (ExtensionMetadata::Category category)
Sets the category of the extension, does not do any error checking.
void setCritical (int critical)
Sets the critical flag of the extension 1=yes, 0=no.
void setExtraArgs (std::vector< std::string > extra_args)
void setID (int num)
Sets the ID of the extension, reports errors to the data stream.
void setInterface (ExtensionMetadata::Interface interface)
Sets the interface of the extension that will be used for device communication.
void setName (std::string name)
Sets the name of the extension, reports errors to the data stream.
void setType (std::string type)
Sets the type of the extension.
void setUpdateInterval (int interval)
Sets the update interval of the extension.
virtual void spawnRunner ()
This function will attempt to spawn the runner thread of the parent class.
Private Attributes
ExtensionMetadata::Category category_
int critical_
int id_
ExtensionMetadata::Interface interface_
std::string name_
DataStream * p_data_stream_
std::thread runner_thread_
std::atomic< ExtensionStatus > status_
std::string type_
int update_interval_
Detailed Description
The SAMM8Q_SIM is a simulated SAM-M8Q extension.
The SAMM8Q_SIM sends simulated data to the data stream every cycle. It sends the following data unit pairs: <GPS_LAT, lattitude>, <GPS_LON, longitude>, <GPS_ALT_M, altitude in meters>, <GPS_QUAL, quality 2, 1, 0>, <HORZ_SPEED, horizontal speed in m/s>, <VERT_SPEED, vertical speed in m/s>.
Vertical speed will only be sent one time, which will result in stale data. This is to test the data module. Lat, lon, alt, and horizontal speed will change every cycle.
Constructor & Destructor Documentation
SAMM8Q_SIM()
SAMM8Q_SIM::SAMM8Q_SIM (DataStream * p_data_stream, ExtensionMetadata extension_metadata)
~SAMM8Q_SIM()
SAMM8Q_SIM::~SAMM8Q_SIM ()
Member Function Documentation
runner()
int SAMM8Q_SIM::runner () virtual
This must be overridden by each extension.
Todo:
Implement this.
This function is called by by spawnRunner() to start the thread. The runner belongs to each extension so the base class runner should never be called. The runner function override should contain an endless loop that generates data for the data stream. It should only continue the loop at a rate that is equal to 'update_interval_'. The runner must also check to see if the status is 'stopping', if it is it must shutdown and return 0. If this function is not overridden, it will add an error to the data stream and return -1.
Returns
int -1, an error value. 0 is for a clean stop.
Reimplemented from Extension.
References Extension::getUpdateInterval(), RUNNING, Extension::sendData(), Extension::setStatus(), Extension::stop_flag_, and STOPPED.
start()
void Extension::start () inherited
Starts the extension thread if it is stopped, changes status.
This function attempts to start the extension thread with spawnRunner(). This will change the status to 'STARTING'. The thread is responsible for the later change to 'RUNNING' or 'ERROR'.
Parameters
None
Returns
void
References Extension::getStatus(), Extension::setStatus(), Extension::spawnRunner(), STARTING, and STOPPED.
stop()
void Extension::stop () inherited
Signals the thread to stop.
Sets the status to 'STOPPING' which signals the thread to stop. The thread is responsible for the later change to 'STOPPED' or 'ERROR'. This function does not wait for the thread to stop, it only changes the status. This functionality needs to be implemented in each extension's runner() method.
Todo:
Implement thread joining.
Parameters
None
Returns
void
References ERROR, Extension::getStatus(), Extension::runner_thread_, RUNNING, Extension::setStatus(), Extension::stop_flag_, and STOPPING.
restart()
void Extension::restart () inherited
Not implemented.
Restarts the extension thread and sets the status based on the result.
Todo:
Implement this.
getStatus()
ExtensionStatus Extension::getStatus () inherited
Returns
ExtensionStatus The status of the extension. Status is an atomic, so it is thread safe.
References Extension::status_.
Referenced by Extension::start(), and Extension::stop().
getID()
int Extension::getID () inherited
Returns
int The id of the extension.
References Extension::id_.
getName()
std::string Extension::getName () inherited
Returns
std::string The name of the extension.
References Extension::name_.
Referenced by Extension::sendData().
getType()
std::string Extension::getType () inherited
Returns
std::string The type of the extension.
References Extension::type_.
getCategory()
ExtensionMetadata::Category Extension::getCategory () inherited
Returns
ExtensionMetadata::Category The category of the extension.
References Extension::category_.
getInterface()
ExtensionMetadata::Interface Extension::getInterface () inherited
Returns
ExtensionMetadata::Interface The interface of the extension.
References Extension::interface_.
getUpdateInterval()
int Extension::getUpdateInterval () inherited
Returns
int The update interval in milliseconds of the extension.
References Extension::update_interval_.
Referenced by TestExtension::runner(), BMP180_SIM::runner(), runner(), DS18B20_SIM::runner(), DRA818V_SIM::runner(), and Extension::sendData().
getCritical()
int Extension::getCritical () inherited
Returns
int Whether or not the extension is flight critical 0=no, 1=yes.
References Extension::critical_.
getExtraArgs()
std::vector<std::string> Extension::getExtraArgs () inherited
setStatus()
void Extension::setStatus (ExtensionStatus status) protected inherited
Sets the status. Thread safe.
Sets the status, no error checking is done. The status member is protected as a std::atomic<> so it is thread safe. This is called within the base class and parent class.
Parameters
status
References Extension::status_.
Referenced by Extension::Extension(), Extension::runner(), TestExtension::runner(), BMP180_SIM::runner(), runner(), DS18B20_SIM::runner(), DRA818V_SIM::runner(), Extension::setID(), Extension::setName(), Extension::start(), and Extension::stop().
sendData() [1/3]
void Extension::sendData (std::string unit, std::string value) protected inherited
Sends data to the data stream.
This function is used to send data from the extension to the data stream. It is a wrapper for the DataStream::addData() function. It fills in the extension name and the valid time in seconds which is defined as 'getUpdateInterval() / 1000'.
Bug:
This function does not take into account the time it may take an extension to collect it's data. Also send data could possibly be put into a template.
Parameters
std::string unit - The unit of the data. Example "TF" for temperature in fahrenheit. This is defined in the configuration.
std::string value
int value
float value
Returns
void
References DataStream::addData(), Extension::getName(), Extension::getUpdateInterval(), and Extension::p_data_stream_.
Referenced by TestExtension::runner(), BMP180_SIM::runner(), runner(), and DS18B20_SIM::runner().
sendData() [2/3]
void Extension::sendData (std::string unit, int value) protected inherited
Override for integers. See sendData(std::string, std::string).
Todo:
Limit number size?
References DataStream::addData(), Extension::getName(), Extension::getUpdateInterval(), and Extension::p_data_stream_.
sendData() [3/3]
void Extension::sendData (std::string unit, float value) protected inherited
Override for floats. See sendData(std::string, std::string).
Todo:
Limit to float precision?
References DataStream::addData(), Extension::getName(), Extension::getUpdateInterval(), and Extension::p_data_stream_.
setID()
void Extension::setID (int num) private inherited
Sets the ID of the extension, reports errors to the data stream.
This does not check for duplicates.
Parameters
num The id
Returns
void
References DataStream::addError(), ERROR, EXTENSION_ID_MAX, EXTENSION_ID_MIN, Extension::id_, Extension::name_, Extension::p_data_stream_, and Extension::setStatus().
Referenced by Extension::Extension().
setName()
void Extension::setName (std::string name) private inherited
Sets the name of the extension, reports errors to the data stream.
Uses the extension max length and min length macros to validate the name. If the name is invalid, the status is set to ERROR, name is set to "NAME_ERROR" and the error is reported to the data stream. This error should be caught by the configuration module before it gets here.
Todo:
Add a check for valid characters (Is there a standard yet?).
Parameters
name The name of the extension.
Returns
void
References DataStream::addError(), ERROR, EXTENSION_NAME_MAX_LENGTH, EXTENSION_NAME_MIN_LENGTH, Extension::name_, Extension::p_data_stream_, and Extension::setStatus().
Referenced by Extension::Extension().
setType()
void Extension::setType (std::string type) private inherited
Sets the type of the extension.
Does not do any error checking.
Todo:
Add length and character checking.
Parameters
type
Returns
void
References Extension::type_.
Referenced by Extension::Extension().
setCategory()
void Extension::setCategory (ExtensionMetadata::Category category) private inherited
Sets the category of the extension, does not do any error checking.
Parameters
category
Returns
void
References Extension::category_.
Referenced by Extension::Extension().
setInterface()
void Extension::setInterface (ExtensionMetadata::Interface interface) private inherited
Sets the interface of the extension that will be used for device communication.
Parameters
interface
Returns
void
Todo:
Add extra args handling here if for interface. Ex: i2c bus and address.
References Extension::interface_.
Referenced by Extension::Extension().
setUpdateInterval()
void Extension::setUpdateInterval (int interval_ms) private inherited
Sets the update interval of the extension.
Currently does not do any error checking.
Todo:
Add range checking.
Parameters
interval The update interval in milliseconds, 0 means the thread will return after a single run.
References Extension::update_interval_.
Referenced by Extension::Extension().
setCritical()
void Extension::setCritical (int critical) private inherited
Sets the critical flag of the extension 1=yes, 0=no.
If the extension is flight critical and the status is 'ERROR' then the system should attempt to recover. This is/will be implemented in the health_check() function.
See also
health_check()
Parameters
critical 1=yes, 0=no.
References DataStream::addError(), Extension::critical_, Extension::name_, and Extension::p_data_stream_.
Referenced by Extension::Extension().
setExtraArgs()
void Extension::setExtraArgs (std::vector< std::string > extra_args) private inherited
spawnRunner()
void Extension::spawnRunner () private virtual inherited
This function will attempt to spawn the runner thread of the parent class.
Todo:
Implement this.
References Extension::runner(), and Extension::runner_thread_.
Referenced by Extension::start().
Member Data Documentation
stop_flag_
std::atomic<int> Extension::stop_flag_ protected inherited
Referenced by TestExtension::runner(), BMP180_SIM::runner(), runner(), DS18B20_SIM::runner(), DRA818V_SIM::runner(), and Extension::stop().
p_data_stream_
DataStream* Extension::p_data_stream_ private inherited
Referenced by Extension::Extension(), Extension::runner(), Extension::sendData(), Extension::setCritical(), Extension::setID(), and Extension::setName().
runner_thread_
std::thread Extension::runner_thread_ private inherited
Referenced by Extension::spawnRunner(), and Extension::stop().
status_
std::atomic<ExtensionStatus> Extension::status_ private inherited
Referenced by Extension::getStatus(), and Extension::setStatus().
id_
int Extension::id_ private inherited
Referenced by Extension::getID(), and Extension::setID().
name_
std::string Extension::name_ private inherited
Referenced by Extension::getName(), Extension::runner(), Extension::setCritical(), Extension::setID(), and Extension::setName().
type_
std::string Extension::type_ private inherited
Referenced by Extension::getType(), and Extension::setType().
category_
ExtensionMetadata::Category Extension::category_ private inherited
Referenced by Extension::getCategory(), and Extension::setCategory().
interface_
ExtensionMetadata::Interface Extension::interface_ private inherited
Referenced by Extension::getInterface(), and Extension::setInterface().
update_interval_
int Extension::update_interval_ private inherited
Referenced by Extension::getUpdateInterval(), and Extension::setUpdateInterval().
critical_
int Extension::critical_ private inherited
Referenced by Extension::getCritical(), and Extension::setCritical().