Giraffe: ServerSocket Class Reference
ServerSocket Class Reference
#include <utility-socket.h>
Public Member Functions
ServerSocket ()
ServerSocket (int port, int non_blocking)
virtual ~ServerSocket ()
void accept (ServerSocket &)
const ServerSocket & operator<< (const std::string &) const
const ServerSocket & operator>> (std::string &) const
Private Member Functions
bool accept (Socket &) const
bool bind (const int port)
bool connect (const std::string host, const int port)
bool create ()
bool is_valid () const
bool listen () const
int recv (std::string &) const
bool send (const std::string) const
void set_non_blocking (const bool)
Private Attributes
sockaddr_in m_addr
int m_sock
Constructor & Destructor Documentation
ServerSocket() [1/2]
ServerSocket::ServerSocket (int port, int non_blocking)
References Socket::bind(), Socket::create(), Socket::listen(), and Socket::set_non_blocking().
ServerSocket() [2/2]
ServerSocket::ServerSocket () inline
~ServerSocket()
ServerSocket::~ServerSocket () virtual
Member Function Documentation
operator<<()
const ServerSocket & ServerSocket::operator<< (const std::string & s) const
References Socket::send().
operator>>()
const ServerSocket & ServerSocket::operator>> (std::string & s) const
References Socket::recv().
accept() [1/2]
void ServerSocket::accept (ServerSocket & sock)
References Socket::accept().
Referenced by ServerModule::runner().
create()
bool Socket::create () inherited
References Socket::is_valid(), and Socket::m_sock.
Referenced by ServerSocket().
bind()
bool Socket::bind (const int port) inherited
References Socket::is_valid(), Socket::m_addr, and Socket::m_sock.
Referenced by ServerSocket().
listen()
bool Socket::listen () const inherited
References Socket::is_valid(), Socket::m_sock, and MAXCONNECTIONS.
Referenced by ServerSocket().
accept() [2/2]
bool Socket::accept (Socket & new_socket) const inherited
References Socket::m_addr, and Socket::m_sock.
Referenced by accept().
connect()
bool Socket::connect (const std::string host, const int port) inherited
References Socket::is_valid(), Socket::m_addr, and Socket::m_sock.
send()
bool Socket::send (const std::string s) const inherited
References Socket::m_sock.
Referenced by operator<<().
recv()
int Socket::recv (std::string & s) const inherited
References Socket::m_sock, and MAXRECV.
Referenced by operator>>().
set_non_blocking()
void Socket::set_non_blocking (const bool b) inherited
References Socket::m_sock.
Referenced by ServerSocket().
is_valid()
bool Socket::is_valid () const inline inherited
References Socket::m_sock.
Referenced by Socket::~Socket(), Socket::bind(), Socket::connect(), Socket::create(), and Socket::listen().
Member Data Documentation
m_sock
int Socket::m_sock private inherited
Referenced by Socket::~Socket(), Socket::accept(), Socket::bind(), Socket::connect(), Socket::create(), Socket::is_valid(), Socket::listen(), Socket::recv(), Socket::send(), and Socket::set_non_blocking().
m_addr
sockaddr_in Socket::m_addr private inherited
Referenced by Socket::Socket(), Socket::accept(), Socket::bind(), and Socket::connect().