Giraffe: TelemetryModule Class Reference
TelemetryModule Class Reference
This class is responsible for handling the radio and transmitting data upon request. Currently only supports PSK.
#include <module-telemetry.h>
Public Member Functions
TelemetryModule (ConfigData config_data, DataStream *data_stream)
Construct a new TelemetryModule object.
~TelemetryModule ()
Destroy the Telemetry Module:: Telemetry Module object.
void sendAFSK (std::string message)
Send a raw AFSK message (callsign is added).
void sendAPRS ()
Pulls data from the data snapshot and then uses the AFSK utility to create an APRS packet.
void sendDataPacket ()
Currently implemented with PSK.
void sendPSK (std::string message)
void sendSSTVImage ()
Adds an SSTV image to the transmit queue. It will use the path of the most recent picture from the data snapshot, along with environmental data.
void start ()
This starts the telemetry module thread.
ModuleStatus status ()
void stop ()
Protected Attributes
std::string error_source_
std::atomic< ModuleStatus > module_status_
Private Member Functions
void addToTXQueue (Transmission transmission)
First checks the transmission for type, and verifies that the wav file actually exists. If both are good, it will acquire a lock on the transmission queue, add the data, then unlock it.
void error (std::string error_code, std::string error_info)
std::string generateAFSK (std::string message)
Takes the callsign, output location, and the message to be encoded. Generates an AX.25 encoded AFSK message that will be split into packets.
std::string generateAPRS ()
std::string generatePSK (std::string message)
std::string generateSSTV ()
int getNextTXNumber ()
Incremented the tx number and returns the new value.
void playWav (std::string wav_location, std::string tx_type, int tx_length)
void runner ()
Private Attributes
FILE * aplay_fp_
std::string call_sign_
ConfigData config_data_
DataStream * p_data_stream_
int psk_length_
std::atomic< int > stop_flag_
int tx_number_
std::thread tx_thread_
Detailed Description
This class is responsible for handling the radio and transmitting data upon request. Currently only supports PSK.
Todo:
Two way communicaiton, AFSK, APRS, etc.
Constructor & Destructor Documentation
TelemetryModule()
TelemetryModule::TelemetryModule (ConfigData config_data, DataStream * data_stream)
Construct a new TelemetryModule object.
Parameters
config_data All configuration data.
data_stream A pointer to the data stream.
References ConfigData::Telemetry::call_sign, call_sign_, config_data_, Module::error_source_, MODULE_TELEMETRY_PREFIX, p_data_stream_, ConfigData::telemetry, and tx_number_.
~TelemetryModule()
TelemetryModule::~TelemetryModule ()
Destroy the Telemetry Module:: Telemetry Module object.
Todo:
implement this in a safe way.
References stop().
Member Function Documentation
start()
void TelemetryModule::start () virtual
This starts the telemetry module thread.
Todo:
not implemented yet.
Reimplemented from Module.
References DataStream::addData(), MODULE_TELEMETRY_PREFIX, p_data_stream_, runner(), stop_flag_, and tx_thread_.
Referenced by FlightRunner::start().
stop()
void TelemetryModule::stop () virtual
Reimplemented from Module.
References Module::module_status_, Module::status(), stop_flag_, STOPPED, and tx_thread_.
Referenced by ~TelemetryModule(), and FlightRunner::deconstruct().
sendDataPacket()
void TelemetryModule::sendDataPacket ()
Currently implemented with PSK.
Parameters
None
Returns
Void
Todo:
implement this.
References addToTXQueue(), call_sign_, generatePSK(), DataStream::getDataFrameCopy(), Transmission::length, p_data_stream_, Transmission::PSK, psk_length_, Transmission::type, and Transmission::wav_location.
Referenced by FlightRunner::flightLoop().
sendAFSK()
void TelemetryModule::sendAFSK (std::string message)
Send a raw AFSK message (callsign is added).
Parameters
message The message to send.
Returns
void
References Transmission::AFSK, generateAFSK(), Transmission::type, and Transmission::wav_location.
sendPSK()
void TelemetryModule::sendPSK (std::string message)
sendAPRS()
void TelemetryModule::sendAPRS ()
Pulls data from the data snapshot and then uses the AFSK utility to create an APRS packet.
Todo:
currently not implemented
References Transmission::APRS, generateAPRS(), DataStream::getDataFrameCopy(), p_data_stream_, Transmission::type, and Transmission::wav_location.
Referenced by FlightRunner::flightLoop().
sendSSTVImage()
void TelemetryModule::sendSSTVImage ()
Adds an SSTV image to the transmit queue. It will use the path of the most recent picture from the data snapshot, along with environmental data.
References Transmission::SSTV, and Transmission::type.
Referenced by FlightRunner::flightLoop().
error()
void TelemetryModule::error (std::string error_code, std::string error_info) private
References DataStream::addError(), Module::error_source_, and p_data_stream_.
Referenced by addToTXQueue(), generatePSK(), and playWav().
getNextTXNumber()
int TelemetryModule::getNextTXNumber () private
Incremented the tx number and returns the new value.
Returns
int
References tx_number_.
Referenced by generatePSK().
addToTXQueue()
void TelemetryModule::addToTXQueue (Transmission transmission) private
First checks the transmission for type, and verifies that the wav file actually exists. If both are good, it will acquire a lock on the transmission queue, add the data, then unlock it.
Parameters
transmission The transmission to add to the queue.
Returns
void
See also
Transmission
Todo:
Fully implement the queue
References DataStream::addError(), DataStream::addToTxQueue(), error(), Transmission::ERROR, p_data_stream_, Transmission::type, and Transmission::wav_location.
Referenced by sendDataPacket().
generateAFSK()
std::string TelemetryModule::generateAFSK (std::string message) private
Takes the callsign, output location, and the message to be encoded. Generates an AX.25 encoded AFSK message that will be split into packets.
Todo:
Not Yet Implemented
Returns
File path to the generated wav file.
Referenced by sendAFSK().
generatePSK()
std::string TelemetryModule::generatePSK (std::string message) private
References PSK::BPSK, config_data_, PSK::encodeTextData(), error(), PSK::getLength(), getNextTXNumber(), psk_length_, ConfigData::Telemetry::psk_mode, ConfigData::Telemetry::psk_symbol_rate, PSK::QPSK, PSK::S125, PSK::S250, PSK::S500, ConfigData::telemetry, and TELEMETRY_WAV_LOCATION.
Referenced by sendDataPacket().
generateAPRS()
std::string TelemetryModule::generateAPRS () private
Referenced by sendAPRS().
generateSSTV()
std::string TelemetryModule::generateSSTV () private
runner()
void TelemetryModule::runner () private
References DataStream::addData(), DataStream::addError(), Transmission::AFSK, Transmission::APRS, Module::error_source_, DataStream::getNextTX(), DataStream::getTXQueueSize(), Transmission::length, Module::module_status_, MODULE_TELEMETRY_PREFIX, p_data_stream_, playWav(), Transmission::PSK, RUNNING, Transmission::SSTV, stop_flag_, TELEMETRY_INTERVAL_MILI_SECONDS, Transmission::type, and Transmission::wav_location.
Referenced by start().
playWav()
void TelemetryModule::playWav (std::string wav_location, std::string tx_type, int tx_length) private
aplay seems to return 0 when it's done playing, 256 when the file doesn't exist, and 2 when it was interrupted (ctrl+c).
This allows me to stop a transmission early if needed and provides time to exit GFS with another ctrl+c.
This is deffinetly a bit of a hack but it gives the functionality that I'm looking for. Eventually this could be replaced with popen or a built in library for playing the wav files. I have had no issues with this so far.
References DataStream::addData(), error(), MODULE_TELEMETRY_PREFIX, and p_data_stream_.
Referenced by runner().
status()
ModuleStatus Module::status () inline inherited
References Module::module_status_.
Referenced by ServerModule::sendDynamicData(), ServerModule::stop(), and stop().
Member Data Documentation
aplay_fp_
FILE* TelemetryModule::aplay_fp_ private
tx_number_
int TelemetryModule::tx_number_ private
Referenced by TelemetryModule(), and getNextTXNumber().
call_sign_
std::string TelemetryModule::call_sign_ private
Referenced by TelemetryModule(), and sendDataPacket().
tx_thread_
std::thread TelemetryModule::tx_thread_ private
Referenced by start(), and stop().
stop_flag_
std::atomic<int> TelemetryModule::stop_flag_ private
Referenced by runner(), start(), and stop().
config_data_
ConfigData TelemetryModule::config_data_ private
Referenced by TelemetryModule(), and generatePSK().
p_data_stream_
DataStream* TelemetryModule::p_data_stream_ private
Referenced by TelemetryModule(), addToTXQueue(), error(), playWav(), runner(), sendAPRS(), sendDataPacket(), and start().
psk_length_
int TelemetryModule::psk_length_ private
Referenced by generatePSK(), and sendDataPacket().
module_status_
std::atomic<ModuleStatus> Module::module_status_ protected inherited
Referenced by DataModule::runner(), ServerModule::runner(), runner(), DataModule::start(), Module::start(), Module::status(), DataModule::stop(), ServerModule::stop(), stop(), and Module::stop().
error_source_
std::string Module::error_source_ protected inherited
Referenced by TelemetryModule(), error(), and runner().