Giraffe: ConfigModule Class Reference
ConfigModule Class Reference
ConfigModule is used to load all of the configuration data from the config file.
#include <module-configuration.h>
Public Member Functions
ConfigModule (DataStream *data_stream)
Construct a new ConfigModule::ConfigModule object.
~ConfigModule ()
Deconstructs the ConfigModule object.
ConfigData getAll ()
Returns all of the configuration data as a ConfigData object. All errors will be included, refer to getErrors() for a list of errors.
json getAllJson ()
Returns a copy of the json data.
int load (std::string filepath)
Load and parse a configuration file from a given path.
Private Member Functions
void error (std::string error_code)
void error (std::string error_code, std::string info)
template<typename T >
void error (std::string error_code, T info)
Simple override for adding errors to the data stream.
void parseAll ()
Calls all of the parse functions to load the configuration data.
void parseDataTypes ()
Parses the data type section of the configuration file.
void parseDebug ()
Parses the debug section of the configuration file.
void parseExtensions ()
Parses the extensions section of the configuration file.
void parseFlightProcedures ()
Parses the flight proc section of the configuration file.
void parseGeneral ()
Parses the general section of the configuration file.
void parseTelemetry ()
Parses the telemetry section of the configuration file.
Private Attributes
ConfigData config_data_
std::string config_file_path_
json json_buffer_
DataStream * p_data_stream_
Detailed Description
ConfigModule is used to load all of the configuration data from the config file.
The configuration is read with Nlohmann JSON and then the data is placed into a common configuration type that is recognized system wide. During parsing, the configuration module will check for errors and will store them in a vector of strings. The errors can be retrieved with the getErrors() function later. If everything was read and parsed correctly, the getErrors() function will return an empty vector.
Basic usage looks like this: ConfigModule config; config.load("path/to/config.json"); config.getErrors(); // check for errors config.getAll(); // get all of the configuration data
Constructor & Destructor Documentation
ConfigModule()
ConfigModule::ConfigModule (DataStream * data_stream)
Construct a new ConfigModule::ConfigModule object.
Parameters
None
References p_data_stream_.
~ConfigModule()
ConfigModule::~ConfigModule ()
Deconstructs the ConfigModule object.
Member Function Documentation
load()
int ConfigModule::load (std::string file_path)
Load and parse a configuration file from a given path.
This function will load and parse a json file from a given path. If the file fails to open or if it does not exists it will return -1. If it does load, it will call parseAll()
Parameters
file_path The local path to the configuration file.
Returns
int 0 if successfully loaded and parsed, -1 if the file failed to open, -2 if there were any errors parsing the file.
See also
parseAll()
References config_file_path_, json_buffer_, and parseAll().
Referenced by FlightRunner::start().
getAll()
ConfigData ConfigModule::getAll ()
Returns all of the configuration data as a ConfigData object. All errors will be included, refer to getErrors() for a list of errors.
Parameters
None
Returns
ConfigData - All of the configuration data.
References config_data_.
Referenced by FlightRunner::start().
getAllJson()
json ConfigModule::getAllJson ()
Returns a copy of the json data.
Parameters
None
Returns
json - nlohmann json object
References json_buffer_.
error() [1/3]
template<typename T > void ConfigModule::error (std::string error_code, T info) private
Simple override for adding errors to the data stream.
Parameters
error_code The error code
info Additional information about the error (optional)
References DataStream::addError(), MODULE_CONFIG_PREFIX, and p_data_stream_.
Referenced by parseExtensions(), and parseGeneral().
error() [2/3]
void ConfigModule::error (std::string error_code, std::string info) private
References DataStream::addError(), MODULE_CONFIG_PREFIX, and p_data_stream_.
error() [3/3]
void ConfigModule::error (std::string error_code) private
References DataStream::addError(), MODULE_CONFIG_PREFIX, and p_data_stream_.
parseAll()
void ConfigModule::parseAll () private
Calls all of the parse functions to load the configuration data.
Parameters
None
Returns
void
References parseDataTypes(), parseDebug(), parseExtensions(), parseFlightProcedures(), parseGeneral(), and parseTelemetry().
Referenced by load().
parseGeneral()
void ConfigModule::parseGeneral () private
Parses the general section of the configuration file.
This function pulls out the project name, mainboard type, and starting proc type. It will add errors to the errors_ vector if any of the required fields contain errors.
Parameters
None
Returns
void
References config_data_, error(), ConfigData::general, json_buffer_, ConfigData::General::main_board, ConfigData::General::project_name, PROJECT_NAME_MAX_LENGTH, PROJECT_NAME_MIN_LENGTH, and ConfigData::General::starting_proc.
Referenced by parseAll().
parseExtensions()
void ConfigModule::parseExtensions () private
Parses the extensions section of the configuration file.
generates a vector of extension metadata objects. It checks for sequential IDs, a name length, extension type, etc.
Parameters
None
Returns
void
Todo:
type does not check for valid types.
additional arguments for i2c, serial, etc. This should be changed into a vector of string arguments to send to the extension as it's most flexible. with all type of extensions.
References ExtensionMetadata::address, ExtensionMetadata::category, config_data_, ExtensionMetadata::critical, error(), ExtensionMetadata::ERROR, EXTENSION_ID_MAX, EXTENSION_INTERVAL_MAX, EXTENSION_INTERVAL_MIN, EXTENSION_NAME_MAX_LENGTH, EXTENSION_NAME_MIN_LENGTH, ExtensionMetadata::extension_type, ConfigData::extensions, ConfigData::Extensions::extensions_list, ExtensionMetadata::I2C, ExtensionMetadata::id, ExtensionMetadata::interface, json_buffer_, ExtensionMetadata::name, ExtensionMetadata::ONEWIRE, ExtensionMetadata::RADIO, and ExtensionMetadata::update_interval.
Referenced by parseAll().
parseDebug()
void ConfigModule::parseDebug () private
Parses the debug section of the configuration file.
Parameters
None
Returns
void
Todo:
Error checking
References config_data_, ConfigData::Debugging::console_enabled, ConfigData::Debugging::console_update_interval, ConfigData::debug, json_buffer_, ConfigData::Debugging::web_server_enabled, and ConfigData::Debugging::web_server_update_interval.
Referenced by parseAll().
parseTelemetry()
void ConfigModule::parseTelemetry () private
Parses the telemetry section of the configuration file.
Currently not fully implemented. It will first check in the config file to see if telemetry is enabled in the config. If it isn't it will immediately return. If it is enabled, it will read in the rest of the telemetry configuration. This is currently not fully implemented and will only read the callsign.
Parameters
None
Returns
void
Todo:
Error Checking
Implement the rest of the telemetry configuration
Todo:
Check if frequency is valid
Todo:
Check if ssid is valid
Todo:
Check if symbol is valid
Todo:
Check if memo is valid
Todo:
Check if frequency is valid
Todo:
Check if frequency is valid
References ConfigData::Telemetry::afsk_enabled, ConfigData::Telemetry::afsk_freq, ConfigData::Telemetry::aprs_enabled, ConfigData::Telemetry::aprs_freq, ConfigData::Telemetry::aprs_memo, ConfigData::Telemetry::aprs_ssid, ConfigData::Telemetry::aprs_symbol, ConfigData::Telemetry::callsign, config_data_, json_buffer_, ConfigData::Telemetry::sstv_enabled, ConfigData::Telemetry::sstv_freq, ConfigData::telemetry, and ConfigData::Telemetry::telemetry_enabled.
Referenced by parseAll().
parseDataTypes()
void ConfigModule::parseDataTypes () private
Parses the data type section of the configuration file.
This will read in the data types from the configuration file. This is what determines if it will be included in telemetry or not. Name is used by the extensions, unit is used by the telemetry and should be a couple characters in length.
Parameters
None
Returns
void
Todo:
Update error checking.
References config_data_, ConfigData::data_types, ConfigData::DataTypes::ExtensionDataType::include_in_telemetry, json_buffer_, ConfigData::DataTypes::ExtensionDataType::name, ConfigData::DataTypes::ExtensionDataType::source, ConfigData::DataTypes::types, and ConfigData::DataTypes::ExtensionDataType::unit.
Referenced by parseAll().
parseFlightProcedures()
void ConfigModule::parseFlightProcedures () private
Parses the flight proc section of the configuration file.
This is the portion that contains the actual tasks of the flight.
Parameters
None
Returns
void
References FlightProcedure::Intervals::aprs, config_data_, FlightProcedure::Intervals::data_log, FlightProcedure::Intervals::data_packet, FlightProcedure::enabled, ConfigData::flight_procs, FlightProcedure::Intervals::health_check, FlightProcedure::intervals, json_buffer_, FlightProcedure::Intervals::picture, ConfigData::Procs::recovery, FlightProcedure::Intervals::sstv, ConfigData::Procs::standard, ConfigData::Procs::testing, and FlightProcedure::type.
Referenced by parseAll().
Member Data Documentation
p_data_stream_
DataStream* ConfigModule::p_data_stream_ private
Referenced by ConfigModule(), and error().
config_file_path_
std::string ConfigModule::config_file_path_ private
Referenced by load().
json_buffer_
json ConfigModule::json_buffer_ private
Referenced by getAllJson(), load(), parseDataTypes(), parseDebug(), parseExtensions(), parseFlightProcedures(), parseGeneral(), and parseTelemetry().
config_data_
ConfigData ConfigModule::config_data_ private
Referenced by getAll(), parseDataTypes(), parseDebug(), parseExtensions(), parseFlightProcedures(), parseGeneral(), and parseTelemetry().