Giraffe: ConsoleModule Class Reference
ConsoleModule Class Reference
This class takes data from a data frame snapshot and prints it out to a simple display in the console.
#include <module-console.h>
Public Member Functions
ConsoleModule (const ConfigData config_data, DataStream *data)
The constructor for the Console Module.
~ConsoleModule ()
The destructor for the Console Module.
void start ()
Starts the console module thread and begins printing data.
ModuleStatus status ()
void stop ()
Sets the stop flag to 1 which will stop the thread, then joins the thread.
Protected Attributes
std::string error_source_
std::atomic< ModuleStatus > module_status_
Private Member Functions
void clearScreen ()
Clears the screen.
void printData ()
Prints formatted data to the console.
void runner ()
The main function for the console module thread.
Private Attributes
ConfigData config_data_
DataStream * data_stream_
std::thread runner_thread_
std::atomic< int > stop_flag_
int update_interval_
Detailed Description
This class takes data from a data frame snapshot and prints it out to a simple display in the console.
Currently runs in it's own thread to prevent any interruptions to the main thread.
Todo:
This class should stop using the data module and use the data stream instead.
Redo all of this with ncurses.
Constructor & Destructor Documentation
ConsoleModule()
ConsoleModule::ConsoleModule (const ConfigData config_data, DataStream * data_stream)
The constructor for the Console Module.
Parameters
config_data The configuration data for the system.
data A pointer to the data module.
Todo:
Use data stream, not data module.
console update interval should be a macro
References config_data_, ConfigData::Debugging::console_update_interval, data_stream_, ConfigData::debug, and update_interval_.
~ConsoleModule()
ConsoleModule::~ConsoleModule ()
The destructor for the Console Module.
References stop().
Member Function Documentation
start()
void ConsoleModule::start () virtual
Starts the console module thread and begins printing data.
Sets the stop flag to 0, and starts the thread which runs the 'runner' function.
Parameters
None
Returns
void
Reimplemented from Module.
References runner(), runner_thread_, and stop_flag_.
Referenced by FlightRunner::start().
stop()
void ConsoleModule::stop () virtual
Sets the stop flag to 1 which will stop the thread, then joins the thread.
Because it joins the thread it can safely be started again after stopping.
Parameters
None
Returns
void
Reimplemented from Module.
References runner_thread_, and stop_flag_.
Referenced by ~ConsoleModule(), and FlightRunner::deconstruct().
runner()
void ConsoleModule::runner () private
The main function for the console module thread.
This function will run until the stop flag is set to 1. It will print the data to the console, and then sleep for the update interval.
Parameters
None
Returns
void
References clearScreen(), printData(), stop_flag_, and update_interval_.
Referenced by start().
clearScreen()
void ConsoleModule::clearScreen () private
Clears the screen.
Parameters
None
Returns
void
Referenced by runner().
printData()
void ConsoleModule::printData () private
Prints formatted data to the console.
This is a bit messy and probably should be redone with ncurses.
Parameters
None
Returns
void
Todo:
Add telemetry data
References ExtensionMetadata::address, ConfigData::Telemetry::afsk_enabled, ConfigData::Telemetry::afsk_freq, FlightProcedure::Intervals::aprs, ConfigData::Telemetry::aprs_enabled, ConfigData::Telemetry::aprs_freq, ConfigData::Telemetry::aprs_key, ConfigData::Telemetry::aprs_memo, ConfigData::Telemetry::aprs_ssid, ConfigData::Telemetry::aprs_symbol, ConfigData::Telemetry::callsign, ExtensionMetadata::category, config_data_, ExtensionMetadata::critical, FlightProcedure::Intervals::data_log, FlightProcedure::Intervals::data_packet, data_stream_, ExtensionMetadata::extension_type, ConfigData::extensions, ConfigData::Extensions::extensions_list, ConfigData::general, DataStream::getDataFrameCopy(), DataStream::getErrorFrameCopy(), DataStream::getFlightProcedureCopy(), DataStream::getNumDataPackets(), DataStream::getNumErrorPackets(), DataStream::getTotalDataPackets(), DataStream::getTotalErrorPackets(), GFS_VERSION, FlightProcedure::Intervals::health_check, ExtensionMetadata::id, ExtensionMetadata::interface, FlightProcedure::intervals, ConfigData::General::main_board, ExtensionMetadata::name, FlightProcedure::Intervals::picture, ConfigData::General::project_name, FlightProcedure::Intervals::sstv, ConfigData::Telemetry::sstv_enabled, ConfigData::Telemetry::sstv_freq, ConfigData::General::starting_proc, ConfigData::telemetry, ConfigData::Telemetry::telemetry_enabled, FlightProcedure::type, and ExtensionMetadata::update_interval.
Referenced by runner().
status()
ModuleStatus Module::status () inline inherited
References Module::module_status_.
Referenced by ServerModule::stop(), and TelemetryModule::stop().
Member Data Documentation
config_data_
ConfigData ConsoleModule::config_data_ private
Referenced by ConsoleModule(), and printData().
data_stream_
DataStream* ConsoleModule::data_stream_ private
Referenced by ConsoleModule(), and printData().
update_interval_
int ConsoleModule::update_interval_ private
Referenced by ConsoleModule(), and runner().
runner_thread_
std::thread ConsoleModule::runner_thread_ private
Referenced by start(), and stop().
stop_flag_
std::atomic<int> ConsoleModule::stop_flag_ private
This flag is an atomic so it can be accessed by both the thread and the main thread. It is set to 1 to signal the thread to stop.
Referenced by runner(), start(), and stop().
module_status_
std::atomic<ModuleStatus> Module::module_status_ protected inherited
Referenced by DataModule::runner(), ServerModule::runner(), DataModule::start(), Module::start(), Module::status(), DataModule::stop(), and Module::stop().
error_source_
std::string Module::error_source_ protected inherited
Referenced by TelemetryModule::TelemetryModule(), and TelemetryModule::runner().