Giraffe: DataModule Class Reference
DataModule Class Reference
The DataModule class is responsible for managing all data between modules. It is responsible for creating safe structures that different concurrently running threads can access. It is in charge of the DataStream. The DataStream is a queue that all of the extensions have access to. They can add data whenever they want. The data module is responsible for collecting this data from the stream and placing it into a data frame which is then sent to the datastream so other modules can access it. This module also continually goes through the DataFrame looking for stale data. If it finds stale data, it will set it's value to 'NO_DATA'. This is an indication of an error within an extension.
#include <module-data.h>
Public Member Functions
DataModule ()
Construct a new DataModule object,.
~DataModule ()
Destroys the DataModule object.
void addConfigData (ConfigData config_data)
DataStream * getDataStream ()
Returns a pointer to the DataStream.
DataFrame getSnapshot ()
void log ()
logs the data in the data frame to the data log file.
void start ()
Starts the DataModule.
ModuleStatus status ()
void stop ()
Stops the DataModule.
Protected Attributes
std::string error_source_
std::atomic< ModuleStatus > module_status_
Private Member Functions
void addDataTypeToFrame (ConfigData::DataTypes::ExtensionDataType data_type)
Adds a data type to the data frame without data.
void checkForStaleData ()
This function checks for state data within the dataframe.
void checkForStaleErrors ()
void parseDataStream ()
Parses data from the DataStream into the DataFrame.
void parseErrorStream ()
Parses the errors from the DataStream into the errorframe.
void runner ()
This is the function that will run in it's own thread. It parses all data and errors automatically.
Private Attributes
std::string data_log_file_path_
DataFrame dataframe_
std::string error_log_file_path_
ErrorFrame errorframe_
DataStream * mpDataStream
std::thread runner_thread_
std::atomic< int > shutdown_signal_
Detailed Description
The DataModule class is responsible for managing all data between modules. It is responsible for creating safe structures that different concurrently running threads can access. It is in charge of the DataStream. The DataStream is a queue that all of the extensions have access to. They can add data whenever they want. The data module is responsible for collecting this data from the stream and placing it into a data frame which is then sent to the datastream so other modules can access it. This module also continually goes through the DataFrame looking for stale data. If it finds stale data, it will set it's value to 'NO_DATA'. This is an indication of an error within an extension.
The DataModule is also responsible for logging the data in the dataframe to a log file when requested to do so.
The DataModule also logs errors which are collected through the datastream in the same way as the data.
The data and error log directories can be set inside of 'utility-configurables.h'.
Constructor & Destructor Documentation
DataModule()
DataModule::DataModule ()
Construct a new DataModule object,.
Initializes the DataStream, opens the log files for data and errors, sets up the data frame. This does not start the module.
Parameters
config_data
References data_log_file_path_, DATA_LOG_LOCATION, error_log_file_path_, ERROR_LOG_LOCATION, and mpDataStream.
~DataModule()
DataModule::~DataModule ()
Destroys the DataModule object.
References mpDataStream.
Member Function Documentation
addConfigData()
void DataModule::addConfigData (ConfigData config_data)
References addDataTypeToFrame(), ConfigData::data_types, and ConfigData::DataTypes::types.
Referenced by FlightRunner::start().
start()
void DataModule::start () virtual
Starts the DataModule.
Starts the thread that parses the DataStream into the DataFrame and logs the data and errors.
Parameters
None
Returns
void
Reimplemented from Module.
References Module::module_status_, runner(), runner_thread_, shutdown_signal_, and STARTING.
Referenced by FlightRunner::start().
stop()
void DataModule::stop () virtual
Stops the DataModule.
Stops the thread that parses the DataStream. Currently not implemented.
Parameters
None
Returns
void
Todo:
Implement this.
Reimplemented from Module.
References Module::module_status_, runner_thread_, shutdown_signal_, and STOPPED.
Referenced by FlightRunner::deconstruct().
getDataStream()
DataStream * DataModule::getDataStream ()
Returns a pointer to the DataStream.
Parameters
None
Returns
DataStream*
References mpDataStream.
Referenced by FlightRunner::start().
getSnapshot()
DataFrame DataModule::getSnapshot ()
log()
void DataModule::log ()
logs the data in the data frame to the data log file.
This function will make a copy of the DataFrame and it will then log it to the data log file.
Parameters
None
Returns
void
References data_log_file_path_, DataStream::getDataFrameCopy(), and mpDataStream.
Referenced by FlightRunner::flightLoop().
addDataTypeToFrame()
void DataModule::addDataTypeToFrame (ConfigData::DataTypes::ExtensionDataType data_type) private
Adds a data type to the data frame without data.
This sets up the data frame so it's ready to receive any data that is sent to it. This is helpful to see what data is missing. Defines the values as "NO_DATA" until they are overwritten. This should be called for each data type at the start of the data module.
Parameters
data_type The actual data type
Returns
void
References dataframe_, DataStreamPacket::expiration_time, ConfigData::DataTypes::ExtensionDataType::source, DataStreamPacket::source, ConfigData::DataTypes::ExtensionDataType::unit, DataStreamPacket::unit, and DataStreamPacket::value.
Referenced by addConfigData().
checkForStaleData()
void DataModule::checkForStaleData () private
This function checks for state data within the dataframe.
This function looks at the expiry time of each item within the data frame and if it has expired it will change it's value to "NO_DATA".
Parameters
None
Returns
void
References dataframe_.
Referenced by runner().
parseDataStream()
void DataModule::parseDataStream () private
Parses data from the DataStream into the DataFrame.
This is called within the runner thread. It will pull all of the packets from the data stream and add them to the dataframe. It will then update the dataframe within the datastream.
Parameters
None
Returns
void
Todo:
Check to see if it exists in the dataframe first, if not add an error.
References dataframe_, DataStream::getNextDataPacket(), DataStream::getNumDataPackets(), mpDataStream, DataStreamPacket::source, DataStreamPacket::unit, and DataStream::updateDataFrame().
Referenced by runner().
checkForStaleErrors()
void DataModule::checkForStaleErrors () private
References errorframe_.
Referenced by runner().
parseErrorStream()
void DataModule::parseErrorStream () private
Parses the errors from the DataStream into the errorframe.
This is called within the runner thread. It will pull all of the errors from the stream and add them to the errorframe. These errors will be removed from the frame after they expire or have been resolved.
Parameters
None
Returns
void
References error_log_file_path_, ErrorStreamPacket::error_name, ErrorStreamPacket::error_source, errorframe_, DataStream::getNextErrorPacket(), DataStream::getNumErrorPackets(), mpDataStream, and DataStream::updateErrorFrame().
Referenced by runner().
runner()
void DataModule::runner () private
This is the function that will run in it's own thread. It parses all data and errors automatically.
This function will parse all of the data and errors from the stream and then it will check for stale errors and data.
Parameters
None
Returns
void
Todo:
Implement the error frame.
References checkForStaleData(), checkForStaleErrors(), MODULE_DATA_FRAME_UPDATE_INTERVAL_MILI_SECONDS, Module::module_status_, parseDataStream(), parseErrorStream(), RUNNING, and shutdown_signal_.
Referenced by start().
status()
ModuleStatus Module::status () inline inherited
References Module::module_status_.
Referenced by ServerModule::stop(), and TelemetryModule::stop().
Member Data Documentation
data_log_file_path_
std::string DataModule::data_log_file_path_ private
Referenced by DataModule(), and log().
error_log_file_path_
std::string DataModule::error_log_file_path_ private
Referenced by DataModule(), and parseErrorStream().
mpDataStream
DataStream* DataModule::mpDataStream private
Referenced by DataModule(), ~DataModule(), getDataStream(), log(), parseDataStream(), and parseErrorStream().
dataframe_
DataFrame DataModule::dataframe_ private
Referenced by addDataTypeToFrame(), checkForStaleData(), and parseDataStream().
errorframe_
ErrorFrame DataModule::errorframe_ private
Referenced by checkForStaleErrors(), and parseErrorStream().
shutdown_signal_
std::atomic<int> DataModule::shutdown_signal_ private
Referenced by runner(), start(), and stop().
runner_thread_
std::thread DataModule::runner_thread_ private
Referenced by start(), and stop().
module_status_
std::atomic<ModuleStatus> Module::module_status_ protected inherited
Referenced by runner(), ServerModule::runner(), start(), Module::start(), Module::status(), stop(), and Module::stop().
error_source_
std::string Module::error_source_ protected inherited
Referenced by TelemetryModule::TelemetryModule(), and TelemetryModule::runner().