Giraffe: FlightRunner Class Reference
FlightRunner Class Reference
The FlightRunner class is responsible for pulling everything together. It manages the timing of each action that is defined in the other files. It is triggered with the start() method and will only return upon program termination.
#include <flight-runner.h>
Public Member Functions
FlightRunner ()
Construct a new Flight Runner object.
FlightRunner (const FlightRunner &)=delete
~FlightRunner ()
Deconstructs the flight runner object, called at program termination; ideally called after shutdown().
FlightRunner & operator= (const FlightRunner &)=delete
void shutdown ()
Sends a shutdown signal to all modules (ExtensionHandler, RadioCommunication, etc). Called by flightLoop().
int start ()
start() initializes the system. start() will perform the following actions:
Private Member Functions
void deconstruct ()
int flightLoop ()
This is where everything actually happens. This is the endless loop that utilizes timers to perform actions. These actions include everything that this software was made to do. Communication, data collection, tracking, etc. It takes in the proc configuration data from start(), creates timers for each action type, performs each action on a user defined timer interval. It will also be responsible for triggering a shutdown when it is commanded to do so. It is capable of switching interval configurations between one flight proc type and another. It will switch either when commanded to or upon the results of a system wide "health check".
void healthCheck ()
This function will switch the flight proc to a different proc type if the values of extensions are within certain ranges.
void switchLoops (FlightProcedure::ProcType procType)
Private Attributes
ConfigData config_data_ = ConfigData()
FlightProcedure::ProcType current_flight_procedure_type_
FlightProcedure::Intervals current_intervals_ = FlightProcedure::Intervals()
DataStream data_stream_ = DataStream()
FlightProcedure flt_proc_descent_ = FlightProcedure(FlightProcedure::ProcType::DESCENT)
FlightProcedure flt_proc_failsafe_ = FlightProcedure(FlightProcedure::ProcType::FAILSAFE)
FlightProcedure flt_proc_recovery_ = FlightProcedure(FlightProcedure::ProcType::RECOVERY)
FlightProcedure flt_proc_standard_ = FlightProcedure(FlightProcedure::ProcType::STANDARD)
FlightProcedure flt_proc_testing_ = FlightProcedure(FlightProcedure::ProcType::TESTING)
modules::ConsoleModule * p_console_module_ = nullptr
modules::DataModule * p_data_module_ = nullptr
modules::ExtensionsModule * p_extension_module_ = nullptr
modules::ServerModule * p_server_module_ = nullptr
modules::TelemetryModule * p_telemetry_module_ = nullptr
int shutdown_signal_
Detailed Description
The FlightRunner class is responsible for pulling everything together. It manages the timing of each action that is defined in the other files. It is triggered with the start() method and will only return upon program termination.
Constructor & Destructor Documentation
FlightRunner() [1/2]
FlightRunner::FlightRunner ()
Construct a new Flight Runner object.
FlightRunner() [2/2]
FlightRunner::FlightRunner (const FlightRunner &) delete
~FlightRunner()
FlightRunner::~FlightRunner ()
Deconstructs the flight runner object, called at program termination; ideally called after shutdown().
See also
shutdown()
Member Function Documentation
operator=()
FlightRunner& FlightRunner::operator= (const FlightRunner &) delete
start()
int FlightRunner::start ()
start() initializes the system. start() will perform the following actions:
Read and parse config file
Start the Data Service
Start the Web Server (if enabled)
Start the Extension Handler
Start the Radio Communication
Perform a system wide test to determine flight proc configuration (standard, failsafe, etc)
Call flightLoop()
Start will only return upon the termination of the flight proc.
Returns
int shutdown signal to main [0 = good shutdown, any other number = bad shutdown]
Todo:
change to hardcoded failsafe
References modules::DataModule::addConfigData(), config_data_, CONFIG_LOCATION, ConfigData::Debugging::console_enabled, data_stream_, ConfigData::debug, flightLoop(), ConfigData::general, modules::ConfigModule::getAll(), healthCheck(), modules::ConfigModule::load(), p_console_module_, p_data_module_, p_extension_module_, p_server_module_, p_telemetry_module_, shutdown_signal_, modules::TelemetryModule::start(), modules::ServerModule::start(), modules::ExtensionsModule::start(), modules::DataModule::start(), modules::ConsoleModule::start(), ConfigData::General::starting_proc, switchLoops(), ConfigData::telemetry, ConfigData::Telemetry::telemetry_enabled, and ConfigData::Debugging::web_server_enabled.
Referenced by main().
shutdown()
void FlightRunner::shutdown ()
Sends a shutdown signal to all modules (ExtensionHandler, RadioCommunication, etc). Called by flightLoop().
Returns
int shutdown signal to main [0 = good shutdown, any other number = bad shutdown]
References shutdown_signal_.
Referenced by flightLoop(), and signalHandler().
flightLoop()
int FlightRunner::flightLoop () private
This is where everything actually happens. This is the endless loop that utilizes timers to perform actions. These actions include everything that this software was made to do. Communication, data collection, tracking, etc. It takes in the proc configuration data from start(), creates timers for each action type, performs each action on a user defined timer interval. It will also be responsible for triggering a shutdown when it is commanded to do so. It is capable of switching interval configurations between one flight proc type and another. It will switch either when commanded to or upon the results of a system wide "health check".
Returns
int shutdown signal [0 = good shutdown, any other number = bad shutdown]
Note
FLIGHT LOOP
References modules::TelemetryModule::addCommand(), FlightProcedure::Intervals::aprs, ConfigData::Telemetry::aprs_enabled, GFSCommand::category, modules::ServerModule::checkShutdown(), config_data_, current_intervals_, FlightProcedure::Intervals::data_log, FlightProcedure::Intervals::data_packet, data_stream_, ConfigData::debug, deconstruct(), Timer::elapsed(), GFSCommand::EXT, GFSCommand::FLR, DataStream::getNextCommand(), modules::DataModule::log(), GFSCommand::MDL, MODULE_SERVER_CHECK_COMMANDS_INTERVAL, p_data_module_, p_server_module_, p_telemetry_module_, ConfigData::Telemetry::psk_enabled, Timer::reset(), modules::TelemetryModule::sendAPRS(), modules::TelemetryModule::sendDataPacket(), modules::TelemetryModule::sendSSTVImage(), shutdown(), shutdown_signal_, FlightProcedure::Intervals::sstv, ConfigData::Telemetry::sstv_enabled, ConfigData::telemetry, ConfigData::Telemetry::telemetry_enabled, GFSCommand::TLM, and ConfigData::Debugging::web_server_enabled.
Referenced by start().
healthCheck()
void FlightRunner::healthCheck () private
This function will switch the flight proc to a different proc type if the values of extensions are within certain ranges.
This function is currently not implemented but it is responsible for switching the flight procs if it's needed. This can be because flight critical components are not working or to switch from standard to recovery.
Parameters
None
Returns
void
Referenced by start().
switchLoops()
void FlightRunner::switchLoops (FlightProcedure::ProcType procType) private
References config_data_, current_intervals_, data_stream_, ConfigData::Procs::failsafe, ConfigData::flight_procs, FlightProcedure::intervals, ConfigData::Procs::testing, FlightProcedure::type, and DataStream::updateFlightProcedure().
Referenced by start().
deconstruct()
void FlightRunner::deconstruct () private
References p_console_module_, p_data_module_, p_extension_module_, p_server_module_, p_telemetry_module_, modules::TelemetryModule::stop(), modules::ServerModule::stop(), modules::ExtensionsModule::stop(), modules::DataModule::stop(), and modules::ConsoleModule::stop().
Referenced by flightLoop().
Member Data Documentation
config_data_
ConfigData FlightRunner::config_data_ = ConfigData() private
Referenced by flightLoop(), start(), and switchLoops().
current_flight_procedure_type_
FlightProcedure::ProcType FlightRunner::current_flight_procedure_type_ private
current_intervals_
FlightProcedure::Intervals FlightRunner::current_intervals_ = FlightProcedure::Intervals() private
Referenced by flightLoop(), and switchLoops().
data_stream_
DataStream FlightRunner::data_stream_ = DataStream() private
Referenced by flightLoop(), start(), and switchLoops().
p_data_module_
modules::DataModule* FlightRunner::p_data_module_ = nullptr private
Referenced by deconstruct(), flightLoop(), and start().
p_extension_module_
modules::ExtensionsModule* FlightRunner::p_extension_module_ = nullptr private
Referenced by deconstruct(), and start().
p_console_module_
modules::ConsoleModule* FlightRunner::p_console_module_ = nullptr private
Referenced by deconstruct(), and start().
p_server_module_
modules::ServerModule* FlightRunner::p_server_module_ = nullptr private
Referenced by deconstruct(), flightLoop(), and start().
p_telemetry_module_
modules::TelemetryModule* FlightRunner::p_telemetry_module_ = nullptr private
Referenced by deconstruct(), flightLoop(), and start().
shutdown_signal_
int FlightRunner::shutdown_signal_ private
Referenced by flightLoop(), shutdown(), and start().
flt_proc_testing_
FlightProcedure FlightRunner::flt_proc_testing_ = FlightProcedure(FlightProcedure::ProcType::TESTING) private
flt_proc_standard_
FlightProcedure FlightRunner::flt_proc_standard_ = FlightProcedure(FlightProcedure::ProcType::STANDARD) private
flt_proc_descent_
FlightProcedure FlightRunner::flt_proc_descent_ = FlightProcedure(FlightProcedure::ProcType::DESCENT) private
flt_proc_recovery_
FlightProcedure FlightRunner::flt_proc_recovery_ = FlightProcedure(FlightProcedure::ProcType::RECOVERY) private
flt_proc_failsafe_
FlightProcedure FlightRunner::flt_proc_failsafe_ = FlightProcedure(FlightProcedure::ProcType::FAILSAFE) private