Giraffe: ServerModule Class Reference
ServerModule Class Reference
#include <module-server.h>
Public Member Functions
ServerModule (const ConfigData config_data, DataStream *data)
~ServerModule ()
int checkShutdown ()
void start ()
ModuleStatus status ()
void stop ()
Protected Attributes
std::string error_source_
std::atomic< ModuleStatus > module_status_
Private Member Functions
void runner ()
void sendDynamicData (ServerSocket &socket)
void sendStaticData (ServerSocket &socket)
Private Attributes
ConfigData config_data_
std::atomic< int > gfs_shutdown_flag_
DataStream * p_data_stream_
std::thread runner_thread_
std::atomic< int > stop_flag_
int update_interval_
Constructor & Destructor Documentation
ServerModule()
ServerModule::ServerModule (const ConfigData config_data, DataStream * data)
References config_data_, ConfigData::debug, gfs_shutdown_flag_, p_data_stream_, update_interval_, and ConfigData::Debugging::web_server_update_interval.
~ServerModule()
ServerModule::~ServerModule ()
References stop().
Member Function Documentation
start()
void ServerModule::start () virtual
Reimplemented from Module.
References runner(), runner_thread_, and stop_flag_.
Referenced by FlightRunner::start().
stop()
void ServerModule::stop () virtual
Reimplemented from Module.
References Module::module_status_, runner_thread_, Module::status(), stop_flag_, and STOPPED.
Referenced by ~ServerModule(), and FlightRunner::deconstruct().
checkShutdown()
int ServerModule::checkShutdown ()
References gfs_shutdown_flag_.
Referenced by FlightRunner::flightLoop().
runner()
void ServerModule::runner () private
References ServerSocket::accept(), DataStream::addData(), DataStream::addError(), SocketException::description(), gfs_shutdown_flag_, MODULE_SERVER_PORT, MODULE_SERVER_PREFIX, Module::module_status_, p_data_stream_, RUNNING, sendDynamicData(), sendStaticData(), stop_flag_, STOPPED, and update_interval_.
Referenced by start().
sendStaticData()
void ServerModule::sendStaticData (ServerSocket & socket) private
References ExtensionMetadata::category, config_data_, ConfigData::Debugging::console_enabled, ExtensionMetadata::critical, ConfigData::debug, ExtensionMetadata::extension_type, ConfigData::extensions, ConfigData::Extensions::extensions_list, ExtensionMetadata::extra_args, ConfigData::general, ExtensionMetadata::I2C, ExtensionMetadata::ExtraArgs::I2C_bus, ExtensionMetadata::ExtraArgs::I2C_device_address, ExtensionMetadata::id, ExtensionMetadata::interface, ConfigData::General::main_board, ExtensionMetadata::name, ExtensionMetadata::ExtraArgs::one_wire_id, ExtensionMetadata::ONEWIRE, ConfigData::General::project_name, ConfigData::General::starting_proc, ConfigData::telemetry, ConfigData::Telemetry::telemetry_enabled, and ExtensionMetadata::update_interval.
Referenced by runner().
sendDynamicData()
void ServerModule::sendDynamicData (ServerSocket & socket) private
References DataStream::addError(), SocketException::description(), ERROR, DataStream::getDataFrameCopy(), DataStream::getExtensionStatuses(), DataStream::getTXQueue(), Transmission::length, DataStream::lockTXQueue(), MODULE_SERVER_PREFIX, p_data_stream_, RUNNING, STARTING, Module::status(), STOPPED, STOPPING, Transmission::type, DataStream::unlockTXQueue(), update_interval_, and Transmission::wav_location.
Referenced by runner().
status()
ModuleStatus Module::status () inline inherited
References Module::module_status_.
Referenced by sendDynamicData(), stop(), and TelemetryModule::stop().
Member Data Documentation
update_interval_
int ServerModule::update_interval_ private
Referenced by ServerModule(), runner(), and sendDynamicData().
config_data_
ConfigData ServerModule::config_data_ private
Referenced by ServerModule(), and sendStaticData().
p_data_stream_
DataStream* ServerModule::p_data_stream_ private
Referenced by ServerModule(), runner(), and sendDynamicData().
runner_thread_
std::thread ServerModule::runner_thread_ private
Referenced by start(), and stop().
stop_flag_
std::atomic<int> ServerModule::stop_flag_ private
This flag is an atomic so it can be accessed by both the thread and the main thread. It is set to 1 to signal the thread to stop.
Referenced by runner(), start(), and stop().
gfs_shutdown_flag_
std::atomic<int> ServerModule::gfs_shutdown_flag_ private
Referenced by ServerModule(), checkShutdown(), and runner().
module_status_
std::atomic<ModuleStatus> Module::module_status_ protected inherited
Referenced by DataModule::runner(), runner(), TelemetryModule::runner(), DataModule::start(), Module::start(), Module::status(), DataModule::stop(), stop(), TelemetryModule::stop(), and Module::stop().
error_source_
std::string Module::error_source_ protected inherited
Referenced by TelemetryModule::TelemetryModule(), TelemetryModule::error(), and TelemetryModule::runner().