Giraffe: PSK Class Reference
PSK Class Reference
#include <utility-psk.h>
Public Types
enum Mode { BPSK , QPSK }
enum SymbolRate {
S31 , S63 , S125 , S250 ,
S500 , S1000
}
Public Member Functions
PSK (std::string file_path, Mode mode, SymbolRate sym_rate)
Construct a PSK Modulator object without morse callsign.
PSK (std::string fuile_path, Mode mode, SymbolRate sym_rate, std::string call_sign)
Construct a PSK Modulator object with morese code callsign added to beginning and end of wav file.
~PSK ()
bool encodeRawData (unsigned char *data, int length)
Encode raw data into PSK audio.
bool encodeTextData (std::string message)
Encode a string of text data into PSK audio data and save to wave file.
int getLength ()
Private Member Functions
void addBits (unsigned char *data, int num_bits)
Adds a bit to the bit stream.
void addCallSign ()
Adds callsign in morse audio form to the wav file.
void addPostamble ()
Adds the postamble to the bit stream. Fldigi seems to use the incorrect postamble in QPSK mode. It uses reapeated 0s instead of 1s. This is a workaround. If you are not using fldigi, set the flag to 0. [https://www.mail-archive.com/fldigi-alpha]@lists.berlios.de/msg01032.html.
void addPreamble ()
Adds the preamble to the bit stream.
void addSymbol (double shift, int next_shift)
Modulates a single symbol in BPSK/QPSK and saves the audio data to the wav file.
void addVaricode (char c)
Converts a char to varicode and adds it to the bitstream.
void encodeBitStream ()
Goes throught he bit stream and modulates with the addSymbol method.
void finalizeFile ()
Updates the 'data segment size' field in the wav header and closes the file.
bool openFile (std::string file_path)
Opens the wav file and writes the header.
int peakNextBit ()
Returns the next bit of the bit stream without removing it.
int popNextBit ()
Returns the next bit of the bit stream that will be encoded.
void pushBufferToBitStream ()
After adding all of the data to the bit stream, this method will write the data left in the buffer to the bit stream. This should be called last.
void setup (Mode mode, SymbolRate baud)
void writeBytes (int data, int size)
Writes the audio data to the wav file.
void writeHeader ()
Writes the header to the wav file, this happens before audio data.
Private Attributes
double angle_delta_
std::vector< uint32_t > bit_stream_
uint32_t bit_stream_buffer_ = 0
int bit_stream_index_ = 0
int bit_stream_offset_ = 0
const int bits_per_sample_ = 16
std::string call_sign_
int carrier_freq_ = 1500
double carrier_wave_angle_ = 0.0f
unsigned char conv_code_buffer_ = 0
int data_start_
std::string file_path_
int last_bit_ = 0
int last_symbol_end_filtered_ = 1
const int max_amplitude_ = pow(2, bits_per_sample_ - 1) - 1
Mode mode_
bool morse_callsign_
const int morse_dah_length_ = 300
const int morse_dit_length_ = 100
const int morse_frequency_ = 600
long int num_samples_ = 0
const int postamble_length_ = 64
const int preamble_length_ = 64
const int sample_rate_ = 44100
int samples_per_symbol_
double symbol_rate_
std::ofstream wav_file_
Member Enumeration Documentation
Mode
enum PSK::Mode
Enumerator
BPSK
QPSK
SymbolRate
enum PSK::SymbolRate
Enumerator
S31
S63
S125
S250
S500
S1000
Constructor & Destructor Documentation
PSK() [1/2]
PSK::PSK (std::string file_path, Mode mode, SymbolRate sym_rate)
Construct a PSK Modulator object without morse callsign.
Parameters
file_path Path to where the wav file will be saved
mode BPSK125, BPSK250, BPSK500, QPSK125, QPSK250, QPSK500
References call_sign_, file_path_, morse_callsign_, and setup().
PSK() [2/2]
PSK::PSK (std::string file_path, Mode mode, SymbolRate sym_rate, std::string call_sign)
Construct a PSK Modulator object with morese code callsign added to beginning and end of wav file.
Parameters
file_path Path to where the wav file will be saved
mode BPSK125, BPSK250, BPSK500, QPSK125, QPSK250, QPSK500
call_sign Callsign - must be at least 4 characters
References call_sign_, file_path_, mode_, morse_callsign_, and setup().
~PSK()
PSK::~PSK ()
Todo:
Member Function Documentation
encodeTextData()
bool PSK::encodeTextData (std::string message)
Encode a string of text data into PSK audio data and save to wave file.
Adds preamble and postamble to the audio data and if a callsign was specified, adds morse code callsign to the beginning and end of the audio.
This method will use varicode with two 0's between each character. If in QPSK mode, it will use the convolutional code.
Parameters
message
Returns
true - Success, you can find the wav file at the file path specified
false - Failure, check the console for more information
References addBits(), addPostamble(), addPreamble(), addVaricode(), encodeBitStream(), file_path_, finalizeFile(), openFile(), pushBufferToBitStream(), and writeHeader().
Referenced by TelemetryModule::generatePSK().
encodeRawData()
bool PSK::encodeRawData (unsigned char * data, int length)
Encode raw data into PSK audio.
Adds preamble and postamble to the audio, and callsign if specified. Does not use varicode or convolutional code! This should only be used if you are manually decoding. You will be forced to use a morse callsign if you use this method. You can of course change this if you want to, but please keep in mind that if you use your own encoding people will not be able to identify your station!
Parameters
data
length
Returns
true
false - Failure, check the console for more information.
References addCallSign(), addPostamble(), addPreamble(), call_sign_, encodeBitStream(), file_path_, finalizeFile(), morse_callsign_, openFile(), and writeHeader().
getLength()
int PSK::getLength ()
References num_samples_, and sample_rate_.
Referenced by TelemetryModule::generatePSK().
setup()
void PSK::setup (Mode mode, SymbolRate symbol_rate) private
Todo:
write docs
Parameters
mode
symbol_rate
References angle_delta_, BPSK, carrier_freq_, mode_, QPSK, S1000, S125, S250, S31, S500, S63, sample_rate_, samples_per_symbol_, and symbol_rate_.
Referenced by PSK().
openFile()
bool PSK::openFile (std::string file_path) private
Opens the wav file and writes the header.
Parameters
file_path
Returns
true - Success
false - Failure
References wav_file_.
Referenced by encodeRawData(), and encodeTextData().
writeHeader()
void PSK::writeHeader () private
Writes the header to the wav file, this happens before audio data.
This method will save the location of the 'data size' field in the header so that it can be updated later after adding data.
References bits_per_sample_, data_start_, sample_rate_, wav_file_, and writeBytes().
Referenced by encodeRawData(), and encodeTextData().
writeBytes()
void PSK::writeBytes (int data, int size) private
Writes the audio data to the wav file.
Parameters
data - int of data to write to wav file
num_bytes - number of bytes to write
References wav_file_.
Referenced by addSymbol(), finalizeFile(), and writeHeader().
finalizeFile()
void PSK::finalizeFile () private
Updates the 'data segment size' field in the wav header and closes the file.
References data_start_, wav_file_, and writeBytes().
Referenced by encodeRawData(), and encodeTextData().
addCallSign()
void PSK::addCallSign () private
Adds callsign in morse audio form to the wav file.
Todo:
implement
Referenced by encodeRawData().
addVaricode()
void PSK::addVaricode (char c) private
Converts a char to varicode and adds it to the bitstream.
Parameters
c char to add to the bistream
References addBits(), and ascii_to_varicode.
Referenced by encodeTextData().
addBits()
void PSK::addBits (unsigned char * data, int num_bits) private
Adds a bit to the bit stream.
see format of 'bit stream' in header file. This function assumes that you're adding bits in order (left to right). So if you want to add 1 you must add 0x80 with a 'num_bits' of 1. All numbers past 'num_bits' must be 0.
Parameters
data
num_bits
References bit_stream_, bit_stream_buffer_, and bit_stream_offset_.
Referenced by addPostamble(), addPreamble(), addVaricode(), and encodeTextData().
pushBufferToBitStream()
void PSK::pushBufferToBitStream () private
After adding all of the data to the bit stream, this method will write the data left in the buffer to the bit stream. This should be called last.
References bit_stream_, bit_stream_buffer_, bit_stream_index_, and bit_stream_offset_.
Referenced by encodeTextData().
addPreamble()
void PSK::addPreamble () private
Adds the preamble to the bit stream.
References addBits(), and preamble_length_.
Referenced by encodeRawData(), and encodeTextData().
addPostamble()
void PSK::addPostamble () private
Adds the postamble to the bit stream. Fldigi seems to use the incorrect postamble in QPSK mode. It uses reapeated 0s instead of 1s. This is a workaround. If you are not using fldigi, set the flag to 0. [https://www.mail-archive.com/fldigi-alpha]@lists.berlios.de/msg01032.html.
References addBits(), bit_stream_offset_, mode_, postamble_length_, and QPSK.
Referenced by encodeRawData(), and encodeTextData().
popNextBit()
int PSK::popNextBit () private
Returns the next bit of the bit stream that will be encoded.
Returns
int [1, 0, -1] -1 = no more bits in bit stream
References bit_stream_, bit_stream_index_, and bit_stream_offset_.
Referenced by encodeBitStream().
peakNextBit()
int PSK::peakNextBit () private
Returns the next bit of the bit stream without removing it.
Returns
int [1, 0, -1] -1 = no more bits in bit stream
References bit_stream_, bit_stream_index_, and bit_stream_offset_.
Referenced by encodeBitStream().
encodeBitStream()
void PSK::encodeBitStream () private
Goes throught he bit stream and modulates with the addSymbol method.
With BPSK31, the bit 0 is encoded by switching phases and the bit 1 is encoded by keeping the phase shift the same.
References addSymbol(), BPSK, conv_code, mode_, peakNextBit(), popNextBit(), and QPSK.
Referenced by encodeRawData(), and encodeTextData().
addSymbol()
void PSK::addSymbol (double shift, int filter_end) private
Modulates a single symbol in BPSK/QPSK and saves the audio data to the wav file.
Parameters
shift The shift of the carrier wave in degrees
filter_end Whether or not to apply the filter to the end of the symbol
References angle_delta_, carrier_wave_angle_, last_symbol_end_filtered_, max_amplitude_, num_samples_, samples_per_symbol_, and writeBytes().
Referenced by encodeBitStream().
Member Data Documentation
morse_frequency_
const int PSK::morse_frequency_ = 600 private
morse_dit_length_
const int PSK::morse_dit_length_ = 100 private
morse_dah_length_
const int PSK::morse_dah_length_ = 300 private
preamble_length_
const int PSK::preamble_length_ = 64 private
Referenced by addPreamble().
postamble_length_
const int PSK::postamble_length_ = 64 private
Referenced by addPostamble().
file_path_
std::string PSK::file_path_ private
Referenced by PSK(), encodeRawData(), and encodeTextData().
mode_
Mode PSK::mode_ private
Referenced by PSK(), addPostamble(), encodeBitStream(), and setup().
morse_callsign_
bool PSK::morse_callsign_ private
Referenced by PSK(), and encodeRawData().
call_sign_
std::string PSK::call_sign_ private
Referenced by PSK(), and encodeRawData().
sample_rate_
const int PSK::sample_rate_ = 44100 private
Referenced by getLength(), setup(), and writeHeader().
bits_per_sample_
const int PSK::bits_per_sample_ = 16 private
Referenced by writeHeader().
max_amplitude_
const int PSK::max_amplitude_ = pow(2, bits_per_sample_ - 1) - 1 private
Referenced by addSymbol().
wav_file_
std::ofstream PSK::wav_file_ private
Referenced by finalizeFile(), openFile(), writeBytes(), and writeHeader().
data_start_
int PSK::data_start_ private
Referenced by finalizeFile(), and writeHeader().
bit_stream_
std::vector<uint32_t> PSK::bit_stream_ private
Bit stream is an array of 32 bit integers. The bits are stored in a 32 bit integer in the following way:
Characters: a a b b c c
varicode with 2x 0 bit padding added to the end of each character: '1011' '00' '1011' '00' '1011111' '00' '1011111' '00' '101111' '00' '101111' '00'
32 bit array: [0](10110010110010111110010111110010) {a, a, b, b, half of c } [1](11110010111100000000000000000000) {other half of c, 0 bits..}
Although this may not be the best way to store the bit stream, it makes it easier to understand.
Referenced by addBits(), peakNextBit(), popNextBit(), and pushBufferToBitStream().
bit_stream_index_
int PSK::bit_stream_index_ = 0 private
Referenced by peakNextBit(), popNextBit(), and pushBufferToBitStream().
bit_stream_buffer_
uint32_t PSK::bit_stream_buffer_ = 0 private
Referenced by addBits(), and pushBufferToBitStream().
bit_stream_offset_
int PSK::bit_stream_offset_ = 0 private
Referenced by addBits(), addPostamble(), peakNextBit(), popNextBit(), and pushBufferToBitStream().
symbol_rate_
double PSK::symbol_rate_ private
Referenced by setup().
carrier_freq_
int PSK::carrier_freq_ = 1500 private
Referenced by setup().
samples_per_symbol_
int PSK::samples_per_symbol_ private
Referenced by addSymbol(), and setup().
carrier_wave_angle_
double PSK::carrier_wave_angle_ = 0.0f private
Referenced by addSymbol().
angle_delta_
double PSK::angle_delta_ private
Referenced by addSymbol(), and setup().
last_symbol_end_filtered_
int PSK::last_symbol_end_filtered_ = 1 private
Referenced by addSymbol().
last_bit_
int PSK::last_bit_ = 0 private
conv_code_buffer_
unsigned char PSK::conv_code_buffer_ = 0 private
num_samples_
long int PSK::num_samples_ = 0 private
Referenced by addSymbol(), and getLength().