Giraffe: BitStream Class Reference
BitStream Class Reference
#include <bit-stream.h>
Public Member Functions
void addBits (unsigned char *data, int num_bits)
void dumpBitStream ()
int getBitStreamLength ()
int peakNextBit ()
Returns the next bit of the bit stream without removing it.
int popNextBit ()
Returns the next bit of the bit stream that will be encoded.
void pushBufferToBitStream ()
After adding all of the data to the bit stream, this method will write the data left in the buffer.
Private Attributes
std::vector< uint32_t > bit_stream_ = std::vector<uint32_t>()
uint32_t bit_stream_buffer_ = 0
int bit_stream_index_ = 0
int bit_stream_length_ = 0
int bit_stream_offset_ = 0
Detailed Description
Bit stream is an array of 32 bit integers. The bits are stored in a 32 bit integer in the following way:
Characters: a a b b c c
varicode with 2x 0 bit padding added to the end of each character: '1011' '00' '1011' '00' '1011111' '00' '1011111' '00' '101111' '00' '101111' '00'
32 bit array: [0](10110010110010111110010111110010) {a, a, b, b, half of c } [1](11110010111100000000000000000000) {other half of c, 0 bits..}
Although this may not be the best way to store the bit stream, it makes it easier to understand.
Todo:
Add support for little endian and big endian.
Member Function Documentation
dumpBitStream()
void BitStream::dumpBitStream ()
References bit_stream_.
addBits()
void BitStream::addBits (unsigned char * data, int num_bits)
References bit_stream_, bit_stream_buffer_, bit_stream_length_, and bit_stream_offset_.
Referenced by addPostamble(), addPreamble(), addVaricode(), AFSK::encodeRawData(), and modulators::PskAscii().
popNextBit()
int BitStream::popNextBit ()
Returns the next bit of the bit stream that will be encoded.
Returns
int [1, 0, -1] -1 = no more bits in bit stream
References bit_stream_, bit_stream_index_, bit_stream_length_, and bit_stream_offset_.
Referenced by AFSK::encodeBitStream(), encodeBpsk(), and encodeQpsk().
peakNextBit()
int BitStream::peakNextBit ()
Returns the next bit of the bit stream without removing it.
Returns
int [1, 0, -1] -1 = no more bits in bit stream
References bit_stream_, bit_stream_index_, and bit_stream_offset_.
Referenced by encodeBpsk().
pushBufferToBitStream()
void BitStream::pushBufferToBitStream ()
After adding all of the data to the bit stream, this method will write the data left in the buffer.
References bit_stream_, bit_stream_buffer_, bit_stream_index_, and bit_stream_offset_.
Referenced by AFSK::encodeRawData(), and modulators::PskAscii().
getBitStreamLength()
int BitStream::getBitStreamLength ()
References bit_stream_length_.
Referenced by AFSK::encodeBitStream().
Member Data Documentation
bit_stream_
std::vector<uint32_t> BitStream::bit_stream_ = std::vector<uint32_t>() private
Referenced by addBits(), dumpBitStream(), peakNextBit(), popNextBit(), and pushBufferToBitStream().
bit_stream_index_
int BitStream::bit_stream_index_ = 0 private
Referenced by peakNextBit(), popNextBit(), and pushBufferToBitStream().
bit_stream_buffer_
uint32_t BitStream::bit_stream_buffer_ = 0 private
Referenced by addBits(), and pushBufferToBitStream().
bit_stream_offset_
int BitStream::bit_stream_offset_ = 0 private
Referenced by addBits(), peakNextBit(), popNextBit(), and pushBufferToBitStream().
bit_stream_length_
int BitStream::bit_stream_length_ = 0 private
Referenced by addBits(), getBitStreamLength(), and popNextBit().