Giraffe: modules::ConsoleModule Class Reference
modules::ConsoleModule Class Reference
This class takes data from a data frame snapshot and prints it out to a simple display in the console.
#include <modules.h>
Public Member Functions
ConsoleModule (const ConfigData config_data, DataStream *data)
The constructor for the Console Module.
ConsoleModule (const ConsoleModule &)=delete
~ConsoleModule ()
The destructor for the Console Module.
ConsoleModule & operator= (const ConsoleModule &)=delete
void start ()
Starts the console module thread and begins printing data.
ModuleStatus status ()
void stop ()
Sets the stop flag to 1 which will stop the thread, then joins the thread.
Protected Member Functions
void data (std::string data_name, int data_value, int second_until_expiry=0)
void data (std::string data_name, std::string data_value, int seconds_until_expiry=0)
void error (std::string error_code)
void error (std::string error_code, std::string info)
void module_sleep (int sleep_time=-1)
std::this_thread::sleep_for() with a default sleep time set by kDefaultSleepTime_.
Protected Attributes
const int kDefaultSleepTime_ = 1000
std::atomic< ModuleStatus > module_status_
Private Member Functions
void clearScreen ()
Clears the screen.
void printData ()
Prints formatted data to the console.
void runner ()
The main function for the console module thread.
Private Attributes
ConfigData config_data_
std::string error_source_
DataStream * p_data_stream_ = nullptr
std::thread runner_thread_ = std::thread()
std::atomic< int > stop_flag_ = 1
int update_interval_ = 10
Detailed Description
This class takes data from a data frame snapshot and prints it out to a simple display in the console.
Currently runs in it's own thread to prevent any interruptions to the main thread.
Todo:
This class should stop using the data module and use the data stream instead.
Redo all of this with ncurses.
Constructor & Destructor Documentation
ConsoleModule() [1/2]
ConsoleModule::ConsoleModule (const ConfigData config_data, DataStream * stream)
The constructor for the Console Module.
Parameters
config_data The configuration data for the system.
data A pointer to the data module.
Todo:
Error on update interval being less than 1
References ConfigData::Debugging::console_update_interval, ConfigData::debug, and update_interval_.
ConsoleModule() [2/2]
modules::ConsoleModule::ConsoleModule (const ConsoleModule &) delete
~ConsoleModule()
ConsoleModule::~ConsoleModule ()
The destructor for the Console Module.
References stop().
Member Function Documentation
operator=()
ConsoleModule& modules::ConsoleModule::operator= (const ConsoleModule &) delete
start()
void ConsoleModule::start () virtual
Starts the console module thread and begins printing data.
Sets the stop flag to 0, and starts the thread which runs the 'runner' function.
Parameters
None
Returns
void
Reimplemented from modules::Module.
References runner(), runner_thread_, and stop_flag_.
Referenced by FlightRunner::start().
stop()
void ConsoleModule::stop () virtual
Sets the stop flag to 1 which will stop the thread, then joins the thread.
Because it joins the thread it can safely be started again after stopping.
Parameters
None
Returns
void
Reimplemented from modules::Module.
References runner_thread_, and stop_flag_.
Referenced by ~ConsoleModule(), and FlightRunner::deconstruct().
runner()
void ConsoleModule::runner () private
The main function for the console module thread.
This function will run until the stop flag is set to 1. It will print the data to the console, and then sleep for the update interval.
Parameters
None
Returns
void
References clearScreen(), printData(), stop_flag_, and update_interval_.
Referenced by start().
clearScreen()
void ConsoleModule::clearScreen () private
Clears the screen.
Parameters
None
Returns
void
Referenced by runner().
printData()
void ConsoleModule::printData () private
Prints formatted data to the console.
This is a bit messy and probably should be redone with ncurses.
Parameters
None
Returns
void
Todo:
Add telemetry data
References ConfigData::Telemetry::afsk_enabled, ConfigData::Telemetry::afsk_freq, FlightProcedure::Intervals::aprs, ConfigData::Telemetry::aprs_enabled, ConfigData::Telemetry::aprs_freq, ConfigData::Telemetry::aprs_key, ConfigData::Telemetry::aprs_memo, ConfigData::Telemetry::aprs_ssid, ConfigData::Telemetry::aprs_symbol, ConfigData::Telemetry::call_sign, config_data_, FlightProcedure::Intervals::data_log, FlightProcedure::Intervals::data_packet, ConfigData::extensions, ConfigData::Extensions::extensions_list, ConfigData::general, DataStream::getDataFrameCopy(), DataStream::getErrorFrameCopy(), DataStream::getFlightProcedureCopy(), DataStream::getNumDataPackets(), DataStream::getNumErrorPackets(), DataStream::getTotalDataPackets(), DataStream::getTotalErrorPackets(), GFS_VERSION, FlightProcedure::Intervals::health_check, FlightProcedure::intervals, ConfigData::General::main_board, p_data_stream_, FlightProcedure::Intervals::picture, ConfigData::General::project_name, FlightProcedure::Intervals::sstv, ConfigData::Telemetry::sstv_enabled, ConfigData::Telemetry::sstv_freq, ConfigData::General::starting_proc, ConfigData::telemetry, ConfigData::Telemetry::telemetry_enabled, and FlightProcedure::type.
Referenced by runner().
status()
ModuleStatus modules::Module::status () inline inherited
References modules::Module::module_status_.
Referenced by modules::ServerModule::sendDynamicData(), modules::TelemetryModule::stop(), modules::ServerModule::stop(), and modules::ExtensionsModule::stop().
error() [1/2]
void modules::Module::error (std::string error_code, std::string info) inline protected inherited
References DataStream::addError(), modules::Module::error_source_, and modules::Module::p_data_stream_.
Referenced by modules::ExtensionsModule::addExtension(), modules::TelemetryModule::addToTXQueue(), modules::TelemetryModule::doCommand(), modules::TelemetryModule::generatePSK(), modules::TelemetryModule::playWav(), modules::TelemetryModule::runner(), modules::ServerModule::runner(), modules::ExtensionsModule::runner(), and modules::ServerModule::sendDynamicData().
error() [2/2]
void modules::Module::error (std::string error_code) inline protected inherited
References DataStream::addError(), modules::Module::error_source_, and modules::Module::p_data_stream_.
data() [1/2]
void modules::Module::data (std::string data_name, std::string data_value, int seconds_until_expiry = 0) inline protected inherited
References DataStream::addData(), modules::Module::error_source_, and modules::Module::p_data_stream_.
Referenced by modules::TelemetryModule::runner(), modules::ServerModule::runner(), modules::ExtensionsModule::runner(), modules::TelemetryModule::sendAPRS(), modules::TelemetryModule::sendDataPacket(), and modules::ServerModule::sendDynamicData().
data() [2/2]
void modules::Module::data (std::string data_name, int data_value, int second_until_expiry = 0) inline protected inherited
References DataStream::addData(), modules::Module::error_source_, and modules::Module::p_data_stream_.
module_sleep()
void modules::Module::module_sleep (int sleep_time = -1) inline protected inherited
std::this_thread::sleep_for() with a default sleep time set by kDefaultSleepTime_.
Parameters
sleep_time Optional, time to sleep in milliseconds.
References modules::Module::kDefaultSleepTime_.
Referenced by modules::ExtensionsModule::runner().
Member Data Documentation
config_data_
ConfigData modules::ConsoleModule::config_data_ private
Referenced by printData().
p_data_stream_
DataStream* modules::ConsoleModule::p_data_stream_ = nullptr private
Referenced by printData().
update_interval_
int modules::ConsoleModule::update_interval_ = 10 private
Referenced by ConsoleModule(), and runner().
runner_thread_
std::thread modules::ConsoleModule::runner_thread_ = std::thread() private
Referenced by start(), and stop().
stop_flag_
std::atomic<int> modules::ConsoleModule::stop_flag_ = 1 private
This flag is an atomic so it can be accessed by both the thread and the main thread. It is set to 1 to signal the thread to stop.
Referenced by runner(), start(), and stop().
kDefaultSleepTime_
const int modules::Module::kDefaultSleepTime_ = 1000 protected inherited
Referenced by modules::Module::module_sleep().
module_status_
std::atomic<ModuleStatus> modules::Module::module_status_ protected inherited
Referenced by modules::TelemetryModule::runner(), modules::ServerModule::runner(), modules::ExtensionsModule::runner(), modules::DataModule::runner(), modules::Module::start(), modules::ExtensionsModule::start(), modules::DataModule::start(), modules::Module::status(), modules::Module::stop(), modules::TelemetryModule::stop(), modules::ServerModule::stop(), modules::ExtensionsModule::stop(), and modules::DataModule::stop().
error_source_
std::string modules::Module::error_source_ private inherited
Referenced by modules::Module::data(), and modules::Module::error().