Giraffe: modules::Module Class Reference
modules::Module Class Reference
All modules used by the FlightRunner inherit this class. This allows for some simplicity when creating small modules.
#include <modules.h>
Public Member Functions
Module (const Module &)=delete
Module (DataStream *p_data_stream, std::string error_prefix)
virtual ~Module ()
Module & operator= (const Module &)=delete
virtual void start ()
ModuleStatus status ()
virtual void stop ()
Protected Member Functions
void data (std::string data_name, int data_value, int second_until_expiry=0)
void data (std::string data_name, std::string data_value, int seconds_until_expiry=0)
void error (std::string error_code)
void error (std::string error_code, std::string info)
void module_sleep (int sleep_time=-1)
std::this_thread::sleep_for() with a default sleep time set by kDefaultSleepTime_.
Protected Attributes
const int kDefaultSleepTime_ = 1000
std::atomic< ModuleStatus > module_status_
DataStream * p_data_stream_
Private Attributes
std::string error_source_
Detailed Description
All modules used by the FlightRunner inherit this class. This allows for some simplicity when creating small modules.
Constructor & Destructor Documentation
Module() [1/2]
modules::Module::Module (DataStream * p_data_stream, std::string error_prefix) inline
References STOPPED.
Module() [2/2]
modules::Module::Module (const Module &) delete
~Module()
virtual modules::Module::~Module () inline virtual
Member Function Documentation
operator=()
Module& modules::Module::operator= (const Module &) delete
status()
ModuleStatus modules::Module::status () inline
References module_status_.
Referenced by modules::ServerModule::sendDynamicData(), modules::TelemetryModule::stop(), modules::ServerModule::stop(), and modules::ExtensionsModule::stop().
start()
virtual void modules::Module::start () inline virtual
Reimplemented in modules::ConsoleModule, modules::DataModule, modules::ExtensionsModule, modules::ServerModule, and modules::TelemetryModule.
References ERROR_STATE, and module_status_.
stop()
virtual void modules::Module::stop () inline virtual
Reimplemented in modules::ConsoleModule, modules::DataModule, modules::ExtensionsModule, modules::ServerModule, and modules::TelemetryModule.
References ERROR_STATE, and module_status_.
error() [1/2]
void modules::Module::error (std::string error_code, std::string info) inline protected
References DataStream::addError(), error_source_, and p_data_stream_.
Referenced by modules::ExtensionsModule::addExtension(), modules::TelemetryModule::addToTXQueue(), modules::TelemetryModule::doCommand(), modules::TelemetryModule::generatePSK(), modules::TelemetryModule::playWav(), modules::TelemetryModule::runner(), modules::ServerModule::runner(), modules::ExtensionsModule::runner(), and modules::ServerModule::sendDynamicData().
error() [2/2]
void modules::Module::error (std::string error_code) inline protected
References DataStream::addError(), error_source_, and p_data_stream_.
data() [1/2]
void modules::Module::data (std::string data_name, std::string data_value, int seconds_until_expiry = 0) inline protected
References DataStream::addData(), error_source_, and p_data_stream_.
Referenced by modules::TelemetryModule::runner(), modules::ServerModule::runner(), modules::ExtensionsModule::runner(), modules::TelemetryModule::sendAPRS(), modules::TelemetryModule::sendDataPacket(), and modules::ServerModule::sendDynamicData().
data() [2/2]
void modules::Module::data (std::string data_name, int data_value, int second_until_expiry = 0) inline protected
References DataStream::addData(), error_source_, and p_data_stream_.
module_sleep()
void modules::Module::module_sleep (int sleep_time = -1) inline protected
std::this_thread::sleep_for() with a default sleep time set by kDefaultSleepTime_.
Parameters
sleep_time Optional, time to sleep in milliseconds.
References kDefaultSleepTime_.
Referenced by modules::ExtensionsModule::runner().
Member Data Documentation
kDefaultSleepTime_
const int modules::Module::kDefaultSleepTime_ = 1000 protected
Referenced by module_sleep().
p_data_stream_
DataStream* modules::Module::p_data_stream_ protected
Referenced by data(), and error().
module_status_
std::atomic<ModuleStatus> modules::Module::module_status_ protected
Referenced by modules::TelemetryModule::runner(), modules::ServerModule::runner(), modules::ExtensionsModule::runner(), modules::DataModule::runner(), start(), modules::ExtensionsModule::start(), modules::DataModule::start(), status(), stop(), modules::TelemetryModule::stop(), modules::ServerModule::stop(), modules::ExtensionsModule::stop(), and modules::DataModule::stop().
error_source_
std::string modules::Module::error_source_ private
Referenced by data(), and error().