Giraffe: modules::ExtensionsModule Class Reference
modules::ExtensionsModule Class Reference
The extension class manages all extensions.
#include <modules.h>
Public Member Functions
ExtensionsModule (const ConfigData config_data, DataStream *stream)
Construct a new ExtensionsModule object.
ExtensionsModule (const ExtensionsModule &other)=delete
~ExtensionsModule ()
Destroys the ExtensionsModule object.
ExtensionsModule & operator= (const ExtensionsModule &other)=delete
void start ()
Starts the ExtensionsModule.
ModuleStatus status ()
void stop ()
Stops all extensions.
Protected Member Functions
void data (std::string data_name, int data_value, int second_until_expiry=0)
void data (std::string data_name, std::string data_value, int seconds_until_expiry=0)
void error (std::string error_code)
void error (std::string error_code, std::string info)
void module_sleep (int sleep_time=-1)
std::this_thread::sleep_for() with a default sleep time set by kDefaultSleepTime_.
Protected Attributes
const int kDefaultSleepTime_ = 1000
std::atomic< ModuleStatus > module_status_
Private Member Functions
void addExtension (ExtensionMetadata meta_data)
This function uses the extension metadata to create an extension of the correct type.
void runner ()
Private Attributes
ConfigData config_data_
std::string error_source_
std::vector< extension::Extension * > extensions_ = {}
DataStream * p_data_stream_
std::thread runner_thread_ = std::thread()
std::atomic< int > stop_flag_ = 0
Detailed Description
The extension class manages all extensions.
This class is responsible for starting, stopping, and managing extensions. This includes all sensors and data collection tools.
Constructor & Destructor Documentation
ExtensionsModule() [1/2]
ExtensionsModule::ExtensionsModule (const ConfigData config_data, DataStream * stream)
Construct a new ExtensionsModule object.
Uses the config_data to create each extension and add it to the extension vector. This does not start the extensions.
Parameters
config_data
stream
References addExtension(), ConfigData::extensions, and ConfigData::Extensions::extensions_list.
ExtensionsModule() [2/2]
modules::ExtensionsModule::ExtensionsModule (const ExtensionsModule & other) delete
~ExtensionsModule()
ExtensionsModule::~ExtensionsModule ()
Destroys the ExtensionsModule object.
References extensions_.
Member Function Documentation
operator=()
ExtensionsModule& modules::ExtensionsModule::operator= (const ExtensionsModule & other) delete
start()
void ExtensionsModule::start () virtual
Starts the ExtensionsModule.
Starts each extension in the extension vector.
Parameters
None
Returns
void
Reimplemented from modules::Module.
References modules::Module::module_status_, runner(), runner_thread_, STARTING, and stop_flag_.
Referenced by FlightRunner::start().
stop()
void ExtensionsModule::stop () virtual
Stops all extensions.
Parameters
None
Returns
void
Reimplemented from modules::Module.
References modules::Module::module_status_, runner_thread_, modules::Module::status(), stop_flag_, and STOPPED.
Referenced by FlightRunner::deconstruct().
runner()
void ExtensionsModule::runner () private
References modules::Module::data(), modules::Module::error(), ERROR, extensions_, modules::Module::module_sleep(), modules::Module::module_status_, RUNNING, STARTING, stop_flag_, STOPPED, STOPPED_ERROR_STATE, and STOPPING.
Referenced by start().
addExtension()
void ExtensionsModule::addExtension (ExtensionMetadata meta_data) private
This function uses the extension metadata to create an extension of the correct type.
Parameters
meta_data The meta_data for one extension.
Returns
void
References modules::Module::error(), ExtensionMetadata::extension_type, extensions_, and p_data_stream_.
Referenced by ExtensionsModule().
status()
ModuleStatus modules::Module::status () inline inherited
References modules::Module::module_status_.
Referenced by modules::ServerModule::sendDynamicData(), modules::TelemetryModule::stop(), modules::ServerModule::stop(), and stop().
error() [1/2]
void modules::Module::error (std::string error_code, std::string info) inline protected inherited
References DataStream::addError(), modules::Module::error_source_, and modules::Module::p_data_stream_.
Referenced by addExtension(), modules::TelemetryModule::addToTXQueue(), modules::TelemetryModule::doCommand(), modules::TelemetryModule::generatePSK(), modules::TelemetryModule::playWav(), modules::TelemetryModule::runner(), modules::ServerModule::runner(), runner(), and modules::ServerModule::sendDynamicData().
error() [2/2]
void modules::Module::error (std::string error_code) inline protected inherited
References DataStream::addError(), modules::Module::error_source_, and modules::Module::p_data_stream_.
data() [1/2]
void modules::Module::data (std::string data_name, std::string data_value, int seconds_until_expiry = 0) inline protected inherited
References DataStream::addData(), modules::Module::error_source_, and modules::Module::p_data_stream_.
Referenced by modules::TelemetryModule::runner(), modules::ServerModule::runner(), runner(), modules::TelemetryModule::sendAPRS(), modules::TelemetryModule::sendDataPacket(), and modules::ServerModule::sendDynamicData().
data() [2/2]
void modules::Module::data (std::string data_name, int data_value, int second_until_expiry = 0) inline protected inherited
References DataStream::addData(), modules::Module::error_source_, and modules::Module::p_data_stream_.
module_sleep()
void modules::Module::module_sleep (int sleep_time = -1) inline protected inherited
std::this_thread::sleep_for() with a default sleep time set by kDefaultSleepTime_.
Parameters
sleep_time Optional, time to sleep in milliseconds.
References modules::Module::kDefaultSleepTime_.
Referenced by runner().
Member Data Documentation
runner_thread_
std::thread modules::ExtensionsModule::runner_thread_ = std::thread() private
Referenced by start(), and stop().
stop_flag_
std::atomic<int> modules::ExtensionsModule::stop_flag_ = 0 private
Referenced by runner(), start(), and stop().
extensions_
std::vector<extension::Extension*> modules::ExtensionsModule::extensions_ = {} private
Referenced by ~ExtensionsModule(), addExtension(), and runner().
p_data_stream_
DataStream* modules::ExtensionsModule::p_data_stream_ private
Referenced by addExtension().
config_data_
ConfigData modules::ExtensionsModule::config_data_ private
kDefaultSleepTime_
const int modules::Module::kDefaultSleepTime_ = 1000 protected inherited
Referenced by modules::Module::module_sleep().
module_status_
std::atomic<ModuleStatus> modules::Module::module_status_ protected inherited
Referenced by modules::TelemetryModule::runner(), modules::ServerModule::runner(), runner(), modules::DataModule::runner(), modules::Module::start(), start(), modules::DataModule::start(), modules::Module::status(), modules::Module::stop(), modules::TelemetryModule::stop(), modules::ServerModule::stop(), stop(), and modules::DataModule::stop().
error_source_
std::string modules::Module::error_source_ private inherited
Referenced by modules::Module::data(), and modules::Module::error().