Giraffe: extension::BMP180 Class Reference
extension::BMP180 Class Reference
BMP180 sensor extension.
#include <extensions.h>
Public Member Functions
BMP180 (DataStream *p_data_stream, ExtensionMetadata extension_metadata)
~BMP180 ()
ExtensionMetadata::Category getCategory ()
int getCritical ()
int getID ()
ExtensionMetadata::Interface getInterface ()
std::string getName ()
ExtensionStatus getStatus ()
std::string getType ()
int getUpdateInterval ()
void restart ()
Not implemented.
int runner ()
This must be overridden by each extension.
void start ()
Starts the extension thread if it is stopped, changes status.
void stop ()
Signals the thread to stop.
Public Attributes
std::atomic< int > restart_attempts_ = 0
Protected Member Functions
void error (std::string error_code)
void error (std::string error_code, std::string info)
void sendData (std::string unit, float value, int precision=1)
Override for floats. See sendData(std::string, std::string).
void sendData (std::string unit, int value)
Override for integers. See sendData(std::string, std::string).
void sendData (std::string unit, std::string value)
Sends data to the data stream.
void setStatus (ExtensionStatus status)
Sets the status. Thread safe.
Protected Attributes
int data_expiration_time_ = 1000
std::atomic< int > stop_flag_ = 1
Private Member Functions
int calculatePressure ()
int calculateTemperature ()
int handshake ()
int readCalibrationData ()
int readRawPressure ()
int readRawTemperature ()
short readShort (int registerAddress)
unsigned short readShortUnsigned (int registerAddress)
void setCategory (ExtensionMetadata::Category category)
Sets the category of the extension, does not do any error checking.
void setCritical (int critical)
Sets the critical flag of the extension 1=yes, 0=no.
void setExtraArgs (std::vector< std::string > extra_args)
void setID (int num)
Sets the ID of the extension, reports errors to the data stream.
void setInterface (ExtensionMetadata::Interface interface)
Sets the interface of the extension that will be used for device communication.
void setName (std::string name)
Sets the name of the extension, reports errors to the data stream.
void setType (std::string type)
Sets the type of the extension.
void setUpdateInterval (int interval)
Sets the update interval of the extension.
virtual void spawnRunner ()
This function will attempt to spawn the runner thread of the parent class.
Private Attributes
volatile short AC1_ = 0
volatile short AC2_ = 0
volatile short AC3_ = 0
volatile unsigned short AC4_ = 0
volatile unsigned short AC5_ = 0
volatile unsigned short AC6_ = 0
volatile short B1_ = 0
volatile short B2_ = 0
int B3_ = 0
unsigned int B4_ = 0
int B5_ = 0
int B6_ = 0
int B7_ = 0
int bus_number_
ExtensionMetadata::Category category_ = ExtensionMetadata::Category::ERROR
int critical_ = 0
int device_address_
I2C i2c_bus_
int id_ = 0
ExtensionMetadata::Interface interface_ = ExtensionMetadata::Interface::ERROR
volatile short MB_ = 0
volatile short MC_ = 0
volatile short MD_ = 0
std::string name_ = ""
int P_ = 0
DataStream *const p_data_stream_
float pressure_altitude_feet_ = 0.0
float pressure_altitude_meters_ = 0.0
float pressure_HPA_ = 0.0
float pressure_INHG_ = 0.0
std::unordered_map< std::string, int > raw_data_ = {}
int raw_pressure_data_ = 0
int raw_temperature_data_ = 0
std::thread runner_thread_ = std::thread()
std::atomic< ExtensionStatus > status_
int T_ = 0
float temp_C_ = 0.0
float temp_F_ = 0.0
std::string type_ = ""
int UP_ = 0
int update_interval_ = 0
int UT_ = 0
int X1_ = 0
int X2_ = 0
int X3_ = 0
Detailed Description
BMP180 sensor extension.
Constructor & Destructor Documentation
BMP180()
extension::BMP180::BMP180 (DataStream * p_data_stream, ExtensionMetadata extension_metadata)
~BMP180()
extension::BMP180::~BMP180 ()
Member Function Documentation
runner()
int extension::BMP180::runner () virtual
This must be overridden by each extension.
This function is called by by spawnRunner() to start the thread. The runner belongs to each extension so the base class runner should never be called. The runner function override should contain an endless loop that generates data for the data stream. It should only continue the loop at a rate that is equal to 'update_interval_'. The runner must also check to see if the status is 'stopping', if it is it must shutdown and return 0. If this function is not overridden, it will add an error to the data stream and return -1.
Returns
int -1, an error value. 0 is for a clean stop.
Reimplemented from extension::Extension.
References ADDRESS_ERROR, BMP180_DEBUG, BUS_ERROR, CONFIG_ERROR_ADDRESS, CONFIG_ERROR_BUS, ERROR, OK, RUNNING, and STOPPED.
readCalibrationData()
int extension::BMP180::readCalibrationData () private
References BMP180_DEBUG, REG_CAL_AC1, REG_CAL_AC2, REG_CAL_AC3, REG_CAL_AC4, REG_CAL_AC5, REG_CAL_AC6, REG_CAL_B1, REG_CAL_B2, REG_CAL_MB, REG_CAL_MC, and REG_CAL_MD.
readRawTemperature()
int extension::BMP180::readRawTemperature () private
References BMP180_DEBUG, CMD_READTEMP, REG_CTRL, and REG_DATA.
readRawPressure()
int extension::BMP180::readRawPressure () private
References BMP180_DEBUG, CMD_READPRES, REG_CTRL, REG_DATA, and SAMPLING_ACCURACY.
calculateTemperature()
int extension::BMP180::calculateTemperature () private
Todo:
POSSIBLE ARITHMETIC ERRORS
calculatePressure()
int extension::BMP180::calculatePressure () private
References SAMPLING_ACCURACY.
readShortUnsigned()
unsigned short extension::BMP180::readShortUnsigned (int registerAddress) private
readShort()
short extension::BMP180::readShort (int registerAddress) private
handshake()
int extension::BMP180::handshake () private
References REG_ID.
start()
void extension::Extension::start () inherited
Starts the extension thread if it is stopped, changes status.
This function attempts to start the extension thread with spawnRunner(). This will change the status to 'STARTING'. The thread is responsible for the later change to 'RUNNING' or 'ERROR'.
Parameters
None
Returns
void
References STARTING, and STOPPED.
stop()
void extension::Extension::stop () inherited
Signals the thread to stop.
Sets the status to 'STOPPING' which signals the thread to stop. The thread is responsible for the later change to 'STOPPED' or 'ERROR'. This function does not wait for the thread to stop, it only changes the status. This functionality needs to be implemented in each extension's runner() method.
Todo:
Implement thread joining.
Parameters
None
Returns
void
References ERROR, RUNNING, STOPPED_ERROR_STATE, and STOPPING.
restart()
void extension::Extension::restart () inherited
Not implemented.
Restarts the extension thread and sets the status based on the result.
Todo:
Implement this.
getStatus()
ExtensionStatus extension::Extension::getStatus () inherited
Returns
ExtensionStatus The status of the extension. Status is an atomic, so it is thread safe.
getID()
int extension::Extension::getID () inherited
Returns
int The id of the extension.
getName()
std::string extension::Extension::getName () inherited
Returns
std::string The name of the extension.
getType()
std::string extension::Extension::getType () inherited
Returns
std::string The type of the extension.
getCategory()
ExtensionMetadata::Category extension::Extension::getCategory () inherited
Returns
ExtensionMetadata::Category The category of the extension.
getInterface()
ExtensionMetadata::Interface extension::Extension::getInterface () inherited
Returns
ExtensionMetadata::Interface The interface of the extension.
getUpdateInterval()
int extension::Extension::getUpdateInterval () inherited
Returns
int The update interval in milliseconds of the extension.
getCritical()
int extension::Extension::getCritical () inherited
Returns
int Whether or not the extension is flight critical 0=no, 1=yes.
setStatus()
void extension::Extension::setStatus (ExtensionStatus status) protected inherited
Sets the status. Thread safe.
Sets the status, no error checking is done. The status member is protected as a std::atomic<> so it is thread safe. This is called within the base class and parent class.
Parameters
status
Referenced by extension::Extension::Extension().
sendData() [1/3]
void extension::Extension::sendData (std::string unit, std::string value) protected inherited
Sends data to the data stream.
This function is used to send data from the extension to the data stream. It is a wrapper for the DataStream::addData() function. It fills in the extension name and the valid time in seconds which is defined as 'getUpdateInterval() / 1000'.
Bug:
This function does not take into account the time it may take an extension to collect it's data. Also send data could possibly be put into a template.
Parameters
std::string unit - The unit of the data. Example "TF" for temperature in fahrenheit. This is defined in the configuration.
std::string value
int value
float value
Returns
void
sendData() [2/3]
void extension::Extension::sendData (std::string unit, int value) protected inherited
Override for integers. See sendData(std::string, std::string).
Todo:
Limit number size?
sendData() [3/3]
void extension::Extension::sendData (std::string unit, float value, int precision = 1) protected inherited
Override for floats. See sendData(std::string, std::string).
Todo:
Limit to float precision?
error() [1/2]
void extension::Extension::error (std::string error_code, std::string info) protected inherited
References EXTENSION_PREFIX.
error() [2/2]
void extension::Extension::error (std::string error_code) protected inherited
References EXTENSION_PREFIX.
setID()
void extension::Extension::setID (int num) private inherited
Sets the ID of the extension, reports errors to the data stream.
This does not check for duplicates.
Parameters
num The id
Returns
void
References ERROR, EXTENSION_ID_MAX, and EXTENSION_ID_MIN.
Referenced by extension::Extension::Extension().
setName()
void extension::Extension::setName (std::string name) private inherited
Sets the name of the extension, reports errors to the data stream.
Uses the extension max length and min length macros to validate the name. If the name is invalid, the status is set to ERROR, name is set to "NAME_ERROR" and the error is reported to the data stream. This error should be caught by the configuration module before it gets here.
Todo:
Add a check for valid characters (Is there a standard yet?).
Parameters
name The name of the extension.
Returns
void
References ERROR, EXTENSION_NAME_MAX_LENGTH, and EXTENSION_NAME_MIN_LENGTH.
Referenced by extension::Extension::Extension().
setType()
void extension::Extension::setType (std::string type) private inherited
Sets the type of the extension.
Does not do any error checking.
Todo:
Add length and character checking.
Parameters
type
Returns
void
Referenced by extension::Extension::Extension().
setCategory()
void extension::Extension::setCategory (ExtensionMetadata::Category category) private inherited
Sets the category of the extension, does not do any error checking.
Parameters
category
Returns
void
Referenced by extension::Extension::Extension().
setInterface()
void extension::Extension::setInterface (ExtensionMetadata::Interface interface) private inherited
Sets the interface of the extension that will be used for device communication.
Parameters
interface
Returns
void
Todo:
Add extra args handling here if for interface. Ex: i2c bus and address.
Referenced by extension::Extension::Extension().
setUpdateInterval()
void extension::Extension::setUpdateInterval (int interval_ms) private inherited
Sets the update interval of the extension.
Currently does not do any error checking.
Todo:
Add range checking.
Parameters
interval The update interval in milliseconds, 0 means the thread will return after a single run.
Referenced by extension::Extension::Extension().
setCritical()
void extension::Extension::setCritical (int critical) private inherited
Sets the critical flag of the extension 1=yes, 0=no.
If the extension is flight critical and the status is 'ERROR' then the system should attempt to recover. This is/will be implemented in the health_check() function.
See also
health_check()
Parameters
critical 1=yes, 0=no.
Referenced by extension::Extension::Extension().
setExtraArgs()
void extension::Extension::setExtraArgs (std::vector< std::string > extra_args) private inherited
spawnRunner()
void extension::Extension::spawnRunner () private virtual inherited
This function will attempt to spawn the runner thread of the parent class.
Todo:
Implement this.
References extension::Extension::runner().
Member Data Documentation
bus_number_
int extension::BMP180::bus_number_ private
device_address_
int extension::BMP180::device_address_ private
i2c_bus_
I2C extension::BMP180::i2c_bus_ private
temp_F_
float extension::BMP180::temp_F_ = 0.0 private
temp_C_
float extension::BMP180::temp_C_ = 0.0 private
pressure_HPA_
float extension::BMP180::pressure_HPA_ = 0.0 private
pressure_INHG_
float extension::BMP180::pressure_INHG_ = 0.0 private
pressure_altitude_meters_
float extension::BMP180::pressure_altitude_meters_ = 0.0 private
pressure_altitude_feet_
float extension::BMP180::pressure_altitude_feet_ = 0.0 private
raw_data_
std::unordered_map<std::string, int> extension::BMP180::raw_data_ = {} private
raw_temperature_data_
int extension::BMP180::raw_temperature_data_ = 0 private
raw_pressure_data_
int extension::BMP180::raw_pressure_data_ = 0 private
AC1_
volatile short extension::BMP180::AC1_ = 0 private
AC2_
volatile short extension::BMP180::AC2_ = 0 private
AC3_
volatile short extension::BMP180::AC3_ = 0 private
AC4_
volatile unsigned short extension::BMP180::AC4_ = 0 private
AC5_
volatile unsigned short extension::BMP180::AC5_ = 0 private
AC6_
volatile unsigned short extension::BMP180::AC6_ = 0 private
B1_
volatile short extension::BMP180::B1_ = 0 private
B2_
volatile short extension::BMP180::B2_ = 0 private
MB_
volatile short extension::BMP180::MB_ = 0 private
MC_
volatile short extension::BMP180::MC_ = 0 private
MD_
volatile short extension::BMP180::MD_ = 0 private
UT_
int extension::BMP180::UT_ = 0 private
UP_
int extension::BMP180::UP_ = 0 private
X1_
int extension::BMP180::X1_ = 0 private
X2_
int extension::BMP180::X2_ = 0 private
X3_
int extension::BMP180::X3_ = 0 private
B3_
int extension::BMP180::B3_ = 0 private
B4_
unsigned int extension::BMP180::B4_ = 0 private
B5_
int extension::BMP180::B5_ = 0 private
B6_
int extension::BMP180::B6_ = 0 private
B7_
int extension::BMP180::B7_ = 0 private
T_
int extension::BMP180::T_ = 0 private
P_
int extension::BMP180::P_ = 0 private
restart_attempts_
std::atomic<int> extension::Extension::restart_attempts_ = 0 inherited
stop_flag_
std::atomic<int> extension::Extension::stop_flag_ = 1 protected inherited
data_expiration_time_
int extension::Extension::data_expiration_time_ = 1000 protected inherited
p_data_stream_
DataStream* const extension::Extension::p_data_stream_ private inherited
runner_thread_
std::thread extension::Extension::runner_thread_ = std::thread() private inherited
status_
std::atomic<ExtensionStatus> extension::Extension::status_ private inherited
id_
int extension::Extension::id_ = 0 private inherited
name_
std::string extension::Extension::name_ = "" private inherited
type_
std::string extension::Extension::type_ = "" private inherited
category_
ExtensionMetadata::Category extension::Extension::category_ = ExtensionMetadata::Category::ERROR private inherited
interface_
ExtensionMetadata::Interface extension::Extension::interface_ = ExtensionMetadata::Interface::ERROR private inherited
update_interval_
int extension::Extension::update_interval_ = 0 private inherited
critical_
int extension::Extension::critical_ = 0 private inherited