Giraffe: main.cpp File Reference
main.cpp File Reference
Defines the entry point/main function of the Flight Computer software.
#include <csignal>
#include "flight-runner.h"
Functions
int main (void)
This is the main function that starts the flight runner. It will return a call to flight.start() which will not return until the flight computer either shuts down or experiences an error.
void signalHandler (int signal_number)
Variables
FlightRunner flight
Detailed Description
Defines the entry point/main function of the Flight Computer software.
Author
Joshua Jerred (github.com/joshua-jerred)
Version
0.1
Date
2022-09-20
Copyright
Copyright (c) 2022
Function Documentation
signalHandler()
void signalHandler (int signal_number)
References flight, and FlightRunner::shutdown().
Referenced by main().
main()
int main (void)
This is the main function that starts the flight runner. It will return a call to flight.start() which will not return until the flight computer either shuts down or experiences an error.
Returns
int - The exit status of the flight runner 0, any other value indicates an error.
Todo:
update docs
Bug:
FlightRunner currently only returns 0.
References flight, signalHandler(), and FlightRunner::start().
Variable Documentation
flight
FlightRunner flight
Referenced by main(), and signalHandler().