Giraffe: modulators Namespace Reference
modulators Namespace Reference
Enumerations
enum class PskMode { BPSK , QPSK }
enum class PskSymbolRate { S125 , S250 , S500 , S1000 }
Functions
bool AfskAscii (WavGen &wavgen, const std::string &message)
bool Morse (WavGen &wavgen, std::string callsign)
bool PskAscii (WavGen &wavgen, const std::string &message, const PskMode &mode, const PskSymbolRate &sym_rate)
Enumeration Type Documentation
PskMode
enum modulators::PskMode strong
Enumerator
BPSK
QPSK
PskSymbolRate
enum modulators::PskSymbolRate strong
Enumerator
S125
S250
S500
S1000
Function Documentation
Morse()
bool modulators::Morse (WavGen & wavgen, std::string callsign)
References WavGen::addSineWave(), AUDIO_AMP, AUDIO_FREQ, DASH_LENGTH, DOT_LENGTH, LETTER_SPACE_LENGTH, MorseChar::morse, morse_chars, and TIME_BETWEEN_SYMBOLS.
Referenced by MWAVData::encode().
PskAscii()
bool modulators::PskAscii (WavGen & wavgen, const std::string & message, const PskMode & mode, const PskSymbolRate & sym_rate)
References BitStream::addBits(), addPostamble(), addPreamble(), addVaricode(), PskWave::angle_delta, BPSK, PskWave::carrier_wave_angle, encodeBpsk(), encodeQpsk(), PskWave::last_symbol_end_filtered, M_PI, BitStream::pushBufferToBitStream(), QPSK, PskWave::samples_per_symbol, and SymbolRate().
Referenced by addPSK().
AfskAscii()
bool modulators::AfskAscii (WavGen & wavgen, const std::string & message)
References AFSK::encodeAscii().
Referenced by MWAVData::encode().