Giraffe: MWAVData Namespace Reference
MWAVData Namespace Reference
Enumerations
enum class MODE { ASCII = 0 , RAW_BIN = 1 }
enum class MODULATION {
BPSK_125 , BPSK_250 , BPSK_500 , BPSK_1000 ,
QPSK_125 , QPSK_250 , QPSK_500 , AFSK1200
}
Functions
bool encode (const MODULATION modulation, const std::string input, const std::string out_file_path)
Encode a string of data into a WAV file, without a morse code callsign. ASCII Input only.
bool encode (const MWAVData::MODULATION modulation, const std::string input, const std::string out_file_path, const std::string callsign)
Encode a string of data into a WAV file, with a morse code callsign. ASCII Input only.
bool encode (const MWAVData::MODULATION modulation, const unsigned char *input, const int input_length, const std::string out_file_path)
Encode raw binary data without a morse code callsign.
Enumeration Type Documentation
MODE
enum MWAVData::MODE strong
Enumerator
ASCII
RAW_BIN
MODULATION
enum MWAVData::MODULATION strong
Enumerator
BPSK_125
BPSK_250
BPSK_500
BPSK_1000
QPSK_125
QPSK_250
QPSK_500
AFSK1200
Function Documentation
encode() [1/3]
bool MWAVData::encode (const MODULATION modulation, const std::string input, const std::string out_file_path)
Encode a string of data into a WAV file, without a morse code callsign. ASCII Input only.
Parameters
modulation The modulation to use for the data, see MWAVData::MODULATION
input The string to encode
out_file_path The path to the output WAV file to create
Returns
true if the WAV file was created successfully
false if the WAV file could not be created
References addPSK(), and modulators::AfskAscii().
Referenced by modules::TelemetryModule::generatePSK().
encode() [2/3]
bool MWAVData::encode (const MWAVData::MODULATION modulation, const std::string input, const std::string out_file_path, const std::string callsign)
Encode a string of data into a WAV file, with a morse code callsign. ASCII Input only.
Parameters
modulation The modulation to use for the data, see MWAVData::MODULATION
input The string to encode
out_file_path The path to the output WAV file to create
callsign The callsign to encode in morse code
Returns
true if the WAV file was created successfully
false if the WAV file could not be created
References addPSK(), WavGen::addSineWave(), and modulators::Morse().
encode() [3/3]
bool MWAVData::encode (const MWAVData::MODULATION modulation, const unsigned char * input, const int input_length, const std::string out_file_path)
Encode raw binary data without a morse code callsign.
Parameters
modulation
input Raw binary data to encode
input_length Number of bytes in the input buffer
out_file_path The path to the output WAV file to create
Returns
true if the WAV file was created successfully
false if the WAV file could not be created