Giraffe: ex_internal Namespace Reference
ex_internal Namespace Reference
Classes
struct cpu_mem_info
struct disk_info
Functions
bool getCpuAndMemInfo (cpu_mem_info &info)
int getCpuTemp ()
bool getDiskInfo (disk_info &info)
Class Documentation
ex_internal::cpu_mem_info
struct ex_internal::cpu_mem_info
Class Members
float uptime_hours
float cpu_load_avg_1
float cpu_load_avg_5
float cpu_load_avg_15
float ram_total_gb
float ram_used_percent
float ram_free_gb
ex_internal::disk_info
struct ex_internal::disk_info
Class Members
float total_gb
float free_space_gb
float used_percent
Function Documentation
getCpuAndMemInfo()
bool ex_internal::getCpuAndMemInfo (cpu_mem_info & info)
References ex_internal::cpu_mem_info::cpu_load_avg_1, ex_internal::cpu_mem_info::cpu_load_avg_15, ex_internal::cpu_mem_info::cpu_load_avg_5, ex_internal::cpu_mem_info::ram_free_gb, ex_internal::cpu_mem_info::ram_total_gb, ex_internal::cpu_mem_info::ram_used_percent, and ex_internal::cpu_mem_info::uptime_hours.
Referenced by extension::SYSINFO::runner().
getCpuTemp()
int ex_internal::getCpuTemp ()
Referenced by extension::SYSINFO::runner().
getDiskInfo()
bool ex_internal::getDiskInfo (disk_info & info)
References ex_internal::disk_info::free_space_gb, ex_internal::disk_info::total_gb, and ex_internal::disk_info::used_percent.
Referenced by extension::SYSINFO::runner().