Giraffe: psk.cpp File Reference
psk.cpp File Reference
See https://github.com/joshua-jerred/MWAV.
#include <cmath>
#include "modulators.h"
#include "convolutional-code.h"
#include "varicode.h"
#include "bit-stream.h"
Classes
struct PskWave
Functions
void addPostamble (BitStream &bit_stream, int postamble_length, PskMode mode)
void addPreamble (BitStream &bit_stream, int preamble_length)
void addSymbol (WavGen &wavgen, PskWave &wave, double shift, int filter_end)
void addVaricode (BitStream &bit_stream, char c)
void encodeBpsk (WavGen &wavgen, BitStream &bit_stream, PskWave &wave)
void encodeQpsk (WavGen &wavgen, BitStream &bit_stream, PskWave &wave)
double SymbolRate (PskSymbolRate rate)
Detailed Description
See https://github.com/joshua-jerred/MWAV.
Author
Joshua Jerred (https://joshuajer.red)
Date
2022-12-30
Copyright
Copyright (c) 2022
Version
0.1
Class Documentation
PskWave
struct PskWave
Class Members
double carrier_wave_angle
int last_symbol_end_filtered
double angle_delta
int samples_per_symbol
Function Documentation
SymbolRate()
double SymbolRate (PskSymbolRate rate)
References modulators::S1000, modulators::S125, modulators::S250, and modulators::S500.
Referenced by modulators::PskAscii().
addVaricode()
void addVaricode (BitStream & bit_stream, char c)
References BitStream::addBits(), and ascii_to_varicode.
Referenced by modulators::PskAscii().
addPreamble()
void addPreamble (BitStream & bit_stream, int preamble_length)
References BitStream::addBits().
Referenced by modulators::PskAscii().
addPostamble()
void addPostamble (BitStream & bit_stream, int postamble_length, PskMode mode)
References BitStream::addBits(), and modulators::QPSK.
Referenced by modulators::PskAscii().
addSymbol()
void addSymbol (WavGen & wavgen, PskWave & wave, double shift, int filter_end)
References WavGen::addSample(), PskWave::angle_delta, PskWave::carrier_wave_angle, PskWave::last_symbol_end_filtered, M_PI, and PskWave::samples_per_symbol.
Referenced by encodeBpsk(), and encodeQpsk().
encodeBpsk()
void encodeBpsk (WavGen & wavgen, BitStream & bit_stream, PskWave & wave)
References addSymbol(), M_PI, BitStream::peakNextBit(), and BitStream::popNextBit().
Referenced by modulators::PskAscii().
encodeQpsk()
void encodeQpsk (WavGen & wavgen, BitStream & bit_stream, PskWave & wave)
References addSymbol(), conv_code, and BitStream::popNextBit().
Referenced by modulators::PskAscii().