Giraffe: ubx.cpp File Reference
ubx.cpp File Reference
Initial implementation of the UBX protocol, in progress.
#include <unistd.h>
#include <chrono>
#include <thread>
#include <iostream>
#include <unordered_map>
#include <cstring>
#include "ubx.h"
Macros
#define MAX_BUFFER_SIZE 4000
#define MAX_PAYLOAD_SIZE 256
#define MESSAGE_RETRY_COUNT 5
#define MESSAGE_RETRY_TIME 200
#define READ_NEXT_MESSAGE_TIMEOUT 500
#define STREAM_REG 0xFF
#define STREAM_SIZE_LSB_REG 0xFE
#define STREAM_SIZE_MSB_REG 0xFD
#define UBX_ACK_NACK 0x00
#define UBX_SYNC_CHAR_1 0xB5
#define UBX_SYNC_CHAR_2 0x62
Functions
int16_t parseI2 (const uint8_t msb, const uint8_t lsb)
int32_t parseI4 (const uint8_t msb, const uint8_t mid_msb, const uint8_t mid_lsb, const uint8_t lsb)
uint16_t parseU2 (const uint8_t msb, const uint8_t lsb)
uint32_t parseU4 (const uint8_t msb, const uint8_t mid_msb, const uint8_t mid_lsb, const uint8_t lsb)
void wait (int ms)
Detailed Description
Initial implementation of the UBX protocol, in progress.
Author
Joshua Jerred (https://joshuajer.red/)
This is a work in progress, it is currently a bit of a mess as I test different methods of implementing this protocol.
The main issue right now is poor reliability of the electrical connection as a logic analyzer shows different behavior compared to what the Pi sees. Need a real scope for this one, not my hantek...
Version
0.3
Date
2023-01-06
Copyright
Copyright (c) 2023
Macro Definition Documentation
STREAM_SIZE_MSB_REG
#define STREAM_SIZE_MSB_REG 0xFD
STREAM_SIZE_LSB_REG
#define STREAM_SIZE_LSB_REG 0xFE
STREAM_REG
#define STREAM_REG 0xFF
UBX_SYNC_CHAR_1
#define UBX_SYNC_CHAR_1 0xB5
UBX_SYNC_CHAR_2
#define UBX_SYNC_CHAR_2 0x62
UBX_ACK_NACK
#define UBX_ACK_NACK 0x00
MESSAGE_RETRY_TIME
#define MESSAGE_RETRY_TIME 200
MESSAGE_RETRY_COUNT
#define MESSAGE_RETRY_COUNT 5
MAX_BUFFER_SIZE
#define MAX_BUFFER_SIZE 4000
MAX_PAYLOAD_SIZE
#define MAX_PAYLOAD_SIZE 256
READ_NEXT_MESSAGE_TIMEOUT
#define READ_NEXT_MESSAGE_TIMEOUT 500
Function Documentation
wait()
void wait (int ms) inline
Referenced by ubx::pollMessage().
parseU2()
uint16_t parseU2 (const uint8_t msb, const uint8_t lsb) inline
Referenced by ubx::parsePVT().
parseU4()
uint32_t parseU4 (const uint8_t msb, const uint8_t mid_msb, const uint8_t mid_lsb, const uint8_t lsb) inline
Referenced by ubx::parsePVT().
parseI2()
int16_t parseI2 (const uint8_t msb, const uint8_t lsb) inline
parseI4()
int32_t parseI4 (const uint8_t msb, const uint8_t mid_msb, const uint8_t mid_lsb, const uint8_t lsb) inline
Referenced by ubx::parsePVT().