/**
 * =*========GIRAFFE========*=
 * A Unified Flight Command and Control System
 * https://github.com/joshua-jerred/Giraffe
 * https://giraffe.joshuajer.red/
 * =*=======================*=
 *
 * @file   version.js
 * @brief  Software version information
 * =*=======================*=
 * @author     Joshua Jerred (https://joshuajer.red)
 * @copyright  2023 (license to be defined)
 */

/// @warning This file is autogenerated and should not be edited directly.

module.exports = {
  version: '0.5.8',
  stage: "development",
  build_date: "2024-01-19",
  build_time: "16:10:29",
  git_hash: "b6f9f596",
  git_branch: "176-aprs-experimental-packet-in-gdl",
  git_commit_count: "696",
  git_repo: "github.com/joshua-jerred/Giraffe",
};

/// @warning This file is autogenerated and should not be edited directly.
