name: Doxygen Validation

on: 
  - workflow_dispatch
  - pull_request

jobs:
  doxygex:
    name: Doxygen Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Doxygen
        run: sudo apt-get install doxygen
      - name: Generate Doxygen
        run: doxygen ./docs/Doxygen/Doxyfile_no_output