name: giraffe-flight-software tests

on: [push]

jobs:

  pull:
    name: Pull code to runner
    runs-on: self-hosted
    steps:
      - uses: actions/checkout/@v3

  build:
    name: Build giraffe-flight-software
    runs-on: self-hosted
    needs: [pull]
    steps:
    - name: CMake configure
      run: mkdir build && cd build && cmake ..
    - name: make
      run: cd build && make giraffe-flight-software

  test-01:
    name: test-01 (Configuration Module)
    runs-on: self-hosted
    needs: [build]
    steps:
    - name: build
      run: cd build && make test-01
    - name: run test
      run: cd build/bin/tests/test-01 && ./test-01

