name: giraffe-flight-software tests

on: [push]

jobs:

  pull:
    name: Pull code to runner
    runs-on: self-hosted
    steps:
      - uses: actions/checkout/@v3

  build:
    name: Build giraffe-flight-software
    runs-on: self-hosted
    needs: [pull]
    steps:
    - name: CMake configure
      run: mkdir build && cd build && cmake ..
    - name: make
      run: cd build && make giraffe-flight-software

  test-01:
    name: test-01 (Data Stream)
    runs-on: self-hosted
    needs: [build]
    steps:
    - name: build
      run: cd build && make test-01
    - name: run test
      run: cd build/bin/tests/test-01 && ./test-01

  test-02:
    name: test-02 (Configuration Module)
    runs-on: self-hosted
    needs: [build]
    steps:
    - name: build
      run: cd build && make test-02
    - name: run test
      run: cd build/bin/tests/test-02 && ./test-02

  test-03:
    name: test-03 (Data Module)
    runs-on: self-hosted
    needs: [build]
    steps:
    - name: build
      run: cd build && make test-03
    - name: run test
      run: cd build/bin/tests/test-03 && ./test-03

  test-04:
    name: test-04 (Extensions Module)
    runs-on: self-hosted
    needs: [build]
    steps:
    - name: build
      run: cd build && make test-04
    - name: run test
      run: cd build/bin/tests/test-04 && ./test-04