name: GFS Unit Tests

on:
  push:
    paths:
      - workflows/**
      - src/flight_software/**
  pull_request:

env:
  BUILD_TEST: "cd build && make -j4 -o2"
  RUN_TEST: "./build/tests/flight_software"

jobs:
  pull:
    name: Pull and Sync Submodules
    runs-on: self-hosted
    steps:
      - uses: actions/checkout/@v3
        with:
          submodules: recursive

  configure:
    name: Configure with CMake
    needs: ['pull']
    runs-on: self-hosted
    steps:
    - name: Configure
      run: mkdir build && cd build && cmake ..

  test-01:
    name: 01 - Configuration
    needs: ['configure']
    runs-on: self-hosted
    steps:
    - name: Build Test
      run: $BUILD_TEST 01_configuration
    - name: Run Test
      run: $RUN_TEST/01_configuration