name: GFS Unit Tests

on:
  push:
    paths:
      - src/flight_software/**
  pull_request:

env:
  MAKE_OPTIMIZATION: "-j4 -o2"

jobs:
  pull:
    name: Pull and Sync Submodules
    runs-on: self-hosted
    steps:
      - uses: actions/checkout/@v3
        with:
          submodules: recursive

  configure:
    name: Configure with CMake
    needs: ['pull']
    runs-on: self-hosted
    steps:
    - name: Configure
      run: mkdir build && cd build && cmake ..


  