name: giraffe-flight-software tests
on:
  push:
    branches:
      - 0.5.0-development
  pull_request:
    branches:
      - master

jobs:
  pull_and_configure:
    name: Pull and Configure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout/@v3
      - name: Configure
        run: mkdir build && cd build && cmake ..