name: giraffe-flight-software tests
on:
  push:
    branches:
      - 0.5.0-development
  pull_request:
    branches:
      - master

jobs:
  pull:
    name: Pull and Sync Submodules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout/@v3
        with:
          submodules: recursive

  configure:
    name: Configure with CMake
    runs-on: ubuntu-latest
    steps:
    - name: Configure
      run: mkdir build && cd build && cmake ..