name: Giraffe CI

on:
   pull_request:
    branches: [ main ]

jobs:
  cpp_ci:
    name: Giraffe C++ CI
    runs-on: ubuntu-latest
    container: joshuajerred/giraffe:latest
    steps:
      - uses: actions/checkout/@v3
        with:
          submodules: recursive
      - name: Install Dependencies
        run: sudo apt-get install
          build-essential
          cmake
          libgtest-dev
          libcurl4-gnutls-dev
          nlohmann-json3-dev
          libi2c-dev
          -y
      - name: CMake Configure
        run: mkdir build -p && cd build && cmake ..
      - name: Build / Giraffe Flight System
        run: cd build && make giraffe_flight_system
      - name: Build / Giraffe Data Link
        run: cd build && make giraffe_data_link
      - name: Build / Unit Test Common
        run: cd build && make unit_test_common
      - name: Unit Test / Common
        run: cd build/bin/tests/common && ./unit_test_common
      - name: Build / Unit Test Flight System
        run: cd build && make unit_test_gfs
      - name: Unit Test / Flight System
        run: cd build/bin/tests/flight_system && ./unit_test_gfs
      - name: Build / Unit Test Data Link
        run: cd build && make unit_test_gdl
      - name: Unit Test / Data Link
        run: cd build/bin/tests/data_link && ./unit_test_gdl

  js_ci:
    name: Giraffe JS CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm install
        name: npm install / common
        working-directory: ./src/common/protocol
      - run: npm test
        name: npm test / common
        working-directory: ./src/common/protocol
      - run: npm install
        name: npm install / ground_station
        working-directory: ./src/ground_station
      - run: npm test
        name: npm test / ground_station
        working-directory: ./src/ground_station
      - run: npm install
        name: npm install / web_client
        working-directory: ./src/web_client
      - run: npm test
        name: npm test / web_client
        working-directory: ./src/web_client

  doxygen:
    name: Doxygen/Structurizr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Doxygen
        run: sudo apt-get install doxygen graphviz -y && mkdir build && mkdir build/dox
      - name: Generate Structurizr PlantUML SVGs
        run: bash project/generate_uml.sh
      - name: Build Doxygen
        run: doxygen project/doxygen/Doxyfile
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/dox/html

  cmake-lint:
    name: static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout/@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: pip install cmakelint
      - name: cmake-lint
        run: cmakelint --config=./project/cmakelintrc