name: Giraffe Static Analysis

on:
  pull_request:
   branches: [ main ]

jobs:
  setup:
    name: cmake-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout/@v3
        with:
          submodules: recursive
      - name: Install cmake-lint
        run: pip install cmakelint
      - name: Run cmake-lint
        run: cmakelint --config=./project/cmakelintrc
