name: Giraffe Static Analysis

on:
  pull_request:
   branches: [ main ]

jobs:
  setup:
    name: cmake-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout/@v3
        with:
          submodules: recursive
      - name: Configure
        run: mkdir build && cd build && cmake ..

  common_tests_cpp:
    name: Unit Tests / Common C++
    needs: ["setup"]
    runs-on: self-hosted
    steps:
      - name: Build Test
        run: cd build && make unit_test_common
      - name: Run Test
        run: cd build/bin/tests/common && ./unit_test_common
