name: GFS Unit Tests

on:
  push:
    branches: ["main", "0.5.0-development"]
    #paths: ['workflows/**', 'src/flight_software/**']
  pull_request:
    branches: ["main"]
 
jobs:
  setup-pull:
    name: Pull and Sync Submodules
    runs-on: self-hosted
    steps:
      - uses: actions/checkout/@v3
        with:
          submodules: recursive

  cmake_configure:
    name: CMake Configure
    needs: ["setup-pull"]
    runs-on: self-hosted
    steps:
      - name: Configure
        run: mkdir build && cd build && cmake ..

  common_tests:
    name: Unit Tests / Common
    needs: ["cmake_configure"]
    runs-on: self-hosted
    steps:
      - name: Build Test
        run: cd build && make unit_test_common
      - name: Run Test
        run: cd build/tests/common && ./unit_test_common

  gfs_tests:
    name: Unit Tests / Flight Software
    env:
      TEST_NAME: "common_02_giraffe_protocol"
    needs: ["common_tests"]
    runs-on: self-hosted
    steps:
      - name: Build Test
        run: cd build && make unit_test_common
      - name: Run Test
        run: cd build/tests/common && ./unit_test_gfs