name: Giraffe Unit Tests

on:
   pull_request:
    branches: [ main ]
   push:
    branches-ignore: [ gh-pages-doxygen ]
 
jobs:
  setup-pull:
    name: Pull and Sync Submodules
    runs-on: self-hosted
    steps:
      - uses: actions/checkout/@v3
        with:
          submodules: recursive

  cmake_configure:
    name: CMake Configure
    needs: ["setup-pull"]
    runs-on: self-hosted
    steps:
      - name: Configure
        run: mkdir build && cd build && cmake ..

  common_tests:
    name: Unit Tests / Common
    needs: ["cmake_configure"]
    runs-on: self-hosted
    steps:
      - name: Build Test
        run: cd build && make unit_test_common
      - name: Run Test
        run: cd build/bin/tests/common && ./unit_test_common

  gfs_tests:
    name: Unit Tests / Giraffe Flight System
    needs: ["common_tests"]
    runs-on: self-hosted
    steps:
      - name: Build Test
        run: cd build && make unit_test_gfs
      - name: Run Test
        run: cd build/bin/tests/flight_system && ./unit_test_gfs