name: GFS Unit Tests

on:
  push:
    branches: ['main', '0.5.0-development']
    #paths: ['workflows/**', 'src/flight_software/**']
  pull_request:
    branches: ['main']

env:
  BUILD_TEST: ./tests/flight_software/build_test.sh
  RUN_TEST: ./tests/flight_software/run_test.sh

jobs:
  pull:
    name: Pull and Sync Submodules
    runs-on: self-hosted
    steps:
      - uses: actions/checkout/@v3
        with:
          submodules: recursive

  configure:
    name: Configure with CMake
    needs: ['pull']
    runs-on: self-hosted
    steps:
    - name: Configure
      run: mkdir build && cd build && cmake ..

  test-01:
    name: 01 - Configuration
    env:
      TEST_NAME: '01_configuration'
    needs: ['configure']
    runs-on: self-hosted
    steps:
    - name: Build Test
      run: $BUILD_TEST
    - name: Run Test
      run: $RUN_TEST