name: GFS Unit Tests

on:
  push:
    branches: ["main", "0.5.0-development"]
    #paths: ['workflows/**', 'src/flight_software/**']
  pull_request:
    branches: ["main"]

env:
  GFS_BUILD: ./src/flight_software/tests/build_test.sh
  GFS_RUN: ./src/flight_software/tests/run_test.sh
  COMMON_BUILD: ./src/common/tests/build_test.sh
  COMMON_RUN: ./src/common/tests/run_test.sh

jobs:
  setup-pull:
    name: Pull and Sync Submodules
    runs-on: self-hosted
    steps:
      - uses: actions/checkout/@v3
        with:
          submodules: recursive

  cmake_configure:
    name: CMake Configure
    needs: ["setup-pull"]
    runs-on: self-hosted
    steps:
      - name: Configure
        run: mkdir build && cd build && cmake ..

  common_test_01:
    name: Common / GFS Configuration Scheme
    env:
      TEST_NAME: "common_01_gfs_configuration_scheme"
    needs: ["cmake_configure"]
    runs-on: self-hosted
    steps:
      - name: Build Test
        run: $COMMON_BUILD
      - name: Run Test
        run: $COMMON_RUN

  common_test_02:
    name: Common / Giraffe Protocol
    env:
      TEST_NAME: "common_02_giraffe_protocol"
    needs: ["cmake_configure"]
    runs-on: self-hosted
    steps:
      - name: Build Test
        run: $COMMON_BUILD
      - name: Run Test
        run: $COMMON_RUN

  gfs_test_01:
    name: GFS / Configuration
    env:
      TEST_NAME: "gfs_01_configuration"
      TEST_ID: "test_01"
    needs: ["cmake_configure"]
    runs-on: self-hosted
    steps:
      - name: Build Test
        run: $GFS_BUILD
      - name: Run Test
        run: $GFS_RUN

  gfs-test-05:
    name: GFS / Exception
    env:
      TEST_NAME: "gfs_02_gfs_exception"
      TEST_ID: "test_02"
    needs: ["cmake_configure"]
    runs-on: self-hosted
    steps:
      - name: Build Test
        run: $GFS_BUILD
      - name: Run Test
        run: $GFS_RUN

  gfs_test_06:
    name: GFS / Stream
    env:
      TEST_NAME: "gfs_03_data_error_stream"
      TEST_ID: "test_03"
    needs: ["cmake_configure"]
    runs-on: self-hosted
    steps:
      - name: Build Test
        run: $GFS_BUILD
      - name: Run Test
        run: $GFS_RUN

  gfs_test_04:
    name: GFS / Module Base
    env:
      TEST_NAME: "gfs_04_module"
      TEST_ID: "test_04"
    needs: ["gfs_test_06"]
    runs-on: self-hosted
    steps:
      - name: Build Test
        run: $GFS_BUILD
      - name: Run Test
        run: $GFS_RUN