name: GFS Unit Tests

on:
  push:
    branches: ['main', '0.5.0-development']
    #paths: ['workflows/**', 'src/flight_software/**']
  pull_request:
    branches: ['main']

env:
  GFS_BUILD: ./src/flight_software/tests/build_test.sh
  GFS_RUN: ./src/flight_software/tests/run_test.sh
  COMMON_BUILD: ./src/common/tests/build_test.sh
  COMMON_RUN: ./src/common/tests/run_test.sh

jobs:
  pull:
    name: Pull and Sync Submodules
    runs-on: self-hosted
    steps:
      - uses: actions/checkout/@v3
        with:
          submodules: recursive

  configure:
    name: Configure
    needs: ['pull']
    runs-on: self-hosted
    steps:
    - name: Configure
      run: mkdir build && cd build && cmake ..

  test-01:
    name: Common / Configuration Scheme
    env:
      TEST_NAME: 'common_01_configuration_scheme'
    needs: ['configure']
    runs-on: self-hosted
    steps:
    - name: Build Test
      run: $COMMON_BUILD
    - name: Run Test
      run: $COMMON_RUN